//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_SENSOR-NATIVE_H__
#define __TCT_SENSOR-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_system_sensor_basic_startup(void);
extern void utc_system_sensor_basic_cleanup(void);
extern void utc_system_sensor_recorder_startup(void);
extern void utc_system_sensor_recorder_cleanup(void);
extern void utc_system_sensor_provider_startup(void);
extern void utc_system_sensor_provider_cleanup(void);
extern void utc_system_sensor_util_startup(void);

extern int utc_system_sensor_get_default_sensor_p(void);
extern int utc_system_sensor_get_default_sensor_n(void);
extern int utc_system_sensor_get_default_sensor_by_uri_p(void);
extern int utc_system_sensor_get_default_sensor_by_uri_n(void);
extern int utc_system_sensor_get_sensor_list_p(void);
extern int utc_system_sensor_get_sensor_list_n(void);
extern int utc_system_sensor_get_sensor_list_by_uri_p(void);
extern int utc_system_sensor_get_sensor_list_by_uri_n(void);
extern int utc_system_sensor_is_wake_up_p(void);
extern int utc_system_sensor_is_wake_up_n(void);
extern int utc_system_sensor_create_listener_p(void);
extern int utc_system_sensor_create_listener_n(void);
extern int utc_system_sensor_destroy_listener_p(void);
extern int utc_system_sensor_destroy_listener_n(void);
extern int utc_system_sensor_listener_start_p(void);
extern int utc_system_sensor_listener_start_n(void);
extern int utc_system_sensor_listener_stop_p(void);
extern int utc_system_sensor_listener_stop_n(void);
extern int utc_system_sensor_listener_set_event_cb_p(void);
extern int utc_system_sensor_listener_set_event_cb_n(void);
extern int utc_system_sensor_listener_unset_event_cb_p(void);
extern int utc_system_sensor_listener_unset_event_cb_n(void);
extern int utc_system_sensor_listener_set_events_cb_p(void);
extern int utc_system_sensor_listener_set_events_cb_n(void);
extern int utc_system_sensor_listener_unset_events_cb_p(void);
extern int utc_system_sensor_listener_unset_events_cb_n(void);
extern int utc_system_sensor_listener_set_accuracy_cb_p(void);
extern int utc_system_sensor_listener_set_accuracy_cb_n(void);
extern int utc_system_sensor_listener_unset_accuracy_cb_p(void);
extern int utc_system_sensor_listener_unset_accuracy_cb_n(void);
extern int utc_system_sensor_listener_read_data_p(void);
extern int utc_system_sensor_listener_read_data_n(void);
extern int utc_system_sensor_listener_set_interval_p(void);
extern int utc_system_sensor_listener_set_interval_n(void);
extern int utc_system_sensor_listener_set_max_batch_latency_p(void);
extern int utc_system_sensor_listener_set_max_batch_latency_n(void);
extern int utc_system_sensor_listener_set_attribute_int_p(void);
extern int utc_system_sensor_listener_set_attribute_int_n(void);
extern int utc_system_sensor_listener_read_data_list_p(void);
extern int utc_system_sensor_listener_read_data_list_n(void);
extern int utc_system_sensor_listener_flush_p(void);
extern int utc_system_sensor_listener_flush_n(void);
extern int utc_system_sensor_get_uri_p(void);
extern int utc_system_sensor_get_uri_n(void);
extern int utc_system_sensor_get_name_p(void);
extern int utc_system_sensor_get_name_n(void);
extern int utc_system_sensor_get_vendor_p(void);
extern int utc_system_sensor_get_vendor_n(void);
extern int utc_system_sensor_get_type_p(void);
extern int utc_system_sensor_get_type_n(void);
extern int utc_system_sensor_get_min_range_p(void);
extern int utc_system_sensor_get_min_range_n(void);
extern int utc_system_sensor_get_max_range_p(void);
extern int utc_system_sensor_get_max_range_n(void);
extern int utc_system_sensor_get_resolution_p(void);
extern int utc_system_sensor_get_resolution_n(void);
extern int utc_system_sensor_get_min_interval_p(void);
extern int utc_system_sensor_get_min_interval_n(void);
extern int utc_system_sensor_get_fifo_count_p(void);
extern int utc_system_sensor_get_fifo_count_n(void);
extern int utc_system_sensor_get_max_batch_count_p(void);
extern int utc_system_sensor_get_max_batch_count_n(void);
extern int utc_system_sensor_listener_set_option_p(void);
extern int utc_system_sensor_listener_set_option_n(void);
extern int utc_system_sensor_is_supported_p(void);
extern int utc_system_sensor_is_supported_n(void);
extern int utc_system_sensor_is_supported_by_uri_p(void);
extern int utc_system_sensor_is_supported_by_uri_n(void);
extern int utc_system_sensor_recorder_is_supported_p(void);
extern int utc_system_sensor_recorder_is_supported_n(void);
extern int utc_system_sensor_recorder_start_p(void);
extern int utc_system_sensor_recorder_start_n(void);
extern int utc_system_sensor_recorder_stop_p(void);
extern int utc_system_sensor_recorder_stop_n(void);
extern int utc_system_sensor_recorder_create_option_p(void);
extern int utc_system_sensor_recorder_create_option_n(void);
extern int utc_system_sensor_recorder_destroy_option_p(void);
extern int utc_system_sensor_recorder_destroy_option_n(void);
extern int utc_system_sensor_recorder_option_set_int_p(void);
extern int utc_system_sensor_recorder_option_set_int_n(void);
extern int utc_system_sensor_recorder_create_query_p(void);
extern int utc_system_sensor_recorder_create_query_n(void);
extern int utc_system_sensor_recorder_destroy_query_p(void);
extern int utc_system_sensor_recorder_destroy_query_n(void);
extern int utc_system_sensor_recorder_query_set_int_p(void);
extern int utc_system_sensor_recorder_query_set_int_n(void);
extern int utc_system_sensor_recorder_query_set_time_p(void);
extern int utc_system_sensor_recorder_query_set_time_n(void);
extern int utc_system_sensor_recorder_read_p(void);
extern int utc_system_sensor_recorder_read_n(void);
extern int utc_system_sensor_recorder_read_sync_p(void);
extern int utc_system_sensor_recorder_read_sync_n(void);
extern int utc_system_sensor_recorder_data_get_time_p(void);
extern int utc_system_sensor_recorder_data_get_time_n(void);
extern int utc_system_sensor_recorder_data_get_int_p(void);
extern int utc_system_sensor_recorder_data_get_int_n(void);
extern int utc_system_sensor_recorder_data_get_double_p(void);
extern int utc_system_sensor_recorder_data_get_double_n(void);
extern int utc_system_sensor_create_provider_p(void);
extern int utc_system_sensor_create_provider_n(void);
extern int utc_system_sensor_destroy_provider_p(void);
extern int utc_system_sensor_destroy_provider_n(void);
extern int utc_system_sensor_add_provider_p(void);
extern int utc_system_sensor_add_provider_n(void);
extern int utc_system_sensor_remove_provider_p(void);
extern int utc_system_sensor_remove_provider_n(void);
extern int utc_system_sensor_add_sensor_added_cb_p(void);
extern int utc_system_sensor_add_sensor_added_cb_n(void);
extern int utc_system_sensor_remove_sensor_added_cb_p(void);
extern int utc_system_sensor_remove_sensor_added_cb_n(void);
extern int utc_system_sensor_add_sensor_removed_cb_p(void);
extern int utc_system_sensor_add_sensor_removed_cb_n(void);
extern int utc_system_sensor_remove_sensor_removed_cb_p(void);
extern int utc_system_sensor_remove_sensor_removed_cb_n(void);
extern int utc_system_sensor_provider_set_name_p(void);
extern int utc_system_sensor_provider_set_name_n(void);
extern int utc_system_sensor_provider_set_vendor_p(void);
extern int utc_system_sensor_provider_set_vendor_n(void);
extern int utc_system_sensor_provider_set_range_p(void);
extern int utc_system_sensor_provider_set_range_n(void);
extern int utc_system_sensor_provider_set_resolution_p(void);
extern int utc_system_sensor_provider_set_resolution_n(void);
extern int utc_system_sensor_provider_set_start_cb_p(void);
extern int utc_system_sensor_provider_set_start_cb_n(void);
extern int utc_system_sensor_provider_set_stop_cb_p(void);
extern int utc_system_sensor_provider_set_stop_cb_n(void);
extern int utc_system_sensor_provider_set_interval_changed_cb_p(void);
extern int utc_system_sensor_provider_set_interval_changed_cb_n(void);
extern int utc_system_sensor_provider_publish_p(void);
extern int utc_system_sensor_provider_publish_n(void);
extern int utc_system_sensor_provider_publish_events_p(void);
extern int utc_system_sensor_provider_publish_events_n(void);
extern int utc_system_sensor_util_get_angle_change_p(void);
extern int utc_system_sensor_util_get_angle_change_n(void);
extern int utc_system_sensor_util_get_declination_p(void);
extern int utc_system_sensor_util_get_declination_n(void);
extern int utc_system_sensor_util_get_inclination_p(void);
extern int utc_system_sensor_util_get_inclination_n(void);
extern int utc_system_sensor_util_get_orientation_p(void);
extern int utc_system_sensor_util_get_orientation_n(void);
extern int utc_system_sensor_util_get_rotation_matrix_p(void);
extern int utc_system_sensor_util_get_rotation_matrix_n(void);
extern int utc_system_sensor_util_get_rotation_matrix_from_vector_p(void);
extern int utc_system_sensor_util_get_rotation_matrix_from_vector_n(void);
extern int utc_system_sensor_util_remap_coordinate_system_p(void);
extern int utc_system_sensor_util_remap_coordinate_system_n(void);

testcase tc_array[] = {
	{"utc_system_sensor_get_default_sensor_p",utc_system_sensor_get_default_sensor_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_default_sensor_n",utc_system_sensor_get_default_sensor_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_default_sensor_by_uri_p",utc_system_sensor_get_default_sensor_by_uri_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_default_sensor_by_uri_n",utc_system_sensor_get_default_sensor_by_uri_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_sensor_list_p",utc_system_sensor_get_sensor_list_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_sensor_list_n",utc_system_sensor_get_sensor_list_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_sensor_list_by_uri_p",utc_system_sensor_get_sensor_list_by_uri_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_sensor_list_by_uri_n",utc_system_sensor_get_sensor_list_by_uri_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_wake_up_p",utc_system_sensor_is_wake_up_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_wake_up_n",utc_system_sensor_is_wake_up_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_create_listener_p",utc_system_sensor_create_listener_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_create_listener_n",utc_system_sensor_create_listener_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_destroy_listener_p",utc_system_sensor_destroy_listener_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_destroy_listener_n",utc_system_sensor_destroy_listener_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_start_p",utc_system_sensor_listener_start_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_start_n",utc_system_sensor_listener_start_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_stop_p",utc_system_sensor_listener_stop_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_stop_n",utc_system_sensor_listener_stop_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_event_cb_p",utc_system_sensor_listener_set_event_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_event_cb_n",utc_system_sensor_listener_set_event_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_event_cb_p",utc_system_sensor_listener_unset_event_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_event_cb_n",utc_system_sensor_listener_unset_event_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_events_cb_p",utc_system_sensor_listener_set_events_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_events_cb_n",utc_system_sensor_listener_set_events_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_events_cb_p",utc_system_sensor_listener_unset_events_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_events_cb_n",utc_system_sensor_listener_unset_events_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_accuracy_cb_p",utc_system_sensor_listener_set_accuracy_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_accuracy_cb_n",utc_system_sensor_listener_set_accuracy_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_accuracy_cb_p",utc_system_sensor_listener_unset_accuracy_cb_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_unset_accuracy_cb_n",utc_system_sensor_listener_unset_accuracy_cb_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_read_data_p",utc_system_sensor_listener_read_data_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_read_data_n",utc_system_sensor_listener_read_data_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_interval_p",utc_system_sensor_listener_set_interval_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_interval_n",utc_system_sensor_listener_set_interval_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_max_batch_latency_p",utc_system_sensor_listener_set_max_batch_latency_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_max_batch_latency_n",utc_system_sensor_listener_set_max_batch_latency_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_attribute_int_p",utc_system_sensor_listener_set_attribute_int_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_attribute_int_n",utc_system_sensor_listener_set_attribute_int_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_read_data_list_p",utc_system_sensor_listener_read_data_list_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_read_data_list_n",utc_system_sensor_listener_read_data_list_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_flush_p",utc_system_sensor_listener_flush_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_flush_n",utc_system_sensor_listener_flush_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_uri_p",utc_system_sensor_get_uri_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_uri_n",utc_system_sensor_get_uri_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_name_p",utc_system_sensor_get_name_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_name_n",utc_system_sensor_get_name_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_vendor_p",utc_system_sensor_get_vendor_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_vendor_n",utc_system_sensor_get_vendor_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_type_p",utc_system_sensor_get_type_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_type_n",utc_system_sensor_get_type_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_min_range_p",utc_system_sensor_get_min_range_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_min_range_n",utc_system_sensor_get_min_range_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_max_range_p",utc_system_sensor_get_max_range_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_max_range_n",utc_system_sensor_get_max_range_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_resolution_p",utc_system_sensor_get_resolution_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_resolution_n",utc_system_sensor_get_resolution_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_min_interval_p",utc_system_sensor_get_min_interval_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_min_interval_n",utc_system_sensor_get_min_interval_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_fifo_count_p",utc_system_sensor_get_fifo_count_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_fifo_count_n",utc_system_sensor_get_fifo_count_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_max_batch_count_p",utc_system_sensor_get_max_batch_count_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_get_max_batch_count_n",utc_system_sensor_get_max_batch_count_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_option_p",utc_system_sensor_listener_set_option_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_listener_set_option_n",utc_system_sensor_listener_set_option_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_supported_p",utc_system_sensor_is_supported_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_supported_n",utc_system_sensor_is_supported_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_supported_by_uri_p",utc_system_sensor_is_supported_by_uri_p,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_is_supported_by_uri_n",utc_system_sensor_is_supported_by_uri_n,utc_system_sensor_basic_startup,utc_system_sensor_basic_cleanup},
	{"utc_system_sensor_recorder_is_supported_p",utc_system_sensor_recorder_is_supported_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_is_supported_n",utc_system_sensor_recorder_is_supported_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_start_p",utc_system_sensor_recorder_start_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_start_n",utc_system_sensor_recorder_start_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_stop_p",utc_system_sensor_recorder_stop_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_stop_n",utc_system_sensor_recorder_stop_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_create_option_p",utc_system_sensor_recorder_create_option_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_create_option_n",utc_system_sensor_recorder_create_option_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_destroy_option_p",utc_system_sensor_recorder_destroy_option_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_destroy_option_n",utc_system_sensor_recorder_destroy_option_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_option_set_int_p",utc_system_sensor_recorder_option_set_int_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_option_set_int_n",utc_system_sensor_recorder_option_set_int_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_create_query_p",utc_system_sensor_recorder_create_query_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_create_query_n",utc_system_sensor_recorder_create_query_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_destroy_query_p",utc_system_sensor_recorder_destroy_query_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_destroy_query_n",utc_system_sensor_recorder_destroy_query_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_query_set_int_p",utc_system_sensor_recorder_query_set_int_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_query_set_int_n",utc_system_sensor_recorder_query_set_int_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_query_set_time_p",utc_system_sensor_recorder_query_set_time_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_query_set_time_n",utc_system_sensor_recorder_query_set_time_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_read_p",utc_system_sensor_recorder_read_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_read_n",utc_system_sensor_recorder_read_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_read_sync_p",utc_system_sensor_recorder_read_sync_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_read_sync_n",utc_system_sensor_recorder_read_sync_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_time_p",utc_system_sensor_recorder_data_get_time_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_time_n",utc_system_sensor_recorder_data_get_time_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_int_p",utc_system_sensor_recorder_data_get_int_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_int_n",utc_system_sensor_recorder_data_get_int_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_double_p",utc_system_sensor_recorder_data_get_double_p,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_recorder_data_get_double_n",utc_system_sensor_recorder_data_get_double_n,utc_system_sensor_recorder_startup,utc_system_sensor_recorder_cleanup},
	{"utc_system_sensor_create_provider_p",utc_system_sensor_create_provider_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_create_provider_n",utc_system_sensor_create_provider_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_destroy_provider_p",utc_system_sensor_destroy_provider_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_destroy_provider_n",utc_system_sensor_destroy_provider_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_provider_p",utc_system_sensor_add_provider_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_provider_n",utc_system_sensor_add_provider_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_provider_p",utc_system_sensor_remove_provider_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_provider_n",utc_system_sensor_remove_provider_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_sensor_added_cb_p",utc_system_sensor_add_sensor_added_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_sensor_added_cb_n",utc_system_sensor_add_sensor_added_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_sensor_added_cb_p",utc_system_sensor_remove_sensor_added_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_sensor_added_cb_n",utc_system_sensor_remove_sensor_added_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_sensor_removed_cb_p",utc_system_sensor_add_sensor_removed_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_add_sensor_removed_cb_n",utc_system_sensor_add_sensor_removed_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_sensor_removed_cb_p",utc_system_sensor_remove_sensor_removed_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_remove_sensor_removed_cb_n",utc_system_sensor_remove_sensor_removed_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_name_p",utc_system_sensor_provider_set_name_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_name_n",utc_system_sensor_provider_set_name_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_vendor_p",utc_system_sensor_provider_set_vendor_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_vendor_n",utc_system_sensor_provider_set_vendor_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_range_p",utc_system_sensor_provider_set_range_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_range_n",utc_system_sensor_provider_set_range_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_resolution_p",utc_system_sensor_provider_set_resolution_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_resolution_n",utc_system_sensor_provider_set_resolution_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_start_cb_p",utc_system_sensor_provider_set_start_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_start_cb_n",utc_system_sensor_provider_set_start_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_stop_cb_p",utc_system_sensor_provider_set_stop_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_stop_cb_n",utc_system_sensor_provider_set_stop_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_interval_changed_cb_p",utc_system_sensor_provider_set_interval_changed_cb_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_set_interval_changed_cb_n",utc_system_sensor_provider_set_interval_changed_cb_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_publish_p",utc_system_sensor_provider_publish_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_publish_n",utc_system_sensor_provider_publish_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_publish_events_p",utc_system_sensor_provider_publish_events_p,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_provider_publish_events_n",utc_system_sensor_provider_publish_events_n,utc_system_sensor_provider_startup,utc_system_sensor_provider_cleanup},
	{"utc_system_sensor_util_get_angle_change_p",utc_system_sensor_util_get_angle_change_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_angle_change_n",utc_system_sensor_util_get_angle_change_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_declination_p",utc_system_sensor_util_get_declination_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_declination_n",utc_system_sensor_util_get_declination_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_inclination_p",utc_system_sensor_util_get_inclination_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_inclination_n",utc_system_sensor_util_get_inclination_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_orientation_p",utc_system_sensor_util_get_orientation_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_orientation_n",utc_system_sensor_util_get_orientation_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_rotation_matrix_p",utc_system_sensor_util_get_rotation_matrix_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_rotation_matrix_n",utc_system_sensor_util_get_rotation_matrix_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_rotation_matrix_from_vector_p",utc_system_sensor_util_get_rotation_matrix_from_vector_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_get_rotation_matrix_from_vector_n",utc_system_sensor_util_get_rotation_matrix_from_vector_n,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_remap_coordinate_system_p",utc_system_sensor_util_remap_coordinate_system_p,utc_system_sensor_util_startup,NULL},
	{"utc_system_sensor_util_remap_coordinate_system_n",utc_system_sensor_util_remap_coordinate_system_n,utc_system_sensor_util_startup,NULL},
	{NULL, NULL}
};

#endif // __TCT_SENSOR-NATIVE_H__
