//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_IOTCON-NATIVE_H__
#define __TCT_IOTCON-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_iotcon_lite_resource_startup(void);
extern void ITs_iotcon_lite_resource_cleanup(void);
extern void ITs_iotcon_representation_startup(void);
extern void ITs_iotcon_representation_cleanup(void);
extern void ITs_iotcon_startup(void);
extern void ITs_iotcon_cleanup(void);
extern void ITs_iotcon_device_startup(void);
extern void ITs_iotcon_device_cleanup(void);
extern void ITs_iotcon_observers_startup(void);
extern void ITs_iotcon_observers_cleanup(void);
extern void ITs_iotcon_query_startup(void);
extern void ITs_iotcon_query_cleanup(void);
extern void ITs_iotcon_attributes_startup(void);
extern void ITs_iotcon_attributes_cleanup(void);
extern void ITs_iotcon_list_startup(void);
extern void ITs_iotcon_list_cleanup(void);
extern void ITs_iotcon_options_startup(void);
extern void ITs_iotcon_options_cleanup(void);
extern void ITs_iotcon_remote_resource_startup(void);
extern void ITs_iotcon_remote_resource_cleanup(void);
extern void ITs_iotcon_response_startup(void);
extern void ITs_iotcon_response_cleanup(void);
extern void ITs_iotcon_request_startup(void);
extern void ITs_iotcon_request_cleanup(void);
extern void ITs_iotcon_resource_startup(void);
extern void ITs_iotcon_resource_cleanup(void);
extern void ITs_iotcon_presence_startup(void);
extern void ITs_iotcon_presence_cleanup(void);
extern void ITs_iotcon_presence_response_startup(void);
extern void ITs_iotcon_presence_response_cleanup(void);
extern void ITs_iotcon_service_startup(void);
extern void ITs_iotcon_service_cleanup(void);

extern int ITc_iotcon_lite_resource_create_destroy_p(void);
extern int ITc_iotcon_lite_resource_update_attributes_p(void);
extern int ITc_iotcon_lite_resource_get_attributes_p(void);
extern int ITc_iotcon_representation_create_destroy_p(void);
extern int ITc_iotcon_representation_clone_p(void);
extern int ITc_iotcon_representation_set_get_uri_path_p(void);
extern int ITc_iotcon_representation_set_get_resource_types_p(void);
extern int ITc_iotcon_representation_set_get_resource_interfaces_p(void);
extern int ITc_iotcon_representation_set_get_attributes_p(void);
extern int ITc_iotcon_representation_add_remove_child_p(void);
extern int ITc_iotcon_representation_foreach_children_p(void);
extern int ITc_iotcon_representation_get_child_count_p(void);
extern int ITc_iotcon_representation_get_nth_child_p(void);
extern int ITc_iotcon_set_get_timeout_p(void);
extern int ITc_iotcon_set_device_name_p(void);
extern int ITc_iotcon_find_device_info_p(void);
extern int ITc_iotcon_device_info_get_property_p(void);
extern int ITc_iotcon_find_platform_info_p(void);
extern int ITc_iotcon_platform_info_get_property_p(void);
extern int ITc_iotcon_observers_create_destroy_p(void);
extern int ITc_iotcon_observers_add_remove_p(void);
extern int ITc_iotcon_query_create_destroy_p(void);
extern int ITc_iotcon_query_set_get_interface_p(void);
extern int ITc_iotcon_query_add_remove_p(void);
extern int ITc_iotcon_query_lookup_p(void);
extern int ITc_iotcon_query_foreach_p(void);
extern int ITc_iotcon_attributes_create_destroy_p(void);
extern int ITc_iotcon_attributes_clone_p(void);
extern int ITc_iotcon_attributes_add_get_int_p(void);
extern int ITc_iotcon_attributes_add_get_bool_p(void);
extern int ITc_iotcon_attributes_add_get_double_p(void);
extern int ITc_iotcon_attributes_add_get_str_p(void);
extern int ITc_iotcon_attributes_add_get_list_p(void);
extern int ITc_iotcon_attributes_add_get_attributes_p(void);
extern int ITc_iotcon_attributes_add_is_null_p(void);
extern int ITc_iotcon_attributes_remove_p(void);
extern int ITc_iotcon_attributes_get_type_p(void);
extern int ITc_iotcon_attributes_foreach_p(void);
extern int ITc_iotcon_attributes_get_keys_count_p(void);
extern int ITc_iotcon_attributes_add_get_byte_str_p(void);
extern int ITc_iotcon_list_create_destroy_p(void);
extern int ITc_iotcon_list_add_get_nth_int_p(void);
extern int ITc_iotcon_list_add_get_nth_bool_p(void);
extern int ITc_iotcon_list_add_get_nth_double_p(void);
extern int ITc_iotcon_list_add_get_nth_str_p(void);
extern int ITc_iotcon_list_add_get_nth_list_p(void);
extern int ITc_iotcon_list_add_get_nth_attributes_p(void);
extern int ITc_iotcon_list_remove_nth_p(void);
extern int ITc_iotcon_list_get_type_p(void);
extern int ITc_iotcon_list_get_length_p(void);
extern int ITc_iotcon_list_foreach_int_p(void);
extern int ITc_iotcon_list_foreach_bool_p(void);
extern int ITc_iotcon_list_foreach_double_p(void);
extern int ITc_iotcon_list_foreach_str_p(void);
extern int ITc_iotcon_list_foreach_list_p(void);
extern int ITc_iotcon_list_foreach_attributes_p(void);
extern int ITc_iotcon_list_add_byte_str_p(void);
extern int ITc_iotcon_list_get_nth_byte_str_p(void);
extern int ITc_iotcon_list_foreach_byte_str_p(void);
extern int ITc_iotcon_options_create_destroy_p(void);
extern int ITc_iotcon_options_add_remove_p(void);
extern int ITc_iotcon_options_lookup_p(void);
extern int ITc_iotcon_options_foreach_p(void);
extern int ITc_iotcon_remote_resource_create_destroy_p(void);
extern int ITc_iotcon_remote_resource_clone_p(void);
extern int ITc_iotcon_remote_resource_observe_register_deregister_p(void);
extern int ITc_iotcon_remote_resource_get_put_post_delete_p(void);
extern int ITc_iotcon_remote_resource_start_stop_caching_p(void);
extern int ITc_iotcon_remote_resource_start_stop_monitoring_p(void);
extern int ITc_iotcon_remote_resource_get_connectivity_type_p(void);
extern int ITc_iotcon_remote_resource_get_uri_path_p(void);
extern int ITc_iotcon_remote_resource_get_host_address_p(void);
extern int ITc_iotcon_remote_resource_get_device_id_p(void);
extern int ITc_iotcon_remote_resource_get_types_p(void);
extern int ITc_iotcon_remote_resource_get_interfaces_p(void);
extern int ITc_iotcon_remote_resource_get_policies_p(void);
extern int ITc_iotcon_remote_resource_set_get_options_p(void);
extern int ITc_iotcon_remote_resource_get_cached_representation_p(void);
extern int ITc_iotcon_remote_resource_set_get_checking_interval_p(void);
extern int ITc_remote_resource_get_device_name_p(void);
extern int ITc_iotcon_response_create_destroy_p(void);
extern int ITc_iotcon_response_set_get_options_p(void);
extern int ITc_iotcon_response_set_get_representation_p(void);
extern int ITc_iotcon_response_set_get_result_p(void);
extern int ITc_iotcon_response_send_p(void);
extern int ITc_iotcon_request_get_query_p(void);
extern int ITc_iotcon_request_get_host_address_p(void);
extern int ITc_iotcon_request_get_connectivity_type_p(void);
extern int ITc_iotcon_request_get_representation_p(void);
extern int ITc_iotcon_request_get_request_type_p(void);
extern int ITc_iotcon_request_get_options_p(void);
extern int ITc_iotcon_request_get_observe_type_p(void);
extern int ITc_iotcon_request_get_observe_id_p(void);
extern int ITc_iotcon_resource_create_destroy_p(void);
extern int ITc_iotcon_resource_bind_interface_p(void);
extern int ITc_iotcon_resource_bind_type_p(void);
extern int ITc_iotcon_resource_set_request_handler_p(void);
extern int ITc_iotcon_resource_bind_unbind_child_resource_p(void);
extern int ITc_iotcon_resource_get_child_count_p(void);
extern int ITc_iotcon_resource_get_nth_child_p(void);
extern int ITc_iotcon_resource_get_uri_path_p(void);
extern int ITc_iotcon_resource_get_types_p(void);
extern int ITc_iotcon_resource_get_interfaces_p(void);
extern int ITc_iotcon_resource_get_policies_p(void);
extern int ITc_iotcon_resource_types_create_destroy_p(void);
extern int ITc_iotcon_resource_types_add_remove_p(void);
extern int ITc_iotcon_resource_types_foreach_p(void);
extern int ITc_iotcon_resource_types_clone_p(void);
extern int ITc_iotcon_resource_notify_p(void);
extern int ITc_iotcon_presence_get_host_address_p(void);
extern int ITc_iotcon_presence_get_connectivity_type_p(void);
extern int ITc_iotcon_presence_get_resource_type_p(void);
extern int ITc_iotcon_presence_start_stop_presence_p(void);
extern int ITc_iotcon_presence_add_remove_presence_cb_p(void);
extern int ITc_iotcon_presence_response_get_result_p(void);
extern int ITc_iotcon_presence_response_get_trigger_p(void);
extern int ITc_iotcon_presence_response_get_connectivity_type_p(void);
extern int ITc_iotcon_presence_response_get_resource_type_p(void);
extern int ITc_iotcon_presence_response_get_host_address_p(void);
extern int ITc_iotcon_initialize_deinitialize_p(void);
extern int ITc_iotcon_add_remove_generated_pin_cb_p(void);

testcase tc_array[] = {
	{"ITc_iotcon_lite_resource_create_destroy_p",ITc_iotcon_lite_resource_create_destroy_p,ITs_iotcon_lite_resource_startup,ITs_iotcon_lite_resource_cleanup},
	{"ITc_iotcon_lite_resource_update_attributes_p",ITc_iotcon_lite_resource_update_attributes_p,ITs_iotcon_lite_resource_startup,ITs_iotcon_lite_resource_cleanup},
	{"ITc_iotcon_lite_resource_get_attributes_p",ITc_iotcon_lite_resource_get_attributes_p,ITs_iotcon_lite_resource_startup,ITs_iotcon_lite_resource_cleanup},
	{"ITc_iotcon_representation_create_destroy_p",ITc_iotcon_representation_create_destroy_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_clone_p",ITc_iotcon_representation_clone_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_set_get_uri_path_p",ITc_iotcon_representation_set_get_uri_path_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_set_get_resource_types_p",ITc_iotcon_representation_set_get_resource_types_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_set_get_resource_interfaces_p",ITc_iotcon_representation_set_get_resource_interfaces_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_set_get_attributes_p",ITc_iotcon_representation_set_get_attributes_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_add_remove_child_p",ITc_iotcon_representation_add_remove_child_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_foreach_children_p",ITc_iotcon_representation_foreach_children_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_get_child_count_p",ITc_iotcon_representation_get_child_count_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_representation_get_nth_child_p",ITc_iotcon_representation_get_nth_child_p,ITs_iotcon_representation_startup,ITs_iotcon_representation_cleanup},
	{"ITc_iotcon_set_get_timeout_p",ITc_iotcon_set_get_timeout_p,ITs_iotcon_startup,ITs_iotcon_cleanup},
	{"ITc_iotcon_set_device_name_p",ITc_iotcon_set_device_name_p,ITs_iotcon_startup,ITs_iotcon_cleanup},
	{"ITc_iotcon_find_device_info_p",ITc_iotcon_find_device_info_p,ITs_iotcon_device_startup,ITs_iotcon_device_cleanup},
	{"ITc_iotcon_device_info_get_property_p",ITc_iotcon_device_info_get_property_p,ITs_iotcon_device_startup,ITs_iotcon_device_cleanup},
	{"ITc_iotcon_find_platform_info_p",ITc_iotcon_find_platform_info_p,ITs_iotcon_device_startup,ITs_iotcon_device_cleanup},
	{"ITc_iotcon_platform_info_get_property_p",ITc_iotcon_platform_info_get_property_p,ITs_iotcon_device_startup,ITs_iotcon_device_cleanup},
	{"ITc_iotcon_observers_create_destroy_p",ITc_iotcon_observers_create_destroy_p,ITs_iotcon_observers_startup,ITs_iotcon_observers_cleanup},
	{"ITc_iotcon_observers_add_remove_p",ITc_iotcon_observers_add_remove_p,ITs_iotcon_observers_startup,ITs_iotcon_observers_cleanup},
	{"ITc_iotcon_query_create_destroy_p",ITc_iotcon_query_create_destroy_p,ITs_iotcon_query_startup,ITs_iotcon_query_cleanup},
	{"ITc_iotcon_query_set_get_interface_p",ITc_iotcon_query_set_get_interface_p,ITs_iotcon_query_startup,ITs_iotcon_query_cleanup},
	{"ITc_iotcon_query_add_remove_p",ITc_iotcon_query_add_remove_p,ITs_iotcon_query_startup,ITs_iotcon_query_cleanup},
	{"ITc_iotcon_query_lookup_p",ITc_iotcon_query_lookup_p,ITs_iotcon_query_startup,ITs_iotcon_query_cleanup},
	{"ITc_iotcon_query_foreach_p",ITc_iotcon_query_foreach_p,ITs_iotcon_query_startup,ITs_iotcon_query_cleanup},
	{"ITc_iotcon_attributes_create_destroy_p",ITc_iotcon_attributes_create_destroy_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_clone_p",ITc_iotcon_attributes_clone_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_int_p",ITc_iotcon_attributes_add_get_int_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_bool_p",ITc_iotcon_attributes_add_get_bool_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_double_p",ITc_iotcon_attributes_add_get_double_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_str_p",ITc_iotcon_attributes_add_get_str_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_list_p",ITc_iotcon_attributes_add_get_list_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_attributes_p",ITc_iotcon_attributes_add_get_attributes_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_is_null_p",ITc_iotcon_attributes_add_is_null_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_remove_p",ITc_iotcon_attributes_remove_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_get_type_p",ITc_iotcon_attributes_get_type_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_foreach_p",ITc_iotcon_attributes_foreach_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_get_keys_count_p",ITc_iotcon_attributes_get_keys_count_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_attributes_add_get_byte_str_p",ITc_iotcon_attributes_add_get_byte_str_p,ITs_iotcon_attributes_startup,ITs_iotcon_attributes_cleanup},
	{"ITc_iotcon_list_create_destroy_p",ITc_iotcon_list_create_destroy_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_int_p",ITc_iotcon_list_add_get_nth_int_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_bool_p",ITc_iotcon_list_add_get_nth_bool_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_double_p",ITc_iotcon_list_add_get_nth_double_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_str_p",ITc_iotcon_list_add_get_nth_str_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_list_p",ITc_iotcon_list_add_get_nth_list_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_get_nth_attributes_p",ITc_iotcon_list_add_get_nth_attributes_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_remove_nth_p",ITc_iotcon_list_remove_nth_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_get_type_p",ITc_iotcon_list_get_type_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_get_length_p",ITc_iotcon_list_get_length_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_int_p",ITc_iotcon_list_foreach_int_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_bool_p",ITc_iotcon_list_foreach_bool_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_double_p",ITc_iotcon_list_foreach_double_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_str_p",ITc_iotcon_list_foreach_str_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_list_p",ITc_iotcon_list_foreach_list_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_attributes_p",ITc_iotcon_list_foreach_attributes_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_add_byte_str_p",ITc_iotcon_list_add_byte_str_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_get_nth_byte_str_p",ITc_iotcon_list_get_nth_byte_str_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_list_foreach_byte_str_p",ITc_iotcon_list_foreach_byte_str_p,ITs_iotcon_list_startup,ITs_iotcon_list_cleanup},
	{"ITc_iotcon_options_create_destroy_p",ITc_iotcon_options_create_destroy_p,ITs_iotcon_options_startup,ITs_iotcon_options_cleanup},
	{"ITc_iotcon_options_add_remove_p",ITc_iotcon_options_add_remove_p,ITs_iotcon_options_startup,ITs_iotcon_options_cleanup},
	{"ITc_iotcon_options_lookup_p",ITc_iotcon_options_lookup_p,ITs_iotcon_options_startup,ITs_iotcon_options_cleanup},
	{"ITc_iotcon_options_foreach_p",ITc_iotcon_options_foreach_p,ITs_iotcon_options_startup,ITs_iotcon_options_cleanup},
	{"ITc_iotcon_remote_resource_create_destroy_p",ITc_iotcon_remote_resource_create_destroy_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_clone_p",ITc_iotcon_remote_resource_clone_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_observe_register_deregister_p",ITc_iotcon_remote_resource_observe_register_deregister_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_put_post_delete_p",ITc_iotcon_remote_resource_get_put_post_delete_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_start_stop_caching_p",ITc_iotcon_remote_resource_start_stop_caching_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_start_stop_monitoring_p",ITc_iotcon_remote_resource_start_stop_monitoring_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_connectivity_type_p",ITc_iotcon_remote_resource_get_connectivity_type_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_uri_path_p",ITc_iotcon_remote_resource_get_uri_path_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_host_address_p",ITc_iotcon_remote_resource_get_host_address_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_device_id_p",ITc_iotcon_remote_resource_get_device_id_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_types_p",ITc_iotcon_remote_resource_get_types_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_interfaces_p",ITc_iotcon_remote_resource_get_interfaces_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_policies_p",ITc_iotcon_remote_resource_get_policies_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_set_get_options_p",ITc_iotcon_remote_resource_set_get_options_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_get_cached_representation_p",ITc_iotcon_remote_resource_get_cached_representation_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_remote_resource_set_get_checking_interval_p",ITc_iotcon_remote_resource_set_get_checking_interval_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_remote_resource_get_device_name_p",ITc_remote_resource_get_device_name_p,ITs_iotcon_remote_resource_startup,ITs_iotcon_remote_resource_cleanup},
	{"ITc_iotcon_response_create_destroy_p",ITc_iotcon_response_create_destroy_p,ITs_iotcon_response_startup,ITs_iotcon_response_cleanup},
	{"ITc_iotcon_response_set_get_options_p",ITc_iotcon_response_set_get_options_p,ITs_iotcon_response_startup,ITs_iotcon_response_cleanup},
	{"ITc_iotcon_response_set_get_representation_p",ITc_iotcon_response_set_get_representation_p,ITs_iotcon_response_startup,ITs_iotcon_response_cleanup},
	{"ITc_iotcon_response_set_get_result_p",ITc_iotcon_response_set_get_result_p,ITs_iotcon_response_startup,ITs_iotcon_response_cleanup},
	{"ITc_iotcon_response_send_p",ITc_iotcon_response_send_p,ITs_iotcon_response_startup,ITs_iotcon_response_cleanup},
	{"ITc_iotcon_request_get_query_p",ITc_iotcon_request_get_query_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_host_address_p",ITc_iotcon_request_get_host_address_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_connectivity_type_p",ITc_iotcon_request_get_connectivity_type_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_representation_p",ITc_iotcon_request_get_representation_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_request_type_p",ITc_iotcon_request_get_request_type_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_options_p",ITc_iotcon_request_get_options_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_observe_type_p",ITc_iotcon_request_get_observe_type_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_request_get_observe_id_p",ITc_iotcon_request_get_observe_id_p,ITs_iotcon_request_startup,ITs_iotcon_request_cleanup},
	{"ITc_iotcon_resource_create_destroy_p",ITc_iotcon_resource_create_destroy_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_bind_interface_p",ITc_iotcon_resource_bind_interface_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_bind_type_p",ITc_iotcon_resource_bind_type_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_set_request_handler_p",ITc_iotcon_resource_set_request_handler_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_bind_unbind_child_resource_p",ITc_iotcon_resource_bind_unbind_child_resource_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_child_count_p",ITc_iotcon_resource_get_child_count_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_nth_child_p",ITc_iotcon_resource_get_nth_child_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_uri_path_p",ITc_iotcon_resource_get_uri_path_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_types_p",ITc_iotcon_resource_get_types_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_interfaces_p",ITc_iotcon_resource_get_interfaces_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_get_policies_p",ITc_iotcon_resource_get_policies_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_types_create_destroy_p",ITc_iotcon_resource_types_create_destroy_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_types_add_remove_p",ITc_iotcon_resource_types_add_remove_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_types_foreach_p",ITc_iotcon_resource_types_foreach_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_types_clone_p",ITc_iotcon_resource_types_clone_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_resource_notify_p",ITc_iotcon_resource_notify_p,ITs_iotcon_resource_startup,ITs_iotcon_resource_cleanup},
	{"ITc_iotcon_presence_get_host_address_p",ITc_iotcon_presence_get_host_address_p,ITs_iotcon_presence_startup,ITs_iotcon_presence_cleanup},
	{"ITc_iotcon_presence_get_connectivity_type_p",ITc_iotcon_presence_get_connectivity_type_p,ITs_iotcon_presence_startup,ITs_iotcon_presence_cleanup},
	{"ITc_iotcon_presence_get_resource_type_p",ITc_iotcon_presence_get_resource_type_p,ITs_iotcon_presence_startup,ITs_iotcon_presence_cleanup},
	{"ITc_iotcon_presence_start_stop_presence_p",ITc_iotcon_presence_start_stop_presence_p,ITs_iotcon_presence_startup,ITs_iotcon_presence_cleanup},
	{"ITc_iotcon_presence_add_remove_presence_cb_p",ITc_iotcon_presence_add_remove_presence_cb_p,ITs_iotcon_presence_startup,ITs_iotcon_presence_cleanup},
	{"ITc_iotcon_presence_response_get_result_p",ITc_iotcon_presence_response_get_result_p,ITs_iotcon_presence_response_startup,ITs_iotcon_presence_response_cleanup},
	{"ITc_iotcon_presence_response_get_trigger_p",ITc_iotcon_presence_response_get_trigger_p,ITs_iotcon_presence_response_startup,ITs_iotcon_presence_response_cleanup},
	{"ITc_iotcon_presence_response_get_connectivity_type_p",ITc_iotcon_presence_response_get_connectivity_type_p,ITs_iotcon_presence_response_startup,ITs_iotcon_presence_response_cleanup},
	{"ITc_iotcon_presence_response_get_resource_type_p",ITc_iotcon_presence_response_get_resource_type_p,ITs_iotcon_presence_response_startup,ITs_iotcon_presence_response_cleanup},
	{"ITc_iotcon_presence_response_get_host_address_p",ITc_iotcon_presence_response_get_host_address_p,ITs_iotcon_presence_response_startup,ITs_iotcon_presence_response_cleanup},
	{"ITc_iotcon_initialize_deinitialize_p",ITc_iotcon_initialize_deinitialize_p,ITs_iotcon_service_startup,ITs_iotcon_service_cleanup},
	{"ITc_iotcon_add_remove_generated_pin_cb_p",ITc_iotcon_add_remove_generated_pin_cb_p,ITs_iotcon_service_startup,ITs_iotcon_service_cleanup},
	{NULL, NULL}
};

#endif // __TCT_IOTCON-NATIVE_H__
