//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_STREAMRECORDER_NATIVE_H__
#define __TCT_STREAMRECORDER_NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_streamrecorder_startup(void);
extern void utc_streamrecorder_cleanup(void);
extern void utc_streamrecorder_buffer_startup(void);
extern void utc_streamrecorder_buffer_cleanup(void);
extern void utc_streamrecorder_callback_startup(void);
extern void utc_streamrecorder_callback_cleanup(void);
extern void utc_streamrecorder_lifecycle_startup(void);
extern void utc_streamrecorder_lifecycle_cleanup(void);

extern int utc_streamrecorder_get_audio_channel_p(void);
extern int utc_streamrecorder_get_audio_channel_n1(void);
extern int utc_streamrecorder_get_audio_channel_n2(void);
extern int utc_streamrecorder_get_audio_encoder_bitrate_p(void);
extern int utc_streamrecorder_get_audio_encoder_bitrate_n1(void);
extern int utc_streamrecorder_get_audio_encoder_bitrate_n2(void);
extern int utc_streamrecorder_get_audio_samplerate_p(void);
extern int utc_streamrecorder_get_audio_samplerate_n1(void);
extern int utc_streamrecorder_get_audio_samplerate_n2(void);
extern int utc_streamrecorder_get_recording_limitation_p(void);
extern int utc_streamrecorder_get_recording_limit_n1(void);
extern int utc_streamrecorder_get_recording_limit_n2(void);
extern int utc_streamrecorder_get_video_framerate_p(void);
extern int utc_streamrecorder_get_video_framerate_n1(void);
extern int utc_streamrecorder_get_video_frmaerate_n2(void);
extern int utc_streamrecorder_get_video_source_format_p(void);
extern int utc_streamrecorder_get_video_source_format_n1(void);
extern int utc_streamrecorder_get_video_source_format_n2(void);
extern int utc_streamrecorder_get_video_encoder_bitrate_p(void);
extern int utc_streamrecorder_get_video_encoder_bitrate_n1(void);
extern int utc_streamrecorder_get_video_encoder_bitrate_n2(void);
extern int utc_streamrecorder_set_audio_channel_p(void);
extern int utc_streamrecorder_set_audio_channel_n1(void);
extern int utc_streamrecorder_set_audio_channel_n2(void);
extern int utc_streamrecorder_set_audio_encoder_bitrate_p(void);
extern int utc_streamrecorder_set_audio_encoder_bitrate_n(void);
extern int utc_streamrecorder_set_audio_samplerate_p(void);
extern int utc_streamrecorder_set_audio_samplerate_n(void);
extern int utc_streamrecorder_set_recording_limit_p(void);
extern int utc_streamrecorder_set_recording_limit_n1(void);
extern int utc_streamrecorder_set_recording_limit_n2(void);
extern int utc_streamrecorder_set_video_encoder_bitrate_p(void);
extern int utc_streamrecorder_set_video_encoder_bitrate_n1(void);
extern int utc_streamrecorder_set_video_encoder_bitrate_n2(void);
extern int utc_streamrecorder_get_audio_encoder_p1(void);
extern int utc_streamrecorder_get_audio_encoder_p2(void);
extern int utc_streamrecorder_get_audio_encoder_n1(void);
extern int utc_streamrecorder_get_audio_encoder_n2(void);
extern int utc_streamrecorder_get_file_format_p(void);
extern int utc_streamrecorder_get_file_format_n(void);
extern int utc_streamrecorder_get_video_encoder_p1(void);
extern int utc_streamrecorder_get_video_encoder_p2(void);
extern int utc_streamrecorder_get_video_encoder_n1(void);
extern int utc_streamrecorder_get_video_encoder_n2(void);
extern int utc_streamrecorder_get_video_resolution_p(void);
extern int utc_streamrecorder_get_video_resolution_n1(void);
extern int utc_streamrecorder_get_video_resolution_n2(void);
extern int utc_streamrecorder_set_audio_encoder_p(void);
extern int utc_streamrecorder_set_audio_encoder_n1(void);
extern int utc_streamrecorder_set_audio_encoder_n2(void);
extern int utc_streamrecorder_set_file_format_p1(void);
extern int utc_streamrecorder_get_file_format_p2(void);
extern int utc_streamrecorder_set_file_format_n(void);
extern int utc_streamrecorder_set_filename_p(void);
extern int utc_streamrecorder_set_filename_n(void);
extern int utc_streamrecorder_set_video_encoder_p(void);
extern int utc_streamrecorder_set_video_encoder_n1(void);
extern int utc_streamrecorder_set_video_encoder_n2(void);
extern int utc_streamrecorder_set_video_resolution_p(void);
extern int utc_streamrecorder_set_video_resolution_n1(void);
extern int utc_streamrecorder_set_video_resolution_n2(void);
extern int utc_streamrecorder_get_filename_p(void);
extern int utc_streamrecorder_get_filename_n(void);
extern int utc_streamrecorder_set_video_source_format_p(void);
extern int utc_streamrecorder_set_video_source_format_n(void);
extern int utc_streamrecorder_set_video_framerate_p(void);
extern int utc_streamrecorder_set_video_framerate_n(void);
extern int utc_streamrecorder_push_stream_buffer_p(void);
extern int utc_streamrecorder_push_stream_buffer_n(void);
extern int utc_streamrecorder_foreach_supported_audio_encoder_p(void);
extern int utc_streamrecorder_foreach_supported_audio_encoder_n(void);
extern int utc_streamrecorder_foreach_supported_file_format_p(void);
extern int utc_streamrecorder_foreach_supported_file_format_n1(void);
extern int utc_streamrecorder_foreach_supported_file_format_n2(void);
extern int utc_streamrecorder_foreach_supported_video_encoder_p(void);
extern int utc_streamrecorder_foreach_supported_video_encoder_n1(void);
extern int utc_streamrecorder_foreach_supported_video_encoder_n2(void);
extern int utc_streamrecorder_foreach_supported_video_resolution_p(void);
extern int utc_streamrecorder_foreach_supported_video_resolution_n(void);
extern int utc_streamrecorder_set_buffer_consume_completed_cb_p(void);
extern int utc_streamrecorder_set_buffer_consume_completed_cb_n1(void);
extern int utc_streamrecorder_set_buffer_consume_completed_cb_n2(void);
extern int utc_streamrecorder_set_recording_limit_reached_cb_p(void);
extern int utc_streamrecorder_set_recording_limit_reached_cb_n1(void);
extern int utc_streamrecorder_set_recording_limit_reached_cb_n2(void);
extern int utc_streamrecorder_set_recording_status_cb_p(void);
extern int utc_streamrecorder_set_recording_status_cb_n1(void);
extern int utc_streamrecorder_set_recording_status_cb_n2(void);
extern int utc_streamrecorder_set_notify_cb_p(void);
extern int utc_streamrecorder_set_notify_cb_n1(void);
extern int utc_streamrecorder_set_notify_cb_n2(void);
extern int utc_streamrecorder_set_error_cb_p(void);
extern int utc_streamrecorder_set_error_cb_n1(void);
extern int utc_streamrecorder_set_error_cb_n2(void);
extern int utc_streamrecorder_unset_recording_limit_reached_cb_p(void);
extern int utc_streamrecorder_unset_recording_limit_reached_cb_n(void);
extern int utc_streamrecorder_unset_buffer_consume_completed_cb_p(void);
extern int utc_streamrecorder_unset_buffer_consume_completed_cb_n1(void);
extern int utc_streamrecorder_unset_recording_status_cb_p(void);
extern int utc_streamrecorder_unset_recording_status_cb_n(void);
extern int utc_streamrecorder_unset_notify_cb_p(void);
extern int utc_streamrecorder_unset_notify_cb_n(void);
extern int utc_streamrecorder_unset_error_cb_p(void);
extern int utc_streamrecorder_unset_error_cb_n(void);
extern int utc_streamrecorder_enable_source_buffer_n(void);
extern int utc_streamrecorder_enable_source_buffer_p(void);
extern int utc_streamrecorder_cancel_p(void);
extern int utc_streamrecorder_cancel_n(void);
extern int utc_streamrecorder_commit_p(void);
extern int utc_streamrecorder_commit_n(void);
extern int utc_streamrecorder_destroy_p(void);
extern int utc_streamrecorder_destroy_n(void);
extern int utc_streamrecorder_pause_p(void);
extern int utc_streamrecorder_pause_n(void);
extern int utc_streamrecorder_prepare_p(void);
extern int utc_streamrecorder_prepare_n1(void);
extern int utc_streamrecorder_prepare_n2(void);
extern int utc_streamrecorder_start_p(void);
extern int utc_streamrecorder_start_n(void);
extern int utc_streamrecorder_unprepare_p(void);
extern int utc_streamrecorder_unprepare_n1(void);
extern int utc_streamrecorder_unprepare_n2(void);
extern int utc_streamrecorder_get_state_p(void);
extern int utc_streamrecorder_get_state_n1(void);
extern int utc_streamrecorder_get_state_n2(void);
extern int utc_streamrecorder_set_mode_p(void);
extern int utc_streamrecorder_set_mode_n(void);
extern int utc_streamrecorder_get_mode_p(void);
extern int utc_streamrecorder_get_mode_n(void);

testcase tc_array[] = {
	{"utc_streamrecorder_get_audio_channel_p",utc_streamrecorder_get_audio_channel_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_channel_n1",utc_streamrecorder_get_audio_channel_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_channel_n2",utc_streamrecorder_get_audio_channel_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_bitrate_p",utc_streamrecorder_get_audio_encoder_bitrate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_bitrate_n1",utc_streamrecorder_get_audio_encoder_bitrate_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_bitrate_n2",utc_streamrecorder_get_audio_encoder_bitrate_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_samplerate_p",utc_streamrecorder_get_audio_samplerate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_samplerate_n1",utc_streamrecorder_get_audio_samplerate_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_samplerate_n2",utc_streamrecorder_get_audio_samplerate_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_recording_limitation_p",utc_streamrecorder_get_recording_limitation_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_recording_limit_n1",utc_streamrecorder_get_recording_limit_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_recording_limit_n2",utc_streamrecorder_get_recording_limit_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_framerate_p",utc_streamrecorder_get_video_framerate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_framerate_n1",utc_streamrecorder_get_video_framerate_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_frmaerate_n2",utc_streamrecorder_get_video_frmaerate_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_source_format_p",utc_streamrecorder_get_video_source_format_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_source_format_n1",utc_streamrecorder_get_video_source_format_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_source_format_n2",utc_streamrecorder_get_video_source_format_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_bitrate_p",utc_streamrecorder_get_video_encoder_bitrate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_bitrate_n1",utc_streamrecorder_get_video_encoder_bitrate_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_bitrate_n2",utc_streamrecorder_get_video_encoder_bitrate_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_channel_p",utc_streamrecorder_set_audio_channel_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_channel_n1",utc_streamrecorder_set_audio_channel_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_channel_n2",utc_streamrecorder_set_audio_channel_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_encoder_bitrate_p",utc_streamrecorder_set_audio_encoder_bitrate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_encoder_bitrate_n",utc_streamrecorder_set_audio_encoder_bitrate_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_samplerate_p",utc_streamrecorder_set_audio_samplerate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_samplerate_n",utc_streamrecorder_set_audio_samplerate_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_recording_limit_p",utc_streamrecorder_set_recording_limit_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_recording_limit_n1",utc_streamrecorder_set_recording_limit_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_recording_limit_n2",utc_streamrecorder_set_recording_limit_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_bitrate_p",utc_streamrecorder_set_video_encoder_bitrate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_bitrate_n1",utc_streamrecorder_set_video_encoder_bitrate_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_bitrate_n2",utc_streamrecorder_set_video_encoder_bitrate_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_p1",utc_streamrecorder_get_audio_encoder_p1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_p2",utc_streamrecorder_get_audio_encoder_p2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_n1",utc_streamrecorder_get_audio_encoder_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_audio_encoder_n2",utc_streamrecorder_get_audio_encoder_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_file_format_p",utc_streamrecorder_get_file_format_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_file_format_n",utc_streamrecorder_get_file_format_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_p1",utc_streamrecorder_get_video_encoder_p1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_p2",utc_streamrecorder_get_video_encoder_p2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_n1",utc_streamrecorder_get_video_encoder_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_encoder_n2",utc_streamrecorder_get_video_encoder_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_resolution_p",utc_streamrecorder_get_video_resolution_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_resolution_n1",utc_streamrecorder_get_video_resolution_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_video_resolution_n2",utc_streamrecorder_get_video_resolution_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_encoder_p",utc_streamrecorder_set_audio_encoder_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_encoder_n1",utc_streamrecorder_set_audio_encoder_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_audio_encoder_n2",utc_streamrecorder_set_audio_encoder_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_file_format_p1",utc_streamrecorder_set_file_format_p1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_file_format_p2",utc_streamrecorder_get_file_format_p2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_file_format_n",utc_streamrecorder_set_file_format_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_filename_p",utc_streamrecorder_set_filename_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_filename_n",utc_streamrecorder_set_filename_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_p",utc_streamrecorder_set_video_encoder_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_n1",utc_streamrecorder_set_video_encoder_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_encoder_n2",utc_streamrecorder_set_video_encoder_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_resolution_p",utc_streamrecorder_set_video_resolution_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_resolution_n1",utc_streamrecorder_set_video_resolution_n1,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_resolution_n2",utc_streamrecorder_set_video_resolution_n2,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_filename_p",utc_streamrecorder_get_filename_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_get_filename_n",utc_streamrecorder_get_filename_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_source_format_p",utc_streamrecorder_set_video_source_format_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_source_format_n",utc_streamrecorder_set_video_source_format_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_framerate_p",utc_streamrecorder_set_video_framerate_p,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_set_video_framerate_n",utc_streamrecorder_set_video_framerate_n,utc_streamrecorder_startup,utc_streamrecorder_cleanup},
	{"utc_streamrecorder_push_stream_buffer_p",utc_streamrecorder_push_stream_buffer_p,utc_streamrecorder_buffer_startup,utc_streamrecorder_buffer_cleanup},
	{"utc_streamrecorder_push_stream_buffer_n",utc_streamrecorder_push_stream_buffer_n,utc_streamrecorder_buffer_startup,utc_streamrecorder_buffer_cleanup},
	{"utc_streamrecorder_foreach_supported_audio_encoder_p",utc_streamrecorder_foreach_supported_audio_encoder_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_audio_encoder_n",utc_streamrecorder_foreach_supported_audio_encoder_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_file_format_p",utc_streamrecorder_foreach_supported_file_format_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_file_format_n1",utc_streamrecorder_foreach_supported_file_format_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_file_format_n2",utc_streamrecorder_foreach_supported_file_format_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_video_encoder_p",utc_streamrecorder_foreach_supported_video_encoder_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_video_encoder_n1",utc_streamrecorder_foreach_supported_video_encoder_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_video_encoder_n2",utc_streamrecorder_foreach_supported_video_encoder_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_video_resolution_p",utc_streamrecorder_foreach_supported_video_resolution_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_foreach_supported_video_resolution_n",utc_streamrecorder_foreach_supported_video_resolution_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_buffer_consume_completed_cb_p",utc_streamrecorder_set_buffer_consume_completed_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_buffer_consume_completed_cb_n1",utc_streamrecorder_set_buffer_consume_completed_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_buffer_consume_completed_cb_n2",utc_streamrecorder_set_buffer_consume_completed_cb_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_limit_reached_cb_p",utc_streamrecorder_set_recording_limit_reached_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_limit_reached_cb_n1",utc_streamrecorder_set_recording_limit_reached_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_limit_reached_cb_n2",utc_streamrecorder_set_recording_limit_reached_cb_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_status_cb_p",utc_streamrecorder_set_recording_status_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_status_cb_n1",utc_streamrecorder_set_recording_status_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_recording_status_cb_n2",utc_streamrecorder_set_recording_status_cb_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_notify_cb_p",utc_streamrecorder_set_notify_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_notify_cb_n1",utc_streamrecorder_set_notify_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_notify_cb_n2",utc_streamrecorder_set_notify_cb_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_error_cb_p",utc_streamrecorder_set_error_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_error_cb_n1",utc_streamrecorder_set_error_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_set_error_cb_n2",utc_streamrecorder_set_error_cb_n2,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_recording_limit_reached_cb_p",utc_streamrecorder_unset_recording_limit_reached_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_recording_limit_reached_cb_n",utc_streamrecorder_unset_recording_limit_reached_cb_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_buffer_consume_completed_cb_p",utc_streamrecorder_unset_buffer_consume_completed_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_buffer_consume_completed_cb_n1",utc_streamrecorder_unset_buffer_consume_completed_cb_n1,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_recording_status_cb_p",utc_streamrecorder_unset_recording_status_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_recording_status_cb_n",utc_streamrecorder_unset_recording_status_cb_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_notify_cb_p",utc_streamrecorder_unset_notify_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_notify_cb_n",utc_streamrecorder_unset_notify_cb_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_error_cb_p",utc_streamrecorder_unset_error_cb_p,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_unset_error_cb_n",utc_streamrecorder_unset_error_cb_n,utc_streamrecorder_callback_startup,utc_streamrecorder_callback_cleanup},
	{"utc_streamrecorder_enable_source_buffer_n",utc_streamrecorder_enable_source_buffer_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_enable_source_buffer_p",utc_streamrecorder_enable_source_buffer_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_cancel_p",utc_streamrecorder_cancel_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_cancel_n",utc_streamrecorder_cancel_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_commit_p",utc_streamrecorder_commit_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_commit_n",utc_streamrecorder_commit_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_destroy_p",utc_streamrecorder_destroy_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_destroy_n",utc_streamrecorder_destroy_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_pause_p",utc_streamrecorder_pause_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_pause_n",utc_streamrecorder_pause_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_prepare_p",utc_streamrecorder_prepare_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_prepare_n1",utc_streamrecorder_prepare_n1,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_prepare_n2",utc_streamrecorder_prepare_n2,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_start_p",utc_streamrecorder_start_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_start_n",utc_streamrecorder_start_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_unprepare_p",utc_streamrecorder_unprepare_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_unprepare_n1",utc_streamrecorder_unprepare_n1,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_unprepare_n2",utc_streamrecorder_unprepare_n2,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_get_state_p",utc_streamrecorder_get_state_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_get_state_n1",utc_streamrecorder_get_state_n1,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_get_state_n2",utc_streamrecorder_get_state_n2,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_set_mode_p",utc_streamrecorder_set_mode_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_set_mode_n",utc_streamrecorder_set_mode_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_get_mode_p",utc_streamrecorder_get_mode_p,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{"utc_streamrecorder_get_mode_n",utc_streamrecorder_get_mode_n,utc_streamrecorder_lifecycle_startup,utc_streamrecorder_lifecycle_cleanup},
	{NULL, NULL}
};

#endif // __TCT_STREAMRECORDER_NATIVE_H__
