//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_APPLICATION-NATIVE_H__
#define __TCT_APPLICATION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_application_preference_startup(void);
extern void utc_application_app_control_startup(void);
extern void utc_application_app_resource_manager_startup(void);
extern void utc_application_app_resource_manager_cleanup(void);
extern void utc_application_app_event_startup(void);
extern void utc_application_app_event_cleanup(void);
extern void utc_application_app_get_display_state_startup(void);
extern void utc_application_app_get_display_state_cleanup(void);
extern void utc_application_app_watchdog_timer_enable_p_cleanup(void);
extern void utc_application_app_watchdog_timer_disable_p_startup(void);
extern void utc_application_app_watchdog_timer_kick_p_startup(void);
extern void utc_application_app_watchdog_timer_kick_p_cleanup(void);

extern int utc_application_app_get_name_p(void);
extern int utc_application_app_get_name_n(void);
extern int utc_application_app_get_version_p(void);
extern int utc_application_app_get_version_n(void);
extern int utc_application_app_get_device_orientation_p(void);
extern int utc_application_app_get_id_p(void);
extern int utc_application_app_get_id_n(void);
extern int utc_application_app_get_cache_path_p(void);
extern int utc_application_app_get_data_path_p(void);
extern int utc_application_app_get_resource_path_p(void);
extern int utc_application_app_get_external_cache_path_p(void);
extern int utc_application_app_get_external_data_path_p(void);
extern int utc_application_app_get_external_shared_data_path_p(void);
extern int utc_application_app_get_shared_data_path_p(void);
extern int utc_application_app_get_shared_resource_path_p(void);
extern int utc_application_app_get_shared_trusted_path_p(void);
extern int utc_application_app_get_tep_resource_path_p(void);
extern int utc_application_app_event_get_low_memory_status_n(void);
extern int utc_application_app_event_get_low_battery_status_n(void);
extern int utc_application_app_event_get_language_n(void);
extern int utc_application_app_event_get_device_orientation_n(void);
extern int utc_application_app_event_get_region_format_n(void);
extern int utc_application_app_event_get_suspended_state_n(void);
extern int utc_application_ui_app_main_n(void);
extern int utc_application_ui_app_add_event_handler_p(void);
extern int utc_application_ui_app_add_event_handler_n(void);
extern int utc_application_ui_app_remove_event_handler_p(void);
extern int utc_application_ui_app_remove_event_handler_n(void);
extern int utc_application_ui_app_exit_p(void);
extern int utc_application_i18n_get_text_p(void);
extern int utc_application_i18n_get_text_n1(void);
extern int utc_application_i18n_get_text_n2(void);
extern int utc_application_i18n_get_text_n3(void);
extern int utc_application_preference_set_int_p(void);
extern int utc_application_preference_set_int_n(void);
extern int utc_application_preference_set_double_p(void);
extern int utc_application_preference_set_double_n(void);
extern int utc_application_preference_set_string_p(void);
extern int utc_application_preference_set_string_n1(void);
extern int utc_application_preference_set_string_n2(void);
extern int utc_application_preference_set_boolean_p(void);
extern int utc_application_preference_set_boolean_n(void);
extern int utc_application_preference_get_int_p(void);
extern int utc_application_preference_get_int_n1(void);
extern int utc_application_preference_get_int_n2(void);
extern int utc_application_preference_get_int_n3(void);
extern int utc_application_preference_get_double_p(void);
extern int utc_application_preference_get_double_n1(void);
extern int utc_application_preference_get_double_n2(void);
extern int utc_application_preference_get_double_n3(void);
extern int utc_application_preference_get_string_p(void);
extern int utc_application_preference_get_string_n1(void);
extern int utc_application_preference_get_string_n2(void);
extern int utc_application_preference_get_string_n3(void);
extern int utc_application_preference_get_boolean_p(void);
extern int utc_application_preference_get_boolean_n1(void);
extern int utc_application_preference_get_boolean_n2(void);
extern int utc_application_preference_get_boolean_n3(void);
extern int utc_application_preference_remove_p(void);
extern int utc_application_preference_remove_n1(void);
extern int utc_application_preference_remove_n2(void);
extern int utc_application_preference_remove_all_p(void);
extern int utc_application_preference_is_existing_p1(void);
extern int utc_application_preference_is_existing_p2(void);
extern int utc_application_preference_is_existing_n1(void);
extern int utc_application_preference_is_existing_n2(void);
extern int utc_application_preference_is_existing_n3(void);
extern int utc_application_preference_set_changed_cb_p1(void);
extern int utc_application_preference_set_changed_cb_p2(void);
extern int utc_application_preference_set_changed_cb_n1(void);
extern int utc_application_preference_set_changed_cb_n2(void);
extern int utc_application_preference_set_changed_cb_n3(void);
extern int utc_application_preference_unset_changed_cb_p1(void);
extern int utc_application_preference_unset_changed_cb_n1(void);
extern int utc_application_preference_unset_changed_cb_n2(void);
extern int utc_application_preference_foreach_item_p(void);
extern int utc_application_preference_foreach_item_n(void);
extern int utc_application_preference_get_type_n(void);
extern int utc_application_preference_get_type_p(void);
extern int utc_application_app_control_create_p(void);
extern int utc_application_app_control_create_n(void);
extern int utc_application_app_control_destroy_p(void);
extern int utc_application_app_control_destroy_n(void);
extern int utc_application_app_control_set_operation_p1(void);
extern int utc_application_app_control_set_operation_p2(void);
extern int utc_application_app_control_set_operation_n(void);
extern int utc_application_app_control_get_operation_p(void);
extern int utc_application_app_control_get_operation_n1(void);
extern int utc_application_app_control_get_operation_n2(void);
extern int utc_application_app_control_get_operation_n3(void);
extern int utc_application_app_control_set_uri_p1(void);
extern int utc_application_app_control_set_uri_p2(void);
extern int utc_application_app_control_set_uri_n(void);
extern int utc_application_app_control_get_uri_p(void);
extern int utc_application_app_control_get_uri_n1(void);
extern int utc_application_app_control_get_uri_n2(void);
extern int utc_application_app_control_get_uri_n3(void);
extern int utc_application_app_control_set_mime_p1(void);
extern int utc_application_app_control_set_mime_p2(void);
extern int utc_application_app_control_set_mime_n(void);
extern int utc_application_app_control_get_mime_p(void);
extern int utc_application_app_control_get_mime_n1(void);
extern int utc_application_app_control_get_mime_n2(void);
extern int utc_application_app_control_get_mime_n3(void);
extern int utc_application_app_control_set_app_id_p1(void);
extern int utc_application_app_control_set_app_id_p2(void);
extern int utc_application_app_control_set_app_id_n1(void);
extern int utc_application_app_control_set_app_id_n2(void);
extern int utc_application_app_control_get_app_id_p(void);
extern int utc_application_app_control_get_app_id_n1(void);
extern int utc_application_app_control_get_app_id_n2(void);
extern int utc_application_app_control_get_app_id_n3(void);
extern int utc_application_app_control_set_category_p1(void);
extern int utc_application_app_control_set_category_p2(void);
extern int utc_application_app_control_set_category_n1(void);
extern int utc_application_app_control_set_category_n2(void);
extern int utc_application_app_control_get_category_p(void);
extern int utc_application_app_control_get_category_n1(void);
extern int utc_application_app_control_get_category_n2(void);
extern int utc_application_app_control_get_category_n3(void);
extern int utc_application_app_control_add_extra_data_p(void);
extern int utc_application_app_control_add_extra_data_n1(void);
extern int utc_application_app_control_add_extra_data_n2(void);
extern int utc_application_app_control_add_extra_data_n3(void);
extern int utc_application_app_control_remove_extra_data_p(void);
extern int utc_application_app_control_remove_extra_data_n1(void);
extern int utc_application_app_control_remove_extra_data_n2(void);
extern int utc_application_app_control_remove_extra_data_n3(void);
extern int utc_application_app_control_remove_extra_data_n4(void);
extern int utc_application_app_control_get_extra_data_p(void);
extern int utc_application_app_control_get_extra_data_n1(void);
extern int utc_application_app_control_get_extra_data_n2(void);
extern int utc_application_app_control_get_extra_data_n3(void);
extern int utc_application_app_control_get_extra_data_n4(void);
extern int utc_application_app_control_get_extra_data_n5(void);
extern int utc_application_app_control_get_extra_data_array_n6(void);
extern int utc_application_app_control_foreach_extra_data_p(void);
extern int utc_application_app_control_foreach_extra_data_n1(void);
extern int utc_application_app_control_foreach_extra_data_n2(void);
extern int utc_application_app_control_clone_p(void);
extern int utc_application_app_control_clone_n1(void);
extern int utc_application_app_control_clone_n2(void);
extern int utc_application_app_control_send_launch_request_p1(void);
extern int utc_application_app_control_send_launch_request_p2(void);
extern int utc_application_app_control_send_launch_request_p3(void);
extern int utc_application_app_control_send_launch_request_p4(void);
extern int utc_application_app_control_send_launch_request_n1(void);
extern int utc_application_app_control_send_launch_request_n2(void);
extern int utc_application_app_control_send_launch_request_n3(void);
extern int utc_application_app_control_send_launch_request_n4(void);
extern int utc_application_app_control_reply_to_launch_request_n1(void);
extern int utc_application_app_control_reply_to_launch_request_n2(void);
extern int utc_application_app_control_reply_to_launch_request_n3(void);
extern int utc_application_app_control_foreach_app_matched_p(void);
extern int utc_application_app_control_foreach_app_matched_n1(void);
extern int utc_application_app_control_foreach_app_matched_n2(void);
extern int utc_application_app_control_add_extra_data_array_p(void);
extern int utc_application_app_control_add_extra_data_array_n1(void);
extern int utc_application_app_control_add_extra_data_array_n2(void);
extern int utc_application_app_control_add_extra_data_array_n3(void);
extern int utc_application_app_control_add_extra_data_array_n4(void);
extern int utc_application_app_control_get_extra_data_array_p(void);
extern int utc_application_app_control_get_extra_data_array_n1(void);
extern int utc_application_app_control_get_extra_data_array_n2(void);
extern int utc_application_app_control_get_extra_data_array_n3(void);
extern int utc_application_app_control_get_extra_data_array_n4(void);
extern int utc_application_app_control_get_extra_data_array_n5(void);
extern int utc_application_app_control_is_extra_data_array_p1(void);
extern int utc_application_app_control_is_extra_data_array_p2(void);
extern int utc_application_app_control_is_extra_data_array_n1(void);
extern int utc_application_app_control_is_extra_data_array_n2(void);
extern int utc_application_app_control_is_extra_data_array_n3(void);
extern int utc_application_app_control_is_extra_data_array_n4(void);
extern int utc_application_app_control_is_reply_requested_n1(void);
extern int utc_application_app_control_is_reply_requested_n2(void);
extern int utc_application_app_control_is_reply_requested_n3(void);
extern int utc_application_app_control_is_reply_requested_n4(void);
extern int utc_application_app_control_get_caller_n1(void);
extern int utc_application_app_control_get_caller_n2(void);
extern int utc_application_app_control_get_caller_n3(void);
extern int utc_application_app_control_send_terminate_request_p(void);
extern int utc_application_app_control_send_terminate_request_n(void);
extern int utc_application_app_control_set_launch_mode_p1(void);
extern int utc_application_app_control_set_launch_mode_p2(void);
extern int utc_application_app_control_set_launch_mode_n(void);
extern int utc_application_app_control_get_launch_mode_p1(void);
extern int utc_application_app_control_get_launch_mode_p2(void);
extern int utc_application_app_control_get_launch_mode_p3(void);
extern int utc_application_app_control_get_launch_mode_n1(void);
extern int utc_application_app_control_enable_app_started_result_event_p1(void);
extern int utc_application_app_control_enable_app_started_result_event_n1(void);
extern int utc_application_app_control_set_component_id_p1(void);
extern int utc_application_app_control_set_component_id_n1(void);
extern int utc_application_app_control_get_component_id_p1(void);
extern int utc_application_app_control_get_component_id_n1(void);
extern int utc_application_app_resource_manager_get_p1(void);
extern int utc_application_app_resource_manager_get_p2(void);
extern int utc_application_app_resource_manager_get_p3(void);
extern int utc_application_app_resource_manager_get_p4(void);
extern int utc_application_app_resource_manager_get_p5(void);
extern int utc_application_app_resource_manager_get_n1(void);
extern int utc_application_app_resource_manager_get_n2(void);
extern int utc_application_app_resource_manager_get_n3(void);
extern int utc_application_app_event_add_event_handler_p1(void);
extern int utc_application_app_event_add_event_handler_p2(void);
extern int utc_application_app_event_add_event_handler_p3(void);
extern int utc_application_app_event_add_event_handler_p4(void);
extern int utc_application_app_event_add_event_handler_p5(void);
extern int utc_application_app_event_add_event_handler_p6(void);
extern int utc_application_app_event_add_event_handler_p7(void);
extern int utc_application_app_event_add_event_handler_p8(void);
extern int utc_application_app_event_add_event_handler_p9(void);
extern int utc_application_app_event_add_event_handler_p10(void);
extern int utc_application_app_event_add_event_handler_p11(void);
extern int utc_application_app_event_add_event_handler_p12(void);
extern int utc_application_app_event_add_event_handler_p13(void);
extern int utc_application_app_event_add_event_handler_p14(void);
extern int utc_application_app_event_add_event_handler_p15(void);
extern int utc_application_app_event_add_event_handler_p16(void);
extern int utc_application_app_event_add_event_handler_p17(void);
extern int utc_application_app_event_add_event_handler_p18(void);
extern int utc_application_app_event_add_event_handler_p19(void);
extern int utc_application_app_event_add_event_handler_p20(void);
extern int utc_application_app_event_add_event_handler_p21(void);
extern int utc_application_app_event_add_event_handler_p22(void);
extern int utc_application_app_event_add_event_handler_p23(void);
extern int utc_application_app_event_add_event_handler_p24(void);
extern int utc_application_app_event_add_event_handler_p25(void);
extern int utc_application_app_event_add_event_handler_p26(void);
extern int utc_application_app_event_add_event_handler_p27(void);
extern int utc_application_app_event_add_event_handler_n1(void);
extern int utc_application_app_event_add_event_handler_n2(void);
extern int utc_application_app_event_add_event_handler_n3(void);
extern int utc_application_app_event_add_event_handler_n4(void);
extern int utc_application_app_event_remove_event_handler_p(void);
extern int utc_application_app_event_remove_event_handler_n(void);
extern int utc_application_app_event_publish_app_event_p1(void);
extern int utc_application_app_event_publish_app_event_p2(void);
extern int utc_application_app_event_publish_app_event_n1(void);
extern int utc_application_app_event_publish_app_event_n2(void);
extern int utc_application_app_event_publish_app_event_n3(void);
extern int utc_application_app_event_publish_trusted_app_event_p(void);
extern int utc_application_app_event_publish_trusted_app_event_n1(void);
extern int utc_application_app_event_publish_trusted_app_event_n2(void);
extern int utc_application_app_event_publish_trusted_app_event_n3(void);
extern int utc_application_app_event_publish_trusted_app_event_n4(void);
extern int utc_application_app_event_publish_trusted_app_event_n5(void);
extern int utc_application_app_event_keep_last_event_data_p(void);
extern int utc_application_app_event_keep_last_event_data_n(void);
extern int utc_application_app_control_send_launch_request_async_p1(void);
extern int utc_application_app_control_send_launch_request_async_p2(void);
extern int utc_application_app_control_send_launch_request_async_p3(void);
extern int utc_application_app_control_send_launch_request_async_p4(void);
extern int utc_application_app_control_send_launch_request_async_n1(void);
extern int utc_application_app_control_send_launch_request_async_n2(void);
extern int utc_application_app_control_send_launch_request_async_n3(void);
extern int utc_application_app_control_send_launch_request_async_n4(void);
extern int utc_application_app_get_display_state_p(void);
extern int utc_application_app_get_display_state_n(void);
extern int utc_application_app_watchdog_timer_enable_p(void);
extern int utc_application_app_watchdog_timer_disable_p(void);
extern int utc_application_app_watchdog_timer_disable_n(void);
extern int utc_application_app_watchdog_timer_kick_p(void);
extern int utc_application_app_watchdog_timer_kick_n(void);
extern int utc_application_app_control_create_with_parameters_p(void);
extern int utc_application_app_control_create_with_parameters_n(void);
extern int utc_application_app_control_send_launch_request_sync_p(void);
extern int utc_application_app_control_send_launch_request_sync_n1(void);
extern int utc_application_app_control_send_launch_request_sync_n2(void);
extern int utc_application_app_control_add_action_handler_p(void);
extern int utc_application_app_control_add_action_handler_n1(void);
extern int utc_application_app_control_add_action_handler_n2(void);
extern int utc_application_app_control_add_action_handler_n3(void);
extern int utc_application_app_control_add_action_handler_n4(void);
extern int utc_application_app_control_remove_action_handler_p(void);
extern int utc_application_app_control_remove_action_handler_n(void);
extern int utc_application_app_control_create_from_uri_handle_p(void);
extern int utc_application_app_control_create_from_uri_handle_n1(void);
extern int utc_application_app_control_create_from_uri_handle_n2(void);
extern int utc_application_app_control_set_uri_by_handle_p(void);
extern int utc_application_app_control_set_uri_by_handle_n1(void);
extern int utc_application_app_control_set_uri_by_handle_n2(void);
extern void utc_application_app_control_uri_startup(void);
extern void utc_application_app_control_uri_cleanup(void);
extern int utc_application_app_control_uri_create_p(void);
extern int utc_application_app_control_uri_create_n1(void);
extern int utc_application_app_control_uri_create_n2(void);
extern int utc_application_app_control_uri_destroy_p(void);
extern int utc_application_app_control_uri_destroy_n(void);
extern int utc_application_app_control_uri_builder_create_p(void);
extern int utc_application_app_control_uri_builder_create_n(void);
extern int utc_application_app_control_uri_set_scheme_p(void);
extern int utc_application_app_control_uri_set_scheme_n1(void);
extern int utc_application_app_control_uri_set_scheme_n2(void);
extern int utc_application_app_control_uri_set_authority_p(void);
extern int utc_application_app_control_uri_set_authority_n1(void);
extern int utc_application_app_control_uri_set_authority_n2(void);
extern int utc_application_app_control_uri_set_path_p(void);
extern int utc_application_app_control_uri_set_path_n1(void);
extern int utc_application_app_control_uri_set_path_n2(void);
extern int utc_application_app_control_uri_add_path_p(void);
extern int utc_application_app_control_uri_add_path_n1(void);
extern int utc_application_app_control_uri_add_path_n2(void);
extern int utc_application_app_control_uri_set_fragment_p(void);
extern int utc_application_app_control_uri_set_fragment_n1(void);
extern int utc_application_app_control_uri_set_fragment_n2(void);
extern int utc_application_app_control_uri_add_query_p(void);
extern int utc_application_app_control_uri_add_query_n1(void);
extern int utc_application_app_control_uri_add_query_n2(void);
extern int utc_application_app_control_uri_add_query_n3(void);
extern int utc_application_app_control_uri_builder_build_p(void);
extern int utc_application_app_control_uri_builder_build_n1(void);
extern int utc_application_app_control_uri_builder_build_n2(void);
extern int utc_application_app_control_uri_builder_destroy_p(void);
extern int utc_application_app_control_uri_builder_destroy_n(void);
extern int utc_application_app_control_uri_encode_p(void);
extern int utc_application_app_control_uri_encode_n(void);
extern int utc_application_app_control_uri_get_scheme_p(void);
extern int utc_application_app_control_uri_get_scheme_n(void);
extern int utc_application_app_control_uri_get_authority_p(void);
extern int utc_application_app_control_uri_get_authority_n(void);
extern int utc_application_app_control_uri_get_path_p(void);
extern int utc_application_app_control_uri_get_path_n(void);
extern int utc_application_app_control_uri_get_fragment_p(void);
extern int utc_application_app_control_uri_get_fragment_n(void);
extern int utc_application_app_control_uri_get_host_p(void);
extern int utc_application_app_control_uri_get_host_n(void);
extern int utc_application_app_control_uri_get_port_p(void);
extern int utc_application_app_control_uri_get_port_n(void);
extern int utc_application_app_control_uri_get_user_p(void);
extern int utc_application_app_control_uri_get_user_n(void);
extern int utc_application_app_control_uri_get_query_p(void);
extern int utc_application_app_control_uri_get_query_n(void);
extern int utc_application_app_control_uri_query_foreach_p(void);
extern int utc_application_app_control_uri_query_foreach_n1(void);
extern int utc_application_app_control_uri_query_foreach_n2(void);


testcase tc_array[] = {
	{"utc_application_app_get_name_p",utc_application_app_get_name_p,NULL,NULL},
	{"utc_application_app_get_name_n",utc_application_app_get_name_n,NULL,NULL},
	{"utc_application_app_get_version_p",utc_application_app_get_version_p,NULL,NULL},
	{"utc_application_app_get_version_n",utc_application_app_get_version_n,NULL,NULL},
	{"utc_application_app_get_device_orientation_p",utc_application_app_get_device_orientation_p,NULL,NULL},
	{"utc_application_app_get_id_p",utc_application_app_get_id_p,NULL,NULL},
	{"utc_application_app_get_id_n",utc_application_app_get_id_n,NULL,NULL},
	{"utc_application_app_get_cache_path_p",utc_application_app_get_cache_path_p,NULL,NULL},
	{"utc_application_app_get_data_path_p",utc_application_app_get_data_path_p,NULL,NULL},
	{"utc_application_app_get_resource_path_p",utc_application_app_get_resource_path_p,NULL,NULL},
	{"utc_application_app_get_external_cache_path_p",utc_application_app_get_external_cache_path_p,NULL,NULL},
	{"utc_application_app_get_external_data_path_p",utc_application_app_get_external_data_path_p,NULL,NULL},
	{"utc_application_app_get_external_shared_data_path_p",utc_application_app_get_external_shared_data_path_p,NULL,NULL},
	{"utc_application_app_get_shared_data_path_p",utc_application_app_get_shared_data_path_p,NULL,NULL},
	{"utc_application_app_get_shared_resource_path_p",utc_application_app_get_shared_resource_path_p,NULL,NULL},
	{"utc_application_app_get_shared_trusted_path_p",utc_application_app_get_shared_trusted_path_p,NULL,NULL},
	{"utc_application_app_get_tep_resource_path_p",utc_application_app_get_tep_resource_path_p,NULL,NULL},
	{"utc_application_app_event_get_low_memory_status_n",utc_application_app_event_get_low_memory_status_n,NULL,NULL},
	{"utc_application_app_event_get_low_battery_status_n",utc_application_app_event_get_low_battery_status_n,NULL,NULL},
	{"utc_application_app_event_get_language_n",utc_application_app_event_get_language_n,NULL,NULL},
	{"utc_application_app_event_get_device_orientation_n",utc_application_app_event_get_device_orientation_n,NULL,NULL},
	{"utc_application_app_event_get_region_format_n",utc_application_app_event_get_region_format_n,NULL,NULL},
	{"utc_application_app_event_get_suspended_state_n",utc_application_app_event_get_suspended_state_n,NULL,NULL},
	{"utc_application_ui_app_main_n",utc_application_ui_app_main_n,NULL,NULL},
	{"utc_application_ui_app_add_event_handler_p",utc_application_ui_app_add_event_handler_p,NULL,NULL},
	{"utc_application_ui_app_add_event_handler_n",utc_application_ui_app_add_event_handler_n,NULL,NULL},
	{"utc_application_ui_app_remove_event_handler_p",utc_application_ui_app_remove_event_handler_p,NULL,NULL},
	{"utc_application_ui_app_remove_event_handler_n",utc_application_ui_app_remove_event_handler_n,NULL,NULL},
	{"utc_application_ui_app_exit_p",utc_application_ui_app_exit_p,NULL,NULL},
	{"utc_application_app_get_display_state_p",utc_application_app_get_display_state_p,utc_application_app_get_display_state_startup,utc_application_app_get_display_state_cleanup},
	{"utc_application_app_get_display_state_n",utc_application_app_get_display_state_n,NULL,NULL},
	{"utc_application_i18n_get_text_p",utc_application_i18n_get_text_p,NULL,NULL},
	{"utc_application_i18n_get_text_n1",utc_application_i18n_get_text_n1,NULL,NULL},
	{"utc_application_i18n_get_text_n2",utc_application_i18n_get_text_n2,NULL,NULL},
	{"utc_application_i18n_get_text_n3",utc_application_i18n_get_text_n3,NULL,NULL},
	{"utc_application_preference_set_int_p",utc_application_preference_set_int_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_int_n",utc_application_preference_set_int_n,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_double_p",utc_application_preference_set_double_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_double_n",utc_application_preference_set_double_n,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_string_p",utc_application_preference_set_string_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_string_n1",utc_application_preference_set_string_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_string_n2",utc_application_preference_set_string_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_boolean_p",utc_application_preference_set_boolean_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_boolean_n",utc_application_preference_set_boolean_n,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_int_p",utc_application_preference_get_int_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_int_n1",utc_application_preference_get_int_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_int_n2",utc_application_preference_get_int_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_int_n3",utc_application_preference_get_int_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_double_p",utc_application_preference_get_double_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_double_n1",utc_application_preference_get_double_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_double_n2",utc_application_preference_get_double_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_double_n3",utc_application_preference_get_double_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_string_p",utc_application_preference_get_string_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_string_n1",utc_application_preference_get_string_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_string_n2",utc_application_preference_get_string_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_string_n3",utc_application_preference_get_string_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_boolean_p",utc_application_preference_get_boolean_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_boolean_n1",utc_application_preference_get_boolean_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_boolean_n2",utc_application_preference_get_boolean_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_boolean_n3",utc_application_preference_get_boolean_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_remove_p",utc_application_preference_remove_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_remove_n1",utc_application_preference_remove_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_remove_n2",utc_application_preference_remove_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_remove_all_p",utc_application_preference_remove_all_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_is_existing_p1",utc_application_preference_is_existing_p1,utc_application_preference_startup,NULL},
	{"utc_application_preference_is_existing_p2",utc_application_preference_is_existing_p2,utc_application_preference_startup,NULL},
	{"utc_application_preference_is_existing_n1",utc_application_preference_is_existing_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_is_existing_n2",utc_application_preference_is_existing_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_is_existing_n3",utc_application_preference_is_existing_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_changed_cb_p1",utc_application_preference_set_changed_cb_p1,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_changed_cb_p2",utc_application_preference_set_changed_cb_p2,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_changed_cb_n1",utc_application_preference_set_changed_cb_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_changed_cb_n2",utc_application_preference_set_changed_cb_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_set_changed_cb_n3",utc_application_preference_set_changed_cb_n3,utc_application_preference_startup,NULL},
	{"utc_application_preference_unset_changed_cb_p1",utc_application_preference_unset_changed_cb_p1,utc_application_preference_startup,NULL},
	{"utc_application_preference_unset_changed_cb_n1",utc_application_preference_unset_changed_cb_n1,utc_application_preference_startup,NULL},
	{"utc_application_preference_unset_changed_cb_n2",utc_application_preference_unset_changed_cb_n2,utc_application_preference_startup,NULL},
	{"utc_application_preference_foreach_item_p",utc_application_preference_foreach_item_p,utc_application_preference_startup,NULL},
	{"utc_application_preference_foreach_item_n",utc_application_preference_foreach_item_n,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_type_n",utc_application_preference_get_type_n,utc_application_preference_startup,NULL},
	{"utc_application_preference_get_type_p",utc_application_preference_get_type_p,utc_application_preference_startup,NULL},
	{"utc_application_app_control_create_p",utc_application_app_control_create_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_create_n",utc_application_app_control_create_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_destroy_p",utc_application_app_control_destroy_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_destroy_n",utc_application_app_control_destroy_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_operation_p1",utc_application_app_control_set_operation_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_operation_p2",utc_application_app_control_set_operation_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_operation_n",utc_application_app_control_set_operation_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_operation_p",utc_application_app_control_get_operation_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_operation_n1",utc_application_app_control_get_operation_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_operation_n2",utc_application_app_control_get_operation_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_operation_n3",utc_application_app_control_get_operation_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_uri_p1",utc_application_app_control_set_uri_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_uri_p2",utc_application_app_control_set_uri_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_uri_n",utc_application_app_control_set_uri_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_uri_p",utc_application_app_control_get_uri_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_uri_n1",utc_application_app_control_get_uri_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_uri_n2",utc_application_app_control_get_uri_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_uri_n3",utc_application_app_control_get_uri_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_mime_p1",utc_application_app_control_set_mime_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_mime_p2",utc_application_app_control_set_mime_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_mime_n",utc_application_app_control_set_mime_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_mime_p",utc_application_app_control_get_mime_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_mime_n1",utc_application_app_control_get_mime_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_mime_n2",utc_application_app_control_get_mime_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_mime_n3",utc_application_app_control_get_mime_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_app_id_p1",utc_application_app_control_set_app_id_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_app_id_p2",utc_application_app_control_set_app_id_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_app_id_n1",utc_application_app_control_set_app_id_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_app_id_n2",utc_application_app_control_set_app_id_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_app_id_p",utc_application_app_control_get_app_id_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_app_id_n1",utc_application_app_control_get_app_id_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_app_id_n2",utc_application_app_control_get_app_id_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_app_id_n3",utc_application_app_control_get_app_id_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_category_p1",utc_application_app_control_set_category_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_category_p2",utc_application_app_control_set_category_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_category_n1",utc_application_app_control_set_category_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_category_n2",utc_application_app_control_set_category_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_category_p",utc_application_app_control_get_category_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_category_n1",utc_application_app_control_get_category_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_category_n2",utc_application_app_control_get_category_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_category_n3",utc_application_app_control_get_category_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_p",utc_application_app_control_add_extra_data_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_n1",utc_application_app_control_add_extra_data_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_n2",utc_application_app_control_add_extra_data_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_n3",utc_application_app_control_add_extra_data_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_remove_extra_data_p",utc_application_app_control_remove_extra_data_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_remove_extra_data_n1",utc_application_app_control_remove_extra_data_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_remove_extra_data_n2",utc_application_app_control_remove_extra_data_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_remove_extra_data_n3",utc_application_app_control_remove_extra_data_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_remove_extra_data_n4",utc_application_app_control_remove_extra_data_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_p",utc_application_app_control_get_extra_data_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_n1",utc_application_app_control_get_extra_data_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_n2",utc_application_app_control_get_extra_data_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_n3",utc_application_app_control_get_extra_data_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_n4",utc_application_app_control_get_extra_data_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_n5",utc_application_app_control_get_extra_data_n5,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n6",utc_application_app_control_get_extra_data_array_n6,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_extra_data_p",utc_application_app_control_foreach_extra_data_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_extra_data_n1",utc_application_app_control_foreach_extra_data_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_extra_data_n2",utc_application_app_control_foreach_extra_data_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_clone_p",utc_application_app_control_clone_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_clone_n1",utc_application_app_control_clone_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_clone_n2",utc_application_app_control_clone_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_p1",utc_application_app_control_send_launch_request_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_p2",utc_application_app_control_send_launch_request_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_p3",utc_application_app_control_send_launch_request_p3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_p4",utc_application_app_control_send_launch_request_p4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_n1",utc_application_app_control_send_launch_request_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_n2",utc_application_app_control_send_launch_request_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_n3",utc_application_app_control_send_launch_request_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_n4",utc_application_app_control_send_launch_request_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_reply_to_launch_request_n1",utc_application_app_control_reply_to_launch_request_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_reply_to_launch_request_n2",utc_application_app_control_reply_to_launch_request_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_reply_to_launch_request_n3",utc_application_app_control_reply_to_launch_request_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_app_matched_p",utc_application_app_control_foreach_app_matched_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_app_matched_n1",utc_application_app_control_foreach_app_matched_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_foreach_app_matched_n2",utc_application_app_control_foreach_app_matched_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_array_p",utc_application_app_control_add_extra_data_array_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_array_n1",utc_application_app_control_add_extra_data_array_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_array_n2",utc_application_app_control_add_extra_data_array_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_array_n3",utc_application_app_control_add_extra_data_array_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_add_extra_data_array_n4",utc_application_app_control_add_extra_data_array_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_p",utc_application_app_control_get_extra_data_array_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n1",utc_application_app_control_get_extra_data_array_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n2",utc_application_app_control_get_extra_data_array_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n3",utc_application_app_control_get_extra_data_array_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n4",utc_application_app_control_get_extra_data_array_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_extra_data_array_n5",utc_application_app_control_get_extra_data_array_n5,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_p1",utc_application_app_control_is_extra_data_array_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_p2",utc_application_app_control_is_extra_data_array_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_n1",utc_application_app_control_is_extra_data_array_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_n2",utc_application_app_control_is_extra_data_array_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_n3",utc_application_app_control_is_extra_data_array_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_extra_data_array_n4",utc_application_app_control_is_extra_data_array_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_reply_requested_n1",utc_application_app_control_is_reply_requested_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_reply_requested_n2",utc_application_app_control_is_reply_requested_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_reply_requested_n3",utc_application_app_control_is_reply_requested_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_is_reply_requested_n4",utc_application_app_control_is_reply_requested_n4,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_caller_n1",utc_application_app_control_get_caller_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_caller_n2",utc_application_app_control_get_caller_n2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_caller_n3",utc_application_app_control_get_caller_n3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_terminate_request_p",utc_application_app_control_send_terminate_request_p,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_terminate_request_n",utc_application_app_control_send_terminate_request_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_launch_mode_p1",utc_application_app_control_set_launch_mode_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_launch_mode_p2",utc_application_app_control_set_launch_mode_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_set_launch_mode_n",utc_application_app_control_set_launch_mode_n,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_launch_mode_p1",utc_application_app_control_get_launch_mode_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_launch_mode_p2",utc_application_app_control_get_launch_mode_p2,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_launch_mode_p3",utc_application_app_control_get_launch_mode_p3,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_get_launch_mode_n1",utc_application_app_control_get_launch_mode_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_enable_app_started_result_event_p1",utc_application_app_control_enable_app_started_result_event_p1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_enable_app_started_result_event_n1",utc_application_app_control_enable_app_started_result_event_n1,utc_application_app_control_startup,NULL},
	{"utc_application_app_control_send_launch_request_async_p1", utc_application_app_control_send_launch_request_async_p1, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_p2", utc_application_app_control_send_launch_request_async_p2, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_p3", utc_application_app_control_send_launch_request_async_p3, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_p4", utc_application_app_control_send_launch_request_async_p4, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_n1", utc_application_app_control_send_launch_request_async_n1, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_n2", utc_application_app_control_send_launch_request_async_n2, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_n3", utc_application_app_control_send_launch_request_async_n3, NULL, NULL},
	{"utc_application_app_control_send_launch_request_async_n4", utc_application_app_control_send_launch_request_async_n4, NULL, NULL},
	{"utc_application_app_control_create_with_parameters_p", utc_application_app_control_create_with_parameters_p, NULL, NULL},
	{"utc_application_app_control_create_with_parameters_n", utc_application_app_control_create_with_parameters_n, NULL, NULL},
	{"utc_application_app_control_send_launch_request_sync_p", utc_application_app_control_send_launch_request_sync_p, NULL, NULL},
	{"utc_application_app_control_send_launch_request_sync_n1", utc_application_app_control_send_launch_request_sync_n1, NULL, NULL},
	{"utc_application_app_control_send_launch_request_sync_n2", utc_application_app_control_send_launch_request_sync_n2, NULL, NULL},
	{"utc_application_app_control_add_action_handler_p", utc_application_app_control_add_action_handler_p, NULL, NULL},
	{"utc_application_app_control_add_action_handler_n1", utc_application_app_control_add_action_handler_n1, NULL, NULL},
	{"utc_application_app_control_add_action_handler_n2", utc_application_app_control_add_action_handler_n2, NULL, NULL},
	{"utc_application_app_control_add_action_handler_n3", utc_application_app_control_add_action_handler_n3, NULL, NULL},
	{"utc_application_app_control_add_action_handler_n4", utc_application_app_control_add_action_handler_n4, NULL, NULL},
	{"utc_application_app_control_remove_action_handler_p", utc_application_app_control_remove_action_handler_p, NULL, NULL},
	{"utc_application_app_control_remove_action_handler_n", utc_application_app_control_remove_action_handler_n, NULL, NULL},
	{"utc_application_app_control_create_from_uri_handle_p", utc_application_app_control_create_from_uri_handle_p, NULL, NULL},
	{"utc_application_app_control_create_from_uri_handle_n1", utc_application_app_control_create_from_uri_handle_n1, NULL, NULL},
	{"utc_application_app_control_create_from_uri_handle_n2", utc_application_app_control_create_from_uri_handle_n2, NULL, NULL},
	{"utc_application_app_control_set_uri_by_handle_p", utc_application_app_control_set_uri_by_handle_p, NULL, NULL},
	{"utc_application_app_control_set_uri_by_handle_n1", utc_application_app_control_set_uri_by_handle_n1, NULL, NULL},
	{"utc_application_app_control_set_uri_by_handle_n2", utc_application_app_control_set_uri_by_handle_n2, NULL, NULL},
	{"utc_application_app_control_set_component_id_p1", utc_application_app_control_set_component_id_p1, NULL, NULL},
	{"utc_application_app_control_set_component_id_n1", utc_application_app_control_set_component_id_n1, NULL, NULL},
	{"utc_application_app_control_get_component_id_p1", utc_application_app_control_get_component_id_p1, NULL, NULL},
	{"utc_application_app_control_get_component_id_n1", utc_application_app_control_get_component_id_n1, NULL, NULL},
	{"utc_application_app_control_uri_create_p", utc_application_app_control_uri_create_p, NULL, NULL},
	{"utc_application_app_control_uri_create_n1", utc_application_app_control_uri_create_n1, NULL, NULL},
	{"utc_application_app_control_uri_create_n2", utc_application_app_control_uri_create_n2, NULL, NULL},
	{"utc_application_app_control_uri_destroy_p", utc_application_app_control_uri_destroy_p, NULL, NULL},
	{"utc_application_app_control_uri_destroy_n", utc_application_app_control_uri_destroy_n, NULL, NULL},
	{"utc_application_app_control_uri_builder_create_p", utc_application_app_control_uri_builder_create_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_create_n", utc_application_app_control_uri_builder_create_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_scheme_p", utc_application_app_control_uri_set_scheme_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_scheme_n1", utc_application_app_control_uri_set_scheme_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_scheme_n2", utc_application_app_control_uri_set_scheme_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_authority_p", utc_application_app_control_uri_set_authority_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_authority_n1", utc_application_app_control_uri_set_authority_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_authority_n2", utc_application_app_control_uri_set_authority_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_path_p", utc_application_app_control_uri_set_path_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_path_n1", utc_application_app_control_uri_set_path_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_path_n2", utc_application_app_control_uri_set_path_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_path_p", utc_application_app_control_uri_add_path_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_path_n1", utc_application_app_control_uri_add_path_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_path_n2", utc_application_app_control_uri_add_path_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_fragment_p", utc_application_app_control_uri_set_fragment_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_fragment_n1", utc_application_app_control_uri_set_fragment_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_set_fragment_n2", utc_application_app_control_uri_set_fragment_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_query_p", utc_application_app_control_uri_add_query_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_query_n1", utc_application_app_control_uri_add_query_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_query_n2", utc_application_app_control_uri_add_query_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_add_query_n3", utc_application_app_control_uri_add_query_n3, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_build_p", utc_application_app_control_uri_builder_build_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_build_n1", utc_application_app_control_uri_builder_build_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_build_n2", utc_application_app_control_uri_builder_build_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_destroy_p", utc_application_app_control_uri_builder_destroy_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_builder_destroy_n", utc_application_app_control_uri_builder_destroy_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_encode_p", utc_application_app_control_uri_encode_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_encode_n", utc_application_app_control_uri_encode_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_scheme_p", utc_application_app_control_uri_get_scheme_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_scheme_n", utc_application_app_control_uri_get_scheme_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_authority_p", utc_application_app_control_uri_get_authority_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_authority_n", utc_application_app_control_uri_get_authority_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_path_p", utc_application_app_control_uri_get_path_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_path_n", utc_application_app_control_uri_get_path_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_fragment_p", utc_application_app_control_uri_get_fragment_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_fragment_n", utc_application_app_control_uri_get_fragment_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_host_p", utc_application_app_control_uri_get_host_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_host_n", utc_application_app_control_uri_get_host_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_port_p", utc_application_app_control_uri_get_port_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_port_n", utc_application_app_control_uri_get_port_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_user_p", utc_application_app_control_uri_get_user_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_user_n", utc_application_app_control_uri_get_user_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_query_p", utc_application_app_control_uri_get_query_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_get_query_n", utc_application_app_control_uri_get_query_n, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_query_foreach_p", utc_application_app_control_uri_query_foreach_p, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_query_foreach_n1", utc_application_app_control_uri_query_foreach_n1, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_control_uri_query_foreach_n2", utc_application_app_control_uri_query_foreach_n2, utc_application_app_control_uri_startup, utc_application_app_control_uri_cleanup},
	{"utc_application_app_resource_manager_get_p1",utc_application_app_resource_manager_get_p1,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_p2",utc_application_app_resource_manager_get_p2,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_p3",utc_application_app_resource_manager_get_p3,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_p4",utc_application_app_resource_manager_get_p4,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_p5",utc_application_app_resource_manager_get_p5,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_n1",utc_application_app_resource_manager_get_n1,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_n2",utc_application_app_resource_manager_get_n2,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_resource_manager_get_n3",utc_application_app_resource_manager_get_n3,utc_application_app_resource_manager_startup,utc_application_app_resource_manager_cleanup},
	{"utc_application_app_event_add_event_handler_p1",utc_application_app_event_add_event_handler_p1,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p2",utc_application_app_event_add_event_handler_p2,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p3",utc_application_app_event_add_event_handler_p3,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p4",utc_application_app_event_add_event_handler_p4,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p5",utc_application_app_event_add_event_handler_p5,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p6",utc_application_app_event_add_event_handler_p6,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p7",utc_application_app_event_add_event_handler_p7,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p8",utc_application_app_event_add_event_handler_p8,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p9",utc_application_app_event_add_event_handler_p9,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p10",utc_application_app_event_add_event_handler_p10,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p11",utc_application_app_event_add_event_handler_p11,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p12",utc_application_app_event_add_event_handler_p12,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p13",utc_application_app_event_add_event_handler_p13,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p14",utc_application_app_event_add_event_handler_p14,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p15",utc_application_app_event_add_event_handler_p15,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p16",utc_application_app_event_add_event_handler_p16,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p17",utc_application_app_event_add_event_handler_p17,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p18",utc_application_app_event_add_event_handler_p18,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p19",utc_application_app_event_add_event_handler_p19,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p20",utc_application_app_event_add_event_handler_p20,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p21",utc_application_app_event_add_event_handler_p21,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p22",utc_application_app_event_add_event_handler_p22,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p23",utc_application_app_event_add_event_handler_p23,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p24",utc_application_app_event_add_event_handler_p24,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p25",utc_application_app_event_add_event_handler_p25,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p26",utc_application_app_event_add_event_handler_p26,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_p27",utc_application_app_event_add_event_handler_p27,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_n1",utc_application_app_event_add_event_handler_n1,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_n2",utc_application_app_event_add_event_handler_n2,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_n3",utc_application_app_event_add_event_handler_n3,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_add_event_handler_n4",utc_application_app_event_add_event_handler_n4,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_remove_event_handler_p",utc_application_app_event_remove_event_handler_p,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_remove_event_handler_n",utc_application_app_event_remove_event_handler_n,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_app_event_p1",utc_application_app_event_publish_app_event_p1,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_app_event_p2",utc_application_app_event_publish_app_event_p2,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_app_event_n1",utc_application_app_event_publish_app_event_n1,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_app_event_n2",utc_application_app_event_publish_app_event_n2,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_app_event_n3",utc_application_app_event_publish_app_event_n3,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_p",utc_application_app_event_publish_trusted_app_event_p,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_n1",utc_application_app_event_publish_trusted_app_event_n1,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_n2",utc_application_app_event_publish_trusted_app_event_n2,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_n3",utc_application_app_event_publish_trusted_app_event_n3,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_n4",utc_application_app_event_publish_trusted_app_event_n4,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_publish_trusted_app_event_n5",utc_application_app_event_publish_trusted_app_event_n5,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_keep_last_event_data_p",utc_application_app_event_keep_last_event_data_p,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_event_keep_last_event_data_n",utc_application_app_event_keep_last_event_data_n,utc_application_app_event_startup,utc_application_app_event_cleanup},
	{"utc_application_app_watchdog_timer_enable_p", utc_application_app_watchdog_timer_enable_p, NULL, utc_application_app_watchdog_timer_enable_p_cleanup},
	{"utc_application_app_watchdog_timer_disable_p", utc_application_app_watchdog_timer_disable_p, utc_application_app_watchdog_timer_disable_p_startup, NULL},
	{"utc_application_app_watchdog_timer_disable_n", utc_application_app_watchdog_timer_disable_n, NULL, NULL},
	{"utc_application_app_watchdog_timer_kick_p", utc_application_app_watchdog_timer_kick_p, utc_application_app_watchdog_timer_kick_p_startup, utc_application_app_watchdog_timer_kick_p_cleanup},
	{"utc_application_app_watchdog_timer_kick_n", utc_application_app_watchdog_timer_kick_n, NULL, NULL},
	{NULL, NULL}
};

#endif // __TCT_APPLICATION-NATIVE_H__
