//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_PHONENUMBER_UTILS_CORE_H__
#define __TCT_PHONENUMBER_UTILS_CORE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_phonenumber_utils_service_startup(void);
extern void utc_phonenumber_utils_service_cleanup(void);
extern void utc_phonenumber_utils_startup(void);
extern void utc_phonenumber_utils_cleanup(void);
extern void utc_phonenumber_utils_blocking_rule_startup(void);
extern void utc_phonenumber_utils_blocking_rule_cleanup(void);

extern int utc_phonenumber_utils_service_phone_number_disconnect_p(void);
extern int utc_phonenumber_utils_service_phone_number_get_location_from_number_p(void);
extern int utc_phonenumber_utils_service_phone_number_get_location_from_number2_p(void);
extern int utc_phonenumber_utils_service_phone_number_get_location_from_number_n(void);
extern int utc_phonenumber_utils_service_phone_number_get_formatted_number_p(void);
extern int utc_phonenumber_utils_service_phone_number_get_formatted_number_n(void);
extern int utc_phonenumber_utils_service_phone_number_get_normalized_number_p(void);
extern int utc_phonenumber_utils_service_phone_number_get_normalized_number_n(void);
extern int utc_phonenumber_utils_blocking_rule_create_p(void);
extern int utc_phonenumber_utils_blocking_rule_destroy_p(void);
extern int utc_phonenumber_utils_blocking_rule_get_number_p(void);
extern int utc_phonenumber_utils_blocking_rule_get_match_type_p(void);
extern int utc_phonenumber_utils_blocking_rule_set_number_p(void);
extern int utc_phonenumber_utils_blocking_rule_set_match_type_p(void);
extern int utc_phonenumber_utils_blocking_rule_create_n(void);
extern int utc_phonenumber_utils_blocking_rule_destroy_n(void);
extern int utc_phonenumber_utils_blocking_rule_get_number_n(void);
extern int utc_phonenumber_utils_blocking_rule_get_match_type_n(void);
extern int utc_phonenumber_utils_blocking_rule_set_number_n(void);
extern int utc_phonenumber_utils_blocking_rule_set_match_type_n(void);


testcase tc_array[] = {
	{"utc_phonenumber_utils_service_phone_number_disconnect_p", utc_phonenumber_utils_service_phone_number_disconnect_p, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_location_from_number_p", utc_phonenumber_utils_service_phone_number_get_location_from_number_p, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_location_from_number2_p", utc_phonenumber_utils_service_phone_number_get_location_from_number2_p, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_location_from_number_n", utc_phonenumber_utils_service_phone_number_get_location_from_number_n, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_formatted_number_p", utc_phonenumber_utils_service_phone_number_get_formatted_number_p, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_formatted_number_n", utc_phonenumber_utils_service_phone_number_get_formatted_number_n, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_normalized_number_p", utc_phonenumber_utils_service_phone_number_get_normalized_number_p, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_service_phone_number_get_normalized_number_n", utc_phonenumber_utils_service_phone_number_get_normalized_number_n, utc_phonenumber_utils_service_startup, utc_phonenumber_utils_service_cleanup},
	{"utc_phonenumber_utils_blocking_rule_create_p", utc_phonenumber_utils_blocking_rule_create_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_create_n", utc_phonenumber_utils_blocking_rule_create_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_destroy_p", utc_phonenumber_utils_blocking_rule_destroy_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_destroy_n", utc_phonenumber_utils_blocking_rule_destroy_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_get_number_p", utc_phonenumber_utils_blocking_rule_get_number_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_get_number_n", utc_phonenumber_utils_blocking_rule_get_number_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_get_match_type_p", utc_phonenumber_utils_blocking_rule_get_match_type_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_get_match_type_n", utc_phonenumber_utils_blocking_rule_get_match_type_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_set_number_p", utc_phonenumber_utils_blocking_rule_set_number_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_set_number_n", utc_phonenumber_utils_blocking_rule_set_number_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_set_match_type_p", utc_phonenumber_utils_blocking_rule_set_match_type_p, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{"utc_phonenumber_utils_blocking_rule_set_match_type_n", utc_phonenumber_utils_blocking_rule_set_match_type_n, utc_phonenumber_utils_blocking_rule_startup, utc_phonenumber_utils_blocking_rule_cleanup},
	{NULL, NULL}
};

#endif // __TCT_PHONENUMBER_UTILS_CORE_H__
