//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_IMAGE-UTIL-NATIVE_H__
#define __TCT_IMAGE-UTIL-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_image_util_decode_startup(void);
extern void utc_image_util_decode_cleanup(void);
extern void utc_image_util_encode_startup(void);
extern void utc_image_util_encode_cleanup(void);
extern void utc_media_image_util_basic_startup(void);
extern void utc_media_image_util_basic_cleanup(void);
extern void utc_image_util_agif_encode_startup(void);
extern void utc_image_util_agif_encode_cleanup(void);
extern void utc_image_util_anim_encode_startup(void);
extern void utc_image_util_anim_encode_cleanup(void);

extern int utc_image_util_foreach_supported_colorspace_n1(void);
extern int utc_image_util_foreach_supported_colorspace_n2(void);
extern int utc_image_util_foreach_supported_colorspace_p(void);
extern int utc_image_util_decode_create_n1(void);
extern int utc_image_util_decode_create_p(void);
extern int utc_image_util_decode_set_input_path_n1(void);
extern int utc_image_util_decode_set_input_path_n2(void);
extern int utc_image_util_decode_set_input_path_n3(void);
extern int utc_image_util_decode_set_input_path_n4(void);
extern int utc_image_util_decode_set_input_path_p(void);
extern int utc_image_util_decode_set_input_buffer_n1(void);
extern int utc_image_util_decode_set_input_buffer_n2(void);
extern int utc_image_util_decode_set_input_buffer_n3(void);
extern int utc_image_util_decode_set_input_buffer_n4(void);
extern int utc_image_util_decode_set_input_buffer_p(void);
extern int utc_image_util_decode_set_output_buffer_n1(void);
extern int utc_image_util_decode_set_output_buffer_n2(void);
extern int utc_image_util_decode_set_output_buffer_n3(void);
extern int utc_image_util_decode_set_output_buffer_p(void);
extern int utc_image_util_decode_set_colorspace_n1(void);
extern int utc_image_util_decode_set_colorspace_n2(void);
extern int utc_image_util_decode_set_colorspace_n3(void);
extern int utc_image_util_decode_set_colorspace_n4(void);
extern int utc_image_util_decode_set_colorspace_n5(void);
extern int utc_image_util_decode_set_colorspace_n6(void);
extern int utc_image_util_decode_set_colorspace_n7(void);
extern int utc_image_util_decode_set_colorspace_p1(void);
extern int utc_image_util_decode_set_colorspace_p2(void);
extern int utc_image_util_decode_set_colorspace_p3(void);
extern int utc_image_util_decode_set_colorspace_p4(void);
extern int utc_image_util_decode_set_jpeg_downscale_n1(void);
extern int utc_image_util_decode_set_jpeg_downscale_n2(void);
extern int utc_image_util_decode_set_jpeg_downscale_n3(void);
extern int utc_image_util_decode_set_jpeg_downscale_n4(void);
extern int utc_image_util_decode_set_jpeg_downscale_p(void);
extern int utc_image_util_decode_run_n1(void);
extern int utc_image_util_decode_run_n2(void);
extern int utc_image_util_decode_run_n3(void);
extern int utc_image_util_decode_run_n4(void);
extern int utc_image_util_decode_run_n5(void);
extern int utc_image_util_decode_run_p1(void);
extern int utc_image_util_decode_run_p2(void);
extern int utc_image_util_decode_run2_n(void);
extern int utc_image_util_decode_run2_p1(void);
extern int utc_image_util_decode_run2_p2(void);
extern int utc_image_util_decode_run_async_n1(void);
extern int utc_image_util_decode_run_async_n2(void);
extern int utc_image_util_decode_run_async_n3(void);
extern int utc_image_util_decode_run_async_n4(void);
extern int utc_image_util_decode_run_async_n5(void);
extern int utc_image_util_decode_run_async_n6(void);
extern int utc_image_util_decode_run_async_p1(void);
extern int utc_image_util_decode_run_async_p2(void);
extern int utc_image_util_decode_run_async2_n(void);
extern int utc_image_util_decode_run_async2_p1(void);
extern int utc_image_util_decode_run_async2_p2(void);
extern int utc_image_util_decode_destroy_n1(void);
extern int utc_image_util_decode_destroy_n2(void);
extern int utc_image_util_decode_destroy_p(void);
extern int utc_image_util_encode_create_n1(void);
extern int utc_image_util_encode_create_n2(void);
extern int utc_image_util_encode_create_p(void);
extern int utc_image_util_encode_set_resolution_n1(void);
extern int utc_image_util_encode_set_resolution_n2(void);
extern int utc_image_util_encode_set_resolution_n3(void);
extern int utc_image_util_encode_set_resolution_n4(void);
extern int utc_image_util_encode_set_resolution_p(void);
extern int utc_image_util_encode_set_colorspace_n1(void);
extern int utc_image_util_encode_set_colorspace_n2(void);
extern int utc_image_util_encode_set_colorspace_n3(void);
extern int utc_image_util_encode_set_colorspace_n4(void);
extern int utc_image_util_encode_set_colorspace_p(void);
extern int utc_image_util_encode_set_quality_n1(void);
extern int utc_image_util_encode_set_quality_n2(void);
extern int utc_image_util_encode_set_quality_n3(void);
extern int utc_image_util_encode_set_quality_n4(void);
extern int utc_image_util_encode_set_quality_p(void);
extern int utc_image_util_encode_set_png_compression_n1(void);
extern int utc_image_util_encode_set_png_compression_n2(void);
extern int utc_image_util_encode_set_png_compression_n3(void);
extern int utc_image_util_encode_set_png_compression_n4(void);
extern int utc_image_util_encode_set_png_compression_p(void);
extern int utc_image_util_encode_set_gif_frame_delay_time_n1(void);
extern int utc_image_util_encode_set_gif_frame_delay_time_n2(void);
extern int utc_image_util_encode_set_gif_frame_delay_time_n3(void);
extern int utc_image_util_encode_set_gif_frame_delay_time_p(void);
extern int utc_image_util_encode_set_webp_lossless_n1(void);
extern int utc_image_util_encode_set_webp_lossless_n2(void);
extern int utc_image_util_encode_set_webp_lossless_p(void);
extern int utc_image_util_encode_set_lossless_n1(void);
extern int utc_image_util_encode_set_lossless_n2(void);
extern int utc_image_util_encode_set_lossless_p(void);
extern int utc_image_util_encode_set_input_buffer_n1(void);
extern int utc_image_util_encode_set_input_buffer_n2(void);
extern int utc_image_util_encode_set_input_buffer_n3(void);
extern int utc_image_util_encode_set_input_buffer_p(void);
extern int utc_image_util_encode_set_output_path_n1(void);
extern int utc_image_util_encode_set_output_path_n2(void);
extern int utc_image_util_encode_set_output_path_n3(void);
extern int utc_image_util_encode_set_output_path_n4(void);
extern int utc_image_util_encode_set_output_path_p(void);
extern int utc_image_util_encode_set_output_buffer_n1(void);
extern int utc_image_util_encode_set_output_buffer_n2(void);
extern int utc_image_util_encode_set_output_buffer_n3(void);
extern int utc_image_util_encode_set_output_buffer_p(void);
extern int utc_image_util_encode_run_n1(void);
extern int utc_image_util_encode_run_n2(void);
extern int utc_image_util_encode_run_n3(void);
extern int utc_image_util_encode_run_n4(void);
extern int utc_image_util_encode_run_n5(void);
extern int utc_image_util_encode_run_n6(void);
extern int utc_image_util_encode_run_n7(void);
extern int utc_image_util_encode_run_n8(void);
extern int utc_image_util_encode_run_p1(void);
extern int utc_image_util_encode_run_p2(void);
extern int utc_image_util_encode_run_p3(void);
extern int utc_image_util_encode_run_p4(void);
extern int utc_image_util_encode_run_async_n1(void);
extern int utc_image_util_encode_run_async_n2(void);
extern int utc_image_util_encode_run_async_n3(void);
extern int utc_image_util_encode_run_async_n4(void);
extern int utc_image_util_encode_run_async_n5(void);
extern int utc_image_util_encode_run_async_n6(void);
extern int utc_image_util_encode_run_async_n7(void);
extern int utc_image_util_encode_run_async_n8(void);
extern int utc_image_util_encode_run_async_n9(void);
extern int utc_image_util_encode_run_async_p1(void);
extern int utc_image_util_encode_run_async_p2(void);
extern int utc_image_util_encode_run_to_file_p(void);
extern int utc_image_util_encode_run_to_file_n(void);
extern int utc_image_util_encode_run_to_buffer_p(void);
extern int utc_image_util_encode_run_to_buffer_n(void);
extern int utc_image_util_encode_run_async_to_file_p(void);
extern int utc_image_util_encode_run_async_to_file_n(void);
extern int utc_image_util_encode_run_async_to_buffer_p(void);
extern int utc_image_util_encode_run_async_to_buffer_n(void);
extern int utc_image_util_encode_destroy_n1(void);
extern int utc_image_util_encode_destroy_n2(void);
extern int utc_image_util_encode_destroy_p(void);

/* in utc-image-util-transform.c */
extern int utc_image_util_calculate_buffer_size_p1(void);
extern int utc_image_util_calculate_buffer_size_p2(void);
extern int utc_image_util_calculate_buffer_size_n1(void);
extern int utc_image_util_calculate_buffer_size_n2(void);
extern int utc_image_util_calculate_buffer_size_n3(void);
extern int utc_image_util_transform_create_n(void);
extern int utc_image_util_transform_create_p(void);
extern int utc_image_util_transform_set_hardware_acceleration_n(void);
extern int utc_image_util_transform_set_hardware_acceleration_p(void);
extern int utc_image_util_transform_set_colorspace_n(void);
extern int utc_image_util_transform_set_colorspace_p(void);
extern int utc_image_util_transform_get_colorspace_n1(void);
extern int utc_image_util_transform_get_colorspace_n2(void);
extern int utc_image_util_transform_get_colorspace_p(void);
extern int utc_image_util_transform_set_resolution_n1(void);
extern int utc_image_util_transform_set_resolution_n2(void);
extern int utc_image_util_transform_set_resolution_n3(void);
extern int utc_image_util_transform_set_resolution_p(void);
extern int utc_image_util_transform_get_resolution_n1(void);
extern int utc_image_util_transform_get_resolution_n2(void);
extern int utc_image_util_transform_get_resolution_p(void);
extern int utc_image_util_transform_set_rotation_n(void);
extern int utc_image_util_transform_set_rotation_p(void);
extern int utc_image_util_transform_get_rotation_n1(void);
extern int utc_image_util_transform_get_rotation_n2(void);
extern int utc_image_util_transform_get_rotation_p(void);
extern int utc_image_util_transform_run_n1(void);
extern int utc_image_util_transform_run_n2(void);
extern int utc_image_util_transform_run_n3(void);
extern int utc_image_util_transform_run_n4(void);
extern int utc_image_util_transform_run_p1(void);
extern int utc_image_util_transform_run_p2(void);
extern int utc_image_util_transform_run_p3(void);
extern int utc_image_util_transform_set_crop_area_n1(void);
extern int utc_image_util_transform_set_crop_area_n2(void);
extern int utc_image_util_transform_set_crop_area_n3(void);
extern int utc_image_util_transform_set_crop_area_p(void);
extern int utc_image_util_transform_get_crop_area_n1(void);
extern int utc_image_util_transform_get_crop_area_n2(void);
extern int utc_image_util_transform_get_crop_area_p(void);
extern int utc_image_util_transform_destory_n(void);
extern int utc_image_util_transform_destory_p(void);
extern int utc_image_util_extract_color_from_memory_p(void);
extern int utc_image_util_extract_color_from_memory_n(void);
extern int utc_image_util_create_image_p(void);
extern int utc_image_util_create_image_n(void);
extern int utc_image_util_clone_image_p(void);
extern int utc_image_util_clone_image_n(void);
extern int utc_image_util_get_image_p(void);
extern int utc_image_util_get_image_n(void);
extern int utc_image_util_destroy_image_p(void);
extern int utc_image_util_destroy_image_n(void);
extern int utc_image_util_transform_run2_p(void);
extern int utc_image_util_transform_run2_n(void);
extern int utc_image_util_transform_run2_async_p(void);
extern int utc_image_util_transform_run2_async_n(void);

/* in utc-image-util-agif-encode.c */
extern int utc_image_util_agif_encode_create_p(void);
extern int utc_image_util_agif_encode_create_n(void);
extern int utc_image_util_agif_encode_add_frame_p(void);
extern int utc_image_util_agif_encode_add_frame_n(void);
extern int utc_image_util_agif_encode_save_to_file_p(void);
extern int utc_image_util_agif_encode_save_to_file_n(void);
extern int utc_image_util_agif_encode_save_to_buffer_p(void);
extern int utc_image_util_agif_encode_save_to_buffer_n(void);
extern int utc_image_util_agif_encode_destroy_p(void);
extern int utc_image_util_agif_encode_destroy_n(void);

extern int utc_image_util_anim_encode_create_p(void);
extern int utc_image_util_anim_encode_create_n1(void);
extern int utc_image_util_anim_encode_create_n2(void);
extern int utc_image_util_anim_encode_set_loop_count_p(void);
extern int utc_image_util_anim_encode_set_loop_count_n(void);
extern int utc_image_util_anim_encode_set_background_color_p(void);
extern int utc_image_util_anim_encode_set_background_color_n1(void);
extern int utc_image_util_anim_encode_set_background_color_n2(void);
extern int utc_image_util_anim_encode_set_lossless_p(void);
extern int utc_image_util_anim_encode_set_lossless_n1(void);
extern int utc_image_util_anim_encode_set_lossless_n2(void);
extern int utc_image_util_anim_encode_add_frame_p(void);
extern int utc_image_util_anim_encode_add_frame_n(void);
extern int utc_image_util_anim_encode_save_to_file_p1(void);
extern int utc_image_util_anim_encode_save_to_file_p2(void);
extern int utc_image_util_anim_encode_save_to_file_n1(void);
extern int utc_image_util_anim_encode_save_to_file_n2(void);
extern int utc_image_util_anim_encode_save_to_buffer_p1(void);
extern int utc_image_util_anim_encode_save_to_buffer_p2(void);
extern int utc_image_util_anim_encode_save_to_buffer_n1(void);
extern int utc_image_util_anim_encode_save_to_buffer_n2(void);
extern int utc_image_util_anim_encode_destroy_p(void);
extern int utc_image_util_anim_encode_destroy_n(void);


testcase tc_array[] = {
	{"utc_image_util_foreach_supported_colorspace_n1",utc_image_util_foreach_supported_colorspace_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_foreach_supported_colorspace_n2",utc_image_util_foreach_supported_colorspace_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_foreach_supported_colorspace_p",utc_image_util_foreach_supported_colorspace_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_create_n1",utc_image_util_decode_create_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_create_p",utc_image_util_decode_create_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_path_n1",utc_image_util_decode_set_input_path_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_path_n2",utc_image_util_decode_set_input_path_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_path_n3",utc_image_util_decode_set_input_path_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_path_n4",utc_image_util_decode_set_input_path_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_path_p",utc_image_util_decode_set_input_path_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_buffer_n1",utc_image_util_decode_set_input_buffer_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_buffer_n2",utc_image_util_decode_set_input_buffer_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_buffer_n3",utc_image_util_decode_set_input_buffer_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_buffer_n4",utc_image_util_decode_set_input_buffer_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_input_buffer_p",utc_image_util_decode_set_input_buffer_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_output_buffer_n1",utc_image_util_decode_set_output_buffer_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_output_buffer_n2",utc_image_util_decode_set_output_buffer_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_output_buffer_n3",utc_image_util_decode_set_output_buffer_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_output_buffer_p",utc_image_util_decode_set_output_buffer_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n1",utc_image_util_decode_set_colorspace_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n2",utc_image_util_decode_set_colorspace_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n3",utc_image_util_decode_set_colorspace_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n4",utc_image_util_decode_set_colorspace_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n5",utc_image_util_decode_set_colorspace_n5,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n6",utc_image_util_decode_set_colorspace_n6,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_n7",utc_image_util_decode_set_colorspace_n7,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_p1",utc_image_util_decode_set_colorspace_p1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_p2",utc_image_util_decode_set_colorspace_p2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_p3",utc_image_util_decode_set_colorspace_p3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_colorspace_p4",utc_image_util_decode_set_colorspace_p4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_jpeg_downscale_n1",utc_image_util_decode_set_jpeg_downscale_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_jpeg_downscale_n2",utc_image_util_decode_set_jpeg_downscale_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_jpeg_downscale_n3",utc_image_util_decode_set_jpeg_downscale_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_jpeg_downscale_n4",utc_image_util_decode_set_jpeg_downscale_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_set_jpeg_downscale_p",utc_image_util_decode_set_jpeg_downscale_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_n1",utc_image_util_decode_run_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_n2",utc_image_util_decode_run_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_n3",utc_image_util_decode_run_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_n4",utc_image_util_decode_run_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_n5",utc_image_util_decode_run_n5,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_p1",utc_image_util_decode_run_p1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_p2",utc_image_util_decode_run_p2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run2_n",utc_image_util_decode_run2_n,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run2_p1",utc_image_util_decode_run2_p1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run2_p2",utc_image_util_decode_run2_p2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n1",utc_image_util_decode_run_async_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n2",utc_image_util_decode_run_async_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n3",utc_image_util_decode_run_async_n3,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n4",utc_image_util_decode_run_async_n4,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n5",utc_image_util_decode_run_async_n5,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_n6",utc_image_util_decode_run_async_n6,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_p1",utc_image_util_decode_run_async_p1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async_p2",utc_image_util_decode_run_async_p2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async2_n",utc_image_util_decode_run_async2_n,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async2_p1",utc_image_util_decode_run_async2_p1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_run_async2_p2",utc_image_util_decode_run_async2_p2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_destroy_n1",utc_image_util_decode_destroy_n1,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_destroy_n2",utc_image_util_decode_destroy_n2,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_decode_destroy_p",utc_image_util_decode_destroy_p,utc_image_util_decode_startup,utc_image_util_decode_cleanup},
	{"utc_image_util_encode_create_n1",utc_image_util_encode_create_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_create_n2",utc_image_util_encode_create_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_create_p",utc_image_util_encode_create_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_resolution_n1",utc_image_util_encode_set_resolution_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_resolution_n2",utc_image_util_encode_set_resolution_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_resolution_n3",utc_image_util_encode_set_resolution_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_resolution_n4",utc_image_util_encode_set_resolution_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_resolution_p",utc_image_util_encode_set_resolution_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_colorspace_n1",utc_image_util_encode_set_colorspace_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_colorspace_n2",utc_image_util_encode_set_colorspace_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_colorspace_n3",utc_image_util_encode_set_colorspace_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_colorspace_n4",utc_image_util_encode_set_colorspace_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_colorspace_p",utc_image_util_encode_set_colorspace_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_quality_n1",utc_image_util_encode_set_quality_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_quality_n2",utc_image_util_encode_set_quality_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_quality_n3",utc_image_util_encode_set_quality_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_quality_n4",utc_image_util_encode_set_quality_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_quality_p",utc_image_util_encode_set_quality_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_png_compression_n1",utc_image_util_encode_set_png_compression_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_png_compression_n2",utc_image_util_encode_set_png_compression_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_png_compression_n3",utc_image_util_encode_set_png_compression_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_png_compression_n4",utc_image_util_encode_set_png_compression_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_png_compression_p",utc_image_util_encode_set_png_compression_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_gif_frame_delay_time_n1",utc_image_util_encode_set_gif_frame_delay_time_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_gif_frame_delay_time_n2",utc_image_util_encode_set_gif_frame_delay_time_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_gif_frame_delay_time_n3",utc_image_util_encode_set_gif_frame_delay_time_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_gif_frame_delay_time_p",utc_image_util_encode_set_gif_frame_delay_time_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_webp_lossless_n1",utc_image_util_encode_set_webp_lossless_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_webp_lossless_n2",utc_image_util_encode_set_webp_lossless_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_webp_lossless_p",utc_image_util_encode_set_webp_lossless_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_lossless_n1",utc_image_util_encode_set_lossless_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_lossless_n2",utc_image_util_encode_set_lossless_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_lossless_p",utc_image_util_encode_set_lossless_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_input_buffer_n1",utc_image_util_encode_set_input_buffer_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_input_buffer_n2",utc_image_util_encode_set_input_buffer_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_input_buffer_n3",utc_image_util_encode_set_input_buffer_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_input_buffer_p",utc_image_util_encode_set_input_buffer_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_path_n1",utc_image_util_encode_set_output_path_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_path_n2",utc_image_util_encode_set_output_path_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_path_n3",utc_image_util_encode_set_output_path_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_path_n4",utc_image_util_encode_set_output_path_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_path_p",utc_image_util_encode_set_output_path_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_buffer_n1",utc_image_util_encode_set_output_buffer_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_buffer_n2",utc_image_util_encode_set_output_buffer_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_buffer_n3",utc_image_util_encode_set_output_buffer_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_set_output_buffer_p",utc_image_util_encode_set_output_buffer_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n1",utc_image_util_encode_run_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n2",utc_image_util_encode_run_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n3",utc_image_util_encode_run_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n4",utc_image_util_encode_run_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n5",utc_image_util_encode_run_n5,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n6",utc_image_util_encode_run_n6,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n7",utc_image_util_encode_run_n7,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_n8",utc_image_util_encode_run_n8,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_p1",utc_image_util_encode_run_p1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_p2",utc_image_util_encode_run_p2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_p3",utc_image_util_encode_run_p3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_p4",utc_image_util_encode_run_p4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n1",utc_image_util_encode_run_async_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n2",utc_image_util_encode_run_async_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n3",utc_image_util_encode_run_async_n3,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n4",utc_image_util_encode_run_async_n4,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n5",utc_image_util_encode_run_async_n5,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n6",utc_image_util_encode_run_async_n6,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n7",utc_image_util_encode_run_async_n7,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n8",utc_image_util_encode_run_async_n8,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_n9",utc_image_util_encode_run_async_n9,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_p1",utc_image_util_encode_run_async_p1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_p2",utc_image_util_encode_run_async_p2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_to_file_p",utc_image_util_encode_run_to_file_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_to_file_n",utc_image_util_encode_run_to_file_n,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_to_buffer_p",utc_image_util_encode_run_to_buffer_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_to_buffer_n",utc_image_util_encode_run_to_buffer_n,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_to_file_p",utc_image_util_encode_run_async_to_file_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_to_file_n",utc_image_util_encode_run_async_to_file_n,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_to_buffer_p",utc_image_util_encode_run_async_to_buffer_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_run_async_to_buffer_n",utc_image_util_encode_run_async_to_buffer_n,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_destroy_n1",utc_image_util_encode_destroy_n1,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_destroy_n2",utc_image_util_encode_destroy_n2,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	{"utc_image_util_encode_destroy_p",utc_image_util_encode_destroy_p,utc_image_util_encode_startup,utc_image_util_encode_cleanup},
	/* in utc-image-util-transform.c */
	{"utc_image_util_calculate_buffer_size_p1",utc_image_util_calculate_buffer_size_p1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_calculate_buffer_size_p2",utc_image_util_calculate_buffer_size_p2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_calculate_buffer_size_n1",utc_image_util_calculate_buffer_size_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_calculate_buffer_size_n2",utc_image_util_calculate_buffer_size_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_calculate_buffer_size_n3",utc_image_util_calculate_buffer_size_n3,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_create_n",utc_image_util_transform_create_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_create_p",utc_image_util_transform_create_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_hardware_acceleration_n",utc_image_util_transform_set_hardware_acceleration_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_hardware_acceleration_p",utc_image_util_transform_set_hardware_acceleration_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_colorspace_n",utc_image_util_transform_set_colorspace_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_colorspace_p",utc_image_util_transform_set_colorspace_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_colorspace_n1",utc_image_util_transform_get_colorspace_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_colorspace_n2",utc_image_util_transform_get_colorspace_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_colorspace_p",utc_image_util_transform_get_colorspace_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_resolution_n1",utc_image_util_transform_set_resolution_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_resolution_n2",utc_image_util_transform_set_resolution_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_resolution_n3",utc_image_util_transform_set_resolution_n3,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_resolution_p",utc_image_util_transform_set_resolution_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_resolution_n1",utc_image_util_transform_get_resolution_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_resolution_n2",utc_image_util_transform_get_resolution_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_resolution_p",utc_image_util_transform_get_resolution_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_rotation_n",utc_image_util_transform_set_rotation_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_rotation_p",utc_image_util_transform_set_rotation_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_rotation_n1",utc_image_util_transform_get_rotation_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_rotation_n2",utc_image_util_transform_get_rotation_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_rotation_p",utc_image_util_transform_get_rotation_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_n1",utc_image_util_transform_run_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_n2",utc_image_util_transform_run_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_n3",utc_image_util_transform_run_n3,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_n4",utc_image_util_transform_run_n4,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_p1",utc_image_util_transform_run_p1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_p2",utc_image_util_transform_run_p2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run_p3",utc_image_util_transform_run_p3,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_crop_area_n1",utc_image_util_transform_set_crop_area_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_crop_area_n2",utc_image_util_transform_set_crop_area_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_crop_area_n3",utc_image_util_transform_set_crop_area_n3,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_set_crop_area_p",utc_image_util_transform_set_crop_area_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_crop_area_n1",utc_image_util_transform_get_crop_area_n1,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_crop_area_n2",utc_image_util_transform_get_crop_area_n2,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_get_crop_area_p",utc_image_util_transform_get_crop_area_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_destory_n",utc_image_util_transform_destory_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_destory_p",utc_image_util_transform_destory_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_extract_color_from_memory_p",utc_image_util_extract_color_from_memory_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_extract_color_from_memory_n",utc_image_util_extract_color_from_memory_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_create_image_n",utc_image_util_create_image_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_create_image_p",utc_image_util_create_image_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_clone_image_n",utc_image_util_clone_image_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_clone_image_p",utc_image_util_clone_image_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_get_image_n",utc_image_util_get_image_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_get_image_p",utc_image_util_get_image_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_destroy_image_n",utc_image_util_destroy_image_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_destroy_image_p",utc_image_util_destroy_image_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run2_n",utc_image_util_transform_run2_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run2_p",utc_image_util_transform_run2_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run2_async_n",utc_image_util_transform_run2_async_n,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	{"utc_image_util_transform_run2_async_p",utc_image_util_transform_run2_async_p,utc_media_image_util_basic_startup,utc_media_image_util_basic_cleanup},
	/* in utc-image-util-agif-encode.c */
	{"utc_image_util_agif_encode_create_p",utc_image_util_agif_encode_create_p,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_create_n",utc_image_util_agif_encode_create_n,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_add_frame_p",utc_image_util_agif_encode_add_frame_p,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_add_frame_n",utc_image_util_agif_encode_add_frame_n,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_save_to_file_p",utc_image_util_agif_encode_save_to_file_p,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_save_to_file_n",utc_image_util_agif_encode_save_to_file_n,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_save_to_buffer_p",utc_image_util_agif_encode_save_to_buffer_p,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_save_to_buffer_n",utc_image_util_agif_encode_save_to_buffer_n,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_destroy_p",utc_image_util_agif_encode_destroy_p,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_agif_encode_destroy_n",utc_image_util_agif_encode_destroy_n,utc_image_util_agif_encode_startup,utc_image_util_agif_encode_cleanup},
	{"utc_image_util_anim_encode_create_p",utc_image_util_anim_encode_create_p,NULL,NULL},
	{"utc_image_util_anim_encode_create_n1",utc_image_util_anim_encode_create_n1,NULL,NULL},
	{"utc_image_util_anim_encode_create_n2",utc_image_util_anim_encode_create_n2,NULL,NULL},
	{"utc_image_util_anim_encode_set_loop_count_p",utc_image_util_anim_encode_set_loop_count_p,NULL,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_set_loop_count_n",utc_image_util_anim_encode_set_loop_count_n,NULL,NULL},
	{"utc_image_util_anim_encode_set_background_color_p",utc_image_util_anim_encode_set_background_color_p,NULL,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_set_background_color_n1",utc_image_util_anim_encode_set_background_color_n1,NULL,NULL},
	{"utc_image_util_anim_encode_set_background_color_n2",utc_image_util_anim_encode_set_background_color_n2,NULL,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_set_lossless_p",utc_image_util_anim_encode_set_lossless_p,NULL,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_set_lossless_n1",utc_image_util_anim_encode_set_lossless_n1,NULL,NULL},
	{"utc_image_util_anim_encode_set_lossless_n2",utc_image_util_anim_encode_set_lossless_n2,NULL,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_add_frame_p",utc_image_util_anim_encode_add_frame_p,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_add_frame_n",utc_image_util_anim_encode_add_frame_n,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_file_p1",utc_image_util_anim_encode_save_to_file_p1,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_file_p2",utc_image_util_anim_encode_save_to_file_p2,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_file_n1",utc_image_util_anim_encode_save_to_file_n1,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_file_n2",utc_image_util_anim_encode_save_to_file_n2,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_buffer_p1",utc_image_util_anim_encode_save_to_buffer_p1,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_buffer_p2",utc_image_util_anim_encode_save_to_buffer_p2,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_buffer_n1",utc_image_util_anim_encode_save_to_buffer_n1,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_save_to_buffer_n2",utc_image_util_anim_encode_save_to_buffer_n2,utc_image_util_anim_encode_startup,utc_image_util_anim_encode_cleanup},
	{"utc_image_util_anim_encode_destroy_p",utc_image_util_anim_encode_destroy_p,NULL,NULL},
	{"utc_image_util_anim_encode_destroy_n",utc_image_util_anim_encode_destroy_n,NULL,NULL},
	{NULL, NULL}
};

#endif // __TCT_IMAGE-UTIL-NATIVE_H__
