//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CALENDAR-SERVICE2-NATIVE_H__
#define __TCT_CALENDAR-SERVICE2-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_calendar_record_startup(void);
extern void utc_calendar_record_cleanup(void);
extern void utc_calendar_filter_startup(void);
extern void utc_calendar_filter_cleanup(void);
extern void utc_calendar_vcalendar_startup(void);
extern void utc_calendar_vcalendar_cleanup(void);
extern void utc_calendar_query_startup(void);
extern void utc_calendar_query_cleanup(void);
extern void utc_calendar_db_startup(void);
extern void utc_calendar_db_cleanup(void);
extern void utc_calendar_reminder_startup(void);
extern void utc_calendar_reminder_cleanup(void);
extern void utc_calendar_recurrence_startup(void);
extern void utc_calendar_recurrence_cleanup(void);
extern void utc_calendar_list_startup(void);
extern void utc_calendar_list_cleanup(void);

extern int utc_calendar_record_create_p(void);
extern int utc_calendar_record_create_n(void);
extern int utc_calendar_record_destroy_p(void);
extern int utc_calendar_record_destroy_n(void);
extern int utc_calendar_record_clone_p(void);
extern int utc_calendar_record_clone_n(void);
extern int utc_calendar_record_get_uri_p_p(void);
extern int utc_calendar_record_get_uri_p_n(void);
extern int utc_calendar_record_get_str_p(void);
extern int utc_calendar_record_get_str_n(void);
extern int utc_calendar_record_get_str_p_p(void);
extern int utc_calendar_record_get_str_p_n(void);
extern int utc_calendar_record_get_int_p(void);
extern int utc_calendar_record_get_int_n(void);
extern int utc_calendar_record_get_double_p(void);
extern int utc_calendar_record_get_double_n(void);
extern int utc_calendar_record_get_lli_p(void);
extern int utc_calendar_record_get_lli_n(void);
extern int utc_calendar_record_get_caltime_p(void);
extern int utc_calendar_record_get_caltime_n(void);
extern int utc_calendar_record_set_str_p(void);
extern int utc_calendar_record_set_str_n(void);
extern int utc_calendar_record_set_int_p(void);
extern int utc_calendar_record_set_int_n(void);
extern int utc_calendar_record_set_double_p(void);
extern int utc_calendar_record_set_double_n(void);
extern int utc_calendar_record_set_lli_p(void);
extern int utc_calendar_record_set_lli_n(void);
extern int utc_calendar_record_set_caltime_p(void);
extern int utc_calendar_record_set_caltime_n(void);
extern int utc_calendar_record_add_child_record_p(void);
extern int utc_calendar_record_add_child_record_n(void);
extern int utc_calendar_record_remove_child_record_p(void);
extern int utc_calendar_record_remove_child_record_n(void);
extern int utc_calendar_record_get_child_record_count_p(void);
extern int utc_calendar_record_get_child_record_count_n(void);
extern int utc_calendar_record_get_child_record_at_p_p(void);
extern int utc_calendar_record_get_child_record_at_p_n(void);
extern int utc_calendar_record_clone_child_record_list_p(void);
extern int utc_calendar_record_clone_child_record_list_n(void);
extern int utc_calendar_filter_create_p(void);
extern int utc_calendar_filter_create_n(void);
extern int utc_calendar_filter_destroy_p(void);
extern int utc_calendar_filter_destroy_n(void);
extern int utc_calendar_filter_add_str_p(void);
extern int utc_calendar_filter_add_str_n(void);
extern int utc_calendar_filter_add_int_p(void);
extern int utc_calendar_filter_add_int_n(void);
extern int utc_calendar_filter_add_double_p(void);
extern int utc_calendar_filter_add_double_n(void);
extern int utc_calendar_filter_add_lli_p(void);
extern int utc_calendar_filter_add_lli_n(void);
extern int utc_calendar_filter_add_caltime_p(void);
extern int utc_calendar_filter_add_caltime_n(void);
extern int utc_calendar_filter_add_filter_p(void);
extern int utc_calendar_filter_add_filter_n(void);
extern int utc_calendar_filter_add_operator_p(void);
extern int utc_calendar_filter_add_operator_n(void);
extern int utc_calendar_vcalendar_make_from_records_p(void);
extern int utc_calendar_vcalendar_make_from_records_n(void);
extern int utc_calendar_vcalendar_parse_to_calendar_p(void);
extern int utc_calendar_vcalendar_parse_to_calendar_n(void);
extern int utc_calendar_vcalendar_parse_to_calendar_foreach_p(void);
extern int utc_calendar_vcalendar_parse_to_calendar_foreach_n(void);
extern int utc_calendar_query_create_p(void);
extern int utc_calendar_query_create_n(void);
extern int utc_calendar_query_destroy_p(void);
extern int utc_calendar_query_destroy_n(void);
extern int utc_calendar_query_set_projection_p(void);
extern int utc_calendar_query_set_projection_n(void);
extern int utc_calendar_query_set_distinct_p(void);
extern int utc_calendar_query_set_distinct_n(void);
extern int utc_calendar_query_set_filter_p(void);
extern int utc_calendar_query_set_filter_n(void);
extern int utc_calendar_query_set_sort_p(void);
extern int utc_calendar_query_set_sort_n(void);
extern int utc_calendar_connect_p(void);
extern int utc_calendar_disconnect_p(void);
extern int utc_calendar_connect_on_thread_p(void);
extern int utc_calendar_disconnect_on_thread_p(void);
extern int utc_calendar_connect_with_flags_p(void);
extern int utc_calendar_db_insert_record_p(void);
extern int utc_calendar_db_insert_record_n(void);
extern int utc_calendar_db_get_record_p(void);
extern int utc_calendar_db_get_record_n(void);
extern int utc_calendar_db_update_record_p(void);
extern int utc_calendar_db_update_record_n(void);
extern int utc_calendar_db_delete_record_p(void);
extern int utc_calendar_db_delete_record_n(void);
extern int utc_calendar_db_get_all_records_p(void);
extern int utc_calendar_db_get_all_records_n(void);
extern int utc_calendar_db_get_records_with_query_p(void);
extern int utc_calendar_db_get_records_with_query_n(void);
extern int utc_calendar_db_get_count_p(void);
extern int utc_calendar_db_get_count_n(void);
extern int utc_calendar_db_get_count_with_query_p(void);
extern int utc_calendar_db_get_count_with_query_n(void);
extern int utc_calendar_db_insert_records_p(void);
extern int utc_calendar_db_insert_records_n(void);
extern int utc_calendar_db_update_records_p(void);
extern int utc_calendar_db_update_records_n(void);
extern int utc_calendar_db_delete_records_p(void);
extern int utc_calendar_db_delete_records_n(void);
extern int utc_calendar_db_get_current_version_p(void);
extern int utc_calendar_db_get_current_version_n(void);
extern int utc_calendar_db_add_changed_cb_p(void);
extern int utc_calendar_db_add_changed_cb_n(void);
extern int utc_calendar_db_remove_changed_cb_p(void);
extern int utc_calendar_db_remove_changed_cb_n(void);
extern int utc_calendar_db_get_changes_by_version_p(void);
extern int utc_calendar_db_get_changes_by_version_n(void);
extern int utc_calendar_db_insert_vcalendars_p(void);
extern int utc_calendar_db_insert_vcalendars_n(void);
extern int utc_calendar_db_replace_vcalendars_p(void);
extern int utc_calendar_db_replace_vcalendars_n(void);
extern int utc_calendar_db_replace_record_p(void);
extern int utc_calendar_db_replace_record_n(void);
extern int utc_calendar_db_replace_records_p(void);
extern int utc_calendar_db_replace_records_n(void);
extern int utc_calendar_db_get_last_change_version_p(void);
extern int utc_calendar_db_get_last_change_version_n(void);
extern int utc_calendar_db_get_changes_exception_by_version_p(void);
extern int utc_calendar_db_get_changes_exception_by_version_n(void);
extern int utc_calendar_db_clean_after_sync_p(void);
extern int utc_calendar_db_clean_after_sync_n(void);
extern int utc_calendar_db_link_record_p(void);
extern int utc_calendar_db_link_record_n(void);
extern int utc_calendar_db_unlink_record_p(void);
extern int utc_calendar_db_unlink_record_n(void);
extern int utc_calendar_reminder_add_cb_utime_once_p(void);
extern int utc_calendar_reminder_add_cb_utime_daily_p(void);
extern int utc_calendar_reminder_add_cb_utime_weekly_p(void);
extern int utc_calendar_reminder_add_cb_utime_monthly_p(void);
extern int utc_calendar_reminder_add_cb_utime_yearly_p(void);
extern int utc_calendar_reminder_add_cb_utime_specific_p(void);
extern int utc_calendar_reminder_add_cb_localtime_once_p(void);
extern int utc_calendar_reminder_add_cb_localtime_daily_p(void);
extern int utc_calendar_reminder_add_cb_localtime_weekly_p(void);
extern int utc_calendar_reminder_add_cb_localtime_monthly_p(void);
extern int utc_calendar_reminder_add_cb_localtime_yearly_p(void);
extern int utc_calendar_reminder_add_cb_localtime_specific_p(void);
extern int utc_calendar_reminder_add_cb_todo_utime_once_p(void);
extern int utc_calendar_reminder_add_cb_todo_localtime_once_p(void);
extern int utc_calendar_reminder_add_cb_n(void);
extern int utc_calendar_reminder_remove_cb_p(void);
extern int utc_calendar_reminder_remove_cb_n(void);
extern int utc_calendar_recurrence_p(void);
extern int utc_calendar_list_create_p(void);
extern int utc_calendar_list_create_n(void);
extern int utc_calendar_list_destroy_p(void);
extern int utc_calendar_list_destroy_n(void);
extern int utc_calendar_list_get_count_p(void);
extern int utc_calendar_list_get_count_n(void);
extern int utc_calendar_list_add_p(void);
extern int utc_calendar_list_add_n(void);
extern int utc_calendar_list_remove_p(void);
extern int utc_calendar_list_remove_n(void);
extern int utc_calendar_list_get_current_record_p_p(void);
extern int utc_calendar_list_get_current_record_p_n(void);
extern int utc_calendar_list_prev_p(void);
extern int utc_calendar_list_prev_n(void);
extern int utc_calendar_list_next_p(void);
extern int utc_calendar_list_next_n(void);
extern int utc_calendar_list_first_p(void);
extern int utc_calendar_list_first_n(void);
extern int utc_calendar_list_last_p(void);
extern int utc_calendar_list_last_n(void);

testcase tc_array[] = {
	{"utc_calendar_record_create_p",utc_calendar_record_create_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_create_n",utc_calendar_record_create_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_destroy_p",utc_calendar_record_destroy_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_destroy_n",utc_calendar_record_destroy_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_clone_p",utc_calendar_record_clone_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_clone_n",utc_calendar_record_clone_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_uri_p_p",utc_calendar_record_get_uri_p_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_uri_p_n",utc_calendar_record_get_uri_p_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_str_p",utc_calendar_record_get_str_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_str_n",utc_calendar_record_get_str_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_str_p_p",utc_calendar_record_get_str_p_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_str_p_n",utc_calendar_record_get_str_p_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_int_p",utc_calendar_record_get_int_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_int_n",utc_calendar_record_get_int_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_double_p",utc_calendar_record_get_double_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_double_n",utc_calendar_record_get_double_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_lli_p",utc_calendar_record_get_lli_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_lli_n",utc_calendar_record_get_lli_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_caltime_p",utc_calendar_record_get_caltime_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_caltime_n",utc_calendar_record_get_caltime_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_str_p",utc_calendar_record_set_str_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_str_n",utc_calendar_record_set_str_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_int_p",utc_calendar_record_set_int_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_int_n",utc_calendar_record_set_int_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_double_p",utc_calendar_record_set_double_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_double_n",utc_calendar_record_set_double_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_lli_p",utc_calendar_record_set_lli_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_lli_n",utc_calendar_record_set_lli_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_caltime_p",utc_calendar_record_set_caltime_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_set_caltime_n",utc_calendar_record_set_caltime_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_add_child_record_p",utc_calendar_record_add_child_record_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_add_child_record_n",utc_calendar_record_add_child_record_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_remove_child_record_p",utc_calendar_record_remove_child_record_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_remove_child_record_n",utc_calendar_record_remove_child_record_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_child_record_count_p",utc_calendar_record_get_child_record_count_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_child_record_count_n",utc_calendar_record_get_child_record_count_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_child_record_at_p_p",utc_calendar_record_get_child_record_at_p_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_get_child_record_at_p_n",utc_calendar_record_get_child_record_at_p_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_clone_child_record_list_p",utc_calendar_record_clone_child_record_list_p,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_record_clone_child_record_list_n",utc_calendar_record_clone_child_record_list_n,utc_calendar_record_startup,utc_calendar_record_cleanup},
	{"utc_calendar_filter_create_p",utc_calendar_filter_create_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_create_n",utc_calendar_filter_create_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_destroy_p",utc_calendar_filter_destroy_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_destroy_n",utc_calendar_filter_destroy_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_str_p",utc_calendar_filter_add_str_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_str_n",utc_calendar_filter_add_str_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_int_p",utc_calendar_filter_add_int_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_int_n",utc_calendar_filter_add_int_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_double_p",utc_calendar_filter_add_double_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_double_n",utc_calendar_filter_add_double_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_lli_p",utc_calendar_filter_add_lli_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_lli_n",utc_calendar_filter_add_lli_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_caltime_p",utc_calendar_filter_add_caltime_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_caltime_n",utc_calendar_filter_add_caltime_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_filter_p",utc_calendar_filter_add_filter_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_filter_n",utc_calendar_filter_add_filter_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_operator_p",utc_calendar_filter_add_operator_p,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_filter_add_operator_n",utc_calendar_filter_add_operator_n,utc_calendar_filter_startup,utc_calendar_filter_cleanup},
	{"utc_calendar_vcalendar_make_from_records_p",utc_calendar_vcalendar_make_from_records_p,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_vcalendar_make_from_records_n",utc_calendar_vcalendar_make_from_records_n,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_vcalendar_parse_to_calendar_p",utc_calendar_vcalendar_parse_to_calendar_p,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_vcalendar_parse_to_calendar_n",utc_calendar_vcalendar_parse_to_calendar_n,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_vcalendar_parse_to_calendar_foreach_p",utc_calendar_vcalendar_parse_to_calendar_foreach_p,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_vcalendar_parse_to_calendar_foreach_n",utc_calendar_vcalendar_parse_to_calendar_foreach_n,utc_calendar_vcalendar_startup,utc_calendar_vcalendar_cleanup},
	{"utc_calendar_query_create_p",utc_calendar_query_create_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_create_n",utc_calendar_query_create_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_destroy_p",utc_calendar_query_destroy_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_destroy_n",utc_calendar_query_destroy_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_projection_p",utc_calendar_query_set_projection_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_projection_n",utc_calendar_query_set_projection_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_distinct_p",utc_calendar_query_set_distinct_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_distinct_n",utc_calendar_query_set_distinct_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_filter_p",utc_calendar_query_set_filter_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_filter_n",utc_calendar_query_set_filter_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_sort_p",utc_calendar_query_set_sort_p,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_query_set_sort_n",utc_calendar_query_set_sort_n,utc_calendar_query_startup,utc_calendar_query_cleanup},
	{"utc_calendar_connect_p",utc_calendar_connect_p,NULL,NULL},
	{"utc_calendar_disconnect_p",utc_calendar_disconnect_p,NULL,NULL},
	{"utc_calendar_connect_on_thread_p",utc_calendar_connect_on_thread_p,NULL,NULL},
	{"utc_calendar_disconnect_on_thread_p",utc_calendar_disconnect_on_thread_p,NULL,NULL},
	{"utc_calendar_connect_with_flags_p",utc_calendar_connect_with_flags_p,NULL,NULL},
	{"utc_calendar_db_insert_record_p",utc_calendar_db_insert_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_insert_record_n",utc_calendar_db_insert_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_record_p",utc_calendar_db_get_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_record_n",utc_calendar_db_get_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_update_record_p",utc_calendar_db_update_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_update_record_n",utc_calendar_db_update_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_delete_record_p",utc_calendar_db_delete_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_delete_record_n",utc_calendar_db_delete_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_all_records_p",utc_calendar_db_get_all_records_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_all_records_n",utc_calendar_db_get_all_records_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_records_with_query_p",utc_calendar_db_get_records_with_query_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_records_with_query_n",utc_calendar_db_get_records_with_query_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_count_p",utc_calendar_db_get_count_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_count_n",utc_calendar_db_get_count_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_count_with_query_p",utc_calendar_db_get_count_with_query_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_count_with_query_n",utc_calendar_db_get_count_with_query_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_insert_records_p",utc_calendar_db_insert_records_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_insert_records_n",utc_calendar_db_insert_records_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_update_records_p",utc_calendar_db_update_records_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_update_records_n",utc_calendar_db_update_records_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_delete_records_p",utc_calendar_db_delete_records_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_delete_records_n",utc_calendar_db_delete_records_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_current_version_p",utc_calendar_db_get_current_version_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_current_version_n",utc_calendar_db_get_current_version_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_add_changed_cb_p",utc_calendar_db_add_changed_cb_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_add_changed_cb_n",utc_calendar_db_add_changed_cb_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_remove_changed_cb_p",utc_calendar_db_remove_changed_cb_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_remove_changed_cb_n",utc_calendar_db_remove_changed_cb_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_changes_by_version_p",utc_calendar_db_get_changes_by_version_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_changes_by_version_n",utc_calendar_db_get_changes_by_version_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_insert_vcalendars_p",utc_calendar_db_insert_vcalendars_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_insert_vcalendars_n",utc_calendar_db_insert_vcalendars_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_vcalendars_p",utc_calendar_db_replace_vcalendars_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_vcalendars_n",utc_calendar_db_replace_vcalendars_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_record_p",utc_calendar_db_replace_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_record_n",utc_calendar_db_replace_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_records_p",utc_calendar_db_replace_records_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_replace_records_n",utc_calendar_db_replace_records_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_last_change_version_p",utc_calendar_db_get_last_change_version_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_last_change_version_n",utc_calendar_db_get_last_change_version_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_changes_exception_by_version_p",utc_calendar_db_get_changes_exception_by_version_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_get_changes_exception_by_version_n",utc_calendar_db_get_changes_exception_by_version_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_clean_after_sync_p",utc_calendar_db_clean_after_sync_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_clean_after_sync_n",utc_calendar_db_clean_after_sync_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_link_record_p",utc_calendar_db_link_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_link_record_n",utc_calendar_db_link_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_unlink_record_p",utc_calendar_db_unlink_record_p,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_db_unlink_record_n",utc_calendar_db_unlink_record_n,utc_calendar_db_startup,utc_calendar_db_cleanup},
	{"utc_calendar_reminder_add_cb_utime_once_p",utc_calendar_reminder_add_cb_utime_once_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_utime_daily_p",utc_calendar_reminder_add_cb_utime_daily_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_utime_weekly_p",utc_calendar_reminder_add_cb_utime_weekly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_utime_monthly_p",utc_calendar_reminder_add_cb_utime_monthly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_utime_yearly_p",utc_calendar_reminder_add_cb_utime_yearly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_utime_specific_p",utc_calendar_reminder_add_cb_utime_specific_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_once_p",utc_calendar_reminder_add_cb_localtime_once_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_daily_p",utc_calendar_reminder_add_cb_localtime_daily_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_weekly_p",utc_calendar_reminder_add_cb_localtime_weekly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_monthly_p",utc_calendar_reminder_add_cb_localtime_monthly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_yearly_p",utc_calendar_reminder_add_cb_localtime_yearly_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_localtime_specific_p",utc_calendar_reminder_add_cb_localtime_specific_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_todo_utime_once_p",utc_calendar_reminder_add_cb_todo_utime_once_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_todo_localtime_once_p",utc_calendar_reminder_add_cb_todo_localtime_once_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_add_cb_n",utc_calendar_reminder_add_cb_n,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_remove_cb_p",utc_calendar_reminder_remove_cb_p,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_reminder_remove_cb_n",utc_calendar_reminder_remove_cb_n,utc_calendar_reminder_startup,utc_calendar_reminder_cleanup},
	{"utc_calendar_recurrence_p",utc_calendar_recurrence_p,utc_calendar_recurrence_startup,utc_calendar_recurrence_cleanup},
	{"utc_calendar_list_create_p",utc_calendar_list_create_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_create_n",utc_calendar_list_create_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_destroy_p",utc_calendar_list_destroy_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_destroy_n",utc_calendar_list_destroy_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_get_count_p",utc_calendar_list_get_count_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_get_count_n",utc_calendar_list_get_count_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_add_p",utc_calendar_list_add_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_add_n",utc_calendar_list_add_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_remove_p",utc_calendar_list_remove_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_remove_n",utc_calendar_list_remove_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_get_current_record_p_p",utc_calendar_list_get_current_record_p_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_get_current_record_p_n",utc_calendar_list_get_current_record_p_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_prev_p",utc_calendar_list_prev_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_prev_n",utc_calendar_list_prev_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_next_p",utc_calendar_list_next_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_next_n",utc_calendar_list_next_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_first_p",utc_calendar_list_first_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_first_n",utc_calendar_list_first_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_last_p",utc_calendar_list_last_p,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{"utc_calendar_list_last_n",utc_calendar_list_last_n,utc_calendar_list_startup,utc_calendar_list_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CALENDAR-SERVICE2-NATIVE_H__
