/*
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __UTC_CALENDAR_UTIL_H__
#define __UTC_CALENDAR_UTIL_H__

#include <dlog.h>

#define UTC_HIDDEN __attribute__ ((visibility("hidden")))
#define UTC_CALENDAR_FEATURE "http://tizen.org/feature/calendar"

#define UTC_CALENDAR_INSERT_COUNT  1

// new
#define UTC_STR_NEW_UID "new@tizen.org"
#define UTC_STR_NEW_NAME "new_name"
#define UTC_STR_NEW_SUMMARY "new_summary"
#define UTC_STR_NEW_DESCRIPTION "new_description 1234567890; 1234567890/ 1234567890: 1234567890, 1234567890! 1234567890"
#define UTC_STR_NEW_COLOR "new_color"
#define UTC_STR_NEW_LOCATION "new_location"
#define UTC_STR_NEW_CATEGORIES "new_categories"
#define UTC_STR_NEW_EXDATE "20150115T090000Z"
#define UTC_STR_NEW_ORGANIZER_NAME "new_organizer_name"
#define UTC_STR_NEW_ORGANIZER_EMAIL "new_organizer_email"
#define UTC_STR_NEW_BYSECOND "1"
#define UTC_STR_NEW_BYMINUTE "2"
#define UTC_STR_NEW_BYHOUR "3"
#define UTC_STR_NEW_BYDAY "MO,TU"
#define UTC_STR_NEW_BYMONTHDAY "5,6"
#define UTC_STR_NEW_BYYEARDAY "45,46"
#define UTC_STR_NEW_BYWEEKNO "2,3"
#define UTC_STR_NEW_BYMONTH "1,2"
#define UTC_STR_NEW_BYSETPOS "3,4"
#define UTC_STR_NEW_RECURRENCE_ID "20150115T090000Z"
#define UTC_STR_NEW_RDATE "1"
#define UTC_STR_NEW_START_TZID "Asia/Seoul"
#define UTC_STR_NEW_END_TZID "Asia/Seoul"
#define UTC_STR_NEW_SYNC_DATA1 "new_sync_data1"
#define UTC_STR_NEW_SYNC_DATA2 "new_sync_data2"
#define UTC_STR_NEW_SYNC_DATA3 "new_sync_data3"
#define UTC_STR_NEW_SYNC_DATA4 "new_sync_data4"
#define UTC_STR_NEW_ALARM_SUMMARY "new_alarm_summary"
#define UTC_STR_NEW_ALARM_DESCRIPTION "new_alarm_description"
#define UTC_STR_NEW_ALARM_ATTACH "new_alarm_attach"
#define UTC_STR_NEW_TIMEZONE_STANDARD_NAME "new_timezone_standard_name"
#define UTC_STR_NEW_TIMEZONE_DAY_LIGHT_NAME "new_timezone_day_light_name"
#define UTC_STR_NEW_ATTENDEE_NUMBER			 "new_attendee_number"
#define UTC_STR_NEW_ATTENDEE_UID             "new_attendee_uid"
#define UTC_STR_NEW_ATTENDEE_GROUP           "new_attendee_group"
#define UTC_STR_NEW_ATTENDEE_EMAIL           "new_attendee_email"
#define UTC_STR_NEW_ATTENDEE_DELEGATEE_URI   "new_attendee_delegatee_uri"
#define UTC_STR_NEW_ATTENDEE_DELEGATOR_URI   "new_attendee_delegator_uri"
#define UTC_STR_NEW_ATTENDEE_NAME            "new_attendee_name"
#define UTC_STR_NEW_ATTENDEE_MEMBER          "new_attendee_member"
#define UTC_STR_NEW_EXTENDED_KEY "new_key"
#define UTC_STR_NEW_EXTENDED_VALUE "new_value"

#define UTC_INT_NEW_VISIBILITY 1
#define UTC_INT_NEW_SYNC_EVENT CALENDAR_BOOK_SYNC_EVENT_FOR_EVERY_AND_DELETE
#define UTC_INT_NEW_ACCOUNT_ID 1
#define UTC_INT_NEW_EVENT_STORE_TYPE CALENDAR_BOOK_TYPE_EVENT
#define UTC_INT_NEW_TODO_STORE_TYPE CALENDAR_BOOK_TYPE_TODO
#define UTC_INT_NEW_MODE CALENDAR_BOOK_MODE_NONE
#define UTC_INT_NEW_EVENT_CALENDAR_BOOK_ID DEFAULT_EVENT_CALENDAR_BOOK_ID
#define UTC_INT_NEW_TODO_CALENDAR_BOOK_ID DEFAULT_TODO_CALENDAR_BOOK_ID
#define UTC_INT_NEW_EVENT_STATUS CALENDAR_EVENT_STATUS_TENTATIVE
#define UTC_INT_NEW_TODO_STATUS CALENDAR_TODO_STATUS_NEEDS_ACTION
#define UTC_INT_NEW_PRIORITY CALENDAR_EVENT_PRIORITY_LOW
#define UTC_INT_NEW_TIMEZONE 9
#define UTC_INT_NEW_PERSON_ID 1
#define UTC_INT_NEW_BUSY_STATUS CALENDAR_EVENT_BUSY_STATUS_FREE
#define UTC_INT_NEW_SENSITIVITY CALENDAR_SENSITIVITY_PUBLIC
#define UTC_INT_NEW_MEETING_STATUS CALENDAR_MEETING_STATUS_MEETING
#define UTC_INT_NEW_ORIGINAL_EVENT_ID -1
#define UTC_INT_NEW_EMAIL_ID 1
#define UTC_INT_NEW_FREQ CALENDAR_RECURRENCE_DAILY
#define UTC_INT_NEW_RANGE_TYPE CALENDAR_RANGE_COUNT
#define UTC_INT_NEW_COUNT 5
#define UTC_INT_NEW_INTERVAL 1
#define UTC_INT_NEW_WKST CALENDAR_SUNDAY
#define UTC_INT_NEW_CALENDAR_SYSTEM_TYPE CALENDAR_SYSTEM_GREGORIAN
#define UTC_INT_NEW_PROPGRESS 50
#define UTC_INT_NEW_ALARM_TICK 5
#define UTC_INT_NEW_ALARM_TICK_UNIT CALENDAR_ALARM_TIME_UNIT_MINUTE
#define UTC_INT_NEW_ALARM_ACTION CALENDAR_ALARM_ACTION_AUDIO
#define UTC_INT_NEW_TIMEZONE_CALENDAR_BOOK_ID 1
#define UTC_INT_NEW_TIMEZONE_TZ_OFFSET_FROM_GMT 9
#define UTC_INT_NEW_TIMEZONE_STANDARD_START_MONTH 1
#define UTC_INT_NEW_TIMEZONE_STANDARD_START_POSITION_OF_WEEK 1
#define UTC_INT_NEW_TIMEZONE_STANDARD_START_DAY 1
#define UTC_INT_NEW_TIMEZONE_STANDARD_START_HOUR 1
#define UTC_INT_NEW_TIMEZONE_STANDARD_BIAS 1
#define UTC_INT_NEW_TIMEZONE_DAY_LIGHT_START_MONTH 1
#define UTC_INT_NEW_TIMEZONE_DAY_LIGHT_START_POSITION_OF_WEEK 1
#define UTC_INT_NEW_TIMEZONE_DAY_LIGHT_START_DAY 1
#define UTC_INT_NEW_TIMEZONE_DAY_LIGHT_START_HOUR 1
#define UTC_INT_NEW_TIMEZONE_DAY_LIGHT_BIAS 1
#define UTC_INT_NEW_ATTENDEE_CUTYPE	CALENDAR_ATTENDEE_CUTYPE_INDIVIDUAL
#define UTC_INT_NEW_ATTENDEE_PERSON_ID 1
#define UTC_INT_NEW_ATTENDEE_ROLE CALENDAR_ATTENDEE_ROLE_REQ_PARTICIPANT
#define UTC_INT_NEW_ATTENDEE_STATUS CALENDAR_ATTENDEE_STATUS_ACCEPTED
#define UTC_INT_NEW_ATTENDEE_RSVP 1

#define UTC_LLI_NEW_COMPLETED_TIME 1

#define UTC_DOUBLE_NEW_LATITUDE 1.1
#define UTC_DOUBLE_NEW_LONGITUDE 1.1

#define UTC_CALTIME_NEW_START_STRING "20150105T000000"
#define UTC_CALTIME_NEW_START_UTIME 1420416000 /* 2015/01/05 00:00:00 UTC */
#define UTC_CALTIME_NEW_START_YEAR 2015
#define UTC_CALTIME_NEW_START_MONTH 1
#define UTC_CALTIME_NEW_START_MDAY 5
#define UTC_CALTIME_NEW_START_HOUR 9
#define UTC_CALTIME_NEW_START_MINUTE 0
#define UTC_CALTIME_NEW_START_SECOND 0
#define UTC_CALTIME_NEW_END_STRING "20150105T010000"
#define UTC_CALTIME_NEW_END_UTIME 1420419600 /* 2015/01/05 01:00:00 UTC */
#define UTC_CALTIME_NEW_END_YEAR 2015
#define UTC_CALTIME_NEW_END_MONTH 1
#define UTC_CALTIME_NEW_END_MDAY 5
#define UTC_CALTIME_NEW_END_HOUR 10
#define UTC_CALTIME_NEW_END_MINUTE 0
#define UTC_CALTIME_NEW_END_SECOND 0


// mod
#define UTC_STR_MOD_UID "mod@tizen.org"
#define UTC_STR_MOD_NAME "mod_name"
#define UTC_STR_MOD_SUMMARY "mod_summary"
#define UTC_STR_MOD_DESCRIPTION "mod_description"
#define UTC_STR_MOD_COLOR "mod_color"
#define UTC_STR_MOD_LOCATION "mod_location"
#define UTC_STR_MOD_CATEGORIES "mod_categories"
#define UTC_STR_MOD_EXDATE "20150114T090000Z"
#define UTC_STR_MOD_ORGANIZER_NAME "mod_organizer_name"
#define UTC_STR_MOD_ORGANIZER_EMAIL "mod_organizer_email"
#define UTC_STR_MOD_BYSECOND "2"
#define UTC_STR_MOD_BYMINUTE "3"
#define UTC_STR_MOD_BYHOUR "4"
#define UTC_STR_MOD_BYDAY "WE,SA"
#define UTC_STR_MOD_BYMONTHDAY "7,8"
#define UTC_STR_MOD_BYYEARDAY "20,23"
#define UTC_STR_MOD_BYWEEKNO "3,4"
#define UTC_STR_MOD_BYMONTH "1,3"
#define UTC_STR_MOD_BYSETPOS "1,3"
#define UTC_STR_MOD_RECURRENCE_ID "20150115T090000Z"
#define UTC_STR_MOD_RDATE "2"
#define UTC_STR_MOD_START_TZID "Asia/Seoul"
#define UTC_STR_MOD_END_TZID "Asia/Seoul"
#define UTC_STR_MOD_SYNC_DATA1 "mod_sync_data1"
#define UTC_STR_MOD_SYNC_DATA2 "mod_sync_data2"
#define UTC_STR_MOD_SYNC_DATA3 "mod_sync_data3"
#define UTC_STR_MOD_SYNC_DATA4 "mod_sync_data4"
#define UTC_STR_MOD_ALARM_SUMMARY "mod_alarm_summary"
#define UTC_STR_MOD_ALARM_DESCRIPTION "mod_alarm_description"
#define UTC_STR_MOD_ALARM_ATTACH "mod_alarm_attach"
#define UTC_STR_MOD_TIMEZONE_STANDARD_NAME "mod_timezone_standard_name"
#define UTC_STR_MOD_TIMEZONE_DAY_LIGHT_NAME "mod_timezone_day_light_name"
#define UTC_STR_MOD_ATTENDEE_NUMBER			 "mod_attendee_number"
#define UTC_STR_MOD_ATTENDEE_UID             "mod_attendee_uid"
#define UTC_STR_MOD_ATTENDEE_GROUP           "mod_attendee_group"
#define UTC_STR_MOD_ATTENDEE_EMAIL           "mod_attendee_email"
#define UTC_STR_MOD_ATTENDEE_DELEGATEE_URI   "mod_attendee_delegatee_uri"
#define UTC_STR_MOD_ATTENDEE_DELEGATOR_URI   "mod_attendee_delegator_uri"
#define UTC_STR_MOD_ATTENDEE_NAME            "mod_attendee_name"
#define UTC_STR_MOD_ATTENDEE_MEMBER          "mod_attendee_member"
#define UTC_STR_MOD_EXTENDED_KEY "mod_key"
#define UTC_STR_MOD_EXTENDED_VALUE "mod_value"

#define UTC_INT_MOD_VISIBILITY 2
#define UTC_INT_MOD_SYNC_EVENT CALENDAR_BOOK_SYNC_EVENT_FOR_EVERY_AND_DELETE
#define UTC_INT_MOD_ACCOUNT_ID 2
#define UTC_INT_MOD_EVENT_STORE_TYPE CALENDAR_BOOK_TYPE_EVENT
#define UTC_INT_MOD_TODO_STORE_TYPE CALENDAR_BOOK_TYPE_TODO
#define UTC_INT_MOD_MODE CALENDAR_BOOK_MODE_NONE
#define UTC_INT_MOD_EVENT_CALENDAR_BOOK_ID DEFAULT_EVENT_CALENDAR_BOOK_ID
#define UTC_INT_MOD_TODO_CALENDAR_BOOK_ID DEFAULT_TODO_CALENDAR_BOOK_ID
#define UTC_INT_MOD_TODO_CALENDAR_BOOK_ID DEFAULT_TODO_CALENDAR_BOOK_ID
#define UTC_INT_MOD_EVENT_STATUS CALENDAR_EVENT_STATUS_CONFIRMED
#define UTC_INT_MOD_TODO_STATUS CALENDAR_TODO_STATUS_COMPLETED
#define UTC_INT_MOD_PRIORITY CALENDAR_EVENT_PRIORITY_HIGH
#define UTC_INT_MOD_TIMEZONE 9
#define UTC_INT_MOD_PERSON_ID 2
#define UTC_INT_MOD_BUSY_STATUS CALENDAR_EVENT_BUSY_STATUS_UNAVAILABLE
#define UTC_INT_MOD_SENSITIVITY CALENDAR_SENSITIVITY_CONFIDENTIAL
#define UTC_INT_MOD_MEETING_STATUS CALENDAR_MEETING_STATUS_RECEIVED
#define UTC_INT_MOD_ORIGINAL_EVENT_ID -1
#define UTC_INT_MOD_EMAIL_ID 2
#define UTC_INT_MOD_FREQ CALENDAR_RECURRENCE_DAILY
#define UTC_INT_MOD_RANGE_TYPE CALENDAR_RANGE_COUNT
#define UTC_INT_MOD_COUNT 7
#define UTC_INT_MOD_INTERVAL 1
#define UTC_INT_MOD_WKST CALENDAR_SUNDAY
#define UTC_INT_MOD_CALENDAR_SYSTEM_TYPE CALENDAR_SYSTEM_GREGORIAN
#define UTC_INT_MOD_PROPGRESS 70
#define UTC_INT_MOD_ALARM_TICK 3
#define UTC_INT_MOD_ALARM_TICK_UNIT CALENDAR_ALARM_TIME_UNIT_HOUR
#define UTC_INT_MOD_ALARM_ACTION CALENDAR_ALARM_ACTION_EMAIL
#define UTC_INT_MOD_TIMEZONE_CALENDAR_BOOK_ID 1
#define UTC_INT_MOD_TIMEZONE_TZ_OFFSET_FROM_GMT 10
#define UTC_INT_MOD_TIMEZONE_STANDARD_START_MONTH 2
#define UTC_INT_MOD_TIMEZONE_STANDARD_START_POSITION_OF_WEEK 2
#define UTC_INT_MOD_TIMEZONE_STANDARD_START_DAY 2
#define UTC_INT_MOD_TIMEZONE_STANDARD_START_HOUR 2
#define UTC_INT_MOD_TIMEZONE_STANDARD_BIAS 2
#define UTC_INT_MOD_TIMEZONE_DAY_LIGHT_START_MONTH 2
#define UTC_INT_MOD_TIMEZONE_DAY_LIGHT_START_POSITION_OF_WEEK 2
#define UTC_INT_MOD_TIMEZONE_DAY_LIGHT_START_DAY 2
#define UTC_INT_MOD_TIMEZONE_DAY_LIGHT_START_HOUR 2
#define UTC_INT_MOD_TIMEZONE_DAY_LIGHT_BIAS 2
#define UTC_INT_MOD_ATTENDEE_CUTYPE	CALENDAR_ATTENDEE_CUTYPE_GROUP
#define UTC_INT_MOD_ATTENDEE_PERSON_ID 2
#define UTC_INT_MOD_ATTENDEE_ROLE CALENDAR_ATTENDEE_ROLE_OPT_PARTICIPANT
#define UTC_INT_MOD_ATTENDEE_STATUS CALENDAR_ATTENDEE_STATUS_DECLINED
#define UTC_INT_MOD_ATTENDEE_RSVP 2

#define UTC_LLI_MOD_COMPLETED_TIME 2

#define UTC_DOUBLE_MOD_LATITUDE 2.2
#define UTC_DOUBLE_MOD_LONGITUDE 2.2

#define UTC_CALTIME_MOD_START_STRING "20150104T000000"
#define UTC_CALTIME_MOD_START_UTIME 1420329600 /* 2015/01/04 00:00:00 UTC */
#define UTC_CALTIME_MOD_START_YEAR 2015
#define UTC_CALTIME_MOD_START_MONTH 1
#define UTC_CALTIME_MOD_START_MDAY 4
#define UTC_CALTIME_MOD_START_HOUR 9
#define UTC_CALTIME_MOD_START_MINUTE 0
#define UTC_CALTIME_MOD_START_SECOND 0
#define UTC_CALTIME_MOD_END_STRING "20150104T010000"
#define UTC_CALTIME_MOD_END_UTIME 1420333200 /* 2015/01/04 01:00:00 UTC */
#define UTC_CALTIME_MOD_END_YEAR 2015
#define UTC_CALTIME_MOD_END_MONTH 1
#define UTC_CALTIME_MOD_END_MDAY 4
#define UTC_CALTIME_MOD_END_HOUR 10
#define UTC_CALTIME_MOD_END_MINUTE 0
#define UTC_CALTIME_MOD_END_SECOND 0

void _clean_db(void);

int _check_str(char *str, const char *value);
int _check_str_with_len(char *str, const char *value, int len);
int _check_int(int *i, const int value);
int _check_double(double *d, const double value);
int _check_lli(long long int *l, const long long int value);
int _check_caltime(calendar_time_s *ct, calendar_time_s value);
bool _is_feature_supported(void);

#endif /* __UTC_CALENDAR_UTIL_H__ */

