//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_MEDIA-VISION-NATIVE_H__
#define __TCT_MEDIA-VISION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_media_vision_face_startup(void);
extern void ITs_media_vision_face_cleanup(void);
extern void ITs_media_vision_image_startup(void);
extern void ITs_media_vision_image_cleanup(void);
extern void ITs_media_vision_surveillance_startup(void);
extern void ITs_media_vision_surveillance_cleanup(void);
extern void ITs_media_vision_barcode_startup(void);
extern void ITs_media_vision_barcode_cleanup(void);
extern void ITs_media_vision_inference_startup(void);
extern void ITs_media_vision_inference_cleanup(void);


extern int ITc_mv_face_recognition_model_create_destroy_p(void);
extern int ITc_mv_face_recognition_model_clone_p(void);
extern int ITc_mv_face_detect_p(void);
extern int ITc_mv_face_recognition_model_save_load_p(void);
extern int ITc_mv_face_recognition_model_add_p(void);
extern int ITc_mv_face_recognition_model_reset_p(void);
extern int ITc_mv_face_recognition_model_learn_p(void);
extern int ITc_mv_face_recognition_model_query_labels_p(void);
extern int ITc_mv_face_tracking_model_create_destroy_p(void);
extern int ITc_mv_face_tracking_model_prepare_p(void);
extern int ITc_mv_face_tracking_model_clone_p(void);
extern int ITc_mv_face_tracking_model_save_p(void);
extern int ITc_mv_face_tracking_model_load_p(void);
extern int ITc_mv_face_recognize_p(void);
extern int ITc_mv_face_track_p(void);
extern int ITc_mv_face_eye_condition_recognize_p(void);
extern int ITc_mv_face_facial_expression_recognize_p(void);
extern int ITc_mv_image_object_create_destroy_p(void);
extern int ITc_mv_image_object_fill_p(void);
extern int ITc_mv_image_object_get_recognition_rate_p(void);
extern int ITc_mv_image_object_set_get_label_p(void);
extern int ITc_mv_image_object_clone_p(void);
extern int ITc_mv_image_object_save_load_p(void);
extern int ITc_mv_image_tracking_model_create_p(void);
extern int ITc_mv_image_tracking_model_set_target_p(void);
extern int ITc_mv_image_tracking_model_destroy_p(void);
extern int ITc_mv_image_tracking_model_refresh_p(void);
extern int ITc_mv_image_tracking_model_clone_p(void);
extern int ITc_mv_image_tracking_model_save_load_p(void);
extern int ITc_mv_image_recognize_p(void);
extern int ITc_mv_image_track_p(void);
extern int ITc_mv_surveillance_event_trigger_create_destroy_p(void);
extern int ITc_mv_surveillance_get_event_trigger_type_p(void);
extern int ITc_mv_surveillance_set_get_event_trigger_roi_p(void);
extern int ITc_mv_surveillance_push_source_p(void);
extern int ITc_mv_surveillance_subscribe_unsubscribe_event_get_result_value_p(void);
extern int ITc_mv_surveillance_foreach_supported_event_type_p(void);
extern int ITc_mv_barcode_generate_source_p(void);
extern int ITc_mv_barcode_generate_image_p(void);
extern int ITc_mv_barcode_detect_p(void);
extern int ITc_mediavision_mv_inference_create_destroy_p(void);
extern int ITc_mediavision_mv_inference_configure_p(void);
extern int ITc_mediavision_mv_inference_prepare_p(void);
extern int ITc_mediavision_mv_inference_foreach_supported_engine_p(void);
extern int ITc_mediavision_mv_inference_image_classify_p(void);
extern int ITc_mediavision_mv_inference_object_detect_p(void);
extern int ITc_mediavision_mv_inference_face_detect_p(void);
extern int ITc_mediavision_mv_inference_facial_landmark_detect_p(void);
extern int ITc_mediavision_mv_engine_set_get_array_string_attribute_p(void);
extern int ITc_mediavision_mv_inference_pose_landmark_detect_p(void);
extern int ITc_mediavision_mv_inference_get_number_of_poses_p(void);
extern int ITc_mediavision_mv_inference_get_number_of_landmarks_p(void);
extern int ITc_mediavision_mv_inference_get_landmark_p(void);
extern int ITc_mediavision_mv_inference_pose_get_label_p(void);
extern int ITc_mediavision_mv_pose_create_destroy_p(void);
extern int ITc_mediavision_mv_pose_set_from_file_p(void);
extern int ITc_mediavision_mv_pose_compare_p(void);

testcase tc_array[] = {
	{"ITc_mv_face_recognition_model_create_destroy_p",ITc_mv_face_recognition_model_create_destroy_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_clone_p",ITc_mv_face_recognition_model_clone_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_detect_p",ITc_mv_face_detect_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_save_load_p",ITc_mv_face_recognition_model_save_load_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_add_p",ITc_mv_face_recognition_model_add_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_reset_p",ITc_mv_face_recognition_model_reset_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_learn_p",ITc_mv_face_recognition_model_learn_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognition_model_query_labels_p",ITc_mv_face_recognition_model_query_labels_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_tracking_model_create_destroy_p",ITc_mv_face_tracking_model_create_destroy_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_tracking_model_prepare_p",ITc_mv_face_tracking_model_prepare_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_tracking_model_clone_p",ITc_mv_face_tracking_model_clone_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_tracking_model_save_p",ITc_mv_face_tracking_model_save_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_tracking_model_load_p",ITc_mv_face_tracking_model_load_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_recognize_p",ITc_mv_face_recognize_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_track_p",ITc_mv_face_track_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_eye_condition_recognize_p",ITc_mv_face_eye_condition_recognize_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_face_facial_expression_recognize_p",ITc_mv_face_facial_expression_recognize_p,ITs_media_vision_face_startup,ITs_media_vision_face_cleanup},
	{"ITc_mv_image_object_create_destroy_p",ITc_mv_image_object_create_destroy_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_object_fill_p",ITc_mv_image_object_fill_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_object_get_recognition_rate_p",ITc_mv_image_object_get_recognition_rate_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_object_set_get_label_p",ITc_mv_image_object_set_get_label_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_object_clone_p",ITc_mv_image_object_clone_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_object_save_load_p",ITc_mv_image_object_save_load_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_create_p",ITc_mv_image_tracking_model_create_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_set_target_p",ITc_mv_image_tracking_model_set_target_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_destroy_p",ITc_mv_image_tracking_model_destroy_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_refresh_p",ITc_mv_image_tracking_model_refresh_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_clone_p",ITc_mv_image_tracking_model_clone_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_tracking_model_save_load_p",ITc_mv_image_tracking_model_save_load_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_recognize_p",ITc_mv_image_recognize_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_image_track_p",ITc_mv_image_track_p,ITs_media_vision_image_startup,ITs_media_vision_image_cleanup},
	{"ITc_mv_surveillance_event_trigger_create_destroy_p",ITc_mv_surveillance_event_trigger_create_destroy_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_surveillance_get_event_trigger_type_p",ITc_mv_surveillance_get_event_trigger_type_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_surveillance_set_get_event_trigger_roi_p",ITc_mv_surveillance_set_get_event_trigger_roi_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_surveillance_push_source_p",ITc_mv_surveillance_push_source_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_surveillance_subscribe_unsubscribe_event_get_result_value_p",ITc_mv_surveillance_subscribe_unsubscribe_event_get_result_value_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_surveillance_foreach_supported_event_type_p",ITc_mv_surveillance_foreach_supported_event_type_p,ITs_media_vision_surveillance_startup,ITs_media_vision_surveillance_cleanup},
	{"ITc_mv_barcode_generate_source_p",ITc_mv_barcode_generate_source_p,ITs_media_vision_barcode_startup,ITs_media_vision_barcode_cleanup},
	{"ITc_mv_barcode_generate_image_p",ITc_mv_barcode_generate_image_p,ITs_media_vision_barcode_startup,ITs_media_vision_barcode_cleanup},
	{"ITc_mv_barcode_detect_p",ITc_mv_barcode_detect_p,ITs_media_vision_barcode_startup,ITs_media_vision_barcode_cleanup},
	{"ITc_mediavision_mv_inference_create_destroy_p",ITc_mediavision_mv_inference_create_destroy_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_configure_p",ITc_mediavision_mv_inference_configure_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_prepare_p",ITc_mediavision_mv_inference_prepare_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_foreach_supported_engine_p",ITc_mediavision_mv_inference_foreach_supported_engine_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_image_classify_p",ITc_mediavision_mv_inference_image_classify_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_object_detect_p",ITc_mediavision_mv_inference_object_detect_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_face_detect_p",ITc_mediavision_mv_inference_face_detect_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_facial_landmark_detect_p",ITc_mediavision_mv_inference_facial_landmark_detect_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_engine_set_get_array_string_attribute_p",ITc_mediavision_mv_engine_set_get_array_string_attribute_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_pose_landmark_detect_p",ITc_mediavision_mv_inference_pose_landmark_detect_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_get_number_of_poses_p",ITc_mediavision_mv_inference_get_number_of_poses_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_get_number_of_landmarks_p",ITc_mediavision_mv_inference_get_number_of_landmarks_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_get_landmark_p",ITc_mediavision_mv_inference_get_landmark_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_inference_pose_get_label_p",ITc_mediavision_mv_inference_pose_get_label_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_pose_create_destroy_p",ITc_mediavision_mv_pose_create_destroy_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_pose_set_from_file_p",ITc_mediavision_mv_pose_set_from_file_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{"ITc_mediavision_mv_pose_compare_p",ITc_mediavision_mv_pose_compare_p,ITs_media_vision_inference_startup,ITs_media_vision_inference_cleanup},
	{NULL, NULL}
};

#endif // __TCT_MEDIA-VISION-NATIVE_H__
