//
// Copyright (c) 2019 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_NNSTREAMER-NATIVE_H__
#define __TCT_NNSTREAMER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_nnstreamer_pipeline_startup (void);
extern void ITs_nnstreamer_pipeline_cleanup (void);
extern void ITs_nnstreamer_tensors_startup (void);
extern void ITs_nnstreamer_tensors_cleanup (void);
extern void ITs_nnstreamer_tensors_single_startup (void);
extern void ITs_nnstreamer_tensors_single_cleanup (void);
extern void ITs_nnstreamer_pipeline_src_startup (void);
extern void ITs_nnstreamer_pipeline_src_cleanup (void);
extern void ITs_nnstreamer_pipeline_switch_startup (void);
extern void ITs_nnstreamer_pipeline_switch_cleanup (void);
extern void ITs_nnstreamer_capi_startup (void);
extern void ITs_nnstreamer_capi_cleanup (void);

extern int ITc_nnstreamer_pipeline_ml_pipeline_construct_destroy_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_get_state_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_start_stop_p (void);
extern int ITc_nnstreamer_pipeline_ml_check_nnfw_availability_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_sink_register_unregister_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_src_get_release_handle_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_src_get_tensors_info_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_src_input_data_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_switch_get_release_handle_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_switch_select_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_switch_get_pad_list_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_valve_get_release_handle_p (void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_valve_set_open_p (void);
extern int ITc_nnstreamer_pipeline_tizensensor_p (void);
extern int ITc_nnstreamer_pipeline_ml_check_element_availability_p(void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_create_destroy_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_clone_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_validate_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_set_get_count_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_name_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_type_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_dimension_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_info_get_tensor_size_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_data_create_destroy_p (void);
extern int ITc_nnstreamer_tensors_ml_tensors_data_set_get_tensor_data_p (void);
extern int ITc_nnstreamer_single_ml_single_open_close_p (void);
extern int ITc_nnstreamer_single_ml_single_invoke_p (void);
extern int ITc_nnstreamer_single_ml_get_set_input_info_p (void);
extern int ITc_nnstreamer_single_ml_get_output_info_p (void);
extern int ITc_nnstreamer_single_ml_set_timeout_p (void);
extern int ITc_nnstreamer_single_ml_set_get_property_p(void);
extern int ITc_nnstreamer_single_ml_invoke_dynamic_p(void);
extern int ITc_nnstreamer_single_ml_single_invoke_fast_p (void);
extern int ITc_nnstreamer_single_ml_single_open_full_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_get_release_handle_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_bool_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_string_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_int32_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_int64_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_uint32_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_uint64_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_double_p(void);
extern int ITc_nnstreamer_ml_pipeline_element_set_get_property_enum_p(void);
extern int ITc_nnstreamer_ml_pipeline_custom_easy_filter_register_unregister_p(void);
extern int ITc_nnstreamer_ml_pipeline_tensor_if_custom_register_unregister_p(void);
extern int ITc_nnstreamer_pipeline_ml_pipeline_src_set_event_cb_p(void);
extern int ITc_nnstreamer_pipeline_ml_check_nnfw_availability_full_p(void);

testcase tc_array[] = {
{"ITc_nnstreamer_pipeline_ml_pipeline_construct_destroy_p", ITc_nnstreamer_pipeline_ml_pipeline_construct_destroy_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_get_state_p", ITc_nnstreamer_pipeline_ml_pipeline_get_state_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_start_stop_p", ITc_nnstreamer_pipeline_ml_pipeline_start_stop_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_check_nnfw_availability_p", ITc_nnstreamer_pipeline_ml_check_nnfw_availability_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_sink_register_unregister_p", ITc_nnstreamer_pipeline_ml_pipeline_sink_register_unregister_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_src_get_release_handle_p", ITc_nnstreamer_pipeline_ml_pipeline_src_get_release_handle_p, ITs_nnstreamer_pipeline_src_startup, ITs_nnstreamer_pipeline_src_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_src_get_tensors_info_p", ITc_nnstreamer_pipeline_ml_pipeline_src_get_tensors_info_p, ITs_nnstreamer_pipeline_src_startup, ITs_nnstreamer_pipeline_src_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_src_input_data_p", ITc_nnstreamer_pipeline_ml_pipeline_src_input_data_p, ITs_nnstreamer_pipeline_src_startup, ITs_nnstreamer_pipeline_src_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_src_set_event_cb_p", ITc_nnstreamer_pipeline_ml_pipeline_src_set_event_cb_p, ITs_nnstreamer_pipeline_src_startup, ITs_nnstreamer_pipeline_src_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_switch_get_release_handle_p", ITc_nnstreamer_pipeline_ml_pipeline_switch_get_release_handle_p, ITs_nnstreamer_pipeline_switch_startup, ITs_nnstreamer_pipeline_switch_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_switch_select_p", ITc_nnstreamer_pipeline_ml_pipeline_switch_select_p, ITs_nnstreamer_pipeline_switch_startup, ITs_nnstreamer_pipeline_switch_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_switch_get_pad_list_p", ITc_nnstreamer_pipeline_ml_pipeline_switch_get_pad_list_p, ITs_nnstreamer_pipeline_switch_startup, ITs_nnstreamer_pipeline_switch_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_valve_get_release_handle_p", ITc_nnstreamer_pipeline_ml_pipeline_valve_get_release_handle_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_pipeline_valve_set_open_p", ITc_nnstreamer_pipeline_ml_pipeline_valve_set_open_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_tizensensor_p", ITc_nnstreamer_pipeline_tizensensor_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_pipeline_ml_check_element_availability_p", ITc_nnstreamer_pipeline_ml_check_element_availability_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_create_destroy_p", ITc_nnstreamer_tensors_ml_tensors_info_create_destroy_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_clone_p", ITc_nnstreamer_tensors_ml_tensors_info_clone_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_validate_p", ITc_nnstreamer_tensors_ml_tensors_info_validate_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_set_get_count_p", ITc_nnstreamer_tensors_ml_tensors_info_set_get_count_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_name_p", ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_name_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_type_p", ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_type_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_dimension_p", ITc_nnstreamer_tensors_ml_tensors_info_set_get_tensor_dimension_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_info_get_tensor_size_p", ITc_nnstreamer_tensors_ml_tensors_info_get_tensor_size_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_data_set_get_tensor_data_p", ITc_nnstreamer_tensors_ml_tensors_data_set_get_tensor_data_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_single_ml_single_open_close_p", ITc_nnstreamer_single_ml_single_open_close_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_single_invoke_p", ITc_nnstreamer_single_ml_single_invoke_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_get_set_input_info_p", ITc_nnstreamer_single_ml_get_set_input_info_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_get_output_info_p", ITc_nnstreamer_single_ml_get_output_info_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_set_timeout_p", ITc_nnstreamer_single_ml_set_timeout_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_tensors_ml_tensors_data_create_destroy_p", ITc_nnstreamer_tensors_ml_tensors_data_create_destroy_p, ITs_nnstreamer_tensors_startup, ITs_nnstreamer_tensors_cleanup},
{"ITc_nnstreamer_single_ml_set_get_property_p", ITc_nnstreamer_single_ml_set_get_property_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_invoke_dynamic_p", ITc_nnstreamer_single_ml_invoke_dynamic_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_single_open_full_p", ITc_nnstreamer_single_ml_single_open_full_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_single_ml_single_invoke_fast_p", ITc_nnstreamer_single_ml_single_invoke_fast_p, ITs_nnstreamer_tensors_single_startup, ITs_nnstreamer_tensors_single_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_get_release_handle_p", ITc_nnstreamer_ml_pipeline_element_get_release_handle_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_bool_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_bool_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_string_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_string_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_int32_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_int32_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_int64_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_int64_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_uint32_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_uint32_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_uint64_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_uint64_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_double_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_double_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_element_set_get_property_enum_p", ITc_nnstreamer_ml_pipeline_element_set_get_property_enum_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_custom_easy_filter_register_unregister_p", ITc_nnstreamer_ml_pipeline_custom_easy_filter_register_unregister_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_ml_pipeline_tensor_if_custom_register_unregister_p", ITc_nnstreamer_ml_pipeline_tensor_if_custom_register_unregister_p, ITs_nnstreamer_capi_startup, ITs_nnstreamer_capi_cleanup},
{"ITc_nnstreamer_pipeline_ml_check_nnfw_availability_full_p", ITc_nnstreamer_pipeline_ml_check_nnfw_availability_full_p, ITs_nnstreamer_pipeline_startup, ITs_nnstreamer_pipeline_cleanup},
  {NULL, NULL}
};

#endif // __TCT_NNSTREAMER-NATIVE_H__
