//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_BLUETOOTH-NATIVE_H__
#define __TCT_BLUETOOTH-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_bluetooth_audio_startup(void);
extern void ITs_bluetooth_audio_cleanup(void);
extern void ITs_bluetooth_device_startup(void);
extern void ITs_bluetooth_device_cleanup(void);
extern void ITs_bluetooth_adapter_le_startup(void);
extern void ITs_bluetooth_adapter_le_cleanup(void);
extern void ITs_bluetooth_startup(void);
extern void ITs_bluetooth_cleanup(void);
extern void ITs_bluetooth_OPP_startup(void);
extern void ITs_bluetooth_OPP_cleanup(void);
extern void ITs_bluetooth_socket_startup(void);
extern void ITs_bluetooth_socket_cleanup(void);
extern void ITs_bluetooth_l2cap_channel_startup(void);
extern void ITs_bluetooth_l2cap_channel_cleanup(void);

extern int ITc_bluetooth_audio_bt_audio_initialize_deinitialize_p(void);
extern int ITc_bluetooth_audio_bt_audio_set_unset_connection_state_changed_cb_p(void);
extern int ITc_bluetooth_device_bt_device_set_unset_authorization_changed_cb_p(void);
extern int ITc_bluetooth_device_bt_device_set_unset_bond_created_cb_p(void);
extern int ITc_bluetooth_device_bt_device_set_unset_bond_destroyed_cb_p(void);
extern int ITc_bluetooth_device_bt_device_set_unset_connection_state_changed_cb_p(void);
extern int ITc_bluetooth_device_bt_device_set_unset_service_searched_cb_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_le_create_destroy_advertiser_p(void);
extern int ITc_bt_adapter_le_start_stop_scan_p(void);
extern int ITc_bt_adapter_le_get_scan_info_p(void);
extern int ITc_bt_adapter_le_add_advertising_service_uuid_p(void);
extern int ITc_bt_adapter_le_add_advertising_service_solicitation_uuid_p(void);
extern int ITc_bt_adapter_le_add_advertising_service_data_p(void);
extern int ITc_bt_adapter_le_set_advertising_appearance_p(void);
extern int ITc_bt_adapter_le_add_advertising_manufacturer_data_p(void);
extern int ITc_bt_adapter_le_set_advertising_device_name_p(void);
extern int ITc_bt_adapter_le_set_advertising_tx_power_level_p(void);
extern int ITc_bt_adapter_le_start_advertising_new_p(void);
extern int ITc_bt_adapter_le_set_advertising_mode_p(void);
extern int ITc_bt_adapter_le_set_advertising_connectable_p(void);
extern int ITc_bt_adapter_le_stop_advertising_p(void);
extern int ITc_bt_adapter_le_clear_advertising_data_p(void);
extern int ITc_bt_adapter_le_set_scan_mode_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_get_name_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_unset_name_changed_cb_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_get_visibility_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_is_discovering_p(void);
extern int ITc_bluetooth_adapter_bt_start_stop_device_discovery_p(void);
extern int ITc_bluetooth_bt_initialize_deinitialize_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_unset_state_changed_cb_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_unset_device_discovery_state_changed_cb_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_is_service_used_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_get_local_oob_data_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_get_address_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_get_state_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_mode_changed_cb_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_duration_changed_cb_p(void);
extern int ITc_bluetooth_adapter_bt_get_uuid_name_p(void);
extern int ITc_bluetooth_adapter_bt_adapter_get_local_oob_ext_data_p(void);
extern int ITc_bluetooth_client_OPP_bt_opp_client_initialize_deinitialize_p(void);
extern int ITc_bluetooth_client_OPP_bt_opp_client_add_file_clear_files_p(void);
extern int ITc_bluetooth_server_OPP_bt_opp_server_initialize_deinitialize_connection_request_p(void);
extern int ITc_bluetooth_server_OPP_bt_opp_server_set_destination_p(void);
extern int ITc_bluetooth_socket_bt_socket_create_destroy_rfcomm_p(void);
extern int ITc_bluetooth_socket_bt_socket_listen_and_accept_rfcomm_p(void);
extern int ITc_bluetooth_socket_bt_socket_set_unset_connection_requested_cb_p(void);
extern int ITc_bluetooth_socket_bt_socket_set_unset_data_received_cb_p(void);
extern int ITc_bluetooth_socket_bt_socket_set_unset_connection_state_changed_cb_p(void);
extern int ITc_bt_adapter_le_scan_filter_create_destroy_p(void);
extern int ITc_bt_adapter_le_get_scan_result_free_ibeacon_report_p(void);
extern int ITc_bt_adapter_le_scan_filter_register_unregister_p(void);
extern int ITc_bt_adapter_le_scan_filter_unregister_all_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_type_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_device_name_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_device_address_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_uuid_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_uuid_with_mask_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_with_mask_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_data_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_service_data_with_mask_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_manufacturer_data_p(void);
extern int ITc_bt_adapter_le_scan_filter_set_manufacturer_data_with_mask_p(void);
extern int ITc_bt_adapter_le_is_2m_phy_supported_p(void);
extern int ITc_bt_adapter_le_is_coded_phy_supported_p(void);
extern int ITc_bt_adapter_le_is_discovering_p(void);
extern int ITc_bluetooth_bt_socket_create_destroy_l2cap_channel_p(void);
extern int ITc_bluetooth_bt_socket_listen_and_accept_l2cap_channel_p(void);
extern int ITc_bluetooth_bt_socket_get_l2cap_psm_p(void);
extern int ITc_bluetooth_bt_socket_listen_l2cap_channel_p(void);
extern int ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_requested_cb_p(void);
extern int ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_state_changed_cb_p(void);

testcase tc_array[] = {
	{"ITc_bluetooth_audio_bt_audio_initialize_deinitialize_p",ITc_bluetooth_audio_bt_audio_initialize_deinitialize_p,ITs_bluetooth_audio_startup,ITs_bluetooth_audio_cleanup},
	{"ITc_bluetooth_audio_bt_audio_set_unset_connection_state_changed_cb_p",ITc_bluetooth_audio_bt_audio_set_unset_connection_state_changed_cb_p,ITs_bluetooth_audio_startup,ITs_bluetooth_audio_cleanup},
	{"ITc_bluetooth_device_bt_device_set_unset_authorization_changed_cb_p",ITc_bluetooth_device_bt_device_set_unset_authorization_changed_cb_p,ITs_bluetooth_device_startup,ITs_bluetooth_device_cleanup},
	{"ITc_bluetooth_device_bt_device_set_unset_bond_created_cb_p",ITc_bluetooth_device_bt_device_set_unset_bond_created_cb_p,ITs_bluetooth_device_startup,ITs_bluetooth_device_cleanup},
	{"ITc_bluetooth_device_bt_device_set_unset_bond_destroyed_cb_p",ITc_bluetooth_device_bt_device_set_unset_bond_destroyed_cb_p,ITs_bluetooth_device_startup,ITs_bluetooth_device_cleanup},
	{"ITc_bluetooth_device_bt_device_set_unset_connection_state_changed_cb_p",ITc_bluetooth_device_bt_device_set_unset_connection_state_changed_cb_p,ITs_bluetooth_device_startup,ITs_bluetooth_device_cleanup},
	{"ITc_bluetooth_device_bt_device_set_unset_service_searched_cb_p",ITc_bluetooth_device_bt_device_set_unset_service_searched_cb_p,ITs_bluetooth_device_startup,ITs_bluetooth_device_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_le_create_destroy_advertiser_p",ITc_bluetooth_adapter_bt_adapter_le_create_destroy_advertiser_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_start_stop_scan_p",ITc_bt_adapter_le_start_stop_scan_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_get_scan_info_p",ITc_bt_adapter_le_get_scan_info_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_add_advertising_service_uuid_p",ITc_bt_adapter_le_add_advertising_service_uuid_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_add_advertising_service_solicitation_uuid_p",ITc_bt_adapter_le_add_advertising_service_solicitation_uuid_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_add_advertising_service_data_p",ITc_bt_adapter_le_add_advertising_service_data_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_advertising_appearance_p",ITc_bt_adapter_le_set_advertising_appearance_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_add_advertising_manufacturer_data_p",ITc_bt_adapter_le_add_advertising_manufacturer_data_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_advertising_device_name_p",ITc_bt_adapter_le_set_advertising_device_name_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_advertising_tx_power_level_p",ITc_bt_adapter_le_set_advertising_tx_power_level_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_start_advertising_new_p",ITc_bt_adapter_le_start_advertising_new_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_advertising_mode_p",ITc_bt_adapter_le_set_advertising_mode_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_advertising_connectable_p",ITc_bt_adapter_le_set_advertising_connectable_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_stop_advertising_p",ITc_bt_adapter_le_stop_advertising_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_clear_advertising_data_p",ITc_bt_adapter_le_clear_advertising_data_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_set_scan_mode_p",ITc_bt_adapter_le_set_scan_mode_p,ITs_bluetooth_adapter_le_startup,ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_get_name_p",ITc_bluetooth_adapter_bt_adapter_set_get_name_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_unset_name_changed_cb_p",ITc_bluetooth_adapter_bt_adapter_set_unset_name_changed_cb_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_get_visibility_p",ITc_bluetooth_adapter_bt_adapter_get_visibility_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_is_discovering_p",ITc_bluetooth_adapter_bt_adapter_is_discovering_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_start_stop_device_discovery_p",ITc_bluetooth_adapter_bt_start_stop_device_discovery_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_bt_initialize_deinitialize_p",ITc_bluetooth_bt_initialize_deinitialize_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_unset_state_changed_cb_p",ITc_bluetooth_adapter_bt_adapter_set_unset_state_changed_cb_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_unset_device_discovery_state_changed_cb_p",ITc_bluetooth_adapter_bt_adapter_set_unset_device_discovery_state_changed_cb_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_is_service_used_p",ITc_bluetooth_adapter_bt_adapter_is_service_used_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_get_local_oob_data_p",ITc_bluetooth_adapter_bt_adapter_get_local_oob_data_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_get_address_p",ITc_bluetooth_adapter_bt_adapter_get_address_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_get_state_p",ITc_bluetooth_adapter_bt_adapter_get_state_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_mode_changed_cb_p",ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_mode_changed_cb_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_duration_changed_cb_p",ITc_bluetooth_adapter_bt_adapter_set_unset_visibility_duration_changed_cb_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_get_uuid_name_p",ITc_bluetooth_adapter_bt_get_uuid_name_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_adapter_bt_adapter_get_local_oob_ext_data_p",ITc_bluetooth_adapter_bt_adapter_get_local_oob_ext_data_p,ITs_bluetooth_startup,ITs_bluetooth_cleanup},
	{"ITc_bluetooth_client_OPP_bt_opp_client_initialize_deinitialize_p",ITc_bluetooth_client_OPP_bt_opp_client_initialize_deinitialize_p,ITs_bluetooth_OPP_startup,ITs_bluetooth_OPP_cleanup},
	{"ITc_bluetooth_client_OPP_bt_opp_client_add_file_clear_files_p",ITc_bluetooth_client_OPP_bt_opp_client_add_file_clear_files_p,ITs_bluetooth_OPP_startup,ITs_bluetooth_OPP_cleanup},
	{"ITc_bluetooth_server_OPP_bt_opp_server_initialize_deinitialize_connection_request_p",ITc_bluetooth_server_OPP_bt_opp_server_initialize_deinitialize_connection_request_p,ITs_bluetooth_OPP_startup,ITs_bluetooth_OPP_cleanup},
	{"ITc_bluetooth_server_OPP_bt_opp_server_set_destination_p",ITc_bluetooth_server_OPP_bt_opp_server_set_destination_p,ITs_bluetooth_OPP_startup,ITs_bluetooth_OPP_cleanup},
	{"ITc_bluetooth_socket_bt_socket_create_destroy_rfcomm_p",ITc_bluetooth_socket_bt_socket_create_destroy_rfcomm_p,ITs_bluetooth_socket_startup,ITs_bluetooth_socket_cleanup},
	{"ITc_bluetooth_socket_bt_socket_listen_and_accept_rfcomm_p",ITc_bluetooth_socket_bt_socket_listen_and_accept_rfcomm_p,ITs_bluetooth_socket_startup,ITs_bluetooth_socket_cleanup},
	{"ITc_bluetooth_socket_bt_socket_set_unset_connection_requested_cb_p",ITc_bluetooth_socket_bt_socket_set_unset_connection_requested_cb_p,ITs_bluetooth_socket_startup,ITs_bluetooth_socket_cleanup},
	{"ITc_bluetooth_socket_bt_socket_set_unset_data_received_cb_p",ITc_bluetooth_socket_bt_socket_set_unset_data_received_cb_p,ITs_bluetooth_socket_startup,ITs_bluetooth_socket_cleanup},
	{"ITc_bluetooth_socket_bt_socket_set_unset_connection_state_changed_cb_p", ITc_bluetooth_socket_bt_socket_set_unset_connection_state_changed_cb_p, ITs_bluetooth_socket_startup, ITs_bluetooth_socket_cleanup},
	{"ITc_bt_adapter_le_scan_filter_create_destroy_p", ITc_bt_adapter_le_scan_filter_create_destroy_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_get_scan_result_free_ibeacon_report_p", ITc_bt_adapter_le_get_scan_result_free_ibeacon_report_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_register_unregister_p", ITc_bt_adapter_le_scan_filter_register_unregister_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_unregister_all_p", ITc_bt_adapter_le_scan_filter_unregister_all_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_type_p", ITc_bt_adapter_le_scan_filter_set_type_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_device_name_p", ITc_bt_adapter_le_scan_filter_set_device_name_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_device_address_p", ITc_bt_adapter_le_scan_filter_set_device_address_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_uuid_p", ITc_bt_adapter_le_scan_filter_set_service_uuid_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_uuid_with_mask_p", ITc_bt_adapter_le_scan_filter_set_service_uuid_with_mask_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_p", ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_with_mask_p", ITc_bt_adapter_le_scan_filter_set_service_solicitation_uuid_with_mask_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_data_p", ITc_bt_adapter_le_scan_filter_set_service_data_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_service_data_with_mask_p", ITc_bt_adapter_le_scan_filter_set_service_data_with_mask_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_manufacturer_data_p", ITc_bt_adapter_le_scan_filter_set_manufacturer_data_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_scan_filter_set_manufacturer_data_with_mask_p", ITc_bt_adapter_le_scan_filter_set_manufacturer_data_with_mask_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_is_2m_phy_supported_p", ITc_bt_adapter_le_is_2m_phy_supported_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_is_coded_phy_supported_p", ITc_bt_adapter_le_is_coded_phy_supported_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bt_adapter_le_is_discovering_p", ITc_bt_adapter_le_is_discovering_p, ITs_bluetooth_adapter_le_startup, ITs_bluetooth_adapter_le_cleanup},
	{"ITc_bluetooth_bt_socket_create_destroy_l2cap_channel_p", ITc_bluetooth_bt_socket_create_destroy_l2cap_channel_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{"ITc_bluetooth_bt_socket_listen_and_accept_l2cap_channel_p", ITc_bluetooth_bt_socket_listen_and_accept_l2cap_channel_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{"ITc_bluetooth_bt_socket_get_l2cap_psm_p", ITc_bluetooth_bt_socket_get_l2cap_psm_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{"ITc_bluetooth_bt_socket_listen_l2cap_channel_p", ITc_bluetooth_bt_socket_listen_l2cap_channel_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{"ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_requested_cb_p", ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_requested_cb_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{"ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_state_changed_cb_p", ITc_bluetooth_bt_socket_set_unset_l2cap_channel_connection_state_changed_cb_p, ITs_bluetooth_l2cap_channel_startup, ITs_bluetooth_l2cap_channel_cleanup},
	{NULL, NULL}
};

#endif // __TCT_BLUETOOTH-NATIVE_H__
