//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CONTACTS-SERVICE2-NATIVE_H__
#define __TCT_CONTACTS-SERVICE2-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_contacts_service2_database_startup(void);
extern void ITs_contacts_service2_database_cleanup(void);
extern void ITs_contacts_service2_sim_startup(void);
extern void ITs_contacts_service2_sim_cleanup(void);
extern void ITs_contacts_service2_setting_startup(void);
extern void ITs_contacts_service2_setting_cleanup(void);
extern void ITs_contacts_service2_vcard_startup(void);
extern void ITs_contacts_service2_vcard_cleanup(void);
extern void ITs_contacts_service2_query_startup(void);
extern void ITs_contacts_service2_query_cleanup(void);
extern void ITs_contacts_service2_phonelog_startup(void);
extern void ITs_contacts_service2_phonelog_cleanup(void);
extern void ITs_contacts_service2_person_startup(void);
extern void ITs_contacts_service2_person_cleanup(void);
extern void ITs_contacts_service2_record_startup(void);
extern void ITs_contacts_service2_record_cleanup(void);
extern void ITs_contacts_service2_filter_startup(void);
extern void ITs_contacts_service2_filter_cleanup(void);
extern void ITs_contacts_service2_list_startup(void);
extern void ITs_contacts_service2_list_cleanup(void);
extern void ITs_contacts_service2_group_startup(void);
extern void ITs_contacts_service2_group_cleanup(void);
extern void ITs_contacts_service2_activity_startup(void);
extern void ITs_contacts_service2_activity_cleanup(void);
extern void ITs_contacts_service2_sip_startup(void);
extern void ITs_contacts_service2_sip_cleanup(void);

extern int ITc_contacts_connect_disconnect_p(void);
extern int ITc_contacts_connect_disconnect_on_thread_p(void);
extern int ITc_contacts_connect_with_flags_p(void);
extern int ITc_contacts_db_add_remove_changed_cb_p(void);
extern int ITc_contacts_db_add_remove_status_changed_cb_p(void);
extern int ITc_contacts_db_insert_delete_records_p(void);
extern int ITc_contacts_db_insert_delete_record_p(void);
extern int ITc_contacts_db_update_record_p(void);
extern int ITc_contacts_db_get_record_p(void);
extern int ITc_contacts_db_update_records_p(void);
extern int ITc_contacts_db_replace_record_p(void);
extern int ITc_contacts_db_get_count_p(void);
extern int ITc_contacts_db_get_count_with_query_p(void);
extern int ITc_contacts_db_get_current_version_p(void);
extern int ITc_contacts_db_get_last_change_version_p(void);
extern int ITc_contacts_db_get_records_with_query_p(void);
extern int ITc_contacts_db_get_changes_by_version_p(void);
extern int ITc_contacts_db_get_status_p(void);
extern int ITc_contacts_db_replace_records_p(void);
extern int ITc_contacts_db_search_records_p(void);
extern int ITc_contacts_db_search_records_with_query_p(void);
extern int ITc_contacts_db_search_records_with_range_p(void);
extern int ITc_contacts_db_get_all_records_p(void);
extern int ITc_contacts_db_search_records_for_snippet_p(void);
extern int ITc_contacts_db_search_records_with_range_for_snippet_p(void);
extern int ITc_contacts_db_search_records_with_query_for_snippet_p(void);
extern int ITc_contacts_sim_get_initialization_status_by_sim_slot_no_p(void);
extern int ITc_contacts_sim_import_all_contacts_by_sim_slot_no_p(void);
extern int ITc_contacts_setting_set_get_name_display_order_p(void);
extern int ITc_contacts_setting_set_get_name_sorting_order_p(void);
extern int ITc_contacts_setting_add_remove_name_display_order_changed_cb_p(void);
extern int ITc_contacts_setting_add_remove_name_sorting_order_changed_cb_p(void);
extern int ITc_contacts_vcard_get_entity_count_p(void);
extern int ITc_contacts_vcard_make_from_contact_p(void);
extern int ITc_contacts_vcard_make_from_my_profile_p(void);
extern int ITc_contacts_vcard_make_from_person_p(void);
extern int ITc_contacts_vcard_parse_to_contact_foreach_p(void);
extern int ITc_contacts_vcard_parse_to_contacts_p(void);
extern int ITc_contacts_vcard_set_get_limit_size_of_photo_p(void);
extern int ITc_contacts_query_create_destroy_p(void);
extern int ITc_contacts_query_set_filter_p(void);
extern int ITc_contacts_query_set_projection_p(void);
extern int ITc_contacts_query_set_sort_p(void);
extern int ITc_contacts_query_set_distinct_p(void);
extern int ITc_contacts_phone_log_reset_statistics_p(void);
extern int ITc_contacts_phone_log_reset_statistics_by_sim_p(void);
extern int ITc_contacts_person_set_get_default_property_p01(void);
extern int ITc_contacts_person_set_get_default_property_p02(void);
extern int ITc_contacts_person_set_get_default_property_p03(void);
extern int ITc_contacts_person_set_get_default_property_p04(void);
extern int ITc_contacts_person_set_favorite_order_p(void);
extern int ITc_contacts_person_link_unlink_person_p(void);
extern int ITc_contacts_person_reset_usage_p(void);
extern int ITc_contacts_person_get_aggregation_suggestions_p(void);
extern int ITc_contacts_record_create_destroy_p(void);
extern int ITc_contacts_record_add_remove_child_record_p(void);
extern int ITc_contacts_record_clone_p(void);
extern int ITc_contacts_record_get_child_record_count_p(void);
extern int ITc_contacts_record_get_child_record_at_p_p(void);
extern int ITc_contacts_record_clone_child_record_list_p(void);
extern int ITc_contacts_record_set_get_str_p(void);
extern int ITc_contacts_record_set_get_int_p(void);
extern int ITc_contacts_record_set_get_bool_p(void);
extern int ITc_contacts_record_get_uri_p_p(void);
extern int ITc_contacts_record_get_str_p_p(void);
extern int ITc_contacts_filter_create_destroy_p(void);
extern int ITc_contacts_filter_add_bool_p(void);
extern int ITc_contacts_filter_add_int_p(void);
extern int ITc_contacts_filter_add_str_p(void);
extern int ITc_contacts_filter_add_double_p(void);
extern int ITc_contacts_filter_add_operator_p(void);
extern int ITc_contacts_filter_add_filter_p(void);
extern int ITc_contacts_list_create_destroy_p(void);
extern int ITc_contacts_list_add_remove_p(void);
extern int ITc_contacts_list_first_p(void);
extern int ITc_contacts_list_last_p(void);
extern int ITc_contacts_list_next_prev_p(void);
extern int ITc_contacts_list_get_count_p(void);
extern int ITc_contacts_list_get_current_record_p_p(void);
extern int ITc_contacts_group_add_remove_contact_p(void);
extern int ITc_contacts_group_set_group_order_p(void);
extern int ITc_contacts_activity_delete_by_account_id_p(void);
extern int ITc_contacts_activity_delete_by_contact_id_p(void);
extern int ITc_contacts_record_create_destroy_sip_p(void);
extern int ITc_contacts_record_set_get_str_sip_p(void);
extern int ITc_contacts_record_set_get_int_sip_p(void);
extern int ITc_contacts_db_get_count_for_search_records_p(void);
extern int ITc_contacts_db_get_count_for_search_records_with_range_p(void);
extern int ITc_contacts_db_get_count_for_search_records_with_query_p(void);

testcase tc_array[] = {
	{"ITc_contacts_connect_disconnect_p",ITc_contacts_connect_disconnect_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_connect_disconnect_on_thread_p",ITc_contacts_connect_disconnect_on_thread_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_connect_with_flags_p",ITc_contacts_connect_with_flags_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_add_remove_changed_cb_p",ITc_contacts_db_add_remove_changed_cb_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_add_remove_status_changed_cb_p",ITc_contacts_db_add_remove_status_changed_cb_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_insert_delete_records_p",ITc_contacts_db_insert_delete_records_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_insert_delete_record_p",ITc_contacts_db_insert_delete_record_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_update_record_p",ITc_contacts_db_update_record_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_record_p",ITc_contacts_db_get_record_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_update_records_p",ITc_contacts_db_update_records_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_replace_record_p",ITc_contacts_db_replace_record_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_count_p",ITc_contacts_db_get_count_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_count_with_query_p",ITc_contacts_db_get_count_with_query_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_current_version_p",ITc_contacts_db_get_current_version_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_last_change_version_p",ITc_contacts_db_get_last_change_version_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_records_with_query_p",ITc_contacts_db_get_records_with_query_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_changes_by_version_p",ITc_contacts_db_get_changes_by_version_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_status_p",ITc_contacts_db_get_status_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_replace_records_p",ITc_contacts_db_replace_records_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_p",ITc_contacts_db_search_records_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_with_query_p",ITc_contacts_db_search_records_with_query_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_with_range_p",ITc_contacts_db_search_records_with_range_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_all_records_p",ITc_contacts_db_get_all_records_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_for_snippet_p",ITc_contacts_db_search_records_for_snippet_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_with_range_for_snippet_p",ITc_contacts_db_search_records_with_range_for_snippet_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_search_records_with_query_for_snippet_p",ITc_contacts_db_search_records_with_query_for_snippet_p,ITs_contacts_service2_database_startup,ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_sim_get_initialization_status_by_sim_slot_no_p",ITc_contacts_sim_get_initialization_status_by_sim_slot_no_p,ITs_contacts_service2_sim_startup,ITs_contacts_service2_sim_cleanup},
	{"ITc_contacts_sim_import_all_contacts_by_sim_slot_no_p",ITc_contacts_sim_import_all_contacts_by_sim_slot_no_p,ITs_contacts_service2_sim_startup,ITs_contacts_service2_sim_cleanup},
	{"ITc_contacts_setting_set_get_name_display_order_p",ITc_contacts_setting_set_get_name_display_order_p,ITs_contacts_service2_setting_startup,ITs_contacts_service2_setting_cleanup},
	{"ITc_contacts_setting_set_get_name_sorting_order_p",ITc_contacts_setting_set_get_name_sorting_order_p,ITs_contacts_service2_setting_startup,ITs_contacts_service2_setting_cleanup},
	{"ITc_contacts_setting_add_remove_name_display_order_changed_cb_p",ITc_contacts_setting_add_remove_name_display_order_changed_cb_p,ITs_contacts_service2_setting_startup,ITs_contacts_service2_setting_cleanup},
	{"ITc_contacts_setting_add_remove_name_sorting_order_changed_cb_p",ITc_contacts_setting_add_remove_name_sorting_order_changed_cb_p,ITs_contacts_service2_setting_startup,ITs_contacts_service2_setting_cleanup},
	{"ITc_contacts_vcard_get_entity_count_p",ITc_contacts_vcard_get_entity_count_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_make_from_contact_p",ITc_contacts_vcard_make_from_contact_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_make_from_my_profile_p",ITc_contacts_vcard_make_from_my_profile_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_make_from_person_p",ITc_contacts_vcard_make_from_person_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_parse_to_contact_foreach_p",ITc_contacts_vcard_parse_to_contact_foreach_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_parse_to_contacts_p",ITc_contacts_vcard_parse_to_contacts_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_vcard_set_get_limit_size_of_photo_p",ITc_contacts_vcard_set_get_limit_size_of_photo_p,ITs_contacts_service2_vcard_startup,ITs_contacts_service2_vcard_cleanup},
	{"ITc_contacts_query_create_destroy_p",ITc_contacts_query_create_destroy_p,ITs_contacts_service2_query_startup,ITs_contacts_service2_query_cleanup},
	{"ITc_contacts_query_set_filter_p",ITc_contacts_query_set_filter_p,ITs_contacts_service2_query_startup,ITs_contacts_service2_query_cleanup},
	{"ITc_contacts_query_set_projection_p",ITc_contacts_query_set_projection_p,ITs_contacts_service2_query_startup,ITs_contacts_service2_query_cleanup},
	{"ITc_contacts_query_set_sort_p",ITc_contacts_query_set_sort_p,ITs_contacts_service2_query_startup,ITs_contacts_service2_query_cleanup},
	{"ITc_contacts_query_set_distinct_p",ITc_contacts_query_set_distinct_p,ITs_contacts_service2_query_startup,ITs_contacts_service2_query_cleanup},
	{"ITc_contacts_phone_log_reset_statistics_p",ITc_contacts_phone_log_reset_statistics_p,ITs_contacts_service2_phonelog_startup,ITs_contacts_service2_phonelog_cleanup},
	{"ITc_contacts_phone_log_reset_statistics_by_sim_p",ITc_contacts_phone_log_reset_statistics_by_sim_p,ITs_contacts_service2_phonelog_startup,ITs_contacts_service2_phonelog_cleanup},
	{"ITc_contacts_person_set_get_default_property_p01",ITc_contacts_person_set_get_default_property_p01,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_set_get_default_property_p02",ITc_contacts_person_set_get_default_property_p02,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_set_get_default_property_p03",ITc_contacts_person_set_get_default_property_p03,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_set_get_default_property_p04",ITc_contacts_person_set_get_default_property_p04,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_set_favorite_order_p",ITc_contacts_person_set_favorite_order_p,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_link_unlink_person_p",ITc_contacts_person_link_unlink_person_p,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_reset_usage_p",ITc_contacts_person_reset_usage_p,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_person_get_aggregation_suggestions_p",ITc_contacts_person_get_aggregation_suggestions_p,ITs_contacts_service2_person_startup,ITs_contacts_service2_person_cleanup},
	{"ITc_contacts_record_create_destroy_p",ITc_contacts_record_create_destroy_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_add_remove_child_record_p",ITc_contacts_record_add_remove_child_record_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_clone_p",ITc_contacts_record_clone_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_get_child_record_count_p",ITc_contacts_record_get_child_record_count_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_get_child_record_at_p_p",ITc_contacts_record_get_child_record_at_p_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_clone_child_record_list_p",ITc_contacts_record_clone_child_record_list_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_set_get_str_p",ITc_contacts_record_set_get_str_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_set_get_int_p",ITc_contacts_record_set_get_int_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_set_get_bool_p",ITc_contacts_record_set_get_bool_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_get_uri_p_p",ITc_contacts_record_get_uri_p_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_record_get_str_p_p",ITc_contacts_record_get_str_p_p,ITs_contacts_service2_record_startup,ITs_contacts_service2_record_cleanup},
	{"ITc_contacts_filter_create_destroy_p",ITc_contacts_filter_create_destroy_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_bool_p",ITc_contacts_filter_add_bool_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_int_p",ITc_contacts_filter_add_int_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_str_p",ITc_contacts_filter_add_str_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_double_p",ITc_contacts_filter_add_double_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_operator_p",ITc_contacts_filter_add_operator_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_filter_add_filter_p",ITc_contacts_filter_add_filter_p,ITs_contacts_service2_filter_startup,ITs_contacts_service2_filter_cleanup},
	{"ITc_contacts_list_create_destroy_p",ITc_contacts_list_create_destroy_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_add_remove_p",ITc_contacts_list_add_remove_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_first_p",ITc_contacts_list_first_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_last_p",ITc_contacts_list_last_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_next_prev_p",ITc_contacts_list_next_prev_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_get_count_p",ITc_contacts_list_get_count_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_list_get_current_record_p_p",ITc_contacts_list_get_current_record_p_p,ITs_contacts_service2_list_startup,ITs_contacts_service2_list_cleanup},
	{"ITc_contacts_group_add_remove_contact_p",ITc_contacts_group_add_remove_contact_p,ITs_contacts_service2_group_startup,ITs_contacts_service2_group_cleanup},
	{"ITc_contacts_group_set_group_order_p",ITc_contacts_group_set_group_order_p,ITs_contacts_service2_group_startup,ITs_contacts_service2_group_cleanup},
	{"ITc_contacts_activity_delete_by_account_id_p",ITc_contacts_activity_delete_by_account_id_p,ITs_contacts_service2_activity_startup,ITs_contacts_service2_activity_cleanup},
	{"ITc_contacts_activity_delete_by_contact_id_p",ITc_contacts_activity_delete_by_contact_id_p,ITs_contacts_service2_activity_startup,ITs_contacts_service2_activity_cleanup},
	{"ITc_contacts_record_create_destroy_sip_p",ITc_contacts_record_create_destroy_sip_p,ITs_contacts_service2_sip_startup,ITs_contacts_service2_sip_cleanup},
	{"ITc_contacts_record_set_get_str_sip_p",ITc_contacts_record_set_get_str_sip_p,ITs_contacts_service2_sip_startup,ITs_contacts_service2_sip_cleanup},
	{"ITc_contacts_record_set_get_int_sip_p",ITc_contacts_record_set_get_int_sip_p,ITs_contacts_service2_sip_startup,ITs_contacts_service2_sip_cleanup},
	{"ITc_contacts_db_get_count_for_search_records_p", ITc_contacts_db_get_count_for_search_records_p, ITs_contacts_service2_database_startup, ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_count_for_search_records_with_range_p", ITc_contacts_db_get_count_for_search_records_with_range_p, ITs_contacts_service2_database_startup, ITs_contacts_service2_database_cleanup},
	{"ITc_contacts_db_get_count_for_search_records_with_query_p", ITc_contacts_db_get_count_for_search_records_with_query_p, ITs_contacts_service2_database_startup, ITs_contacts_service2_database_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CONTACTS-SERVICE2-NATIVE_H__
