//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_TELEPHONY-NATIVE_H__
#define __TCT_TELEPHONY-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_telephony_common_startup(void);
extern void utc_telephony_common_cleanup(void);
extern void utc_telephony_call_startup(void);
extern void utc_telephony_call_cleanup(void);
extern void utc_telephony_network_startup(void);
extern void utc_telephony_network_cleanup(void);
extern void utc_telephony_sim_startup(void);
extern void utc_telephony_sim_cleanup(void);
extern void utc_telephony_modem_startup(void);
extern void utc_telephony_modem_cleanup(void);

extern int utc_telephony_telephony_init_p(void);
extern int utc_telephony_telephony_init_n(void);
extern int utc_telephony_telephony_deinit_p(void);
extern int utc_telephony_telephony_deinit_n(void);
extern int utc_telephony_telephony_set_noti_cb_p1(void);
extern int utc_telephony_telephony_set_noti_cb_p2(void);
extern int utc_telephony_telephony_set_noti_cb_p3(void);
extern int utc_telephony_telephony_set_noti_cb_p4(void);
extern int utc_telephony_telephony_set_noti_cb_p5(void);
extern int utc_telephony_telephony_set_noti_cb_p6(void);
extern int utc_telephony_telephony_set_noti_cb_p7(void);
extern int utc_telephony_telephony_set_noti_cb_p8(void);
extern int utc_telephony_telephony_set_noti_cb_p9(void);
extern int utc_telephony_telephony_set_noti_cb_p12(void);
extern int utc_telephony_telephony_set_noti_cb_p13(void);
extern int utc_telephony_telephony_set_noti_cb_p14(void);
extern int utc_telephony_telephony_set_noti_cb_p15(void);
extern int utc_telephony_telephony_set_noti_cb_p16(void);
extern int utc_telephony_telephony_set_noti_cb_p17(void);
extern int utc_telephony_telephony_set_noti_cb_p18(void);
extern int utc_telephony_telephony_set_noti_cb_p19(void);
extern int utc_telephony_telephony_set_noti_cb_p20(void);
extern int utc_telephony_telephony_set_noti_cb_p21(void);
extern int utc_telephony_telephony_set_noti_cb_p22(void);
extern int utc_telephony_telephony_set_noti_cb_p23(void);
extern int utc_telephony_telephony_set_noti_cb_p24(void);
extern int utc_telephony_telephony_set_noti_cb_p25(void);
extern int utc_telephony_telephony_set_noti_cb_p26(void);
extern int utc_telephony_telephony_set_noti_cb_p27(void);
extern int utc_telephony_telephony_set_noti_cb_p28(void);
extern int utc_telephony_telephony_set_noti_cb_p29(void);
extern int utc_telephony_telephony_set_noti_cb_p30(void);
extern int utc_telephony_telephony_set_noti_cb_p31(void);
extern int utc_telephony_telephony_set_noti_cb_p32(void);
extern int utc_telephony_telephony_set_noti_cb_n1(void);
extern int utc_telephony_telephony_set_noti_cb_n2(void);
extern int utc_telephony_telephony_unset_noti_cb_p1(void);
extern int utc_telephony_telephony_unset_noti_cb_p2(void);
extern int utc_telephony_telephony_unset_noti_cb_p3(void);
extern int utc_telephony_telephony_unset_noti_cb_p4(void);
extern int utc_telephony_telephony_unset_noti_cb_p5(void);
extern int utc_telephony_telephony_unset_noti_cb_p6(void);
extern int utc_telephony_telephony_unset_noti_cb_p7(void);
extern int utc_telephony_telephony_unset_noti_cb_p8(void);
extern int utc_telephony_telephony_unset_noti_cb_p9(void);
extern int utc_telephony_telephony_unset_noti_cb_p12(void);
extern int utc_telephony_telephony_unset_noti_cb_p13(void);
extern int utc_telephony_telephony_unset_noti_cb_p14(void);
extern int utc_telephony_telephony_unset_noti_cb_p15(void);
extern int utc_telephony_telephony_unset_noti_cb_p16(void);
extern int utc_telephony_telephony_unset_noti_cb_p17(void);
extern int utc_telephony_telephony_unset_noti_cb_p18(void);
extern int utc_telephony_telephony_unset_noti_cb_p19(void);
extern int utc_telephony_telephony_unset_noti_cb_p20(void);
extern int utc_telephony_telephony_unset_noti_cb_p21(void);
extern int utc_telephony_telephony_unset_noti_cb_p22(void);
extern int utc_telephony_telephony_unset_noti_cb_p23(void);
extern int utc_telephony_telephony_unset_noti_cb_p24(void);
extern int utc_telephony_telephony_unset_noti_cb_p25(void);
extern int utc_telephony_telephony_unset_noti_cb_p26(void);
extern int utc_telephony_telephony_unset_noti_cb_p27(void);
extern int utc_telephony_telephony_unset_noti_cb_p28(void);
extern int utc_telephony_telephony_unset_noti_cb_p29(void);
extern int utc_telephony_telephony_unset_noti_cb_p30(void);
extern int utc_telephony_telephony_unset_noti_cb_p31(void);
extern int utc_telephony_telephony_unset_noti_cb_p32(void);
extern int utc_telephony_telephony_unset_noti_cb_n1(void);
extern int utc_telephony_telephony_unset_noti_cb_n2(void);
extern int utc_telephony_get_state_p(void);
extern int utc_telephony_get_state_n(void);
extern int utc_telephony_set_state_changed_cb_p(void);
extern int utc_telephony_set_state_changed_cb_n(void);
extern int utc_telephony_unset_state_changed_cb_p(void);
extern int utc_telephony_unset_state_changed_cb_n(void);
extern int utc_telephony_telephony_call_get_preferred_voice_subscription_p(void);
extern int utc_telephony_telephony_call_get_preferred_voice_subscription_n1(void);
extern int utc_telephony_telephony_call_get_preferred_voice_subscription_n2(void);
extern int utc_telephony_telephony_call_get_call_list_p(void);
extern int utc_telephony_telephony_call_get_call_list_n1(void);
extern int utc_telephony_telephony_call_get_call_list_n2(void);
extern int utc_telephony_telephony_call_get_call_list_n3(void);
extern int utc_telephony_telephony_call_release_call_list_p(void);
extern int utc_telephony_telephony_call_release_call_list_n(void);
extern int utc_telephony_telephony_call_get_handle_id_n1(void);
extern int utc_telephony_telephony_call_get_handle_id_n2(void);
extern int utc_telephony_telephony_call_get_number_n1(void);
extern int utc_telephony_telephony_call_get_number_n2(void);
extern int utc_telephony_telephony_call_get_type_n1(void);
extern int utc_telephony_telephony_call_get_type_n2(void);
extern int utc_telephony_telephony_call_get_status_n1(void);
extern int utc_telephony_telephony_call_get_status_n2(void);
extern int utc_telephony_telephony_call_get_direction_n1(void);
extern int utc_telephony_telephony_call_get_direction_n2(void);
extern int utc_telephony_telephony_call_get_conference_status_n1(void);
extern int utc_telephony_telephony_call_get_conference_status_n2(void);
extern int utc_telephony_telephony_network_get_lac_p(void);
extern int utc_telephony_telephony_network_get_lac_n1(void);
extern int utc_telephony_telephony_network_get_lac_n2(void);
extern int utc_telephony_telephony_network_get_cell_id_p(void);
extern int utc_telephony_telephony_network_get_cell_id_n1(void);
extern int utc_telephony_telephony_network_get_cell_id_n2(void);
extern int utc_telephony_telephony_network_get_rssi_p(void);
extern int utc_telephony_telephony_network_get_rssi_n1(void);
extern int utc_telephony_telephony_network_get_rssi_n2(void);
extern int utc_telephony_telephony_network_get_roaming_status_p(void);
extern int utc_telephony_telephony_network_get_roaming_status_n1(void);
extern int utc_telephony_telephony_network_get_roaming_status_n2(void);
extern int utc_telephony_telephony_network_get_mcc_p(void);
extern int utc_telephony_telephony_network_get_mcc_n1(void);
extern int utc_telephony_telephony_network_get_mcc_n2(void);
extern int utc_telephony_telephony_network_get_mnc_p(void);
extern int utc_telephony_telephony_network_get_mnc_n1(void);
extern int utc_telephony_telephony_network_get_mnc_n2(void);
extern int utc_telephony_telephony_network_get_network_name_p(void);
extern int utc_telephony_telephony_network_get_network_name_n1(void);
extern int utc_telephony_telephony_network_get_network_name_n2(void);
extern int utc_telephony_telephony_network_get_type_p(void);
extern int utc_telephony_telephony_network_get_type_n1(void);
extern int utc_telephony_telephony_network_get_type_n2(void);
extern int utc_telephony_telephony_network_get_ps_type_p(void);
extern int utc_telephony_telephony_network_get_ps_type_n1(void);
extern int utc_telephony_telephony_network_get_ps_type_n2(void);
extern int utc_telephony_telephony_network_get_network_name_option_p(void);
extern int utc_telephony_telephony_network_get_network_name_option_n1(void);
extern int utc_telephony_telephony_network_get_network_name_option_n2(void);
extern int utc_telephony_telephony_network_get_service_state_p(void);
extern int utc_telephony_telephony_network_get_service_state_n1(void);
extern int utc_telephony_telephony_network_get_service_state_n2(void);
extern int utc_telephony_telephony_network_get_default_data_subscription_p(void);
extern int utc_telephony_telephony_network_get_default_data_subscription_n1(void);
extern int utc_telephony_telephony_network_get_default_data_subscription_n2(void);
extern int utc_telephony_telephony_network_get_default_subscription_p(void);
extern int utc_telephony_telephony_network_get_default_subscription_n1(void);
extern int utc_telephony_telephony_network_get_default_subscription_n2(void);
extern int utc_telephony_telephony_network_get_selection_mode_p(void);
extern int utc_telephony_telephony_network_get_selection_mode_n1(void);
extern int utc_telephony_telephony_network_get_selection_mode_n2(void);
extern int utc_telephony_telephony_network_get_tac_p(void);
extern int utc_telephony_telephony_network_get_tac_n1(void);
extern int utc_telephony_telephony_network_get_tac_n2(void);
extern int utc_telephony_telephony_network_get_system_id_p(void);
extern int utc_telephony_telephony_network_get_system_id_n1(void);
extern int utc_telephony_telephony_network_get_system_id_n2(void);
extern int utc_telephony_telephony_network_get_network_id_p(void);
extern int utc_telephony_telephony_network_get_network_id_n1(void);
extern int utc_telephony_telephony_network_get_network_id_n2(void);
extern int utc_telephony_telephony_network_get_base_station_id_p(void);
extern int utc_telephony_telephony_network_get_base_station_id_n1(void);
extern int utc_telephony_telephony_network_get_base_station_id_n2(void);
extern int utc_telephony_telephony_network_get_base_station_latitude_p(void);
extern int utc_telephony_telephony_network_get_base_station_latitude_n1(void);
extern int utc_telephony_telephony_network_get_base_station_latitude_n2(void);
extern int utc_telephony_telephony_network_get_base_station_longitude_p(void);
extern int utc_telephony_telephony_network_get_base_station_longitude_n1(void);
extern int utc_telephony_telephony_network_get_base_station_longitude_n2(void);
extern int utc_telephony_telephony_network_get_signal_strength_p(void);
extern int utc_telephony_telephony_network_get_signal_strength_n1(void);
extern int utc_telephony_telephony_network_get_signal_strength_n2(void);
extern int utc_telephony_telephony_sim_get_operator_p(void);
extern int utc_telephony_telephony_sim_get_operator_n1(void);
extern int utc_telephony_telephony_sim_get_operator_n2(void);
extern int utc_telephony_telephony_sim_get_msin_p(void);
extern int utc_telephony_telephony_sim_get_msin_n1(void);
extern int utc_telephony_telephony_sim_get_msin_n2(void);
extern int utc_telephony_telephony_sim_get_spn_p(void);
extern int utc_telephony_telephony_sim_get_spn_n1(void);
extern int utc_telephony_telephony_sim_get_spn_n2(void);
extern int utc_telephony_telephony_sim_is_changed_p(void);
extern int utc_telephony_telephony_sim_is_changed_n1(void);
extern int utc_telephony_telephony_sim_is_changed_n2(void);
extern int utc_telephony_telephony_sim_get_state_p(void);
extern int utc_telephony_telephony_sim_get_state_n1(void);
extern int utc_telephony_telephony_sim_get_state_n2(void);
extern int utc_telephony_telephony_sim_get_application_list_p(void);
extern int utc_telephony_telephony_sim_get_application_list_n1(void);
extern int utc_telephony_telephony_sim_get_application_list_n2(void);
extern int utc_telephony_telephony_sim_get_subscriber_number_p(void);
extern int utc_telephony_telephony_sim_get_subscriber_number_n1(void);
extern int utc_telephony_telephony_sim_get_subscriber_number_n2(void);
extern int utc_telephony_telephony_sim_get_subscriber_id_p(void);
extern int utc_telephony_telephony_sim_get_subscriber_id_n1(void);
extern int utc_telephony_telephony_sim_get_subscriber_id_n2(void);
extern int utc_telephony_telephony_sim_get_lock_state_p(void);
extern int utc_telephony_telephony_sim_get_lock_state_n1(void);
extern int utc_telephony_telephony_sim_get_lock_state_n2(void);
extern int utc_telephony_telephony_sim_get_group_id1_p(void);
extern int utc_telephony_telephony_sim_get_group_id1_n1(void);
extern int utc_telephony_telephony_sim_get_group_id1_n2(void);
extern int utc_telephony_telephony_sim_get_call_forwarding_indicator_state_p(void);
extern int utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n1(void);
extern int utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n2(void);
extern int utc_telephony_telephony_modem_get_power_status_p(void);
extern int utc_telephony_telephony_modem_get_power_status_n1(void);
extern int utc_telephony_telephony_modem_get_power_status_n2(void);

testcase tc_array[] = {
	{"utc_telephony_telephony_init_p",utc_telephony_telephony_init_p,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_init_n",utc_telephony_telephony_init_n,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_deinit_p",utc_telephony_telephony_deinit_p,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_deinit_n",utc_telephony_telephony_deinit_n,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p1",utc_telephony_telephony_set_noti_cb_p1,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p2",utc_telephony_telephony_set_noti_cb_p2,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p3",utc_telephony_telephony_set_noti_cb_p3,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p4",utc_telephony_telephony_set_noti_cb_p4,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p5",utc_telephony_telephony_set_noti_cb_p5,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p6",utc_telephony_telephony_set_noti_cb_p6,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p7",utc_telephony_telephony_set_noti_cb_p7,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p8",utc_telephony_telephony_set_noti_cb_p8,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p9",utc_telephony_telephony_set_noti_cb_p9,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p12",utc_telephony_telephony_set_noti_cb_p12,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p13",utc_telephony_telephony_set_noti_cb_p13,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p14",utc_telephony_telephony_set_noti_cb_p14,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p15",utc_telephony_telephony_set_noti_cb_p15,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p16",utc_telephony_telephony_set_noti_cb_p16,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p17",utc_telephony_telephony_set_noti_cb_p17,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p18",utc_telephony_telephony_set_noti_cb_p18,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p19",utc_telephony_telephony_set_noti_cb_p19,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p20",utc_telephony_telephony_set_noti_cb_p20,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p21",utc_telephony_telephony_set_noti_cb_p21,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p22",utc_telephony_telephony_set_noti_cb_p22,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p23",utc_telephony_telephony_set_noti_cb_p23,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p24",utc_telephony_telephony_set_noti_cb_p24,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p25",utc_telephony_telephony_set_noti_cb_p25,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p26",utc_telephony_telephony_set_noti_cb_p26,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p27",utc_telephony_telephony_set_noti_cb_p27,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p28",utc_telephony_telephony_set_noti_cb_p28,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p29",utc_telephony_telephony_set_noti_cb_p29,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p30",utc_telephony_telephony_set_noti_cb_p30,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p31",utc_telephony_telephony_set_noti_cb_p31,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_p32",utc_telephony_telephony_set_noti_cb_p32,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_n1",utc_telephony_telephony_set_noti_cb_n1,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_set_noti_cb_n2",utc_telephony_telephony_set_noti_cb_n2,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p1",utc_telephony_telephony_unset_noti_cb_p1,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p2",utc_telephony_telephony_unset_noti_cb_p2,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p3",utc_telephony_telephony_unset_noti_cb_p3,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p4",utc_telephony_telephony_unset_noti_cb_p4,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p5",utc_telephony_telephony_unset_noti_cb_p5,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p6",utc_telephony_telephony_unset_noti_cb_p6,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p7",utc_telephony_telephony_unset_noti_cb_p7,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p8",utc_telephony_telephony_unset_noti_cb_p8,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p9",utc_telephony_telephony_unset_noti_cb_p9,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p12",utc_telephony_telephony_unset_noti_cb_p12,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p13",utc_telephony_telephony_unset_noti_cb_p13,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p14",utc_telephony_telephony_unset_noti_cb_p14,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p15",utc_telephony_telephony_unset_noti_cb_p15,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p16",utc_telephony_telephony_unset_noti_cb_p16,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p17",utc_telephony_telephony_unset_noti_cb_p17,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p18",utc_telephony_telephony_unset_noti_cb_p18,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p19",utc_telephony_telephony_unset_noti_cb_p19,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p20",utc_telephony_telephony_unset_noti_cb_p20,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p21",utc_telephony_telephony_unset_noti_cb_p21,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p22",utc_telephony_telephony_unset_noti_cb_p22,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p23",utc_telephony_telephony_unset_noti_cb_p23,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p24",utc_telephony_telephony_unset_noti_cb_p24,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p25",utc_telephony_telephony_unset_noti_cb_p25,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p26",utc_telephony_telephony_unset_noti_cb_p26,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p27",utc_telephony_telephony_unset_noti_cb_p27,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p28",utc_telephony_telephony_unset_noti_cb_p28,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p29",utc_telephony_telephony_unset_noti_cb_p29,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p30",utc_telephony_telephony_unset_noti_cb_p30,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p31",utc_telephony_telephony_unset_noti_cb_p31,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_p32",utc_telephony_telephony_unset_noti_cb_p32,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_n1",utc_telephony_telephony_unset_noti_cb_n1,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_unset_noti_cb_n2",utc_telephony_telephony_unset_noti_cb_n2,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_get_state_p",utc_telephony_get_state_p,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_get_state_n",utc_telephony_get_state_n,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_set_state_changed_cb_p",utc_telephony_set_state_changed_cb_p,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_set_state_changed_cb_n",utc_telephony_set_state_changed_cb_n,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_unset_state_changed_cb_p",utc_telephony_unset_state_changed_cb_p,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_unset_state_changed_cb_n",utc_telephony_unset_state_changed_cb_n,utc_telephony_common_startup,utc_telephony_common_cleanup},
	{"utc_telephony_telephony_call_get_preferred_voice_subscription_p",utc_telephony_telephony_call_get_preferred_voice_subscription_p,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_preferred_voice_subscription_n1",utc_telephony_telephony_call_get_preferred_voice_subscription_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_preferred_voice_subscription_n2",utc_telephony_telephony_call_get_preferred_voice_subscription_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_call_list_p",utc_telephony_telephony_call_get_call_list_p,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_call_list_n1",utc_telephony_telephony_call_get_call_list_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_call_list_n2",utc_telephony_telephony_call_get_call_list_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_call_list_n3",utc_telephony_telephony_call_get_call_list_n3,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_release_call_list_p",utc_telephony_telephony_call_release_call_list_p,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_release_call_list_n",utc_telephony_telephony_call_release_call_list_n,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_handle_id_n1",utc_telephony_telephony_call_get_handle_id_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_handle_id_n2",utc_telephony_telephony_call_get_handle_id_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_number_n1",utc_telephony_telephony_call_get_number_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_number_n2",utc_telephony_telephony_call_get_number_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_type_n1",utc_telephony_telephony_call_get_type_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_type_n2",utc_telephony_telephony_call_get_type_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_status_n1",utc_telephony_telephony_call_get_status_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_status_n2",utc_telephony_telephony_call_get_status_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_direction_n1",utc_telephony_telephony_call_get_direction_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_direction_n2",utc_telephony_telephony_call_get_direction_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_conference_status_n1",utc_telephony_telephony_call_get_conference_status_n1,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_call_get_conference_status_n2",utc_telephony_telephony_call_get_conference_status_n2,utc_telephony_call_startup,utc_telephony_call_cleanup},
	{"utc_telephony_telephony_network_get_lac_p",utc_telephony_telephony_network_get_lac_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_lac_n1",utc_telephony_telephony_network_get_lac_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_lac_n2",utc_telephony_telephony_network_get_lac_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_cell_id_p",utc_telephony_telephony_network_get_cell_id_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_cell_id_n1",utc_telephony_telephony_network_get_cell_id_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_cell_id_n2",utc_telephony_telephony_network_get_cell_id_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_rssi_p",utc_telephony_telephony_network_get_rssi_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_rssi_n1",utc_telephony_telephony_network_get_rssi_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_rssi_n2",utc_telephony_telephony_network_get_rssi_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_roaming_status_p",utc_telephony_telephony_network_get_roaming_status_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_roaming_status_n1",utc_telephony_telephony_network_get_roaming_status_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_roaming_status_n2",utc_telephony_telephony_network_get_roaming_status_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mcc_p",utc_telephony_telephony_network_get_mcc_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mcc_n1",utc_telephony_telephony_network_get_mcc_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mcc_n2",utc_telephony_telephony_network_get_mcc_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mnc_p",utc_telephony_telephony_network_get_mnc_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mnc_n1",utc_telephony_telephony_network_get_mnc_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_mnc_n2",utc_telephony_telephony_network_get_mnc_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_p",utc_telephony_telephony_network_get_network_name_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_n1",utc_telephony_telephony_network_get_network_name_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_n2",utc_telephony_telephony_network_get_network_name_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_type_p",utc_telephony_telephony_network_get_type_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_type_n1",utc_telephony_telephony_network_get_type_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_type_n2",utc_telephony_telephony_network_get_type_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_ps_type_p",utc_telephony_telephony_network_get_ps_type_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_ps_type_n1",utc_telephony_telephony_network_get_ps_type_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_ps_type_n2",utc_telephony_telephony_network_get_ps_type_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_option_p",utc_telephony_telephony_network_get_network_name_option_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_option_n1",utc_telephony_telephony_network_get_network_name_option_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_name_option_n2",utc_telephony_telephony_network_get_network_name_option_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_service_state_p",utc_telephony_telephony_network_get_service_state_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_service_state_n1",utc_telephony_telephony_network_get_service_state_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_service_state_n2",utc_telephony_telephony_network_get_service_state_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_data_subscription_p",utc_telephony_telephony_network_get_default_data_subscription_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_data_subscription_n1",utc_telephony_telephony_network_get_default_data_subscription_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_data_subscription_n2",utc_telephony_telephony_network_get_default_data_subscription_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_subscription_p",utc_telephony_telephony_network_get_default_subscription_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_subscription_n1",utc_telephony_telephony_network_get_default_subscription_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_default_subscription_n2",utc_telephony_telephony_network_get_default_subscription_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_selection_mode_p",utc_telephony_telephony_network_get_selection_mode_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_selection_mode_n1",utc_telephony_telephony_network_get_selection_mode_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_selection_mode_n2",utc_telephony_telephony_network_get_selection_mode_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_tac_p",utc_telephony_telephony_network_get_tac_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_tac_n1",utc_telephony_telephony_network_get_tac_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_tac_n2",utc_telephony_telephony_network_get_tac_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_system_id_p",utc_telephony_telephony_network_get_system_id_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_system_id_n1",utc_telephony_telephony_network_get_system_id_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_system_id_n2",utc_telephony_telephony_network_get_system_id_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_id_p",utc_telephony_telephony_network_get_network_id_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_id_n1",utc_telephony_telephony_network_get_network_id_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_network_id_n2",utc_telephony_telephony_network_get_network_id_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_id_p",utc_telephony_telephony_network_get_base_station_id_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_id_n1",utc_telephony_telephony_network_get_base_station_id_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_id_n2",utc_telephony_telephony_network_get_base_station_id_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_latitude_p",utc_telephony_telephony_network_get_base_station_latitude_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_latitude_n1",utc_telephony_telephony_network_get_base_station_latitude_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_latitude_n2",utc_telephony_telephony_network_get_base_station_latitude_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_longitude_p",utc_telephony_telephony_network_get_base_station_longitude_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_longitude_n1",utc_telephony_telephony_network_get_base_station_longitude_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_base_station_longitude_n2",utc_telephony_telephony_network_get_base_station_longitude_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_signal_strength_p",utc_telephony_telephony_network_get_signal_strength_p,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_signal_strength_n1",utc_telephony_telephony_network_get_signal_strength_n1,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_network_get_signal_strength_n2",utc_telephony_telephony_network_get_signal_strength_n2,utc_telephony_network_startup,utc_telephony_network_cleanup},
	{"utc_telephony_telephony_sim_get_operator_p",utc_telephony_telephony_sim_get_operator_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_operator_n1",utc_telephony_telephony_sim_get_operator_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_operator_n2",utc_telephony_telephony_sim_get_operator_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_msin_p",utc_telephony_telephony_sim_get_msin_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_msin_n1",utc_telephony_telephony_sim_get_msin_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_msin_n2",utc_telephony_telephony_sim_get_msin_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_spn_p",utc_telephony_telephony_sim_get_spn_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_spn_n1",utc_telephony_telephony_sim_get_spn_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_spn_n2",utc_telephony_telephony_sim_get_spn_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_is_changed_p",utc_telephony_telephony_sim_is_changed_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_is_changed_n1",utc_telephony_telephony_sim_is_changed_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_is_changed_n2",utc_telephony_telephony_sim_is_changed_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_state_p",utc_telephony_telephony_sim_get_state_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_state_n1",utc_telephony_telephony_sim_get_state_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_state_n2",utc_telephony_telephony_sim_get_state_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_application_list_p",utc_telephony_telephony_sim_get_application_list_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_application_list_n1",utc_telephony_telephony_sim_get_application_list_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_application_list_n2",utc_telephony_telephony_sim_get_application_list_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_number_p",utc_telephony_telephony_sim_get_subscriber_number_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_number_n1",utc_telephony_telephony_sim_get_subscriber_number_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_number_n2",utc_telephony_telephony_sim_get_subscriber_number_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_id_p",utc_telephony_telephony_sim_get_subscriber_id_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_id_n1",utc_telephony_telephony_sim_get_subscriber_id_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_subscriber_id_n2",utc_telephony_telephony_sim_get_subscriber_id_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_lock_state_p",utc_telephony_telephony_sim_get_lock_state_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_lock_state_n1",utc_telephony_telephony_sim_get_lock_state_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_lock_state_n2",utc_telephony_telephony_sim_get_lock_state_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_group_id1_p",utc_telephony_telephony_sim_get_group_id1_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_group_id1_n1",utc_telephony_telephony_sim_get_group_id1_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_group_id1_n2",utc_telephony_telephony_sim_get_group_id1_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_call_forwarding_indicator_state_p",utc_telephony_telephony_sim_get_call_forwarding_indicator_state_p,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n1",utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n1,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n2",utc_telephony_telephony_sim_get_call_forwarding_indicator_state_n2,utc_telephony_sim_startup,utc_telephony_sim_cleanup},
	{"utc_telephony_telephony_modem_get_power_status_p",utc_telephony_telephony_modem_get_power_status_p,utc_telephony_modem_startup,utc_telephony_modem_cleanup},
	{"utc_telephony_telephony_modem_get_power_status_n1",utc_telephony_telephony_modem_get_power_status_n1,utc_telephony_modem_startup,utc_telephony_modem_cleanup},
	{"utc_telephony_telephony_modem_get_power_status_n2",utc_telephony_telephony_modem_get_power_status_n2,utc_telephony_modem_startup,utc_telephony_modem_cleanup},
	{NULL, NULL}
};

#endif // __TCT_TELEPHONY-NATIVE_H__
