//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WIDGET_VIEWER_EVAS-NATIVE_H__
#define __TCT_WIDGET_VIEWER_EVAS-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_widget_viewer_evas_startup(void);
extern void utc_widget_viewer_evas_cleanup(void);

extern int utc_widget_viewer_evas_init_n(void);
extern int utc_widget_viewer_evas_fini_n(void);
extern int utc_widget_viewer_evas_add_widget_n(void);
extern int utc_widget_viewer_evas_add_widget_n2(void);
extern int utc_widget_viewer_evas_notify_resumed_status_of_viewer_n(void);
extern int utc_widget_viewer_evas_notify_paused_status_of_viewer_n(void);
extern int utc_widget_viewer_evas_notify_orientation_of_viewer_n(void);
extern int utc_widget_viewer_evas_pause_widget_n1(void);
extern int utc_widget_viewer_evas_pause_widget_n2(void);
extern int utc_widget_viewer_evas_resume_widget_n(void);
extern int utc_widget_viewer_evas_set_option_n(void);
extern int utc_widget_viewer_evas_get_content_info_n(void);
extern int utc_widget_viewer_evas_get_title_string_n(void);
extern int utc_widget_viewer_evas_get_widget_id_n1(void);
extern int utc_widget_viewer_evas_get_widget_id_n2(void);
extern int utc_widget_viewer_evas_get_period_n1(void);
extern int utc_widget_viewer_evas_get_period_n2(void);
extern int utc_widget_viewer_evas_cancel_click_event_n(void);
extern int utc_widget_viewer_evas_disable_preview_n(void);
extern int utc_widget_viewer_evas_disable_overlay_text_n(void);
extern int utc_widget_viewer_evas_disable_loading_n(void);
extern int utc_widget_viewer_evas_feed_mouse_up_event_p(void);
extern int utc_widget_viewer_evas_feed_mouse_up_event_n(void);
extern int utc_widget_viewer_evas_activate_faulted_widget_n(void);
extern int utc_widget_viewer_evas_is_faulted_n(void);
extern int utc_widget_viewer_evas_freeze_visibility_n1(void);
extern int utc_widget_viewer_evas_freeze_visibility_n2(void);
extern int utc_widget_viewer_evas_thaw_visibility_n(void);
extern int utc_widget_viewer_evas_is_visibility_frozen_n(void);
extern int utc_widget_viewer_evas_is_widget_n(void);
extern int utc_widget_viewer_evas_set_permanent_delete_n(void);
extern int utc_widget_viewer_evas_init_p(void);
extern int utc_widget_viewer_evas_fini_p(void);
extern int utc_widget_viewer_evas_add_widget_p1(void);
extern int utc_widget_viewer_evas_add_widget_p2(void);
extern int utc_widget_viewer_evas_notify_resumed_status_of_viewer_p(void);
extern int utc_widget_viewer_evas_notify_paused_status_of_viewer_p(void);
extern int utc_widget_viewer_evas_notify_orientation_of_viewer_p(void);
extern int utc_widget_viewer_evas_pause_widget_p(void);
extern int utc_widget_viewer_evas_resume_widget_p(void);
extern int utc_widget_viewer_evas_set_option_p(void);
extern int utc_widget_viewer_evas_get_content_info_p(void);
extern int utc_widget_viewer_evas_get_title_string_p(void);
extern int utc_widget_viewer_evas_get_widget_id_p(void);
extern int utc_widget_viewer_evas_get_period_p(void);
extern int utc_widget_viewer_evas_cancel_click_event_p(void);
extern int utc_widget_viewer_evas_disable_preview_p(void);
extern int utc_widget_viewer_evas_disable_overlay_text_p(void);
extern int utc_widget_viewer_evas_disable_loading_p(void);
extern int utc_widget_viewer_evas_activate_faulted_widget_p(void);
extern int utc_widget_viewer_evas_is_faulted_p(void);
extern int utc_widget_viewer_evas_freeze_visibility_p(void);
extern int utc_widget_viewer_evas_thaw_visibility_p(void);
extern int utc_widget_viewer_evas_is_visibility_frozen_p(void);
extern int utc_widget_viewer_evas_is_widget_p(void);
extern int utc_widget_viewer_evas_set_permanent_delete_p(void);
extern int utc_widget_viewer_evas_get_widget_instance_id_p(void);

testcase tc_array[] = {
	{"utc_widget_viewer_evas_init_n",utc_widget_viewer_evas_init_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_fini_n",utc_widget_viewer_evas_fini_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_add_widget_n",utc_widget_viewer_evas_add_widget_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_add_widget_n2",utc_widget_viewer_evas_add_widget_n2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_resumed_status_of_viewer_n",utc_widget_viewer_evas_notify_resumed_status_of_viewer_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_paused_status_of_viewer_n",utc_widget_viewer_evas_notify_paused_status_of_viewer_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_orientation_of_viewer_n",utc_widget_viewer_evas_notify_orientation_of_viewer_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_pause_widget_n1",utc_widget_viewer_evas_pause_widget_n1,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_pause_widget_n2",utc_widget_viewer_evas_pause_widget_n2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_resume_widget_n",utc_widget_viewer_evas_resume_widget_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_set_option_n",utc_widget_viewer_evas_set_option_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_content_info_n",utc_widget_viewer_evas_get_content_info_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_title_string_n",utc_widget_viewer_evas_get_title_string_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_widget_id_n1",utc_widget_viewer_evas_get_widget_id_n1,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_widget_id_n2",utc_widget_viewer_evas_get_widget_id_n2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_period_n1",utc_widget_viewer_evas_get_period_n1,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_period_n2",utc_widget_viewer_evas_get_period_n2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_cancel_click_event_n",utc_widget_viewer_evas_cancel_click_event_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_preview_n",utc_widget_viewer_evas_disable_preview_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_overlay_text_n",utc_widget_viewer_evas_disable_overlay_text_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_loading_n",utc_widget_viewer_evas_disable_loading_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_feed_mouse_up_event_p",utc_widget_viewer_evas_feed_mouse_up_event_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_feed_mouse_up_event_n",utc_widget_viewer_evas_feed_mouse_up_event_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_activate_faulted_widget_n",utc_widget_viewer_evas_activate_faulted_widget_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_faulted_n",utc_widget_viewer_evas_is_faulted_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_freeze_visibility_n1",utc_widget_viewer_evas_freeze_visibility_n1,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_freeze_visibility_n2",utc_widget_viewer_evas_freeze_visibility_n2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_thaw_visibility_n",utc_widget_viewer_evas_thaw_visibility_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_visibility_frozen_n",utc_widget_viewer_evas_is_visibility_frozen_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_widget_n",utc_widget_viewer_evas_is_widget_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_set_permanent_delete_n",utc_widget_viewer_evas_set_permanent_delete_n,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_init_p",utc_widget_viewer_evas_init_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_fini_p",utc_widget_viewer_evas_fini_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_add_widget_p1",utc_widget_viewer_evas_add_widget_p1,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_add_widget_p2",utc_widget_viewer_evas_add_widget_p2,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_resumed_status_of_viewer_p",utc_widget_viewer_evas_notify_resumed_status_of_viewer_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_paused_status_of_viewer_p",utc_widget_viewer_evas_notify_paused_status_of_viewer_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_notify_orientation_of_viewer_p",utc_widget_viewer_evas_notify_orientation_of_viewer_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_pause_widget_p",utc_widget_viewer_evas_pause_widget_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_resume_widget_p",utc_widget_viewer_evas_resume_widget_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_set_option_p",utc_widget_viewer_evas_set_option_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_content_info_p",utc_widget_viewer_evas_get_content_info_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_title_string_p",utc_widget_viewer_evas_get_title_string_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_widget_id_p",utc_widget_viewer_evas_get_widget_id_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_period_p",utc_widget_viewer_evas_get_period_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_cancel_click_event_p",utc_widget_viewer_evas_cancel_click_event_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_preview_p",utc_widget_viewer_evas_disable_preview_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_overlay_text_p",utc_widget_viewer_evas_disable_overlay_text_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_disable_loading_p",utc_widget_viewer_evas_disable_loading_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_activate_faulted_widget_p",utc_widget_viewer_evas_activate_faulted_widget_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_faulted_p",utc_widget_viewer_evas_is_faulted_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_freeze_visibility_p",utc_widget_viewer_evas_freeze_visibility_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_thaw_visibility_p",utc_widget_viewer_evas_thaw_visibility_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_visibility_frozen_p",utc_widget_viewer_evas_is_visibility_frozen_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_is_widget_p",utc_widget_viewer_evas_is_widget_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_set_permanent_delete_p",utc_widget_viewer_evas_set_permanent_delete_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{"utc_widget_viewer_evas_get_widget_instance_id_p",utc_widget_viewer_evas_get_widget_instance_id_p,utc_widget_viewer_evas_startup,utc_widget_viewer_evas_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WIDGET_VIEWER_EVAS-NATIVE_H__
