//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAPI-MEDIA-VISION-NATIVE_H__
#define __TCT_CAPI-MEDIA-VISION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_capi_media_vision_common_startup(void);
extern void utc_capi_media_vision_common_cleanup(void);
extern void utc_capi_media_vision_barcode_startup(void);
extern void utc_capi_media_vision_barcode_cleanup(void);
extern void utc_capi_media_vision_face_startup(void);
extern void utc_capi_media_vision_face_cleanup(void);
extern void utc_capi_media_vision_image_startup(void);
extern void utc_capi_media_vision_image_cleanup(void);
extern void utc_capi_media_vision_surveillance_startup(void);
extern void utc_capi_media_vision_surveillance_cleanup(void);
extern void utc_capi_media_vision_surveillance_cb1_startup(void);
extern void utc_capi_media_vision_surveillance_cb2_startup(void);
extern void utc_capi_media_vision_surveillance_cb3_startup(void);
extern void utc_capi_media_vision_inference_startup1(void);
extern void utc_capi_media_vision_inference_cleanup1(void);
extern void utc_capi_media_vision_inference_startup2(void);
extern void utc_capi_media_vision_inference_cleanup2(void);
extern void utc_capi_media_vision_inference_pose_landmark_detect_cb1_startup(void);
extern void utc_capi_media_vision_inference_pose_landmark_detect_cb2_startup(void);
extern void utc_capi_media_vision_inference_pose_landmark_detect_cb3_startup(void);
extern void utc_capi_media_vision_inference_pose_landmark_detect_cb4_startup(void);
extern void utc_capi_media_vision_inference_pose_landmark_detect_cb5_startup(void);

extern int utc_mediavision_mv_create_source_p(void);
extern int utc_mediavision_mv_create_source_n(void);
extern int utc_mediavision_mv_destroy_source_p(void);
extern int utc_mediavision_mv_destroy_source_n(void);
extern int utc_mediavision_mv_source_fill_by_media_packet_p(void);
extern int utc_mediavision_mv_source_fill_by_media_packet_n(void);
extern int utc_mediavision_mv_source_fill_by_buffer_p(void);
extern int utc_mediavision_mv_source_fill_by_buffer_n(void);
extern int utc_mediavision_mv_source_clear_p(void);
extern int utc_mediavision_mv_source_clear_n(void);
extern int utc_mediavision_mv_source_get_buffer_p(void);
extern int utc_mediavision_mv_source_get_buffer_n(void);
extern int utc_mediavision_mv_source_get_height_p(void);
extern int utc_mediavision_mv_source_get_height_n(void);
extern int utc_mediavision_mv_source_get_width_p(void);
extern int utc_mediavision_mv_source_get_width_n(void);
extern int utc_mediavision_mv_source_get_colorspace_p(void);
extern int utc_mediavision_mv_source_get_colorspace_n(void);
extern int utc_mediavision_mv_create_engine_config_p(void);
extern int utc_mediavision_mv_create_engine_config_n(void);
extern int utc_mediavision_mv_destroy_engine_config_p(void);
extern int utc_mediavision_mv_destroy_engine_config_n(void);
extern int utc_mediavision_mv_engine_config_set_double_attribute_p(void);
extern int utc_mediavision_mv_engine_config_set_double_attribute_n(void);
extern int utc_mediavision_mv_engine_config_set_int_attribute_p(void);
extern int utc_mediavision_mv_engine_config_set_int_attribute_n(void);
extern int utc_mediavision_mv_engine_config_set_bool_attribute_p(void);
extern int utc_mediavision_mv_engine_config_set_bool_attribute_n(void);
extern int utc_mediavision_mv_engine_config_set_string_attribute_p(void);
extern int utc_mediavision_mv_engine_config_set_string_attribute_n(void);
extern int utc_mediavision_mv_engine_config_get_double_attribute_p(void);
extern int utc_mediavision_mv_engine_config_get_double_attribute_n(void);
extern int utc_mediavision_mv_engine_config_get_int_attribute_p(void);
extern int utc_mediavision_mv_engine_config_get_int_attribute_n(void);
extern int utc_mediavision_mv_engine_config_get_bool_attribute_p(void);
extern int utc_mediavision_mv_engine_config_get_bool_attribute_n(void);
extern int utc_mediavision_mv_engine_config_get_string_attribute_p(void);
extern int utc_mediavision_mv_engine_config_get_string_attribute_n(void);
extern int utc_mediavision_mv_engine_config_foreach_supported_attribute_p(void);
extern int utc_mediavision_mv_engine_config_foreach_supported_attribute_n(void);
extern int utc_mediavision_mv_barcode_generate_image_p(void);
extern int utc_mediavision_mv_barcode_generate_source_p(void);
extern int utc_mediavision_mv_barcode_detect_p1(void);
extern int utc_mediavision_mv_barcode_detect_p2(void);
extern int utc_mediavision_mv_barcode_detect_p3(void);
extern int utc_mediavision_mv_barcode_generate_image_n1(void);
extern int utc_mediavision_mv_barcode_generate_image_n2(void);
extern int utc_mediavision_mv_barcode_generate_image_n3(void);
extern int utc_mediavision_mv_barcode_generate_image_n4(void);
extern int utc_mediavision_mv_barcode_generate_source_n1(void);
extern int utc_mediavision_mv_barcode_generate_source_n2(void);
extern int utc_mediavision_mv_barcode_detect_n1(void);
extern int utc_mediavision_mv_barcode_detect_n2(void);
extern int utc_mediavision_mv_barcode_detect_n3(void);
extern int utc_mediavision_mv_barcode_detect_n4(void);
extern int utc_mediavision_mv_barcode_detect_n5(void);
extern int utc_mediavision_mv_face_tracking_model_create_p(void);
extern int utc_mediavision_mv_face_tracking_model_create_n(void);
extern int utc_mediavision_mv_face_tracking_model_destroy_p(void);
extern int utc_mediavision_mv_face_tracking_model_destroy_n(void);
extern int utc_mediavision_mv_face_tracking_model_prepare_p(void);
extern int utc_mediavision_mv_face_tracking_model_prepare_n(void);
extern int utc_mediavision_mv_face_tracking_model_clone_p(void);
extern int utc_mediavision_mv_face_tracking_model_clone_n(void);
extern int utc_mediavision_mv_face_tracking_model_save_p(void);
extern int utc_mediavision_mv_face_tracking_model_save_n(void);
extern int utc_mediavision_mv_face_tracking_model_load_p(void);
extern int utc_mediavision_mv_face_tracking_model_load_n(void);
extern int utc_mediavision_mv_face_track_p(void);
extern int utc_mediavision_mv_face_track_n(void);
extern int utc_mediavision_mv_face_recognize_p(void);
extern int utc_mediavision_mv_face_recognize_n(void);
extern int utc_mediavision_mv_face_eye_condition_recognize_p(void);
extern int utc_mediavision_mv_face_eye_condition_recognize_n(void);
extern int utc_mediavision_mv_face_facial_expression_recognize_p(void);
extern int utc_mediavision_mv_face_facial_expression_recognize_n(void);
extern int utc_mediavision_mv_face_recognition_model_create_p(void);
extern int utc_mediavision_mv_face_recognition_model_create_n(void);
extern int utc_mediavision_mv_face_recognition_model_destroy_p(void);
extern int utc_mediavision_mv_face_recognition_model_destroy_n(void);
extern int utc_mediavision_mv_face_recognition_model_clone_p(void);
extern int utc_mediavision_mv_face_recognition_model_clone_n(void);
extern int utc_mediavision_mv_face_recognition_model_save_p(void);
extern int utc_mediavision_mv_face_recognition_model_save_n(void);
extern int utc_mediavision_mv_face_recognition_model_load_p(void);
extern int utc_mediavision_mv_face_recognition_model_load_n(void);
extern int utc_mediavision_mv_face_recognition_model_add_p(void);
extern int utc_mediavision_mv_face_recognition_model_add_n(void);
extern int utc_mediavision_mv_face_recognition_model_reset_p(void);
extern int utc_mediavision_mv_face_recognition_model_reset_n(void);
extern int utc_mediavision_mv_face_recognition_model_learn_p(void);
extern int utc_mediavision_mv_face_recognition_model_learn_n(void);
extern int utc_mediavision_mv_face_recognition_model_query_labels_p(void);
extern int utc_mediavision_mv_face_recognition_model_query_labels_n(void);
extern int utc_mediavision_mv_face_detect_p(void);
extern int utc_mediavision_mv_face_detect_n(void);
extern int utc_mediavision_mv_image_tracking_model_create_p(void);
extern int utc_mediavision_mv_image_tracking_model_create_n(void);
extern int utc_mediavision_mv_image_tracking_model_destroy_p(void);
extern int utc_mediavision_mv_image_tracking_model_destroy_n(void);
extern int utc_mediavision_mv_image_tracking_model_clone_p(void);
extern int utc_mediavision_mv_image_tracking_model_clone_n(void);
extern int utc_mediavision_mv_image_tracking_model_save_p(void);
extern int utc_mediavision_mv_image_tracking_model_save_n1(void);
extern int utc_mediavision_mv_image_tracking_model_save_n2(void);
extern int utc_mediavision_mv_image_tracking_model_load_p(void);
extern int utc_mediavision_mv_image_tracking_model_load_n1(void);
extern int utc_mediavision_mv_image_tracking_model_load_n2(void);
extern int utc_mediavision_mv_image_recognize_p(void);
extern int utc_mediavision_mv_image_recognize_n(void);
extern int utc_mediavision_mv_image_object_create_p(void);
extern int utc_mediavision_mv_image_object_create_n(void);
extern int utc_mediavision_mv_image_object_destroy_p(void);
extern int utc_mediavision_mv_image_object_destroy_n(void);
extern int utc_mediavision_mv_image_object_fill_p(void);
extern int utc_mediavision_mv_image_object_fill_n(void);
extern int utc_mediavision_mv_image_object_save_p(void);
extern int utc_mediavision_mv_image_object_save_n1(void);
extern int utc_mediavision_mv_image_object_save_n2(void);
extern int utc_mediavision_mv_image_object_load_p(void);
extern int utc_mediavision_mv_image_object_load_n1(void);
extern int utc_mediavision_mv_image_object_load_n2(void);
extern int utc_mediavision_mv_image_object_get_recognition_rate_p(void);
extern int utc_mediavision_mv_image_object_get_recognition_rate_n(void);
extern int utc_mediavision_mv_image_object_get_label_p(void);
extern int utc_mediavision_mv_image_object_get_label_n(void);
extern int utc_mediavision_mv_image_object_set_label_p(void);
extern int utc_mediavision_mv_image_object_set_label_n(void);
extern int utc_mediavision_mv_image_object_clone_p(void);
extern int utc_mediavision_mv_image_object_clone_n(void);
extern int utc_mediavision_mv_image_track_p(void);
extern int utc_mediavision_mv_image_track_n(void);
extern int utc_mediavision_mv_image_tracking_model_refresh_p(void);
extern int utc_mediavision_mv_image_tracking_model_refresh_n(void);
extern int utc_mediavision_mv_image_tracking_model_set_target_p(void);
extern int utc_mediavision_mv_image_tracking_model_set_target_n(void);
extern int utc_mediavision_mv_surveillance_event_trigger_create_p(void);
extern int utc_mediavision_mv_surveillance_event_trigger_create_n(void);
extern int utc_mediavision_mv_surveillance_event_trigger_destroy_p(void);
extern int utc_mediavision_mv_surveillance_event_trigger_destroy_n(void);
extern int utc_mediavision_mv_surveillance_subscribe_event_trigger_p(void);
extern int utc_mediavision_mv_surveillance_subscribe_event_trigger_n(void);
extern int utc_mediavision_mv_surveillance_unsubscribe_event_trigger_p(void);
extern int utc_mediavision_mv_surveillance_unsubscribe_event_trigger_n(void);
extern int utc_mediavision_mv_surveillance_push_source_p(void);
extern int utc_mediavision_mv_surveillance_push_source_n(void);
extern int utc_mediavision_mv_surveillance_foreach_supported_event_type_p(void);
extern int utc_mediavision_mv_surveillance_foreach_supported_event_type_n(void);
extern int utc_mediavision_mv_surveillance_foreach_event_result_name_p(void);
extern int utc_mediavision_mv_surveillance_foreach_event_result_name_n(void);
extern int utc_mediavision_mv_surveillance_get_event_trigger_type_p(void);
extern int utc_mediavision_mv_surveillance_get_event_trigger_type_n(void);
extern int utc_mediavision_mv_surveillance_set_event_trigger_roi_p1(void);
extern int utc_mediavision_mv_surveillance_set_event_trigger_roi_p2(void);
extern int utc_mediavision_mv_surveillance_set_event_trigger_roi_n1(void);
extern int utc_mediavision_mv_surveillance_set_event_trigger_roi_n2(void);
extern int utc_mediavision_mv_surveillance_get_event_trigger_roi_p(void);
extern int utc_mediavision_mv_surveillance_get_event_trigger_roi_n(void);
extern int utc_mediavision_mv_surveillance_get_result_value_n(void);
extern int utc_mediavision_mv_surveillance_get_result_value_p1(void);
extern int utc_mediavision_mv_surveillance_get_result_value_p2(void);
extern int utc_mediavision_mv_surveillance_get_result_value_p3(void);
extern int utc_mediavision_mv_inference_foreach_supported_engine(void);
extern int utc_mediavision_mv_inference_create_p(void);
extern int utc_mediavision_mv_inference_create_n(void);
extern int utc_mediavision_mv_inference_destroy_p(void);
extern int utc_mediavision_mv_inference_destroy_n(void);
extern int utc_mediavision_mv_inference_configure_p(void);
extern int utc_mediavision_mv_inference_configure_n1(void);
extern int utc_mediavision_mv_inference_configure_n2(void);
extern int utc_mediavision_mv_inference_prepare_p(void);
extern int utc_mediavision_mv_inference_prepare_n1(void);
extern int utc_mediavision_mv_inference_image_classify_p(void);
extern int utc_mediavision_mv_inference_image_classify_n1(void);
extern int utc_mediavision_mv_inference_image_classify_n2(void);
extern int utc_mediavision_mv_inference_object_detect_p(void);
extern int utc_mediavision_mv_inference_object_detect_n1(void);
extern int utc_mediavision_mv_inference_object_detect_n2(void);
extern int utc_mediavision_mv_inference_face_detect_p(void);
extern int utc_mediavision_mv_inference_face_detect_n1(void);
extern int utc_mediavision_mv_inference_face_detect_n2(void);
extern int utc_mediavision_mv_inference_facial_landmark_detect_p(void);
extern int utc_mediavision_mv_inference_facial_landmark_detect_n1(void);
extern int utc_mediavision_mv_inference_facial_landmark_detect_n2(void);
extern int utc_mediavision_mv_inference_pose_landmark_detect_p(void);
extern int utc_mediavision_mv_inference_pose_landmark_detect_n1(void);
extern int utc_mediavision_mv_inference_pose_landmark_detect_n2(void);
extern int utc_mediavision_mv_inference_get_number_of_poses_p(void);
extern int utc_mediavision_mv_inference_get_number_of_poses_n(void);
extern int utc_mediavision_mv_inference_get_number_of_landmarks_p(void);
extern int utc_mediavision_mv_inference_get_number_of_landmarks_n(void);
extern int utc_mediavision_mv_inference_get_label_p(void);
extern int utc_mediavision_mv_inference_get_label_n(void);
extern int utc_mediavision_mv_inference_get_landmark_p(void);
extern int utc_mediavision_mv_inference_get_landmark_n(void);
extern int utc_mediavision_mv_pose_create_p(void);
extern int utc_mediavision_mv_pose_create_n(void);
extern int utc_mediavision_mv_pose_destroy_p(void);
extern int utc_mediavision_mv_pose_destroy_n(void);
extern int utc_mediavision_mv_pose_set_from_file_p(void);
extern int utc_mediavision_mv_pose_set_from_file_n1(void);
extern int utc_mediavision_mv_pose_set_from_file_n2(void);
extern int utc_mediavision_mv_pose_compare_p(void);
extern int utc_mediavision_mv_pose_compare_n(void);

testcase tc_array[] = {
	{"utc_mediavision_mv_create_source_p",utc_mediavision_mv_create_source_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_create_source_n",utc_mediavision_mv_create_source_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_destroy_source_p",utc_mediavision_mv_destroy_source_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_destroy_source_n",utc_mediavision_mv_destroy_source_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_fill_by_media_packet_p",utc_mediavision_mv_source_fill_by_media_packet_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_fill_by_media_packet_n",utc_mediavision_mv_source_fill_by_media_packet_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_fill_by_buffer_p",utc_mediavision_mv_source_fill_by_buffer_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_fill_by_buffer_n",utc_mediavision_mv_source_fill_by_buffer_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_clear_p",utc_mediavision_mv_source_clear_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_clear_n",utc_mediavision_mv_source_clear_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_buffer_p",utc_mediavision_mv_source_get_buffer_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_buffer_n",utc_mediavision_mv_source_get_buffer_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_height_p",utc_mediavision_mv_source_get_height_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_height_n",utc_mediavision_mv_source_get_height_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_width_p",utc_mediavision_mv_source_get_width_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_width_n",utc_mediavision_mv_source_get_width_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_colorspace_p",utc_mediavision_mv_source_get_colorspace_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_source_get_colorspace_n",utc_mediavision_mv_source_get_colorspace_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_create_engine_config_p",utc_mediavision_mv_create_engine_config_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_create_engine_config_n",utc_mediavision_mv_create_engine_config_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_destroy_engine_config_p",utc_mediavision_mv_destroy_engine_config_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_destroy_engine_config_n",utc_mediavision_mv_destroy_engine_config_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_double_attribute_p",utc_mediavision_mv_engine_config_set_double_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_double_attribute_n",utc_mediavision_mv_engine_config_set_double_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_int_attribute_p",utc_mediavision_mv_engine_config_set_int_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_int_attribute_n",utc_mediavision_mv_engine_config_set_int_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_bool_attribute_p",utc_mediavision_mv_engine_config_set_bool_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_bool_attribute_n",utc_mediavision_mv_engine_config_set_bool_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_string_attribute_p",utc_mediavision_mv_engine_config_set_string_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_set_string_attribute_n",utc_mediavision_mv_engine_config_set_string_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_double_attribute_p",utc_mediavision_mv_engine_config_get_double_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_double_attribute_n",utc_mediavision_mv_engine_config_get_double_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_int_attribute_p",utc_mediavision_mv_engine_config_get_int_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_int_attribute_n",utc_mediavision_mv_engine_config_get_int_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_bool_attribute_p",utc_mediavision_mv_engine_config_get_bool_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_bool_attribute_n",utc_mediavision_mv_engine_config_get_bool_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_string_attribute_p",utc_mediavision_mv_engine_config_get_string_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_get_string_attribute_n",utc_mediavision_mv_engine_config_get_string_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_foreach_supported_attribute_p",utc_mediavision_mv_engine_config_foreach_supported_attribute_p,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_engine_config_foreach_supported_attribute_n",utc_mediavision_mv_engine_config_foreach_supported_attribute_n,utc_capi_media_vision_common_startup,utc_capi_media_vision_common_cleanup},
	{"utc_mediavision_mv_barcode_generate_image_p",utc_mediavision_mv_barcode_generate_image_p,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_source_p",utc_mediavision_mv_barcode_generate_source_p,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_p1",utc_mediavision_mv_barcode_detect_p1,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_p2",utc_mediavision_mv_barcode_detect_p2,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_p3",utc_mediavision_mv_barcode_detect_p3,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_image_n1",utc_mediavision_mv_barcode_generate_image_n1,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_image_n2",utc_mediavision_mv_barcode_generate_image_n2,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_image_n3",utc_mediavision_mv_barcode_generate_image_n3,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_image_n4",utc_mediavision_mv_barcode_generate_image_n4,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_source_n1",utc_mediavision_mv_barcode_generate_source_n1,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_generate_source_n2",utc_mediavision_mv_barcode_generate_source_n2,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_n1",utc_mediavision_mv_barcode_detect_n1,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_n2",utc_mediavision_mv_barcode_detect_n2,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_n3",utc_mediavision_mv_barcode_detect_n3,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_n4",utc_mediavision_mv_barcode_detect_n4,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_barcode_detect_n5",utc_mediavision_mv_barcode_detect_n5,utc_capi_media_vision_barcode_startup,utc_capi_media_vision_barcode_cleanup},
	{"utc_mediavision_mv_face_tracking_model_create_p",utc_mediavision_mv_face_tracking_model_create_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_create_n",utc_mediavision_mv_face_tracking_model_create_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_destroy_p",utc_mediavision_mv_face_tracking_model_destroy_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_destroy_n",utc_mediavision_mv_face_tracking_model_destroy_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_prepare_p",utc_mediavision_mv_face_tracking_model_prepare_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_prepare_n",utc_mediavision_mv_face_tracking_model_prepare_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_clone_p",utc_mediavision_mv_face_tracking_model_clone_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_clone_n",utc_mediavision_mv_face_tracking_model_clone_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_save_p",utc_mediavision_mv_face_tracking_model_save_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_save_n",utc_mediavision_mv_face_tracking_model_save_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_load_p",utc_mediavision_mv_face_tracking_model_load_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_tracking_model_load_n",utc_mediavision_mv_face_tracking_model_load_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_track_p",utc_mediavision_mv_face_track_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_track_n",utc_mediavision_mv_face_track_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognize_p",utc_mediavision_mv_face_recognize_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognize_n",utc_mediavision_mv_face_recognize_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_eye_condition_recognize_p",utc_mediavision_mv_face_eye_condition_recognize_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_eye_condition_recognize_n",utc_mediavision_mv_face_eye_condition_recognize_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_facial_expression_recognize_p",utc_mediavision_mv_face_facial_expression_recognize_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_facial_expression_recognize_n",utc_mediavision_mv_face_facial_expression_recognize_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_create_p",utc_mediavision_mv_face_recognition_model_create_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_create_n",utc_mediavision_mv_face_recognition_model_create_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_destroy_p",utc_mediavision_mv_face_recognition_model_destroy_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_destroy_n",utc_mediavision_mv_face_recognition_model_destroy_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_clone_p",utc_mediavision_mv_face_recognition_model_clone_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_clone_n",utc_mediavision_mv_face_recognition_model_clone_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_save_p",utc_mediavision_mv_face_recognition_model_save_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_save_n",utc_mediavision_mv_face_recognition_model_save_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_load_p",utc_mediavision_mv_face_recognition_model_load_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_load_n",utc_mediavision_mv_face_recognition_model_load_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_add_p",utc_mediavision_mv_face_recognition_model_add_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_add_n",utc_mediavision_mv_face_recognition_model_add_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_reset_p",utc_mediavision_mv_face_recognition_model_reset_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_reset_n",utc_mediavision_mv_face_recognition_model_reset_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_learn_p",utc_mediavision_mv_face_recognition_model_learn_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_learn_n",utc_mediavision_mv_face_recognition_model_learn_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_query_labels_p",utc_mediavision_mv_face_recognition_model_query_labels_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_recognition_model_query_labels_n",utc_mediavision_mv_face_recognition_model_query_labels_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_detect_p",utc_mediavision_mv_face_detect_p,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_face_detect_n",utc_mediavision_mv_face_detect_n,utc_capi_media_vision_face_startup,utc_capi_media_vision_face_cleanup},
	{"utc_mediavision_mv_image_tracking_model_create_p",utc_mediavision_mv_image_tracking_model_create_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_create_n",utc_mediavision_mv_image_tracking_model_create_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_destroy_p",utc_mediavision_mv_image_tracking_model_destroy_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_destroy_n",utc_mediavision_mv_image_tracking_model_destroy_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_clone_p",utc_mediavision_mv_image_tracking_model_clone_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_clone_n",utc_mediavision_mv_image_tracking_model_clone_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_save_p",utc_mediavision_mv_image_tracking_model_save_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_save_n1",utc_mediavision_mv_image_tracking_model_save_n1,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_save_n2",utc_mediavision_mv_image_tracking_model_save_n2,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_load_p",utc_mediavision_mv_image_tracking_model_load_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_load_n1",utc_mediavision_mv_image_tracking_model_load_n1,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_load_n2",utc_mediavision_mv_image_tracking_model_load_n2,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_recognize_p",utc_mediavision_mv_image_recognize_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_recognize_n",utc_mediavision_mv_image_recognize_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_create_p",utc_mediavision_mv_image_object_create_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_create_n",utc_mediavision_mv_image_object_create_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_destroy_p",utc_mediavision_mv_image_object_destroy_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_destroy_n",utc_mediavision_mv_image_object_destroy_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_fill_p",utc_mediavision_mv_image_object_fill_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_fill_n",utc_mediavision_mv_image_object_fill_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_save_p",utc_mediavision_mv_image_object_save_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_save_n1",utc_mediavision_mv_image_object_save_n1,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_save_n2",utc_mediavision_mv_image_object_save_n2,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_load_p",utc_mediavision_mv_image_object_load_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_load_n1",utc_mediavision_mv_image_object_load_n1,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_load_n2",utc_mediavision_mv_image_object_load_n2,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_get_recognition_rate_p",utc_mediavision_mv_image_object_get_recognition_rate_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_get_recognition_rate_n",utc_mediavision_mv_image_object_get_recognition_rate_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_get_label_p",utc_mediavision_mv_image_object_get_label_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_get_label_n",utc_mediavision_mv_image_object_get_label_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_set_label_p",utc_mediavision_mv_image_object_set_label_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_set_label_n",utc_mediavision_mv_image_object_set_label_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_clone_p",utc_mediavision_mv_image_object_clone_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_object_clone_n",utc_mediavision_mv_image_object_clone_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_track_p",utc_mediavision_mv_image_track_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_track_n",utc_mediavision_mv_image_track_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_refresh_p",utc_mediavision_mv_image_tracking_model_refresh_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_refresh_n",utc_mediavision_mv_image_tracking_model_refresh_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_set_target_p",utc_mediavision_mv_image_tracking_model_set_target_p,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_image_tracking_model_set_target_n",utc_mediavision_mv_image_tracking_model_set_target_n,utc_capi_media_vision_image_startup,utc_capi_media_vision_image_cleanup},
	{"utc_mediavision_mv_surveillance_event_trigger_create_p",utc_mediavision_mv_surveillance_event_trigger_create_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_event_trigger_create_n",utc_mediavision_mv_surveillance_event_trigger_create_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_event_trigger_destroy_p",utc_mediavision_mv_surveillance_event_trigger_destroy_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_event_trigger_destroy_n",utc_mediavision_mv_surveillance_event_trigger_destroy_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_subscribe_event_trigger_p",utc_mediavision_mv_surveillance_subscribe_event_trigger_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_subscribe_event_trigger_n",utc_mediavision_mv_surveillance_subscribe_event_trigger_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_unsubscribe_event_trigger_p",utc_mediavision_mv_surveillance_unsubscribe_event_trigger_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_unsubscribe_event_trigger_n",utc_mediavision_mv_surveillance_unsubscribe_event_trigger_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_push_source_p",utc_mediavision_mv_surveillance_push_source_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_push_source_n",utc_mediavision_mv_surveillance_push_source_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_foreach_supported_event_type_p",utc_mediavision_mv_surveillance_foreach_supported_event_type_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_foreach_supported_event_type_n",utc_mediavision_mv_surveillance_foreach_supported_event_type_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_foreach_event_result_name_p",utc_mediavision_mv_surveillance_foreach_event_result_name_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_foreach_event_result_name_n",utc_mediavision_mv_surveillance_foreach_event_result_name_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_event_trigger_type_p",utc_mediavision_mv_surveillance_get_event_trigger_type_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_event_trigger_type_n",utc_mediavision_mv_surveillance_get_event_trigger_type_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_set_event_trigger_roi_p1",utc_mediavision_mv_surveillance_set_event_trigger_roi_p1,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_set_event_trigger_roi_p2",utc_mediavision_mv_surveillance_set_event_trigger_roi_p2,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_set_event_trigger_roi_n1",utc_mediavision_mv_surveillance_set_event_trigger_roi_n1,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_set_event_trigger_roi_n2",utc_mediavision_mv_surveillance_set_event_trigger_roi_n2,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_event_trigger_roi_p",utc_mediavision_mv_surveillance_get_event_trigger_roi_p,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_event_trigger_roi_n",utc_mediavision_mv_surveillance_get_event_trigger_roi_n,utc_capi_media_vision_surveillance_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_result_value_n",utc_mediavision_mv_surveillance_get_result_value_n,utc_capi_media_vision_surveillance_cb1_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_result_value_p1",utc_mediavision_mv_surveillance_get_result_value_p1,utc_capi_media_vision_surveillance_cb1_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_result_value_p2",utc_mediavision_mv_surveillance_get_result_value_p2,utc_capi_media_vision_surveillance_cb2_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_surveillance_get_result_value_p3",utc_mediavision_mv_surveillance_get_result_value_p3,utc_capi_media_vision_surveillance_cb3_startup,utc_capi_media_vision_surveillance_cleanup},
	{"utc_mediavision_mv_inference_foreach_supported_engine",utc_mediavision_mv_inference_foreach_supported_engine,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_create_p",utc_mediavision_mv_inference_create_p,utc_capi_media_vision_inference_startup1,utc_capi_media_vision_inference_cleanup1},
	{"utc_mediavision_mv_inference_create_n",utc_mediavision_mv_inference_create_n,utc_capi_media_vision_inference_startup1,utc_capi_media_vision_inference_cleanup1},
	{"utc_mediavision_mv_inference_destroy_p",utc_mediavision_mv_inference_destroy_p,utc_capi_media_vision_inference_startup1,utc_capi_media_vision_inference_cleanup1},
	{"utc_mediavision_mv_inference_destroy_n",utc_mediavision_mv_inference_destroy_n,utc_capi_media_vision_inference_startup1,utc_capi_media_vision_inference_cleanup1},
	{"utc_mediavision_mv_inference_configure_p",utc_mediavision_mv_inference_configure_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_configure_n1",utc_mediavision_mv_inference_configure_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_configure_n2",utc_mediavision_mv_inference_configure_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_prepare_p",utc_mediavision_mv_inference_prepare_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_prepare_n1",utc_mediavision_mv_inference_prepare_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_image_classify_p",utc_mediavision_mv_inference_image_classify_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_image_classify_n1",utc_mediavision_mv_inference_image_classify_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_image_classify_n2",utc_mediavision_mv_inference_image_classify_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_object_detect_p",utc_mediavision_mv_inference_object_detect_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_object_detect_n1",utc_mediavision_mv_inference_object_detect_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_object_detect_n2",utc_mediavision_mv_inference_object_detect_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_face_detect_p",utc_mediavision_mv_inference_face_detect_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_face_detect_n1",utc_mediavision_mv_inference_face_detect_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_face_detect_n2",utc_mediavision_mv_inference_face_detect_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_facial_landmark_detect_p",utc_mediavision_mv_inference_facial_landmark_detect_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_facial_landmark_detect_n1",utc_mediavision_mv_inference_facial_landmark_detect_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_facial_landmark_detect_n2",utc_mediavision_mv_inference_facial_landmark_detect_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_pose_landmark_detect_p", utc_mediavision_mv_inference_pose_landmark_detect_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_pose_landmark_detect_n1", utc_mediavision_mv_inference_pose_landmark_detect_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_pose_landmark_detect_n2", utc_mediavision_mv_inference_pose_landmark_detect_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_number_of_poses_p", utc_mediavision_mv_inference_get_number_of_poses_p,utc_capi_media_vision_inference_pose_landmark_detect_cb1_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_number_of_poses_n", utc_mediavision_mv_inference_get_number_of_poses_n,utc_capi_media_vision_inference_pose_landmark_detect_cb1_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_label_p", utc_mediavision_mv_inference_get_label_p,utc_capi_media_vision_inference_pose_landmark_detect_cb5_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_label_n", utc_mediavision_mv_inference_get_label_n,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_number_of_landmarks_p", utc_mediavision_mv_inference_get_number_of_landmarks_p,utc_capi_media_vision_inference_pose_landmark_detect_cb2_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_number_of_landmarks_n", utc_mediavision_mv_inference_get_number_of_landmarks_n,utc_capi_media_vision_inference_pose_landmark_detect_cb2_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_landmark_p", utc_mediavision_mv_inference_get_landmark_p,utc_capi_media_vision_inference_pose_landmark_detect_cb3_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_inference_get_landmark_n", utc_mediavision_mv_inference_get_landmark_n,utc_capi_media_vision_inference_pose_landmark_detect_cb3_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_create_p", utc_mediavision_mv_pose_create_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_create_n", utc_mediavision_mv_pose_create_n,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_destroy_p", utc_mediavision_mv_pose_destroy_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_destroy_n", utc_mediavision_mv_pose_destroy_n,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_set_from_file_p", utc_mediavision_mv_pose_set_from_file_p,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_set_from_file_n1", utc_mediavision_mv_pose_set_from_file_n1,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_set_from_file_n2", utc_mediavision_mv_pose_set_from_file_n2,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_compare_p", utc_mediavision_mv_pose_compare_p,utc_capi_media_vision_inference_pose_landmark_detect_cb4_startup,utc_capi_media_vision_inference_cleanup2},
	{"utc_mediavision_mv_pose_compare_n", utc_mediavision_mv_pose_compare_n,utc_capi_media_vision_inference_startup2,utc_capi_media_vision_inference_cleanup2},
	{NULL, NULL}
};


#endif // __TCT_CAPI-MEDIA-VISION-NATIVE_H__
