//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_SOUND-MANAGER-NATIVE_H__
#define __TCT_SOUND-MANAGER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_sound_manager_device_startup(void);
extern void ITs_sound_manager_device_cleanup(void);
extern void ITs_sound_manager_stream_startup(void);
extern void ITs_sound_manager_stream_cleanup(void);
extern void ITs_sound_manager_volume_startup(void);
extern void ITs_sound_manager_volume_cleanup(void);

extern int ITc_sound_manager_get_next_device_free_device_p(void);
extern int ITc_sound_manager_get_prev_device_p(void);
extern int ITc_sound_manager_get_device_type_p(void);
extern int ITc_sound_manager_get_device_io_direction_p(void);
extern int ITc_sound_manager_get_device_id_p(void);
extern int ITc_sound_manager_get_device_name_p(void);
extern int ITc_sound_manager_get_device_state_p(void);
extern int ITc_sound_manager_get_device_list_p(void);
extern int ITc_sound_manager_get_current_media_playback_device_type_p(void);
extern int ITc_sound_manager_add_remove_device_connection_changed_cb_p(void);
extern int ITc_sound_manager_add_remove_device_state_changed_cb_p(void);
extern int ITc_sound_manager_create_destroy_stream_information_p(void);
extern int ITc_sound_manager_add_remove_device_for_stream_routing_p(void);
extern int ITc_sound_manager_remove_all_devices_for_stream_routing_p(void);
extern int ITc_sound_manager_apply_stream_routing_p(void);
extern int ITc_sound_manager_acquire_release_focus_p(void);
extern int ITc_sound_manager_get_focus_state_p(void);
extern int ITc_sound_manager_add_remove_focus_state_watch_cb_p(void);
extern int ITc_sound_manager_set_get_focus_reacquisition_p(void);
extern int ITc_sound_manager_get_sound_type_p(void);
extern int ITc_sound_manager_get_current_playback_recording_focus_p(void);
extern int ITc_sound_manager_focus_get_requesting_requested_behavior_get_changed_focus_state_p(void);
extern int ITc_sound_manager_is_stream_on_device_p(void);
extern int ITc_sound_manager_get_max_volume_p(void);
extern int ITc_sound_manager_set_get_volume_p(void);
extern int ITc_sound_manager_get_current_sound_type_p(void);
extern int ITc_sound_manager_add_remove_volume_changed_cb_p(void);
extern int ITc_sound_manager_acquire_release_focus_all_p(void);
extern int ITc_sound_manager_deliver_focus_p(void);
extern int ITc_sound_manager_activate_deactivate_ducking_p(void);
extern int ITc_sound_manager_is_ducked_p(void);
extern int ITc_sound_manager_create_destroy_stream_ducking_p(void);
extern int ITc_sound_manager_set_get_stream_prefered_device_p(void);
testcase tc_array[] = {
	{"ITc_sound_manager_get_next_device_free_device_p",ITc_sound_manager_get_next_device_free_device_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_prev_device_p",ITc_sound_manager_get_prev_device_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_type_p",ITc_sound_manager_get_device_type_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_io_direction_p",ITc_sound_manager_get_device_io_direction_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_id_p",ITc_sound_manager_get_device_id_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_name_p",ITc_sound_manager_get_device_name_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_state_p",ITc_sound_manager_get_device_state_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_device_list_p",ITc_sound_manager_get_device_list_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_get_current_media_playback_device_type_p",ITc_sound_manager_get_current_media_playback_device_type_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_add_remove_device_connection_changed_cb_p",ITc_sound_manager_add_remove_device_connection_changed_cb_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_add_remove_device_state_changed_cb_p",ITc_sound_manager_add_remove_device_state_changed_cb_p,ITs_sound_manager_device_startup,ITs_sound_manager_device_cleanup},
	{"ITc_sound_manager_create_destroy_stream_information_p",ITc_sound_manager_create_destroy_stream_information_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_add_remove_device_for_stream_routing_p",ITc_sound_manager_add_remove_device_for_stream_routing_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_remove_all_devices_for_stream_routing_p",ITc_sound_manager_remove_all_devices_for_stream_routing_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_apply_stream_routing_p",ITc_sound_manager_apply_stream_routing_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_acquire_release_focus_p",ITc_sound_manager_acquire_release_focus_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_get_focus_state_p",ITc_sound_manager_get_focus_state_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_add_remove_focus_state_watch_cb_p",ITc_sound_manager_add_remove_focus_state_watch_cb_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_set_get_focus_reacquisition_p",ITc_sound_manager_set_get_focus_reacquisition_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_get_sound_type_p",ITc_sound_manager_get_sound_type_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_get_current_playback_recording_focus_p",ITc_sound_manager_get_current_playback_recording_focus_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_focus_get_requesting_requested_behavior_get_changed_focus_state_p",ITc_sound_manager_focus_get_requesting_requested_behavior_get_changed_focus_state_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_is_stream_on_device_p",ITc_sound_manager_is_stream_on_device_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_get_max_volume_p",ITc_sound_manager_get_max_volume_p,ITs_sound_manager_volume_startup,ITs_sound_manager_volume_cleanup},
	{"ITc_sound_manager_set_get_volume_p",ITc_sound_manager_set_get_volume_p,ITs_sound_manager_volume_startup,ITs_sound_manager_volume_cleanup},
	{"ITc_sound_manager_get_current_sound_type_p",ITc_sound_manager_get_current_sound_type_p,ITs_sound_manager_volume_startup,ITs_sound_manager_volume_cleanup},
	{"ITc_sound_manager_add_remove_volume_changed_cb_p",ITc_sound_manager_add_remove_volume_changed_cb_p,ITs_sound_manager_volume_startup,ITs_sound_manager_volume_cleanup},
	{"ITc_sound_manager_acquire_release_focus_all_p", ITc_sound_manager_acquire_release_focus_all_p, ITs_sound_manager_stream_startup, ITs_sound_manager_stream_cleanup},
	{"ITc_sound_manager_deliver_focus_p", ITc_sound_manager_deliver_focus_p, ITs_sound_manager_stream_startup, ITs_sound_manager_stream_cleanup},
{"ITc_sound_manager_activate_deactivate_ducking_p",ITc_sound_manager_activate_deactivate_ducking_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
{"ITc_sound_manager_is_ducked_p",ITc_sound_manager_is_ducked_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
{"ITc_sound_manager_create_destroy_stream_ducking_p",ITc_sound_manager_create_destroy_stream_ducking_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
{"ITc_sound_manager_set_get_stream_prefered_device_p",ITc_sound_manager_set_get_stream_prefered_device_p,ITs_sound_manager_stream_startup,ITs_sound_manager_stream_cleanup},
	{NULL, NULL}
};

#endif // __TCT_SOUND-MANAGER-NATIVE_H__
