//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_SCREEN-MIRRORING-NATIVE_H__
#define __TCT_SCREEN-MIRRORING-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_media_screen_mirroring_sink_startup(void);
extern void utc_media_screen_mirroring_sink_cleanup(void);

extern int utc_media_scmirroring_sink_create_p(void);
extern int utc_media_scmirroring_sink_create_n(void);
extern int utc_media_scmirroring_sink_destroy_p(void);
extern int utc_media_scmirroring_sink_destroy_n(void);
extern int utc_media_scmirroring_sink_set_state_changed_cb_p1(void);
extern int utc_media_scmirroring_sink_set_state_changed_cb_p2(void);
extern int utc_media_scmirroring_sink_set_state_changed_cb_n1(void);
extern int utc_media_scmirroring_sink_set_state_changed_cb_n2(void);
extern int utc_media_scmirroring_sink_unset_state_changed_cb_p(void);
extern int utc_media_scmirroring_sink_unset_state_changed_cb_n(void);
extern int utc_media_scmirroring_sink_set_ip_and_port_p(void);
extern int utc_media_scmirroring_sink_set_ip_and_port_n1(void);
extern int utc_media_scmirroring_sink_set_ip_and_port_n2(void);
extern int utc_media_scmirroring_sink_set_ip_and_port_n3(void);
extern int utc_media_scmirroring_sink_set_display_p1(void);
extern int utc_media_scmirroring_sink_set_display_p2(void);
extern int utc_media_scmirroring_sink_set_display_n1(void);
extern int utc_media_scmirroring_sink_set_display_n2(void);
extern int utc_media_scmirroring_sink_set_display_n3(void);
extern int utc_media_scmirroring_sink_set_resolution_p(void);
extern int utc_media_scmirroring_sink_set_resolution_n1(void);
extern int utc_media_scmirroring_sink_set_resolution_n2(void);
extern int utc_media_scmirroring_sink_prepare_p(void);
extern int utc_media_scmirroring_sink_prepare_n1(void);
extern int utc_media_scmirroring_sink_prepare_n2(void);
extern int utc_media_scmirroring_sink_connect_n1(void);
extern int utc_media_scmirroring_sink_connect_n2(void);
extern int utc_media_scmirroring_sink_connect_n3(void);
extern int utc_media_scmirroring_sink_start_n1(void);
extern int utc_media_scmirroring_sink_start_n2(void);
extern int utc_media_scmirroring_sink_disconnect_n(void);
extern int utc_media_scmirroring_sink_unprepare_p(void);
extern int utc_media_scmirroring_sink_unprepare_n(void);
extern int utc_media_scmirroring_sink_pause_n1(void);
extern int utc_media_scmirroring_sink_pause_n2(void);
extern int utc_media_scmirroring_sink_resume_n1(void);
extern int utc_media_scmirroring_sink_resume_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_codec_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_codec_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_codec_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_resolution_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_resolution_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_resolution_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_resolution_n4(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_codec_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_codec_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_codec_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_channel_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_channel_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_channel_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n3(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n1(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n2(void);
extern int utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n3(void);
extern int utc_media_scmirroring_sink_get_current_state_p1(void);
extern int utc_media_scmirroring_sink_get_current_state_p2(void);
extern int utc_media_scmirroring_sink_get_current_state_n1(void);
extern int utc_media_scmirroring_sink_get_current_state_n2(void);

testcase tc_array[] = {
	{"utc_media_scmirroring_sink_create_p",utc_media_scmirroring_sink_create_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_create_n",utc_media_scmirroring_sink_create_n,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_destroy_p",utc_media_scmirroring_sink_destroy_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_destroy_n",utc_media_scmirroring_sink_destroy_n,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_state_changed_cb_p1",utc_media_scmirroring_sink_set_state_changed_cb_p1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_state_changed_cb_p2",utc_media_scmirroring_sink_set_state_changed_cb_p2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_state_changed_cb_n1",utc_media_scmirroring_sink_set_state_changed_cb_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_state_changed_cb_n2",utc_media_scmirroring_sink_set_state_changed_cb_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_unset_state_changed_cb_p",utc_media_scmirroring_sink_unset_state_changed_cb_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_unset_state_changed_cb_n",utc_media_scmirroring_sink_unset_state_changed_cb_n,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_ip_and_port_p",utc_media_scmirroring_sink_set_ip_and_port_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_ip_and_port_n1",utc_media_scmirroring_sink_set_ip_and_port_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_ip_and_port_n2",utc_media_scmirroring_sink_set_ip_and_port_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_ip_and_port_n3",utc_media_scmirroring_sink_set_ip_and_port_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_display_p1",utc_media_scmirroring_sink_set_display_p1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_display_p2",utc_media_scmirroring_sink_set_display_p2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_display_n1",utc_media_scmirroring_sink_set_display_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_display_n2",utc_media_scmirroring_sink_set_display_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_display_n3",utc_media_scmirroring_sink_set_display_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_resolution_p",utc_media_scmirroring_sink_set_resolution_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_resolution_n1",utc_media_scmirroring_sink_set_resolution_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_set_resolution_n2",utc_media_scmirroring_sink_set_resolution_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_prepare_p",utc_media_scmirroring_sink_prepare_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_prepare_n1",utc_media_scmirroring_sink_prepare_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_prepare_n2",utc_media_scmirroring_sink_prepare_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_connect_n1",utc_media_scmirroring_sink_connect_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_connect_n2",utc_media_scmirroring_sink_connect_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_connect_n3",utc_media_scmirroring_sink_connect_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_start_n1",utc_media_scmirroring_sink_start_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_start_n2",utc_media_scmirroring_sink_start_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_disconnect_n",utc_media_scmirroring_sink_disconnect_n,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_unprepare_p",utc_media_scmirroring_sink_unprepare_p,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_unprepare_n",utc_media_scmirroring_sink_unprepare_n,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_pause_n1",utc_media_scmirroring_sink_pause_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_pause_n2",utc_media_scmirroring_sink_pause_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_resume_n1",utc_media_scmirroring_sink_resume_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_resume_n2",utc_media_scmirroring_sink_resume_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_codec_n1",utc_media_scmirroring_sink_get_negotiated_video_codec_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_codec_n2",utc_media_scmirroring_sink_get_negotiated_video_codec_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_codec_n3",utc_media_scmirroring_sink_get_negotiated_video_codec_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_resolution_n1",utc_media_scmirroring_sink_get_negotiated_video_resolution_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_resolution_n2",utc_media_scmirroring_sink_get_negotiated_video_resolution_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_resolution_n3",utc_media_scmirroring_sink_get_negotiated_video_resolution_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_resolution_n4",utc_media_scmirroring_sink_get_negotiated_video_resolution_n4,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n1",utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n2",utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n3",utc_media_scmirroring_sink_get_negotiated_video_frame_rate_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_codec_n1",utc_media_scmirroring_sink_get_negotiated_audio_codec_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_codec_n2",utc_media_scmirroring_sink_get_negotiated_audio_codec_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_codec_n3",utc_media_scmirroring_sink_get_negotiated_audio_codec_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_channel_n1",utc_media_scmirroring_sink_get_negotiated_audio_channel_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_channel_n2",utc_media_scmirroring_sink_get_negotiated_audio_channel_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_channel_n3",utc_media_scmirroring_sink_get_negotiated_audio_channel_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n1",utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n2",utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n3",utc_media_scmirroring_sink_get_negotiated_audio_sample_rate_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n1",utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n2",utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n3",utc_media_scmirroring_sink_get_negotiated_audio_bitwidth_n3,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_current_state_p1",utc_media_scmirroring_sink_get_current_state_p1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_current_state_p2",utc_media_scmirroring_sink_get_current_state_p2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_current_state_n1",utc_media_scmirroring_sink_get_current_state_n1,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{"utc_media_scmirroring_sink_get_current_state_n2",utc_media_scmirroring_sink_get_current_state_n2,utc_media_screen_mirroring_sink_startup,utc_media_screen_mirroring_sink_cleanup},
	{NULL, NULL}
};

#endif // __TCT_SCREEN-MIRRORING-NATIVE_H__
