//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_LOCATION-MANAGER-NATIVE_H__
#define __TCT_LOCATION-MANAGER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_location_manager_startup(void);
extern void ITs_location_manager_cleanup(void);
extern void ITs_location_bounds_startup(void);
extern void ITs_location_bounds_cleanup(void);
extern void ITs_location_gps_status_startup(void);
extern void ITs_location_gps_status_cleanup(void);
extern void ITs_location_batch_startup(void);
extern void ITs_location_batch_cleanup(void);

extern int ITc_location_manager_start_stop_p(void);
extern int ITc_location_manager_create_destroy_p(void);
extern int ITc_location_manager_set_unset_service_state_changed_cb_p(void);
extern int ITc_location_manager_get_accuracy_p(void);
extern int ITc_location_manager_get_distance_p(void);
extern int ITc_location_manager_get_last_accuracy_p(void);
extern int ITc_location_manager_get_last_location_p(void);
extern int ITc_location_manager_get_last_position_p(void);
extern int ITc_location_manager_get_last_velocity_p(void);
extern int ITc_location_manager_get_location_p(void);
extern int ITc_location_manager_get_is_supported_method_p(void);
extern int ITc_location_manager_get_position_p(void);
extern int ITc_location_manager_get_velocity_p(void);
extern int ITc_location_manager_add_remove_boundary_circle_p(void);
extern int ITc_location_manager_add_remove_boundary_rect_p(void);
extern int ITc_location_manager_add_remove_boundary_polygon_p(void);
extern int ITc_location_manager_set_unset_position_updated_cb_p(void);
extern int ITc_location_manager_set_unset_velocity_updated_cb(void);
extern int ITc_location_manager_set_unset_zone_changed_cb_p(void);
extern int ITc_location_manager_foreach_boundary_p(void);
extern int ITc_location_manager_set_unset_setting_changed_cb_p(void);
extern int ITc_location_manager_request_single_location_p(void);
extern int ITc_location_manager_is_enabled_method_p(void);
extern int ITc_location_manager_set_unset_location_changed_cb_p(void);
extern int ITc_location_manager_set_unset_distance_based_location_changed_cb_p(void);
extern int ITc_location_manager_enable_mock_location_p(void);
extern int ITc_location_manager_set_clear_mock_location_p(void);
extern int ITc_location_manager_is_enabled_mock_location_p(void);
extern int ITc_location_manager_get_velocity_accuracy_p(void);
extern int ITc_location_bounds_create_destory_rect_p(void);
extern int ITc_location_bounds_get_rect_coords_p(void);
extern int ITc_location_bounds_create_destory_circle_p(void);
extern int ITc_location_bounds_get_circle_coords_p(void);
extern int ITc_location_bounds_create_destory_polygon_p(void);
extern int ITc_location_bounds_set_unset_state_changed_cb_p(void);
extern int ITc_location_bounds_foreach_polygon_coords_p(void);
extern int ITc_location_bounds_contains_coordinates_p(void);
extern int ITc_location_bounds_get_type_p(void);
extern int ITc_location_bounds_contains_coordinates_on_edge_p(void);
extern int ITc_gps_status_get_nmea_p(void);
extern int ITc_gps_status_get_satellite_p(void);
extern int ITc_gps_status_get_last_satellite_p(void);
extern int ITc_gps_status_foreach_last_satellites_in_view_p(void);
extern int ITc_gps_status_foreach_satellites_in_view_p(void);
extern int ITc_gps_status_set_unset_satellite_updated_cb_p(void);
extern int ITc_location_start_stop_batch_p(void);
extern int ITc_location_manager_foreach_location_batch_p(void);
extern int ITc_location_manager_set_unset_location_batch_cb_p(void);

testcase tc_array[] = {
	{"ITc_location_manager_start_stop_p",ITc_location_manager_start_stop_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_create_destroy_p",ITc_location_manager_create_destroy_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_service_state_changed_cb_p",ITc_location_manager_set_unset_service_state_changed_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_accuracy_p",ITc_location_manager_get_accuracy_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_distance_p",ITc_location_manager_get_distance_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_last_accuracy_p",ITc_location_manager_get_last_accuracy_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_last_location_p",ITc_location_manager_get_last_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_last_position_p",ITc_location_manager_get_last_position_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_last_velocity_p",ITc_location_manager_get_last_velocity_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_location_p",ITc_location_manager_get_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_is_supported_method_p",ITc_location_manager_get_is_supported_method_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_position_p",ITc_location_manager_get_position_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_velocity_p",ITc_location_manager_get_velocity_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_add_remove_boundary_circle_p",ITc_location_manager_add_remove_boundary_circle_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_add_remove_boundary_rect_p",ITc_location_manager_add_remove_boundary_rect_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_add_remove_boundary_polygon_p",ITc_location_manager_add_remove_boundary_polygon_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_position_updated_cb_p",ITc_location_manager_set_unset_position_updated_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_velocity_updated_cb",ITc_location_manager_set_unset_velocity_updated_cb,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_zone_changed_cb_p",ITc_location_manager_set_unset_zone_changed_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_foreach_boundary_p",ITc_location_manager_foreach_boundary_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_setting_changed_cb_p",ITc_location_manager_set_unset_setting_changed_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_request_single_location_p",ITc_location_manager_request_single_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_is_enabled_method_p",ITc_location_manager_is_enabled_method_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_location_changed_cb_p",ITc_location_manager_set_unset_location_changed_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_unset_distance_based_location_changed_cb_p",ITc_location_manager_set_unset_distance_based_location_changed_cb_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_enable_mock_location_p",ITc_location_manager_enable_mock_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_set_clear_mock_location_p",ITc_location_manager_set_clear_mock_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_is_enabled_mock_location_p",ITc_location_manager_is_enabled_mock_location_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_manager_get_velocity_accuracy_p",ITc_location_manager_get_velocity_accuracy_p,ITs_location_manager_startup,ITs_location_manager_cleanup},
	{"ITc_location_bounds_create_destory_rect_p",ITc_location_bounds_create_destory_rect_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_get_rect_coords_p",ITc_location_bounds_get_rect_coords_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_create_destory_circle_p",ITc_location_bounds_create_destory_circle_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_get_circle_coords_p",ITc_location_bounds_get_circle_coords_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_create_destory_polygon_p",ITc_location_bounds_create_destory_polygon_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_set_unset_state_changed_cb_p",ITc_location_bounds_set_unset_state_changed_cb_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_foreach_polygon_coords_p",ITc_location_bounds_foreach_polygon_coords_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_contains_coordinates_p",ITc_location_bounds_contains_coordinates_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_get_type_p",ITc_location_bounds_get_type_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_location_bounds_contains_coordinates_on_edge_p",ITc_location_bounds_contains_coordinates_on_edge_p,ITs_location_bounds_startup,ITs_location_bounds_cleanup},
	{"ITc_gps_status_get_nmea_p",ITc_gps_status_get_nmea_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_gps_status_get_satellite_p",ITc_gps_status_get_satellite_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_gps_status_get_last_satellite_p",ITc_gps_status_get_last_satellite_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_gps_status_foreach_last_satellites_in_view_p",ITc_gps_status_foreach_last_satellites_in_view_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_gps_status_foreach_satellites_in_view_p",ITc_gps_status_foreach_satellites_in_view_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_gps_status_set_unset_satellite_updated_cb_p",ITc_gps_status_set_unset_satellite_updated_cb_p,ITs_location_gps_status_startup,ITs_location_gps_status_cleanup},
	{"ITc_location_start_stop_batch_p",ITc_location_start_stop_batch_p,ITs_location_batch_startup,ITs_location_batch_cleanup},
	{"ITc_location_manager_foreach_location_batch_p",ITc_location_manager_foreach_location_batch_p,ITs_location_batch_startup,ITs_location_batch_cleanup},
	{"ITc_location_manager_set_unset_location_batch_cb_p",ITc_location_manager_set_unset_location_batch_cb_p,ITs_location_batch_startup,ITs_location_batch_cleanup},
	{NULL, NULL}
};

#endif // __TCT_LOCATION-MANAGER-NATIVE_H__
