#ifndef _UTC_DALI_CONSTRAINT_FUNCTION_COMMON_H_
#define _UTC_DALI_CONSTRAINT_FUNCTION_COMMON_H_

#include "dali-common.h"


using namespace Dali;

#define SUITE_NAME "CONSTRAINT_FUNCTION_UTC"

#endif  //_UTC_DALI_CONSTRAINT_FUNCTION_COMMON_H_
