//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAPI-MEDIA-STREAMER-NATIVE_H__
#define __TCT_CAPI-MEDIA-STREAMER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_capi_media_streamer_startup(void);
extern void utc_capi_media_streamer_cleanup(void);
extern void utc_capi_media_streamer_cb_startup(void);
extern void utc_capi_media_streamer_cb_cleanup(void);

extern int utc_media_streamer_create_p(void);
extern int utc_media_streamer_create_n(void);
extern int utc_media_streamer_prepare_p(void);
extern int utc_media_streamer_prepare_n(void);
extern int utc_media_streamer_unprepare_p(void);
extern int utc_media_streamer_unprepare_n(void);
extern int utc_media_streamer_play_p1(void);
extern int utc_media_streamer_play_p2(void);
extern int utc_media_streamer_play_n1(void);
extern int utc_media_streamer_play_n2(void);
extern int utc_media_streamer_pause_p(void);
extern int utc_media_streamer_pause_n(void);
extern int utc_media_streamer_set_position_p(void);
extern int utc_media_streamer_set_position_n1(void);
extern int utc_media_streamer_set_position_n2(void);
extern int utc_media_streamer_get_position_p(void);
extern int utc_media_streamer_get_position_n(void);
extern int utc_media_streamer_get_duration_p1(void);
extern int utc_media_streamer_get_duration_p2(void);
extern int utc_media_streamer_get_duration_n(void);
extern int utc_media_streamer_stop_p(void);
extern int utc_media_streamer_stop_n(void);
extern int utc_media_streamer_destroy_p1(void);
extern int utc_media_streamer_destroy_p2(void);
extern int utc_media_streamer_destroy_n(void);
extern int utc_media_streamer_get_state_p(void);
extern int utc_media_streamer_get_state_n(void);
extern int utc_media_streamer_node_create_src_p(void);
extern int utc_media_streamer_node_create_src_n1(void);
extern int utc_media_streamer_node_create_src_n2(void);
extern int utc_media_streamer_node_push_packet_p(void);
extern int utc_media_streamer_node_push_packet_n1(void);
extern int utc_media_streamer_node_push_packet_n2(void);
extern int utc_media_streamer_node_create_sink_p(void);
extern int utc_media_streamer_node_create_sink_n1(void);
extern int utc_media_streamer_node_create_sink_n2(void);
extern int utc_media_streamer_node_pull_packet_p(void);
extern int utc_media_streamer_node_pull_packet_n(void);
extern int utc_media_streamer_node_create_p(void);
extern int utc_media_streamer_node_create_n(void);
extern int utc_media_streamer_node_add_p(void);
extern int utc_media_streamer_node_add_n(void);
extern int utc_media_streamer_node_destroy_p(void);
extern int utc_media_streamer_node_destroy_n(void);
extern int utc_media_streamer_node_remove_p(void);
extern int utc_media_streamer_node_remove_n(void);
extern int utc_media_streamer_node_link_p(void);
extern int utc_media_streamer_node_link_n(void);
extern int utc_media_streamer_node_set_pad_format_p(void);
extern int utc_media_streamer_node_set_pad_format_n(void);
extern int utc_media_streamer_node_get_pad_format_p(void);
extern int utc_media_streamer_node_get_pad_format_n1(void);
extern int utc_media_streamer_node_get_pad_format_n2(void);
extern int utc_media_streamer_node_get_pad_format_n3(void);
extern int utc_media_streamer_node_get_pad_format_n4(void);
extern int utc_media_streamer_node_get_pad_format_n5(void);
extern int utc_media_streamer_node_get_pad_name_p(void);
extern int utc_media_streamer_node_get_pad_name_n(void);
extern int utc_media_streamer_node_set_params_p1(void);
extern int utc_media_streamer_node_set_params_p2(void);
extern int utc_media_streamer_node_set_params_p3(void);
extern int utc_media_streamer_node_set_params_p4(void);
extern int utc_media_streamer_node_set_params_n1(void);
extern int utc_media_streamer_node_set_params_n2(void);
extern int utc_media_streamer_node_set_params_n3(void);
extern int utc_media_streamer_node_set_params_n4(void);
extern int utc_media_streamer_node_get_params_p1(void);
extern int utc_media_streamer_node_get_params_p2(void);
extern int utc_media_streamer_node_get_params_p3(void);
extern int utc_media_streamer_node_get_params_p4(void);
extern int utc_media_streamer_node_get_params_p5(void);
extern int utc_media_streamer_node_get_params_n1(void);
extern int utc_media_streamer_node_get_params_n2(void);
extern int utc_media_streamer_node_get_params_n3(void);
extern int utc_media_streamer_node_get_params_n4(void);
extern int utc_media_streamer_node_set_param_p1(void);
extern int utc_media_streamer_node_set_param_p2(void);
extern int utc_media_streamer_node_set_param_p3(void);
extern int utc_media_streamer_node_set_param_p4(void);
extern int utc_media_streamer_node_set_param_n1(void);
extern int utc_media_streamer_node_set_param_n2(void);
extern int utc_media_streamer_node_set_param_n3(void);
extern int utc_media_streamer_node_set_param_n4(void);
extern int utc_media_streamer_node_get_param_p1(void);
extern int utc_media_streamer_node_get_param_p2(void);
extern int utc_media_streamer_node_get_param_p3(void);
extern int utc_media_streamer_node_get_param_p4(void);
extern int utc_media_streamer_node_get_param_p5(void);
extern int utc_media_streamer_node_get_param_n1(void);
extern int utc_media_streamer_node_get_param_n2(void);
extern int utc_media_streamer_node_get_param_n3(void);
extern int utc_media_streamer_node_get_param_n4(void);
extern int utc_media_streamer_play_p3(void);
extern int utc_media_streamer_play_p4(void);
extern int utc_media_streamer_play_p5(void);
extern int utc_media_streamer_play_p6(void);
extern int utc_media_streamer_set_error_cb_p(void);
extern int utc_media_streamer_set_error_cb_n(void);
extern int utc_media_streamer_unset_error_cb_p(void);
extern int utc_media_streamer_unset_error_cb_n(void);
extern int utc_media_streamer_set_state_change_cb_p(void);
extern int utc_media_streamer_set_state_change_cb_n(void);
extern int utc_media_streamer_unset_state_change_cb_p(void);
extern int utc_media_streamer_unset_state_change_cb_n(void);
extern int utc_media_streamer_src_set_buffer_status_cb_p(void);
extern int utc_media_streamer_src_set_buffer_status_cb_n(void);
extern int utc_media_streamer_src_unset_buffer_status_cb_p(void);
extern int utc_media_streamer_src_unset_buffer_status_cb_n(void);
extern int utc_media_streamer_sink_set_data_ready_cb_p(void);
extern int utc_media_streamer_sink_set_data_ready_cb_n(void);
extern int utc_media_streamer_sink_unset_data_ready_cb_p(void);
extern int utc_media_streamer_sink_unset_data_ready_cb_n(void);
extern int utc_media_streamer_sink_set_eos_cb_p(void);
extern int utc_media_streamer_sink_set_eos_cb_n(void);
extern int utc_media_streamer_sink_unset_eos_cb_p(void);
extern int utc_media_streamer_sink_unset_eos_cb_n(void);
extern int utc_media_streamer_set_interrupted_cb_p(void);
extern int utc_media_streamer_set_interrupted_cb_n(void);
extern int utc_media_streamer_unset_interrupted_cb_p(void);
extern int utc_media_streamer_unset_interrupted_cb_n(void);

testcase tc_array[] = {
	{"utc_media_streamer_create_p",utc_media_streamer_create_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_create_n",utc_media_streamer_create_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_prepare_p",utc_media_streamer_prepare_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_prepare_n",utc_media_streamer_prepare_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_unprepare_p",utc_media_streamer_unprepare_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_unprepare_n",utc_media_streamer_unprepare_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p1",utc_media_streamer_play_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p2",utc_media_streamer_play_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_n1",utc_media_streamer_play_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_n2",utc_media_streamer_play_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_pause_p",utc_media_streamer_pause_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_pause_n",utc_media_streamer_pause_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_set_position_p",utc_media_streamer_set_position_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_set_position_n1",utc_media_streamer_set_position_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_set_position_n2",utc_media_streamer_set_position_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_position_p",utc_media_streamer_get_position_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_position_n",utc_media_streamer_get_position_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_duration_p1",utc_media_streamer_get_duration_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_duration_p2",utc_media_streamer_get_duration_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_duration_n",utc_media_streamer_get_duration_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_stop_p",utc_media_streamer_stop_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_stop_n",utc_media_streamer_stop_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_destroy_p1",utc_media_streamer_destroy_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_destroy_p2",utc_media_streamer_destroy_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_destroy_n",utc_media_streamer_destroy_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_state_p",utc_media_streamer_get_state_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_get_state_n",utc_media_streamer_get_state_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_src_p",utc_media_streamer_node_create_src_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_src_n1",utc_media_streamer_node_create_src_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_src_n2",utc_media_streamer_node_create_src_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_push_packet_p",utc_media_streamer_node_push_packet_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_push_packet_n1",utc_media_streamer_node_push_packet_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_push_packet_n2",utc_media_streamer_node_push_packet_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_sink_p",utc_media_streamer_node_create_sink_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_sink_n1",utc_media_streamer_node_create_sink_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_sink_n2",utc_media_streamer_node_create_sink_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_pull_packet_p",utc_media_streamer_node_pull_packet_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_pull_packet_n",utc_media_streamer_node_pull_packet_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_p",utc_media_streamer_node_create_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_create_n",utc_media_streamer_node_create_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_add_p",utc_media_streamer_node_add_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_add_n",utc_media_streamer_node_add_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_destroy_p",utc_media_streamer_node_destroy_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_destroy_n",utc_media_streamer_node_destroy_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_remove_p",utc_media_streamer_node_remove_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_remove_n",utc_media_streamer_node_remove_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_link_p",utc_media_streamer_node_link_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_link_n",utc_media_streamer_node_link_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_pad_format_p",utc_media_streamer_node_set_pad_format_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_pad_format_n",utc_media_streamer_node_set_pad_format_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_p",utc_media_streamer_node_get_pad_format_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_n1",utc_media_streamer_node_get_pad_format_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_n2",utc_media_streamer_node_get_pad_format_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_n3",utc_media_streamer_node_get_pad_format_n3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_n4",utc_media_streamer_node_get_pad_format_n4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_format_n5",utc_media_streamer_node_get_pad_format_n5,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_name_p",utc_media_streamer_node_get_pad_name_p,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_pad_name_n",utc_media_streamer_node_get_pad_name_n,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_p1",utc_media_streamer_node_set_params_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_p2",utc_media_streamer_node_set_params_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_p3",utc_media_streamer_node_set_params_p3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_p4",utc_media_streamer_node_set_params_p4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_n1",utc_media_streamer_node_set_params_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_n2",utc_media_streamer_node_set_params_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_n3",utc_media_streamer_node_set_params_n3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_params_n4",utc_media_streamer_node_set_params_n4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_p1",utc_media_streamer_node_get_params_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_p2",utc_media_streamer_node_get_params_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_p3",utc_media_streamer_node_get_params_p3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_p4",utc_media_streamer_node_get_params_p4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_p5",utc_media_streamer_node_get_params_p5,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_n1",utc_media_streamer_node_get_params_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_n2",utc_media_streamer_node_get_params_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_n3",utc_media_streamer_node_get_params_n3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_params_n4",utc_media_streamer_node_get_params_n4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_p1",utc_media_streamer_node_set_param_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_p2",utc_media_streamer_node_set_param_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_p3",utc_media_streamer_node_set_param_p3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_p4",utc_media_streamer_node_set_param_p4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_n1",utc_media_streamer_node_set_param_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_n2",utc_media_streamer_node_set_param_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_n3",utc_media_streamer_node_set_param_n3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_set_param_n4",utc_media_streamer_node_set_param_n4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_p1",utc_media_streamer_node_get_param_p1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_p2",utc_media_streamer_node_get_param_p2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_p3",utc_media_streamer_node_get_param_p3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_p4",utc_media_streamer_node_get_param_p4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_p5",utc_media_streamer_node_get_param_p5,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_n1",utc_media_streamer_node_get_param_n1,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_n2",utc_media_streamer_node_get_param_n2,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_n3",utc_media_streamer_node_get_param_n3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_node_get_param_n4",utc_media_streamer_node_get_param_n4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p3",utc_media_streamer_play_p3,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p4",utc_media_streamer_play_p4,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p5",utc_media_streamer_play_p5,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_play_p6",utc_media_streamer_play_p6,utc_capi_media_streamer_startup,utc_capi_media_streamer_cleanup},
	{"utc_media_streamer_set_error_cb_p",utc_media_streamer_set_error_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_set_error_cb_n",utc_media_streamer_set_error_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_error_cb_p",utc_media_streamer_unset_error_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_error_cb_n",utc_media_streamer_unset_error_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_set_state_change_cb_p",utc_media_streamer_set_state_change_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_set_state_change_cb_n",utc_media_streamer_set_state_change_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_state_change_cb_p",utc_media_streamer_unset_state_change_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_state_change_cb_n",utc_media_streamer_unset_state_change_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_src_set_buffer_status_cb_p",utc_media_streamer_src_set_buffer_status_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_src_set_buffer_status_cb_n",utc_media_streamer_src_set_buffer_status_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_src_unset_buffer_status_cb_p",utc_media_streamer_src_unset_buffer_status_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_src_unset_buffer_status_cb_n",utc_media_streamer_src_unset_buffer_status_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_set_data_ready_cb_p",utc_media_streamer_sink_set_data_ready_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_set_data_ready_cb_n",utc_media_streamer_sink_set_data_ready_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_unset_data_ready_cb_p",utc_media_streamer_sink_unset_data_ready_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_unset_data_ready_cb_n",utc_media_streamer_sink_unset_data_ready_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_set_eos_cb_p",utc_media_streamer_sink_set_eos_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_set_eos_cb_n",utc_media_streamer_sink_set_eos_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_unset_eos_cb_p",utc_media_streamer_sink_unset_eos_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_sink_unset_eos_cb_n",utc_media_streamer_sink_unset_eos_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_set_interrupted_cb_p",utc_media_streamer_set_interrupted_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_set_interrupted_cb_n",utc_media_streamer_set_interrupted_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_interrupted_cb_p",utc_media_streamer_unset_interrupted_cb_p,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{"utc_media_streamer_unset_interrupted_cb_n",utc_media_streamer_unset_interrupted_cb_n,utc_capi_media_streamer_cb_startup,utc_capi_media_streamer_cb_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CAPI-MEDIA-STREAMER-NATIVE_H__
