//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CONTACTS-SERVICE2-NATIVE_H__
#define __TCT_CONTACTS-SERVICE2-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_contacts_service2_service_startup(void);
extern void utc_contacts_service2_service_cleanup(void);
extern void utc_contacts_service2_filter_startup(void);
extern void utc_contacts_service2_filter_cleanup(void);
extern void utc_contacts_service2_person_startup(void);
extern void utc_contacts_service2_person_cleanup(void);
extern void utc_contacts_service2_group_startup(void);
extern void utc_contacts_service2_group_cleanup(void);
extern void utc_contacts_service2_sim_startup(void);
extern void utc_contacts_service2_sim_cleanup(void);
extern void utc_contacts_service2_setting_startup(void);
extern void utc_contacts_service2_setting_cleanup(void);
extern void utc_contacts_service2_vcard_startup(void);
extern void utc_contacts_service2_vcard_cleanup(void);
extern void utc_contacts_service2_sdn_startup(void);
extern void utc_contacts_service2_sdn_cleanup(void);
extern void utc_contacts_service2_list_startup(void);
extern void utc_contacts_service2_list_cleanup(void);
extern void utc_contacts_service2_db_startup(void);
extern void utc_contacts_service2_db_cleanup(void);
extern void utc_contacts_service2_db_status_startup(void);
extern void utc_contacts_service2_db_status_cleanup(void);
extern void utc_contacts_service2_query_startup(void);
extern void utc_contacts_service2_query_cleanup(void);
extern void utc_contacts_service2_record_startup(void);
extern void utc_contacts_service2_record_cleanup(void);
extern void utc_contacts_service2_activity_startup(void);
extern void utc_contacts_service2_activity_cleanup(void);
extern void utc_contacts_service2_phone_log_startup(void);
extern void utc_contacts_service2_phone_log_cleanup(void);

extern int utc_contacts_service2_connect_p(void);
extern int utc_contacts_service2_connect_on_flags_p(void);
extern int utc_contacts_service2_connect_on_flags_n(void);
extern int utc_contacts_service2_disconnect_p(void);
extern int utc_contacts_service2_connect_on_thread_p(void);
extern int utc_contacts_service2_disconnect_on_thread_p(void);
extern int utc_contacts_service2_filter_create_p(void);
extern int utc_contacts_service2_filter_create_n(void);
extern int utc_contacts_service2_filter_destroy_p(void);
extern int utc_contacts_service2_filter_destroy_n(void);
extern int utc_contacts_service2_filter_add_operator_p(void);
extern int utc_contacts_service2_filter_add_operator_n(void);
extern int utc_contacts_service2_filter_add_filter_p(void);
extern int utc_contacts_service2_filter_add_filter_n(void);
extern int utc_contacts_service2_filter_add_bool_n(void);
extern int utc_contacts_service2_filter_add_int_n(void);
extern int utc_contacts_service2_filter_add_double_n(void);
extern int utc_contacts_service2_filter_add_lli_n(void);
extern int utc_contacts_service2_filter_add_str_n(void);
extern int utc_contacts_service2_filter_add_bool_p(void);
extern int utc_contacts_service2_filter_add_int_p(void);
extern int utc_contacts_service2_filter_add_lli_p(void);
extern int utc_contacts_service2_filter_add_str_p(void);
extern int utc_contacts_service2_person_get_default_property_p(void);
extern int utc_contacts_service2_person_get_default_property_n(void);
extern int utc_contacts_service2_person_set_default_property_p(void);
extern int utc_contacts_service2_person_set_default_property_n(void);
extern int utc_contacts_service2_person_link_person_p(void);
extern int utc_contacts_service2_person_link_person_n(void);
extern int utc_contacts_service2_person_unlink_contact_p(void);
extern int utc_contacts_service2_person_unlink_contact_n(void);
extern int utc_contacts_service2_person_reset_usage_p(void);
extern int utc_contacts_service2_person_reset_usage_n(void);
extern int utc_contacts_service2_person_set_favorite_order_p(void);
extern int utc_contacts_service2_person_set_favorite_order_n(void);
extern int utc_contacts_service2_person_get_aggregation_suggestions_p(void);
extern int utc_contacts_service2_person_get_aggregation_suggestions_n(void);
extern int utc_contacts_service2_group_add_contact_p(void);
extern int utc_contacts_service2_group_add_contact_n(void);
extern int utc_contacts_service2_group_remove_contact_p(void);
extern int utc_contacts_service2_group_remove_contact_n(void);
extern int utc_contacts_service2_group_set_group_order_p(void);
extern int utc_contacts_service2_group_set_group_order_n(void);
extern int utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_p(void);
extern int utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_n(void);
extern int utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_p(void);
extern int utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_n(void);
extern int utc_contacts_service2_setting_add_name_display_order_changed_cb_p(void);
extern int utc_contacts_service2_setting_add_name_display_order_changed_cb_n(void);
extern int utc_contacts_service2_setting_remove_name_display_order_changed_cb_p(void);
extern int utc_contacts_service2_setting_remove_name_display_order_changed_cb_n(void);
extern int utc_contacts_service2_setting_add_name_sorting_order_changed_cb_p(void);
extern int utc_contacts_service2_setting_add_name_sorting_order_changed_cb_n(void);
extern int utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_p(void);
extern int utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_n(void);
extern int utc_contacts_service2_setting_get_name_display_order_p(void);
extern int utc_contacts_service2_setting_get_name_display_order_n(void);
extern int utc_contacts_service2_setting_set_name_display_order_p(void);
extern int utc_contacts_service2_setting_set_name_display_order_n(void);
extern int utc_contacts_service2_setting_get_name_sorting_order_p(void);
extern int utc_contacts_service2_setting_get_name_sorting_order_n(void);
extern int utc_contacts_service2_setting_set_name_sorting_order_p(void);
extern int utc_contacts_service2_setting_set_name_sorting_order_n(void);
extern int utc_contacts_service2_vcard_get_entity_count_p(void);
extern int utc_contacts_service2_vcard_get_entity_count_n(void);
extern int utc_contacts_service2_vcard_make_from_contact_p(void);
extern int utc_contacts_service2_vcard_make_from_contact_n(void);
extern int utc_contacts_service2_vcard_make_from_my_profile_p(void);
extern int utc_contacts_service2_vcard_make_from_my_profile_n(void);
extern int utc_contacts_service2_vcard_make_from_person_p(void);
extern int utc_contacts_service2_vcard_make_from_person_n(void);
extern int utc_contacts_service2_vcard_parse_to_contacts_p(void);
extern int utc_contacts_service2_vcard_parse_to_contacts_n(void);
extern int utc_contacts_service2_vcard_parse_to_contact_foreach_p(void);
extern int utc_contacts_service2_vcard_parse_to_contact_foreach_n(void);
extern int utc_contacts_service2_vcard_get_limit_size_of_photo_p(void);
extern int utc_contacts_service2_vcard_get_limit_size_of_photo_n(void);
extern int utc_contacts_service2_vcard_set_limit_size_of_photo_p(void);
extern int utc_contacts_service2_vcard_set_limit_size_of_photo_n(void);
extern int utc_contacts_service2_sdn_db_p(void);
extern int utc_contacts_service2_list_create_p(void);
extern int utc_contacts_service2_list_create_n(void);
extern int utc_contacts_service2_list_destroy_p(void);
extern int utc_contacts_service2_list_destroy_n(void);
extern int utc_contacts_service2_list_first_p(void);
extern int utc_contacts_service2_list_first_n(void);
extern int utc_contacts_service2_list_get_count_p(void);
extern int utc_contacts_service2_list_get_count_n(void);
extern int utc_contacts_service2_list_get_current_record_p_p(void);
extern int utc_contacts_service2_list_get_current_record_p_n(void);
extern int utc_contacts_service2_list_last_p(void);
extern int utc_contacts_service2_list_last_n(void);
extern int utc_contacts_service2_list_next_p(void);
extern int utc_contacts_service2_list_next_n(void);
extern int utc_contacts_service2_list_prev_p(void);
extern int utc_contacts_service2_list_prev_n(void);
extern int utc_contacts_service2_list_add_p(void);
extern int utc_contacts_service2_list_add_n(void);
extern int utc_contacts_service2_list_remove_p(void);
extern int utc_contacts_service2_list_remove_n(void);
extern int utc_contacts_service2_db_get_record_p(void);
extern int utc_contacts_service2_db_get_record_n(void);
extern int utc_contacts_service2_db_get_all_records_p(void);
extern int utc_contacts_service2_db_get_all_records_n(void);
extern int utc_contacts_service2_db_get_records_with_query_p(void);
extern int utc_contacts_service2_db_get_records_with_query_n(void);
extern int utc_contacts_service2_db_get_changes_by_version_p(void);
extern int utc_contacts_service2_db_get_changes_by_version_n(void);
extern int utc_contacts_service2_db_get_count_p(void);
extern int utc_contacts_service2_db_get_count_n(void);
extern int utc_contacts_service2_db_get_count_with_query_p(void);
extern int utc_contacts_service2_db_get_count_with_query_n(void);
extern int utc_contacts_service2_db_get_current_version_p(void);
extern int utc_contacts_service2_db_get_current_version_n(void);
extern int utc_contacts_service2_db_get_last_change_version_p(void);
extern int utc_contacts_service2_db_get_last_change_version_n(void);
extern int utc_contacts_service2_db_insert_record_p(void);
extern int utc_contacts_service2_db_insert_record_n(void);
extern int utc_contacts_service2_db_insert_records_p(void);
extern int utc_contacts_service2_db_insert_records_n(void);
extern int utc_contacts_service2_db_update_record_p(void);
extern int utc_contacts_service2_db_update_record_n(void);
extern int utc_contacts_service2_db_update_records_p(void);
extern int utc_contacts_service2_db_update_records_n(void);
extern int utc_contacts_service2_db_replace_record_p(void);
extern int utc_contacts_service2_db_replace_record_n(void);
extern int utc_contacts_service2_db_replace_records_p(void);
extern int utc_contacts_service2_db_replace_records_n(void);
extern int utc_contacts_service2_db_delete_record_p(void);
extern int utc_contacts_service2_db_delete_record_n(void);
extern int utc_contacts_service2_db_delete_records_p(void);
extern int utc_contacts_service2_db_delete_records_n(void);
extern int utc_contacts_service2_db_search_records_p(void);
extern int utc_contacts_service2_db_search_records_n(void);
extern int utc_contacts_service2_db_search_records_with_query_p(void);
extern int utc_contacts_service2_db_search_records_with_query_n(void);
extern int utc_contacts_service2_db_search_records_with_range_p(void);
extern int utc_contacts_service2_db_search_records_with_range_n(void);
extern int utc_contacts_service2_db_get_count_for_search_records_p(void);
extern int utc_contacts_service2_db_get_count_for_search_records_n(void);
extern int utc_contacts_service2_db_get_count_for_search_records_with_query_p(void);
extern int utc_contacts_service2_db_get_count_for_search_records_with_query_n(void);
extern int utc_contacts_service2_db_get_count_for_search_records_with_range_p(void);
extern int utc_contacts_service2_db_get_count_for_search_records_with_range_n(void);
extern int utc_contacts_service2_db_search_records_for_snippet_p(void);
extern int utc_contacts_service2_db_search_records_for_snippet_n(void);
extern int utc_contacts_service2_db_search_records_with_query_for_snippet_p(void);
extern int utc_contacts_service2_db_search_records_with_query_for_snippet_n(void);
extern int utc_contacts_service2_db_search_records_with_range_for_snippet_p(void);
extern int utc_contacts_service2_db_search_records_with_range_for_snippet_n(void);
extern int utc_contacts_service2_db_add_changed_cb_p(void);
extern int utc_contacts_service2_db_add_changed_cb_n(void);
extern int utc_contacts_service2_db_remove_changed_cb_p(void);
extern int utc_contacts_service2_db_remove_changed_cb_n(void);
extern int utc_contacts_service2_db_get_status_p(void);
extern int utc_contacts_service2_db_get_status_n(void);
extern int utc_contacts_service2_db_add_status_changed_cb_p(void);
extern int utc_contacts_service2_db_add_status_changed_cb_n(void);
extern int utc_contacts_service2_db_remove_status_changed_cb_p(void);
extern int utc_contacts_service2_db_remove_status_changed_cb_n(void);
extern int utc_contacts_service2_query_create_p(void);
extern int utc_contacts_service2_query_create_n(void);
extern int utc_contacts_service2_query_destroy_p(void);
extern int utc_contacts_service2_query_destroy_n(void);
extern int utc_contacts_service2_query_set_distinct_p(void);
extern int utc_contacts_service2_query_set_distinct_n(void);
extern int utc_contacts_service2_query_set_filter_p(void);
extern int utc_contacts_service2_query_set_filter_n(void);
extern int utc_contacts_service2_query_set_projection_p(void);
extern int utc_contacts_service2_query_set_projection_n(void);
extern int utc_contacts_service2_query_set_sort_p(void);
extern int utc_contacts_service2_query_set_sort_n(void);
extern int utc_contacts_service2_record_clone_p(void);
extern int utc_contacts_service2_record_create_p(void);
extern int utc_contacts_service2_record_destroy_p(void);
extern int utc_contacts_service2_record_get_uri_p_p(void);
extern int utc_contacts_service2_record_add_child_record_p(void);
extern int utc_contacts_service2_record_clone_child_record_list_p(void);
extern int utc_contacts_service2_record_remove_child_record_p(void);
extern int utc_contacts_service2_record_get_child_record_at_p_p(void);
extern int utc_contacts_service2_record_get_child_record_count_p(void);
extern int utc_contacts_service2_record_get_bool_p(void);
extern int utc_contacts_service2_record_get_double_p(void);
extern int utc_contacts_service2_record_get_int_p(void);
extern int utc_contacts_service2_record_get_lli_p(void);
extern int utc_contacts_service2_record_get_str_p(void);
extern int utc_contacts_service2_record_get_str_p_p(void);
extern int utc_contacts_service2_record_set_bool_p(void);
extern int utc_contacts_service2_record_set_double_p(void);
extern int utc_contacts_service2_record_set_int_p(void);
extern int utc_contacts_service2_record_set_lli_p(void);
extern int utc_contacts_service2_record_set_str_p(void);
extern int utc_contacts_service2_record_clone_n(void);
extern int utc_contacts_service2_record_create_n(void);
extern int utc_contacts_service2_record_destroy_n(void);
extern int utc_contacts_service2_record_get_uri_p_n(void);
extern int utc_contacts_service2_record_add_child_record_n(void);
extern int utc_contacts_service2_record_clone_child_record_list_n(void);
extern int utc_contacts_service2_record_remove_child_record_n(void);
extern int utc_contacts_service2_record_get_child_record_at_p_n(void);
extern int utc_contacts_service2_record_get_child_record_count_n(void);
extern int utc_contacts_service2_record_get_bool_n(void);
extern int utc_contacts_service2_record_get_double_n(void);
extern int utc_contacts_service2_record_get_int_n(void);
extern int utc_contacts_service2_record_get_lli_n(void);
extern int utc_contacts_service2_record_get_str_n(void);
extern int utc_contacts_service2_record_get_str_p_n(void);
extern int utc_contacts_service2_record_set_bool_n(void);
extern int utc_contacts_service2_record_set_double_n(void);
extern int utc_contacts_service2_record_set_int_n(void);
extern int utc_contacts_service2_record_set_lli_n(void);
extern int utc_contacts_service2_record_set_str_n(void);
extern int utc_contacts_service2_activity_delete_by_contact_id_p(void);
extern int utc_contacts_service2_activity_delete_by_contact_id_n(void);
extern int utc_contacts_service2_activity_delete_by_account_id_p(void);
extern int utc_contacts_service2_activity_delete_by_account_id_n(void);
extern int utc_contacts_service2_phone_log_reset_statistics_p(void);
extern int utc_contacts_service2_phone_log_reset_statistics_by_sim_p(void);
extern int utc_contacts_service2_phone_log_reset_statistics_by_sim_n(void);

testcase tc_array[] = {
	{"utc_contacts_service2_connect_p",utc_contacts_service2_connect_p,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_connect_on_flags_p",utc_contacts_service2_connect_on_flags_p,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_connect_on_flags_n",utc_contacts_service2_connect_on_flags_n,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_disconnect_p",utc_contacts_service2_disconnect_p,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_connect_on_thread_p",utc_contacts_service2_connect_on_thread_p,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_disconnect_on_thread_p",utc_contacts_service2_disconnect_on_thread_p,utc_contacts_service2_service_startup,utc_contacts_service2_service_cleanup},
	{"utc_contacts_service2_filter_create_p",utc_contacts_service2_filter_create_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_create_n",utc_contacts_service2_filter_create_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_destroy_p",utc_contacts_service2_filter_destroy_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_destroy_n",utc_contacts_service2_filter_destroy_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_operator_p",utc_contacts_service2_filter_add_operator_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_operator_n",utc_contacts_service2_filter_add_operator_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_filter_p",utc_contacts_service2_filter_add_filter_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_filter_n",utc_contacts_service2_filter_add_filter_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_bool_n",utc_contacts_service2_filter_add_bool_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_int_n",utc_contacts_service2_filter_add_int_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_double_n",utc_contacts_service2_filter_add_double_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_lli_n",utc_contacts_service2_filter_add_lli_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_str_n",utc_contacts_service2_filter_add_str_n,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_bool_p",utc_contacts_service2_filter_add_bool_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_int_p",utc_contacts_service2_filter_add_int_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_lli_p",utc_contacts_service2_filter_add_lli_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_filter_add_str_p",utc_contacts_service2_filter_add_str_p,utc_contacts_service2_filter_startup,utc_contacts_service2_filter_cleanup},
	{"utc_contacts_service2_person_get_default_property_p",utc_contacts_service2_person_get_default_property_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_get_default_property_n",utc_contacts_service2_person_get_default_property_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_set_default_property_p",utc_contacts_service2_person_set_default_property_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_set_default_property_n",utc_contacts_service2_person_set_default_property_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_link_person_p",utc_contacts_service2_person_link_person_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_link_person_n",utc_contacts_service2_person_link_person_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_unlink_contact_p",utc_contacts_service2_person_unlink_contact_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_unlink_contact_n",utc_contacts_service2_person_unlink_contact_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_reset_usage_p",utc_contacts_service2_person_reset_usage_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_reset_usage_n",utc_contacts_service2_person_reset_usage_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_set_favorite_order_p",utc_contacts_service2_person_set_favorite_order_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_set_favorite_order_n",utc_contacts_service2_person_set_favorite_order_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_get_aggregation_suggestions_p",utc_contacts_service2_person_get_aggregation_suggestions_p,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_person_get_aggregation_suggestions_n",utc_contacts_service2_person_get_aggregation_suggestions_n,utc_contacts_service2_person_startup,utc_contacts_service2_person_cleanup},
	{"utc_contacts_service2_group_add_contact_p",utc_contacts_service2_group_add_contact_p,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_group_add_contact_n",utc_contacts_service2_group_add_contact_n,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_group_remove_contact_p",utc_contacts_service2_group_remove_contact_p,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_group_remove_contact_n",utc_contacts_service2_group_remove_contact_n,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_group_set_group_order_p",utc_contacts_service2_group_set_group_order_p,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_group_set_group_order_n",utc_contacts_service2_group_set_group_order_n,utc_contacts_service2_group_startup,utc_contacts_service2_group_cleanup},
	{"utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_p",utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_p,utc_contacts_service2_sim_startup,utc_contacts_service2_sim_cleanup},
	{"utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_n",utc_contacts_service2_sim_get_initialization_status_by_sim_slot_no_n,utc_contacts_service2_sim_startup,utc_contacts_service2_sim_cleanup},
	{"utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_p",utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_p,utc_contacts_service2_sim_startup,utc_contacts_service2_sim_cleanup},
	{"utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_n",utc_contacts_service2_sim_import_all_contacts_by_sim_slot_no_n,utc_contacts_service2_sim_startup,utc_contacts_service2_sim_cleanup},
	{"utc_contacts_service2_setting_add_name_display_order_changed_cb_p",utc_contacts_service2_setting_add_name_display_order_changed_cb_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_add_name_display_order_changed_cb_n",utc_contacts_service2_setting_add_name_display_order_changed_cb_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_remove_name_display_order_changed_cb_p",utc_contacts_service2_setting_remove_name_display_order_changed_cb_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_remove_name_display_order_changed_cb_n",utc_contacts_service2_setting_remove_name_display_order_changed_cb_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_add_name_sorting_order_changed_cb_p",utc_contacts_service2_setting_add_name_sorting_order_changed_cb_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_add_name_sorting_order_changed_cb_n",utc_contacts_service2_setting_add_name_sorting_order_changed_cb_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_p",utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_n",utc_contacts_service2_setting_remove_name_sorting_order_changed_cb_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_get_name_display_order_p",utc_contacts_service2_setting_get_name_display_order_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_get_name_display_order_n",utc_contacts_service2_setting_get_name_display_order_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_set_name_display_order_p",utc_contacts_service2_setting_set_name_display_order_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_set_name_display_order_n",utc_contacts_service2_setting_set_name_display_order_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_get_name_sorting_order_p",utc_contacts_service2_setting_get_name_sorting_order_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_get_name_sorting_order_n",utc_contacts_service2_setting_get_name_sorting_order_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_set_name_sorting_order_p",utc_contacts_service2_setting_set_name_sorting_order_p,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_setting_set_name_sorting_order_n",utc_contacts_service2_setting_set_name_sorting_order_n,utc_contacts_service2_setting_startup,utc_contacts_service2_setting_cleanup},
	{"utc_contacts_service2_vcard_get_entity_count_p",utc_contacts_service2_vcard_get_entity_count_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_get_entity_count_n",utc_contacts_service2_vcard_get_entity_count_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_contact_p",utc_contacts_service2_vcard_make_from_contact_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_contact_n",utc_contacts_service2_vcard_make_from_contact_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_my_profile_p",utc_contacts_service2_vcard_make_from_my_profile_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_my_profile_n",utc_contacts_service2_vcard_make_from_my_profile_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_person_p",utc_contacts_service2_vcard_make_from_person_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_make_from_person_n",utc_contacts_service2_vcard_make_from_person_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_parse_to_contacts_p",utc_contacts_service2_vcard_parse_to_contacts_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_parse_to_contacts_n",utc_contacts_service2_vcard_parse_to_contacts_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_parse_to_contact_foreach_p",utc_contacts_service2_vcard_parse_to_contact_foreach_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_parse_to_contact_foreach_n",utc_contacts_service2_vcard_parse_to_contact_foreach_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_get_limit_size_of_photo_p",utc_contacts_service2_vcard_get_limit_size_of_photo_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_get_limit_size_of_photo_n",utc_contacts_service2_vcard_get_limit_size_of_photo_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_set_limit_size_of_photo_p",utc_contacts_service2_vcard_set_limit_size_of_photo_p,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_vcard_set_limit_size_of_photo_n",utc_contacts_service2_vcard_set_limit_size_of_photo_n,utc_contacts_service2_vcard_startup,utc_contacts_service2_vcard_cleanup},
	{"utc_contacts_service2_sdn_db_p",utc_contacts_service2_sdn_db_p,utc_contacts_service2_sdn_startup,utc_contacts_service2_sdn_cleanup},
	{"utc_contacts_service2_list_create_p",utc_contacts_service2_list_create_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_create_n",utc_contacts_service2_list_create_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_destroy_p",utc_contacts_service2_list_destroy_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_destroy_n",utc_contacts_service2_list_destroy_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_first_p",utc_contacts_service2_list_first_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_first_n",utc_contacts_service2_list_first_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_get_count_p",utc_contacts_service2_list_get_count_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_get_count_n",utc_contacts_service2_list_get_count_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_get_current_record_p_p",utc_contacts_service2_list_get_current_record_p_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_get_current_record_p_n",utc_contacts_service2_list_get_current_record_p_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_last_p",utc_contacts_service2_list_last_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_last_n",utc_contacts_service2_list_last_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_next_p",utc_contacts_service2_list_next_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_next_n",utc_contacts_service2_list_next_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_prev_p",utc_contacts_service2_list_prev_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_prev_n",utc_contacts_service2_list_prev_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_add_p",utc_contacts_service2_list_add_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_add_n",utc_contacts_service2_list_add_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_remove_p",utc_contacts_service2_list_remove_p,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_list_remove_n",utc_contacts_service2_list_remove_n,utc_contacts_service2_list_startup,utc_contacts_service2_list_cleanup},
	{"utc_contacts_service2_db_get_record_p",utc_contacts_service2_db_get_record_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_record_n",utc_contacts_service2_db_get_record_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_all_records_p",utc_contacts_service2_db_get_all_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_all_records_n",utc_contacts_service2_db_get_all_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_records_with_query_p",utc_contacts_service2_db_get_records_with_query_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_records_with_query_n",utc_contacts_service2_db_get_records_with_query_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_changes_by_version_p",utc_contacts_service2_db_get_changes_by_version_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_changes_by_version_n",utc_contacts_service2_db_get_changes_by_version_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_p",utc_contacts_service2_db_get_count_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_n",utc_contacts_service2_db_get_count_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_with_query_p",utc_contacts_service2_db_get_count_with_query_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_with_query_n",utc_contacts_service2_db_get_count_with_query_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_current_version_p",utc_contacts_service2_db_get_current_version_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_current_version_n",utc_contacts_service2_db_get_current_version_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_last_change_version_p",utc_contacts_service2_db_get_last_change_version_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_last_change_version_n",utc_contacts_service2_db_get_last_change_version_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_insert_record_p",utc_contacts_service2_db_insert_record_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_insert_record_n",utc_contacts_service2_db_insert_record_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_insert_records_p",utc_contacts_service2_db_insert_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_insert_records_n",utc_contacts_service2_db_insert_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_update_record_p",utc_contacts_service2_db_update_record_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_update_record_n",utc_contacts_service2_db_update_record_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_update_records_p",utc_contacts_service2_db_update_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_update_records_n",utc_contacts_service2_db_update_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_replace_record_p",utc_contacts_service2_db_replace_record_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_replace_record_n",utc_contacts_service2_db_replace_record_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_replace_records_p",utc_contacts_service2_db_replace_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_replace_records_n",utc_contacts_service2_db_replace_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_delete_record_p",utc_contacts_service2_db_delete_record_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_delete_record_n",utc_contacts_service2_db_delete_record_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_delete_records_p",utc_contacts_service2_db_delete_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_delete_records_n",utc_contacts_service2_db_delete_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_p",utc_contacts_service2_db_search_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_n",utc_contacts_service2_db_search_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_query_p",utc_contacts_service2_db_search_records_with_query_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_query_n",utc_contacts_service2_db_search_records_with_query_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_range_p",utc_contacts_service2_db_search_records_with_range_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_range_n",utc_contacts_service2_db_search_records_with_range_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_p",utc_contacts_service2_db_get_count_for_search_records_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_n",utc_contacts_service2_db_get_count_for_search_records_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_with_query_p",utc_contacts_service2_db_get_count_for_search_records_with_query_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_with_query_n",utc_contacts_service2_db_get_count_for_search_records_with_query_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_with_range_p",utc_contacts_service2_db_get_count_for_search_records_with_range_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_count_for_search_records_with_range_n",utc_contacts_service2_db_get_count_for_search_records_with_range_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_for_snippet_p",utc_contacts_service2_db_search_records_for_snippet_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_for_snippet_p",utc_contacts_service2_db_search_records_for_snippet_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_for_snippet_n",utc_contacts_service2_db_search_records_for_snippet_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_query_for_snippet_p",utc_contacts_service2_db_search_records_with_query_for_snippet_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_query_for_snippet_n",utc_contacts_service2_db_search_records_with_query_for_snippet_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_range_for_snippet_p",utc_contacts_service2_db_search_records_with_range_for_snippet_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_search_records_with_range_for_snippet_n",utc_contacts_service2_db_search_records_with_range_for_snippet_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_add_changed_cb_p",utc_contacts_service2_db_add_changed_cb_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_add_changed_cb_n",utc_contacts_service2_db_add_changed_cb_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_remove_changed_cb_p",utc_contacts_service2_db_remove_changed_cb_p,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_remove_changed_cb_n",utc_contacts_service2_db_remove_changed_cb_n,utc_contacts_service2_db_startup,utc_contacts_service2_db_cleanup},
	{"utc_contacts_service2_db_get_status_p",utc_contacts_service2_db_get_status_p,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_db_get_status_n",utc_contacts_service2_db_get_status_n,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_db_add_status_changed_cb_p",utc_contacts_service2_db_add_status_changed_cb_p,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_db_add_status_changed_cb_n",utc_contacts_service2_db_add_status_changed_cb_n,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_db_remove_status_changed_cb_p",utc_contacts_service2_db_remove_status_changed_cb_p,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_db_remove_status_changed_cb_n",utc_contacts_service2_db_remove_status_changed_cb_n,utc_contacts_service2_db_status_startup,utc_contacts_service2_db_status_cleanup},
	{"utc_contacts_service2_query_create_p",utc_contacts_service2_query_create_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_create_n",utc_contacts_service2_query_create_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_destroy_p",utc_contacts_service2_query_destroy_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_destroy_n",utc_contacts_service2_query_destroy_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_distinct_p",utc_contacts_service2_query_set_distinct_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_distinct_n",utc_contacts_service2_query_set_distinct_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_filter_p",utc_contacts_service2_query_set_filter_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_filter_n",utc_contacts_service2_query_set_filter_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_projection_p",utc_contacts_service2_query_set_projection_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_projection_n",utc_contacts_service2_query_set_projection_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_sort_p",utc_contacts_service2_query_set_sort_p,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_query_set_sort_n",utc_contacts_service2_query_set_sort_n,utc_contacts_service2_query_startup,utc_contacts_service2_query_cleanup},
	{"utc_contacts_service2_record_clone_p",utc_contacts_service2_record_clone_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_create_p",utc_contacts_service2_record_create_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_destroy_p",utc_contacts_service2_record_destroy_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_uri_p_p",utc_contacts_service2_record_get_uri_p_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_add_child_record_p",utc_contacts_service2_record_add_child_record_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_clone_child_record_list_p",utc_contacts_service2_record_clone_child_record_list_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_remove_child_record_p",utc_contacts_service2_record_remove_child_record_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_child_record_at_p_p",utc_contacts_service2_record_get_child_record_at_p_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_child_record_count_p",utc_contacts_service2_record_get_child_record_count_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_bool_p",utc_contacts_service2_record_get_bool_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_double_p",utc_contacts_service2_record_get_double_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_int_p",utc_contacts_service2_record_get_int_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_lli_p",utc_contacts_service2_record_get_lli_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_str_p",utc_contacts_service2_record_get_str_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_str_p_p",utc_contacts_service2_record_get_str_p_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_bool_p",utc_contacts_service2_record_set_bool_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_double_p",utc_contacts_service2_record_set_double_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_int_p",utc_contacts_service2_record_set_int_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_lli_p",utc_contacts_service2_record_set_lli_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_str_p",utc_contacts_service2_record_set_str_p,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_clone_n",utc_contacts_service2_record_clone_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_create_n",utc_contacts_service2_record_create_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_destroy_n",utc_contacts_service2_record_destroy_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_uri_p_n",utc_contacts_service2_record_get_uri_p_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_add_child_record_n",utc_contacts_service2_record_add_child_record_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_clone_child_record_list_n",utc_contacts_service2_record_clone_child_record_list_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_remove_child_record_n",utc_contacts_service2_record_remove_child_record_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_child_record_at_p_n",utc_contacts_service2_record_get_child_record_at_p_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_child_record_count_n",utc_contacts_service2_record_get_child_record_count_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_bool_n",utc_contacts_service2_record_get_bool_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_double_n",utc_contacts_service2_record_get_double_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_int_n",utc_contacts_service2_record_get_int_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_lli_n",utc_contacts_service2_record_get_lli_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_str_n",utc_contacts_service2_record_get_str_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_get_str_p_n",utc_contacts_service2_record_get_str_p_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_bool_n",utc_contacts_service2_record_set_bool_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_double_n",utc_contacts_service2_record_set_double_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_int_n",utc_contacts_service2_record_set_int_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_lli_n",utc_contacts_service2_record_set_lli_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_record_set_str_n",utc_contacts_service2_record_set_str_n,utc_contacts_service2_record_startup,utc_contacts_service2_record_cleanup},
	{"utc_contacts_service2_activity_delete_by_contact_id_p",utc_contacts_service2_activity_delete_by_contact_id_p,utc_contacts_service2_activity_startup,utc_contacts_service2_activity_cleanup},
	{"utc_contacts_service2_activity_delete_by_contact_id_n",utc_contacts_service2_activity_delete_by_contact_id_n,utc_contacts_service2_activity_startup,utc_contacts_service2_activity_cleanup},
	{"utc_contacts_service2_activity_delete_by_account_id_p",utc_contacts_service2_activity_delete_by_account_id_p,utc_contacts_service2_activity_startup,utc_contacts_service2_activity_cleanup},
	{"utc_contacts_service2_activity_delete_by_account_id_n",utc_contacts_service2_activity_delete_by_account_id_n,utc_contacts_service2_activity_startup,utc_contacts_service2_activity_cleanup},
	{"utc_contacts_service2_phone_log_reset_statistics_p",utc_contacts_service2_phone_log_reset_statistics_p,utc_contacts_service2_phone_log_startup,utc_contacts_service2_phone_log_cleanup},
	{"utc_contacts_service2_phone_log_reset_statistics_by_sim_p",utc_contacts_service2_phone_log_reset_statistics_by_sim_p,utc_contacts_service2_phone_log_startup,utc_contacts_service2_phone_log_cleanup},
	{"utc_contacts_service2_phone_log_reset_statistics_by_sim_n",utc_contacts_service2_phone_log_reset_statistics_by_sim_n,utc_contacts_service2_phone_log_startup,utc_contacts_service2_phone_log_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CONTACTS-SERVICE2-NATIVE_H__
