//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_METADATA-EDITOR-NATIVE_H__
#define __TCT_METADATA-EDITOR-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_metadata_editor_startup(void);
extern void utc_metadata_editor_cleanup(void);

extern int utc_metadata_editor_create_n(void);
extern int utc_metadata_editor_create_p(void);
extern int utc_metadata_editor_set_path_n(void);
extern int utc_metadata_editor_set_path_p(void);
extern int utc_metadata_editor_get_metadata_n1(void);
extern int utc_metadata_editor_get_metadata_n2(void);
extern int utc_metadata_editor_get_metadata_n3(void);
extern int utc_metadata_editor_get_metadata_n4(void);
extern int utc_metadata_editor_get_metadata_p1(void);
extern int utc_metadata_editor_get_metadata_p2(void);
extern int utc_metadata_editor_get_metadata_p3(void);
extern int utc_metadata_editor_get_metadata_p4(void);
extern int utc_metadata_editor_get_metadata_p5(void);
extern int utc_metadata_editor_get_metadata_p6(void);
extern int utc_metadata_editor_get_metadata_p7(void);
extern int utc_metadata_editor_get_metadata_p8(void);
extern int utc_metadata_editor_set_metadata_n1(void);
extern int utc_metadata_editor_set_metadata_n2(void);
extern int utc_metadata_editor_set_metadata_n3(void);
extern int utc_metadata_editor_set_metadata_n4(void);
extern int utc_metadata_editor_set_metadata_p1(void);
extern int utc_metadata_editor_set_metadata_p2(void);
extern int utc_metadata_editor_set_metadata_p3(void);
extern int utc_metadata_editor_set_metadata_p4(void);
extern int utc_metadata_editor_set_metadata_p5(void);
extern int utc_metadata_editor_set_metadata_p6(void);
extern int utc_metadata_editor_update_metadata_n(void);
extern int utc_metadata_editor_update_metadata_p1(void);
extern int utc_metadata_editor_update_metadata_p2(void);
extern int utc_metadata_editor_update_metadata_p3(void);
extern int utc_metadata_editor_update_metadata_p4(void);
extern int utc_metadata_editor_update_metadata_p5(void);
extern int utc_metadata_editor_update_metadata_p6(void);
extern int utc_metadata_editor_update_metadata_p7(void);
extern int utc_metadata_editor_update_metadata_p8(void);
extern int utc_metadata_editor_get_picture_n1(void);
extern int utc_metadata_editor_get_picture_n2(void);
extern int utc_metadata_editor_get_picture_n3(void);
extern int utc_metadata_editor_get_picture_n4(void);
extern int utc_metadata_editor_get_picture_p(void);
extern int utc_metadata_editor_append_picture_n1(void);
extern int utc_metadata_editor_append_picture_n2(void);
extern int utc_metadata_editor_append_picture_n3(void);
extern int utc_metadata_editor_append_picture_n4(void);
extern int utc_metadata_editor_append_picture_p1(void);
extern int utc_metadata_editor_append_picture_p2(void);
extern int utc_metadata_editor_append_picture_p3(void);
extern int utc_metadata_editor_append_picture_p4(void);
extern int utc_metadata_editor_append_picture_p5(void);
extern int utc_metadata_editor_append_picture_p6(void);
extern int utc_metadata_editor_append_picture_p7(void);
extern int utc_metadata_editor_remove_picture_n1(void);
extern int utc_metadata_editor_remove_picture_n2(void);
extern int utc_metadata_editor_remove_picture_n3(void);
extern int utc_metadata_editor_remove_picture_p1(void);
extern int utc_metadata_editor_remove_picture_p2(void);
extern int utc_metadata_editor_remove_picture_p3(void);
extern int utc_metadata_editor_remove_picture_p4(void);
extern int utc_metadata_editor_remove_picture_p5(void);
extern int utc_metadata_editor_remove_picture_p6(void);
extern int utc_metadata_editor_destroy_n(void);
extern int utc_metadata_editor_destroy_p(void);

testcase tc_array[] = {
	{"utc_metadata_editor_create_n",utc_metadata_editor_create_n,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_create_p",utc_metadata_editor_create_p,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_path_n",utc_metadata_editor_set_path_n,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_path_p",utc_metadata_editor_set_path_p,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_n1",utc_metadata_editor_get_metadata_n1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_n2",utc_metadata_editor_get_metadata_n2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_n3",utc_metadata_editor_get_metadata_n3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_n4",utc_metadata_editor_get_metadata_n4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p1",utc_metadata_editor_get_metadata_p1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p2",utc_metadata_editor_get_metadata_p2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p3",utc_metadata_editor_get_metadata_p3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p4",utc_metadata_editor_get_metadata_p4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p5",utc_metadata_editor_get_metadata_p5,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p6",utc_metadata_editor_get_metadata_p6,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p7",utc_metadata_editor_get_metadata_p7,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_metadata_p8",utc_metadata_editor_get_metadata_p8,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_n1",utc_metadata_editor_set_metadata_n1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_n2",utc_metadata_editor_set_metadata_n2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_n3",utc_metadata_editor_set_metadata_n3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_n4",utc_metadata_editor_set_metadata_n4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p1",utc_metadata_editor_set_metadata_p1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p2",utc_metadata_editor_set_metadata_p2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p3",utc_metadata_editor_set_metadata_p3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p4",utc_metadata_editor_set_metadata_p4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p5",utc_metadata_editor_set_metadata_p5,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_set_metadata_p6",utc_metadata_editor_set_metadata_p6,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_n",utc_metadata_editor_update_metadata_n,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p1",utc_metadata_editor_update_metadata_p1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p2",utc_metadata_editor_update_metadata_p2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p3",utc_metadata_editor_update_metadata_p3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p4",utc_metadata_editor_update_metadata_p4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p5",utc_metadata_editor_update_metadata_p5,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p6",utc_metadata_editor_update_metadata_p6,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p7",utc_metadata_editor_update_metadata_p7,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_update_metadata_p8",utc_metadata_editor_update_metadata_p8,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_picture_n1",utc_metadata_editor_get_picture_n1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_picture_n2",utc_metadata_editor_get_picture_n2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_picture_n3",utc_metadata_editor_get_picture_n3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_picture_n4",utc_metadata_editor_get_picture_n4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_get_picture_p",utc_metadata_editor_get_picture_p,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_n1",utc_metadata_editor_append_picture_n1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_n2",utc_metadata_editor_append_picture_n2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_n3",utc_metadata_editor_append_picture_n3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_n4",utc_metadata_editor_append_picture_n4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p1",utc_metadata_editor_append_picture_p1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p2",utc_metadata_editor_append_picture_p2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p3",utc_metadata_editor_append_picture_p3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p4",utc_metadata_editor_append_picture_p4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p5",utc_metadata_editor_append_picture_p5,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p6",utc_metadata_editor_append_picture_p6,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_append_picture_p7",utc_metadata_editor_append_picture_p7,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_n1",utc_metadata_editor_remove_picture_n1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_n2",utc_metadata_editor_remove_picture_n2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_n3",utc_metadata_editor_remove_picture_n3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p1",utc_metadata_editor_remove_picture_p1,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p2",utc_metadata_editor_remove_picture_p2,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p3",utc_metadata_editor_remove_picture_p3,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p4",utc_metadata_editor_remove_picture_p4,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p5",utc_metadata_editor_remove_picture_p5,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_remove_picture_p6",utc_metadata_editor_remove_picture_p6,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_destroy_n",utc_metadata_editor_destroy_n,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{"utc_metadata_editor_destroy_p",utc_metadata_editor_destroy_p,utc_metadata_editor_startup,utc_metadata_editor_cleanup},
	{NULL, NULL}
};

#endif // __TCT_METADATA-EDITOR-NATIVE_H__
