//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_MULTI-ASSISTANT-NATIVE_H__
#define __TCT_MULTI-ASSISTANT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_multi_assistant_startup(void);
extern void utc_multi_assistant_cleanup(void);

extern int utc_ma_initialize_p(void);
extern int utc_ma_deinitialize_p(void);
extern int utc_ma_deinitialize_n(void);
extern int utc_ma_prepare_p(void);
extern int utc_ma_prepare_n(void);
extern int utc_ma_unprepare_p(void);
extern int utc_ma_unprepare_n(void);
extern int utc_ma_get_state_p(void);
extern int utc_ma_get_state_n1(void);
extern int utc_ma_get_state_n2(void);
extern int utc_ma_get_current_language_p(void);
extern int utc_ma_get_current_language_n(void);
extern int utc_ma_get_recording_audio_format_p(void);
extern int utc_ma_get_recording_audio_format_n1(void);
extern int utc_ma_get_recording_audio_format_n2(void);
extern int utc_ma_set_state_changed_cb_p(void);
extern int utc_ma_set_state_changed_cb_n1(void);
extern int utc_ma_set_state_changed_cb_n2(void);
extern int utc_ma_unset_state_changed_cb_p(void);
extern int utc_ma_unset_state_changed_cb_n(void);
extern int utc_ma_set_error_cb_p(void);
extern int utc_ma_set_error_cb_n1(void);
extern int utc_ma_set_error_cb_n2(void);
extern int utc_ma_unset_error_cb_p(void);
extern int utc_ma_unset_error_cb_n(void);
extern int utc_ma_set_language_changed_cb_p(void);
extern int utc_ma_set_language_changed_cb_n1(void);
extern int utc_ma_set_language_changed_cb_n2(void);
extern int utc_ma_unset_language_changed_cb_p(void);
extern int utc_ma_unset_language_changed_cb_n(void);
extern int utc_ma_set_audio_streaming_cb_p(void);
extern int utc_ma_set_audio_streaming_cb_n1(void);
extern int utc_ma_set_audio_streaming_cb_n2(void);
extern int utc_ma_unset_audio_streaming_cb_p(void);
extern int utc_ma_unset_audio_streaming_cb_n(void);
extern int utc_ma_send_asr_result_p(void);
extern int utc_ma_send_asr_result_n1(void);
extern int utc_ma_send_asr_result_n2(void);
extern int utc_ma_send_result_p(void);
extern int utc_ma_send_result_n(void);
extern int utc_ma_send_recognition_result_p(void);
extern int utc_ma_send_recognition_result_n(void);
extern int utc_ma_set_active_state_changed_cb_p(void);
extern int utc_ma_set_active_state_changed_cb_n1(void);
extern int utc_ma_set_active_state_changed_cb_n2(void);
extern int utc_ma_unset_active_state_changed_cb_p(void);
extern int utc_ma_unset_active_state_changed_cb_n(void);
extern int utc_ma_start_receiving_audio_streaming_data_p(void);
extern int utc_ma_start_receiving_audio_streaming_data_n(void);
extern int utc_ma_stop_receiving_audio_streaming_data_p(void);
extern int utc_ma_stop_receiving_audio_streaming_data_n(void);
extern int utc_ma_update_voice_feedback_state_p(void);
extern int utc_ma_update_voice_feedback_state_n(void);
extern int utc_ma_send_assistant_specific_command_p(void);
extern int utc_ma_send_assistant_specific_command_n(void);
extern int utc_ma_set_wakeup_engine_command_cb_p(void);
extern int utc_ma_set_wakeup_engine_command_cb_n1(void);
extern int utc_ma_set_wakeup_engine_command_cb_n2(void);
extern int utc_ma_unset_wakeup_engine_command_cb_p(void);
extern int utc_ma_unset_wakeup_engine_command_cb_n(void);
extern int utc_ma_assistant_info_foreach_assistants_p(void);
extern int utc_ma_assistant_info_foreach_assistants_n(void);
extern int utc_ma_assistant_info_get_app_id_p(void);
extern int utc_ma_assistant_info_get_app_id_n(void);
extern int utc_ma_assistant_info_get_enabled_status_p(void);
extern int utc_ma_assistant_info_get_enabled_status_n(void);
extern int utc_ma_get_recording_audio_source_type_p(void);
extern int utc_ma_get_recording_audio_source_type_n1(void);
extern int utc_ma_get_recording_audio_source_type_n2(void);
extern int utc_ma_set_background_volume_p(void);
extern int utc_ma_set_background_volume_n(void);
extern int utc_ma_set_preprocessing_allow_mode_p(void);
extern int utc_ma_set_preprocessing_allow_mode_n(void);
extern int utc_ma_set_preprocessing_information_changed_cb_p(void);
extern int utc_ma_set_preprocessing_information_changed_cb_n1(void);
extern int utc_ma_set_preprocessing_information_changed_cb_n2(void);
extern int utc_ma_unset_preprocessing_information_changed_cb_p(void);
extern int utc_ma_unset_preprocessing_information_changed_cb_n(void);
extern int utc_ma_send_preprocessing_result_p(void);
extern int utc_ma_send_preprocessing_result_n(void);
extern int utc_ma_set_wake_word_audio_require_flag_p(void);
extern int utc_ma_set_wake_word_audio_require_flag_n(void);
extern int utc_ma_set_audio_streaming_data_section_changed_cb_p(void);
extern int utc_ma_set_audio_streaming_data_section_changed_cb_n1(void);
extern int utc_ma_set_audio_streaming_data_section_changed_cb_n2(void);
extern int utc_ma_unset_audio_streaming_data_section_changed_cb_p(void);
extern int utc_ma_unset_audio_streaming_data_section_changed_cb_n(void);
extern int utc_ma_set_assistant_wakeup_language_p(void);
extern int utc_ma_set_assistant_wakeup_language_n(void);
extern int utc_ma_set_service_state_changed_cb_p(void);
extern int utc_ma_set_service_state_changed_cb_n(void);
extern int utc_ma_unset_service_state_changed_cb_p(void);
extern int utc_ma_unset_service_state_changed_cb_n(void);
extern int utc_ma_set_voice_key_status_changed_cb_p(void);
extern int utc_ma_set_voice_key_status_changed_cb_n(void);
extern int utc_ma_unset_voice_key_status_changed_cb_p(void);
extern int utc_ma_unset_voice_key_status_changed_cb_n(void);
extern int utc_ma_add_wake_word_p(void);
extern int utc_ma_add_wake_word_n1(void);
extern int utc_ma_add_wake_word_n2(void);
extern int utc_ma_remove_wake_word_p(void);
extern int utc_ma_remove_wake_word_n1(void);
extern int utc_ma_remove_wake_word_n2(void);

testcase tc_array[] = {
	{"utc_ma_initialize_p",utc_ma_initialize_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_deinitialize_p",utc_ma_deinitialize_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_deinitialize_n",utc_ma_deinitialize_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_prepare_p",utc_ma_prepare_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_prepare_n",utc_ma_prepare_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unprepare_p",utc_ma_unprepare_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unprepare_n",utc_ma_unprepare_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_state_p",utc_ma_get_state_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_state_n1",utc_ma_get_state_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_state_n2",utc_ma_get_state_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_current_language_p",utc_ma_get_current_language_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_current_language_n",utc_ma_get_current_language_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_format_p",utc_ma_get_recording_audio_format_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_format_n1",utc_ma_get_recording_audio_format_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_format_n2",utc_ma_get_recording_audio_format_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_state_changed_cb_p",utc_ma_set_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_state_changed_cb_n1",utc_ma_set_state_changed_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_state_changed_cb_n2",utc_ma_set_state_changed_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_state_changed_cb_p",utc_ma_unset_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_state_changed_cb_n",utc_ma_unset_state_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_error_cb_p",utc_ma_set_error_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_error_cb_n1",utc_ma_set_error_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_error_cb_n2",utc_ma_set_error_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_error_cb_p",utc_ma_unset_error_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_error_cb_n",utc_ma_unset_error_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_language_changed_cb_p",utc_ma_set_language_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_language_changed_cb_n1",utc_ma_set_language_changed_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_language_changed_cb_n2",utc_ma_set_language_changed_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_language_changed_cb_p",utc_ma_unset_language_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_language_changed_cb_n",utc_ma_unset_language_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_cb_p",utc_ma_set_audio_streaming_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_cb_n1",utc_ma_set_audio_streaming_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_cb_n2",utc_ma_set_audio_streaming_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_audio_streaming_cb_p",utc_ma_unset_audio_streaming_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_audio_streaming_cb_n",utc_ma_unset_audio_streaming_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_asr_result_p",utc_ma_send_asr_result_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_asr_result_n1",utc_ma_send_asr_result_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_asr_result_n2",utc_ma_send_asr_result_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_result_p",utc_ma_send_result_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_result_n",utc_ma_send_result_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_recognition_result_p",utc_ma_send_recognition_result_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_recognition_result_n",utc_ma_send_recognition_result_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_active_state_changed_cb_p",utc_ma_set_active_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_active_state_changed_cb_n1",utc_ma_set_active_state_changed_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_active_state_changed_cb_n2",utc_ma_set_active_state_changed_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_active_state_changed_cb_p",utc_ma_unset_active_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_active_state_changed_cb_n",utc_ma_unset_active_state_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_start_receiving_audio_streaming_data_p",utc_ma_start_receiving_audio_streaming_data_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_start_receiving_audio_streaming_data_n",utc_ma_start_receiving_audio_streaming_data_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_stop_receiving_audio_streaming_data_p",utc_ma_stop_receiving_audio_streaming_data_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_stop_receiving_audio_streaming_data_n",utc_ma_stop_receiving_audio_streaming_data_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_update_voice_feedback_state_p",utc_ma_update_voice_feedback_state_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_update_voice_feedback_state_n",utc_ma_update_voice_feedback_state_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_assistant_specific_command_p",utc_ma_send_assistant_specific_command_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_assistant_specific_command_n",utc_ma_send_assistant_specific_command_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_wakeup_engine_command_cb_p",utc_ma_set_wakeup_engine_command_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_wakeup_engine_command_cb_n1",utc_ma_set_wakeup_engine_command_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_wakeup_engine_command_cb_n2",utc_ma_set_wakeup_engine_command_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_wakeup_engine_command_cb_p",utc_ma_unset_wakeup_engine_command_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_wakeup_engine_command_cb_n",utc_ma_unset_wakeup_engine_command_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_foreach_assistants_p",utc_ma_assistant_info_foreach_assistants_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_foreach_assistants_n",utc_ma_assistant_info_foreach_assistants_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_get_app_id_p",utc_ma_assistant_info_get_app_id_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_get_app_id_n",utc_ma_assistant_info_get_app_id_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_get_enabled_status_p",utc_ma_assistant_info_get_enabled_status_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_assistant_info_get_enabled_status_n",utc_ma_assistant_info_get_enabled_status_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_source_type_p",utc_ma_get_recording_audio_source_type_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_source_type_n1",utc_ma_get_recording_audio_source_type_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_get_recording_audio_source_type_n2",utc_ma_get_recording_audio_source_type_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_background_volume_p",utc_ma_set_background_volume_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_background_volume_n",utc_ma_set_background_volume_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_preprocessing_allow_mode_p",utc_ma_set_preprocessing_allow_mode_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_preprocessing_allow_mode_n",utc_ma_set_preprocessing_allow_mode_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_preprocessing_information_changed_cb_p",utc_ma_set_preprocessing_information_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_preprocessing_information_changed_cb_n1",utc_ma_set_preprocessing_information_changed_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_preprocessing_information_changed_cb_n2",utc_ma_set_preprocessing_information_changed_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_preprocessing_information_changed_cb_p",utc_ma_unset_preprocessing_information_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_preprocessing_information_changed_cb_n",utc_ma_unset_preprocessing_information_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_preprocessing_result_p",utc_ma_send_preprocessing_result_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_send_preprocessing_result_n",utc_ma_send_preprocessing_result_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_wake_word_audio_require_flag_p",utc_ma_set_wake_word_audio_require_flag_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_wake_word_audio_require_flag_n",utc_ma_set_wake_word_audio_require_flag_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_data_section_changed_cb_p",utc_ma_set_audio_streaming_data_section_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_data_section_changed_cb_n1",utc_ma_set_audio_streaming_data_section_changed_cb_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_audio_streaming_data_section_changed_cb_n2",utc_ma_set_audio_streaming_data_section_changed_cb_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_audio_streaming_data_section_changed_cb_p",utc_ma_unset_audio_streaming_data_section_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_audio_streaming_data_section_changed_cb_n",utc_ma_unset_audio_streaming_data_section_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_assistant_wakeup_language_p",utc_ma_set_assistant_wakeup_language_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_assistant_wakeup_language_n",utc_ma_set_assistant_wakeup_language_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_service_state_changed_cb_p",utc_ma_set_service_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_service_state_changed_cb_n",utc_ma_set_service_state_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_service_state_changed_cb_p",utc_ma_unset_service_state_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_service_state_changed_cb_n",utc_ma_unset_service_state_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_voice_key_status_changed_cb_p",utc_ma_set_voice_key_status_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_set_voice_key_status_changed_cb_n",utc_ma_set_voice_key_status_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_voice_key_status_changed_cb_p",utc_ma_unset_voice_key_status_changed_cb_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_unset_voice_key_status_changed_cb_n",utc_ma_unset_voice_key_status_changed_cb_n,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_add_wake_word_p",utc_ma_add_wake_word_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_add_wake_word_n1",utc_ma_add_wake_word_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_add_wake_word_n2",utc_ma_add_wake_word_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_remove_wake_word_p",utc_ma_remove_wake_word_p,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_remove_wake_word_n1",utc_ma_remove_wake_word_n1,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{"utc_ma_remove_wake_word_n2",utc_ma_remove_wake_word_n2,utc_multi_assistant_startup,utc_multi_assistant_cleanup},
	{NULL, NULL}
};

#endif // __TCT_MULTI-ASSISTANT-NATIVE_H__
