//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAPI-MESSAGE-PORT-NATIVE_H__
#define __TCT_CAPI-MESSAGE-PORT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_capi_message_port_startup(void);
extern void utc_capi_message_port_cleanup(void);

extern int utc_capi_message_port_register_local_port_n01(void);
extern int utc_capi_message_port_register_local_port_n02(void);
extern int utc_capi_message_port_register_local_port_p01(void);
extern int utc_capi_message_port_register_trusted_local_port_n01(void);
extern int utc_capi_message_port_register_trusted_local_port_n02(void);
extern int utc_capi_message_port_register_trusted_local_port_p01(void);
extern int utc_capi_message_port_unregister_local_port_n01(void);
extern int utc_capi_message_port_unregister_local_port_n02(void);
extern int utc_capi_message_port_unregister_local_port_p01(void);
extern int utc_capi_message_port_unregister_trusted_local_port_n01(void);
extern int utc_capi_message_port_unregister_trusted_local_port_n02(void);
extern int utc_capi_message_port_unregister_trusted_local_port_p01(void);
extern int utc_capi_message_port_check_remote_port_p01(void);
extern int utc_capi_message_port_check_remote_port_p02(void);
extern int utc_capi_message_port_check_remote_port_p03(void);
extern int utc_capi_message_port_check_remote_port_n01(void);
extern int utc_capi_message_port_check_remote_port_n02(void);
extern int utc_capi_message_port_check_remote_port_n03(void);
extern int utc_capi_message_port_check_trusted_remote_port_p01(void);
extern int utc_capi_message_port_check_trusted_remote_port_p02(void);
extern int utc_capi_message_port_check_trusted_remote_port_n01(void);
extern int utc_capi_message_port_check_trusted_remote_port_n02(void);
extern int utc_capi_message_port_send_message_p01(void);
extern int utc_capi_message_port_send_message_n01(void);
extern int utc_capi_message_port_send_message_n02(void);
extern int utc_capi_message_port_send_message_n03(void);
extern int utc_capi_message_port_send_message_n04(void);
extern int utc_capi_message_port_send_message_n05(void);
extern int utc_capi_message_port_send_trusted_message_p01(void);
extern int utc_capi_message_port_send_trusted_message_n01(void);
extern int utc_capi_message_port_send_trusted_message_n02(void);
extern int utc_capi_message_port_send_trusted_message_n03(void);
extern int utc_capi_message_port_send_trusted_message_n04(void);
extern int utc_capi_message_port_send_trusted_message_n05(void);
extern int utc_capi_message_port_send_trusted_message_n06(void);
extern int utc_capi_message_port_send_message_with_local_port_p01(void);
extern int utc_capi_message_port_send_message_with_local_port_p02(void);
extern int utc_capi_message_port_send_message_with_local_port_n01(void);
extern int utc_capi_message_port_send_message_with_local_port_n02(void);
extern int utc_capi_message_port_send_message_with_local_port_n03(void);
extern int utc_capi_message_port_send_message_with_local_port_n04(void);
extern int utc_capi_message_port_send_message_with_local_port_n05(void);
extern int utc_capi_message_port_send_message_with_local_port_n06(void);
extern int utc_capi_message_port_send_message_with_local_port_n07(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_p01(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n01(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n02(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n03(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n04(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n05(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n06(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n07(void);
extern int utc_capi_message_port_send_trusted_message_with_local_port_n08(void);
extern int utc_capi_message_port_add_registered_cb_p01(void);
extern int utc_capi_message_port_add_registered_cb_n01(void);
extern int utc_capi_message_port_add_unregistered_cb_p01(void);
extern int utc_capi_message_port_add_unregistered_cb_n01(void);
extern int utc_capi_message_port_remove_registration_event_cb_p01(void);
extern int utc_capi_message_port_remove_registration_event_cb_n01(void);

testcase tc_array[] = {
	{"utc_capi_message_port_register_local_port_n01",utc_capi_message_port_register_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_register_local_port_n02",utc_capi_message_port_register_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_register_local_port_p01",utc_capi_message_port_register_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_register_trusted_local_port_n01",utc_capi_message_port_register_trusted_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_register_trusted_local_port_n02",utc_capi_message_port_register_trusted_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_register_trusted_local_port_p01",utc_capi_message_port_register_trusted_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_local_port_n01",utc_capi_message_port_unregister_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_local_port_n02",utc_capi_message_port_unregister_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_local_port_p01",utc_capi_message_port_unregister_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_trusted_local_port_n01",utc_capi_message_port_unregister_trusted_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_trusted_local_port_n02",utc_capi_message_port_unregister_trusted_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_unregister_trusted_local_port_p01",utc_capi_message_port_unregister_trusted_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_p01",utc_capi_message_port_check_remote_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_p02",utc_capi_message_port_check_remote_port_p02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_p03",utc_capi_message_port_check_remote_port_p03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_n01",utc_capi_message_port_check_remote_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_n02",utc_capi_message_port_check_remote_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_remote_port_n03",utc_capi_message_port_check_remote_port_n03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_trusted_remote_port_p01",utc_capi_message_port_check_trusted_remote_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_trusted_remote_port_p02",utc_capi_message_port_check_trusted_remote_port_p02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_trusted_remote_port_n01",utc_capi_message_port_check_trusted_remote_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_check_trusted_remote_port_n02",utc_capi_message_port_check_trusted_remote_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_p01",utc_capi_message_port_send_message_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_n01",utc_capi_message_port_send_message_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_n02",utc_capi_message_port_send_message_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_n03",utc_capi_message_port_send_message_n03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_n04",utc_capi_message_port_send_message_n04,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_n05",utc_capi_message_port_send_message_n05,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_p01",utc_capi_message_port_send_trusted_message_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n01",utc_capi_message_port_send_trusted_message_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n02",utc_capi_message_port_send_trusted_message_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n03",utc_capi_message_port_send_trusted_message_n03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n04",utc_capi_message_port_send_trusted_message_n04,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n05",utc_capi_message_port_send_trusted_message_n05,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_n06",utc_capi_message_port_send_trusted_message_n06,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_p01",utc_capi_message_port_send_message_with_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_p02",utc_capi_message_port_send_message_with_local_port_p02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n01",utc_capi_message_port_send_message_with_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n02",utc_capi_message_port_send_message_with_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n03",utc_capi_message_port_send_message_with_local_port_n03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n04",utc_capi_message_port_send_message_with_local_port_n04,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n05",utc_capi_message_port_send_message_with_local_port_n05,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n06",utc_capi_message_port_send_message_with_local_port_n06,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_message_with_local_port_n07",utc_capi_message_port_send_message_with_local_port_n07,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_p01",utc_capi_message_port_send_trusted_message_with_local_port_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n01",utc_capi_message_port_send_trusted_message_with_local_port_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n02",utc_capi_message_port_send_trusted_message_with_local_port_n02,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n03",utc_capi_message_port_send_trusted_message_with_local_port_n03,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n04",utc_capi_message_port_send_trusted_message_with_local_port_n04,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n05",utc_capi_message_port_send_trusted_message_with_local_port_n05,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n06",utc_capi_message_port_send_trusted_message_with_local_port_n06,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n07",utc_capi_message_port_send_trusted_message_with_local_port_n07,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_send_trusted_message_with_local_port_n08",utc_capi_message_port_send_trusted_message_with_local_port_n08,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_add_registered_cb_p01",utc_capi_message_port_add_registered_cb_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_add_registered_cb_n01",utc_capi_message_port_add_registered_cb_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_add_unregistered_cb_p01",utc_capi_message_port_add_unregistered_cb_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_add_unregistered_cb_n01",utc_capi_message_port_add_unregistered_cb_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_remove_registration_event_cb_p01",utc_capi_message_port_remove_registration_event_cb_p01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{"utc_capi_message_port_remove_registration_event_cb_n01",utc_capi_message_port_remove_registration_event_cb_n01,utc_capi_message_port_startup,utc_capi_message_port_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CAPI-MESSAGE-PORT-NATIVE_H__
