/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __TCT_WATCHFACE_COMPLICATION_NATIVE_H__
#define __TCT_WATCHFACE_COMPLICATION_NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_watchface_complication_startup(void);
extern void utc_watchface_complication_cleanup(void);
extern int utc_watchface_complication_get_current_provider_id_p(void);
extern int utc_watchface_complication_get_current_provider_id_n1(void);
extern int utc_watchface_complication_get_current_type_p(void);
extern int utc_watchface_complication_get_current_type_n1(void);
extern int utc_watchface_complication_add_updated_cb_p(void);
extern int utc_watchface_complication_add_updated_cb_n1(void);
extern int utc_watchface_complication_remove_updated_cb_p(void);
extern int utc_watchface_complication_remove_updated_cb_n1(void);
extern int utc_watchface_complication_send_update_request_p(void);
extern int utc_watchface_complication_send_update_request_n1(void);
extern int utc_watchface_complication_create_p(void);
extern int utc_watchface_complication_create_n1(void);
extern int utc_watchface_complication_destroy_p(void);
extern int utc_watchface_complication_destroy_n1(void);
extern int utc_watchface_complication_data_get_type_n1(void);
extern int utc_watchface_complication_data_get_short_text_p1(void);
extern int utc_watchface_complication_data_get_short_text_n1(void);
extern int utc_watchface_complication_data_get_long_text_p1(void);
extern int utc_watchface_complication_data_get_long_text_n1(void);
extern int utc_watchface_complication_data_get_title_p1(void);
extern int utc_watchface_complication_data_get_title_n1(void);
extern int utc_watchface_complication_data_get_timestamp_p1(void);
extern int utc_watchface_complication_data_get_timestamp_n1(void);
extern int utc_watchface_complication_data_get_image_path_p1(void);
extern int utc_watchface_complication_data_get_image_path_n1(void);
extern int utc_watchface_complication_data_get_ranged_value_p1(void);
extern int utc_watchface_complication_data_get_ranged_value_n1(void);
extern int utc_watchface_complication_data_get_icon_path_p1(void);
extern int utc_watchface_complication_data_get_icon_path_n1(void);
extern int utc_watchface_complication_data_get_extra_data_p1(void);
extern int utc_watchface_complication_data_get_extra_data_n1(void);
extern int utc_watchface_complication_data_get_screen_reader_text_p(void);
extern int utc_watchface_complication_data_get_screen_reader_text_n1(void);
extern int utc_watchface_complication_data_get_screen_reader_text_n2(void);
extern int utc_watchface_complication_allowed_list_create_p(void);
extern int utc_watchface_complication_allowed_list_create_n1(void);
extern int utc_watchface_complication_allowed_list_destroy_p(void);
extern int utc_watchface_complication_allowed_list_destroy_n1(void);
extern int utc_watchface_complication_allowed_list_add_p(void);
extern int utc_watchface_complication_allowed_list_add_n1(void);
extern int utc_watchface_complication_allowed_list_add_n2(void);
extern int utc_watchface_complication_allowed_list_get_nth_p(void);
extern int utc_watchface_complication_allowed_list_get_nth_n1(void);
extern int utc_watchface_complication_allowed_list_delete_p(void);
extern int utc_watchface_complication_allowed_list_delete_n1(void);
extern int utc_watchface_complication_allowed_list_delete_n2(void);
extern int utc_watchface_complication_allowed_list_apply_p(void);
extern int utc_watchface_complication_allowed_list_apply_n1(void);
extern int utc_watchface_complication_allowed_list_clear_p(void);
extern int utc_watchface_complication_allowed_list_clear_n1(void);
extern int utc_watchface_complication_transfer_event_p(void);
extern int utc_watchface_complication_transfer_event_n1(void);
extern int utc_watchface_complication_transfer_event_n2(void);
extern int utc_watchface_complication_data_get_timeinfo_p(void);
extern int utc_watchface_complication_data_get_timeinfo_n(void);
extern int utc_watchface_complication_timeinfo_get_timezone_p(void);
extern int utc_watchface_complication_timeinfo_get_timezone_n(void);
extern int utc_watchface_complication_timeinfo_get_timezone_id_p(void);
extern int utc_watchface_complication_timeinfo_get_timezone_id_n(void);
extern int utc_watchface_complication_timeinfo_get_timezone_country_p(void);
extern int utc_watchface_complication_timeinfo_get_timezone_country_n(void);
extern int utc_watchface_complication_timeinfo_get_timezone_city_p(void);
extern int utc_watchface_complication_timeinfo_get_timezone_city_n(void);
extern int utc_watchface_complication_timeinfo_get_timestamp_p(void);
extern int utc_watchface_complication_timeinfo_get_timestamp_n(void);

extern void utc_watchface_complication_provider_startup(void);
extern void utc_watchface_complication_provider_cleanup(void);
extern int utc_watchface_complication_provider_add_update_requested_cb_p(void);
extern int utc_watchface_complication_provider_add_update_requested_cb_n1(void);
extern int utc_watchface_complication_provider_remove_update_requested_cb_p(void);
extern int utc_watchface_complication_provider_remove_update_requested_cb_n1(void);
extern int utc_watchface_complication_provider_notify_update_p(void);
extern int utc_watchface_complication_provider_notify_update_n1(void);
extern void _utc_watchface_complication_provider_setup_is_editing_p_checker(void);
extern int utc_watchface_complication_provider_setup_is_editing_p(void);
extern int utc_watchface_complication_provider_setup_is_editing_n1(void);
extern void _utc_watchface_complication_provider_setup_reply_to_editor_p_checker(void);
extern int utc_watchface_complication_provider_setup_reply_to_editor_p(void);
extern int utc_watchface_complication_provider_setup_reply_to_editor_n1(void);
extern void _utc_watchface_complication_provider_setup_get_context_p_checker(void);
extern int utc_watchface_complication_provider_setup_get_context_p(void);
extern int utc_watchface_complication_provider_setup_get_context_n1(void);
extern int utc_watchface_complication_provider_data_set_short_text_p(void);
extern int utc_watchface_complication_provider_data_set_short_text_n1(void);
extern int utc_watchface_complication_provider_data_set_long_text_p(void);
extern int utc_watchface_complication_provider_data_set_long_text_n1(void);
extern int utc_watchface_complication_provider_data_set_title_p(void);
extern int utc_watchface_complication_provider_data_set_title_n1(void);
extern int utc_watchface_complication_provider_data_set_timestamp_p(void);
extern int utc_watchface_complication_provider_data_set_timestamp_n1(void);
extern int utc_watchface_complication_provider_data_set_image_path_p(void);
extern int utc_watchface_complication_provider_data_set_image_path_n1(void);
extern int utc_watchface_complication_provider_data_set_ranged_value_p(void);
extern int utc_watchface_complication_provider_data_set_ranged_value_n1(void);
extern int utc_watchface_complication_provider_data_set_icon_path_p(void);
extern int utc_watchface_complication_provider_data_set_icon_path_n1(void);
extern int utc_watchface_complication_provider_data_set_extra_data_p(void);
extern int utc_watchface_complication_provider_data_set_extra_data_n1(void);
extern int utc_watchface_complication_provider_data_is_valid_p(void);
extern int utc_watchface_complication_provider_data_is_valid_n1(void);
extern int utc_watchface_complication_provider_data_is_valid_n2(void);
extern int utc_watchface_complication_provider_event_get_type_p(void);
extern int utc_watchface_complication_provider_event_get_type_n1(void);
extern int utc_watchface_complication_provider_event_get_provider_id_p(void);
extern int utc_watchface_complication_provider_event_get_provider_id_n1(void);
extern int utc_watchface_complication_provider_event_get_complication_type_p(void);
extern int utc_watchface_complication_provider_event_get_complication_type_n1(void);
extern int utc_watchface_complication_provider_event_get_context_p(void);
extern int utc_watchface_complication_provider_event_get_context_n1(void);
extern int utc_watchface_complication_provider_timeinfo_create_p1(void);
extern int utc_watchface_complication_provider_timeinfo_create_n1(void);
extern int utc_watchface_complication_provider_timeinfo_destroy_p1(void);
extern int utc_watchface_complication_provider_timeinfo_destroy_n1(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_p(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_n1(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_id_p(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_id_n1(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_country_p(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_country_n1(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_city_p(void);
extern int utc_watchface_complication_provider_timeinfo_set_timezone_city_n1(void);
extern void __utc_watchface_complication_provider_event_get_type_p_checker(void);
extern void __utc_watchface_complication_provider_event_get_provider_id_p_checker(void);
extern void __utc_watchface_complication_provider_event_get_complication_type_p_checker(void);
extern void __utc_watchface_complication_provider_event_get_context_p_checker(void);

extern void utc_watchface_editable_startup(void);
extern void utc_watchface_editable_cleanup(void);
extern int utc_watchface_editable_candidates_list_create_n(void);
extern int utc_watchface_editable_candidates_list_create_p(void);
extern int utc_watchface_editable_candidates_list_add_n1(void);
extern int utc_watchface_editable_candidates_list_add_n2(void);
extern int utc_watchface_editable_candidates_list_add_p(void);
extern int utc_watchface_editable_candidates_list_destroy_n(void);
extern int utc_watchface_editable_candidates_list_destroy_p(void);
extern int utc_watchface_editable_add_design_element_n1(void);
extern int utc_watchface_editable_add_design_element_n2(void);
extern int utc_watchface_editable_add_design_element_n3(void);
extern int utc_watchface_editable_add_design_element_p(void);
extern int utc_watchface_editable_add_complication_n1(void);
extern int utc_watchface_editable_add_complication_n2(void);
extern int utc_watchface_editable_add_complication_p(void);
extern int utc_watchface_editable_request_edit_n1(void);
extern int utc_watchface_editable_request_edit_n2(void);
extern int utc_watchface_editable_request_edit_p(void);
extern int utc_watchface_editable_add_edit_ready_cb_n(void);
extern int utc_watchface_editable_add_edit_ready_cb_p(void);
extern int utc_watchface_editable_remove_edit_ready_cb_n(void);
extern int utc_watchface_editable_remove_edit_ready_cb_p(void);
extern int utc_watchface_editable_get_editable_name_n1(void);
extern int utc_watchface_editable_get_editable_name_n2(void);
extern int utc_watchface_editable_get_editable_name_p(void);
extern int utc_watchface_editable_set_editable_name_n1(void);
extern int utc_watchface_editable_set_editable_name_n2(void);
extern int utc_watchface_editable_set_editable_name_p(void);
extern int utc_watchface_editable_get_nth_data_n1(void);
extern int utc_watchface_editable_get_nth_data_n2(void);
extern int utc_watchface_editable_get_nth_data_p(void);
extern int utc_watchface_editable_get_current_data_n1(void);
extern int utc_watchface_editable_get_current_data_n2(void);
extern int utc_watchface_editable_get_current_data_p(void);
extern int utc_watchface_editable_get_current_data_idx_n1(void);
extern int utc_watchface_editable_get_current_data_idx_n2(void);
extern int utc_watchface_editable_get_current_data_idx_p(void);
extern int utc_watchface_editable_get_editable_id_n1(void);
extern int utc_watchface_editable_get_editable_id_n2(void);
extern int utc_watchface_editable_get_editable_id_p(void);
extern int utc_watchface_editable_get_highlight_n1(void);
extern int utc_watchface_editable_get_highlight_n2(void);
extern int utc_watchface_editable_get_highlight_p(void);
extern int utc_watchface_editable_load_current_data_n(void);
extern int utc_watchface_editable_load_current_data_p(void);
extern int utc_watchface_editable_highlight_create_n(void);
extern int utc_watchface_editable_highlight_create_p(void);
extern int utc_watchface_editable_highlight_destroy_n(void);
extern int utc_watchface_editable_highlight_destroy_p(void);
extern int utc_watchface_editable_highlight_set_geometry_n(void);
extern int utc_watchface_editable_highlight_set_geometry_p(void);
extern int utc_watchface_editable_highlight_get_geometry_n1(void);
extern int utc_watchface_editable_highlight_get_geometry_n2(void);
extern int utc_watchface_editable_highlight_get_geometry_n3(void);
extern int utc_watchface_editable_highlight_get_geometry_n4(void);
extern int utc_watchface_editable_highlight_get_geometry_n5(void);
extern int utc_watchface_editable_highlight_get_geometry_p(void);
extern int utc_watchface_editable_highlight_set_shape_type_p(void);
extern int utc_watchface_editable_highlight_set_shape_type_n1(void);
extern int utc_watchface_editable_highlight_set_shape_type_n2(void);
extern int utc_watchface_editable_highlight_get_shape_type_p(void);
extern int utc_watchface_editable_highlight_get_shape_type_n1(void);
extern int utc_watchface_editable_highlight_get_shape_type_n2(void);

testcase tc_array[] = {
	{"utc_watchface_complication_get_current_provider_id_p",utc_watchface_complication_get_current_provider_id_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_get_current_provider_id_n1",utc_watchface_complication_get_current_provider_id_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_get_current_type_p",utc_watchface_complication_get_current_type_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_get_current_type_n1",utc_watchface_complication_get_current_type_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_add_updated_cb_p",utc_watchface_complication_add_updated_cb_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_add_updated_cb_n1",utc_watchface_complication_add_updated_cb_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_remove_updated_cb_p",utc_watchface_complication_remove_updated_cb_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_remove_updated_cb_n1",utc_watchface_complication_remove_updated_cb_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_send_update_request_p",utc_watchface_complication_send_update_request_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_send_update_request_n1",utc_watchface_complication_send_update_request_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_create_p",utc_watchface_complication_create_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_create_n1",utc_watchface_complication_create_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_destroy_p",utc_watchface_complication_destroy_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_destroy_n1",utc_watchface_complication_destroy_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_type_n1",utc_watchface_complication_data_get_type_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_short_text_p1",utc_watchface_complication_data_get_short_text_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_short_text_n1",utc_watchface_complication_data_get_short_text_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_long_text_p1",utc_watchface_complication_data_get_long_text_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_long_text_n1",utc_watchface_complication_data_get_long_text_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_title_p1",utc_watchface_complication_data_get_title_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_title_n1",utc_watchface_complication_data_get_title_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_timestamp_p1",utc_watchface_complication_data_get_timestamp_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_timestamp_n1",utc_watchface_complication_data_get_timestamp_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_image_path_p1",utc_watchface_complication_data_get_image_path_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_image_path_n1",utc_watchface_complication_data_get_image_path_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_ranged_value_p1",utc_watchface_complication_data_get_ranged_value_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_ranged_value_n1",utc_watchface_complication_data_get_ranged_value_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_icon_path_p1",utc_watchface_complication_data_get_icon_path_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_icon_path_n1",utc_watchface_complication_data_get_icon_path_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_extra_data_p1",utc_watchface_complication_data_get_extra_data_p1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_extra_data_n1",utc_watchface_complication_data_get_extra_data_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_screen_reader_text_p",utc_watchface_complication_data_get_screen_reader_text_p,NULL,NULL},
	{"utc_watchface_complication_data_get_screen_reader_text_n1",utc_watchface_complication_data_get_screen_reader_text_n1,NULL,NULL},
	{"utc_watchface_complication_data_get_screen_reader_text_n2",utc_watchface_complication_data_get_screen_reader_text_n2,NULL,NULL},
	{"utc_watchface_complication_allowed_list_create_p",utc_watchface_complication_allowed_list_create_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_create_n1",utc_watchface_complication_allowed_list_create_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_destroy_p",utc_watchface_complication_allowed_list_destroy_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_destroy_n1",utc_watchface_complication_allowed_list_destroy_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_add_p",utc_watchface_complication_allowed_list_add_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_add_n1",utc_watchface_complication_allowed_list_add_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_get_nth_p",utc_watchface_complication_allowed_list_get_nth_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_get_nth_n1",utc_watchface_complication_allowed_list_get_nth_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_add_n2",utc_watchface_complication_allowed_list_add_n2,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_delete_p",utc_watchface_complication_allowed_list_delete_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_delete_n1",utc_watchface_complication_allowed_list_delete_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_delete_n2",utc_watchface_complication_allowed_list_delete_n2,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_apply_p",utc_watchface_complication_allowed_list_apply_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_apply_n1",utc_watchface_complication_allowed_list_apply_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_clear_p",utc_watchface_complication_allowed_list_clear_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_allowed_list_clear_n1",utc_watchface_complication_allowed_list_clear_n1,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_transfer_event_p",utc_watchface_complication_transfer_event_p,NULL,NULL},
	{"utc_watchface_complication_transfer_event_n1",utc_watchface_complication_transfer_event_n1,NULL,NULL},
	{"utc_watchface_complication_transfer_event_n2",utc_watchface_complication_transfer_event_n2,NULL,NULL},
	{"utc_watchface_complication_data_get_timeinfo_p",utc_watchface_complication_data_get_timeinfo_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_data_get_timeinfo_n",utc_watchface_complication_data_get_timeinfo_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_timeinfo_get_timezone_p",utc_watchface_complication_timeinfo_get_timezone_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_timeinfo_get_timezone_n",utc_watchface_complication_timeinfo_get_timezone_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},{"utc_watchface_complication_timeinfo_get_timezone_id_p",utc_watchface_complication_timeinfo_get_timezone_id_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},{"utc_watchface_complication_timeinfo_get_timezone_id_n",utc_watchface_complication_timeinfo_get_timezone_id_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},{"utc_watchface_complication_timeinfo_get_timezone_country_p",utc_watchface_complication_timeinfo_get_timezone_country_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},{"utc_watchface_complication_timeinfo_get_timezone_country_n",utc_watchface_complication_timeinfo_get_timezone_country_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},{"utc_watchface_complication_timeinfo_get_timezone_city_p",utc_watchface_complication_timeinfo_get_timezone_city_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_timeinfo_get_timezone_city_n",utc_watchface_complication_timeinfo_get_timezone_city_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_timeinfo_get_timestamp_p",utc_watchface_complication_timeinfo_get_timestamp_p,utc_watchface_complication_startup,utc_watchface_complication_cleanup},
	{"utc_watchface_complication_timeinfo_get_timestamp_n",utc_watchface_complication_timeinfo_get_timestamp_n,utc_watchface_complication_startup,utc_watchface_complication_cleanup},

	{"utc_watchface_complication_provider_add_update_requested_cb_p",utc_watchface_complication_provider_add_update_requested_cb_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_add_update_requested_cb_n1",utc_watchface_complication_provider_add_update_requested_cb_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_remove_update_requested_cb_p",utc_watchface_complication_provider_remove_update_requested_cb_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_remove_update_requested_cb_n1",utc_watchface_complication_provider_remove_update_requested_cb_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_notify_update_p",utc_watchface_complication_provider_notify_update_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_notify_update_n1",utc_watchface_complication_provider_notify_update_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_is_editing_p",utc_watchface_complication_provider_setup_is_editing_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_is_editing_n1",utc_watchface_complication_provider_setup_is_editing_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_reply_to_editor_p",utc_watchface_complication_provider_setup_reply_to_editor_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_reply_to_editor_n1",utc_watchface_complication_provider_setup_reply_to_editor_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_get_context_p",utc_watchface_complication_provider_setup_get_context_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_setup_get_context_n1",utc_watchface_complication_provider_setup_get_context_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_short_text_p",utc_watchface_complication_provider_data_set_short_text_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_short_text_n1",utc_watchface_complication_provider_data_set_short_text_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_long_text_p",utc_watchface_complication_provider_data_set_long_text_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_long_text_n1",utc_watchface_complication_provider_data_set_long_text_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_title_p",utc_watchface_complication_provider_data_set_title_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_title_n1",utc_watchface_complication_provider_data_set_title_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_timestamp_p",utc_watchface_complication_provider_data_set_timestamp_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_timestamp_n1",utc_watchface_complication_provider_data_set_timestamp_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_image_path_p",utc_watchface_complication_provider_data_set_image_path_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_image_path_n1",utc_watchface_complication_provider_data_set_image_path_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_ranged_value_p",utc_watchface_complication_provider_data_set_ranged_value_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_ranged_value_n1",utc_watchface_complication_provider_data_set_ranged_value_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_icon_path_p",utc_watchface_complication_provider_data_set_icon_path_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_icon_path_n1",utc_watchface_complication_provider_data_set_icon_path_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_extra_data_p",utc_watchface_complication_provider_data_set_extra_data_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_set_extra_data_n1",utc_watchface_complication_provider_data_set_extra_data_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_data_is_valid_p",utc_watchface_complication_provider_data_is_valid_p,NULL,NULL},
	{"utc_watchface_complication_provider_data_is_valid_n1",utc_watchface_complication_provider_data_is_valid_n1,NULL,NULL},
	{"utc_watchface_complication_provider_data_is_valid_n2",utc_watchface_complication_provider_data_is_valid_n2,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_type_p",utc_watchface_complication_provider_event_get_type_p,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_type_n1",utc_watchface_complication_provider_event_get_type_n1,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_provider_id_p",utc_watchface_complication_provider_event_get_provider_id_p,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_provider_id_n1",utc_watchface_complication_provider_event_get_provider_id_n1,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_complication_type_p",utc_watchface_complication_provider_event_get_complication_type_p,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_complication_type_n1",utc_watchface_complication_provider_event_get_complication_type_n1,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_context_p",utc_watchface_complication_provider_event_get_context_p,NULL,NULL},
	{"utc_watchface_complication_provider_event_get_context_n1",utc_watchface_complication_provider_event_get_context_n1,NULL,NULL},
	{"utc_watchface_complication_provider_timeinfo_create_p1",utc_watchface_complication_provider_timeinfo_create_p1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_create_n1",utc_watchface_complication_provider_timeinfo_create_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_destroy_p1",utc_watchface_complication_provider_timeinfo_destroy_p1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_destroy_n1",utc_watchface_complication_provider_timeinfo_destroy_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_p",utc_watchface_complication_provider_timeinfo_set_timezone_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_n1",utc_watchface_complication_provider_timeinfo_set_timezone_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_id_p",utc_watchface_complication_provider_timeinfo_set_timezone_id_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_id_n1",utc_watchface_complication_provider_timeinfo_set_timezone_id_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_country_p",utc_watchface_complication_provider_timeinfo_set_timezone_country_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_country_n1",utc_watchface_complication_provider_timeinfo_set_timezone_country_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_city_p",utc_watchface_complication_provider_timeinfo_set_timezone_city_p,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},
	{"utc_watchface_complication_provider_timeinfo_set_timezone_city_n1",utc_watchface_complication_provider_timeinfo_set_timezone_city_n1,utc_watchface_complication_provider_startup,utc_watchface_complication_provider_cleanup},

	{"utc_watchface_editable_candidates_list_create_n", utc_watchface_editable_candidates_list_create_n, NULL, NULL},
	{"utc_watchface_editable_candidates_list_create_p", utc_watchface_editable_candidates_list_create_p, NULL, NULL},
	{"utc_watchface_editable_candidates_list_add_n1", utc_watchface_editable_candidates_list_add_n1, NULL, NULL},
	{"utc_watchface_editable_candidates_list_add_n2", utc_watchface_editable_candidates_list_add_n2, NULL, NULL},
	{"utc_watchface_editable_candidates_list_add_p", utc_watchface_editable_candidates_list_add_p, NULL, NULL},
	{"utc_watchface_editable_candidates_list_destroy_n", utc_watchface_editable_candidates_list_destroy_n, NULL, NULL},
	{"utc_watchface_editable_candidates_list_destroy_p", utc_watchface_editable_candidates_list_destroy_p, NULL, NULL},
	{"utc_watchface_editable_add_design_element_n1", utc_watchface_editable_add_design_element_n1, NULL, NULL},
	{"utc_watchface_editable_add_design_element_n2", utc_watchface_editable_add_design_element_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_add_design_element_n3", utc_watchface_editable_add_design_element_n3, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_add_design_element_p", utc_watchface_editable_add_design_element_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_add_complication_n1", utc_watchface_editable_add_complication_n1, NULL, NULL},
	{"utc_watchface_editable_add_complication_n2", utc_watchface_editable_add_complication_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_add_complication_p", utc_watchface_editable_add_complication_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_request_edit_n1", utc_watchface_editable_request_edit_n1, NULL, NULL},
	{"utc_watchface_editable_request_edit_n2", utc_watchface_editable_request_edit_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_request_edit_p", utc_watchface_editable_request_edit_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_add_edit_ready_cb_n", utc_watchface_editable_add_edit_ready_cb_n, NULL, NULL},
	{"utc_watchface_editable_add_edit_ready_cb_p", utc_watchface_editable_add_edit_ready_cb_p, NULL, NULL},
	{"utc_watchface_editable_remove_edit_ready_cb_n", utc_watchface_editable_remove_edit_ready_cb_n, NULL, NULL},
	{"utc_watchface_editable_remove_edit_ready_cb_p", utc_watchface_editable_remove_edit_ready_cb_p, NULL, NULL},
	{"utc_watchface_editable_get_editable_name_n1", utc_watchface_editable_get_editable_name_n1, NULL, NULL},
	{"utc_watchface_editable_get_editable_name_n2", utc_watchface_editable_get_editable_name_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_editable_name_p", utc_watchface_editable_get_editable_name_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_set_editable_name_n1", utc_watchface_editable_set_editable_name_n1, NULL, NULL},
	{"utc_watchface_editable_set_editable_name_n2", utc_watchface_editable_set_editable_name_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_set_editable_name_p", utc_watchface_editable_set_editable_name_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_nth_data_n1", utc_watchface_editable_get_nth_data_n1, NULL, NULL},
	{"utc_watchface_editable_get_nth_data_n2", utc_watchface_editable_get_nth_data_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_nth_data_p", utc_watchface_editable_get_nth_data_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_current_data_n1", utc_watchface_editable_get_current_data_n1, NULL, NULL},
	{"utc_watchface_editable_get_current_data_n2", utc_watchface_editable_get_current_data_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_current_data_p", utc_watchface_editable_get_current_data_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_current_data_idx_n1", utc_watchface_editable_get_current_data_idx_n1, NULL, NULL},
	{"utc_watchface_editable_get_current_data_idx_n2", utc_watchface_editable_get_current_data_idx_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_current_data_idx_p", utc_watchface_editable_get_current_data_idx_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_editable_id_n1", utc_watchface_editable_get_editable_id_n1, NULL, NULL},
	{"utc_watchface_editable_get_editable_id_n2", utc_watchface_editable_get_editable_id_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_editable_id_p", utc_watchface_editable_get_editable_id_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_highlight_n1", utc_watchface_editable_get_highlight_n1, NULL, NULL},
	{"utc_watchface_editable_get_highlight_n2", utc_watchface_editable_get_highlight_n2, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_get_highlight_p", utc_watchface_editable_get_highlight_p, utc_watchface_editable_startup, utc_watchface_editable_cleanup},
	{"utc_watchface_editable_load_current_data_n", utc_watchface_editable_load_current_data_n, NULL, NULL},
	{"utc_watchface_editable_load_current_data_p", utc_watchface_editable_load_current_data_p, NULL, NULL},
	{"utc_watchface_editable_highlight_create_n", utc_watchface_editable_highlight_create_n, NULL, NULL},
	{"utc_watchface_editable_highlight_create_p", utc_watchface_editable_highlight_create_p, NULL, NULL},
	{"utc_watchface_editable_highlight_destroy_n", utc_watchface_editable_highlight_destroy_n, NULL, NULL},
	{"utc_watchface_editable_highlight_destroy_p", utc_watchface_editable_highlight_destroy_p, NULL, NULL},
	{"utc_watchface_editable_highlight_set_geometry_n", utc_watchface_editable_highlight_set_geometry_n, NULL, NULL},
	{"utc_watchface_editable_highlight_set_geometry_p", utc_watchface_editable_highlight_set_geometry_p, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_n1", utc_watchface_editable_highlight_get_geometry_n1, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_n2", utc_watchface_editable_highlight_get_geometry_n2, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_n3", utc_watchface_editable_highlight_get_geometry_n3, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_n4", utc_watchface_editable_highlight_get_geometry_n4, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_n5", utc_watchface_editable_highlight_get_geometry_n5, NULL, NULL},
	{"utc_watchface_editable_highlight_get_geometry_p", utc_watchface_editable_highlight_get_geometry_p, NULL, NULL},
	{"utc_watchface_editable_highlight_set_shape_type_p", utc_watchface_editable_highlight_set_shape_type_p, NULL, NULL},
	{"utc_watchface_editable_highlight_set_shape_type_n1", utc_watchface_editable_highlight_set_shape_type_n1, NULL, NULL},
	{"utc_watchface_editable_highlight_set_shape_type_n2", utc_watchface_editable_highlight_set_shape_type_n2, NULL, NULL},
	{"utc_watchface_editable_highlight_get_shape_type_p", utc_watchface_editable_highlight_get_shape_type_p, NULL, NULL},
	{"utc_watchface_editable_highlight_get_shape_type_n1", utc_watchface_editable_highlight_get_shape_type_n1, NULL, NULL},
	{"utc_watchface_editable_highlight_get_shape_type_n2", utc_watchface_editable_highlight_get_shape_type_n2, NULL, NULL},
	{NULL, NULL}
};
#endif // __TCT_WATCHFACE_COMPLICATION_NATIVE_H__
