//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_LOCATION-MANAGER-NATIVE_H__
#define __TCT_LOCATION-MANAGER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_location_manager_startup(void);
extern void utc_location_manager_cleanup(void);
extern void utc_location_manager_cb_startup(void);
extern void utc_location_manager_cb_cleanup(void);
extern void utc_location_manager_batch_startup(void);
extern void utc_location_manager_batch_cleanup(void);
extern void utc_location_gps_status_startup(void);
extern void utc_location_gps_status_cleanup(void);
extern void utc_location_manager_bound_startup(void);
extern void utc_location_manager_bound_cleanup(void);

extern int utc_location_manager_create_p(void);
extern int utc_location_manager_create_p2(void);
extern int utc_location_manager_create_p3(void);
extern int utc_location_manager_create_p4(void);
extern int utc_location_manager_create_p5(void);
extern int utc_location_manager_create_n(void);
extern int utc_location_manager_create_n2(void);
extern int utc_location_manager_get_method_p(void);
extern int utc_location_manager_get_method_p2(void);
extern int utc_location_manager_get_method_p3(void);
extern int utc_location_manager_get_method_p4(void);
extern int utc_location_manager_get_method_p5(void);
extern int utc_location_manager_get_method_n(void);
extern int utc_location_manager_get_position_p(void);
extern int utc_location_manager_get_position_p2(void);
extern int utc_location_manager_get_position_n(void);
extern int utc_location_manager_get_velocity_p(void);
extern int utc_location_manager_get_velocity_n(void);
extern int utc_location_manager_get_accuracy_p(void);
extern int utc_location_manager_get_accuracy_n(void);
extern int utc_location_manager_get_velocity_accuracy_p(void);
extern int utc_location_manager_get_velocity_accuracy_n(void);
extern int utc_location_manager_get_last_accuracy_p(void);
extern int utc_location_manager_get_last_accuracy_n(void);
extern int utc_location_manager_get_accessibility_state_p(void);
extern int utc_location_manager_get_accessibility_state_n(void);
extern int utc_location_manager_get_last_location_p(void);
extern int utc_location_manager_get_last_location_n(void);
extern int utc_location_manager_get_location_p(void);
extern int utc_location_manager_get_location_n(void);
extern int utc_location_manager_get_last_position_p(void);
extern int utc_location_manager_get_last_position_n(void);
extern int utc_location_manager_get_last_velocity_p(void);
extern int utc_location_manager_get_last_velocity_n(void);
extern int utc_location_manager_is_supported_method_p(void);
extern int utc_location_manager_is_supported_method_p2(void);
extern int utc_location_manager_is_supported_method_p3(void);
extern int utc_location_manager_is_supported_method_p4(void);
extern int utc_location_manager_is_supported_method_n(void);
extern int utc_location_manager_destroy_p(void);
extern int utc_location_manager_destroy_n(void);
extern int utc_location_manager_get_distance_p(void);
extern int utc_location_manager_get_distance_n(void);
extern int utc_location_manager_is_enabled_method_p(void);
extern int utc_location_manager_is_enabled_method_p2(void);
extern int utc_location_manager_is_enabled_method_p3(void);
extern int utc_location_manager_is_enabled_method_n(void);
extern int utc_location_manager_request_single_location_p(void);
extern int utc_location_manager_request_single_location_p2(void);
extern int utc_location_manager_request_single_location_n(void);
extern int utc_location_manager_request_single_location_n2(void);
extern int utc_location_manager_request_single_location_n3(void);
extern int utc_location_manager_is_enabled_mock_location_p(void);
extern int utc_location_manager_is_enabled_mock_location_n(void);
extern int utc_location_manager_enable_mock_location_p(void);
extern int utc_location_manager_set_mock_location_p(void);
extern int utc_location_manager_set_mock_location_n(void);
extern int utc_location_manager_clear_mock_location_p(void);
extern int utc_location_manager_clear_mock_location_n(void);
extern int utc_location_manager_start_p(void);
extern int utc_location_manager_start_n(void);
extern int utc_location_manager_set_position_updated_cb_p(void);
extern int utc_location_manager_set_position_updated_cb_n(void);
extern int utc_location_manager_unset_position_updated_cb_p(void);
extern int utc_location_manager_unset_position_updated_cb_n(void);
extern int utc_location_manager_set_velocity_updated_cb_p(void);
extern int utc_location_manager_set_velocity_updated_cb_n(void);
extern int utc_location_manager_unset_velocity_updated_cb_p(void);
extern int utc_location_manager_unset_velocity_updated_cb_n(void);
extern int utc_location_manager_set_service_state_changed_cb_p(void);
extern int utc_location_manager_set_service_state_changed_cb_n(void);
extern int utc_location_manager_unset_service_state_changed_cb_p(void);
extern int utc_location_manager_unset_service_state_changed_cb_n(void);
extern int utc_location_manager_set_zone_changed_cb_p(void);
extern int utc_location_manager_set_zone_changed_cb_p2(void);
extern int utc_location_manager_set_zone_changed_cb_p3(void);
extern int utc_location_manager_set_zone_changed_cb_n(void);
extern int utc_location_manager_unset_zone_changed_cb_p(void);
extern int utc_location_manager_unset_zone_changed_cb_n(void);
extern int utc_location_manager_set_setting_changed_cb_p(void);
extern int utc_location_manager_set_setting_changed_cb_n(void);
extern int utc_location_manager_unset_setting_changed_cb_p(void);
extern int utc_location_manager_unset_setting_changed_cb_n(void);
extern int utc_location_manager_stop_p(void);
extern int utc_location_manager_stop_n(void);
extern int utc_location_manager_set_distance_based_location_changed_cb_p(void);
extern int utc_location_manager_set_distance_based_location_changed_cb_n(void);
extern int utc_location_manager_unset_distance_based_location_changed_cb_p(void);
extern int utc_location_manager_unset_distance_based_location_changed_cb_n(void);
extern int utc_location_manager_set_location_changed_cb_p(void);
extern int utc_location_manager_set_location_changed_cb_p2(void);
extern int utc_location_manager_set_location_changed_cb_n(void);
extern int utc_location_manager_unset_location_changed_cb_p(void);
extern int utc_location_manager_unset_location_changed_cb_n(void);
extern int utc_location_manager_start_batch_p(void);
extern int utc_location_manager_start_batch_n(void);
extern int utc_location_manager_stop_batch_p(void);
extern int utc_location_manager_stop_batch_n(void);
extern int utc_location_manager_foreach_location_batch_p(void);
extern int utc_location_manager_foreach_location_batch_n(void);
extern int utc_location_manager_foreach_location_batch_n2(void);
extern int utc_location_manager_set_location_batch_cb_p(void);
extern int utc_location_manager_set_location_batch_cb_n(void);
extern int utc_location_manager_unset_location_batch_cb_p(void);
extern int utc_location_manager_unset_location_batch_cb_n(void);
extern int utc_location_manager_set_fused_mode_p(void);
extern int utc_location_manager_set_fused_mode_n(void);
extern int utc_location_gps_status_get_nmea_p(void);
extern int utc_location_gps_status_get_nmea_n(void);
extern int utc_location_gps_status_get_nmea_n2(void);
extern int utc_location_gps_status_set_satellite_updated_cb_p(void);
extern int utc_location_gps_status_set_satellite_updated_cb_n(void);
extern int utc_location_gps_status_unset_satellite_updated_cb_p(void);
extern int utc_location_gps_status_unset_satellite_updated_cb_n(void);
extern int utc_location_gps_status_get_satellite_p(void);
extern int utc_location_gps_status_get_satellite_n(void);
extern int utc_location_gps_status_foreach_satellites_in_view_p(void);
extern int utc_location_gps_status_foreach_satellites_in_view_n(void);
extern int utc_location_gps_status_foreach_last_satellites_in_view_p(void);
extern int utc_location_gps_status_foreach_last_satellites_in_view_n(void);
extern int utc_location_gps_status_get_last_satellite_p(void);
extern int utc_location_gps_status_get_last_satellite_n(void);
extern int utc_location_manager_add_boundary_p(void);
extern int utc_location_manager_add_boundary_p2(void);
extern int utc_location_manager_add_boundary_p3(void);
extern int utc_location_manager_add_boundary_n(void);
extern int utc_location_manager_foreach_boundary_p(void);
extern int utc_location_manager_foreach_boundary_n(void);
extern int utc_location_manager_remove_boundary_p(void);
extern int utc_location_manager_remove_boundary_p2(void);
extern int utc_location_manager_remove_boundary_p3(void);
extern int utc_location_manager_remove_boundary_n(void);
extern int utc_location_bounds_foreach_polygon_coords_p(void);
extern int utc_location_bounds_foreach_polygon_coords_n(void);
extern int utc_location_bounds_foreach_polygon_coords_n2(void);
extern int utc_location_bounds_get_circle_coords_p(void);
extern int utc_location_bounds_get_circle_coords_n(void);
extern int utc_location_bounds_get_rect_coords_p(void);
extern int utc_location_bounds_get_rect_coords_n(void);
extern int utc_location_bounds_get_type_p(void);
extern int utc_location_bounds_get_type_n(void);
extern int utc_location_bounds_contains_coordinates_p(void);
extern int utc_location_bounds_contains_coordinates_n(void);
extern int utc_location_bounds_contains_coordinates_n2(void);
extern int utc_location_bounds_contains_coordinates_on_edge_p(void);
extern int utc_location_bounds_contains_coordinates_on_edge_n(void);
extern int utc_location_bounds_contains_coordinates_on_edge_n2(void);
extern int utc_location_bounds_contains_coordinates_on_edge_n3(void);
extern int utc_location_bounds_create_rect_p(void);
extern int utc_location_bounds_create_rect_n(void);
extern int utc_location_bounds_create_rect_n2(void);
extern int utc_location_bounds_create_rect_n3(void);
extern int utc_location_bounds_create_circle_p(void);
extern int utc_location_bounds_create_circle_n(void);
extern int utc_location_bounds_create_circle_n2(void);
extern int utc_location_bounds_create_circle_n3(void);
extern int utc_location_bounds_create_polygon_p(void);
extern int utc_location_bounds_set_state_changed_cb_p2(void);
extern int utc_location_bounds_set_state_changed_cb_n(void);
extern int utc_location_bounds_unset_state_changed_cb_p(void);
extern int utc_location_bounds_unset_state_changed_cb_n(void);
extern int utc_location_bounds_destroy_p(void);
extern int utc_location_bounds_destroy_n(void);

testcase tc_array[] = {
	{"utc_location_manager_create_p",utc_location_manager_create_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_p2",utc_location_manager_create_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_p3",utc_location_manager_create_p3,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_p4",utc_location_manager_create_p4,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_p5",utc_location_manager_create_p5,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_n",utc_location_manager_create_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_create_n2",utc_location_manager_create_n2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_p",utc_location_manager_get_method_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_p2",utc_location_manager_get_method_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_p3",utc_location_manager_get_method_p3,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_p4",utc_location_manager_get_method_p4,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_p5",utc_location_manager_get_method_p5,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_method_n",utc_location_manager_get_method_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_position_p",utc_location_manager_get_position_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_position_p2",utc_location_manager_get_position_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_position_n",utc_location_manager_get_position_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_velocity_p",utc_location_manager_get_velocity_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_velocity_n",utc_location_manager_get_velocity_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_accuracy_p",utc_location_manager_get_accuracy_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_accuracy_n",utc_location_manager_get_accuracy_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_velocity_accuracy_p",utc_location_manager_get_velocity_accuracy_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_velocity_accuracy_n",utc_location_manager_get_velocity_accuracy_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_accuracy_p",utc_location_manager_get_last_accuracy_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_accuracy_n",utc_location_manager_get_last_accuracy_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_accessibility_state_p",utc_location_manager_get_accessibility_state_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_accessibility_state_n",utc_location_manager_get_accessibility_state_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_location_p",utc_location_manager_get_last_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_location_n",utc_location_manager_get_last_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_location_p",utc_location_manager_get_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_location_n",utc_location_manager_get_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_position_p",utc_location_manager_get_last_position_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_position_n",utc_location_manager_get_last_position_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_velocity_p",utc_location_manager_get_last_velocity_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_last_velocity_n",utc_location_manager_get_last_velocity_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_supported_method_p",utc_location_manager_is_supported_method_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_supported_method_p2",utc_location_manager_is_supported_method_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_supported_method_p3",utc_location_manager_is_supported_method_p3,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_supported_method_p4",utc_location_manager_is_supported_method_p4,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_supported_method_n",utc_location_manager_is_supported_method_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_destroy_p",utc_location_manager_destroy_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_destroy_n",utc_location_manager_destroy_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_distance_p",utc_location_manager_get_distance_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_get_distance_n",utc_location_manager_get_distance_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_method_p",utc_location_manager_is_enabled_method_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_method_p2",utc_location_manager_is_enabled_method_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_method_p3",utc_location_manager_is_enabled_method_p3,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_method_n",utc_location_manager_is_enabled_method_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_request_single_location_p",utc_location_manager_request_single_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_request_single_location_p2",utc_location_manager_request_single_location_p2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_request_single_location_n",utc_location_manager_request_single_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_request_single_location_n2",utc_location_manager_request_single_location_n2,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_request_single_location_n3",utc_location_manager_request_single_location_n3,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_mock_location_p",utc_location_manager_is_enabled_mock_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_is_enabled_mock_location_n",utc_location_manager_is_enabled_mock_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_enable_mock_location_p",utc_location_manager_enable_mock_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_set_mock_location_p",utc_location_manager_set_mock_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_set_mock_location_n",utc_location_manager_set_mock_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_clear_mock_location_p",utc_location_manager_clear_mock_location_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_clear_mock_location_n",utc_location_manager_clear_mock_location_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_start_p",utc_location_manager_start_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_start_n",utc_location_manager_start_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_position_updated_cb_p",utc_location_manager_set_position_updated_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_position_updated_cb_n",utc_location_manager_set_position_updated_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_position_updated_cb_p",utc_location_manager_unset_position_updated_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_position_updated_cb_n",utc_location_manager_unset_position_updated_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_velocity_updated_cb_p",utc_location_manager_set_velocity_updated_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_velocity_updated_cb_n",utc_location_manager_set_velocity_updated_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_velocity_updated_cb_p",utc_location_manager_unset_velocity_updated_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_velocity_updated_cb_n",utc_location_manager_unset_velocity_updated_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_service_state_changed_cb_p",utc_location_manager_set_service_state_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_service_state_changed_cb_n",utc_location_manager_set_service_state_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_service_state_changed_cb_p",utc_location_manager_unset_service_state_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_service_state_changed_cb_n",utc_location_manager_unset_service_state_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_zone_changed_cb_p",utc_location_manager_set_zone_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_zone_changed_cb_p2",utc_location_manager_set_zone_changed_cb_p2,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_zone_changed_cb_p3",utc_location_manager_set_zone_changed_cb_p3,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_zone_changed_cb_n",utc_location_manager_set_zone_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_zone_changed_cb_p",utc_location_manager_unset_zone_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_zone_changed_cb_n",utc_location_manager_unset_zone_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_setting_changed_cb_p",utc_location_manager_set_setting_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_setting_changed_cb_n",utc_location_manager_set_setting_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_setting_changed_cb_p",utc_location_manager_unset_setting_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_setting_changed_cb_n",utc_location_manager_unset_setting_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_stop_p",utc_location_manager_stop_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_stop_n",utc_location_manager_stop_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_distance_based_location_changed_cb_p",utc_location_manager_set_distance_based_location_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_distance_based_location_changed_cb_n",utc_location_manager_set_distance_based_location_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_distance_based_location_changed_cb_p",utc_location_manager_unset_distance_based_location_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_distance_based_location_changed_cb_n",utc_location_manager_unset_distance_based_location_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_location_changed_cb_p",utc_location_manager_set_location_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_location_changed_cb_p2",utc_location_manager_set_location_changed_cb_p2,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_set_location_changed_cb_n",utc_location_manager_set_location_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_location_changed_cb_p",utc_location_manager_unset_location_changed_cb_p,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_unset_location_changed_cb_n",utc_location_manager_unset_location_changed_cb_n,utc_location_manager_cb_startup,utc_location_manager_cb_cleanup},
	{"utc_location_manager_start_batch_p",utc_location_manager_start_batch_p,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_start_batch_n",utc_location_manager_start_batch_n,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_stop_batch_p",utc_location_manager_stop_batch_p,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_stop_batch_n",utc_location_manager_stop_batch_n,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_foreach_location_batch_p",utc_location_manager_foreach_location_batch_p,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_foreach_location_batch_n",utc_location_manager_foreach_location_batch_n,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_foreach_location_batch_n2",utc_location_manager_foreach_location_batch_n2,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_set_location_batch_cb_p",utc_location_manager_set_location_batch_cb_p,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_set_location_batch_cb_n",utc_location_manager_set_location_batch_cb_n,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_unset_location_batch_cb_p",utc_location_manager_unset_location_batch_cb_p,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_unset_location_batch_cb_n",utc_location_manager_unset_location_batch_cb_n,utc_location_manager_batch_startup,utc_location_manager_batch_cleanup},
	{"utc_location_manager_set_fused_mode_p",utc_location_manager_set_fused_mode_p,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_manager_set_fused_mode_n",utc_location_manager_set_fused_mode_n,utc_location_manager_startup,utc_location_manager_cleanup},
	{"utc_location_gps_status_get_nmea_p",utc_location_gps_status_get_nmea_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_nmea_n",utc_location_gps_status_get_nmea_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_nmea_n2",utc_location_gps_status_get_nmea_n2,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_set_satellite_updated_cb_p",utc_location_gps_status_set_satellite_updated_cb_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_set_satellite_updated_cb_n",utc_location_gps_status_set_satellite_updated_cb_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_unset_satellite_updated_cb_p",utc_location_gps_status_unset_satellite_updated_cb_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_unset_satellite_updated_cb_n",utc_location_gps_status_unset_satellite_updated_cb_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_satellite_p",utc_location_gps_status_get_satellite_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_satellite_n",utc_location_gps_status_get_satellite_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_foreach_satellites_in_view_p",utc_location_gps_status_foreach_satellites_in_view_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_foreach_satellites_in_view_n",utc_location_gps_status_foreach_satellites_in_view_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_foreach_last_satellites_in_view_p",utc_location_gps_status_foreach_last_satellites_in_view_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_foreach_last_satellites_in_view_n",utc_location_gps_status_foreach_last_satellites_in_view_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_last_satellite_p",utc_location_gps_status_get_last_satellite_p,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_gps_status_get_last_satellite_n",utc_location_gps_status_get_last_satellite_n,utc_location_gps_status_startup,utc_location_gps_status_cleanup},
	{"utc_location_manager_add_boundary_p",utc_location_manager_add_boundary_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_add_boundary_p2",utc_location_manager_add_boundary_p2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_add_boundary_p3",utc_location_manager_add_boundary_p3,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_add_boundary_n",utc_location_manager_add_boundary_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_foreach_boundary_p",utc_location_manager_foreach_boundary_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_foreach_boundary_n",utc_location_manager_foreach_boundary_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_remove_boundary_p",utc_location_manager_remove_boundary_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_remove_boundary_p2",utc_location_manager_remove_boundary_p2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_remove_boundary_p3",utc_location_manager_remove_boundary_p3,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_manager_remove_boundary_n",utc_location_manager_remove_boundary_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_foreach_polygon_coords_p",utc_location_bounds_foreach_polygon_coords_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_foreach_polygon_coords_n",utc_location_bounds_foreach_polygon_coords_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_foreach_polygon_coords_n2",utc_location_bounds_foreach_polygon_coords_n2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_circle_coords_p",utc_location_bounds_get_circle_coords_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_circle_coords_n",utc_location_bounds_get_circle_coords_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_rect_coords_p",utc_location_bounds_get_rect_coords_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_rect_coords_n",utc_location_bounds_get_rect_coords_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_type_p",utc_location_bounds_get_type_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_get_type_n",utc_location_bounds_get_type_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_p",utc_location_bounds_contains_coordinates_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_n",utc_location_bounds_contains_coordinates_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_n2",utc_location_bounds_contains_coordinates_n2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_on_edge_p",utc_location_bounds_contains_coordinates_on_edge_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_on_edge_n",utc_location_bounds_contains_coordinates_on_edge_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_on_edge_n2",utc_location_bounds_contains_coordinates_on_edge_n2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_contains_coordinates_on_edge_n3",utc_location_bounds_contains_coordinates_on_edge_n3,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_rect_p",utc_location_bounds_create_rect_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_rect_n",utc_location_bounds_create_rect_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_rect_n2",utc_location_bounds_create_rect_n2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_rect_n3",utc_location_bounds_create_rect_n3,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_circle_p",utc_location_bounds_create_circle_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_circle_n",utc_location_bounds_create_circle_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_circle_n2",utc_location_bounds_create_circle_n2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_circle_n3",utc_location_bounds_create_circle_n3,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_create_polygon_p",utc_location_bounds_create_polygon_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_set_state_changed_cb_p2",utc_location_bounds_set_state_changed_cb_p2,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_set_state_changed_cb_n",utc_location_bounds_set_state_changed_cb_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_unset_state_changed_cb_p",utc_location_bounds_unset_state_changed_cb_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_unset_state_changed_cb_n",utc_location_bounds_unset_state_changed_cb_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_destroy_p",utc_location_bounds_destroy_p,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{"utc_location_bounds_destroy_n",utc_location_bounds_destroy_n,utc_location_manager_bound_startup,utc_location_manager_bound_cleanup},
	{NULL, NULL}
};

#endif // __TCT_LOCATION-MANAGER-NATIVE_H__
