//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_PACKAGE-MANAGER-NATIVE_H__
#define __TCT_PACKAGE-MANAGER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_package_manager_startup(void);
extern void ITs_package_manager_cleanup(void);
extern void ITs_package_manager_info_startup(void);
extern void ITs_package_manager_info_cleanup(void);

extern int ITc_package_manager_filter_foreach_package_info_p(void);
extern int ITc_package_manager_foreach_package_info_p(void);
extern int ITc_package_manager_create_destroy_p(void);
extern int ITc_package_manager_compare_app_cert_info_p(void);
extern int ITc_package_manager_compare_package_cert_info_p(void);
extern int ITc_package_manager_get_package_id_by_app_id_p(void);
extern int ITc_package_manager_get_destroy_package_info_p(void);
extern int ITc_package_manager_is_preload_package_by_app_id_p(void);
extern int ITc_package_manager_get_permission_type_p(void);
extern int ITc_package_manager_set_unset_event_cb_p(void);
extern int ITc_package_manager_set_event_status_p(void);
extern int ITc_package_manager_filter_create_destroy_p(void);
extern int ITc_package_manager_filter_count_p(void);
extern int ITc_package_manager_filter_add_bool_p(void);
extern int ITc_package_manager_clear_cache_dir_p(void);
extern int ITc_package_manager_get_package_size_info_p(void);
extern int ITc_package_size_info_get_data_size_p(void);
extern int ITc_package_size_info_get_cache_size_p(void);
extern int ITc_package_size_info_get_app_size_p(void);
extern int ITc_package_size_info_get_external_data_size_p(void);
extern int ITc_package_size_info_get_external_cache_size_p(void);
extern int ITc_package_size_info_get_external_app_size_p(void);
extern int ITc_package_info_foreach_app_from_package_p(void);
extern int ITc_package_info_clone_is_equal_p(void);
extern int ITc_package_info_foreach_cert_info_p(void);
extern int ITc_package_info_get_icon_p(void);
extern int ITc_package_info_get_label_p(void);
extern int ITc_package_info_get_package_p(void);
extern int ITc_package_info_get_installed_storage_p(void);
extern int ITc_package_info_get_type_p(void);
extern int ITc_package_info_get_version_p(void);
extern int ITc_package_info_is_accessible_p(void);
extern int ITc_package_info_is_preload_package_p(void);
extern int ITc_package_info_is_removable_package_p(void);
extern int ITc_package_info_is_system_package_p(void);
extern int ITc_package_info_get_root_path_p(void);
extern int ITc_package_info_create_p(void);
extern int ITc_package_info_foreach_privilege_info_p(void);
extern int ITc_package_info_get_main_app_id_p(void);
extern int ITc_package_archive_info_create_destroy_p(void);
extern int ITc_package_archive_info_get_api_version_p(void);
extern int ITc_package_archive_info_get_author_p(void);
extern int ITc_package_archive_info_get_description_p(void);
extern int ITc_package_archive_info_get_icon_p(void);
extern int ITc_package_archive_info_get_label_p(void);
extern int ITc_package_archive_info_get_package_p(void);
extern int ITc_package_archive_info_get_type_p(void);
extern int ITc_package_archive_info_get_version_p(void);
extern int ITc_package_info_get_installed_time_p(void);
extern int ITc_package_info_updateinfo_create_destroy_p(void);
extern int ITc_package_info_updateinfo_get_pkgid_p(void);
extern int ITc_package_info_updateinfo_get_version_p(void);
extern int ITc_package_info_updateinfo_get_type_p(void);
extern int ITc_package_info_updateinfo_foreach_info_p(void);
extern int ITc_package_manager_updateinfo_request_create_destroy_p(void);
extern int ITc_package_manager_updateinfo_set_pkgid_p(void);
extern int ITc_package_manager_updateinfo_set_version_p(void);
extern int ITc_package_manager_updateinfo_set_type_p(void);
extern int ITc_package_info_foreach_dependency_info_p(void);
extern int ITc_package_info_foreach_dependency_info_depends_on_p(void);
extern int ITc_package_archive_info_foreach_direct_dependency_p(void);
extern int ITc_package_manager_get_total_package_size_info_p(void);
extern int ITc_package_info_foreach_required_privilege_p(void);
extern int ITc_package_manager_package_info_foreach_res_allowed_package_p(void);
extern int ITc_package_manager_package_info_get_res_type_p(void);
extern int ITc_package_manager_package_info_get_res_version_p(void);
extern int ITc_package_manager_package_manager_filter_add_string_p(void);

testcase tc_array[] = {
	{"ITc_package_info_foreach_required_privilege_p", ITc_package_info_foreach_required_privilege_p, ITs_package_manager_startup, ITs_package_manager_cleanup},
	{"ITc_package_manager_package_info_foreach_res_allowed_package_p", ITc_package_manager_package_info_foreach_res_allowed_package_p, ITs_package_manager_startup, ITs_package_manager_cleanup},
	{"ITc_package_manager_package_info_get_res_type_p", ITc_package_manager_package_info_get_res_type_p, ITs_package_manager_startup, ITs_package_manager_cleanup},
	{"ITc_package_manager_package_info_get_res_version_p", ITc_package_manager_package_info_get_res_version_p, ITs_package_manager_startup, ITs_package_manager_cleanup},
	{"ITc_package_manager_package_manager_filter_add_string_p", ITc_package_manager_package_manager_filter_add_string_p, ITs_package_manager_startup, ITs_package_manager_cleanup},
	{"ITc_package_manager_filter_foreach_package_info_p",ITc_package_manager_filter_foreach_package_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_foreach_package_info_p",ITc_package_manager_foreach_package_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_create_destroy_p",ITc_package_manager_create_destroy_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_compare_app_cert_info_p",ITc_package_manager_compare_app_cert_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_compare_package_cert_info_p",ITc_package_manager_compare_package_cert_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_get_package_id_by_app_id_p",ITc_package_manager_get_package_id_by_app_id_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_get_destroy_package_info_p",ITc_package_manager_get_destroy_package_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_is_preload_package_by_app_id_p",ITc_package_manager_is_preload_package_by_app_id_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_get_permission_type_p",ITc_package_manager_get_permission_type_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_set_unset_event_cb_p",ITc_package_manager_set_unset_event_cb_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_set_event_status_p",ITc_package_manager_set_event_status_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_filter_create_destroy_p",ITc_package_manager_filter_create_destroy_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_filter_count_p",ITc_package_manager_filter_count_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_filter_add_bool_p",ITc_package_manager_filter_add_bool_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_clear_cache_dir_p",ITc_package_manager_clear_cache_dir_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_manager_get_package_size_info_p",ITc_package_manager_get_package_size_info_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_data_size_p",ITc_package_size_info_get_data_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_cache_size_p",ITc_package_size_info_get_cache_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_app_size_p",ITc_package_size_info_get_app_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_external_data_size_p",ITc_package_size_info_get_external_data_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_external_cache_size_p",ITc_package_size_info_get_external_cache_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_size_info_get_external_app_size_p",ITc_package_size_info_get_external_app_size_p,ITs_package_manager_startup,ITs_package_manager_cleanup},
	{"ITc_package_info_foreach_app_from_package_p",ITc_package_info_foreach_app_from_package_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_clone_is_equal_p",ITc_package_info_clone_is_equal_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_foreach_cert_info_p",ITc_package_info_foreach_cert_info_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_icon_p",ITc_package_info_get_icon_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_label_p",ITc_package_info_get_label_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_package_p",ITc_package_info_get_package_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_installed_storage_p",ITc_package_info_get_installed_storage_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_type_p",ITc_package_info_get_type_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_version_p",ITc_package_info_get_version_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_is_accessible_p",ITc_package_info_is_accessible_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_is_preload_package_p",ITc_package_info_is_preload_package_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_is_removable_package_p",ITc_package_info_is_removable_package_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_is_system_package_p",ITc_package_info_is_system_package_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_root_path_p",ITc_package_info_get_root_path_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_create_p",ITc_package_info_create_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_foreach_privilege_info_p",ITc_package_info_foreach_privilege_info_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_main_app_id_p",ITc_package_info_get_main_app_id_p,ITs_package_manager_info_startup,ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_main_app_id_p", ITc_package_info_get_main_app_id_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_create_destroy_p", ITc_package_archive_info_create_destroy_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_api_version_p", ITc_package_archive_info_get_api_version_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_author_p", ITc_package_archive_info_get_author_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_description_p", ITc_package_archive_info_get_description_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_icon_p", ITc_package_archive_info_get_icon_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_label_p", ITc_package_archive_info_get_label_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_package_p", ITc_package_archive_info_get_package_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_type_p", ITc_package_archive_info_get_type_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_get_version_p", ITc_package_archive_info_get_version_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_get_installed_time_p", ITc_package_info_get_installed_time_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_updateinfo_create_destroy_p", ITc_package_info_updateinfo_create_destroy_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_updateinfo_get_pkgid_p", ITc_package_info_updateinfo_get_pkgid_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_updateinfo_get_version_p", ITc_package_info_updateinfo_get_version_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_updateinfo_get_type_p", ITc_package_info_updateinfo_get_type_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_updateinfo_foreach_info_p", ITc_package_info_updateinfo_foreach_info_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_manager_updateinfo_request_create_destroy_p", ITc_package_manager_updateinfo_request_create_destroy_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_manager_updateinfo_set_pkgid_p", ITc_package_manager_updateinfo_set_pkgid_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_manager_updateinfo_set_version_p", ITc_package_manager_updateinfo_set_version_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_manager_updateinfo_set_type_p", ITc_package_manager_updateinfo_set_type_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_foreach_dependency_info_p", ITc_package_info_foreach_dependency_info_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_info_foreach_dependency_info_depends_on_p", ITc_package_info_foreach_dependency_info_depends_on_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_archive_info_foreach_direct_dependency_p", ITc_package_archive_info_foreach_direct_dependency_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{"ITc_package_manager_get_total_package_size_info_p", ITc_package_manager_get_total_package_size_info_p, ITs_package_manager_info_startup, ITs_package_manager_info_cleanup},
	{NULL, NULL}
};

#endif // __TCT_PACKAGE-MANAGER-NATIVE_H__
