//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_PLATFORM-PERMISSION-NATIVE_H__
#define __TCT_PLATFORM-PERMISSION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void CTs_platform_permission_appmanager_startup(void);
extern void CTs_platform_permission_appmanager_cleanup(void);
extern void CTs_platform_permission_Application_startup(void);
extern void CTs_platform_permission_Application_cleanup(void);
extern void CTs_platform_permission_audioio_startup(void);
extern void CTs_platform_permission_audioio_cleanup(void);
extern void CTs_platform_permission_badge_startup(void);
extern void CTs_platform_permission_badge_cleanup(void);
extern void CTs_platform_permission_bluetooth_startup(void);
extern void CTs_platform_permission_bluetooth_cleanup(void);
extern void CTs_platform_permission_camera_startup(void);
extern void CTs_platform_permission_camera_cleanup(void);
extern void CTs_platform_permission_connection_startup(void);
extern void CTs_platform_permission_connection_cleanup(void);
extern void CTs_platform_permission_datacontrol_startup(void);
extern void CTs_platform_permission_datacontrol_cleanup(void);
extern void CTs_platform_permission_device_startup(void);
extern void CTs_platform_permission_device_cleanup(void);
extern void CTs_platform_permission_locationmanager_startup(void);
extern void CTs_platform_permission_locationmanager_cleanup(void);
extern void CTs_platform_permission_mediacontent_startup(void);
extern void CTs_platform_permission_mediacontent_cleanup(void);
extern void CTs_platform_permission_messages_startup(void);
extern void CTs_platform_permission_messages_cleanup(void);
extern void CTs_platform_permission_nfc_startup(void);
extern void CTs_platform_permission_nfc_cleanup(void);
extern void CTs_platform_permission_notification_startup(void);
extern void CTs_platform_permission_notification_cleanup(void);
extern void CTs_platform_permission_packagemanager_startup(void);
extern void CTs_platform_permission_packagemanager_cleanup(void);
extern void CTs_platform_permission_recorder_startup(void);
extern void CTs_platform_permission_recorder_cleanup(void);
extern void CTs_platform_permission_sensor_startup(void);
extern void CTs_platform_permission_sensor_cleanup(void);
extern void CTs_platform_permission_smartcard_startup(void);
extern void CTs_platform_permission_smartcard_cleanup(void);
extern void CTs_platform_permission_soundmanager_startup(void);
extern void CTs_platform_permission_soundmanager_cleanup(void);
extern void CTs_platform_permission_sppc_startup(void);
extern void CTs_platform_permission_sppc_cleanup(void);
extern void CTs_platform_permission_stt_startup(void);
extern void CTs_platform_permission_stt_cleanup(void);
extern void CTs_platform_permission_telephony_startup(void);
extern void CTs_platform_permission_telephony_cleanup(void);
extern void CTs_platform_permission_widgetservice_startup(void);
extern void CTs_platform_permission_widgetservice_cleanup(void);
extern void CTs_platform_permission_WidgetViewer_startup(void);
extern void CTs_platform_permission_WidgetViewer_cleanup(void);
extern void CTs_platform_permission_http_startup(void);
extern void CTs_platform_permission_http_cleanup(void);
extern void CTs_platform_permission_media_streamer_startup(void);
extern void CTs_platform_permission_media_streamer_cleanup(void);
extern void CTs_platform_permission_wifi_manager_startup(void);
extern void CTs_platform_permission_wifi_manager_cleanup(void);

extern int CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_cancel_all(void);
extern int CTc_Application_PrivilegeAlarmGet_alarm_get_app_control(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_period(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date(void);
extern int CTc_AudioIO_PrivilegeRecorder_Create(void);
extern int CTc_Badge_PrivilegeNotification_add(void);
extern int CTc_Badge_PrivilegeNotification_new(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_set_name(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_gatt_connect(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect(void);
extern int CTc_Camera_Privilege_Camera(void);
extern int CTc_Connection_Privilege_NetworkGet(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_add(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_get(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_set(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb(void);
extern int CTc_DataControl_PrivilegeDataControlprovider_add_cb(void);
extern int CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti(void);
extern int CTc_Device_PrivilegeDisplay_get_numbers(void);
extern int CTc_Device_PrivilegePower_wakeup(void);
extern int CTc_Device_PrivilegeDisplay_state_change(void);
extern int CTc_Device_PrivilegeDisplay_get_max_brightness(void);
extern int CTc_Device_PrivilegeDisplay_get_brightness(void);
extern int CTc_Device_PrivilegeFlash_get_max_brightness(void);
extern int CTc_Device_PrivilegeFlash_set_brightness(void);
extern int CTc_Device_PrivilegeFlash_get_brightness(void);
extern int CTc_Device_PrivilegeHaptic_open(void);
extern int CTc_Device_PrivilegeLed_play_stop(void);
extern int CTc_Device_PrivilegePower_request_release(void);
extern int CTc_Location_PrivilegeLocation_start(void);
extern int CTc_Location_PrivilegeLocation_set_satelite_updated_cb(void);
extern int CTc_Location_PrivilegeLocation_enable_mock_location(void);
extern int CTc_Location_PrivilegeLocation_set_mock_location(void);
extern int CTc_Location_PrivilegeLocation_clear_mock_location(void);
extern int CTc_Location_PrivilegeLocation_location_manager_request_single_location(void);
extern int CTc_MediaContent_PrivilegeMediaStorage_scan_folder(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db(void);
extern int CTc_Messaging_PrivilegeMessageRead_open_close_service(void);
extern int CTc_nfc_Privilege_Nfc_HandlerEnable(void);
extern int CTc_nfc_Privilege_Nfc_IsHandlerEnabled(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_GetSeType(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_SetSeType(void);
extern int CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch(void);
extern int CTc_Nfc_Privilege_Nfc_GetConnectedTag(void);
extern int CTc_Nfc_Privilege_Nfc_GetConnectedTarget(void);
extern int CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation(void);
extern int CTc_Nfc_PrivilegeNfc_se_set_preferred_handler(void);
extern int CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler(void);
extern int CTc_Notification_PrivilegeNotification_delete(void);
extern int CTc_Notification_PrivilegeNotification_delete_all(void);
extern int CTc_Notification_PrivilegeNotification_post(void);
extern int CTc_Notification_PrivilegeNotification_load_by_tag(void);
extern int CTc_Notification_PrivilegeNotification_update(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_create(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type(void);
extern int CTc_Recorder_PrivilegeAudioRecorder_create(void);
extern int CTc_Sensor_PrivilegeHealthInfo_get_default_sensor(void);
extern int CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list(void);
extern int CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize(void);
extern int CTc_SoundManager_PrivilegeVolumeSet_getvolume(void);
extern int CTc_Messaging_PrivilegePush_service_connect(void);
extern int CTc_Messaging_PrivilegePush_app_control_to_noti_data(void);
extern int CTc_Messaging_PrivilegePush_app_control_to_notification(void);
extern int CTc_Stt_PrivilegeRecorder_create_destroy(void);
extern int CTc_Telephony_Privilege_Telephony_get_state(void);
extern int CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription(void);
extern int CTc_Telephony_Privilege_Telephony_GetCallList(void);
extern int CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetCellId(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetLac(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetMcc(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetMnc(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkName(void);
extern int CTc_Telephony_Privilege_Telephony_RoamingStatus(void);
extern int CTc_Telephony_Privilege_Telephony_GetRssi(void);
extern int CTc_Telephony_Privilege_Telephony_GetServiceState(void);
extern int CTc_Telephony_Privilege_Telephony_GetType(void);
extern int CTc_Telephony_Privilege_Telephony_GetPsType(void);
extern int CTc_Telephony_Privilege_Telephony_GetNetworkNameOption(void);
extern int CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs(void);
extern int CTc_Telephony_Privilege_Telephony_GetDefaultSubs(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetMsin(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetOperator(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSpn(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo(void);
extern int CTc_Telephony_Privilege_Telephony_SimIsChanged(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetApplicationList(void);
extern int CTc_Telephony_Privilege_Telephony_sim_get_lock_state(void);
extern int CTc_Telephony_Privilege_Telephony_network_get_selection_mode(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_icon(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_package_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_name(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types(void);
extern int CTc_WidgetViewer_PrivilegeWidgetViewer(void);
extern int CTc_Http_PrivilegeInternet_http_transaction_submit(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params(void);
extern int CTc_Wifi_Manager_Privilege_NetworkGet(void);

testcase tc_array[] = {
	{"CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request",CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request,CTs_platform_permission_appmanager_startup,CTs_platform_permission_appmanager_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay",CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_cancel_all",CTc_Application_PrivilegeAlarmSet_alarm_cancel_all,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmGet_alarm_get_app_control",CTc_Application_PrivilegeAlarmGet_alarm_get_app_control,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date",CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_period",CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_period,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date",CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_AudioIO_PrivilegeRecorder_Create",CTc_AudioIO_PrivilegeRecorder_Create,CTs_platform_permission_audioio_startup,CTs_platform_permission_audioio_cleanup},
	{"CTc_Badge_PrivilegeNotification_add",CTc_Badge_PrivilegeNotification_add,CTs_platform_permission_badge_startup,CTs_platform_permission_badge_cleanup},
	{"CTc_Badge_PrivilegeNotification_new",CTc_Badge_PrivilegeNotification_new,CTs_platform_permission_badge_startup,CTs_platform_permission_badge_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_set_name",CTc_Bluetooth_PrivilegeBluetooth_set_name,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering",CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm",CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination",CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan",CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode",CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data",CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_gatt_connect",CTc_Bluetooth_PrivilegeBluetooth_gatt_connect,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect",CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Camera_Privilege_Camera",CTc_Camera_Privilege_Camera,CTs_platform_permission_camera_startup,CTs_platform_permission_camera_cleanup},
	{"CTc_Connection_Privilege_NetworkGet",CTc_Connection_Privilege_NetworkGet,CTs_platform_permission_connection_startup,CTs_platform_permission_connection_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_add",CTc_DataControl_PrivilegeDataControlConsumer_map_add,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_get",CTc_DataControl_PrivilegeDataControlConsumer_map_get,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page",CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_set",CTc_DataControl_PrivilegeDataControlConsumer_map_set,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb",CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb",CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update",CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb",CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlprovider_add_cb",CTc_DataControl_PrivilegeDataControlprovider_add_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti",CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_numbers",CTc_Device_PrivilegeDisplay_get_numbers,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegePower_wakeup",CTc_Device_PrivilegePower_wakeup,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_state_change",CTc_Device_PrivilegeDisplay_state_change,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_max_brightness",CTc_Device_PrivilegeDisplay_get_max_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_brightness",CTc_Device_PrivilegeDisplay_get_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_get_max_brightness",CTc_Device_PrivilegeFlash_get_max_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_set_brightness",CTc_Device_PrivilegeFlash_set_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_get_brightness",CTc_Device_PrivilegeFlash_get_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeHaptic_open",CTc_Device_PrivilegeHaptic_open,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeLed_play_stop",CTc_Device_PrivilegeLed_play_stop,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegePower_request_release",CTc_Device_PrivilegePower_request_release,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Location_PrivilegeLocation_start",CTc_Location_PrivilegeLocation_start,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_set_satelite_updated_cb",CTc_Location_PrivilegeLocation_set_satelite_updated_cb,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_enable_mock_location",CTc_Location_PrivilegeLocation_enable_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_set_mock_location",CTc_Location_PrivilegeLocation_set_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_clear_mock_location",CTc_Location_PrivilegeLocation_clear_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_location_manager_request_single_location",CTc_Location_PrivilegeLocation_location_manager_request_single_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_MediaContent_PrivilegeMediaStorage_scan_folder",CTc_MediaContent_PrivilegeMediaStorage_scan_folder,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db",CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_Messaging_PrivilegeMessageRead_open_close_service",CTc_Messaging_PrivilegeMessageRead_open_close_service,CTs_platform_permission_messages_startup,CTs_platform_permission_messages_cleanup},
	{"CTc_nfc_Privilege_Nfc_HandlerEnable",CTc_nfc_Privilege_Nfc_HandlerEnable,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_nfc_Privilege_Nfc_IsHandlerEnabled",CTc_nfc_Privilege_Nfc_IsHandlerEnabled,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent",CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_GetSeType",CTc_Nfc_Privilege_NfcCardEmulation_GetSeType,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_SetSeType",CTc_Nfc_Privilege_NfcCardEmulation_SetSeType,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer",CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode",CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid",CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid",CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory",CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch",CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_GetConnectedTag",CTc_Nfc_Privilege_Nfc_GetConnectedTag,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_GetConnectedTarget",CTc_Nfc_Privilege_Nfc_GetConnectedTarget,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation",CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_PrivilegeNfc_se_set_preferred_handler",CTc_Nfc_PrivilegeNfc_se_set_preferred_handler,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler",CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Notification_PrivilegeNotification_delete",CTc_Notification_PrivilegeNotification_delete,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_delete_all",CTc_Notification_PrivilegeNotification_delete_all,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_post",CTc_Notification_PrivilegeNotification_post,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_load_by_tag",CTc_Notification_PrivilegeNotification_load_by_tag,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_update",CTc_Notification_PrivilegeNotification_update,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_create",CTc_PackageInfo_PrivilegePackagemanagerInfo_create,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create",CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id",CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info",CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id",CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type",CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_Recorder_PrivilegeAudioRecorder_create",CTc_Recorder_PrivilegeAudioRecorder_create,CTs_platform_permission_recorder_startup,CTs_platform_permission_recorder_cleanup},
	{"CTc_Sensor_PrivilegeHealthInfo_get_default_sensor",CTc_Sensor_PrivilegeHealthInfo_get_default_sensor,CTs_platform_permission_sensor_startup,CTs_platform_permission_sensor_cleanup},
	{"CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list",CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list,CTs_platform_permission_sensor_startup,CTs_platform_permission_sensor_cleanup},
	{"CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize",CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize,CTs_platform_permission_smartcard_startup,CTs_platform_permission_smartcard_cleanup},
	{"CTc_SoundManager_PrivilegeVolumeSet_getvolume",CTc_SoundManager_PrivilegeVolumeSet_getvolume,CTs_platform_permission_soundmanager_startup,CTs_platform_permission_soundmanager_cleanup},
	{"CTc_Messaging_PrivilegePush_service_connect",CTc_Messaging_PrivilegePush_service_connect,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Messaging_PrivilegePush_app_control_to_noti_data",CTc_Messaging_PrivilegePush_app_control_to_noti_data,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Messaging_PrivilegePush_app_control_to_notification",CTc_Messaging_PrivilegePush_app_control_to_notification,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Stt_PrivilegeRecorder_create_destroy",CTc_Stt_PrivilegeRecorder_create_destroy,CTs_platform_permission_stt_startup,CTs_platform_permission_stt_cleanup},
	{"CTc_Telephony_Privilege_Telephony_get_state",CTc_Telephony_Privilege_Telephony_get_state,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription",CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetCallList",CTc_Telephony_Privilege_Telephony_GetCallList,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus",CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetCellId",CTc_Telephony_Privilege_Telephony_NetworkGetCellId,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetLac",CTc_Telephony_Privilege_Telephony_NetworkGetLac,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetMcc",CTc_Telephony_Privilege_Telephony_NetworkGetMcc,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetMnc",CTc_Telephony_Privilege_Telephony_NetworkGetMnc,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkName",CTc_Telephony_Privilege_Telephony_NetworkName,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_RoamingStatus",CTc_Telephony_Privilege_Telephony_RoamingStatus,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetRssi",CTc_Telephony_Privilege_Telephony_GetRssi,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetServiceState",CTc_Telephony_Privilege_Telephony_GetServiceState,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetType",CTc_Telephony_Privilege_Telephony_GetType,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetPsType",CTc_Telephony_Privilege_Telephony_GetPsType,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetNetworkNameOption",CTc_Telephony_Privilege_Telephony_GetNetworkNameOption,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs",CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetDefaultSubs",CTc_Telephony_Privilege_Telephony_GetDefaultSubs,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetMsin",CTc_Telephony_Privilege_Telephony_SimGetMsin,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetOperator",CTc_Telephony_Privilege_Telephony_SimGetOperator,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSpn",CTc_Telephony_Privilege_Telephony_SimGetSpn,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo",CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimIsChanged",CTc_Telephony_Privilege_Telephony_SimIsChanged,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId",CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetApplicationList",CTc_Telephony_Privilege_Telephony_SimGetApplicationList,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_sim_get_lock_state",CTc_Telephony_Privilege_Telephony_sim_get_lock_state,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_network_get_selection_mode",CTc_Telephony_Privilege_Telephony_network_get_selection_mode,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_icon",CTc_WidgetService_PrivilegeWidgetViewer_get_icon,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app",CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect",CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_package_id",CTc_WidgetService_PrivilegeWidgetViewer_get_package_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_name",CTc_WidgetService_PrivilegeWidgetViewer_get_name,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes",CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types",CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetViewer_PrivilegeWidgetViewer",CTc_WidgetViewer_PrivilegeWidgetViewer,CTs_platform_permission_WidgetViewer_startup,CTs_platform_permission_WidgetViewer_cleanup},
	{"CTc_Http_PrivilegeInternet_http_transaction_submit",CTc_Http_PrivilegeInternet_http_transaction_submit,CTs_platform_permission_http_startup,CTs_platform_permission_http_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src",CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink",CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param",CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params",CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_Wifi_Manager_Privilege_NetworkGet",CTc_Wifi_Manager_Privilege_NetworkGet,CTs_platform_permission_wifi_manager_startup,CTs_platform_permission_wifi_manager_cleanup},
	{NULL, NULL}
};

#endif // __TCT_PLATFORM-PERMISSION-NATIVE_H__
