//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_PLATFORM-PERMISSION-NATIVE_H__
#define __TCT_PLATFORM-PERMISSION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void CTs_platform_permission_ime_startup(void);
extern void CTs_platform_permission_ime_cleanup(void);
extern void CTs_platform_permission_syncmanager_startup(void);
extern void CTs_platform_permission_syncmanager_cleanup(void);
extern void CTs_platform_permission_context_startup(void);
extern void CTs_platform_permission_context_cleanup(void);
extern void CTs_platform_permission_notification_startup(void);
extern void CTs_platform_permission_notification_cleanup(void);
extern void CTs_platform_permission_datacontrol_startup(void);
extern void CTs_platform_permission_datacontrol_cleanup(void);
extern void CTs_platform_permission_device_startup(void);
extern void CTs_platform_permission_device_cleanup(void);
extern void CTs_platform_permission_email_startup(void);
extern void CTs_platform_permission_email_cleanup(void);
extern void CTs_platform_permission_locationmanager_startup(void);
extern void CTs_platform_permission_locationmanager_cleanup(void);
extern void CTs_platform_permission_messages_startup(void);
extern void CTs_platform_permission_messages_cleanup(void);
extern void CTs_platform_permission_packagemanager_startup(void);
extern void CTs_platform_permission_packagemanager_cleanup(void);
extern void CTs_platform_permission_recorder_startup(void);
extern void CTs_platform_permission_recorder_cleanup(void);
extern void CTs_platform_permission_runtimeinfo_startup(void);
extern void CTs_platform_permission_runtimeinfo_cleanup(void);
extern void CTs_platform_permission_sensor_startup(void);
extern void CTs_platform_permission_sensor_cleanup(void);
extern void CTs_platform_permission_soundmanager_startup(void);
extern void CTs_platform_permission_soundmanager_cleanup(void);
extern void CTs_platform_permission_smartcard_startup(void);
extern void CTs_platform_permission_smartcard_cleanup(void);
extern void CTs_platform_permission_stt_startup(void);
extern void CTs_platform_permission_stt_cleanup(void);
extern void CTs_platform_permission_badge_startup(void);
extern void CTs_platform_permission_badge_cleanup(void);
extern void CTs_platform_permission_shortcut_startup(void);
extern void CTs_platform_permission_shortcut_cleanup(void);
extern void CTs_platform_permission_sppc_startup(void);
extern void CTs_platform_permission_sppc_cleanup(void);
extern void CTs_platform_permission_bluetooth_startup(void);
extern void CTs_platform_permission_bluetooth_cleanup(void);
extern void CTs_platform_permission_audioio_startup(void);
extern void CTs_platform_permission_audioio_cleanup(void);
extern void CTs_platform_permission_camera_startup(void);
extern void CTs_platform_permission_camera_cleanup(void);
extern void CTs_platform_permission_inputmethodmanager_startup(void);
extern void CTs_platform_permission_inputmethodmanager_cleanup(void);
extern void CTs_platform_permission_connection_startup(void);
extern void CTs_platform_permission_connection_cleanup(void);
extern void CTs_platform_permission_thumbnailutil_startup(void);
extern void CTs_platform_permission_thumbnailutil_cleanup(void);
extern void CTs_platform_permission_urldownload_startup(void);
extern void CTs_platform_permission_urldownload_cleanup(void);
extern void CTs_platform_permission_wifidirect_startup(void);
extern void CTs_platform_permission_wifidirect_cleanup(void);
extern void CTs_platform_permission_appmanager_startup(void);
extern void CTs_platform_permission_appmanager_cleanup(void);
extern void CTs_platform_permission_Libfeedback_startup(void);
extern void CTs_platform_permission_Libfeedback_cleanup(void);
extern void CTs_platform_permission_telephony_startup(void);
extern void CTs_platform_permission_telephony_cleanup(void);
extern void CTs_platform_permission_nfc_startup(void);
extern void CTs_platform_permission_nfc_cleanup(void);
extern void CTs_platform_permission_MediaController_startup(void);
extern void CTs_platform_permission_MediaController_cleanup(void);
extern void CTs_platform_permission_mediacontent_startup(void);
extern void CTs_platform_permission_mediacontent_cleanup(void);
extern void CTs_platform_permission_VoiceControl_startup(void);
extern void CTs_platform_permission_VoiceControl_cleanup(void);
extern void CTs_platform_permission_widgetservice_startup(void);
extern void CTs_platform_permission_widgetservice_cleanup(void);
extern void CTs_platform_permission_WidgetViewer_startup(void);
extern void CTs_platform_permission_WidgetViewer_cleanup(void);
extern void CTs_platform_permission_Application_startup(void);
extern void CTs_platform_permission_Application_cleanup(void);
extern void CTs_platform_permission_MapsService_startup(void);
extern void CTs_platform_permission_MapsService_cleanup(void);
extern void CTs_platform_permission_Attach_Panel_startup(void);
extern void CTs_platform_permission_Attach_Panel_cleanup(void);
extern void CTs_platform_permission_accountsvc_startup(void);
extern void CTs_platform_permission_accountsvc_cleanup(void);
extern void CTs_platform_permission_ContactsService_startup(void);
extern void CTs_platform_permission_ContactsService_cleanup(void);
extern void CTs_platform_permission_CalendarService_startup(void);
extern void CTs_platform_permission_CalendarService_cleanup(void);
extern void CTs_platform_permission_OAuth2_startup(void);
extern void CTs_platform_permission_OAuth2_cleanup(void);
extern void CTs_platform_permission_vpn_service_startup(void);
extern void CTs_platform_permission_vpn_service_cleanup(void);
extern void CTs_platform_permission_efl_util_startup(void);
extern void CTs_platform_permission_efl_util_cleanup(void);
extern void CTs_platform_permission_iotcon_startup(void);
extern void CTs_platform_permission_iotcon_cleanup(void);
extern void CTs_platform_permission_phonenumber_utils_startup(void);
extern void CTs_platform_permission_phonenumber_utils_cleanup(void);
extern void CTs_platform_permission_media_streamer_startup(void);
extern void CTs_platform_permission_media_streamer_cleanup(void);
extern void CTs_platform_permission_http_startup(void);
extern void CTs_platform_permission_http_cleanup(void);
extern void CTs_platform_permission_wifi_manager_startup(void);
extern void CTs_platform_permission_wifi_manager_cleanup(void);

extern int CTc_IME_PrivilegeIME_IME_Run(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Focus_In_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Focus_Out_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Surrounding_Text_Updated_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Input_Context_Reset_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Cursor_Position_Updated_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Language_Requested_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Language_Set_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Set_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Layout_Set_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_Type_Set_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_State_Set_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Geometry_Requested_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Process_Key_Event_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Display_Language_Changed_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Rotation_Degree_Changed_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Accessibility_State_Changed_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Created_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Destroyed_cb(void);
extern int CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Requested_cb(void);
extern int CTc_SyncManager_PrivilegeAlarmSet(void);
extern int CTc_SyncManager_PrivilegeContactRead_PrivilegeCalendarRead(void);
extern int CTc_Context_PrivilegeApphistoryRead_PrivilegeMediahistoryRead(void);
extern int CTc_Context_PrivilegeAppManagerLaunch_PrivilegeCall_set_action(void);
extern int CTc_Context_PrivilegeNotification(void);
extern int CTc_Notification_PrivilegeNotification_delete(void);
extern int CTc_Notification_PrivilegeNotification_delete_all(void);
extern int CTc_Notification_PrivilegeNotification_post(void);
extern int CTc_Notification_PrivilegeNotification_load_by_tag(void);
extern int CTc_Notification_PrivilegeNotification_update(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_add(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_get(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_set(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update(void);
extern int CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb(void);
extern int CTc_DataControl_PrivilegeDataControlprovider_add_cb(void);
extern int CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti(void);
extern int CTc_Device_PrivilegeDisplay_get_numbers(void);
extern int CTc_Device_PrivilegePower_wakeup(void);
extern int CTc_Device_PrivilegeDisplay_state_change(void);
extern int CTc_Device_PrivilegeDisplay_get_max_brightness(void);
extern int CTc_Device_PrivilegeDisplay_get_brightness(void);
extern int CTc_Device_PrivilegeFlash_get_max_brightness(void);
extern int CTc_Device_PrivilegeFlash_set_brightness(void);
extern int CTc_Device_PrivilegeFlash_get_brightness(void);
extern int CTc_Device_PrivilegeHaptic_open(void);
extern int CTc_Device_PrivilegeLed_play_stop(void);
extern int CTc_Device_PrivilegePower_request_release(void);
extern int CTc_Device_Privilege_ir_is_available(void);
extern int CTc_Device_Privilege_ir_transmit(void);
extern int CTc_Email_PrivilegeMessagingEmail_create_message(void);
extern int CTc_Location_PrivilegeLocation_start(void);
extern int CTc_Location_PrivilegeLocation_set_satelite_updated_cb(void);
extern int CTc_Location_PrivilegeLocation_enable_mock_location(void);
extern int CTc_Location_PrivilegeLocation_set_mock_location(void);
extern int CTc_Location_PrivilegeLocation_clear_mock_location(void);
extern int CTc_Messaging_PrivilegeMessageRead_open_close_service(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_create(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id(void);
extern int CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type(void);
extern int CTc_Recorder_PrivilegeAudioRecorder_create(void);
extern int CTc_RuntimeInfo_PrivilegeSystemMonitor_cpu_ucage(void);
extern int CTc_RuntimeInfo_PrivilegeSystemMonitor_get_process_memory_info(void);
extern int CTc_Sensor_PrivilegeHealthInfo_get_default_sensor(void);
extern int CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list(void);
extern int CTc_SoundManager_PrivilegeVolumeSet_getvolume(void);
extern int CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize(void);
extern int CTc_Stt_PrivilegeRecorder_create_destroy(void);
extern int CTc_Badge_PrivilegeNotification_add(void);
extern int CTc_Badge_PrivilegeNotification_new(void);
extern int CTc_Shortcut_PrivilegeShortcut_add_to_home(void);
extern int CTc_Shortcut_PrivilegeShortcut_set_request_cb(void);
extern int CTc_Shortcut_PrivilegeShortcut_add_to_home_widget(void);
extern int CTc_Shortcut_PrivilegeShortcut_get_list(void);
extern int CTc_Messaging_PrivilegePush_service_connect(void);
extern int CTc_Messaging_PrivilegePush_app_control_to_noti_data(void);
extern int CTc_Messaging_PrivilegePush_app_control_to_notification(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_set_name(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_le_start_advertising_new(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_gatt_connect(void);
extern int CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect(void);
extern int CTc_AudioIO_PrivilegeRecorder_Create(void);
extern int CTc_Camera_Privilege_Camera(void);
extern int CTc_IME_Manager_GetActiveIME(void);
extern int CTc_IME_Manager_Show_IME_Selector(void);
extern int CTc_IME_Manager_Show_IME_List(void);
extern int CTc_IME_MANAGER_GET_ENABLED_IME_COUNT(void);
extern int CTc_Connection_Privilege_NetworkGet(void);
extern int CTc_Urldownload_Privilege_Download(void);
extern int CTc_Network_Privilege_WifiDirect(void);
extern int CTc_Network_Privilege_WifiDirect_display_port(void);
extern int CTc_Network_Privilege_WifiDirect_display_hdcp(void);
extern int CTc_Network_Privilege_WifiDirect_display_thoughput(void);
extern int CTc_Network_Privilege_WifiDirect_display_type(void);
extern int CTc_Network_Privilege_WifiDirect_display_availability(void);
extern int CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request(void);
extern int CTc_Libfeedback_PrivilegeHaptic_feedback_is_supported_pattern(void);
extern int CTc_Libfeedback_PrivilegeHaptic_feedback_play_type(void);
extern int CTc_Telephony_Privilege_Telephony_get_state(void);
extern int CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription(void);
extern int CTc_Telephony_Privilege_Telephony_GetCallList(void);
extern int CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetCellId(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetLac(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetMcc(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkGetMnc(void);
extern int CTc_Telephony_Privilege_Telephony_NetworkName(void);
extern int CTc_Telephony_Privilege_Telephony_RoamingStatus(void);
extern int CTc_Telephony_Privilege_Telephony_GetRssi(void);
extern int CTc_Telephony_Privilege_Telephony_GetServiceState(void);
extern int CTc_Telephony_Privilege_Telephony_GetType(void);
extern int CTc_Telephony_Privilege_Telephony_GetPsType(void);
extern int CTc_Telephony_Privilege_Telephony_GetNetworkNameOption(void);
extern int CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs(void);
extern int CTc_Telephony_Privilege_Telephony_GetDefaultSubs(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetMsin(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetOperator(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSpn(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo(void);
extern int CTc_Telephony_Privilege_Telephony_SimIsChanged(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId(void);
extern int CTc_Telephony_Privilege_Telephony_SimGetApplicationList(void);
extern int CTc_Telephony_Privilege_Telephony_sim_get_lock_state(void);
extern int CTc_Telephony_Privilege_Telephony_network_get_selection_mode(void);
extern int CTc_nfc_Privilege_Nfc_HandlerEnable(void);
extern int CTc_nfc_Privilege_Nfc_IsHandlerEnabled(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_GetSeType(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_SetSeType(void);
extern int CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory(void);
extern int CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch(void);
extern int CTc_Nfc_Privilege_Nfc_GetConnectedTag(void);
extern int CTc_Nfc_Privilege_Nfc_GetConnectedTarget(void);
extern int CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation(void);
extern int CTc_Nfc_PrivilegeNfc_se_set_preferred_handler(void);
extern int CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler(void);
extern int CTc_MediaController_PrivilegeMediaControllerClient(void);
extern int CTc_MediaContent_PrivilegeMediaStorage_scan_folder(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db(void);
extern int CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db(void);
extern int CTc_VoiceControl_PrivilegeRecorder(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_icon(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_package_id(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_name(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes(void);
extern int CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types(void);
extern int CTc_WidgetViewer_PrivilegeWidgetViewer(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date(void);
extern int CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date(void);
extern int CTc_MapsService_PrivilegeMapSservice_maps_service_create(void);
extern int CTc_Attach_Panel_Privileges_Add_Content_Category(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_locale(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_app_id_exist(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_supported_feature(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_provider_feature_by_app_id(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_account_by_account_id(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_update_sync_status_by_id(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_insert_to_db(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_account_query_account_by_package_name(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_account_delete_from_db_by_package_name(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_account_type_query_by_app_id(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_app_id(void);
extern int CTc_AccountManager_PrivilegeAccountReadWrite_foreach_account_type_from_db(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_records(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_record(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_query(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_range(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_get_all_records(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_get_current_version(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count_with_query(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_get_records_with_query(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_db_add_changed_cb(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_group_set_group_order(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_person_set_default_property(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_person_link_person(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_person_reset_usage(void);
extern int CTc_ContactsService_PrivilegeCallhistoryWrite_contacts_phone_log_reset_statistics(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_sorting_order(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_sorting_order(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_setting_add_name_display_order_changed_cb(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_display_order(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_display_order(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_contacts_setting_add_name_sorting_order_changed_cb(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_sim_import_all_contacts(void);
extern int CTc_ContactsService_PrivilegeContactRead_contacts_sim_get_initialization_status(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_contact_id(void);
extern int CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_account_id(void);
extern int CTc_ContactsService_PrivilegeContacts_person_get_aggregation_suggestions(void);
extern int CTc_ContactsService_PrivilegeContacts_phone_log_reset_statistics_by_sim(void);
extern int CTc_ContactsService_PrivilegeContacts_vcard_get_limit_size_of_photo(void);
extern int CTc_ContactsService_PrivilegeContacts_vcard_set_limit_size_of_photo(void);
extern int CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_record(void);
extern int CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_records(void);
extern int CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_vcalendars(void);
extern int CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_record(void);
extern int CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_records(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_add_changed_cb(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_all_records(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_current_version(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_last_change_version(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_records_with_query(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count_with_query(void);
extern int CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count(void);
extern int CTc_OAuth2_PrivilegeInternet_Request_Token(void);
extern int CTc_OAuth2_PrivilegeInternet_Authorization_Grant(void);
extern int CTc_OAuth2_PrivilegeInternet_Request_Access_Token(void);
extern int CTc_OAuth2_PrivilegeInternet_Refresh_Access_Token(void);
extern int CTc_OAuth2_PrivilegeInternet_Clear_Cookies(void);
extern int CTc_OAuth2_PrivilegeInternet_Clear_Cache(void);
extern int CTc_VpnService_PrivilegeVpnsvc_init(void);
extern int CTc_EflUtil_Privilege_efl_util_set_window_brightness(void);
extern int CTc_Iotcon_PrivilegeNetworkGet_initialize_deinitialize_p(void);
extern int CTc_PhoneNumber_PrivilegePhoneNumberUtils_get_normalized_number(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param(void);
extern int CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params(void);
extern int CTc_Http_PrivilegeInternet_http_transaction_submit(void);
extern int CTc_Wifi_Manager_Privilege_NetworkGet(void);

testcase tc_array[] = {
	{"CTc_IME_PrivilegeIME_IME_Run",CTc_IME_PrivilegeIME_IME_Run,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Focus_In_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Focus_In_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Focus_Out_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Focus_Out_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Surrounding_Text_Updated_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Surrounding_Text_Updated_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Input_Context_Reset_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Input_Context_Reset_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Cursor_Position_Updated_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Cursor_Position_Updated_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Language_Requested_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Language_Requested_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Language_Set_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Language_Set_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Set_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Set_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Layout_Set_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Layout_Set_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_Type_Set_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_Type_Set_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_State_Set_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Return_Key_State_Set_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Geometry_Requested_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Geometry_Requested_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Process_Key_Event_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Process_Key_Event_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Display_Language_Changed_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Display_Language_Changed_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Rotation_Degree_Changed_cb",CTc_IME_PrivilegeIME_IME_Event_Rotation_Degree_Changed_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Accessibility_State_Changed_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Accessibility_State_Changed_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Created_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Created_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Destroyed_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Option_Window_Destroyed_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Requested_cb",CTc_IME_PrivilegeIME_IME_Event_Set_Imdata_Requested_cb,CTs_platform_permission_ime_startup,CTs_platform_permission_ime_cleanup},
	{"CTc_SyncManager_PrivilegeAlarmSet",CTc_SyncManager_PrivilegeAlarmSet,CTs_platform_permission_syncmanager_startup,CTs_platform_permission_syncmanager_cleanup},
	{"CTc_SyncManager_PrivilegeContactRead_PrivilegeCalendarRead",CTc_SyncManager_PrivilegeContactRead_PrivilegeCalendarRead,CTs_platform_permission_syncmanager_startup,CTs_platform_permission_syncmanager_cleanup},
	{"CTc_Context_PrivilegeApphistoryRead_PrivilegeMediahistoryRead",CTc_Context_PrivilegeApphistoryRead_PrivilegeMediahistoryRead,CTs_platform_permission_context_startup,CTs_platform_permission_context_cleanup},
	{"CTc_Context_PrivilegeAppManagerLaunch_PrivilegeCall_set_action",CTc_Context_PrivilegeAppManagerLaunch_PrivilegeCall_set_action,CTs_platform_permission_context_startup,CTs_platform_permission_context_cleanup},
	{"CTc_Context_PrivilegeNotification",CTc_Context_PrivilegeNotification,CTs_platform_permission_context_startup,CTs_platform_permission_context_cleanup},
	{"CTc_Notification_PrivilegeNotification_delete",CTc_Notification_PrivilegeNotification_delete,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_delete_all",CTc_Notification_PrivilegeNotification_delete_all,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_post",CTc_Notification_PrivilegeNotification_post,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_load_by_tag",CTc_Notification_PrivilegeNotification_load_by_tag,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_Notification_PrivilegeNotification_update",CTc_Notification_PrivilegeNotification_update,CTs_platform_permission_notification_startup,CTs_platform_permission_notification_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_add",CTc_DataControl_PrivilegeDataControlConsumer_map_add,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_get",CTc_DataControl_PrivilegeDataControlConsumer_map_get,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page",CTc_DataControl_PrivilegeDataControlConsumer_map_get_with_page,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_set",CTc_DataControl_PrivilegeDataControlConsumer_map_set,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb",CTc_DataControl_PrivilegeDataControlConsumer_map_register_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb",CTc_DataControl_PrivilegeDataControlConsumer_sql_insert_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update",CTc_DataControl_PrivilegeDataControlConsumer_data_control_sql_update,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb",CTc_DataControl_PrivilegeDataControlConsumer_provider_sql_register_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlprovider_add_cb",CTc_DataControl_PrivilegeDataControlprovider_add_cb,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti",CTc_DataControl_PrivilegeDataControlprovider_send_data_change_noti,CTs_platform_permission_datacontrol_startup,CTs_platform_permission_datacontrol_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_numbers",CTc_Device_PrivilegeDisplay_get_numbers,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegePower_wakeup",CTc_Device_PrivilegePower_wakeup,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_state_change",CTc_Device_PrivilegeDisplay_state_change,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_max_brightness",CTc_Device_PrivilegeDisplay_get_max_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeDisplay_get_brightness",CTc_Device_PrivilegeDisplay_get_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_get_max_brightness",CTc_Device_PrivilegeFlash_get_max_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_set_brightness",CTc_Device_PrivilegeFlash_set_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeFlash_get_brightness",CTc_Device_PrivilegeFlash_get_brightness,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeHaptic_open",CTc_Device_PrivilegeHaptic_open,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegeLed_play_stop",CTc_Device_PrivilegeLed_play_stop,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_PrivilegePower_request_release",CTc_Device_PrivilegePower_request_release,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_Privilege_ir_is_available",CTc_Device_Privilege_ir_is_available,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Device_Privilege_ir_transmit",CTc_Device_Privilege_ir_transmit,CTs_platform_permission_device_startup,CTs_platform_permission_device_cleanup},
	{"CTc_Email_PrivilegeMessagingEmail_create_message",CTc_Email_PrivilegeMessagingEmail_create_message,CTs_platform_permission_email_startup,CTs_platform_permission_email_cleanup},
	{"CTc_Location_PrivilegeLocation_start",CTc_Location_PrivilegeLocation_start,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_set_satelite_updated_cb",CTc_Location_PrivilegeLocation_set_satelite_updated_cb,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_enable_mock_location",CTc_Location_PrivilegeLocation_enable_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_set_mock_location",CTc_Location_PrivilegeLocation_set_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Location_PrivilegeLocation_clear_mock_location",CTc_Location_PrivilegeLocation_clear_mock_location,CTs_platform_permission_locationmanager_startup,CTs_platform_permission_locationmanager_cleanup},
	{"CTc_Messaging_PrivilegeMessageRead_open_close_service",CTc_Messaging_PrivilegeMessageRead_open_close_service,CTs_platform_permission_messages_startup,CTs_platform_permission_messages_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_create",CTc_PackageInfo_PrivilegePackagemanagerInfo_create,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create",CTc_PackageInfo_PrivilegePackagemanagerInfor_filter_create,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id",CTc_PackageInfo_PrivilegePackagemanagerInfo_get_package_id_by_app_id,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info",CTc_PackageInfo_PrivilegePackagemanagerInfo_foreach_package_info,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id",CTc_PackageInfo_PrivilegePackagemanagerInfo_preload_package_by_app_id,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type",CTc_PackageInfo_PrivilegePackagemanagerInfo_get_permission_type,CTs_platform_permission_packagemanager_startup,CTs_platform_permission_packagemanager_cleanup},
	{"CTc_Recorder_PrivilegeAudioRecorder_create",CTc_Recorder_PrivilegeAudioRecorder_create,CTs_platform_permission_recorder_startup,CTs_platform_permission_recorder_cleanup},
	{"CTc_RuntimeInfo_PrivilegeSystemMonitor_cpu_ucage",CTc_RuntimeInfo_PrivilegeSystemMonitor_cpu_ucage,CTs_platform_permission_runtimeinfo_startup,CTs_platform_permission_runtimeinfo_cleanup},
	{"CTc_RuntimeInfo_PrivilegeSystemMonitor_get_process_memory_info",CTc_RuntimeInfo_PrivilegeSystemMonitor_get_process_memory_info,CTs_platform_permission_runtimeinfo_startup,CTs_platform_permission_runtimeinfo_cleanup},
	{"CTc_Sensor_PrivilegeHealthInfo_get_default_sensor",CTc_Sensor_PrivilegeHealthInfo_get_default_sensor,CTs_platform_permission_sensor_startup,CTs_platform_permission_sensor_cleanup},
	{"CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list",CTc_Sensor_PrivilegeHealthInfo_sensor_get_sensor_list,CTs_platform_permission_sensor_startup,CTs_platform_permission_sensor_cleanup},
	{"CTc_SoundManager_PrivilegeVolumeSet_getvolume",CTc_SoundManager_PrivilegeVolumeSet_getvolume,CTs_platform_permission_soundmanager_startup,CTs_platform_permission_soundmanager_cleanup},
	{"CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize",CTc_SmartCard_PrivilegeSecureElement_initialize_deinitialize,CTs_platform_permission_smartcard_startup,CTs_platform_permission_smartcard_cleanup},
	{"CTc_Stt_PrivilegeRecorder_create_destroy",CTc_Stt_PrivilegeRecorder_create_destroy,CTs_platform_permission_stt_startup,CTs_platform_permission_stt_cleanup},
	{"CTc_Badge_PrivilegeNotification_add",CTc_Badge_PrivilegeNotification_add,CTs_platform_permission_badge_startup,CTs_platform_permission_badge_cleanup},
	{"CTc_Badge_PrivilegeNotification_new",CTc_Badge_PrivilegeNotification_new,CTs_platform_permission_badge_startup,CTs_platform_permission_badge_cleanup},
	{"CTc_Shortcut_PrivilegeShortcut_add_to_home",CTc_Shortcut_PrivilegeShortcut_add_to_home,CTs_platform_permission_shortcut_startup,CTs_platform_permission_shortcut_cleanup},
	{"CTc_Shortcut_PrivilegeShortcut_set_request_cb",CTc_Shortcut_PrivilegeShortcut_set_request_cb,CTs_platform_permission_shortcut_startup,CTs_platform_permission_shortcut_cleanup},
	{"CTc_Shortcut_PrivilegeShortcut_add_to_home_widget",CTc_Shortcut_PrivilegeShortcut_add_to_home_widget,CTs_platform_permission_shortcut_startup,CTs_platform_permission_shortcut_cleanup},
	{"CTc_Shortcut_PrivilegeShortcut_get_list",CTc_Shortcut_PrivilegeShortcut_get_list,CTs_platform_permission_shortcut_startup,CTs_platform_permission_shortcut_cleanup},
	{"CTc_Messaging_PrivilegePush_service_connect",CTc_Messaging_PrivilegePush_service_connect,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Messaging_PrivilegePush_app_control_to_noti_data",CTc_Messaging_PrivilegePush_app_control_to_noti_data,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Messaging_PrivilegePush_app_control_to_notification",CTc_Messaging_PrivilegePush_app_control_to_notification,CTs_platform_permission_sppc_startup,CTs_platform_permission_sppc_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_set_name",CTc_Bluetooth_PrivilegeBluetooth_set_name,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering",CTc_Bluetooth_PrivilegeBluetooth_bt_adapter_is_discovering,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm",CTc_Bluetooth_PrivilegeBluetooth_bt_socket_create_destroy_rfcomm,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination",CTc_Bluetooth_PrivilegeBluetooth_bt_opp_server_set_destination,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan",CTc_Bluetooth_PrivilegeBluetooth_adapter_le_start_stop_scan,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_le_start_advertising_new",CTc_Bluetooth_PrivilegeBluetooth_le_start_advertising_new,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode",CTc_Bluetooth_PrivilegeBluetooth_adapter_le_set_advertising_mode,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data",CTc_Bluetooth_PrivilegeBluetooth_adapter_set_remove_remote_oob_data,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_gatt_connect",CTc_Bluetooth_PrivilegeBluetooth_gatt_connect,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect",CTc_Bluetooth_PrivilegeBluetooth_audio_connect_disconnect,CTs_platform_permission_bluetooth_startup,CTs_platform_permission_bluetooth_cleanup},
	{"CTc_AudioIO_PrivilegeRecorder_Create",CTc_AudioIO_PrivilegeRecorder_Create,CTs_platform_permission_audioio_startup,CTs_platform_permission_audioio_cleanup},
	{"CTc_Camera_Privilege_Camera",CTc_Camera_Privilege_Camera,CTs_platform_permission_camera_startup,CTs_platform_permission_camera_cleanup},
	{"CTc_IME_Manager_GetActiveIME",CTc_IME_Manager_GetActiveIME,CTs_platform_permission_inputmethodmanager_startup,CTs_platform_permission_inputmethodmanager_cleanup},
	{"CTc_IME_Manager_Show_IME_Selector",CTc_IME_Manager_Show_IME_Selector,CTs_platform_permission_inputmethodmanager_startup,CTs_platform_permission_inputmethodmanager_cleanup},
	{"CTc_IME_Manager_Show_IME_List",CTc_IME_Manager_Show_IME_List,CTs_platform_permission_inputmethodmanager_startup,CTs_platform_permission_inputmethodmanager_cleanup},
	{"CTc_IME_MANAGER_GET_ENABLED_IME_COUNT",CTc_IME_MANAGER_GET_ENABLED_IME_COUNT,CTs_platform_permission_inputmethodmanager_startup,CTs_platform_permission_inputmethodmanager_cleanup},
	{"CTc_Connection_Privilege_NetworkGet",CTc_Connection_Privilege_NetworkGet,CTs_platform_permission_connection_startup,CTs_platform_permission_connection_cleanup},
	{"CTc_Urldownload_Privilege_Download",CTc_Urldownload_Privilege_Download,CTs_platform_permission_urldownload_startup,CTs_platform_permission_urldownload_cleanup},
	{"CTc_Network_Privilege_WifiDirect",CTc_Network_Privilege_WifiDirect,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_Network_Privilege_WifiDirect_display_port",CTc_Network_Privilege_WifiDirect_display_port,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_Network_Privilege_WifiDirect_display_hdcp",CTc_Network_Privilege_WifiDirect_display_hdcp,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_Network_Privilege_WifiDirect_display_thoughput",CTc_Network_Privilege_WifiDirect_display_thoughput,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_Network_Privilege_WifiDirect_display_type",CTc_Network_Privilege_WifiDirect_display_type,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_Network_Privilege_WifiDirect_display_availability",CTc_Network_Privilege_WifiDirect_display_availability,CTs_platform_permission_wifidirect_startup,CTs_platform_permission_wifidirect_cleanup},
	{"CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request",CTc_AppManager_Privilege_PackagemanagerInfo_app_control_send_launch_request,CTs_platform_permission_appmanager_startup,CTs_platform_permission_appmanager_cleanup},
	{"CTc_Libfeedback_PrivilegeHaptic_feedback_is_supported_pattern",CTc_Libfeedback_PrivilegeHaptic_feedback_is_supported_pattern,CTs_platform_permission_Libfeedback_startup,CTs_platform_permission_Libfeedback_cleanup},
	{"CTc_Libfeedback_PrivilegeHaptic_feedback_play_type",CTc_Libfeedback_PrivilegeHaptic_feedback_play_type,CTs_platform_permission_Libfeedback_startup,CTs_platform_permission_Libfeedback_cleanup},
	{"CTc_Telephony_Privilege_Telephony_get_state",CTc_Telephony_Privilege_Telephony_get_state,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription",CTc_Telephony_Privilege_Telephony_PrefVoiceSubscription,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetCallList",CTc_Telephony_Privilege_Telephony_GetCallList,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus",CTc_Telephony_Privilege_Telephony_ModemGetPowerStatus,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetCellId",CTc_Telephony_Privilege_Telephony_NetworkGetCellId,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetLac",CTc_Telephony_Privilege_Telephony_NetworkGetLac,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetMcc",CTc_Telephony_Privilege_Telephony_NetworkGetMcc,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkGetMnc",CTc_Telephony_Privilege_Telephony_NetworkGetMnc,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_NetworkName",CTc_Telephony_Privilege_Telephony_NetworkName,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_RoamingStatus",CTc_Telephony_Privilege_Telephony_RoamingStatus,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetRssi",CTc_Telephony_Privilege_Telephony_GetRssi,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetServiceState",CTc_Telephony_Privilege_Telephony_GetServiceState,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetType",CTc_Telephony_Privilege_Telephony_GetType,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetPsType",CTc_Telephony_Privilege_Telephony_GetPsType,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetNetworkNameOption",CTc_Telephony_Privilege_Telephony_GetNetworkNameOption,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs",CTc_Telephony_Privilege_Telephony_GetDefaultDataSubs,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_GetDefaultSubs",CTc_Telephony_Privilege_Telephony_GetDefaultSubs,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetMsin",CTc_Telephony_Privilege_Telephony_SimGetMsin,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetOperator",CTc_Telephony_Privilege_Telephony_SimGetOperator,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSpn",CTc_Telephony_Privilege_Telephony_SimGetSpn,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo",CTc_Telephony_Privilege_Telephony_SimGetSubscriptionNo,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimIsChanged",CTc_Telephony_Privilege_Telephony_SimIsChanged,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId",CTc_Telephony_Privilege_Telephony_SimGetSubscriptionId,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_SimGetApplicationList",CTc_Telephony_Privilege_Telephony_SimGetApplicationList,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_sim_get_lock_state",CTc_Telephony_Privilege_Telephony_sim_get_lock_state,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_Telephony_Privilege_Telephony_network_get_selection_mode",CTc_Telephony_Privilege_Telephony_network_get_selection_mode,CTs_platform_permission_telephony_startup,CTs_platform_permission_telephony_cleanup},
	{"CTc_nfc_Privilege_Nfc_HandlerEnable",CTc_nfc_Privilege_Nfc_HandlerEnable,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_nfc_Privilege_Nfc_IsHandlerEnabled",CTc_nfc_Privilege_Nfc_IsHandlerEnabled,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent",CTc_Nfc_Privilege_NfcCardEmulation_SetHceEvent,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_GetSeType",CTc_Nfc_Privilege_NfcCardEmulation_GetSeType,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_SetSeType",CTc_Nfc_Privilege_NfcCardEmulation_SetSeType,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer",CTc_Nfc_Privilege_Nfc_RegisterUnregisterServer,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode",CTc_Nfc_Privilege_NfcCardEmulation_CardEmulationMode,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid",CTc_Nfc_Privilege_NfcCardEmulation_RegisterAid,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid",CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForAid,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory",CTc_Nfc_Privilege_NfcCardEmulation_ActivatedHandleForCategory,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch",CTc_Nfc_Privilege_NfcCardEmulation_TransectionFgDispatch,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_GetConnectedTag",CTc_Nfc_Privilege_Nfc_GetConnectedTag,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_Nfc_GetConnectedTarget",CTc_Nfc_Privilege_Nfc_GetConnectedTarget,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation",CTc_Nfc_Privilege_NfcCardEmulationEnableCardEmulation,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_PrivilegeNfc_se_set_preferred_handler",CTc_Nfc_PrivilegeNfc_se_set_preferred_handler,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler",CTc_Nfc_PrivilegeNfc_se_unset_preferred_handler,CTs_platform_permission_nfc_startup,CTs_platform_permission_nfc_cleanup},
	{"CTc_MediaController_PrivilegeMediaControllerClient",CTc_MediaController_PrivilegeMediaControllerClient,CTs_platform_permission_MediaController_startup,CTs_platform_permission_MediaController_cleanup},
	{"CTc_MediaContent_PrivilegeMediaStorage_scan_folder",CTc_MediaContent_PrivilegeMediaStorage_scan_folder,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_info_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db",CTc_MediaContent_PrivilegeContentWrite_media_info_insert_batch_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_playlist_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db",CTc_MediaContent_PrivilegeContentWrite_media_tag_insert_to_db,CTs_platform_permission_mediacontent_startup,CTs_platform_permission_mediacontent_cleanup},
	{"CTc_VoiceControl_PrivilegeRecorder",CTc_VoiceControl_PrivilegeRecorder,CTs_platform_permission_VoiceControl_startup,CTs_platform_permission_VoiceControl_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_icon",CTc_WidgetService_PrivilegeWidgetViewer_get_icon,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_main_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_mouse_support,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app",CTc_WidgetService_PrivilegeWidgetViewer_get_app_id_of_setup_app,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect",CTc_WidgetService_PrivilegeWidgetViewer_get_need_of_touch_effect,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid",CTc_WidgetService_PrivilegeWidgetViewer_get_widget_list_by_pkgid,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_package_id",CTc_WidgetService_PrivilegeWidgetViewer_get_package_id,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_name",CTc_WidgetService_PrivilegeWidgetViewer_get_name,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes",CTc_WidgetService_PrivilegeWidgetViewer_get_supported_sizes,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types",CTc_WidgetService_PrivilegeWidgetViewer_get_supported_size_types,CTs_platform_permission_widgetservice_startup,CTs_platform_permission_widgetservice_cleanup},
	{"CTc_WidgetViewer_PrivilegeWidgetViewer",CTc_WidgetViewer_PrivilegeWidgetViewer,CTs_platform_permission_WidgetViewer_startup,CTs_platform_permission_WidgetViewer_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay",CTc_Application_PrivilegeAlarmSet_alarm_schedule_once_after_delay,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date",CTc_Application_PrivilegeAlarmSet_alarm_get_scheduled_date,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date",CTc_Application_PrivilegeAlarmSet_alarm_schedule_at_date,CTs_platform_permission_Application_startup,CTs_platform_permission_Application_cleanup},
	{"CTc_MapsService_PrivilegeMapSservice_maps_service_create",CTc_MapsService_PrivilegeMapSservice_maps_service_create,CTs_platform_permission_MapsService_startup,CTs_platform_permission_MapsService_cleanup},
	{"CTc_Attach_Panel_Privileges_Add_Content_Category",CTc_Attach_Panel_Privileges_Add_Content_Category,CTs_platform_permission_Attach_Panel_startup,CTs_platform_permission_Attach_Panel_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_locale",CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_locale,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_app_id_exist",CTc_AccountManager_PrivilegeAccountReadWrite_query_app_id_exist,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_supported_feature",CTc_AccountManager_PrivilegeAccountReadWrite_query_supported_feature,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_provider_feature_by_app_id",CTc_AccountManager_PrivilegeAccountReadWrite_query_provider_feature_by_app_id,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_account_by_account_id",CTc_AccountManager_PrivilegeAccountReadWrite_query_account_by_account_id,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_update_sync_status_by_id",CTc_AccountManager_PrivilegeAccountReadWrite_update_sync_status_by_id,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_insert_to_db",CTc_AccountManager_PrivilegeAccountReadWrite_insert_to_db,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_account_query_account_by_package_name",CTc_AccountManager_PrivilegeAccountReadWrite_account_query_account_by_package_name,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_account_delete_from_db_by_package_name",CTc_AccountManager_PrivilegeAccountReadWrite_account_delete_from_db_by_package_name,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_account_type_query_by_app_id",CTc_AccountManager_PrivilegeAccountReadWrite_account_type_query_by_app_id,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_app_id",CTc_AccountManager_PrivilegeAccountReadWrite_query_label_by_app_id,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_AccountManager_PrivilegeAccountReadWrite_foreach_account_type_from_db",CTc_AccountManager_PrivilegeAccountReadWrite_foreach_account_type_from_db,CTs_platform_permission_accountsvc_startup,CTs_platform_permission_accountsvc_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_records",CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_records,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_record",CTc_ContactsService_PrivilegeContactWrite_contacts_db_insert_record,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records",CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_query",CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_query,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_range",CTc_ContactsService_PrivilegeContactRead_contacts_db_search_records_with_range,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_get_all_records",CTc_ContactsService_PrivilegeContactRead_contacts_db_get_all_records,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_get_current_version",CTc_ContactsService_PrivilegeContactRead_contacts_db_get_current_version,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count",CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count_with_query",CTc_ContactsService_PrivilegeContactRead_contacts_db_get_count_with_query,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_get_records_with_query",CTc_ContactsService_PrivilegeContactRead_contacts_db_get_records_with_query,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_db_add_changed_cb",CTc_ContactsService_PrivilegeContactRead_contacts_db_add_changed_cb,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_group_set_group_order",CTc_ContactsService_PrivilegeContactWrite_contacts_group_set_group_order,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_person_set_default_property",CTc_ContactsService_PrivilegeContactWrite_contacts_person_set_default_property,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_person_link_person",CTc_ContactsService_PrivilegeContactWrite_contacts_person_link_person,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_person_reset_usage",CTc_ContactsService_PrivilegeContactWrite_contacts_person_reset_usage,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeCallhistoryWrite_contacts_phone_log_reset_statistics",CTc_ContactsService_PrivilegeCallhistoryWrite_contacts_phone_log_reset_statistics,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_sorting_order",CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_sorting_order,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_sorting_order",CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_sorting_order,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_setting_add_name_display_order_changed_cb",CTc_ContactsService_PrivilegeContactWrite_contacts_setting_add_name_display_order_changed_cb,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_display_order",CTc_ContactsService_PrivilegeContactWrite_contacts_setting_set_name_display_order,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_display_order",CTc_ContactsService_PrivilegeContactRead_contacts_setting_get_name_display_order,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_contacts_setting_add_name_sorting_order_changed_cb",CTc_ContactsService_PrivilegeContactRead_contacts_contacts_setting_add_name_sorting_order_changed_cb,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_sim_import_all_contacts",CTc_ContactsService_PrivilegeContactWrite_contacts_sim_import_all_contacts,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactRead_contacts_sim_get_initialization_status",CTc_ContactsService_PrivilegeContactRead_contacts_sim_get_initialization_status,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_contact_id",CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_contact_id,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_account_id",CTc_ContactsService_PrivilegeContactWrite_contacts_activity_delete_by_account_id,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContacts_person_get_aggregation_suggestions",CTc_ContactsService_PrivilegeContacts_person_get_aggregation_suggestions,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContacts_phone_log_reset_statistics_by_sim",CTc_ContactsService_PrivilegeContacts_phone_log_reset_statistics_by_sim,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContacts_vcard_get_limit_size_of_photo",CTc_ContactsService_PrivilegeContacts_vcard_get_limit_size_of_photo,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_ContactsService_PrivilegeContacts_vcard_set_limit_size_of_photo",CTc_ContactsService_PrivilegeContacts_vcard_set_limit_size_of_photo,CTs_platform_permission_ContactsService_startup,CTs_platform_permission_ContactsService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_record",CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_record,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_records",CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_records,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_vcalendars",CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_insert_vcalendars,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_record",CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_record,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_records",CTc_CalendarService_PrivilegeCalendarWrite_calendar_db_replace_records,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_add_changed_cb",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_add_changed_cb,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_all_records",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_all_records,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_current_version",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_current_version,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_last_change_version",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_last_change_version,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_records_with_query",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_records_with_query,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count_with_query",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count_with_query,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count",CTc_CalendarService_PrivilegeCalendarRead_calendar_db_get_count,CTs_platform_permission_CalendarService_startup,CTs_platform_permission_CalendarService_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Request_Token",CTc_OAuth2_PrivilegeInternet_Request_Token,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Authorization_Grant",CTc_OAuth2_PrivilegeInternet_Authorization_Grant,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Request_Access_Token",CTc_OAuth2_PrivilegeInternet_Request_Access_Token,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Refresh_Access_Token",CTc_OAuth2_PrivilegeInternet_Refresh_Access_Token,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Clear_Cookies",CTc_OAuth2_PrivilegeInternet_Clear_Cookies,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_OAuth2_PrivilegeInternet_Clear_Cache",CTc_OAuth2_PrivilegeInternet_Clear_Cache,CTs_platform_permission_OAuth2_startup,CTs_platform_permission_OAuth2_cleanup},
	{"CTc_VpnService_PrivilegeVpnsvc_init",CTc_VpnService_PrivilegeVpnsvc_init,CTs_platform_permission_vpn_service_startup,CTs_platform_permission_vpn_service_cleanup},
	{"CTc_EflUtil_Privilege_efl_util_set_window_brightness",CTc_EflUtil_Privilege_efl_util_set_window_brightness,CTs_platform_permission_efl_util_startup,CTs_platform_permission_efl_util_cleanup},
	{"CTc_Iotcon_PrivilegeNetworkGet_initialize_deinitialize_p",CTc_Iotcon_PrivilegeNetworkGet_initialize_deinitialize_p,CTs_platform_permission_iotcon_startup,CTs_platform_permission_iotcon_cleanup},
	{"CTc_PhoneNumber_PrivilegePhoneNumberUtils_get_normalized_number",CTc_PhoneNumber_PrivilegePhoneNumberUtils_get_normalized_number,CTs_platform_permission_phonenumber_utils_startup,CTs_platform_permission_phonenumber_utils_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src",CTc_MediaStreamer_PrivilegeMediaStorage_node_create_src,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink",CTc_MediaStreamer_PrivilegeMediaStorage_node_create_sink,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param",CTc_MediaStreamer_PrivilegeMediaStorage_node_set_param,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params",CTc_MediaStreamer_PrivilegeMediaStorage_node_set_params,CTs_platform_permission_media_streamer_startup,CTs_platform_permission_media_streamer_cleanup},
	{"CTc_Http_PrivilegeInternet_http_transaction_submit",CTc_Http_PrivilegeInternet_http_transaction_submit,CTs_platform_permission_http_startup,CTs_platform_permission_http_cleanup},
	{"CTc_Wifi_Manager_Privilege_NetworkGet",CTc_Wifi_Manager_Privilege_NetworkGet,CTs_platform_permission_wifi_manager_startup,CTs_platform_permission_wifi_manager_cleanup},
	{NULL, NULL}
};

#endif // __TCT_PLATFORM-PERMISSION-NATIVE_H__
