//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_MEDIA-CONTENT-NATIVE_H__
#define __TCT_MEDIA-CONTENT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_media_content_startup(void);
extern void ITs_media_content_cleanup(void);
extern void ITs_media_content_album_startup(void);
extern void ITs_media_content_album_cleanup(void);
extern void ITs_media_content_tag_startup(void);
extern void ITs_media_content_tag_cleanup(void);
extern void ITs_media_content_folder_startup(void);
extern void ITs_media_content_folder_cleanup(void);
extern void ITs_media_content_bookmark_startup(void);
extern void ITs_media_content_bookmark_cleanup(void);
extern void ITs_media_content_playlist_startup(void);
extern void ITs_media_content_playlist_cleanup(void);
extern void ITs_media_content_filter_startup(void);
extern void ITs_media_content_filter_cleanup(void);
extern void ITs_media_content_group_startup(void);
extern void ITs_media_content_group_cleanup(void);
extern void ITs_media_content_info_startup(void);
extern void ITs_media_content_info_cleanup(void);
extern void ITs_media_content_audio_meta_startup(void);
extern void ITs_media_content_audio_meta_cleanup(void);
extern void ITs_media_content_video_meta_startup(void);
extern void ITs_media_content_video_meta_cleanup(void);
extern void ITs_media_content_image_meta_startup(void);
extern void ITs_media_content_image_meta_cleanup(void);
extern void ITs_media_content_face_startup(void);
extern void ITs_media_content_face_cleanup(void);
extern void ITs_media_content_book_startup(void);
extern void ITs_media_content_book_cleanup(void);

extern int ITc_media_content_connect_disconnect_p(void);
extern int ITc_media_content_scan_file_p(void);
extern int ITc_media_content_scan_folder_p(void);
extern int ITc_media_content_cancel_scan_folder_p(void);
extern int ITc_media_content_add_remove_db_updated_cb_p(void);
extern int ITc_media_album_get_album_count_from_db_p(void);
extern int ITc_media_album_foreach_album_from_db_p(void);
extern int ITc_media_album_clone_destroy_p(void);
extern int ITc_media_album_get_album_id_p(void);
extern int ITc_media_album_get_media_count_from_db_p(void);
extern int ITc_media_album_foreach_media_from_db_p(void);
extern int ITc_media_album_get_name_p(void);
extern int ITc_media_album_get_artist_p(void);
extern int ITc_media_album_get_album_art_p(void);
extern int ITc_media_album_get_album_from_db_p(void);
extern int ITc_media_tag_get_tag_count_from_db_p(void);
extern int ITc_media_tag_foreach_tag_from_db_p(void);
extern int ITc_media_tag_clone_destroy_p(void);
extern int ITc_media_tag_get_tag_id_p(void);
extern int ITc_media_tag_get_media_count_from_db_p(void);
extern int ITc_media_tag_foreach_media_from_db_p(void);
extern int ITc_media_tag_get_tag_from_db_p(void);
extern int ITc_media_tag_set_get_name_p(void);
extern int ITc_media_tag_add_remove_media_p(void);
extern int ITc_media_tag_update_to_db_p(void);
extern int ITc_media_tag_insert_delete_from_db_p(void);
extern int ITc_media_folder_get_folder_count_from_db_p(void);
extern int ITc_media_folder_foreach_folder_from_db_p(void);
extern int ITc_media_folder_clone_destroy_p(void);
extern int ITc_media_folder_get_folder_id_p(void);
extern int ITc_media_folder_get_media_count_from_db_p(void);
extern int ITc_media_folder_foreach_media_from_db_p(void);
extern int ITc_media_folder_get_name_p(void);
extern int ITc_media_folder_get_path_p(void);
extern int ITc_media_folder_get_folder_from_db_p(void);
extern int ITc_media_bookmark_get_bookmark_count_from_db_p(void);
extern int ITc_media_bookmark_get_bookmark_id_p(void);
extern int ITc_media_bookmark_get_thumbnail_path_p(void);
extern int ITc_media_bookmark_clone_destroy_p(void);
extern int ITc_media_bookmark_get_marked_time_p(void);
extern int ITc_media_bookmark_insert_delete_from_db_p(void);
extern int ITc_media_playlist_get_playlist_count_from_db_p(void);
extern int ITc_media_playlist_foreach_playlist_from_db_p(void);
extern int ITc_media_playlist_clone_destroy_p(void);
extern int ITc_media_playlist_get_playlist_id_p(void);
extern int ITc_media_playlist_get_media_count_from_db_p(void);
extern int ITc_media_playlist_foreach_media_from_db_p(void);
extern int ITc_media_playlist_set_get_name_p(void);
extern int ITc_media_playlist_get_playlist_from_db_p(void);
extern int ITc_media_playlist_update_to_db_p(void);
extern int ITc_media_playlist_insert_delete_from_db_p(void);
extern int ITc_media_playlist_set_get_thumbnail_path_p(void);
extern int ITc_media_playlist_add_remove_media_p(void);
extern int ITc_media_playlist_set_get_play_order_p(void);
extern int ITc_media_playlist_import_export_to_file_p(void);
extern int ITc_media_filter_create_destroy_p(void);
extern int ITc_media_filter_set_get_condition_p(void);
extern int ITc_media_filter_set_get_order_p(void);
extern int ITc_media_filter_set_get_offset_p(void);
extern int ITc_media_group_get_group_count_from_db_p(void);
extern int ITc_media_group_foreach_group_from_db_p(void);
extern int ITc_media_group_get_media_count_from_db_p(void);
extern int ITc_media_group_foreach_media_from_db_p(void);
extern int ITc_media_info_get_media_count_from_db_p(void);
extern int ITc_media_info_foreach_media_from_db_p(void);
extern int ITc_media_info_clone_destroy_p(void);
extern int ITc_media_info_insert_to_db_p(void);
extern int ITc_media_info_generate_thumbnail_p(void);
extern int ITc_media_info_insert_batch_to_db_p(void);
extern int ITc_media_info_foreach_bookmark_from_db_p(void);
extern int ITc_media_info_foreach_tag_from_db_p(void);
extern int ITc_media_info_get_bookmark_count_from_db_p(void);
extern int ITc_media_info_get_tag_count_from_db_p(void);
extern int ITc_media_info_update_to_db_p(void);
extern int ITc_media_info_get_media_id_p(void);
extern int ITc_media_info_get_media_from_db_p(void);
extern int ITc_media_info_get_added_time_p(void);
extern int ITc_media_info_get_altitude_p(void);
extern int ITc_media_info_get_description_p(void);
extern int ITc_media_info_get_display_name_p(void);
extern int ITc_media_info_set_get_favorite_p(void);
extern int ITc_media_info_get_file_path_p(void);
extern int ITc_media_info_get_image_p(void);
extern int ITc_media_info_get_audio_p(void);
extern int ITc_media_info_get_video_p(void);
extern int ITc_media_info_get_modified_time_p(void);
extern int ITc_media_info_get_latitude_p(void);
extern int ITc_media_info_get_longitude_p(void);
extern int ITc_media_info_get_rating_p(void);

extern int ITc_media_info_is_drm_p(void);
extern int ITc_media_info_get_media_type_p(void);
extern int ITc_media_info_get_mime_type_p(void);
extern int ITc_media_info_get_size_p(void);
extern int ITc_media_info_get_timeline_p(void);
extern int ITc_media_info_get_title_p(void);
extern int ITc_media_info_move_to_db_p(void);
extern int ITc_media_info_get_face_count_from_db_p(void);
extern int ITc_media_info_foreach_face_from_db_p(void);
extern int ITc_media_info_is_360_content_p(void);
extern int ITc_media_info_get_media_from_db_by_path_p(void);
extern int ITc_audio_meta_clone_destroy_p(void);
extern int ITc_audio_meta_get_album_p(void);
extern int ITc_audio_meta_get_album_artist_p(void);
extern int ITc_audio_meta_get_artist_p(void);
extern int ITc_audio_meta_get_bit_rate_p(void);
extern int ITc_audio_meta_get_bitpersample_p(void);
extern int ITc_audio_meta_get_channel_p(void);
extern int ITc_audio_meta_get_composer_p(void);
extern int ITc_audio_meta_get_copyright_p(void);
extern int ITc_audio_meta_get_duration_p(void);
extern int ITc_audio_meta_get_genre_p(void);
extern int ITc_audio_meta_get_media_id_p(void);
extern int ITc_audio_meta_get_recorded_date_p(void);
extern int ITc_audio_meta_get_sample_rate_p(void);
extern int ITc_audio_meta_get_track_num_p(void);
extern int ITc_audio_meta_get_year_p(void);
extern int ITc_video_meta_clone_destroy_p(void);
extern int ITc_video_meta_get_album_p(void);
extern int ITc_video_meta_get_album_artist_p(void);
extern int ITc_video_meta_get_artist_p(void);
extern int ITc_video_meta_get_bit_rate_p(void);
extern int ITc_video_meta_get_composer_p(void);
extern int ITc_video_meta_get_copyright_p(void);
extern int ITc_video_meta_get_duration_p(void);
extern int ITc_video_meta_get_genre_p(void);
extern int ITc_video_meta_get_media_id_p(void);
extern int ITc_video_meta_get_recorded_date_p(void);
extern int ITc_video_meta_get_track_num_p(void);
extern int ITc_video_meta_get_year_p(void);
extern int ITc_video_meta_get_height_p(void);
extern int ITc_video_meta_get_width_p(void);
extern int ITc_video_meta_get_rotation_p(void);
extern int ITc_image_meta_clone_destroy_p(void);
extern int ITc_image_meta_get_media_id_p(void);
extern int ITc_image_meta_get_height_p(void);
extern int ITc_image_meta_get_width_p(void);
extern int ITc_image_meta_get_date_taken_p(void);
extern int ITc_image_meta_get_orientation_p(void);
extern int ITc_image_meta_get_model_p(void);
extern int ITc_image_meta_get_exposure_time_p(void);
extern int ITc_image_meta_get_iso_p(void);
extern int ITc_image_meta_get_fnumber_p(void);
extern int ITc_media_face_create_destroy_p(void);
extern int ITc_media_face_clone_p(void);
extern int ITc_media_face_get_face_id_p(void);
extern int ITc_media_face_get_media_id_p(void);
extern int ITc_media_face_set_get_face_rect_p(void);
extern int ITc_media_face_set_get_orientation_p(void);
extern int ITc_media_face_set_get_tag_p(void);
extern int ITc_media_face_insert_to_and_delete_from_db_p(void);
extern int ITc_media_face_update_to_db_p(void);
extern int ITc_media_info_start_cancel_face_detection_p(void);
extern int ITc_media_bookmark_set_get_name_p(void);
extern int ITc_media_bookmark_update_to_db_p(void);
extern int ITc_media_face_get_face_count_from_db_p(void);
extern int ITc_media_face_foreach_face_from_db_p(void);
extern int ITc_media_bookmark_foreach_bookmark_from_db_p(void);

extern int ITc_media_book_meta_clone_destroy_p(void);
extern int ITc_media_book_meta_get_media_id_p(void);
extern int ITc_book_meta_get_subject_p(void);
extern int ITc_book_meta_get_author_p(void);
extern int ITc_book_meta_get_date_p(void);
extern int ITc_book_meta_get_publisher_p(void);
extern int ITc_media_info_get_book_p(void);
extern int ITc_media_book_meta_get_path_with_keyword_p(void);

testcase tc_array[] = {
	{"ITc_media_content_connect_disconnect_p",ITc_media_content_connect_disconnect_p,ITs_media_content_startup,ITs_media_content_cleanup},
	{"ITc_media_content_scan_file_p",ITc_media_content_scan_file_p,ITs_media_content_startup,ITs_media_content_cleanup},
	{"ITc_media_content_scan_folder_p",ITc_media_content_scan_folder_p,ITs_media_content_startup,ITs_media_content_cleanup},
	{"ITc_media_content_cancel_scan_folder_p",ITc_media_content_cancel_scan_folder_p,ITs_media_content_startup,ITs_media_content_cleanup},
	{"ITc_media_content_add_remove_db_updated_cb_p",ITc_media_content_add_remove_db_updated_cb_p,ITs_media_content_startup,ITs_media_content_cleanup},
	{"ITc_media_album_get_album_count_from_db_p",ITc_media_album_get_album_count_from_db_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_foreach_album_from_db_p",ITc_media_album_foreach_album_from_db_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_clone_destroy_p",ITc_media_album_clone_destroy_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_album_id_p",ITc_media_album_get_album_id_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_media_count_from_db_p",ITc_media_album_get_media_count_from_db_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_foreach_media_from_db_p",ITc_media_album_foreach_media_from_db_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_name_p",ITc_media_album_get_name_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_artist_p",ITc_media_album_get_artist_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_album_art_p",ITc_media_album_get_album_art_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_album_get_album_from_db_p",ITc_media_album_get_album_from_db_p,ITs_media_content_album_startup,ITs_media_content_album_cleanup},
	{"ITc_media_tag_get_tag_count_from_db_p",ITc_media_tag_get_tag_count_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_foreach_tag_from_db_p",ITc_media_tag_foreach_tag_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_clone_destroy_p",ITc_media_tag_clone_destroy_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_get_tag_id_p",ITc_media_tag_get_tag_id_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_get_media_count_from_db_p",ITc_media_tag_get_media_count_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_foreach_media_from_db_p",ITc_media_tag_foreach_media_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_get_tag_from_db_p",ITc_media_tag_get_tag_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_set_get_name_p",ITc_media_tag_set_get_name_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_add_remove_media_p",ITc_media_tag_add_remove_media_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_update_to_db_p",ITc_media_tag_update_to_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_tag_insert_delete_from_db_p",ITc_media_tag_insert_delete_from_db_p,ITs_media_content_tag_startup,ITs_media_content_tag_cleanup},
	{"ITc_media_folder_get_folder_count_from_db_p",ITc_media_folder_get_folder_count_from_db_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_foreach_folder_from_db_p",ITc_media_folder_foreach_folder_from_db_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_clone_destroy_p",ITc_media_folder_clone_destroy_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_get_folder_id_p",ITc_media_folder_get_folder_id_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_get_media_count_from_db_p",ITc_media_folder_get_media_count_from_db_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_foreach_media_from_db_p",ITc_media_folder_foreach_media_from_db_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_get_name_p",ITc_media_folder_get_name_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_get_path_p",ITc_media_folder_get_path_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_folder_get_folder_from_db_p",ITc_media_folder_get_folder_from_db_p,ITs_media_content_folder_startup,ITs_media_content_folder_cleanup},
	{"ITc_media_bookmark_get_bookmark_count_from_db_p",ITc_media_bookmark_get_bookmark_count_from_db_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_get_bookmark_id_p",ITc_media_bookmark_get_bookmark_id_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_get_thumbnail_path_p",ITc_media_bookmark_get_thumbnail_path_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_clone_destroy_p",ITc_media_bookmark_clone_destroy_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_get_marked_time_p",ITc_media_bookmark_get_marked_time_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_insert_delete_from_db_p",ITc_media_bookmark_insert_delete_from_db_p,ITs_media_content_bookmark_startup,ITs_media_content_bookmark_cleanup},
	{"ITc_media_playlist_get_playlist_count_from_db_p",ITc_media_playlist_get_playlist_count_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_foreach_playlist_from_db_p",ITc_media_playlist_foreach_playlist_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_clone_destroy_p",ITc_media_playlist_clone_destroy_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_get_playlist_id_p",ITc_media_playlist_get_playlist_id_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_get_media_count_from_db_p",ITc_media_playlist_get_media_count_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_foreach_media_from_db_p",ITc_media_playlist_foreach_media_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_set_get_name_p",ITc_media_playlist_set_get_name_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_get_playlist_from_db_p",ITc_media_playlist_get_playlist_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_update_to_db_p",ITc_media_playlist_update_to_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_insert_delete_from_db_p",ITc_media_playlist_insert_delete_from_db_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_set_get_thumbnail_path_p",ITc_media_playlist_set_get_thumbnail_path_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_add_remove_media_p",ITc_media_playlist_add_remove_media_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_set_get_play_order_p",ITc_media_playlist_set_get_play_order_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_playlist_import_export_to_file_p",ITc_media_playlist_import_export_to_file_p,ITs_media_content_playlist_startup,ITs_media_content_playlist_cleanup},
	{"ITc_media_filter_create_destroy_p",ITc_media_filter_create_destroy_p,ITs_media_content_filter_startup,ITs_media_content_filter_cleanup},
	{"ITc_media_filter_set_get_condition_p",ITc_media_filter_set_get_condition_p,ITs_media_content_filter_startup,ITs_media_content_filter_cleanup},
	{"ITc_media_filter_set_get_order_p",ITc_media_filter_set_get_order_p,ITs_media_content_filter_startup,ITs_media_content_filter_cleanup},
	{"ITc_media_filter_set_get_offset_p",ITc_media_filter_set_get_offset_p,ITs_media_content_filter_startup,ITs_media_content_filter_cleanup},
	{"ITc_media_group_get_group_count_from_db_p",ITc_media_group_get_group_count_from_db_p,ITs_media_content_group_startup,ITs_media_content_group_cleanup},
	{"ITc_media_group_foreach_group_from_db_p",ITc_media_group_foreach_group_from_db_p,ITs_media_content_group_startup,ITs_media_content_group_cleanup},
	{"ITc_media_group_get_media_count_from_db_p",ITc_media_group_get_media_count_from_db_p,ITs_media_content_group_startup,ITs_media_content_group_cleanup},
	{"ITc_media_group_foreach_media_from_db_p",ITc_media_group_foreach_media_from_db_p,ITs_media_content_group_startup,ITs_media_content_group_cleanup},
	{"ITc_media_info_get_media_count_from_db_p",ITc_media_info_get_media_count_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_foreach_media_from_db_p",ITc_media_info_foreach_media_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_clone_destroy_p",ITc_media_info_clone_destroy_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_insert_to_db_p",ITc_media_info_insert_to_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_generate_thumbnail_p",ITc_media_info_generate_thumbnail_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_insert_batch_to_db_p",ITc_media_info_insert_batch_to_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_foreach_bookmark_from_db_p",ITc_media_info_foreach_bookmark_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_foreach_tag_from_db_p",ITc_media_info_foreach_tag_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_bookmark_count_from_db_p",ITc_media_info_get_bookmark_count_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_tag_count_from_db_p",ITc_media_info_get_tag_count_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_update_to_db_p",ITc_media_info_update_to_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_media_id_p",ITc_media_info_get_media_id_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_media_from_db_p",ITc_media_info_get_media_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_added_time_p",ITc_media_info_get_added_time_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_altitude_p",ITc_media_info_get_altitude_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_description_p",ITc_media_info_get_description_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_display_name_p",ITc_media_info_get_display_name_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_set_get_favorite_p",ITc_media_info_set_get_favorite_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_file_path_p",ITc_media_info_get_file_path_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_image_p",ITc_media_info_get_image_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_audio_p",ITc_media_info_get_audio_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_video_p",ITc_media_info_get_video_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_modified_time_p",ITc_media_info_get_modified_time_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_latitude_p",ITc_media_info_get_latitude_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_longitude_p",ITc_media_info_get_longitude_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_rating_p",ITc_media_info_get_rating_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_is_drm_p",ITc_media_info_is_drm_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_media_type_p",ITc_media_info_get_media_type_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_mime_type_p",ITc_media_info_get_mime_type_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_size_p",ITc_media_info_get_size_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_timeline_p",ITc_media_info_get_timeline_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_title_p",ITc_media_info_get_title_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_move_to_db_p",ITc_media_info_move_to_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_face_count_from_db_p",ITc_media_info_get_face_count_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_foreach_face_from_db_p",ITc_media_info_foreach_face_from_db_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_is_360_content_p",ITc_media_info_is_360_content_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
	{"ITc_media_info_get_media_from_db_by_path_p",ITc_media_info_get_media_from_db_by_path_p,ITs_media_content_info_startup,ITs_media_content_info_cleanup},
        {"ITc_media_info_get_book_p", ITc_media_info_get_book_p, ITs_media_content_info_startup, ITs_media_content_info_cleanup},
	{"ITc_audio_meta_clone_destroy_p",ITc_audio_meta_clone_destroy_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_album_p",ITc_audio_meta_get_album_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_album_artist_p",ITc_audio_meta_get_album_artist_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_artist_p",ITc_audio_meta_get_artist_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_bit_rate_p",ITc_audio_meta_get_bit_rate_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_bitpersample_p",ITc_audio_meta_get_bitpersample_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_channel_p",ITc_audio_meta_get_channel_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_composer_p",ITc_audio_meta_get_composer_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_copyright_p",ITc_audio_meta_get_copyright_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_duration_p",ITc_audio_meta_get_duration_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_genre_p",ITc_audio_meta_get_genre_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_media_id_p",ITc_audio_meta_get_media_id_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_recorded_date_p",ITc_audio_meta_get_recorded_date_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_sample_rate_p",ITc_audio_meta_get_sample_rate_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_track_num_p",ITc_audio_meta_get_track_num_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_audio_meta_get_year_p",ITc_audio_meta_get_year_p,ITs_media_content_audio_meta_startup,ITs_media_content_audio_meta_cleanup},
	{"ITc_video_meta_clone_destroy_p",ITc_video_meta_clone_destroy_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_album_p",ITc_video_meta_get_album_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_album_artist_p",ITc_video_meta_get_album_artist_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_artist_p",ITc_video_meta_get_artist_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_bit_rate_p",ITc_video_meta_get_bit_rate_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_composer_p",ITc_video_meta_get_composer_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_copyright_p",ITc_video_meta_get_copyright_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_duration_p",ITc_video_meta_get_duration_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_genre_p",ITc_video_meta_get_genre_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_media_id_p",ITc_video_meta_get_media_id_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_recorded_date_p",ITc_video_meta_get_recorded_date_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_track_num_p",ITc_video_meta_get_track_num_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_year_p",ITc_video_meta_get_year_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_height_p",ITc_video_meta_get_height_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_width_p",ITc_video_meta_get_width_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_video_meta_get_rotation_p",ITc_video_meta_get_rotation_p,ITs_media_content_video_meta_startup,ITs_media_content_video_meta_cleanup},
	{"ITc_image_meta_clone_destroy_p",ITc_image_meta_clone_destroy_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_media_id_p",ITc_image_meta_get_media_id_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_height_p",ITc_image_meta_get_height_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_width_p",ITc_image_meta_get_width_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_date_taken_p",ITc_image_meta_get_date_taken_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_orientation_p",ITc_image_meta_get_orientation_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_model_p",ITc_image_meta_get_model_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_exposure_time_p",ITc_image_meta_get_exposure_time_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_iso_p",ITc_image_meta_get_iso_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_image_meta_get_fnumber_p",ITc_image_meta_get_fnumber_p,ITs_media_content_image_meta_startup,ITs_media_content_image_meta_cleanup},
	{"ITc_media_face_create_destroy_p",ITc_media_face_create_destroy_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_clone_p",ITc_media_face_clone_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_get_face_id_p",ITc_media_face_get_face_id_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_get_media_id_p",ITc_media_face_get_media_id_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_set_get_face_rect_p",ITc_media_face_set_get_face_rect_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_set_get_orientation_p",ITc_media_face_set_get_orientation_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_set_get_tag_p",ITc_media_face_set_get_tag_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_insert_to_and_delete_from_db_p",ITc_media_face_insert_to_and_delete_from_db_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_face_update_to_db_p",ITc_media_face_update_to_db_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_info_start_cancel_face_detection_p",ITc_media_info_start_cancel_face_detection_p,ITs_media_content_face_startup,ITs_media_content_face_cleanup},
	{"ITc_media_bookmark_set_get_name_p", ITc_media_bookmark_set_get_name_p, ITs_media_content_bookmark_startup, ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_update_to_db_p", ITc_media_bookmark_update_to_db_p, ITs_media_content_bookmark_startup, ITs_media_content_bookmark_cleanup},
	{"ITc_media_face_get_face_count_from_db_p", ITc_media_face_get_face_count_from_db_p, ITs_media_content_bookmark_startup, ITs_media_content_bookmark_cleanup},
	{"ITc_media_face_foreach_face_from_db_p", ITc_media_face_foreach_face_from_db_p, ITs_media_content_bookmark_startup, ITs_media_content_bookmark_cleanup},
	{"ITc_media_bookmark_foreach_bookmark_from_db_p", ITc_media_bookmark_foreach_bookmark_from_db_p, ITs_media_content_bookmark_startup, ITs_media_content_bookmark_cleanup},
	{"ITc_media_book_meta_clone_destroy_p", ITc_media_book_meta_clone_destroy_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_media_book_meta_get_media_id_p", ITc_media_book_meta_get_media_id_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_book_meta_get_subject_p", ITc_book_meta_get_subject_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_book_meta_get_author_p", ITc_book_meta_get_author_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_book_meta_get_date_p", ITc_book_meta_get_date_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_book_meta_get_publisher_p", ITc_book_meta_get_publisher_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{"ITc_media_book_meta_get_path_with_keyword_p", ITc_media_book_meta_get_path_with_keyword_p, ITs_media_content_book_startup, ITs_media_content_book_cleanup},
	{NULL, NULL}
};

#endif // __TCT_MEDIA-CONTENT-NATIVE_H__
