//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_DEVICE-NATIVE_H__
#define __TCT_DEVICE-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_system_device_display_startup(void);
extern void utc_system_device_display_cleanup(void);
extern void utc_system_device_power_startup(void);
extern void utc_system_device_power_cleanup(void);
extern void utc_system_haptic_startup(void);
extern void utc_system_haptic_cleanup(void);
extern void utc_system_device_ir_startup(void);
extern void utc_system_device_battery_startup(void);
extern void utc_system_device_battery_cleanup(void);
extern void utc_system_device_thermal_startup(void);
extern void utc_system_device_thermal_cleanup(void);

extern int utc_system_device_add_callback_p(void);
extern int utc_system_device_add_callback_n_1(void);
extern int utc_system_device_add_callback_n_2(void);
extern int utc_system_device_remove_callback_p(void);
extern int utc_system_device_remove_callback_n_1(void);
extern int utc_system_device_remove_callback_n_2(void);
extern int utc_system_device_display_get_numbers_p(void);
extern int utc_system_device_display_get_numbers_n(void);
extern int utc_system_device_display_get_max_brightness_p(void);
extern int utc_system_device_display_get_max_brightness_n_1(void);
extern int utc_system_device_display_get_max_brightness_n_2(void);
extern int utc_system_device_display_get_brightness_p(void);
extern int utc_system_device_display_get_brightness_n_1(void);
extern int utc_system_device_display_get_brightness_n_2(void);
extern int utc_system_device_display_set_brightness_p(void);
extern int utc_system_device_display_set_brightness_n_1(void);
extern int utc_system_device_display_set_brightness_n_2(void);
extern int utc_system_device_display_set_brightness_n_3(void);
extern int utc_system_device_display_get_state_p(void);
extern int utc_system_device_display_get_state_n(void);
extern int utc_system_device_display_change_state_p(void);
extern int utc_system_device_display_change_state_n(void);
extern int utc_system_device_power_request_lock_p_1(void);
extern int utc_system_device_power_request_lock_p_2(void);
extern int utc_system_device_power_request_lock_n_1(void);
extern int utc_system_device_power_request_lock_n_2(void);
extern int utc_system_device_power_release_lock_p(void);
extern int utc_system_device_power_release_lock_n(void);
extern int utc_system_device_power_wakeup_p(void);
extern int utc_system_device_battery_get_percent_p(void);
extern int utc_system_device_battery_get_percent_n(void);
extern int utc_system_device_battery_is_charging_p(void);
extern int utc_system_device_battery_is_charging_n(void);
extern int utc_system_device_battery_get_level_status_p(void);
extern int utc_system_device_battery_get_level_status_n(void);
extern int utc_system_device_battery_get_health_p(void);
extern int utc_system_device_battery_get_health_n(void);
extern int utc_system_device_battery_get_power_source_p(void);
extern int utc_system_device_battery_get_power_source_n(void);
extern int utc_system_device_battery_get_status_p(void);
extern int utc_system_device_battery_get_status_n(void);
extern int utc_system_device_battery_get_property_p(void);
extern int utc_system_device_battery_get_property_n(void);
extern int utc_system_device_haptic_get_count_p(void);
extern int utc_system_device_haptic_get_count_n(void);
extern int utc_system_device_haptic_open_p(void);
extern int utc_system_device_haptic_open_n_1(void);
extern int utc_system_device_haptic_open_n_2(void);
extern int utc_system_device_haptic_close_p(void);
extern int utc_system_device_haptic_close_n(void);
extern int utc_system_device_haptic_vibrate_p(void);
extern int utc_system_device_haptic_vibrate_n_1(void);
extern int utc_system_device_haptic_vibrate_n_2(void);
extern int utc_system_device_haptic_vibrate_n_3(void);
extern int utc_system_device_haptic_stop_p(void);
extern int utc_system_device_haptic_stop_n(void);
extern int utc_system_device_flash_get_max_brightness_p(void);
extern int utc_system_device_flash_get_max_brightness_n(void);
extern int utc_system_device_flash_get_brightness_p(void);
extern int utc_system_device_flash_get_brightness_n(void);
extern int utc_system_device_flash_set_brightness_p(void);
extern int utc_system_device_flash_set_brightness_n(void);
extern int utc_system_device_led_play_custom_p(void);
extern int utc_system_device_led_play_custom_n_1(void);
extern int utc_system_device_led_play_custom_n2(void);
extern int utc_system_device_led_stop_custom_p(void);
extern int utc_system_device_led_stop_custom_n(void);
extern int utc_system_device_ir_is_available_p(void);
extern int utc_system_device_ir_is_available_n(void);
extern int utc_system_device_ir_transmit_p(void);
extern int utc_system_device_ir_transmit_n_1(void);
extern int utc_system_device_ir_transmit_n_2(void);
extern int utc_system_device_thermal_get_temperature_p(void);
extern int utc_system_device_thermal_get_temperature_n(void);

testcase tc_array[] = {
	{"utc_system_device_add_callback_p",utc_system_device_add_callback_p,NULL,NULL},
	{"utc_system_device_add_callback_n_1",utc_system_device_add_callback_n_1,NULL,NULL},
	{"utc_system_device_add_callback_n_2",utc_system_device_add_callback_n_2,NULL,NULL},
	{"utc_system_device_remove_callback_p",utc_system_device_remove_callback_p,NULL,NULL},
	{"utc_system_device_remove_callback_n_1",utc_system_device_remove_callback_n_1,NULL,NULL},
	{"utc_system_device_remove_callback_n_2",utc_system_device_remove_callback_n_2,NULL,NULL},
	{"utc_system_device_display_get_numbers_p",utc_system_device_display_get_numbers_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_numbers_n",utc_system_device_display_get_numbers_n,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_max_brightness_p",utc_system_device_display_get_max_brightness_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_max_brightness_n_1",utc_system_device_display_get_max_brightness_n_1,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_max_brightness_n_2",utc_system_device_display_get_max_brightness_n_2,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_brightness_p",utc_system_device_display_get_brightness_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_brightness_n_1",utc_system_device_display_get_brightness_n_1,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_brightness_n_2",utc_system_device_display_get_brightness_n_2,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_set_brightness_p",utc_system_device_display_set_brightness_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_set_brightness_n_1",utc_system_device_display_set_brightness_n_1,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_set_brightness_n_2",utc_system_device_display_set_brightness_n_2,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_set_brightness_n_3",utc_system_device_display_set_brightness_n_3,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_state_p",utc_system_device_display_get_state_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_get_state_n",utc_system_device_display_get_state_n,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_change_state_p",utc_system_device_display_change_state_p,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_display_change_state_n",utc_system_device_display_change_state_n,utc_system_device_display_startup,utc_system_device_display_cleanup},
	{"utc_system_device_power_request_lock_p_1",utc_system_device_power_request_lock_p_1,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_request_lock_p_2",utc_system_device_power_request_lock_p_2,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_request_lock_n_1",utc_system_device_power_request_lock_n_1,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_request_lock_n_2",utc_system_device_power_request_lock_n_2,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_release_lock_p",utc_system_device_power_release_lock_p,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_release_lock_n",utc_system_device_power_release_lock_n,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_power_wakeup_p",utc_system_device_power_wakeup_p,utc_system_device_power_startup,utc_system_device_power_cleanup},
	{"utc_system_device_battery_get_percent_p",utc_system_device_battery_get_percent_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_percent_n",utc_system_device_battery_get_percent_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_is_charging_p",utc_system_device_battery_is_charging_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_is_charging_n",utc_system_device_battery_is_charging_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_level_status_p",utc_system_device_battery_get_level_status_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_level_status_n",utc_system_device_battery_get_level_status_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_health_p",utc_system_device_battery_get_health_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_health_n",utc_system_device_battery_get_health_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_power_source_p",utc_system_device_battery_get_power_source_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_power_source_n",utc_system_device_battery_get_power_source_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_status_p",utc_system_device_battery_get_status_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_status_n",utc_system_device_battery_get_status_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_property_p",utc_system_device_battery_get_property_p,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_battery_get_property_n",utc_system_device_battery_get_property_n,utc_system_device_battery_startup,utc_system_device_battery_cleanup},
	{"utc_system_device_haptic_get_count_p",utc_system_device_haptic_get_count_p,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_get_count_n",utc_system_device_haptic_get_count_n,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_open_p",utc_system_device_haptic_open_p,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_open_n_1",utc_system_device_haptic_open_n_1,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_open_n_2",utc_system_device_haptic_open_n_2,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_close_p",utc_system_device_haptic_close_p,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_close_n",utc_system_device_haptic_close_n,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_vibrate_p",utc_system_device_haptic_vibrate_p,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_vibrate_n_1",utc_system_device_haptic_vibrate_n_1,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_vibrate_n_2",utc_system_device_haptic_vibrate_n_2,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_vibrate_n_3",utc_system_device_haptic_vibrate_n_3,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_stop_p",utc_system_device_haptic_stop_p,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_haptic_stop_n",utc_system_device_haptic_stop_n,utc_system_haptic_startup,utc_system_haptic_cleanup},
	{"utc_system_device_flash_get_max_brightness_p",utc_system_device_flash_get_max_brightness_p,NULL,NULL},
	{"utc_system_device_flash_get_max_brightness_n",utc_system_device_flash_get_max_brightness_n,NULL,NULL},
	{"utc_system_device_flash_get_brightness_p",utc_system_device_flash_get_brightness_p,NULL,NULL},
	{"utc_system_device_flash_get_brightness_n",utc_system_device_flash_get_brightness_n,NULL,NULL},
	{"utc_system_device_flash_set_brightness_p",utc_system_device_flash_set_brightness_p,NULL,NULL},
	{"utc_system_device_flash_set_brightness_n",utc_system_device_flash_set_brightness_n,NULL,NULL},
	{"utc_system_device_led_play_custom_p",utc_system_device_led_play_custom_p,NULL,NULL},
	{"utc_system_device_led_play_custom_n_1",utc_system_device_led_play_custom_n_1,NULL,NULL},
	{"utc_system_device_led_play_custom_n2",utc_system_device_led_play_custom_n2,NULL,NULL},
	{"utc_system_device_led_stop_custom_p",utc_system_device_led_stop_custom_p,NULL,NULL},
	{"utc_system_device_led_stop_custom_n",utc_system_device_led_stop_custom_n,NULL,NULL},
	{"utc_system_device_ir_is_available_p",utc_system_device_ir_is_available_p,utc_system_device_ir_startup,NULL},
	{"utc_system_device_ir_is_available_n",utc_system_device_ir_is_available_n,utc_system_device_ir_startup,NULL},
	{"utc_system_device_ir_transmit_p",utc_system_device_ir_transmit_p,utc_system_device_ir_startup,NULL},
	{"utc_system_device_ir_transmit_n_1",utc_system_device_ir_transmit_n_1,utc_system_device_ir_startup,NULL},
	{"utc_system_device_ir_transmit_n_2",utc_system_device_ir_transmit_n_2,utc_system_device_ir_startup,NULL},
	{"utc_system_device_thermal_get_temperature_p",utc_system_device_thermal_get_temperature_p,utc_system_device_thermal_startup,utc_system_device_thermal_cleanup},
	{"utc_system_device_thermal_get_temperature_n",utc_system_device_thermal_get_temperature_n,utc_system_device_thermal_startup,utc_system_device_thermal_cleanup},
	{NULL, NULL}
};

#endif // __TCT_DEVICE-NATIVE_H__
