//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_APPCORE-WATCH-NATIVE_H__
#define __TCT_APPCORE-WATCH-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_appcore_watch_startup(void);
extern void utc_appcore_watch_cleanup(void);

extern int utc_appcore_watch_watch_app_main_n1(void);
extern int utc_appcore_watch_watch_app_main_n2(void);
extern int utc_appcore_watch_watch_app_main_n3(void);
extern int utc_appcore_watch_watch_app_add_event_handler_p(void);
extern int utc_appcore_watch_watch_app_add_event_handler_n(void);
extern int utc_appcore_watch_watch_app_remove_event_handler_p(void);
extern int utc_appcore_watch_watch_app_remove_event_handler_n(void);
extern int utc_appcore_watch_watch_time_get_current_time_p(void);
extern int utc_appcore_watch_watch_time_get_current_time_n(void);
extern int utc_appcore_watch_watch_time_delete_p(void);
extern int utc_appcore_watch_watch_time_delete_n(void);
extern int utc_appcore_watch_watch_time_get_year_p(void);
extern int utc_appcore_watch_watch_time_get_year_n(void);
extern int utc_appcore_watch_watch_time_get_month_p(void);
extern int utc_appcore_watch_watch_time_get_month_n(void);
extern int utc_appcore_watch_watch_time_get_day_p(void);
extern int utc_appcore_watch_watch_time_get_day_n(void);
extern int utc_appcore_watch_watch_time_get_day_of_week_p(void);
extern int utc_appcore_watch_watch_time_get_day_of_week_n(void);
extern int utc_appcore_watch_watch_time_get_hour_p(void);
extern int utc_appcore_watch_watch_time_get_hour_n(void);
extern int utc_appcore_watch_watch_time_get_hour24_p(void);
extern int utc_appcore_watch_watch_time_get_hour24_n(void);
extern int utc_appcore_watch_watch_time_get_minute_p(void);
extern int utc_appcore_watch_watch_time_get_minute_n(void);
extern int utc_appcore_watch_watch_time_get_second_p(void);
extern int utc_appcore_watch_watch_time_get_second_n(void);
extern int utc_appcore_watch_watch_time_get_millisecond_p(void);
extern int utc_appcore_watch_watch_time_get_millisecond_n(void);
extern int utc_appcore_watch_watch_time_get_utc_time_p(void);
extern int utc_appcore_watch_watch_time_get_utc_time_n1(void);
extern int utc_appcore_watch_watch_time_get_utc_time_n2(void);
extern int utc_appcore_watch_watch_time_get_utc_timestamp_p(void);
extern int utc_appcore_watch_watch_time_get_utc_timestamp_n(void);
extern int utc_appcore_watch_watch_time_get_time_zone_p(void);
extern int utc_appcore_watch_watch_time_get_time_zone_n1(void);
extern int utc_appcore_watch_watch_time_get_time_zone_n2(void);
extern int utc_appcore_watch_watch_time_get_dst_status_p(void);
extern int utc_appcore_watch_watch_time_get_dst_status_n1(void);
extern int utc_appcore_watch_watch_time_get_dst_status_n2(void);
extern int utc_appcore_watch_watch_app_get_elm_win_n(void);
extern int utc_appcore_watch_watch_app_set_ambient_tick_type_p(void);
extern int utc_appcore_watch_watch_app_set_ambient_tick_type_n(void);
extern int utc_appcore_watch_watch_app_get_ambient_tick_type_p(void);
extern int utc_appcore_watch_watch_app_get_ambient_tick_type_n(void);
extern int utc_appcore_watch_watch_app_set_time_tick_frequency_p(void);
extern int utc_appcore_watch_watch_app_set_time_tick_frequency_n(void);
extern int utc_appcore_watch_watch_app_get_time_tick_frequency_p(void);
extern int utc_appcore_watch_watch_app_get_time_tick_frequency_n(void);

testcase tc_array[] = {
	{"utc_appcore_watch_watch_app_main_n1",utc_appcore_watch_watch_app_main_n1,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_main_n2",utc_appcore_watch_watch_app_main_n2,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_main_n3",utc_appcore_watch_watch_app_main_n3,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_add_event_handler_p",utc_appcore_watch_watch_app_add_event_handler_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_add_event_handler_n",utc_appcore_watch_watch_app_add_event_handler_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_remove_event_handler_p",utc_appcore_watch_watch_app_remove_event_handler_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_remove_event_handler_n",utc_appcore_watch_watch_app_remove_event_handler_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_current_time_p",utc_appcore_watch_watch_time_get_current_time_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_current_time_n",utc_appcore_watch_watch_time_get_current_time_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_delete_p",utc_appcore_watch_watch_time_delete_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_delete_n",utc_appcore_watch_watch_time_delete_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_year_p",utc_appcore_watch_watch_time_get_year_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_year_n",utc_appcore_watch_watch_time_get_year_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_month_p",utc_appcore_watch_watch_time_get_month_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_month_n",utc_appcore_watch_watch_time_get_month_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_day_p",utc_appcore_watch_watch_time_get_day_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_day_n",utc_appcore_watch_watch_time_get_day_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_day_of_week_p",utc_appcore_watch_watch_time_get_day_of_week_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_day_of_week_n",utc_appcore_watch_watch_time_get_day_of_week_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_hour_p",utc_appcore_watch_watch_time_get_hour_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_hour_n",utc_appcore_watch_watch_time_get_hour_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_hour24_p",utc_appcore_watch_watch_time_get_hour24_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_hour24_n",utc_appcore_watch_watch_time_get_hour24_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_minute_p",utc_appcore_watch_watch_time_get_minute_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_minute_n",utc_appcore_watch_watch_time_get_minute_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_second_p",utc_appcore_watch_watch_time_get_second_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_second_n",utc_appcore_watch_watch_time_get_second_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_millisecond_p",utc_appcore_watch_watch_time_get_millisecond_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_millisecond_n",utc_appcore_watch_watch_time_get_millisecond_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_utc_time_p",utc_appcore_watch_watch_time_get_utc_time_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_utc_time_n1",utc_appcore_watch_watch_time_get_utc_time_n1,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_utc_time_n2",utc_appcore_watch_watch_time_get_utc_time_n2,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_utc_timestamp_p",utc_appcore_watch_watch_time_get_utc_timestamp_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_utc_timestamp_n",utc_appcore_watch_watch_time_get_utc_timestamp_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_time_zone_p",utc_appcore_watch_watch_time_get_time_zone_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_time_zone_n1",utc_appcore_watch_watch_time_get_time_zone_n1,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_time_zone_n2",utc_appcore_watch_watch_time_get_time_zone_n2,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_dst_status_p",utc_appcore_watch_watch_time_get_dst_status_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_dst_status_n1",utc_appcore_watch_watch_time_get_dst_status_n1,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_time_get_dst_status_n2",utc_appcore_watch_watch_time_get_dst_status_n2,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_get_elm_win_n",utc_appcore_watch_watch_app_get_elm_win_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_set_ambient_tick_type_p",utc_appcore_watch_watch_app_set_ambient_tick_type_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_set_ambient_tick_type_n",utc_appcore_watch_watch_app_set_ambient_tick_type_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_get_ambient_tick_type_p",utc_appcore_watch_watch_app_get_ambient_tick_type_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_get_ambient_tick_type_n",utc_appcore_watch_watch_app_get_ambient_tick_type_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_set_time_tick_frequency_p",utc_appcore_watch_watch_app_set_time_tick_frequency_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_set_time_tick_frequency_n",utc_appcore_watch_watch_app_set_time_tick_frequency_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_get_time_tick_frequency_p",utc_appcore_watch_watch_app_get_time_tick_frequency_p,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{"utc_appcore_watch_watch_app_get_time_tick_frequency_n",utc_appcore_watch_watch_app_get_time_tick_frequency_n,utc_appcore_watch_startup,utc_appcore_watch_cleanup},
	{NULL, NULL}
};

#endif // __TCT_APPCORE-WATCH-NATIVE_H__
