//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_EFL-EXT-NATIVE_H__
#define __TCT_EFL-EXT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_efl_ext_startup(void);
extern void utc_efl_ext_cleanup(void);

extern int utc_efl_ext_popup_back_p(void);
extern int utc_efl_ext_ctxpopup_back_p(void);
extern int utc_efl_ext_naviframe_more_cb_p(void);
extern int utc_efl_ext_naviframe_back_cb_p(void);
extern int utc_efl_ext_object_event_callback_add_p1(void);
extern int utc_efl_ext_object_event_callback_add_p2(void);
extern int utc_efl_ext_object_event_callback_del_p(void);
extern int utc_efl_ext_entry_back_cb_p(void);
extern int utc_efl_ext_entry_selection_start_cb_p(void);
extern int utc_efl_ext_entry_selection_cleared_cb_p(void);
extern int utc_efl_ext_entry_selection_back_event_allow_set_p1(void);
extern int utc_efl_ext_entry_selection_back_event_allow_set_p2(void);
extern int utc_efl_ext_win_keygrab_set_p(void);
extern int utc_efl_ext_win_keygrab_unset_p(void);
extern int utc_efl_ext_rotary_object_event_callback_add_p(void);
extern int utc_efl_ext_rotary_object_event_callback_add_n1(void);
extern int utc_efl_ext_rotary_object_event_callback_add_n2(void);
extern int utc_efl_ext_rotary_object_event_callback_priority_add_p(void);
extern int utc_efl_ext_rotary_object_event_callback_priority_add_n1(void);
extern int utc_efl_ext_rotary_object_event_callback_priority_add_n2(void);
extern int utc_efl_ext_rotary_object_event_callback_del_p1(void);
extern int utc_efl_ext_rotary_object_event_callback_del_p2(void);
extern int utc_efl_ext_rotary_event_handler_add_p(void);
extern int utc_efl_ext_rotary_event_handler_add_n(void);
extern int utc_efl_ext_rotary_event_handler_del_p(void);
extern int utc_efl_ext_rotary_object_event_activated_set_p(void);
extern int utc_efl_ext_rotary_object_event_activated_set_n(void);
extern int utc_efl_ext_eext_circle_object_line_width_set_p(void);
extern int utc_efl_ext_eext_circle_object_line_width_set_n(void);
extern int utc_efl_ext_eext_circle_object_line_width_get_p(void);
extern int utc_efl_ext_eext_circle_object_line_width_get_n(void);
extern int utc_efl_ext_eext_circle_object_angle_set_p(void);
extern int utc_efl_ext_eext_circle_object_angle_set_n(void);
extern int utc_efl_ext_eext_circle_object_angle_get_p(void);
extern int utc_efl_ext_eext_circle_object_angle_get_n(void);
extern int utc_efl_ext_eext_circle_object_angle_offset_set_p(void);
extern int utc_efl_ext_eext_circle_object_angle_offset_set_n(void);
extern int utc_efl_ext_eext_circle_object_angle_offset_get_p(void);
extern int utc_efl_ext_eext_circle_object_angle_offset_get_n(void);
extern int utc_efl_ext_eext_circle_object_angle_min_max_set_p(void);
extern int utc_efl_ext_eext_circle_object_angle_min_max_set_n(void);
extern int utc_efl_ext_eext_circle_object_angle_min_max_get_p(void);
extern int utc_efl_ext_eext_circle_object_angle_min_max_get_n(void);
extern int utc_efl_ext_eext_circle_object_value_min_max_set_p(void);
extern int utc_efl_ext_eext_circle_object_value_min_max_set_n(void);
extern int utc_efl_ext_eext_circle_object_value_min_max_get_p(void);
extern int utc_efl_ext_eext_circle_object_value_min_max_get_n(void);
extern int utc_efl_ext_eext_circle_object_value_set_p(void);
extern int utc_efl_ext_eext_circle_object_value_set_n(void);
extern int utc_efl_ext_eext_circle_object_value_get_p(void);
extern int utc_efl_ext_eext_circle_object_value_get_n(void);
extern int utc_efl_ext_eext_circle_object_color_set_p(void);
extern int utc_efl_ext_eext_circle_object_color_set_n(void);
extern int utc_efl_ext_eext_circle_object_color_get_p(void);
extern int utc_efl_ext_eext_circle_object_color_get_n(void);
extern int utc_efl_ext_eext_circle_object_radius_set_p(void);
extern int utc_efl_ext_eext_circle_object_radius_set_n(void);
extern int utc_efl_ext_eext_circle_object_radius_get_p(void);
extern int utc_efl_ext_eext_circle_object_radius_get_n(void);
extern int utc_efl_ext_eext_circle_object_disabled_set_p(void);
extern int utc_efl_ext_eext_circle_object_disabled_set_n(void);
extern int utc_efl_ext_eext_circle_object_disabled_get_p(void);
extern int utc_efl_ext_eext_circle_object_disabled_get_n(void);
extern int utc_efl_ext_eext_circle_object_add_p(void);
extern int utc_efl_ext_eext_circle_object_item_line_width_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_line_width_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_line_width_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_line_width_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_offset_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_offset_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_offset_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_offset_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_min_max_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_min_max_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_angle_min_max_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_angle_min_max_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_value_min_max_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_value_min_max_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_value_min_max_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_value_min_max_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_value_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_value_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_value_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_value_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_color_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_color_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_color_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_color_get_n(void);
extern int utc_efl_ext_eext_circle_object_item_radius_set_p(void);
extern int utc_efl_ext_eext_circle_object_item_radius_set_n(void);
extern int utc_efl_ext_eext_circle_object_item_radius_get_p(void);
extern int utc_efl_ext_eext_circle_object_item_radius_get_n(void);
extern int utc_efl_ext_eext_circle_surface_conformant_add_p(void);
extern int utc_efl_ext_eext_circle_surface_conformant_add_n1(void);
extern int utc_efl_ext_eext_circle_surface_conformant_add_n2(void);
extern int utc_efl_ext_eext_circle_surface_layout_add_p(void);
extern int utc_efl_ext_eext_circle_surface_layout_add_n1(void);
extern int utc_efl_ext_eext_circle_surface_layout_add_n2(void);
extern int utc_efl_ext_eext_circle_surface_naviframe_add_p(void);
extern int utc_efl_ext_eext_circle_surface_naviframe_add_n1(void);
extern int utc_efl_ext_eext_circle_surface_naviframe_add_n2(void);
extern int utc_efl_ext_eext_circle_surface_del_p(void);
extern int utc_efl_ext_eext_circle_surface_del_n(void);
extern int utc_efl_ext_eext_circle_object_datetime_add_p(void);
extern int utc_efl_ext_eext_circle_object_datetime_add_n(void);
extern int utc_efl_ext_eext_circle_object_genlist_add_p(void);
extern int utc_efl_ext_eext_circle_object_genlist_add_n(void);
extern int utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_p(void);
extern int utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_n(void);
extern int utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_p(void);
extern int utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_n(void);
extern int utc_efl_ext_eext_circle_object_progressbar_add_p(void);
extern int utc_efl_ext_eext_circle_object_progressbar_add_n(void);
extern int utc_efl_ext_eext_circle_object_slider_add_p(void);
extern int utc_efl_ext_eext_circle_object_slider_add_n(void);
extern int utc_efl_ext_eext_circle_object_slider_step_set_p(void);
extern int utc_efl_ext_eext_circle_object_slider_step_set_n(void);
extern int utc_efl_ext_eext_circle_object_slider_step_get_p(void);
extern int utc_efl_ext_eext_circle_object_slider_step_get_n(void);
extern int utc_efl_ext_eext_circle_object_scroller_add_p(void);
extern int utc_efl_ext_eext_circle_object_scroller_add_n(void);
extern int utc_efl_ext_eext_circle_object_scroller_policy_get_p(void);
extern int utc_efl_ext_eext_circle_object_scroller_policy_get_n(void);
extern int utc_efl_ext_eext_circle_object_scroller_policy_set_p(void);
extern int utc_efl_ext_eext_circle_object_scroller_policy_set_n(void);
extern int utc_efl_ext_eext_circle_object_mirrored_set_p(void);
extern int utc_efl_ext_eext_circle_object_mirrored_set_n(void);
extern int utc_efl_ext_eext_circle_object_mirrored_get_p(void);
extern int utc_efl_ext_eext_circle_object_mirrored_get_n(void);
extern int utc_efl_ext_eext_more_option_add_p(void);
extern int utc_efl_ext_eext_more_option_add_n(void);
extern int utc_efl_ext_eext_more_option_direction_set_p(void);
extern int utc_efl_ext_eext_more_option_direction_set_n(void);
extern int utc_efl_ext_eext_more_option_direction_get_p(void);
extern int utc_efl_ext_eext_more_option_direction_get_n(void);
extern int utc_efl_ext_eext_more_option_item_append_p(void);
extern int utc_efl_ext_eext_more_option_item_append_n(void);
extern int utc_efl_ext_eext_more_option_item_prepend_p(void);
extern int utc_efl_ext_eext_more_option_item_prepend_n(void);
extern int utc_efl_ext_eext_more_option_item_insert_after_p(void);
extern int utc_efl_ext_eext_more_option_item_insert_after_n(void);
extern int utc_efl_ext_eext_more_option_item_insert_before_p(void);
extern int utc_efl_ext_eext_more_option_item_insert_before_n(void);
extern int utc_efl_ext_eext_more_option_item_del_p(void);
extern int utc_efl_ext_eext_more_option_item_del_n(void);
extern int utc_efl_ext_eext_more_option_items_clear_p(void);
extern int utc_efl_ext_eext_more_option_items_clear_n(void);
extern int utc_efl_ext_eext_more_option_item_part_text_set_p(void);
extern int utc_efl_ext_eext_more_option_item_part_text_set_n(void);
extern int utc_efl_ext_eext_more_option_item_part_text_get_p(void);
extern int utc_efl_ext_eext_more_option_item_part_text_get_n(void);
extern int utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_p(void);
extern int utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_n(void);
extern int utc_efl_ext_eext_more_option_item_part_content_set_p(void);
extern int utc_efl_ext_eext_more_option_item_part_content_set_n(void);
extern int utc_efl_ext_eext_more_option_item_part_content_get_p(void);
extern int utc_efl_ext_eext_more_option_item_part_content_get_n(void);
extern int utc_efl_ext_eext_more_option_opened_set_p(void);
extern int utc_efl_ext_eext_more_option_opened_set_n(void);
extern int utc_efl_ext_eext_more_option_opened_get_p(void);
extern int utc_efl_ext_eext_more_option_opened_get_n(void);
extern int utc_efl_ext_eext_more_option_items_get_p(void);
extern int utc_efl_ext_eext_more_option_items_get_n(void);
extern int utc_efl_ext_eext_more_option_editing_enabled_get_n(void);
extern int utc_efl_ext_eext_more_option_editing_enabled_get_p(void);
extern int utc_efl_ext_eext_more_option_editing_enabled_set_n(void);
extern int utc_efl_ext_eext_more_option_editing_enabled_set_p(void);
extern int utc_efl_ext_eext_more_option_add_item_enabled_get_n(void);
extern int utc_efl_ext_eext_more_option_add_item_enabled_get_p(void);
extern int utc_efl_ext_eext_more_option_add_item_enabled_set_n(void);
extern int utc_efl_ext_eext_more_option_add_item_enabled_set_p(void);
extern int utc_efl_ext_eext_more_option_item_delete_enabled_get_p(void);
extern int utc_efl_ext_eext_more_option_item_delete_enabled_get_n(void);
extern int utc_efl_ext_eext_more_option_item_delete_enabled_set_p(void);
extern int utc_efl_ext_eext_more_option_item_delete_enabled_set_n(void);
extern int utc_efl_ext_eext_circle_object_spinner_add_p(void);
extern int utc_efl_ext_eext_circle_object_spinner_add_n(void);
extern int utc_efl_ext_eext_circle_object_spinner_angle_set_p(void);
extern int utc_efl_ext_eext_circle_object_spinner_angle_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_add_p(void);
extern int utc_efl_ext_eext_rotary_selector_add_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_append_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_append_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_prepend_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_prepend_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_insert_after_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_insert_after_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_insert_before_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_insert_before_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_del_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_del_n(void);
extern int utc_efl_ext_eext_rotary_selector_items_clear_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_text_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_text_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_text_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_text_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_content_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_content_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_content_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_content_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_part_content_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_part_content_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_part_content_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_part_content_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_color_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_color_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_color_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_part_color_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_part_color_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_part_color_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_part_color_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_part_color_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_selected_item_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_selected_item_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_selected_item_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_selected_item_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_items_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_items_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_editing_enabled_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_editing_enabled_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_editing_enabled_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_editing_enabled_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_add_item_enabled_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_add_item_enabled_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_add_item_enabled_set_n(void);
extern int utc_efl_ext_eext_rotary_selector_add_item_enabled_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_n(void);
extern int utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_p(void);
extern int utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_n(void);
extern int utc_efl_ext_eext_panel_add_p(void);
extern int utc_efl_ext_eext_panel_add_n(void);
extern int utc_efl_ext_eext_panel_part_content_set_p(void);
extern int utc_efl_ext_eext_panel_part_content_set_n(void);
extern int utc_efl_ext_eext_panel_part_content_get_p(void);
extern int utc_efl_ext_eext_panel_part_content_get_n(void);
extern int utc_efl_ext_eext_rotary_event_activated_object_get_p(void);
extern int utc_efl_ext_eext_rotary_event_activated_object_get_n(void);
extern int utc_efl_ext_eext_popup_add_p(void);
extern int utc_efl_ext_eext_popup_add_n(void);


testcase tc_array[] = {
	{"utc_efl_ext_popup_back_p",utc_efl_ext_popup_back_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_ctxpopup_back_p",utc_efl_ext_ctxpopup_back_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_naviframe_more_cb_p",utc_efl_ext_naviframe_more_cb_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_naviframe_back_cb_p",utc_efl_ext_naviframe_back_cb_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_object_event_callback_add_p1",utc_efl_ext_object_event_callback_add_p1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_object_event_callback_add_p2",utc_efl_ext_object_event_callback_add_p2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_object_event_callback_del_p",utc_efl_ext_object_event_callback_del_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_entry_back_cb_p",utc_efl_ext_entry_back_cb_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_entry_selection_start_cb_p",utc_efl_ext_entry_selection_start_cb_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_entry_selection_cleared_cb_p",utc_efl_ext_entry_selection_cleared_cb_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_entry_selection_back_event_allow_set_p1",utc_efl_ext_entry_selection_back_event_allow_set_p1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_entry_selection_back_event_allow_set_p2",utc_efl_ext_entry_selection_back_event_allow_set_p2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_win_keygrab_set_p",utc_efl_ext_win_keygrab_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_win_keygrab_unset_p",utc_efl_ext_win_keygrab_unset_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_add_p",utc_efl_ext_rotary_object_event_callback_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_add_n1",utc_efl_ext_rotary_object_event_callback_add_n1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_add_n2",utc_efl_ext_rotary_object_event_callback_add_n2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_priority_add_p",utc_efl_ext_rotary_object_event_callback_priority_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_priority_add_n1",utc_efl_ext_rotary_object_event_callback_priority_add_n1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_priority_add_n2",utc_efl_ext_rotary_object_event_callback_priority_add_n2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_del_p1",utc_efl_ext_rotary_object_event_callback_del_p1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_callback_del_p2",utc_efl_ext_rotary_object_event_callback_del_p2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_event_handler_add_p",utc_efl_ext_rotary_event_handler_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_event_handler_add_n",utc_efl_ext_rotary_event_handler_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_event_handler_del_p",utc_efl_ext_rotary_event_handler_del_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_activated_set_p",utc_efl_ext_rotary_object_event_activated_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_rotary_object_event_activated_set_n",utc_efl_ext_rotary_object_event_activated_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_line_width_set_p",utc_efl_ext_eext_circle_object_line_width_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_line_width_set_n",utc_efl_ext_eext_circle_object_line_width_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_line_width_get_p",utc_efl_ext_eext_circle_object_line_width_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_line_width_get_n",utc_efl_ext_eext_circle_object_line_width_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_set_p",utc_efl_ext_eext_circle_object_angle_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_set_n",utc_efl_ext_eext_circle_object_angle_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_get_p",utc_efl_ext_eext_circle_object_angle_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_get_n",utc_efl_ext_eext_circle_object_angle_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_offset_set_p",utc_efl_ext_eext_circle_object_angle_offset_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_offset_set_n",utc_efl_ext_eext_circle_object_angle_offset_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_offset_get_p",utc_efl_ext_eext_circle_object_angle_offset_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_offset_get_n",utc_efl_ext_eext_circle_object_angle_offset_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_min_max_set_p",utc_efl_ext_eext_circle_object_angle_min_max_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_min_max_set_n",utc_efl_ext_eext_circle_object_angle_min_max_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_min_max_get_p",utc_efl_ext_eext_circle_object_angle_min_max_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_angle_min_max_get_n",utc_efl_ext_eext_circle_object_angle_min_max_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_min_max_set_p",utc_efl_ext_eext_circle_object_value_min_max_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_min_max_set_n",utc_efl_ext_eext_circle_object_value_min_max_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_min_max_get_p",utc_efl_ext_eext_circle_object_value_min_max_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_min_max_get_n",utc_efl_ext_eext_circle_object_value_min_max_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_set_p",utc_efl_ext_eext_circle_object_value_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_set_n",utc_efl_ext_eext_circle_object_value_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_get_p",utc_efl_ext_eext_circle_object_value_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_value_get_n",utc_efl_ext_eext_circle_object_value_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_color_set_p",utc_efl_ext_eext_circle_object_color_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_color_set_n",utc_efl_ext_eext_circle_object_color_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_color_get_p",utc_efl_ext_eext_circle_object_color_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_color_get_n",utc_efl_ext_eext_circle_object_color_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_radius_set_p",utc_efl_ext_eext_circle_object_radius_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_radius_set_n",utc_efl_ext_eext_circle_object_radius_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_radius_get_p",utc_efl_ext_eext_circle_object_radius_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_radius_get_n",utc_efl_ext_eext_circle_object_radius_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_disabled_set_p",utc_efl_ext_eext_circle_object_disabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_disabled_set_n",utc_efl_ext_eext_circle_object_disabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_disabled_get_p",utc_efl_ext_eext_circle_object_disabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_disabled_get_n",utc_efl_ext_eext_circle_object_disabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_add_p",utc_efl_ext_eext_circle_object_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_line_width_set_p",utc_efl_ext_eext_circle_object_item_line_width_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_line_width_set_n",utc_efl_ext_eext_circle_object_item_line_width_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_line_width_get_p",utc_efl_ext_eext_circle_object_item_line_width_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_line_width_get_n",utc_efl_ext_eext_circle_object_item_line_width_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_set_p",utc_efl_ext_eext_circle_object_item_angle_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_set_n",utc_efl_ext_eext_circle_object_item_angle_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_get_p",utc_efl_ext_eext_circle_object_item_angle_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_get_n",utc_efl_ext_eext_circle_object_item_angle_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_offset_set_p",utc_efl_ext_eext_circle_object_item_angle_offset_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_offset_set_n",utc_efl_ext_eext_circle_object_item_angle_offset_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_offset_get_p",utc_efl_ext_eext_circle_object_item_angle_offset_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_offset_get_n",utc_efl_ext_eext_circle_object_item_angle_offset_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_min_max_set_p",utc_efl_ext_eext_circle_object_item_angle_min_max_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_min_max_set_n",utc_efl_ext_eext_circle_object_item_angle_min_max_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_min_max_get_p",utc_efl_ext_eext_circle_object_item_angle_min_max_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_angle_min_max_get_n",utc_efl_ext_eext_circle_object_item_angle_min_max_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_min_max_set_p",utc_efl_ext_eext_circle_object_item_value_min_max_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_min_max_set_n",utc_efl_ext_eext_circle_object_item_value_min_max_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_min_max_get_p",utc_efl_ext_eext_circle_object_item_value_min_max_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_min_max_get_n",utc_efl_ext_eext_circle_object_item_value_min_max_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_set_p",utc_efl_ext_eext_circle_object_item_value_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_set_n",utc_efl_ext_eext_circle_object_item_value_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_get_p",utc_efl_ext_eext_circle_object_item_value_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_value_get_n",utc_efl_ext_eext_circle_object_item_value_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_color_set_p",utc_efl_ext_eext_circle_object_item_color_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_color_set_n",utc_efl_ext_eext_circle_object_item_color_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_color_get_p",utc_efl_ext_eext_circle_object_item_color_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_color_get_n",utc_efl_ext_eext_circle_object_item_color_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_radius_set_p",utc_efl_ext_eext_circle_object_item_radius_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_radius_set_n",utc_efl_ext_eext_circle_object_item_radius_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_radius_get_p",utc_efl_ext_eext_circle_object_item_radius_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_item_radius_get_n",utc_efl_ext_eext_circle_object_item_radius_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_conformant_add_p",utc_efl_ext_eext_circle_surface_conformant_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_conformant_add_n1",utc_efl_ext_eext_circle_surface_conformant_add_n1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_conformant_add_n2",utc_efl_ext_eext_circle_surface_conformant_add_n2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_layout_add_p",utc_efl_ext_eext_circle_surface_layout_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_layout_add_n1",utc_efl_ext_eext_circle_surface_layout_add_n1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_layout_add_n2",utc_efl_ext_eext_circle_surface_layout_add_n2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_naviframe_add_p",utc_efl_ext_eext_circle_surface_naviframe_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_naviframe_add_n1",utc_efl_ext_eext_circle_surface_naviframe_add_n1,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_naviframe_add_n2",utc_efl_ext_eext_circle_surface_naviframe_add_n2,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_del_p",utc_efl_ext_eext_circle_surface_del_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_surface_del_n",utc_efl_ext_eext_circle_surface_del_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_datetime_add_p",utc_efl_ext_eext_circle_object_datetime_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_datetime_add_n",utc_efl_ext_eext_circle_object_datetime_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_add_p",utc_efl_ext_eext_circle_object_genlist_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_add_n",utc_efl_ext_eext_circle_object_genlist_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_p",utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_n",utc_efl_ext_eext_circle_object_genlist_scroller_policy_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_p",utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_n",utc_efl_ext_eext_circle_object_genlist_scroller_policy_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_mirrored_set_p", utc_efl_ext_eext_circle_object_mirrored_set_p, utc_efl_ext_startup, utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_mirrored_set_n", utc_efl_ext_eext_circle_object_mirrored_set_n, utc_efl_ext_startup, utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_mirrored_get_p", utc_efl_ext_eext_circle_object_mirrored_get_p, utc_efl_ext_startup, utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_mirrored_get_n", utc_efl_ext_eext_circle_object_mirrored_get_n, utc_efl_ext_startup, utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_progressbar_add_p",utc_efl_ext_eext_circle_object_progressbar_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_progressbar_add_n",utc_efl_ext_eext_circle_object_progressbar_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_add_p",utc_efl_ext_eext_circle_object_slider_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_add_n",utc_efl_ext_eext_circle_object_slider_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_step_set_p",utc_efl_ext_eext_circle_object_slider_step_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_step_set_n",utc_efl_ext_eext_circle_object_slider_step_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_step_get_p",utc_efl_ext_eext_circle_object_slider_step_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_slider_step_get_n",utc_efl_ext_eext_circle_object_slider_step_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_add_p",utc_efl_ext_eext_circle_object_scroller_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_add_n",utc_efl_ext_eext_circle_object_scroller_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_policy_get_p",utc_efl_ext_eext_circle_object_scroller_policy_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_policy_get_n",utc_efl_ext_eext_circle_object_scroller_policy_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_policy_set_p",utc_efl_ext_eext_circle_object_scroller_policy_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_scroller_policy_set_n",utc_efl_ext_eext_circle_object_scroller_policy_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_p",utc_efl_ext_eext_more_option_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_n",utc_efl_ext_eext_more_option_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_direction_set_p",utc_efl_ext_eext_more_option_direction_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_direction_set_n",utc_efl_ext_eext_more_option_direction_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_direction_get_p",utc_efl_ext_eext_more_option_direction_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_direction_get_n",utc_efl_ext_eext_more_option_direction_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_append_p",utc_efl_ext_eext_more_option_item_append_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_append_n",utc_efl_ext_eext_more_option_item_append_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_prepend_p",utc_efl_ext_eext_more_option_item_prepend_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_prepend_n",utc_efl_ext_eext_more_option_item_prepend_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_insert_after_p",utc_efl_ext_eext_more_option_item_insert_after_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_insert_after_n",utc_efl_ext_eext_more_option_item_insert_after_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_insert_before_p",utc_efl_ext_eext_more_option_item_insert_before_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_insert_before_n",utc_efl_ext_eext_more_option_item_insert_before_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_del_p",utc_efl_ext_eext_more_option_item_del_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_del_n",utc_efl_ext_eext_more_option_item_del_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_items_clear_p",utc_efl_ext_eext_more_option_items_clear_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_items_clear_n",utc_efl_ext_eext_more_option_items_clear_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_text_set_p",utc_efl_ext_eext_more_option_item_part_text_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_text_set_n",utc_efl_ext_eext_more_option_item_part_text_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_text_get_p",utc_efl_ext_eext_more_option_item_part_text_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_text_get_n",utc_efl_ext_eext_more_option_item_part_text_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_p",utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_n",utc_efl_ext_eext_more_option_item_domain_translatable_part_text_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_content_set_p",utc_efl_ext_eext_more_option_item_part_content_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_content_set_n",utc_efl_ext_eext_more_option_item_part_content_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_content_get_p",utc_efl_ext_eext_more_option_item_part_content_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_part_content_get_n",utc_efl_ext_eext_more_option_item_part_content_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_opened_set_p",utc_efl_ext_eext_more_option_opened_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_opened_set_n",utc_efl_ext_eext_more_option_opened_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_opened_get_p",utc_efl_ext_eext_more_option_opened_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_opened_get_n",utc_efl_ext_eext_more_option_opened_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_items_get_p",utc_efl_ext_eext_more_option_items_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_items_get_n",utc_efl_ext_eext_more_option_items_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_editing_enabled_get_n",utc_efl_ext_eext_more_option_editing_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_editing_enabled_get_p",utc_efl_ext_eext_more_option_editing_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_editing_enabled_set_n",utc_efl_ext_eext_more_option_editing_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_editing_enabled_set_p",utc_efl_ext_eext_more_option_editing_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_item_enabled_get_p",utc_efl_ext_eext_more_option_add_item_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_item_enabled_get_n",utc_efl_ext_eext_more_option_add_item_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_item_enabled_set_p",utc_efl_ext_eext_more_option_add_item_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_add_item_enabled_set_n",utc_efl_ext_eext_more_option_add_item_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_delete_enabled_get_p",utc_efl_ext_eext_more_option_item_delete_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_delete_enabled_get_n",utc_efl_ext_eext_more_option_item_delete_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_delete_enabled_set_p",utc_efl_ext_eext_more_option_item_delete_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_more_option_item_delete_enabled_set_n",utc_efl_ext_eext_more_option_item_delete_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_spinner_add_p",utc_efl_ext_eext_circle_object_spinner_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_spinner_add_n",utc_efl_ext_eext_circle_object_spinner_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_spinner_angle_set_p",utc_efl_ext_eext_circle_object_spinner_angle_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_circle_object_spinner_angle_set_n",utc_efl_ext_eext_circle_object_spinner_angle_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_p",utc_efl_ext_eext_rotary_selector_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_n",utc_efl_ext_eext_rotary_selector_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_append_p",utc_efl_ext_eext_rotary_selector_item_append_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_append_n",utc_efl_ext_eext_rotary_selector_item_append_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_prepend_p",utc_efl_ext_eext_rotary_selector_item_prepend_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_prepend_n",utc_efl_ext_eext_rotary_selector_item_prepend_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_insert_after_p",utc_efl_ext_eext_rotary_selector_item_insert_after_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_insert_after_n",utc_efl_ext_eext_rotary_selector_item_insert_after_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_insert_before_p",utc_efl_ext_eext_rotary_selector_item_insert_before_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_insert_before_n",utc_efl_ext_eext_rotary_selector_item_insert_before_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_del_p",utc_efl_ext_eext_rotary_selector_item_del_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_del_n",utc_efl_ext_eext_rotary_selector_item_del_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_items_clear_p",utc_efl_ext_eext_rotary_selector_items_clear_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_text_set_p",utc_efl_ext_eext_rotary_selector_item_part_text_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_text_set_n",utc_efl_ext_eext_rotary_selector_item_part_text_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_text_get_p",utc_efl_ext_eext_rotary_selector_item_part_text_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_text_get_n",utc_efl_ext_eext_rotary_selector_item_part_text_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_p",utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_n",utc_efl_ext_eext_rotary_selector_item_domain_translatable_part_text_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_content_set_p",utc_efl_ext_eext_rotary_selector_item_part_content_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_content_set_n",utc_efl_ext_eext_rotary_selector_item_part_content_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_content_get_p",utc_efl_ext_eext_rotary_selector_item_part_content_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_content_get_n",utc_efl_ext_eext_rotary_selector_item_part_content_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_content_set_p",utc_efl_ext_eext_rotary_selector_part_content_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_content_set_n",utc_efl_ext_eext_rotary_selector_part_content_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_content_get_p",utc_efl_ext_eext_rotary_selector_part_content_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_content_get_n",utc_efl_ext_eext_rotary_selector_part_content_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_color_get_p",utc_efl_ext_eext_rotary_selector_item_part_color_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_color_get_n",utc_efl_ext_eext_rotary_selector_item_part_color_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_color_set_p",utc_efl_ext_eext_rotary_selector_item_part_color_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_part_color_set_n",utc_efl_ext_eext_rotary_selector_item_part_color_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_color_get_p",utc_efl_ext_eext_rotary_selector_part_color_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_color_get_n",utc_efl_ext_eext_rotary_selector_part_color_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_color_set_p",utc_efl_ext_eext_rotary_selector_part_color_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_part_color_set_n",utc_efl_ext_eext_rotary_selector_part_color_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_selected_item_set_p",utc_efl_ext_eext_rotary_selector_selected_item_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_selected_item_set_n",utc_efl_ext_eext_rotary_selector_selected_item_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_selected_item_get_p",utc_efl_ext_eext_rotary_selector_selected_item_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_selected_item_get_n",utc_efl_ext_eext_rotary_selector_selected_item_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_items_get_p",utc_efl_ext_eext_rotary_selector_items_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_items_get_n",utc_efl_ext_eext_rotary_selector_items_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_editing_enabled_get_n",utc_efl_ext_eext_rotary_selector_editing_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_editing_enabled_get_p",utc_efl_ext_eext_rotary_selector_editing_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_editing_enabled_set_n",utc_efl_ext_eext_rotary_selector_editing_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_editing_enabled_set_p",utc_efl_ext_eext_rotary_selector_editing_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_item_enabled_get_p",utc_efl_ext_eext_rotary_selector_add_item_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_item_enabled_get_n",utc_efl_ext_eext_rotary_selector_add_item_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_item_enabled_set_p",utc_efl_ext_eext_rotary_selector_add_item_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_add_item_enabled_set_n",utc_efl_ext_eext_rotary_selector_add_item_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_p",utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_n",utc_efl_ext_eext_rotary_selector_item_delete_enabled_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_p",utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_n",utc_efl_ext_eext_rotary_selector_item_delete_enabled_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_add_p",utc_efl_ext_eext_panel_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_add_n",utc_efl_ext_eext_panel_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_part_content_set_p",utc_efl_ext_eext_panel_part_content_set_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_part_content_set_n",utc_efl_ext_eext_panel_part_content_set_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_part_content_get_p",utc_efl_ext_eext_panel_part_content_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_panel_part_content_get_n",utc_efl_ext_eext_panel_part_content_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_event_activated_object_get_p",utc_efl_ext_eext_rotary_event_activated_object_get_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_rotary_event_activated_object_get_n",utc_efl_ext_eext_rotary_event_activated_object_get_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_popup_add_p",utc_efl_ext_eext_popup_add_p,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{"utc_efl_ext_eext_popup_add_n",utc_efl_ext_eext_popup_add_n,utc_efl_ext_startup,utc_efl_ext_cleanup},
	{NULL, NULL}
};

#endif // __TCT_EFL-EXT-NATIVE_H__
