//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WEBKIT2-NATIVE_H__
#define __TCT_WEBKIT2-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_webkit2_ewk_back_forward_list_count_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_count_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_current_item_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_current_item_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_at_index_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_at_index_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_original_url_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_original_url_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_ref_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_ref_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_title_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_title_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_unref_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_unref_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_item_url_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_item_url_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_next_item_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_next_item_get_func_cleanup(void);
extern void utc_webkit2_ewk_back_forward_list_previous_item_get_func_startup(void);
extern void utc_webkit2_ewk_back_forward_list_previous_item_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_background_music_get_func_startup(void);
extern void utc_webkit2_ewk_context_background_music_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_background_music_set_func_startup(void);
extern void utc_webkit2_ewk_context_background_music_set_func_cleanup(void);
extern void utc_webkit2_ewk_context_block_multimedia_on_call_get_func_startup(void);
extern void utc_webkit2_ewk_context_block_multimedia_on_call_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_block_multimedia_on_call_set_func_startup(void);
extern void utc_webkit2_ewk_context_block_multimedia_on_call_set_func_cleanup(void);
extern void utc_webkit2_ewk_context_cache_model_get_func_startup(void);
extern void utc_webkit2_ewk_context_cache_model_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_cache_model_set_func_startup(void);
extern void utc_webkit2_ewk_context_cache_model_set_func_cleanup(void);
extern void utc_webkit2_ewk_context_cookie_manager_get_func_startup(void);
extern void utc_webkit2_ewk_context_cookie_manager_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_intercept_request_callback_set_func_startup(void);
extern void utc_webkit2_ewk_context_intercept_request_callback_set_func_cleanup(void);
extern void utc_webkit2_ewk_context_menu_item_count_func_startup(void);
extern void utc_webkit2_ewk_context_menu_item_count_func_cleanup(void);
extern void utc_webkit2_ewk_context_menu_item_remove_func_startup(void);
extern void utc_webkit2_ewk_context_menu_item_remove_func_cleanup(void);
extern void utc_webkit2_ewk_context_menu_item_tag_get_func_startup(void);
extern void utc_webkit2_ewk_context_menu_item_tag_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_menu_nth_item_get_func_startup(void);
extern void utc_webkit2_ewk_context_menu_nth_item_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_resource_cache_clear_func_startup(void);
extern void utc_webkit2_ewk_context_resource_cache_clear_func_cleanup(void);
extern void utc_webkit2_ewk_context_rotation_lock_get_func_startup(void);
extern void utc_webkit2_ewk_context_rotation_lock_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_rotation_lock_set_func_startup(void);
extern void utc_webkit2_ewk_context_rotation_lock_set_func_cleanup(void);
extern void utc_webkit2_ewk_context_sound_overlap_get_func_startup(void);
extern void utc_webkit2_ewk_context_sound_overlap_get_func_cleanup(void);
extern void utc_webkit2_ewk_context_sound_overlap_set_func_startup(void);
extern void utc_webkit2_ewk_context_sound_overlap_set_func_cleanup(void);
extern void utc_webkit2_ewk_cookie_manager_accept_policy_async_get_startup(void);
extern void utc_webkit2_ewk_cookie_manager_accept_policy_async_get_cleanup(void);
extern void utc_webkit2_ewk_cookie_manager_accept_policy_set_startup(void);
extern void utc_webkit2_ewk_cookie_manager_accept_policy_set_cleanup(void);
extern void utc_webkit2_ewk_cookie_manager_cookies_clear_func_startup(void);
extern void utc_webkit2_ewk_cookie_manager_cookies_clear_func_cleanup(void);
extern void utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_startup(void);
extern void utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_cleanup(void);
extern void utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_startup(void);
extern void utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_cleanup(void);
extern void utc_webkit2_ewk_geolocation_permission_request_origin_get_func_startup(void);
extern void utc_webkit2_ewk_geolocation_permission_request_origin_get_func_cleanup(void);
extern void utc_webkit2_ewk_init_func_startup(void);
extern void utc_webkit2_ewk_init_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_headers_get_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_headers_get_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_http_method_get_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_http_method_get_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_ignore_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_ignore_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_body_set_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_body_set_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_add_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_add_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_add_func_neg_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_add_func_neg_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_map_add_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_map_add_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_set_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_set_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_status_set_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_status_set_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_status_set_func_neg_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_status_set_func_neg_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_response_write_chunk_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_response_write_chunk_func_cleanup(void);
extern void utc_webkit2_ewk_intercept_request_url_get_func_startup(void);
extern void utc_webkit2_ewk_intercept_request_url_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_background_color_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_background_color_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_count_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_count_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_height_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_height_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_sizes_count_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_sizes_count_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_src_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_src_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_type_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_type_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_icons_width_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_icons_width_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_name_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_name_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_orientation_type_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_orientation_type_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_short_name_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_short_name_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_start_url_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_start_url_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_theme_color_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_theme_color_get_func_cleanup(void);
extern void utc_webkit2_ewk_manifest_web_display_mode_get_func_startup(void);
extern void utc_webkit2_ewk_manifest_web_display_mode_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_cookie_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_cookie_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_host_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_host_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_http_method_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_http_method_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_ignore_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_ignore_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_navigation_type_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_navigation_type_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_response_headers_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_response_headers_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_response_mime_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_response_mime_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_response_status_code_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_response_status_code_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_scheme_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_scheme_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_type_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_type_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_url_get_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_url_get_func_cleanup(void);
extern void utc_webkit2_ewk_policy_decision_use_func_startup(void);
extern void utc_webkit2_ewk_policy_decision_use_func_cleanup(void);
extern void utc_webkit2_ewk_security_origin_host_get_func_startup(void);
extern void utc_webkit2_ewk_security_origin_host_get_func_cleanup(void);
extern void utc_webkit2_ewk_security_origin_protocol_get_func_startup(void);
extern void utc_webkit2_ewk_security_origin_protocol_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_default_font_size_get_func_startup(void);
extern void utc_webkit2_ewk_settings_default_font_size_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_default_font_size_set_func_startup(void);
extern void utc_webkit2_ewk_settings_default_font_size_set_func_cleanup(void);
extern void utc_webkit2_ewk_settings_default_text_encoding_name_get_func_startup(void);
extern void utc_webkit2_ewk_settings_default_text_encoding_name_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_default_text_encoding_name_set_func_startup(void);
extern void utc_webkit2_ewk_settings_default_text_encoding_name_set_func_cleanup(void);
extern void utc_webkit2_ewk_settings_javascript_enabled_get_func_startup(void);
extern void utc_webkit2_ewk_settings_javascript_enabled_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_javascript_enabled_set_func_startup(void);
extern void utc_webkit2_ewk_settings_javascript_enabled_set_func_cleanup(void);
extern void utc_webkit2_ewk_settings_loads_images_automatically_get_func_startup(void);
extern void utc_webkit2_ewk_settings_loads_images_automatically_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_loads_images_automatically_set_func_startup(void);
extern void utc_webkit2_ewk_settings_loads_images_automatically_set_func_cleanup(void);
extern void utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_startup(void);
extern void utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_cleanup(void);
extern void utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_startup(void);
extern void utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_cleanup(void);
extern void utc_webkit2_ewk_shutdown_func_startup(void);
extern void utc_webkit2_ewk_shutdown_func_cleanup(void);
extern void utc_webkit2_ewk_view_add_startup(void);
extern void utc_webkit2_ewk_view_add_cleanup(void);
extern void utc_webkit2_ewk_view_add_in_incognito_mode_startup(void);
extern void utc_webkit2_ewk_view_add_in_incognito_mode_cleanup(void);
extern void utc_webkit2_ewk_view_back_forward_list_clear_func_startup(void);
extern void utc_webkit2_ewk_view_back_forward_list_clear_func_cleanup(void);
extern void utc_webkit2_ewk_view_back_forward_list_get_func_startup(void);
extern void utc_webkit2_ewk_view_back_forward_list_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_back_startup(void);
extern void utc_webkit2_ewk_view_back_cleanup(void);
extern void utc_webkit2_ewk_view_back_possible_startup(void);
extern void utc_webkit2_ewk_view_back_possible_cleanup(void);
extern void utc_webkit2_ewk_view_contents_size_get_startup(void);
extern void utc_webkit2_ewk_view_contents_size_get_cleanup(void);
extern void utc_webkit2_ewk_view_context_get_func_startup(void);
extern void utc_webkit2_ewk_view_context_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_evaluate_javascript_startup(void);
extern void utc_webkit2_ewk_view_evaluate_javascript_cleanup(void);
extern void utc_webkit2_ewk_view_focus_get_startup(void);
extern void utc_webkit2_ewk_view_focus_get_cleanup(void);
extern void utc_webkit2_ewk_view_focus_set_startup(void);
extern void utc_webkit2_ewk_view_focus_set_cleanup(void);
extern void utc_webkit2_ewk_view_forward_startup(void);
extern void utc_webkit2_ewk_view_forward_cleanup(void);
extern void utc_webkit2_ewk_view_forward_possible_func_startup(void);
extern void utc_webkit2_ewk_view_forward_possible_func_cleanup(void);
extern void utc_webkit2_ewk_view_fullscreen_exit_func_startup(void);
extern void utc_webkit2_ewk_view_fullscreen_exit_func_cleanup(void);
extern void utc_webkit2_ewk_view_html_string_load_func_startup(void);
extern void utc_webkit2_ewk_view_html_string_load_func_cleanup(void);
extern void utc_webkit2_ewk_view_javascript_message_handler_add_startup(void);
extern void utc_webkit2_ewk_view_javascript_message_handler_add_cleanup(void);
extern void utc_webkit2_ewk_view_load_progress_get_func_startup(void);
extern void utc_webkit2_ewk_view_load_progress_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_orientation_send_func_startup(void);
extern void utc_webkit2_ewk_view_orientation_send_func_cleanup(void);
extern void utc_webkit2_ewk_view_original_url_get_startup(void);
extern void utc_webkit2_ewk_view_original_url_get_cleanup(void);
extern void utc_webkit2_ewk_view_reload_startup(void);
extern void utc_webkit2_ewk_view_reload_cleanup(void);
extern void utc_webkit2_ewk_view_request_manifest_startup(void);
extern void utc_webkit2_ewk_view_request_manifest_cleanup(void);
extern void utc_webkit2_ewk_view_resume_startup(void);
extern void utc_webkit2_ewk_view_resume_cleanup(void);
extern void utc_webkit2_ewk_view_scale_get_startup(void);
extern void utc_webkit2_ewk_view_scale_get_cleanup(void);
extern void utc_webkit2_ewk_view_scale_set_startup(void);
extern void utc_webkit2_ewk_view_scale_set_cleanup(void);
extern void utc_webkit2_ewk_view_script_execute_func_startup(void);
extern void utc_webkit2_ewk_view_script_execute_func_cleanup(void);
extern void utc_webkit2_ewk_view_scroll_by_func_startup(void);
extern void utc_webkit2_ewk_view_scroll_by_func_cleanup(void);
extern void utc_webkit2_ewk_view_scroll_pos_get_func_startup(void);
extern void utc_webkit2_ewk_view_scroll_pos_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_scroll_set_func_startup(void);
extern void utc_webkit2_ewk_view_scroll_set_func_cleanup(void);
extern void utc_webkit2_ewk_view_settings_get_func_startup(void);
extern void utc_webkit2_ewk_view_settings_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_stop_startup(void);
extern void utc_webkit2_ewk_view_stop_cleanup(void);
extern void utc_webkit2_ewk_view_suspend_startup(void);
extern void utc_webkit2_ewk_view_suspend_cleanup(void);
extern void utc_webkit2_ewk_view_text_find_func_startup(void);
extern void utc_webkit2_ewk_view_text_find_func_cleanup(void);
extern void utc_webkit2_ewk_view_title_get_startup(void);
extern void utc_webkit2_ewk_view_title_get_cleanup(void);
extern void utc_webkit2_ewk_view_url_get_startup(void);
extern void utc_webkit2_ewk_view_url_get_cleanup(void);
extern void utc_webkit2_ewk_view_url_request_set_func_startup(void);
extern void utc_webkit2_ewk_view_url_request_set_func_cleanup(void);
extern void utc_webkit2_ewk_view_url_set_func_startup(void);
extern void utc_webkit2_ewk_view_url_set_func_cleanup(void);
extern void utc_webkit2_ewk_view_user_agent_get_func_startup(void);
extern void utc_webkit2_ewk_view_user_agent_get_func_cleanup(void);
extern void utc_webkit2_ewk_view_user_agent_set_func_startup(void);
extern void utc_webkit2_ewk_view_user_agent_set_func_cleanup(void);
extern void utc_webkit2_ewk_view_visibility_set_func_startup(void);
extern void utc_webkit2_ewk_view_visibility_set_func_cleanup(void);

extern int utc_webkit2_ewk_back_forward_list_count_p(void);
extern int utc_webkit2_ewk_back_forward_list_count_n(void);
extern int utc_webkit2_ewk_back_forward_list_current_item_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_current_item_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_at_index_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_at_index_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_original_url_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_original_url_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_ref_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_ref_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_title_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_title_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_unref_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_unref_n(void);
extern int utc_webkit2_ewk_back_forward_list_item_url_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_item_url_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_n_back_items_copy_p(void);
extern int utc_webkit2_ewk_back_forward_list_n_back_items_copy_n(void);
extern int utc_webkit2_ewk_back_forward_list_n_forward_items_copy_p(void);
extern int utc_webkit2_ewk_back_forward_list_n_forward_items_copy_n(void);
extern int utc_webkit2_ewk_back_forward_list_next_item_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_next_item_get_n(void);
extern int utc_webkit2_ewk_back_forward_list_previous_item_get_p(void);
extern int utc_webkit2_ewk_back_forward_list_previous_item_get_n(void);
extern int utc_webkit2_ewk_context_background_music_get_p(void);
extern int utc_webkit2_ewk_context_background_music_get_p1(void);
extern int utc_webkit2_ewk_context_background_music_get_n(void);
extern int utc_webkit2_ewk_context_background_music_get_n1(void);
extern int utc_webkit2_ewk_context_background_music_set_p(void);
extern int utc_webkit2_ewk_context_background_music_set_p1(void);
extern int utc_webkit2_ewk_context_background_music_set_n(void);
extern int utc_webkit2_ewk_context_background_music_set_n1(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_get_p(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_get_p1(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_get_n(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_get_n1(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_set_p(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_set_p1(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_set_n(void);
extern int utc_webkit2_ewk_context_block_multimedia_on_call_set_n1(void);
extern int utc_webkit2_ewk_context_cache_model_get_p(void);
extern int utc_webkit2_ewk_context_cache_model_get_p1(void);
extern int utc_webkit2_ewk_context_cache_model_get_p2(void);
extern int utc_webkit2_ewk_context_cache_model_get_n(void);
extern int utc_webkit2_ewk_context_cache_model_get_n1(void);
extern int utc_webkit2_ewk_context_cache_model_get_n2(void);
extern int utc_webkit2_ewk_context_cache_model_set_p(void);
extern int utc_webkit2_ewk_context_cache_model_set_p1(void);
extern int utc_webkit2_ewk_context_cache_model_set_p2(void);
extern int utc_webkit2_ewk_context_cache_model_set_n(void);
extern int utc_webkit2_ewk_context_cache_model_set_n1(void);
extern int utc_webkit2_ewk_context_cache_model_set_n2(void);
extern int utc_webkit2_ewk_context_cookie_manager_get_p(void);
extern int utc_webkit2_ewk_context_cookie_manager_get_n(void);
extern int utc_webkit2_ewk_context_intercept_request_callback_set_p(void);
extern int utc_webkit2_ewk_context_intercept_request_callback_set_p1(void);
extern int utc_webkit2_ewk_context_intercept_request_callback_set_n(void);
extern int utc_webkit2_ewk_context_menu_item_count_n(void);
extern int utc_webkit2_ewk_context_menu_item_remove_n(void);
extern int utc_webkit2_ewk_context_menu_item_tag_get_n(void);
extern int utc_webkit2_ewk_context_menu_nth_item_get_n(void);
extern int utc_webkit2_ewk_context_resource_cache_clear_p(void);
extern int utc_webkit2_ewk_context_resource_cache_clear_n(void);
extern int utc_webkit2_ewk_context_rotation_lock_get_p(void);
extern int utc_webkit2_ewk_context_rotation_lock_get_p1(void);
extern int utc_webkit2_ewk_context_rotation_lock_get_n(void);
extern int utc_webkit2_ewk_context_rotation_lock_get_n1(void);
extern int utc_webkit2_ewk_context_rotation_lock_set_p(void);
extern int utc_webkit2_ewk_context_rotation_lock_set_p1(void);
extern int utc_webkit2_ewk_context_rotation_lock_set_n(void);
extern int utc_webkit2_ewk_context_rotation_lock_set_n1(void);
extern int utc_webkit2_ewk_context_sound_overlap_get_p(void);
extern int utc_webkit2_ewk_context_sound_overlap_get_p1(void);
extern int utc_webkit2_ewk_context_sound_overlap_get_n(void);
extern int utc_webkit2_ewk_context_sound_overlap_get_n1(void);
extern int utc_webkit2_ewk_context_sound_overlap_set_p(void);
extern int utc_webkit2_ewk_context_sound_overlap_set_p1(void);
extern int utc_webkit2_ewk_context_sound_overlap_set_n(void);
extern int utc_webkit2_ewk_context_sound_overlap_set_n1(void);
extern int utc_webkit2_ewk_cookie_manager_accept_policy_async_get_p(void);
extern int utc_webkit2_ewk_cookie_manager_accept_policy_async_get_n(void);
extern int utc_webkit2_ewk_cookie_manager_accept_policy_set_p(void);
extern int utc_webkit2_ewk_cookie_manager_accept_policy_set_n(void);
extern int utc_webkit2_ewk_cookie_manager_cookies_clear_p(void);
extern int utc_webkit2_ewk_cookie_manager_cookies_clear_n(void);
extern int utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_p(void);
extern int utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_n(void);
extern int utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_p(void);
extern int utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_n(void);
extern int utc_webkit2_ewk_geolocation_permission_request_origin_get_n(void);
extern int utc_webkit2_ewk_init_p(void);
extern int utc_webkit2_ewk_init_n(void);
extern int utc_webkit2_ewk_intercept_request_headers_get_p(void);
extern int utc_webkit2_ewk_intercept_request_headers_get_n(void);
extern int utc_webkit2_ewk_intercept_request_http_method_get_p(void);
extern int utc_webkit2_ewk_intercept_request_http_method_get_n(void);
extern int utc_webkit2_ewk_intercept_request_ignore_p(void);
extern int utc_webkit2_ewk_intercept_request_ignore_n(void);
extern int utc_webkit2_ewk_intercept_request_response_body_set_p(void);
extern int utc_webkit2_ewk_intercept_request_response_body_set_n(void);
extern int utc_webkit2_ewk_intercept_request_response_body_set_n1(void);
extern int utc_webkit2_ewk_intercept_request_response_header_add_p(void);
extern int utc_webkit2_ewk_intercept_request_response_header_add_n(void);
extern int utc_webkit2_ewk_intercept_request_response_header_add_n1(void);
extern int utc_webkit2_ewk_intercept_request_response_header_add_n2(void);
extern int utc_webkit2_ewk_intercept_request_response_header_map_add_p(void);
extern int utc_webkit2_ewk_intercept_request_response_header_map_add_n(void);
extern int utc_webkit2_ewk_intercept_request_response_header_map_add_n1(void);
extern int utc_webkit2_ewk_intercept_request_response_set_p(void);
extern int utc_webkit2_ewk_intercept_request_response_set_n(void);
extern int utc_webkit2_ewk_intercept_request_response_set_n1(void);
extern int utc_webkit2_ewk_intercept_request_response_set_n2(void);
extern int utc_webkit2_ewk_intercept_request_response_status_set_p(void);
extern int utc_webkit2_ewk_intercept_request_response_status_set_p1(void);
extern int utc_webkit2_ewk_intercept_request_response_status_set_n(void);
extern int utc_webkit2_ewk_intercept_request_response_write_chunk_p(void);
extern int utc_webkit2_ewk_intercept_request_response_write_chunk_n(void);
extern int utc_webkit2_ewk_intercept_request_response_write_chunk_n1(void);
extern int utc_webkit2_ewk_intercept_request_url_get_p(void);
extern int utc_webkit2_ewk_intercept_request_url_get_n(void);
extern int utc_webkit2_ewk_manifest_background_color_get_p(void);
extern int utc_webkit2_ewk_manifest_background_color_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_count_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_count_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_height_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_height_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_sizes_count_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_sizes_count_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_src_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_src_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_type_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_type_get_n(void);
extern int utc_webkit2_ewk_manifest_icons_width_get_p(void);
extern int utc_webkit2_ewk_manifest_icons_width_get_n(void);
extern int utc_webkit2_ewk_manifest_name_get_p(void);
extern int utc_webkit2_ewk_manifest_name_get_n(void);
extern int utc_webkit2_ewk_manifest_orientation_type_get_p(void);
extern int utc_webkit2_ewk_manifest_orientation_type_get_n(void);
extern int utc_webkit2_ewk_manifest_short_name_get_p(void);
extern int utc_webkit2_ewk_manifest_short_name_get_n(void);
extern int utc_webkit2_ewk_manifest_start_url_get_p(void);
extern int utc_webkit2_ewk_manifest_start_url_get_n(void);
extern int utc_webkit2_ewk_manifest_theme_color_get_p(void);
extern int utc_webkit2_ewk_manifest_theme_color_get_n(void);
extern int utc_webkit2_ewk_manifest_web_display_mode_get_p(void);
extern int utc_webkit2_ewk_manifest_web_display_mode_get_n(void);
extern int utc_webkit2_ewk_policy_decision_cookie_get_p(void);
extern int utc_webkit2_ewk_policy_decision_cookie_get_n(void);
extern int utc_webkit2_ewk_policy_decision_host_get_p(void);
extern int utc_webkit2_ewk_policy_decision_host_get_n(void);
extern int utc_webkit2_ewk_policy_decision_http_method_get_p(void);
extern int utc_webkit2_ewk_policy_decision_http_method_get_n(void);
extern int utc_webkit2_ewk_policy_decision_ignore_p(void);
extern int utc_webkit2_ewk_policy_decision_ignore_n(void);
extern int utc_webkit2_ewk_policy_decision_navigation_type_get_p(void);
extern int utc_webkit2_ewk_policy_decision_navigation_type_get_n(void);
extern int utc_webkit2_ewk_policy_decision_response_headers_get_p(void);
extern int utc_webkit2_ewk_policy_decision_response_headers_get_n(void);
extern int utc_webkit2_ewk_policy_decision_response_mime_get_p(void);
extern int utc_webkit2_ewk_policy_decision_response_mime_get_n(void);
extern int utc_webkit2_ewk_policy_decision_response_status_code_get_p(void);
extern int utc_webkit2_ewk_policy_decision_response_status_code_get_n(void);
extern int utc_webkit2_ewk_policy_decision_scheme_get_p(void);
extern int utc_webkit2_ewk_policy_decision_scheme_get_n(void);
extern int utc_webkit2_ewk_policy_decision_type_get_p(void);
extern int utc_webkit2_ewk_policy_decision_type_get_n(void);
extern int utc_webkit2_ewk_policy_decision_url_get_p(void);
extern int utc_webkit2_ewk_policy_decision_url_get_n(void);
extern int utc_webkit2_ewk_policy_decision_use_p(void);
extern int utc_webkit2_ewk_policy_decision_use_n(void);
extern int utc_webkit2_ewk_security_origin_host_get_n(void);
extern int utc_webkit2_ewk_security_origin_protocol_get_n(void);
extern int utc_webkit2_ewk_settings_default_font_size_get_p(void);
extern int utc_webkit2_ewk_settings_default_font_size_get_p1(void);
extern int utc_webkit2_ewk_settings_default_font_size_get_n(void);
extern int utc_webkit2_ewk_settings_default_font_size_set_p(void);
extern int utc_webkit2_ewk_settings_default_font_size_set_n(void);
extern int utc_webkit2_ewk_settings_default_text_encoding_name_get_p(void);
extern int utc_webkit2_ewk_settings_default_text_encoding_name_get_p1(void);
extern int utc_webkit2_ewk_settings_default_text_encoding_name_get_n(void);
extern int utc_webkit2_ewk_settings_default_text_encoding_name_set_p(void);
extern int utc_webkit2_ewk_settings_default_text_encoding_name_set_n(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_get_p(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_get_p1(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_get_n(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_set_p(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_set_p1(void);
extern int utc_webkit2_ewk_settings_javascript_enabled_set_n(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_get_p(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_get_p1(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_get_n(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_set_p(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_set_p1(void);
extern int utc_webkit2_ewk_settings_loads_images_automatically_set_n(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_get_p(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_get_p1(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_get_n(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_set_p(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_set_p1(void);
extern int utc_webkit2_ewk_settings_scripts_can_open_windows_set_n(void);
extern int utc_webkit2_ewk_shutdown_p(void);
extern int utc_webkit2_ewk_shutdown_n(void);
extern int utc_webkit2_ewk_view_add_p(void);
extern int utc_webkit2_ewk_view_add_n(void);
extern int utc_webkit2_ewk_view_add_in_incognito_mode_p(void);
extern int utc_webkit2_ewk_view_add_in_incognito_mode_n(void);
extern int utc_webkit2_ewk_view_back_forward_list_clear_p(void);
extern int utc_webkit2_ewk_view_back_forward_list_clear_n(void);
extern int utc_webkit2_ewk_view_back_forward_list_get_p(void);
extern int utc_webkit2_ewk_view_back_forward_list_get_n(void);
extern int utc_webkit2_ewk_view_back_p(void);
extern int utc_webkit2_ewk_view_back_n(void);
extern int utc_webkit2_ewk_view_back_possible_p1(void);
extern int utc_webkit2_ewk_view_back_possible_p2(void);
extern int utc_webkit2_ewk_view_back_possible_p3(void);
extern int utc_webkit2_ewk_view_back_possible_n(void);
extern int utc_webkit2_ewk_view_contents_size_get_p(void);
extern int utc_webkit2_ewk_view_contents_size_get_n(void);
extern int utc_webkit2_ewk_view_context_get_p(void);
extern int utc_webkit2_ewk_view_context_get_n(void);
extern int utc_webkit2_ewk_view_evaluate_javascript_p(void);
extern int utc_webkit2_ewk_view_evaluate_javascript_n(void);
extern int utc_webkit2_ewk_view_focus_get_p(void);
extern int utc_webkit2_ewk_view_focus_get_p1(void);
extern int utc_webkit2_ewk_view_focus_get_n(void);
extern int utc_webkit2_ewk_view_focus_set_p(void);
extern int utc_webkit2_ewk_view_focus_set_p1(void);
extern int utc_webkit2_ewk_view_focus_set_n(void);
extern int utc_webkit2_ewk_view_forward_p(void);
extern int utc_webkit2_ewk_view_forward_n(void);
extern int utc_webkit2_ewk_view_forward_possible_p(void);
extern int utc_webkit2_ewk_view_forward_possible_p1(void);
extern int utc_webkit2_ewk_view_forward_possible_p2(void);
extern int utc_webkit2_ewk_view_forward_possible_n(void);
extern int utc_webkit2_ewk_view_fullscreen_exit_p(void);
extern int utc_webkit2_ewk_view_fullscreen_exit_n(void);
extern int utc_webkit2_ewk_view_html_string_load_p(void);
extern int utc_webkit2_ewk_view_html_string_load_n(void);
extern int utc_webkit2_ewk_view_javascript_message_handler_add_p(void);
extern int utc_webkit2_ewk_view_javascript_message_handler_add_n(void);
extern int utc_webkit2_ewk_view_load_progress_get_p(void);
extern int utc_webkit2_ewk_view_load_progress_get_p1(void);
extern int utc_webkit2_ewk_view_load_progress_get_n(void);
extern int utc_webkit2_ewk_view_orientation_send_p(void);
extern int utc_webkit2_ewk_view_orientation_send_n(void);
extern int utc_webkit2_ewk_view_original_url_get_p(void);
extern int utc_webkit2_ewk_view_original_url_get_n(void);
extern int utc_webkit2_ewk_view_reload_p(void);
extern int utc_webkit2_ewk_view_reload_n(void);
extern int utc_webkit2_ewk_view_request_manifest_p(void);
extern int utc_webkit2_ewk_view_request_manifest_n(void);
extern int utc_webkit2_ewk_view_resume_p(void);
extern int utc_webkit2_ewk_view_resume_n(void);
extern int utc_webkit2_ewk_view_scale_get_p(void);
extern int utc_webkit2_ewk_view_scale_get_n(void);
extern int utc_webkit2_ewk_view_scale_set_p(void);
extern int utc_webkit2_ewk_view_scale_set_n(void);
extern int utc_webkit2_ewk_view_script_execute_p(void);
extern int utc_webkit2_ewk_view_script_execute_n(void);
extern int utc_webkit2_ewk_view_script_execute_n1(void);
extern int utc_webkit2_ewk_view_scroll_by_p(void);
extern int utc_webkit2_ewk_view_scroll_by_p1(void);
extern int utc_webkit2_ewk_view_scroll_by_p2(void);
extern int utc_webkit2_ewk_view_scroll_by_n(void);
extern int utc_webkit2_ewk_view_scroll_pos_get_p(void);
extern int utc_webkit2_ewk_view_scroll_pos_get_p1(void);
extern int utc_webkit2_ewk_view_scroll_pos_get_n(void);
extern int utc_webkit2_ewk_view_scroll_set_p(void);
extern int utc_webkit2_ewk_view_scroll_set_p1(void);
extern int utc_webkit2_ewk_view_scroll_set_p2(void);
extern int utc_webkit2_ewk_view_scroll_set_n(void);
extern int utc_webkit2_ewk_view_settings_get_p(void);
extern int utc_webkit2_ewk_view_settings_get_n(void);
extern int utc_webkit2_ewk_view_stop_p(void);
extern int utc_webkit2_ewk_view_stop_n(void);
extern int utc_webkit2_ewk_view_suspend_p(void);
extern int utc_webkit2_ewk_view_suspend_n(void);
extern int utc_webkit2_ewk_view_text_find_p(void);
extern int utc_webkit2_ewk_view_text_find_n(void);
extern int utc_webkit2_ewk_view_title_get_p(void);
extern int utc_webkit2_ewk_view_title_get_n(void);
extern int utc_webkit2_ewk_view_url_get_p(void);
extern int utc_webkit2_ewk_view_url_get_n(void);
extern int utc_webkit2_ewk_view_url_request_set_p(void);
extern int utc_webkit2_ewk_view_url_request_set_n(void);
extern int utc_webkit2_ewk_view_url_request_set_n1(void);
extern int utc_webkit2_ewk_view_url_request_set_n2(void);
extern int utc_webkit2_ewk_view_url_set_p(void);
extern int utc_webkit2_ewk_view_url_set_n(void);
extern int utc_webkit2_ewk_view_user_agent_get_p(void);
extern int utc_webkit2_ewk_view_user_agent_get_n(void);
extern int utc_webkit2_ewk_view_user_agent_set_p(void);
extern int utc_webkit2_ewk_view_user_agent_set_n(void);
extern int utc_webkit2_ewk_view_visibility_set_p(void);
extern int utc_webkit2_ewk_view_visibility_set_n(void);

testcase tc_array[] = {
	{"utc_webkit2_ewk_back_forward_list_count_p",utc_webkit2_ewk_back_forward_list_count_p,utc_webkit2_ewk_back_forward_list_count_func_startup,utc_webkit2_ewk_back_forward_list_count_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_count_n",utc_webkit2_ewk_back_forward_list_count_n,utc_webkit2_ewk_back_forward_list_count_func_startup,utc_webkit2_ewk_back_forward_list_count_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_current_item_get_p",utc_webkit2_ewk_back_forward_list_current_item_get_p,utc_webkit2_ewk_back_forward_list_current_item_get_func_startup,utc_webkit2_ewk_back_forward_list_current_item_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_current_item_get_n",utc_webkit2_ewk_back_forward_list_current_item_get_n,utc_webkit2_ewk_back_forward_list_current_item_get_func_startup,utc_webkit2_ewk_back_forward_list_current_item_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_at_index_get_p",utc_webkit2_ewk_back_forward_list_item_at_index_get_p,utc_webkit2_ewk_back_forward_list_item_at_index_get_func_startup,utc_webkit2_ewk_back_forward_list_item_at_index_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_at_index_get_n",utc_webkit2_ewk_back_forward_list_item_at_index_get_n,utc_webkit2_ewk_back_forward_list_item_at_index_get_func_startup,utc_webkit2_ewk_back_forward_list_item_at_index_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_original_url_get_p",utc_webkit2_ewk_back_forward_list_item_original_url_get_p,utc_webkit2_ewk_back_forward_list_item_original_url_get_func_startup,utc_webkit2_ewk_back_forward_list_item_original_url_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_original_url_get_n",utc_webkit2_ewk_back_forward_list_item_original_url_get_n,utc_webkit2_ewk_back_forward_list_item_original_url_get_func_startup,utc_webkit2_ewk_back_forward_list_item_original_url_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_ref_p",utc_webkit2_ewk_back_forward_list_item_ref_p,utc_webkit2_ewk_back_forward_list_item_ref_func_startup,utc_webkit2_ewk_back_forward_list_item_ref_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_ref_n",utc_webkit2_ewk_back_forward_list_item_ref_n,utc_webkit2_ewk_back_forward_list_item_ref_func_startup,utc_webkit2_ewk_back_forward_list_item_ref_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_title_get_p",utc_webkit2_ewk_back_forward_list_item_title_get_p,utc_webkit2_ewk_back_forward_list_item_title_get_func_startup,utc_webkit2_ewk_back_forward_list_item_title_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_title_get_n",utc_webkit2_ewk_back_forward_list_item_title_get_n,utc_webkit2_ewk_back_forward_list_item_title_get_func_startup,utc_webkit2_ewk_back_forward_list_item_title_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_unref_p",utc_webkit2_ewk_back_forward_list_item_unref_p,utc_webkit2_ewk_back_forward_list_item_unref_func_startup,utc_webkit2_ewk_back_forward_list_item_unref_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_unref_n",utc_webkit2_ewk_back_forward_list_item_unref_n,utc_webkit2_ewk_back_forward_list_item_unref_func_startup,utc_webkit2_ewk_back_forward_list_item_unref_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_url_get_p",utc_webkit2_ewk_back_forward_list_item_url_get_p,utc_webkit2_ewk_back_forward_list_item_url_get_func_startup,utc_webkit2_ewk_back_forward_list_item_url_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_item_url_get_n",utc_webkit2_ewk_back_forward_list_item_url_get_n,utc_webkit2_ewk_back_forward_list_item_url_get_func_startup,utc_webkit2_ewk_back_forward_list_item_url_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_n_back_items_copy_p",utc_webkit2_ewk_back_forward_list_n_back_items_copy_p,utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_startup,utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_n_back_items_copy_n",utc_webkit2_ewk_back_forward_list_n_back_items_copy_n,utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_startup,utc_webkit2_ewk_back_forward_list_n_back_items_copy_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_n_forward_items_copy_p",utc_webkit2_ewk_back_forward_list_n_forward_items_copy_p,utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_startup,utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_n_forward_items_copy_n",utc_webkit2_ewk_back_forward_list_n_forward_items_copy_n,utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_startup,utc_webkit2_ewk_back_forward_list_n_forward_items_copy_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_next_item_get_p",utc_webkit2_ewk_back_forward_list_next_item_get_p,utc_webkit2_ewk_back_forward_list_next_item_get_func_startup,utc_webkit2_ewk_back_forward_list_next_item_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_next_item_get_n",utc_webkit2_ewk_back_forward_list_next_item_get_n,utc_webkit2_ewk_back_forward_list_next_item_get_func_startup,utc_webkit2_ewk_back_forward_list_next_item_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_previous_item_get_p",utc_webkit2_ewk_back_forward_list_previous_item_get_p,utc_webkit2_ewk_back_forward_list_previous_item_get_func_startup,utc_webkit2_ewk_back_forward_list_previous_item_get_func_cleanup},
	{"utc_webkit2_ewk_back_forward_list_previous_item_get_n",utc_webkit2_ewk_back_forward_list_previous_item_get_n,utc_webkit2_ewk_back_forward_list_previous_item_get_func_startup,utc_webkit2_ewk_back_forward_list_previous_item_get_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_get_p",utc_webkit2_ewk_context_background_music_get_p,utc_webkit2_ewk_context_background_music_get_func_startup,utc_webkit2_ewk_context_background_music_get_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_get_p1",utc_webkit2_ewk_context_background_music_get_p1,utc_webkit2_ewk_context_background_music_get_func_startup,utc_webkit2_ewk_context_background_music_get_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_get_n",utc_webkit2_ewk_context_background_music_get_n,utc_webkit2_ewk_context_background_music_get_func_startup,utc_webkit2_ewk_context_background_music_get_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_get_n1",utc_webkit2_ewk_context_background_music_get_n1,utc_webkit2_ewk_context_background_music_get_func_startup,utc_webkit2_ewk_context_background_music_get_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_set_p",utc_webkit2_ewk_context_background_music_set_p,utc_webkit2_ewk_context_background_music_set_func_startup,utc_webkit2_ewk_context_background_music_set_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_set_p1",utc_webkit2_ewk_context_background_music_set_p1,utc_webkit2_ewk_context_background_music_set_func_startup,utc_webkit2_ewk_context_background_music_set_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_set_n",utc_webkit2_ewk_context_background_music_set_n,utc_webkit2_ewk_context_background_music_set_func_startup,utc_webkit2_ewk_context_background_music_set_func_cleanup},
        {"utc_webkit2_ewk_context_background_music_set_n1",utc_webkit2_ewk_context_background_music_set_n1,utc_webkit2_ewk_context_background_music_set_func_startup,utc_webkit2_ewk_context_background_music_set_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_get_p",utc_webkit2_ewk_context_block_multimedia_on_call_get_p,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_get_p1",utc_webkit2_ewk_context_block_multimedia_on_call_get_p1,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_get_n",utc_webkit2_ewk_context_block_multimedia_on_call_get_n,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_get_n1",utc_webkit2_ewk_context_block_multimedia_on_call_get_n1,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_get_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_set_p",utc_webkit2_ewk_context_block_multimedia_on_call_set_p,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_set_p1",utc_webkit2_ewk_context_block_multimedia_on_call_set_p1,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_set_n",utc_webkit2_ewk_context_block_multimedia_on_call_set_n,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_cleanup},
        {"utc_webkit2_ewk_context_block_multimedia_on_call_set_n1",utc_webkit2_ewk_context_block_multimedia_on_call_set_n1,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_startup,utc_webkit2_ewk_context_block_multimedia_on_call_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_p",utc_webkit2_ewk_context_cache_model_get_p,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_p1",utc_webkit2_ewk_context_cache_model_get_p1,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_p2",utc_webkit2_ewk_context_cache_model_get_p2,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_n",utc_webkit2_ewk_context_cache_model_get_n,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_n1",utc_webkit2_ewk_context_cache_model_get_n1,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_get_n2",utc_webkit2_ewk_context_cache_model_get_n2,utc_webkit2_ewk_context_cache_model_get_func_startup,utc_webkit2_ewk_context_cache_model_get_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_p",utc_webkit2_ewk_context_cache_model_set_p,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_p1",utc_webkit2_ewk_context_cache_model_set_p1,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_p2",utc_webkit2_ewk_context_cache_model_set_p2,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_n",utc_webkit2_ewk_context_cache_model_set_n,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_n1",utc_webkit2_ewk_context_cache_model_set_n1,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cache_model_set_n2",utc_webkit2_ewk_context_cache_model_set_n2,utc_webkit2_ewk_context_cache_model_set_func_startup,utc_webkit2_ewk_context_cache_model_set_func_cleanup},
	{"utc_webkit2_ewk_context_cookie_manager_get_p",utc_webkit2_ewk_context_cookie_manager_get_p,utc_webkit2_ewk_context_cookie_manager_get_func_startup,utc_webkit2_ewk_context_cookie_manager_get_func_cleanup},
	{"utc_webkit2_ewk_context_cookie_manager_get_n",utc_webkit2_ewk_context_cookie_manager_get_n,utc_webkit2_ewk_context_cookie_manager_get_func_startup,utc_webkit2_ewk_context_cookie_manager_get_func_cleanup},
	{"utc_webkit2_ewk_context_intercept_request_callback_set_p",utc_webkit2_ewk_context_intercept_request_callback_set_p,utc_webkit2_ewk_context_intercept_request_callback_set_func_startup,utc_webkit2_ewk_context_intercept_request_callback_set_func_cleanup},
	{"utc_webkit2_ewk_context_intercept_request_callback_set_p1",utc_webkit2_ewk_context_intercept_request_callback_set_p1,utc_webkit2_ewk_context_intercept_request_callback_set_func_startup,utc_webkit2_ewk_context_intercept_request_callback_set_func_cleanup},
	{"utc_webkit2_ewk_context_intercept_request_callback_set_n",utc_webkit2_ewk_context_intercept_request_callback_set_n,utc_webkit2_ewk_context_intercept_request_callback_set_func_startup,utc_webkit2_ewk_context_intercept_request_callback_set_func_cleanup},
	{"utc_webkit2_ewk_context_menu_item_count_n",utc_webkit2_ewk_context_menu_item_count_n,utc_webkit2_ewk_context_menu_item_count_func_startup,utc_webkit2_ewk_context_menu_item_count_func_cleanup},
	{"utc_webkit2_ewk_context_menu_item_remove_n",utc_webkit2_ewk_context_menu_item_remove_n,utc_webkit2_ewk_context_menu_item_remove_func_startup,utc_webkit2_ewk_context_menu_item_remove_func_cleanup},
	{"utc_webkit2_ewk_context_menu_item_tag_get_n",utc_webkit2_ewk_context_menu_item_tag_get_n,utc_webkit2_ewk_context_menu_item_tag_get_func_startup,utc_webkit2_ewk_context_menu_item_tag_get_func_cleanup},
	{"utc_webkit2_ewk_context_menu_nth_item_get_n",utc_webkit2_ewk_context_menu_nth_item_get_n,utc_webkit2_ewk_context_menu_nth_item_get_func_startup,utc_webkit2_ewk_context_menu_nth_item_get_func_cleanup},
	{"utc_webkit2_ewk_context_resource_cache_clear_p",utc_webkit2_ewk_context_resource_cache_clear_p,utc_webkit2_ewk_context_resource_cache_clear_func_startup,utc_webkit2_ewk_context_resource_cache_clear_func_cleanup},
	{"utc_webkit2_ewk_context_resource_cache_clear_n",utc_webkit2_ewk_context_resource_cache_clear_n,utc_webkit2_ewk_context_resource_cache_clear_func_startup,utc_webkit2_ewk_context_resource_cache_clear_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_get_p",utc_webkit2_ewk_context_rotation_lock_get_p,utc_webkit2_ewk_context_rotation_lock_get_func_startup,utc_webkit2_ewk_context_rotation_lock_get_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_get_p1",utc_webkit2_ewk_context_rotation_lock_get_p1,utc_webkit2_ewk_context_rotation_lock_get_func_startup,utc_webkit2_ewk_context_rotation_lock_get_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_get_n",utc_webkit2_ewk_context_rotation_lock_get_n,utc_webkit2_ewk_context_rotation_lock_get_func_startup,utc_webkit2_ewk_context_rotation_lock_get_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_get_n1",utc_webkit2_ewk_context_rotation_lock_get_n1,utc_webkit2_ewk_context_rotation_lock_get_func_startup,utc_webkit2_ewk_context_rotation_lock_get_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_set_p",utc_webkit2_ewk_context_rotation_lock_set_p,utc_webkit2_ewk_context_rotation_lock_set_func_startup,utc_webkit2_ewk_context_rotation_lock_set_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_set_p1",utc_webkit2_ewk_context_rotation_lock_set_p1,utc_webkit2_ewk_context_rotation_lock_set_func_startup,utc_webkit2_ewk_context_rotation_lock_set_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_set_n",utc_webkit2_ewk_context_rotation_lock_set_n,utc_webkit2_ewk_context_rotation_lock_set_func_startup,utc_webkit2_ewk_context_rotation_lock_set_func_cleanup},
        {"utc_webkit2_ewk_context_rotation_lock_set_n1",utc_webkit2_ewk_context_rotation_lock_set_n1,utc_webkit2_ewk_context_rotation_lock_set_func_startup,utc_webkit2_ewk_context_rotation_lock_set_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_get_p",utc_webkit2_ewk_context_sound_overlap_get_p,utc_webkit2_ewk_context_sound_overlap_get_func_startup,utc_webkit2_ewk_context_sound_overlap_get_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_get_p1",utc_webkit2_ewk_context_sound_overlap_get_p1,utc_webkit2_ewk_context_sound_overlap_get_func_startup,utc_webkit2_ewk_context_sound_overlap_get_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_get_n",utc_webkit2_ewk_context_sound_overlap_get_n,utc_webkit2_ewk_context_sound_overlap_get_func_startup,utc_webkit2_ewk_context_sound_overlap_get_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_get_n1",utc_webkit2_ewk_context_sound_overlap_get_n1,utc_webkit2_ewk_context_sound_overlap_get_func_startup,utc_webkit2_ewk_context_sound_overlap_get_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_set_p",utc_webkit2_ewk_context_sound_overlap_set_p,utc_webkit2_ewk_context_sound_overlap_set_func_startup,utc_webkit2_ewk_context_sound_overlap_set_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_set_p1",utc_webkit2_ewk_context_sound_overlap_set_p1,utc_webkit2_ewk_context_sound_overlap_set_func_startup,utc_webkit2_ewk_context_sound_overlap_set_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_set_n",utc_webkit2_ewk_context_sound_overlap_set_n,utc_webkit2_ewk_context_sound_overlap_set_func_startup,utc_webkit2_ewk_context_sound_overlap_set_func_cleanup},
        {"utc_webkit2_ewk_context_sound_overlap_set_n1",utc_webkit2_ewk_context_sound_overlap_set_n1,utc_webkit2_ewk_context_sound_overlap_set_func_startup,utc_webkit2_ewk_context_sound_overlap_set_func_cleanup},
	{"utc_webkit2_ewk_cookie_manager_accept_policy_async_get_p",utc_webkit2_ewk_cookie_manager_accept_policy_async_get_p,utc_webkit2_ewk_cookie_manager_accept_policy_async_get_startup,utc_webkit2_ewk_cookie_manager_accept_policy_async_get_cleanup},
	{"utc_webkit2_ewk_cookie_manager_accept_policy_async_get_n",utc_webkit2_ewk_cookie_manager_accept_policy_async_get_n,utc_webkit2_ewk_cookie_manager_accept_policy_async_get_startup,utc_webkit2_ewk_cookie_manager_accept_policy_async_get_cleanup},
	{"utc_webkit2_ewk_cookie_manager_accept_policy_set_p",utc_webkit2_ewk_cookie_manager_accept_policy_set_p,utc_webkit2_ewk_cookie_manager_accept_policy_set_startup,utc_webkit2_ewk_cookie_manager_accept_policy_set_cleanup},
	{"utc_webkit2_ewk_cookie_manager_accept_policy_set_n",utc_webkit2_ewk_cookie_manager_accept_policy_set_n,utc_webkit2_ewk_cookie_manager_accept_policy_set_startup,utc_webkit2_ewk_cookie_manager_accept_policy_set_cleanup},
	{"utc_webkit2_ewk_cookie_manager_cookies_clear_p",utc_webkit2_ewk_cookie_manager_cookies_clear_p,utc_webkit2_ewk_cookie_manager_cookies_clear_func_startup,utc_webkit2_ewk_cookie_manager_cookies_clear_func_cleanup},
	{"utc_webkit2_ewk_cookie_manager_cookies_clear_n",utc_webkit2_ewk_cookie_manager_cookies_clear_n,utc_webkit2_ewk_cookie_manager_cookies_clear_func_startup,utc_webkit2_ewk_cookie_manager_cookies_clear_func_cleanup},
	{"utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_p",utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_p,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_startup,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_cleanup},
	{"utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_n",utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_n,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_startup,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_get_cleanup},
	{"utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_p",utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_p,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_startup,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_cleanup},
	{"utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_n",utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_n,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_startup,utc_webkit2_ewk_cookie_manager_file_scheme_cookies_allow_set_cleanup},
	{"utc_webkit2_ewk_geolocation_permission_request_origin_get_n",utc_webkit2_ewk_geolocation_permission_request_origin_get_n,utc_webkit2_ewk_geolocation_permission_request_origin_get_func_startup,utc_webkit2_ewk_geolocation_permission_request_origin_get_func_cleanup},
	{"utc_webkit2_ewk_init_p",utc_webkit2_ewk_init_p,utc_webkit2_ewk_init_func_startup,utc_webkit2_ewk_init_func_cleanup},
	{"utc_webkit2_ewk_init_n",utc_webkit2_ewk_init_n,utc_webkit2_ewk_init_func_startup,utc_webkit2_ewk_init_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_headers_get_p",utc_webkit2_ewk_intercept_request_headers_get_p,utc_webkit2_ewk_intercept_request_headers_get_func_startup,utc_webkit2_ewk_intercept_request_headers_get_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_headers_get_n",utc_webkit2_ewk_intercept_request_headers_get_n,utc_webkit2_ewk_intercept_request_headers_get_func_startup,utc_webkit2_ewk_intercept_request_headers_get_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_http_method_get_p",utc_webkit2_ewk_intercept_request_http_method_get_p,utc_webkit2_ewk_intercept_request_http_method_get_func_startup,utc_webkit2_ewk_intercept_request_http_method_get_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_http_method_get_n",utc_webkit2_ewk_intercept_request_http_method_get_n,utc_webkit2_ewk_intercept_request_http_method_get_func_startup,utc_webkit2_ewk_intercept_request_http_method_get_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_ignore_p",utc_webkit2_ewk_intercept_request_ignore_p,utc_webkit2_ewk_intercept_request_ignore_func_startup,utc_webkit2_ewk_intercept_request_ignore_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_ignore_n",utc_webkit2_ewk_intercept_request_ignore_n,utc_webkit2_ewk_intercept_request_ignore_func_startup,utc_webkit2_ewk_intercept_request_ignore_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_body_set_p",utc_webkit2_ewk_intercept_request_response_body_set_p,utc_webkit2_ewk_intercept_request_response_body_set_func_startup,utc_webkit2_ewk_intercept_request_response_body_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_body_set_n",utc_webkit2_ewk_intercept_request_response_body_set_n,utc_webkit2_ewk_intercept_request_response_body_set_func_startup,utc_webkit2_ewk_intercept_request_response_body_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_body_set_n1",utc_webkit2_ewk_intercept_request_response_body_set_n1,utc_webkit2_ewk_intercept_request_response_body_set_func_startup,utc_webkit2_ewk_intercept_request_response_body_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_add_p",utc_webkit2_ewk_intercept_request_response_header_add_p,utc_webkit2_ewk_intercept_request_response_header_add_func_startup,utc_webkit2_ewk_intercept_request_response_header_add_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_add_n",utc_webkit2_ewk_intercept_request_response_header_add_n,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_startup,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_add_n1",utc_webkit2_ewk_intercept_request_response_header_add_n1,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_startup,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_add_n2",utc_webkit2_ewk_intercept_request_response_header_add_n2,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_startup,utc_webkit2_ewk_intercept_request_response_header_add_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_map_add_p",utc_webkit2_ewk_intercept_request_response_header_map_add_p,utc_webkit2_ewk_intercept_request_response_header_map_add_func_startup,utc_webkit2_ewk_intercept_request_response_header_map_add_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_map_add_n",utc_webkit2_ewk_intercept_request_response_header_map_add_n,utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_startup,utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_header_map_add_n1",utc_webkit2_ewk_intercept_request_response_header_map_add_n1,utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_startup,utc_webkit2_ewk_intercept_request_response_header_map_add_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_set_p",utc_webkit2_ewk_intercept_request_response_set_p,utc_webkit2_ewk_intercept_request_response_set_func_startup,utc_webkit2_ewk_intercept_request_response_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_set_n",utc_webkit2_ewk_intercept_request_response_set_n,utc_webkit2_ewk_intercept_request_response_set_func_startup,utc_webkit2_ewk_intercept_request_response_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_set_n1",utc_webkit2_ewk_intercept_request_response_set_n1,utc_webkit2_ewk_intercept_request_response_set_func_startup,utc_webkit2_ewk_intercept_request_response_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_set_n2",utc_webkit2_ewk_intercept_request_response_set_n2,utc_webkit2_ewk_intercept_request_response_set_func_startup,utc_webkit2_ewk_intercept_request_response_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_status_set_p",utc_webkit2_ewk_intercept_request_response_status_set_p,utc_webkit2_ewk_intercept_request_response_status_set_func_startup,utc_webkit2_ewk_intercept_request_response_status_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_status_set_p1",utc_webkit2_ewk_intercept_request_response_status_set_p1,utc_webkit2_ewk_intercept_request_response_status_set_func_startup,utc_webkit2_ewk_intercept_request_response_status_set_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_status_set_n",utc_webkit2_ewk_intercept_request_response_status_set_n,utc_webkit2_ewk_intercept_request_response_status_set_func_neg_startup,utc_webkit2_ewk_intercept_request_response_status_set_func_neg_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_write_chunk_p",utc_webkit2_ewk_intercept_request_response_write_chunk_p,utc_webkit2_ewk_intercept_request_response_write_chunk_func_startup,utc_webkit2_ewk_intercept_request_response_write_chunk_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_write_chunk_n",utc_webkit2_ewk_intercept_request_response_write_chunk_n,utc_webkit2_ewk_intercept_request_response_write_chunk_func_startup,utc_webkit2_ewk_intercept_request_response_write_chunk_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_response_write_chunk_n1",utc_webkit2_ewk_intercept_request_response_write_chunk_n1,utc_webkit2_ewk_intercept_request_response_write_chunk_func_startup,utc_webkit2_ewk_intercept_request_response_write_chunk_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_url_get_p",utc_webkit2_ewk_intercept_request_url_get_p,utc_webkit2_ewk_intercept_request_url_get_func_startup,utc_webkit2_ewk_intercept_request_url_get_func_cleanup},
	{"utc_webkit2_ewk_intercept_request_url_get_n",utc_webkit2_ewk_intercept_request_url_get_n,utc_webkit2_ewk_intercept_request_url_get_func_startup,utc_webkit2_ewk_intercept_request_url_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_background_color_get_p",utc_webkit2_ewk_manifest_background_color_get_p,utc_webkit2_ewk_manifest_background_color_get_func_startup,utc_webkit2_ewk_manifest_background_color_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_background_color_get_n",utc_webkit2_ewk_manifest_background_color_get_n,utc_webkit2_ewk_manifest_background_color_get_func_startup,utc_webkit2_ewk_manifest_background_color_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_count_get_p",utc_webkit2_ewk_manifest_icons_count_get_p,utc_webkit2_ewk_manifest_icons_count_get_func_startup,utc_webkit2_ewk_manifest_icons_count_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_count_get_n",utc_webkit2_ewk_manifest_icons_count_get_n,utc_webkit2_ewk_manifest_icons_count_get_func_startup,utc_webkit2_ewk_manifest_icons_count_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_height_get_p",utc_webkit2_ewk_manifest_icons_height_get_p,utc_webkit2_ewk_manifest_icons_height_get_func_startup,utc_webkit2_ewk_manifest_icons_height_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_height_get_n",utc_webkit2_ewk_manifest_icons_height_get_n,utc_webkit2_ewk_manifest_icons_height_get_func_startup,utc_webkit2_ewk_manifest_icons_height_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_sizes_count_get_p",utc_webkit2_ewk_manifest_icons_sizes_count_get_p,utc_webkit2_ewk_manifest_icons_sizes_count_get_func_startup,utc_webkit2_ewk_manifest_icons_sizes_count_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_sizes_count_get_n",utc_webkit2_ewk_manifest_icons_sizes_count_get_n,utc_webkit2_ewk_manifest_icons_sizes_count_get_func_startup,utc_webkit2_ewk_manifest_icons_sizes_count_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_src_get_p",utc_webkit2_ewk_manifest_icons_src_get_p,utc_webkit2_ewk_manifest_icons_src_get_func_startup,utc_webkit2_ewk_manifest_icons_src_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_src_get_n",utc_webkit2_ewk_manifest_icons_src_get_n,utc_webkit2_ewk_manifest_icons_src_get_func_startup,utc_webkit2_ewk_manifest_icons_src_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_type_get_p",utc_webkit2_ewk_manifest_icons_type_get_p,utc_webkit2_ewk_manifest_icons_type_get_func_startup,utc_webkit2_ewk_manifest_icons_type_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_type_get_n",utc_webkit2_ewk_manifest_icons_type_get_n,utc_webkit2_ewk_manifest_icons_type_get_func_startup,utc_webkit2_ewk_manifest_icons_type_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_width_get_p",utc_webkit2_ewk_manifest_icons_width_get_p,utc_webkit2_ewk_manifest_icons_width_get_func_startup,utc_webkit2_ewk_manifest_icons_width_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_icons_width_get_n",utc_webkit2_ewk_manifest_icons_width_get_n,utc_webkit2_ewk_manifest_icons_width_get_func_startup,utc_webkit2_ewk_manifest_icons_width_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_name_get_p",utc_webkit2_ewk_manifest_name_get_p,utc_webkit2_ewk_manifest_name_get_func_startup,utc_webkit2_ewk_manifest_name_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_name_get_n",utc_webkit2_ewk_manifest_name_get_n,utc_webkit2_ewk_manifest_name_get_func_startup,utc_webkit2_ewk_manifest_name_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_orientation_type_get_p",utc_webkit2_ewk_manifest_orientation_type_get_p,utc_webkit2_ewk_manifest_orientation_type_get_func_startup,utc_webkit2_ewk_manifest_orientation_type_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_orientation_type_get_n",utc_webkit2_ewk_manifest_orientation_type_get_n,utc_webkit2_ewk_manifest_orientation_type_get_func_startup,utc_webkit2_ewk_manifest_orientation_type_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_short_name_get_p",utc_webkit2_ewk_manifest_short_name_get_p,utc_webkit2_ewk_manifest_short_name_get_func_startup,utc_webkit2_ewk_manifest_short_name_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_short_name_get_n",utc_webkit2_ewk_manifest_short_name_get_n,utc_webkit2_ewk_manifest_short_name_get_func_startup,utc_webkit2_ewk_manifest_short_name_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_start_url_get_p",utc_webkit2_ewk_manifest_start_url_get_p,utc_webkit2_ewk_manifest_start_url_get_func_startup,utc_webkit2_ewk_manifest_start_url_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_start_url_get_n",utc_webkit2_ewk_manifest_start_url_get_n,utc_webkit2_ewk_manifest_start_url_get_func_startup,utc_webkit2_ewk_manifest_start_url_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_theme_color_get_p",utc_webkit2_ewk_manifest_theme_color_get_p,utc_webkit2_ewk_manifest_theme_color_get_func_startup,utc_webkit2_ewk_manifest_theme_color_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_theme_color_get_n",utc_webkit2_ewk_manifest_theme_color_get_n,utc_webkit2_ewk_manifest_theme_color_get_func_startup,utc_webkit2_ewk_manifest_theme_color_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_web_display_mode_get_p",utc_webkit2_ewk_manifest_web_display_mode_get_p,utc_webkit2_ewk_manifest_web_display_mode_get_func_startup,utc_webkit2_ewk_manifest_web_display_mode_get_func_cleanup},
	{"utc_webkit2_ewk_manifest_web_display_mode_get_n",utc_webkit2_ewk_manifest_web_display_mode_get_n,utc_webkit2_ewk_manifest_web_display_mode_get_func_startup,utc_webkit2_ewk_manifest_web_display_mode_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_cookie_get_p",utc_webkit2_ewk_policy_decision_cookie_get_p,utc_webkit2_ewk_policy_decision_cookie_get_func_startup,utc_webkit2_ewk_policy_decision_cookie_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_cookie_get_n",utc_webkit2_ewk_policy_decision_cookie_get_n,utc_webkit2_ewk_policy_decision_cookie_get_func_startup,utc_webkit2_ewk_policy_decision_cookie_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_host_get_p",utc_webkit2_ewk_policy_decision_host_get_p,utc_webkit2_ewk_policy_decision_host_get_func_startup,utc_webkit2_ewk_policy_decision_host_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_host_get_n",utc_webkit2_ewk_policy_decision_host_get_n,utc_webkit2_ewk_policy_decision_host_get_func_startup,utc_webkit2_ewk_policy_decision_host_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_http_method_get_p",utc_webkit2_ewk_policy_decision_http_method_get_p,utc_webkit2_ewk_policy_decision_http_method_get_func_startup,utc_webkit2_ewk_policy_decision_http_method_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_http_method_get_n",utc_webkit2_ewk_policy_decision_http_method_get_n,utc_webkit2_ewk_policy_decision_http_method_get_func_startup,utc_webkit2_ewk_policy_decision_http_method_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_ignore_p",utc_webkit2_ewk_policy_decision_ignore_p,utc_webkit2_ewk_policy_decision_ignore_func_startup,utc_webkit2_ewk_policy_decision_ignore_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_ignore_n",utc_webkit2_ewk_policy_decision_ignore_n,utc_webkit2_ewk_policy_decision_ignore_func_startup,utc_webkit2_ewk_policy_decision_ignore_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_navigation_type_get_p",utc_webkit2_ewk_policy_decision_navigation_type_get_p,utc_webkit2_ewk_policy_decision_navigation_type_get_func_startup,utc_webkit2_ewk_policy_decision_navigation_type_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_navigation_type_get_n",utc_webkit2_ewk_policy_decision_navigation_type_get_n,utc_webkit2_ewk_policy_decision_navigation_type_get_func_startup,utc_webkit2_ewk_policy_decision_navigation_type_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_headers_get_p",utc_webkit2_ewk_policy_decision_response_headers_get_p,utc_webkit2_ewk_policy_decision_response_headers_get_func_startup,utc_webkit2_ewk_policy_decision_response_headers_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_headers_get_n",utc_webkit2_ewk_policy_decision_response_headers_get_n,utc_webkit2_ewk_policy_decision_response_headers_get_func_startup,utc_webkit2_ewk_policy_decision_response_headers_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_mime_get_p",utc_webkit2_ewk_policy_decision_response_mime_get_p,utc_webkit2_ewk_policy_decision_response_mime_get_func_startup,utc_webkit2_ewk_policy_decision_response_mime_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_mime_get_n",utc_webkit2_ewk_policy_decision_response_mime_get_n,utc_webkit2_ewk_policy_decision_response_mime_get_func_startup,utc_webkit2_ewk_policy_decision_response_mime_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_status_code_get_p",utc_webkit2_ewk_policy_decision_response_status_code_get_p,utc_webkit2_ewk_policy_decision_response_status_code_get_func_startup,utc_webkit2_ewk_policy_decision_response_status_code_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_response_status_code_get_n",utc_webkit2_ewk_policy_decision_response_status_code_get_n,utc_webkit2_ewk_policy_decision_response_status_code_get_func_startup,utc_webkit2_ewk_policy_decision_response_status_code_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_scheme_get_p",utc_webkit2_ewk_policy_decision_scheme_get_p,utc_webkit2_ewk_policy_decision_scheme_get_func_startup,utc_webkit2_ewk_policy_decision_scheme_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_scheme_get_n",utc_webkit2_ewk_policy_decision_scheme_get_n,utc_webkit2_ewk_policy_decision_scheme_get_func_startup,utc_webkit2_ewk_policy_decision_scheme_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_type_get_p",utc_webkit2_ewk_policy_decision_type_get_p,utc_webkit2_ewk_policy_decision_type_get_func_startup,utc_webkit2_ewk_policy_decision_type_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_type_get_n",utc_webkit2_ewk_policy_decision_type_get_n,utc_webkit2_ewk_policy_decision_type_get_func_startup,utc_webkit2_ewk_policy_decision_type_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_url_get_p",utc_webkit2_ewk_policy_decision_url_get_p,utc_webkit2_ewk_policy_decision_url_get_func_startup,utc_webkit2_ewk_policy_decision_url_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_url_get_n",utc_webkit2_ewk_policy_decision_url_get_n,utc_webkit2_ewk_policy_decision_url_get_func_startup,utc_webkit2_ewk_policy_decision_url_get_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_use_p",utc_webkit2_ewk_policy_decision_use_p,utc_webkit2_ewk_policy_decision_use_func_startup,utc_webkit2_ewk_policy_decision_use_func_cleanup},
	{"utc_webkit2_ewk_policy_decision_use_n",utc_webkit2_ewk_policy_decision_use_n,utc_webkit2_ewk_policy_decision_use_func_startup,utc_webkit2_ewk_policy_decision_use_func_cleanup},
	{"utc_webkit2_ewk_security_origin_host_get_n",utc_webkit2_ewk_security_origin_host_get_n,utc_webkit2_ewk_security_origin_host_get_func_startup,utc_webkit2_ewk_security_origin_host_get_func_cleanup},
	{"utc_webkit2_ewk_security_origin_protocol_get_n",utc_webkit2_ewk_security_origin_protocol_get_n,utc_webkit2_ewk_security_origin_protocol_get_func_startup,utc_webkit2_ewk_security_origin_protocol_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_font_size_get_p",utc_webkit2_ewk_settings_default_font_size_get_p,utc_webkit2_ewk_settings_default_font_size_get_func_startup,utc_webkit2_ewk_settings_default_font_size_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_font_size_get_p1",utc_webkit2_ewk_settings_default_font_size_get_p1,utc_webkit2_ewk_settings_default_font_size_get_func_startup,utc_webkit2_ewk_settings_default_font_size_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_font_size_get_n",utc_webkit2_ewk_settings_default_font_size_get_n,utc_webkit2_ewk_settings_default_font_size_get_func_startup,utc_webkit2_ewk_settings_default_font_size_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_font_size_set_p",utc_webkit2_ewk_settings_default_font_size_set_p,utc_webkit2_ewk_settings_default_font_size_set_func_startup,utc_webkit2_ewk_settings_default_font_size_set_func_cleanup},
	{"utc_webkit2_ewk_settings_default_font_size_set_n",utc_webkit2_ewk_settings_default_font_size_set_n,utc_webkit2_ewk_settings_default_font_size_set_func_startup,utc_webkit2_ewk_settings_default_font_size_set_func_cleanup},
	{"utc_webkit2_ewk_settings_default_text_encoding_name_get_p",utc_webkit2_ewk_settings_default_text_encoding_name_get_p,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_startup,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_text_encoding_name_get_p1",utc_webkit2_ewk_settings_default_text_encoding_name_get_p1,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_startup,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_text_encoding_name_get_n",utc_webkit2_ewk_settings_default_text_encoding_name_get_n,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_startup,utc_webkit2_ewk_settings_default_text_encoding_name_get_func_cleanup},
	{"utc_webkit2_ewk_settings_default_text_encoding_name_set_p",utc_webkit2_ewk_settings_default_text_encoding_name_set_p,utc_webkit2_ewk_settings_default_text_encoding_name_set_func_startup,utc_webkit2_ewk_settings_default_text_encoding_name_set_func_cleanup},
	{"utc_webkit2_ewk_settings_default_text_encoding_name_set_n",utc_webkit2_ewk_settings_default_text_encoding_name_set_n,utc_webkit2_ewk_settings_default_text_encoding_name_set_func_startup,utc_webkit2_ewk_settings_default_text_encoding_name_set_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_get_p",utc_webkit2_ewk_settings_javascript_enabled_get_p,utc_webkit2_ewk_settings_javascript_enabled_get_func_startup,utc_webkit2_ewk_settings_javascript_enabled_get_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_get_p1",utc_webkit2_ewk_settings_javascript_enabled_get_p1,utc_webkit2_ewk_settings_javascript_enabled_get_func_startup,utc_webkit2_ewk_settings_javascript_enabled_get_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_get_n",utc_webkit2_ewk_settings_javascript_enabled_get_n,utc_webkit2_ewk_settings_javascript_enabled_get_func_startup,utc_webkit2_ewk_settings_javascript_enabled_get_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_set_p",utc_webkit2_ewk_settings_javascript_enabled_set_p,utc_webkit2_ewk_settings_javascript_enabled_set_func_startup,utc_webkit2_ewk_settings_javascript_enabled_set_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_set_p1",utc_webkit2_ewk_settings_javascript_enabled_set_p1,utc_webkit2_ewk_settings_javascript_enabled_set_func_startup,utc_webkit2_ewk_settings_javascript_enabled_set_func_cleanup},
	{"utc_webkit2_ewk_settings_javascript_enabled_set_n",utc_webkit2_ewk_settings_javascript_enabled_set_n,utc_webkit2_ewk_settings_javascript_enabled_set_func_startup,utc_webkit2_ewk_settings_javascript_enabled_set_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_get_p",utc_webkit2_ewk_settings_loads_images_automatically_get_p,utc_webkit2_ewk_settings_loads_images_automatically_get_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_get_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_get_p1",utc_webkit2_ewk_settings_loads_images_automatically_get_p1,utc_webkit2_ewk_settings_loads_images_automatically_get_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_get_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_get_n",utc_webkit2_ewk_settings_loads_images_automatically_get_n,utc_webkit2_ewk_settings_loads_images_automatically_get_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_get_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_set_p",utc_webkit2_ewk_settings_loads_images_automatically_set_p,utc_webkit2_ewk_settings_loads_images_automatically_set_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_set_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_set_p1",utc_webkit2_ewk_settings_loads_images_automatically_set_p1,utc_webkit2_ewk_settings_loads_images_automatically_set_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_set_func_cleanup},
	{"utc_webkit2_ewk_settings_loads_images_automatically_set_n",utc_webkit2_ewk_settings_loads_images_automatically_set_n,utc_webkit2_ewk_settings_loads_images_automatically_set_func_startup,utc_webkit2_ewk_settings_loads_images_automatically_set_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_get_p",utc_webkit2_ewk_settings_scripts_can_open_windows_get_p,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_get_p1",utc_webkit2_ewk_settings_scripts_can_open_windows_get_p1,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_get_n",utc_webkit2_ewk_settings_scripts_can_open_windows_get_n,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_get_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_set_p",utc_webkit2_ewk_settings_scripts_can_open_windows_set_p,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_set_p1",utc_webkit2_ewk_settings_scripts_can_open_windows_set_p1,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_cleanup},
	{"utc_webkit2_ewk_settings_scripts_can_open_windows_set_n",utc_webkit2_ewk_settings_scripts_can_open_windows_set_n,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_startup,utc_webkit2_ewk_settings_scripts_can_open_windows_set_func_cleanup},
	{"utc_webkit2_ewk_shutdown_p",utc_webkit2_ewk_shutdown_p,utc_webkit2_ewk_shutdown_func_startup,utc_webkit2_ewk_shutdown_func_cleanup},
	{"utc_webkit2_ewk_shutdown_n",utc_webkit2_ewk_shutdown_n,utc_webkit2_ewk_shutdown_func_startup,utc_webkit2_ewk_shutdown_func_cleanup},
	{"utc_webkit2_ewk_view_add_p",utc_webkit2_ewk_view_add_p,utc_webkit2_ewk_view_add_startup,utc_webkit2_ewk_view_add_cleanup},
	{"utc_webkit2_ewk_view_add_n",utc_webkit2_ewk_view_add_n,utc_webkit2_ewk_view_add_startup,utc_webkit2_ewk_view_add_cleanup},
	{"utc_webkit2_ewk_view_add_in_incognito_mode_p",utc_webkit2_ewk_view_add_in_incognito_mode_p,utc_webkit2_ewk_view_add_in_incognito_mode_startup,utc_webkit2_ewk_view_add_in_incognito_mode_cleanup},
	{"utc_webkit2_ewk_view_add_in_incognito_mode_n",utc_webkit2_ewk_view_add_in_incognito_mode_n,utc_webkit2_ewk_view_add_in_incognito_mode_startup,utc_webkit2_ewk_view_add_in_incognito_mode_cleanup},
	{"utc_webkit2_ewk_view_back_forward_list_clear_p",utc_webkit2_ewk_view_back_forward_list_clear_p,utc_webkit2_ewk_view_back_forward_list_clear_func_startup,utc_webkit2_ewk_view_back_forward_list_clear_func_cleanup},
	{"utc_webkit2_ewk_view_back_forward_list_clear_n",utc_webkit2_ewk_view_back_forward_list_clear_n,utc_webkit2_ewk_view_back_forward_list_clear_func_startup,utc_webkit2_ewk_view_back_forward_list_clear_func_cleanup},
	{"utc_webkit2_ewk_view_back_forward_list_get_p",utc_webkit2_ewk_view_back_forward_list_get_p,utc_webkit2_ewk_view_back_forward_list_get_func_startup,utc_webkit2_ewk_view_back_forward_list_get_func_cleanup},
	{"utc_webkit2_ewk_view_back_forward_list_get_n",utc_webkit2_ewk_view_back_forward_list_get_n,utc_webkit2_ewk_view_back_forward_list_get_func_startup,utc_webkit2_ewk_view_back_forward_list_get_func_cleanup},
	{"utc_webkit2_ewk_view_back_p",utc_webkit2_ewk_view_back_p,utc_webkit2_ewk_view_back_startup,utc_webkit2_ewk_view_back_cleanup},
	{"utc_webkit2_ewk_view_back_n",utc_webkit2_ewk_view_back_n,utc_webkit2_ewk_view_back_startup,utc_webkit2_ewk_view_back_cleanup},
	{"utc_webkit2_ewk_view_back_possible_p1",utc_webkit2_ewk_view_back_possible_p1,utc_webkit2_ewk_view_back_possible_startup,utc_webkit2_ewk_view_back_possible_cleanup},
	{"utc_webkit2_ewk_view_back_possible_p2",utc_webkit2_ewk_view_back_possible_p2,utc_webkit2_ewk_view_back_possible_startup,utc_webkit2_ewk_view_back_possible_cleanup},
	{"utc_webkit2_ewk_view_back_possible_p3",utc_webkit2_ewk_view_back_possible_p3,utc_webkit2_ewk_view_back_possible_startup,utc_webkit2_ewk_view_back_possible_cleanup},
	{"utc_webkit2_ewk_view_back_possible_n",utc_webkit2_ewk_view_back_possible_n,utc_webkit2_ewk_view_back_possible_startup,utc_webkit2_ewk_view_back_possible_cleanup},
	{"utc_webkit2_ewk_view_contents_size_get_p",utc_webkit2_ewk_view_contents_size_get_p,utc_webkit2_ewk_view_contents_size_get_startup,utc_webkit2_ewk_view_contents_size_get_cleanup},
	{"utc_webkit2_ewk_view_contents_size_get_n",utc_webkit2_ewk_view_contents_size_get_n,utc_webkit2_ewk_view_contents_size_get_startup,utc_webkit2_ewk_view_contents_size_get_cleanup},
	{"utc_webkit2_ewk_view_context_get_p",utc_webkit2_ewk_view_context_get_p,utc_webkit2_ewk_view_context_get_func_startup,utc_webkit2_ewk_view_context_get_func_cleanup},
	{"utc_webkit2_ewk_view_context_get_n",utc_webkit2_ewk_view_context_get_n,utc_webkit2_ewk_view_context_get_func_startup,utc_webkit2_ewk_view_context_get_func_cleanup},
	{"utc_webkit2_ewk_view_evaluate_javascript_p",utc_webkit2_ewk_view_evaluate_javascript_p,utc_webkit2_ewk_view_evaluate_javascript_startup,utc_webkit2_ewk_view_evaluate_javascript_cleanup},
	{"utc_webkit2_ewk_view_evaluate_javascript_n",utc_webkit2_ewk_view_evaluate_javascript_n,utc_webkit2_ewk_view_evaluate_javascript_startup,utc_webkit2_ewk_view_evaluate_javascript_cleanup},
	{"utc_webkit2_ewk_view_focus_get_p",utc_webkit2_ewk_view_focus_get_p,utc_webkit2_ewk_view_focus_get_startup,utc_webkit2_ewk_view_focus_get_cleanup},
	{"utc_webkit2_ewk_view_focus_get_p1",utc_webkit2_ewk_view_focus_get_p1,utc_webkit2_ewk_view_focus_get_startup,utc_webkit2_ewk_view_focus_get_cleanup},
	{"utc_webkit2_ewk_view_focus_get_n",utc_webkit2_ewk_view_focus_get_n,utc_webkit2_ewk_view_focus_get_startup,utc_webkit2_ewk_view_focus_get_cleanup},
	{"utc_webkit2_ewk_view_focus_set_p",utc_webkit2_ewk_view_focus_set_p,utc_webkit2_ewk_view_focus_set_startup,utc_webkit2_ewk_view_focus_set_cleanup},
	{"utc_webkit2_ewk_view_focus_set_p1",utc_webkit2_ewk_view_focus_set_p1,utc_webkit2_ewk_view_focus_set_startup,utc_webkit2_ewk_view_focus_set_cleanup},
	{"utc_webkit2_ewk_view_focus_set_n",utc_webkit2_ewk_view_focus_set_n,utc_webkit2_ewk_view_focus_set_startup,utc_webkit2_ewk_view_focus_set_cleanup},
	{"utc_webkit2_ewk_view_forward_p",utc_webkit2_ewk_view_forward_p,utc_webkit2_ewk_view_forward_startup,utc_webkit2_ewk_view_forward_cleanup},
	{"utc_webkit2_ewk_view_forward_n",utc_webkit2_ewk_view_forward_n,utc_webkit2_ewk_view_forward_startup,utc_webkit2_ewk_view_forward_cleanup},
	{"utc_webkit2_ewk_view_forward_possible_p",utc_webkit2_ewk_view_forward_possible_p,utc_webkit2_ewk_view_forward_possible_func_startup,utc_webkit2_ewk_view_forward_possible_func_cleanup},
	{"utc_webkit2_ewk_view_forward_possible_p1",utc_webkit2_ewk_view_forward_possible_p1,utc_webkit2_ewk_view_forward_possible_func_startup,utc_webkit2_ewk_view_forward_possible_func_cleanup},
	{"utc_webkit2_ewk_view_forward_possible_p2",utc_webkit2_ewk_view_forward_possible_p2,utc_webkit2_ewk_view_forward_possible_func_startup,utc_webkit2_ewk_view_forward_possible_func_cleanup},
	{"utc_webkit2_ewk_view_forward_possible_n",utc_webkit2_ewk_view_forward_possible_n,utc_webkit2_ewk_view_forward_possible_func_startup,utc_webkit2_ewk_view_forward_possible_func_cleanup},
	{"utc_webkit2_ewk_view_fullscreen_exit_p",utc_webkit2_ewk_view_fullscreen_exit_p,utc_webkit2_ewk_view_fullscreen_exit_func_startup,utc_webkit2_ewk_view_fullscreen_exit_func_cleanup},
	{"utc_webkit2_ewk_view_fullscreen_exit_n",utc_webkit2_ewk_view_fullscreen_exit_n,utc_webkit2_ewk_view_fullscreen_exit_func_startup,utc_webkit2_ewk_view_fullscreen_exit_func_cleanup},
	{"utc_webkit2_ewk_view_html_string_load_p",utc_webkit2_ewk_view_html_string_load_p,utc_webkit2_ewk_view_html_string_load_func_startup,utc_webkit2_ewk_view_html_string_load_func_cleanup},
	{"utc_webkit2_ewk_view_html_string_load_n",utc_webkit2_ewk_view_html_string_load_n,utc_webkit2_ewk_view_html_string_load_func_startup,utc_webkit2_ewk_view_html_string_load_func_cleanup},
	{"utc_webkit2_ewk_view_javascript_message_handler_add_p",utc_webkit2_ewk_view_javascript_message_handler_add_p,utc_webkit2_ewk_view_javascript_message_handler_add_startup,utc_webkit2_ewk_view_javascript_message_handler_add_cleanup},
	{"utc_webkit2_ewk_view_javascript_message_handler_add_n",utc_webkit2_ewk_view_javascript_message_handler_add_n,utc_webkit2_ewk_view_javascript_message_handler_add_startup,utc_webkit2_ewk_view_javascript_message_handler_add_cleanup},
	{"utc_webkit2_ewk_view_load_progress_get_p",utc_webkit2_ewk_view_load_progress_get_p,utc_webkit2_ewk_view_load_progress_get_func_startup,utc_webkit2_ewk_view_load_progress_get_func_cleanup},
	{"utc_webkit2_ewk_view_load_progress_get_p1",utc_webkit2_ewk_view_load_progress_get_p1,utc_webkit2_ewk_view_load_progress_get_func_startup,utc_webkit2_ewk_view_load_progress_get_func_cleanup},
	{"utc_webkit2_ewk_view_load_progress_get_n",utc_webkit2_ewk_view_load_progress_get_n,utc_webkit2_ewk_view_load_progress_get_func_startup,utc_webkit2_ewk_view_load_progress_get_func_cleanup},
	{"utc_webkit2_ewk_view_orientation_send_p",utc_webkit2_ewk_view_orientation_send_p,utc_webkit2_ewk_view_orientation_send_func_startup,utc_webkit2_ewk_view_orientation_send_func_cleanup},
	{"utc_webkit2_ewk_view_orientation_send_n",utc_webkit2_ewk_view_orientation_send_n,utc_webkit2_ewk_view_orientation_send_func_startup,utc_webkit2_ewk_view_orientation_send_func_cleanup},
        {"utc_webkit2_ewk_view_original_url_get_p",utc_webkit2_ewk_view_original_url_get_p,utc_webkit2_ewk_view_original_url_get_startup,utc_webkit2_ewk_view_original_url_get_cleanup},
        {"utc_webkit2_ewk_view_original_url_get_n",utc_webkit2_ewk_view_original_url_get_n,utc_webkit2_ewk_view_original_url_get_startup,utc_webkit2_ewk_view_original_url_get_cleanup},
	{"utc_webkit2_ewk_view_reload_p",utc_webkit2_ewk_view_reload_p,utc_webkit2_ewk_view_reload_startup,utc_webkit2_ewk_view_reload_cleanup},
	{"utc_webkit2_ewk_view_reload_n",utc_webkit2_ewk_view_reload_n,utc_webkit2_ewk_view_reload_startup,utc_webkit2_ewk_view_reload_cleanup},
	{"utc_webkit2_ewk_view_request_manifest_p",utc_webkit2_ewk_view_request_manifest_p,utc_webkit2_ewk_view_request_manifest_startup,utc_webkit2_ewk_view_request_manifest_cleanup},
	{"utc_webkit2_ewk_view_request_manifest_n",utc_webkit2_ewk_view_request_manifest_n,utc_webkit2_ewk_view_request_manifest_startup,utc_webkit2_ewk_view_request_manifest_cleanup},
	{"utc_webkit2_ewk_view_resume_p",utc_webkit2_ewk_view_resume_p,utc_webkit2_ewk_view_resume_startup,utc_webkit2_ewk_view_resume_cleanup},
	{"utc_webkit2_ewk_view_resume_n",utc_webkit2_ewk_view_resume_n,utc_webkit2_ewk_view_resume_startup,utc_webkit2_ewk_view_resume_cleanup},
	{"utc_webkit2_ewk_view_scale_get_p",utc_webkit2_ewk_view_scale_get_p,utc_webkit2_ewk_view_scale_get_startup,utc_webkit2_ewk_view_scale_get_cleanup},
	{"utc_webkit2_ewk_view_scale_get_n",utc_webkit2_ewk_view_scale_get_n,utc_webkit2_ewk_view_scale_get_startup,utc_webkit2_ewk_view_scale_get_cleanup},
	{"utc_webkit2_ewk_view_scale_set_p",utc_webkit2_ewk_view_scale_set_p,utc_webkit2_ewk_view_scale_set_startup,utc_webkit2_ewk_view_scale_set_cleanup},
	{"utc_webkit2_ewk_view_scale_set_n",utc_webkit2_ewk_view_scale_set_n,utc_webkit2_ewk_view_scale_set_startup,utc_webkit2_ewk_view_scale_set_cleanup},
	{"utc_webkit2_ewk_view_script_execute_p",utc_webkit2_ewk_view_script_execute_p,utc_webkit2_ewk_view_script_execute_func_startup,utc_webkit2_ewk_view_script_execute_func_cleanup},
	{"utc_webkit2_ewk_view_script_execute_n",utc_webkit2_ewk_view_script_execute_n,utc_webkit2_ewk_view_script_execute_func_startup,utc_webkit2_ewk_view_script_execute_func_cleanup},
	{"utc_webkit2_ewk_view_script_execute_n1",utc_webkit2_ewk_view_script_execute_n1,utc_webkit2_ewk_view_script_execute_func_startup,utc_webkit2_ewk_view_script_execute_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_by_p",utc_webkit2_ewk_view_scroll_by_p,utc_webkit2_ewk_view_scroll_by_func_startup,utc_webkit2_ewk_view_scroll_by_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_by_p1",utc_webkit2_ewk_view_scroll_by_p1,utc_webkit2_ewk_view_scroll_by_func_startup,utc_webkit2_ewk_view_scroll_by_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_by_p2",utc_webkit2_ewk_view_scroll_by_p2,utc_webkit2_ewk_view_scroll_by_func_startup,utc_webkit2_ewk_view_scroll_by_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_by_n",utc_webkit2_ewk_view_scroll_by_n,utc_webkit2_ewk_view_scroll_by_func_startup,utc_webkit2_ewk_view_scroll_by_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_pos_get_p",utc_webkit2_ewk_view_scroll_pos_get_p,utc_webkit2_ewk_view_scroll_pos_get_func_startup,utc_webkit2_ewk_view_scroll_pos_get_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_pos_get_p1",utc_webkit2_ewk_view_scroll_pos_get_p1,utc_webkit2_ewk_view_scroll_pos_get_func_startup,utc_webkit2_ewk_view_scroll_pos_get_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_pos_get_n",utc_webkit2_ewk_view_scroll_pos_get_n,utc_webkit2_ewk_view_scroll_pos_get_func_startup,utc_webkit2_ewk_view_scroll_pos_get_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_set_p",utc_webkit2_ewk_view_scroll_set_p,utc_webkit2_ewk_view_scroll_set_func_startup,utc_webkit2_ewk_view_scroll_set_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_set_p1",utc_webkit2_ewk_view_scroll_set_p1,utc_webkit2_ewk_view_scroll_set_func_startup,utc_webkit2_ewk_view_scroll_set_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_set_p2",utc_webkit2_ewk_view_scroll_set_p2,utc_webkit2_ewk_view_scroll_set_func_startup,utc_webkit2_ewk_view_scroll_set_func_cleanup},
	{"utc_webkit2_ewk_view_scroll_set_n",utc_webkit2_ewk_view_scroll_set_n,utc_webkit2_ewk_view_scroll_set_func_startup,utc_webkit2_ewk_view_scroll_set_func_cleanup},
	{"utc_webkit2_ewk_view_settings_get_p",utc_webkit2_ewk_view_settings_get_p,utc_webkit2_ewk_view_settings_get_func_startup,utc_webkit2_ewk_view_settings_get_func_cleanup},
	{"utc_webkit2_ewk_view_settings_get_n",utc_webkit2_ewk_view_settings_get_n,utc_webkit2_ewk_view_settings_get_func_startup,utc_webkit2_ewk_view_settings_get_func_cleanup},
	{"utc_webkit2_ewk_view_stop_p",utc_webkit2_ewk_view_stop_p,utc_webkit2_ewk_view_stop_startup,utc_webkit2_ewk_view_stop_cleanup},
	{"utc_webkit2_ewk_view_stop_n",utc_webkit2_ewk_view_stop_n,utc_webkit2_ewk_view_stop_startup,utc_webkit2_ewk_view_stop_cleanup},
	{"utc_webkit2_ewk_view_suspend_p",utc_webkit2_ewk_view_suspend_p,utc_webkit2_ewk_view_suspend_startup,utc_webkit2_ewk_view_suspend_cleanup},
	{"utc_webkit2_ewk_view_suspend_n",utc_webkit2_ewk_view_suspend_n,utc_webkit2_ewk_view_suspend_startup,utc_webkit2_ewk_view_suspend_cleanup},
	{"utc_webkit2_ewk_view_text_find_p",utc_webkit2_ewk_view_text_find_p,utc_webkit2_ewk_view_text_find_func_startup,utc_webkit2_ewk_view_text_find_func_cleanup},
	{"utc_webkit2_ewk_view_text_find_n",utc_webkit2_ewk_view_text_find_n,utc_webkit2_ewk_view_text_find_func_startup,utc_webkit2_ewk_view_text_find_func_cleanup},
	{"utc_webkit2_ewk_view_title_get_p",utc_webkit2_ewk_view_title_get_p,utc_webkit2_ewk_view_title_get_startup,utc_webkit2_ewk_view_title_get_cleanup},
	{"utc_webkit2_ewk_view_title_get_n",utc_webkit2_ewk_view_title_get_n,utc_webkit2_ewk_view_title_get_startup,utc_webkit2_ewk_view_title_get_cleanup},
	{"utc_webkit2_ewk_view_url_get_p",utc_webkit2_ewk_view_url_get_p,utc_webkit2_ewk_view_url_get_startup,utc_webkit2_ewk_view_url_get_cleanup},
	{"utc_webkit2_ewk_view_url_get_n",utc_webkit2_ewk_view_url_get_n,utc_webkit2_ewk_view_url_get_startup,utc_webkit2_ewk_view_url_get_cleanup},
	{"utc_webkit2_ewk_view_url_request_set_p",utc_webkit2_ewk_view_url_request_set_p,utc_webkit2_ewk_view_url_request_set_func_startup,utc_webkit2_ewk_view_url_request_set_func_cleanup},
	{"utc_webkit2_ewk_view_url_request_set_n",utc_webkit2_ewk_view_url_request_set_n,utc_webkit2_ewk_view_url_request_set_func_startup,utc_webkit2_ewk_view_url_request_set_func_cleanup},
	{"utc_webkit2_ewk_view_url_request_set_n1",utc_webkit2_ewk_view_url_request_set_n1,utc_webkit2_ewk_view_url_request_set_func_startup,utc_webkit2_ewk_view_url_request_set_func_cleanup},
	{"utc_webkit2_ewk_view_url_request_set_n2",utc_webkit2_ewk_view_url_request_set_n2,utc_webkit2_ewk_view_url_request_set_func_startup,utc_webkit2_ewk_view_url_request_set_func_cleanup},
	{"utc_webkit2_ewk_view_url_set_p",utc_webkit2_ewk_view_url_set_p,utc_webkit2_ewk_view_url_set_func_startup,utc_webkit2_ewk_view_url_set_func_cleanup},
	{"utc_webkit2_ewk_view_url_set_n",utc_webkit2_ewk_view_url_set_n,utc_webkit2_ewk_view_url_set_func_startup,utc_webkit2_ewk_view_url_set_func_cleanup},
	{"utc_webkit2_ewk_view_user_agent_get_p",utc_webkit2_ewk_view_user_agent_get_p,utc_webkit2_ewk_view_user_agent_get_func_startup,utc_webkit2_ewk_view_user_agent_get_func_cleanup},
	{"utc_webkit2_ewk_view_user_agent_get_n",utc_webkit2_ewk_view_user_agent_get_n,utc_webkit2_ewk_view_user_agent_get_func_startup,utc_webkit2_ewk_view_user_agent_get_func_cleanup},
	{"utc_webkit2_ewk_view_user_agent_set_p",utc_webkit2_ewk_view_user_agent_set_p,utc_webkit2_ewk_view_user_agent_set_func_startup,utc_webkit2_ewk_view_user_agent_set_func_cleanup},
	{"utc_webkit2_ewk_view_user_agent_set_n",utc_webkit2_ewk_view_user_agent_set_n,utc_webkit2_ewk_view_user_agent_set_func_startup,utc_webkit2_ewk_view_user_agent_set_func_cleanup},
	{"utc_webkit2_ewk_view_visibility_set_p",utc_webkit2_ewk_view_visibility_set_p,utc_webkit2_ewk_view_visibility_set_func_startup,utc_webkit2_ewk_view_visibility_set_func_cleanup},
	{"utc_webkit2_ewk_view_visibility_set_n",utc_webkit2_ewk_view_visibility_set_n,utc_webkit2_ewk_view_visibility_set_func_startup,utc_webkit2_ewk_view_visibility_set_func_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WEBKIT2-NATIVE_H__
