//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_MEDIA-CONTROLLER-NATIVE_H__
#define __TCT_MEDIA-CONTROLLER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

// utc-media-controller-server.c
extern void utc_mc_server_startup(void);
extern void utc_mc_server_cleanup(void);

extern int utc_mc_server_create_p(void);
extern int utc_mc_server_create_n(void);
extern int utc_mc_server_destroy_p(void);
extern int utc_mc_server_destroy_n(void);
extern int utc_mc_server_set_playback_state_p(void);
extern int utc_mc_server_set_playback_state_n(void);
extern int utc_mc_server_set_playback_position_p(void);
extern int utc_mc_server_set_playback_position_n(void);
extern int utc_mc_server_set_playback_content_type_p(void);
extern int utc_mc_server_set_playback_content_type_n(void);
extern int utc_mc_server_set_content_age_rating_p(void);
extern int utc_mc_server_set_content_age_rating_n(void);
extern int utc_mc_server_set_metadata_p(void);
extern int utc_mc_server_set_metadata_n(void);
extern int utc_mc_server_set_icon_p(void);
extern int utc_mc_server_set_icon_n(void);
extern int utc_mc_server_set_playback_ability_p(void);
extern int utc_mc_server_set_playback_ability_n(void);
extern int utc_mc_server_update_playback_ability_p(void);
extern int utc_mc_server_update_playback_ability_n(void);
extern int utc_mc_server_set_shuffle_ability_p(void);
extern int utc_mc_server_set_shuffle_ability_n(void);
extern int utc_mc_server_set_repeat_ability_p(void);
extern int utc_mc_server_set_repeat_ability_n(void);
extern int utc_mc_server_set_ability_support_p(void);
extern int utc_mc_server_set_ability_support_n(void);
extern int utc_mc_server_update_playback_info_p(void);
extern int utc_mc_server_update_playback_info_n(void);
extern int utc_mc_server_update_metadata_p(void);
extern int utc_mc_server_update_metadata_n(void);
extern int utc_mc_server_update_shuffle_mode_p(void);
extern int utc_mc_server_update_shuffle_mode_n(void);
extern int utc_mc_server_update_repeat_mode_p(void);
extern int utc_mc_server_update_repeat_mode_n(void);
extern int utc_mc_server_set_playback_position_cmd_received_cb_p(void);
extern int utc_mc_server_set_playback_position_cmd_received_cb_n(void);
extern int utc_mc_server_unset_playback_position_cmd_received_cb_p(void);
extern int utc_mc_server_unset_playback_position_cmd_received_cb_n(void);
extern int utc_mc_server_set_shuffle_mode_cmd_received_cb_p(void);
extern int utc_mc_server_set_shuffle_mode_cmd_received_cb_n(void);
extern int utc_mc_server_unset_shuffle_mode_cmd_received_cb_p(void);
extern int utc_mc_server_unset_shuffle_mode_cmd_received_cb_n(void);
extern int utc_mc_server_set_repeat_mode_cmd_received_cb_p(void);
extern int utc_mc_server_set_repeat_mode_cmd_received_cb_n(void);
extern int utc_mc_server_unset_repeat_mode_cmd_received_cb_p(void);
extern int utc_mc_server_unset_repeat_mode_cmd_received_cb_n(void);
extern int utc_mc_server_set_playback_action_cmd_received_cb_p(void);
extern int utc_mc_server_set_playback_action_cmd_received_cb_n(void);
extern int utc_mc_server_unset_playback_action_cmd_received_cb_p(void);
extern int utc_mc_server_unset_playback_action_cmd_received_cb_n(void);
extern int utc_mc_server_set_playlist_cmd_received_cb_p(void);
extern int utc_mc_server_set_playlist_cmd_received_cb_n(void);
extern int utc_mc_server_unset_playlist_cmd_received_cb_p(void);
extern int utc_mc_server_unset_playlist_cmd_received_cb_n(void);
extern int utc_mc_server_set_custom_cmd_received_cb_p(void);
extern int utc_mc_server_set_custom_cmd_received_cb_n(void);
extern int utc_mc_server_unset_custom_cmd_received_cb_p(void);
extern int utc_mc_server_unset_custom_cmd_received_cb_n(void);
extern int utc_mc_server_send_cmd_reply_p(void);
extern int utc_mc_server_send_cmd_reply_n(void);
extern int utc_mc_server_set_playlist_item_index_p(void);
extern int utc_mc_server_set_playlist_item_index_n(void);
extern int utc_mc_server_set_playlist_item_info_p(void);
extern int utc_mc_server_set_playlist_item_info_n(void);
extern int utc_mc_server_create_playlist_p(void);
extern int utc_mc_server_create_playlist_n(void);
extern int utc_mc_server_add_item_to_playlist_p(void);
extern int utc_mc_server_add_item_to_playlist_n(void);
extern int utc_mc_server_update_playlist_done_p(void);
extern int utc_mc_server_update_playlist_done_n(void);
extern int utc_mc_server_delete_playlist_p(void);
extern int utc_mc_server_delete_playlist_n(void);
extern int utc_mc_server_foreach_playlist_p(void);
extern int utc_mc_server_foreach_playlist_n(void);
extern int utc_mc_server_foreach_client_p(void);
extern int utc_mc_server_foreach_client_n(void);
extern int utc_mc_server_set_event_reply_received_cb_p(void);
extern int utc_mc_server_set_event_reply_received_cb_n(void);
extern int utc_mc_server_unset_event_reply_received_cb_p(void);
extern int utc_mc_server_unset_event_reply_received_cb_n(void);
extern int utc_mc_server_send_custom_event_p(void);
extern int utc_mc_server_send_custom_event_n(void);
extern int utc_mc_server_set_search_cmd_received_cb_p(void);
extern int utc_mc_server_set_search_cmd_received_cb_n(void);
extern int utc_mc_server_unset_search_cmd_received_cb_p(void);
extern int utc_mc_server_unset_search_cmd_received_cb_n(void);
extern int utc_mc_server_update_subtitles_enabled_p(void);
extern int utc_mc_server_update_subtitles_enabled_n(void);
extern int utc_mc_server_update_360_mode_enabled_p(void);
extern int utc_mc_server_update_360_mode_enabled_n(void);
extern int utc_mc_server_update_display_mode_p(void);
extern int utc_mc_server_update_display_mode_n(void);
extern int utc_mc_server_update_display_rotation_p(void);
extern int utc_mc_server_update_display_rotation_n(void);
extern int utc_mc_server_set_subtitles_cmd_received_cb_p(void);
extern int utc_mc_server_set_subtitles_cmd_received_cb_n(void);
extern int utc_mc_server_unset_subtitles_cmd_received_cb_p(void);
extern int utc_mc_server_unset_subtitles_cmd_received_cb_n(void);
extern int utc_mc_server_set_360_mode_cmd_received_cb_p(void);
extern int utc_mc_server_set_360_mode_cmd_received_cb_n(void);
extern int utc_mc_server_unset_360_mode_cmd_received_cb_p(void);
extern int utc_mc_server_unset_360_mode_cmd_received_cb_n(void);
extern int utc_mc_server_set_display_mode_cmd_received_cb_p(void);
extern int utc_mc_server_set_display_mode_cmd_received_cb_n(void);
extern int utc_mc_server_unset_display_mode_cmd_received_cb_p(void);
extern int utc_mc_server_unset_display_mode_cmd_received_cb_n(void);
extern int utc_mc_server_set_display_rotation_cmd_received_cb_p(void);
extern int utc_mc_server_set_display_rotation_cmd_received_cb_n(void);
extern int utc_mc_server_unset_display_rotation_cmd_received_cb_p(void);
extern int utc_mc_server_unset_display_rotation_cmd_received_cb_n(void);
extern int utc_mc_server_set_display_mode_ability_p(void);
extern int utc_mc_server_set_display_mode_ability_n(void);
extern int utc_mc_server_set_display_rotation_ability_p(void);
extern int utc_mc_server_set_display_rotation_ability_n(void);


// utc-media-controller-client.c
extern void utc_mc_client_startup(void);
extern void utc_mc_client_cleanup(void);

extern int utc_mc_client_create_p(void);
extern int utc_mc_client_create_n(void);
extern int utc_mc_client_destroy_p(void);
extern int utc_mc_client_destroy_n(void);
extern int utc_mc_client_set_server_updated_cb_p(void);
extern int utc_mc_client_set_server_updated_cb_n(void);
extern int utc_mc_client_unset_server_updated_cb_p(void);
extern int utc_mc_client_unset_server_updated_cb_n(void);
extern int utc_mc_client_set_playback_updated_cb_p(void);
extern int utc_mc_client_set_playback_updated_cb_n(void);
extern int utc_mc_client_unset_playback_updated_cb_p(void);
extern int utc_mc_client_unset_playback_updated_cb_n(void);
extern int utc_mc_client_set_metadata_updated_cb_p(void);
extern int utc_mc_client_set_metadata_updated_cb_n(void);
extern int utc_mc_client_unset_metadata_updated_cb_p(void);
extern int utc_mc_client_unset_metadata_updated_cb_n(void);
extern int utc_mc_client_set_shuffle_mode_updated_cb_p(void);
extern int utc_mc_client_set_shuffle_mode_updated_cb_n(void);
extern int utc_mc_client_unset_shuffle_mode_updated_cb_p(void);
extern int utc_mc_client_unset_shuffle_mode_updated_cb_n(void);
extern int utc_mc_client_set_repeat_mode_updated_cb_p(void);
extern int utc_mc_client_set_repeat_mode_updated_cb_n(void);
extern int utc_mc_client_unset_repeat_mode_updated_cb_p(void);
extern int utc_mc_client_unset_repeat_mode_updated_cb_n(void);
extern int utc_mc_client_set_playback_ability_updated_cb_p(void);
extern int utc_mc_client_set_playback_ability_updated_cb_n(void);
extern int utc_mc_client_unset_playback_ability_updated_cb_p(void);
extern int utc_mc_client_unset_playback_ability_updated_cb_n(void);
extern int utc_mc_client_set_shuffle_ability_updated_cb_p(void);
extern int utc_mc_client_set_shuffle_ability_updated_cb_n(void);
extern int utc_mc_client_unset_shuffle_ability_updated_cb_p(void);
extern int utc_mc_client_unset_shuffle_ability_updated_cb_n(void);
extern int utc_mc_client_set_repeat_ability_updated_cb_p(void);
extern int utc_mc_client_set_repeat_ability_updated_cb_n(void);
extern int utc_mc_client_unset_repeat_ability_updated_cb_p(void);
extern int utc_mc_client_unset_repeat_ability_updated_cb_n(void);
extern int utc_mc_client_set_ability_support_updated_cb_p(void);
extern int utc_mc_client_set_ability_support_updated_cb_n(void);
extern int utc_mc_client_unset_ability_support_updated_cb_p(void);
extern int utc_mc_client_unset_ability_support_updated_cb_n(void);
extern int utc_mc_client_set_cmd_reply_received_cb_p(void);
extern int utc_mc_client_set_cmd_reply_received_cb_n(void);
extern int utc_mc_client_unset_cmd_reply_received_cb_p(void);
extern int utc_mc_client_unset_cmd_reply_received_cb_n(void);
extern int utc_mc_client_get_playback_state_p(void);
extern int utc_mc_client_get_playback_state_n(void);
extern int utc_mc_client_get_playback_position_p(void);
extern int utc_mc_client_get_playback_position_n(void);
extern int utc_mc_client_get_playback_content_type_p(void);
extern int utc_mc_client_get_playback_content_type_n(void);
extern int utc_mc_client_get_age_rating_p(void);
extern int utc_mc_client_get_age_rating_n(void);
extern int utc_mc_client_destroy_playback_p(void);
extern int utc_mc_client_destroy_playback_n(void);
extern int utc_mc_client_get_latest_server_info_p(void);
extern int utc_mc_client_get_latest_server_info_n(void);
extern int utc_mc_client_get_server_playback_info_p(void);
extern int utc_mc_client_get_server_playback_info_n(void);
extern int utc_mc_client_get_server_metadata_p(void);
extern int utc_mc_client_get_server_metadata_n(void);
extern int utc_mc_client_get_server_shuffle_mode_p(void);
extern int utc_mc_client_get_server_shuffle_mode_n(void);
extern int utc_mc_client_get_server_repeat_mode_p(void);
extern int utc_mc_client_get_server_repeat_mode_n(void);
extern int utc_mc_client_get_server_icon_p(void);
extern int utc_mc_client_get_server_icon_n(void);
extern int utc_mc_client_get_server_playback_ability_p(void);
extern int utc_mc_client_get_server_playback_ability_n(void);
extern int utc_mc_client_get_server_shuffle_ability_support_p(void);
extern int utc_mc_client_get_server_shuffle_ability_support_n(void);
extern int utc_mc_client_get_server_repeat_ability_support_p(void);
extern int utc_mc_client_get_server_repeat_ability_support_n(void);
extern int utc_mc_client_get_server_ability_support_p(void);
extern int utc_mc_client_get_server_ability_support_n(void);
extern int utc_mc_client_foreach_server_p(void);
extern int utc_mc_client_foreach_server_n(void);
extern int utc_mc_client_send_playback_action_cmd_p(void);
extern int utc_mc_client_send_playback_action_cmd_n(void);
extern int utc_mc_client_send_playback_position_cmd_p(void);
extern int utc_mc_client_send_playback_position_cmd_n(void);
extern int utc_mc_client_send_shuffle_mode_cmd_p(void);
extern int utc_mc_client_send_shuffle_mode_cmd_n(void);
extern int utc_mc_client_send_repeat_mode_cmd_p(void);
extern int utc_mc_client_send_repeat_mode_cmd_n(void);
extern int utc_mc_client_send_playlist_cmd_p(void);
extern int utc_mc_client_send_playlist_cmd_n(void);
extern int utc_mc_client_send_custom_cmd_p(void);
extern int utc_mc_client_send_custom_cmd_n(void);
extern int utc_mc_client_send_search_cmd_p(void);
extern int utc_mc_client_send_search_cmd_n(void);
extern int utc_mc_client_subscribe_p(void);
extern int utc_mc_client_subscribe_n(void);
extern int utc_mc_client_unsubscribe_p(void);
extern int utc_mc_client_unsubscribe_n(void);
extern int utc_mc_client_foreach_server_subscribed_p(void);
extern int utc_mc_client_foreach_server_subscribed_n(void);
extern int utc_mc_client_get_playlist_item_index_p(void);
extern int utc_mc_client_get_playlist_item_index_n(void);
extern int utc_mc_client_get_playlist_item_info_p(void);
extern int utc_mc_client_get_playlist_item_info_n(void);
extern int utc_mc_client_set_playlist_updated_cb_p(void);
extern int utc_mc_client_set_playlist_updated_cb_n(void);
extern int utc_mc_client_unset_playlist_updated_cb_p(void);
extern int utc_mc_client_unset_playlist_updated_cb_n(void);
extern int utc_mc_client_foreach_server_playlist_p(void);
extern int utc_mc_client_foreach_server_playlist_n(void);
extern int utc_mc_client_set_custom_event_received_cb_p(void);
extern int utc_mc_client_set_custom_event_received_cb_n(void);
extern int utc_mc_client_unset_custom_event_received_cb_p(void);
extern int utc_mc_client_unset_custom_event_received_cb_n(void);
extern int utc_mc_client_send_event_reply_p(void);
extern int utc_mc_client_send_event_reply_n(void);
extern int utc_mc_client_set_display_mode_ability_updated_cb_p(void);
extern int utc_mc_client_set_display_mode_ability_updated_cb_n(void);
extern int utc_mc_client_unset_display_mode_ability_updated_cb_p(void);
extern int utc_mc_client_unset_display_mode_ability_updated_cb_n(void);
extern int utc_mc_client_set_display_rotation_ability_updated_cb_p(void);
extern int utc_mc_client_set_display_rotation_ability_updated_cb_n(void);
extern int utc_mc_client_unset_display_rotation_ability_updated_cb_p(void);
extern int utc_mc_client_unset_display_rotation_ability_updated_cb_n(void);
extern int utc_mc_client_set_subtitles_updated_cb_p(void);
extern int utc_mc_client_set_subtitles_updated_cb_n(void);
extern int utc_mc_client_unset_subtitles_updated_cb_p(void);
extern int utc_mc_client_unset_subtitles_updated_cb_n(void);
extern int utc_mc_client_set_360_mode_updated_cb_p(void);
extern int utc_mc_client_set_360_mode_updated_cb_n(void);
extern int utc_mc_client_unset_360_mode_updated_cb_p(void);
extern int utc_mc_client_unset_360_mode_updated_cb_n(void);
extern int utc_mc_client_set_display_mode_updated_cb_p(void);
extern int utc_mc_client_set_display_mode_updated_cb_n(void);
extern int utc_mc_client_unset_display_mode_updated_cb_p(void);
extern int utc_mc_client_unset_display_mode_updated_cb_n(void);
extern int utc_mc_client_set_display_rotation_updated_cb_p(void);
extern int utc_mc_client_set_display_rotation_updated_cb_n(void);
extern int utc_mc_client_unset_display_rotation_updated_cb_p(void);
extern int utc_mc_client_unset_display_rotation_updated_cb_n(void);
extern int utc_mc_client_get_server_subtitles_enabled_p(void);
extern int utc_mc_client_get_server_subtitles_enabled_n(void);
extern int utc_mc_client_get_server_360_mode_enabled_p(void);
extern int utc_mc_client_get_server_360_mode_enabled_n(void);
extern int utc_mc_client_get_server_display_mode_p(void);
extern int utc_mc_client_get_server_display_mode_n(void);
extern int utc_mc_client_get_server_display_rotation_p(void);
extern int utc_mc_client_get_server_display_rotation_n(void);
extern int utc_mc_client_get_server_display_mode_ability_p(void);
extern int utc_mc_client_get_server_display_mode_ability_n(void);
extern int utc_mc_client_get_server_display_rotation_ability_p(void);
extern int utc_mc_client_get_server_display_rotation_ability_n(void);
extern int utc_mc_client_send_subtitles_cmd_p(void);
extern int utc_mc_client_send_subtitles_cmd_n(void);
extern int utc_mc_client_send_360_mode_cmd_p(void);
extern int utc_mc_client_send_360_mode_cmd_n(void);
extern int utc_mc_client_send_display_mode_cmd_p(void);
extern int utc_mc_client_send_display_mode_cmd_n(void);
extern int utc_mc_client_send_display_rotation_cmd_p(void);
extern int utc_mc_client_send_display_rotation_cmd_n(void);


// utc-media-controller.c
extern void utc_mc_playlist_startup(void);
extern void utc_mc_playlist_cleanup(void);

extern int utc_mc_playlist_get_name_p(void);
extern int utc_mc_playlist_get_name_n(void);
extern int utc_mc_playlist_get_playlist_count_p(void);
extern int utc_mc_playlist_get_playlist_count_n(void);
extern int utc_mc_playlist_foreach_playlist_p(void);
extern int utc_mc_playlist_foreach_playlist_n(void);
extern int utc_mc_playlist_get_item_count_p(void);
extern int utc_mc_playlist_get_item_count_n(void);
extern int utc_mc_playlist_foreach_item_p(void);
extern int utc_mc_playlist_foreach_item_n(void);
extern int utc_mc_playlist_get_playlist_p(void);
extern int utc_mc_playlist_get_playlist_n(void);
extern int utc_mc_playlist_clone_p(void);
extern int utc_mc_playlist_clone_n(void);
extern int utc_mc_playlist_destroy_p(void);
extern int utc_mc_playlist_destroy_n(void);

extern void utc_mc_metadata_startup(void);
extern void utc_mc_metadata_cleanup(void);
extern int utc_mc_metadata_clone_p(void);
extern int utc_mc_metadata_clone_n(void);
extern int utc_mc_metadata_destroy_p(void);
extern int utc_mc_metadata_destroy_n(void);
extern int utc_mc_metadata_get_p(void);
extern int utc_mc_metadata_get_n(void);
extern int utc_mc_metadata_encode_season_p(void);
extern int utc_mc_metadata_encode_season_n(void);
extern int utc_mc_metadata_encode_episode_p(void);
extern int utc_mc_metadata_encode_episode_n(void);
extern int utc_mc_metadata_encode_resolution_p(void);
extern int utc_mc_metadata_encode_resolution_n(void);
extern int utc_mc_metadata_decode_season_p(void);
extern int utc_mc_metadata_decode_season_n(void);
extern int utc_mc_metadata_decode_episode_p(void);
extern int utc_mc_metadata_decode_episode_n(void);
extern int utc_mc_metadata_decode_resolution_p(void);
extern int utc_mc_metadata_decode_resolution_n(void);

extern void utc_mc_playback_ability_startup(void);
extern void utc_mc_playback_ability_cleanup(void);
extern int utc_mc_playback_ability_clone_p(void);
extern int utc_mc_playback_ability_clone_n(void);
extern int utc_mc_playback_ability_destroy_p(void);
extern int utc_mc_playback_ability_destroy_n(void);
extern int utc_mc_playback_action_is_supported_p(void);
extern int utc_mc_playback_action_is_supported_n(void);

extern void utc_mc_search_startup(void);
extern void utc_mc_search_cleanup(void);
extern int utc_mc_search_create_p(void);
extern int utc_mc_search_create_n(void);
extern int utc_mc_search_set_condition_p(void);
extern int utc_mc_search_set_condition_n(void);
extern int utc_mc_search_get_condition_count_p(void);
extern int utc_mc_search_get_condition_count_n(void);
extern int utc_mc_search_foreach_condition_p(void);
extern int utc_mc_search_foreach_condition_n(void);
extern int utc_mc_search_clone_p(void);
extern int utc_mc_search_clone_n(void);
extern int utc_mc_search_destroy_p(void);
extern int utc_mc_search_destroy_n(void);


testcase tc_array[] = {
	// utc-media-controller-server.c
	{"utc_mc_server_create_p",utc_mc_server_create_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_create_n",utc_mc_server_create_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_destroy_p",utc_mc_server_destroy_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_destroy_n",utc_mc_server_destroy_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_state_p",utc_mc_server_set_playback_state_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_state_n",utc_mc_server_set_playback_state_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_position_p",utc_mc_server_set_playback_position_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_position_n",utc_mc_server_set_playback_position_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_content_type_p",utc_mc_server_set_playback_content_type_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_content_type_n",utc_mc_server_set_playback_content_type_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_content_age_rating_p",utc_mc_server_set_content_age_rating_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_content_age_rating_n",utc_mc_server_set_content_age_rating_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_metadata_p",utc_mc_server_set_metadata_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_metadata_n",utc_mc_server_set_metadata_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_icon_p",utc_mc_server_set_icon_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_icon_n",utc_mc_server_set_icon_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_ability_p",utc_mc_server_set_playback_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_ability_n",utc_mc_server_set_playback_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playback_ability_p",utc_mc_server_update_playback_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playback_ability_n",utc_mc_server_update_playback_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_shuffle_ability_p",utc_mc_server_set_shuffle_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_shuffle_ability_n",utc_mc_server_set_shuffle_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_repeat_ability_p",utc_mc_server_set_repeat_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_repeat_ability_n",utc_mc_server_set_repeat_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_ability_support_p",utc_mc_server_set_ability_support_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_ability_support_n",utc_mc_server_set_ability_support_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playback_info_p",utc_mc_server_update_playback_info_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playback_info_n",utc_mc_server_update_playback_info_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_metadata_p",utc_mc_server_update_metadata_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_metadata_n",utc_mc_server_update_metadata_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_shuffle_mode_p",utc_mc_server_update_shuffle_mode_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_shuffle_mode_n",utc_mc_server_update_shuffle_mode_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_repeat_mode_p",utc_mc_server_update_repeat_mode_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_repeat_mode_n",utc_mc_server_update_repeat_mode_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_position_cmd_received_cb_p",utc_mc_server_set_playback_position_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_position_cmd_received_cb_n",utc_mc_server_set_playback_position_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playback_position_cmd_received_cb_p",utc_mc_server_unset_playback_position_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playback_position_cmd_received_cb_n",utc_mc_server_unset_playback_position_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_shuffle_mode_cmd_received_cb_p",utc_mc_server_set_shuffle_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_shuffle_mode_cmd_received_cb_n",utc_mc_server_set_shuffle_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_shuffle_mode_cmd_received_cb_p",utc_mc_server_unset_shuffle_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_shuffle_mode_cmd_received_cb_n",utc_mc_server_unset_shuffle_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_repeat_mode_cmd_received_cb_p",utc_mc_server_set_repeat_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_repeat_mode_cmd_received_cb_n",utc_mc_server_set_repeat_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_repeat_mode_cmd_received_cb_p",utc_mc_server_unset_repeat_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_repeat_mode_cmd_received_cb_n",utc_mc_server_unset_repeat_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_action_cmd_received_cb_p",utc_mc_server_set_playback_action_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playback_action_cmd_received_cb_n",utc_mc_server_set_playback_action_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playback_action_cmd_received_cb_p",utc_mc_server_unset_playback_action_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playback_action_cmd_received_cb_n",utc_mc_server_unset_playback_action_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_cmd_received_cb_p",utc_mc_server_set_playlist_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_cmd_received_cb_n",utc_mc_server_set_playlist_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playlist_cmd_received_cb_p",utc_mc_server_unset_playlist_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_playlist_cmd_received_cb_n",utc_mc_server_unset_playlist_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_custom_cmd_received_cb_p",utc_mc_server_set_custom_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_custom_cmd_received_cb_n",utc_mc_server_set_custom_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_custom_cmd_received_cb_p",utc_mc_server_unset_custom_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_custom_cmd_received_cb_n",utc_mc_server_unset_custom_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_send_cmd_reply_p",utc_mc_server_send_cmd_reply_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_send_cmd_reply_n",utc_mc_server_send_cmd_reply_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_item_index_p",utc_mc_server_set_playlist_item_index_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_item_index_n",utc_mc_server_set_playlist_item_index_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_item_info_p",utc_mc_server_set_playlist_item_info_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_playlist_item_info_n",utc_mc_server_set_playlist_item_info_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_create_playlist_p",utc_mc_server_create_playlist_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_create_playlist_n",utc_mc_server_create_playlist_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_add_item_to_playlist_p",utc_mc_server_add_item_to_playlist_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_add_item_to_playlist_n",utc_mc_server_add_item_to_playlist_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playlist_done_p",utc_mc_server_update_playlist_done_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_playlist_done_n",utc_mc_server_update_playlist_done_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_delete_playlist_p",utc_mc_server_delete_playlist_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_delete_playlist_n",utc_mc_server_delete_playlist_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_foreach_playlist_p",utc_mc_server_foreach_playlist_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_foreach_playlist_n",utc_mc_server_foreach_playlist_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_foreach_client_p",utc_mc_server_foreach_client_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_foreach_client_n",utc_mc_server_foreach_client_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_event_reply_received_cb_p",utc_mc_server_set_event_reply_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_event_reply_received_cb_n",utc_mc_server_set_event_reply_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_event_reply_received_cb_p",utc_mc_server_unset_event_reply_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_event_reply_received_cb_n",utc_mc_server_unset_event_reply_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_send_custom_event_p",utc_mc_server_send_custom_event_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_send_custom_event_n",utc_mc_server_send_custom_event_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_search_cmd_received_cb_p",utc_mc_server_set_search_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_search_cmd_received_cb_n",utc_mc_server_set_search_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_search_cmd_received_cb_p",utc_mc_server_unset_search_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_search_cmd_received_cb_n",utc_mc_server_unset_search_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_subtitles_enabled_p",utc_mc_server_update_subtitles_enabled_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_subtitles_enabled_n",utc_mc_server_update_subtitles_enabled_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_360_mode_enabled_p",utc_mc_server_update_360_mode_enabled_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_360_mode_enabled_n",utc_mc_server_update_360_mode_enabled_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_display_mode_p",utc_mc_server_update_display_mode_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_display_mode_n",utc_mc_server_update_display_mode_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_display_rotation_p",utc_mc_server_update_display_rotation_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_update_display_rotation_n",utc_mc_server_update_display_rotation_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_subtitles_cmd_received_cb_p",utc_mc_server_set_subtitles_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_subtitles_cmd_received_cb_n",utc_mc_server_set_subtitles_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_subtitles_cmd_received_cb_p",utc_mc_server_unset_subtitles_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_subtitles_cmd_received_cb_n",utc_mc_server_unset_subtitles_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_360_mode_cmd_received_cb_p",utc_mc_server_set_360_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_360_mode_cmd_received_cb_n",utc_mc_server_set_360_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_360_mode_cmd_received_cb_p",utc_mc_server_unset_360_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_360_mode_cmd_received_cb_n",utc_mc_server_unset_360_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_mode_cmd_received_cb_p",utc_mc_server_set_display_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_mode_cmd_received_cb_n",utc_mc_server_set_display_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_display_mode_cmd_received_cb_p",utc_mc_server_unset_display_mode_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_display_mode_cmd_received_cb_n",utc_mc_server_unset_display_mode_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_rotation_cmd_received_cb_p",utc_mc_server_set_display_rotation_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_rotation_cmd_received_cb_n",utc_mc_server_set_display_rotation_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_display_rotation_cmd_received_cb_p",utc_mc_server_unset_display_rotation_cmd_received_cb_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_unset_display_rotation_cmd_received_cb_n",utc_mc_server_unset_display_rotation_cmd_received_cb_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_mode_ability_p",utc_mc_server_set_display_mode_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_mode_ability_n",utc_mc_server_set_display_mode_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_rotation_ability_p",utc_mc_server_set_display_rotation_ability_p,utc_mc_server_startup,utc_mc_server_cleanup},
	{"utc_mc_server_set_display_rotation_ability_n",utc_mc_server_set_display_rotation_ability_n,utc_mc_server_startup,utc_mc_server_cleanup},

	// utc-media-controller-client.c
	{"utc_mc_client_create_p",utc_mc_client_create_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_create_n",utc_mc_client_create_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_destroy_p",utc_mc_client_destroy_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_destroy_n",utc_mc_client_destroy_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_server_updated_cb_p",utc_mc_client_set_server_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_server_updated_cb_n",utc_mc_client_set_server_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_server_updated_cb_p",utc_mc_client_unset_server_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_server_updated_cb_n",utc_mc_client_unset_server_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playback_updated_cb_p",utc_mc_client_set_playback_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playback_updated_cb_n",utc_mc_client_set_playback_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playback_updated_cb_p",utc_mc_client_unset_playback_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playback_updated_cb_n",utc_mc_client_unset_playback_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_metadata_updated_cb_p",utc_mc_client_set_metadata_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_metadata_updated_cb_n",utc_mc_client_set_metadata_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_metadata_updated_cb_p",utc_mc_client_unset_metadata_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_metadata_updated_cb_n",utc_mc_client_unset_metadata_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_shuffle_mode_updated_cb_p",utc_mc_client_set_shuffle_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_shuffle_mode_updated_cb_n",utc_mc_client_set_shuffle_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_shuffle_mode_updated_cb_p",utc_mc_client_unset_shuffle_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_shuffle_mode_updated_cb_n",utc_mc_client_unset_shuffle_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_repeat_mode_updated_cb_p",utc_mc_client_set_repeat_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_repeat_mode_updated_cb_n",utc_mc_client_set_repeat_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_repeat_mode_updated_cb_p",utc_mc_client_unset_repeat_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_repeat_mode_updated_cb_n",utc_mc_client_unset_repeat_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playback_ability_updated_cb_p",utc_mc_client_set_playback_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playback_ability_updated_cb_n",utc_mc_client_set_playback_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playback_ability_updated_cb_p",utc_mc_client_unset_playback_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playback_ability_updated_cb_n",utc_mc_client_unset_playback_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_shuffle_ability_updated_cb_p",utc_mc_client_set_shuffle_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_shuffle_ability_updated_cb_n",utc_mc_client_set_shuffle_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_shuffle_ability_updated_cb_p",utc_mc_client_unset_shuffle_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_shuffle_ability_updated_cb_n",utc_mc_client_unset_shuffle_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_repeat_ability_updated_cb_p",utc_mc_client_set_repeat_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_repeat_ability_updated_cb_n",utc_mc_client_set_repeat_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_repeat_ability_updated_cb_p",utc_mc_client_unset_repeat_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_repeat_ability_updated_cb_n",utc_mc_client_unset_repeat_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_ability_support_updated_cb_p",utc_mc_client_set_ability_support_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_ability_support_updated_cb_n",utc_mc_client_set_ability_support_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_ability_support_updated_cb_p",utc_mc_client_unset_ability_support_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_ability_support_updated_cb_n",utc_mc_client_unset_ability_support_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_cmd_reply_received_cb_p",utc_mc_client_set_cmd_reply_received_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_cmd_reply_received_cb_n",utc_mc_client_set_cmd_reply_received_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_cmd_reply_received_cb_p",utc_mc_client_unset_cmd_reply_received_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_cmd_reply_received_cb_n",utc_mc_client_unset_cmd_reply_received_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_state_p",utc_mc_client_get_playback_state_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_state_n",utc_mc_client_get_playback_state_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_position_p",utc_mc_client_get_playback_position_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_position_n",utc_mc_client_get_playback_position_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_content_type_p",utc_mc_client_get_playback_content_type_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playback_content_type_n",utc_mc_client_get_playback_content_type_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_age_rating_p",utc_mc_client_get_age_rating_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_age_rating_n",utc_mc_client_get_age_rating_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_destroy_playback_p",utc_mc_client_destroy_playback_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_destroy_playback_n",utc_mc_client_destroy_playback_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_latest_server_info_p",utc_mc_client_get_latest_server_info_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_latest_server_info_n",utc_mc_client_get_latest_server_info_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_playback_info_p",utc_mc_client_get_server_playback_info_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_playback_info_n",utc_mc_client_get_server_playback_info_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_metadata_p",utc_mc_client_get_server_metadata_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_metadata_n",utc_mc_client_get_server_metadata_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_shuffle_mode_p",utc_mc_client_get_server_shuffle_mode_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_shuffle_mode_n",utc_mc_client_get_server_shuffle_mode_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_repeat_mode_p",utc_mc_client_get_server_repeat_mode_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_repeat_mode_n",utc_mc_client_get_server_repeat_mode_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_icon_p",utc_mc_client_get_server_icon_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_icon_n",utc_mc_client_get_server_icon_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_playback_ability_p",utc_mc_client_get_server_playback_ability_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_playback_ability_n",utc_mc_client_get_server_playback_ability_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_shuffle_ability_support_p",utc_mc_client_get_server_shuffle_ability_support_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_shuffle_ability_support_n",utc_mc_client_get_server_shuffle_ability_support_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_repeat_ability_support_p",utc_mc_client_get_server_repeat_ability_support_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_repeat_ability_support_n",utc_mc_client_get_server_repeat_ability_support_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_ability_support_p",utc_mc_client_get_server_ability_support_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_ability_support_n",utc_mc_client_get_server_ability_support_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_p",utc_mc_client_foreach_server_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_n",utc_mc_client_foreach_server_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playback_action_cmd_p",utc_mc_client_send_playback_action_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playback_action_cmd_n",utc_mc_client_send_playback_action_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playback_position_cmd_p",utc_mc_client_send_playback_position_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playback_position_cmd_n",utc_mc_client_send_playback_position_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_shuffle_mode_cmd_p",utc_mc_client_send_shuffle_mode_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_shuffle_mode_cmd_n",utc_mc_client_send_shuffle_mode_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_repeat_mode_cmd_p",utc_mc_client_send_repeat_mode_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_repeat_mode_cmd_n",utc_mc_client_send_repeat_mode_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playlist_cmd_p",utc_mc_client_send_playlist_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_playlist_cmd_n",utc_mc_client_send_playlist_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_custom_cmd_p",utc_mc_client_send_custom_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_custom_cmd_n",utc_mc_client_send_custom_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_search_cmd_p",utc_mc_client_send_search_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_search_cmd_n",utc_mc_client_send_search_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_subscribe_p",utc_mc_client_subscribe_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_subscribe_n",utc_mc_client_subscribe_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unsubscribe_p",utc_mc_client_unsubscribe_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unsubscribe_n",utc_mc_client_unsubscribe_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playlist_item_index_p",utc_mc_client_get_playlist_item_index_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playlist_item_index_n",utc_mc_client_get_playlist_item_index_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_subscribed_p",utc_mc_client_foreach_server_subscribed_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_subscribed_n",utc_mc_client_foreach_server_subscribed_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playlist_item_info_p",utc_mc_client_get_playlist_item_info_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_playlist_item_info_n",utc_mc_client_get_playlist_item_info_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playlist_updated_cb_p",utc_mc_client_set_playlist_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_playlist_updated_cb_n",utc_mc_client_set_playlist_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playlist_updated_cb_p",utc_mc_client_unset_playlist_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_playlist_updated_cb_n",utc_mc_client_unset_playlist_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_playlist_p",utc_mc_client_foreach_server_playlist_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_foreach_server_playlist_n",utc_mc_client_foreach_server_playlist_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_custom_event_received_cb_p",utc_mc_client_set_custom_event_received_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_custom_event_received_cb_n",utc_mc_client_set_custom_event_received_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_custom_event_received_cb_p",utc_mc_client_unset_custom_event_received_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_custom_event_received_cb_n",utc_mc_client_unset_custom_event_received_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_event_reply_p",utc_mc_client_send_event_reply_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_event_reply_n",utc_mc_client_send_event_reply_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_mode_ability_updated_cb_p",utc_mc_client_set_display_mode_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_mode_ability_updated_cb_n",utc_mc_client_set_display_mode_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_mode_ability_updated_cb_p",utc_mc_client_unset_display_mode_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_mode_ability_updated_cb_n",utc_mc_client_unset_display_mode_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_rotation_ability_updated_cb_p",utc_mc_client_set_display_rotation_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_rotation_ability_updated_cb_n",utc_mc_client_set_display_rotation_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_rotation_ability_updated_cb_p",utc_mc_client_unset_display_rotation_ability_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_rotation_ability_updated_cb_n",utc_mc_client_unset_display_rotation_ability_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_subtitles_updated_cb_p",utc_mc_client_set_subtitles_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_subtitles_updated_cb_n",utc_mc_client_set_subtitles_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_subtitles_updated_cb_p",utc_mc_client_unset_subtitles_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_subtitles_updated_cb_n",utc_mc_client_unset_subtitles_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_360_mode_updated_cb_p",utc_mc_client_set_360_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_360_mode_updated_cb_n",utc_mc_client_set_360_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_360_mode_updated_cb_p",utc_mc_client_unset_360_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_360_mode_updated_cb_n",utc_mc_client_unset_360_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_mode_updated_cb_p",utc_mc_client_set_display_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_mode_updated_cb_n",utc_mc_client_set_display_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_mode_updated_cb_p",utc_mc_client_unset_display_mode_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_mode_updated_cb_n",utc_mc_client_unset_display_mode_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_rotation_updated_cb_p",utc_mc_client_set_display_rotation_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_set_display_rotation_updated_cb_n",utc_mc_client_set_display_rotation_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_rotation_updated_cb_p",utc_mc_client_unset_display_rotation_updated_cb_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_unset_display_rotation_updated_cb_n",utc_mc_client_unset_display_rotation_updated_cb_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_subtitles_enabled_p",utc_mc_client_get_server_subtitles_enabled_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_subtitles_enabled_n",utc_mc_client_get_server_subtitles_enabled_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_360_mode_enabled_p",utc_mc_client_get_server_360_mode_enabled_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_360_mode_enabled_n",utc_mc_client_get_server_360_mode_enabled_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_mode_p",utc_mc_client_get_server_display_mode_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_mode_n",utc_mc_client_get_server_display_mode_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_rotation_p",utc_mc_client_get_server_display_rotation_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_rotation_n",utc_mc_client_get_server_display_rotation_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_mode_ability_p",utc_mc_client_get_server_display_mode_ability_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_mode_ability_n",utc_mc_client_get_server_display_mode_ability_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_rotation_ability_p",utc_mc_client_get_server_display_rotation_ability_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_get_server_display_rotation_ability_n",utc_mc_client_get_server_display_rotation_ability_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_subtitles_cmd_p",utc_mc_client_send_subtitles_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_subtitles_cmd_n",utc_mc_client_send_subtitles_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_360_mode_cmd_p",utc_mc_client_send_360_mode_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_360_mode_cmd_n",utc_mc_client_send_360_mode_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_display_mode_cmd_p",utc_mc_client_send_display_mode_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_display_mode_cmd_n",utc_mc_client_send_display_mode_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_display_rotation_cmd_p",utc_mc_client_send_display_rotation_cmd_p,utc_mc_client_startup,utc_mc_client_cleanup},
	{"utc_mc_client_send_display_rotation_cmd_n",utc_mc_client_send_display_rotation_cmd_n,utc_mc_client_startup,utc_mc_client_cleanup},

	// utc-media-controller.c
	{"utc_mc_playlist_get_name_p",utc_mc_playlist_get_name_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_name_n",utc_mc_playlist_get_name_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_playlist_count_p",utc_mc_playlist_get_playlist_count_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_playlist_count_n",utc_mc_playlist_get_playlist_count_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_foreach_playlist_p",utc_mc_playlist_foreach_playlist_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_foreach_playlist_n",utc_mc_playlist_foreach_playlist_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_item_count_p",utc_mc_playlist_get_item_count_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_item_count_n",utc_mc_playlist_get_item_count_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_foreach_item_p",utc_mc_playlist_foreach_item_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_foreach_item_n",utc_mc_playlist_foreach_item_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_playlist_p",utc_mc_playlist_get_playlist_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_get_playlist_n",utc_mc_playlist_get_playlist_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_clone_p",utc_mc_playlist_clone_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_clone_n",utc_mc_playlist_clone_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_destroy_p",utc_mc_playlist_destroy_p,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_playlist_destroy_n",utc_mc_playlist_destroy_n,utc_mc_playlist_startup,utc_mc_playlist_cleanup},
	{"utc_mc_metadata_clone_p",utc_mc_metadata_clone_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_clone_n",utc_mc_metadata_clone_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_destroy_p",utc_mc_metadata_destroy_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_destroy_n",utc_mc_metadata_destroy_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_get_p",utc_mc_metadata_get_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_get_n",utc_mc_metadata_get_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_season_p",utc_mc_metadata_encode_season_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_season_n",utc_mc_metadata_encode_season_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_episode_p",utc_mc_metadata_encode_episode_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_episode_n",utc_mc_metadata_encode_episode_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_resolution_p",utc_mc_metadata_encode_resolution_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_encode_resolution_n",utc_mc_metadata_encode_resolution_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_season_p",utc_mc_metadata_decode_season_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_season_n",utc_mc_metadata_decode_season_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_episode_p",utc_mc_metadata_decode_episode_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_episode_n",utc_mc_metadata_decode_episode_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_resolution_p",utc_mc_metadata_decode_resolution_p,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_metadata_decode_resolution_n",utc_mc_metadata_decode_resolution_n,utc_mc_metadata_startup,utc_mc_metadata_cleanup},
	{"utc_mc_playback_ability_clone_p",utc_mc_playback_ability_clone_p,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_playback_ability_clone_n",utc_mc_playback_ability_clone_n,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_playback_ability_destroy_p",utc_mc_playback_ability_destroy_p,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_playback_ability_destroy_n",utc_mc_playback_ability_destroy_n,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_playback_action_is_supported_p",utc_mc_playback_action_is_supported_p,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_playback_action_is_supported_n",utc_mc_playback_action_is_supported_n,utc_mc_playback_ability_startup,utc_mc_playback_ability_cleanup},
	{"utc_mc_search_create_p",utc_mc_search_create_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_create_n",utc_mc_search_create_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_set_condition_p",utc_mc_search_set_condition_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_set_condition_n",utc_mc_search_set_condition_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_get_condition_count_p",utc_mc_search_get_condition_count_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_get_condition_count_n",utc_mc_search_get_condition_count_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_foreach_condition_p",utc_mc_search_foreach_condition_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_foreach_condition_n",utc_mc_search_foreach_condition_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_clone_p",utc_mc_search_clone_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_clone_n",utc_mc_search_clone_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_destroy_p",utc_mc_search_destroy_p,utc_mc_search_startup,utc_mc_search_cleanup},
	{"utc_mc_search_destroy_n",utc_mc_search_destroy_n,utc_mc_search_startup,utc_mc_search_cleanup},
	{NULL, NULL}
};

#endif // __TCT_MEDIA-CONTROLLER-NATIVE_H__
