//
// Copyright (c) 2019 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAPI_UI_STICKER_NATIVE_H__
#define __TCT_CAPI_UI_STICKER_NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_capi_ui_sticker_data_startup(void);
extern void ITs_capi_ui_sticker_data_cleanup(void);

extern void ITs_capi_ui_sticker_consumer_startup(void);
extern void ITs_capi_ui_sticker_consumer_cleanup(void);

extern void ITs_capi_ui_sticker_provider_startup(void);
extern void ITs_capi_ui_sticker_provider_cleanup(void);

extern int ITc_capi_ui_sticker_data_sticker_data_create_destroy_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_clone_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_get_app_id_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_set_get_uri_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_foreach_keyword_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_add_remove_keyword_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_set_get_group_name_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_set_get_thumbnail_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_set_get_description_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_get_date_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_set_get_display_type_p(void);

extern int ITc_capi_ui_sticker_data_sticker_consumer_create_destroy_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_all_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_keyword_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_group_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_type_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_all_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_keyword_list_foreach_all_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_display_type_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_by_display_type_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_add_get_recent_data_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_set_unset_event_cb_p(void);
extern int ITc_capi_ui_sticker_data_sticker_consumer_group_image_list_foreach_all_p(void);

extern int ITc_capi_ui_sticker_data_sticker_provider_create_destroy_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_insert_data_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_insert_data_by_json_file_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_update_data_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_delete_data_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_get_sticker_count_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_data_foreach_all_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_delete_data_by_uri_p(void);
extern int ITc_capi_ui_sticker_data_sticker_data_get_handle_p(void);
extern int ITc_capi_ui_sticker_data_sticker_provider_set_group_image_p(void);

testcase tc_array[] = {
{"ITc_capi_ui_sticker_data_sticker_data_create_destroy_p", ITc_capi_ui_sticker_data_sticker_data_create_destroy_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_clone_p", ITc_capi_ui_sticker_data_sticker_data_clone_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_get_app_id_p", ITc_capi_ui_sticker_data_sticker_data_get_app_id_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_set_get_uri_p", ITc_capi_ui_sticker_data_sticker_data_set_get_uri_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_foreach_keyword_p", ITc_capi_ui_sticker_data_sticker_data_foreach_keyword_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_add_remove_keyword_p", ITc_capi_ui_sticker_data_sticker_data_add_remove_keyword_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_set_get_group_name_p", ITc_capi_ui_sticker_data_sticker_data_set_get_group_name_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_set_get_thumbnail_p", ITc_capi_ui_sticker_data_sticker_data_set_get_thumbnail_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_set_get_description_p", ITc_capi_ui_sticker_data_sticker_data_set_get_description_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_get_date_p", ITc_capi_ui_sticker_data_sticker_data_get_date_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_set_get_display_type_p", ITc_capi_ui_sticker_data_sticker_data_set_get_display_type_p, ITs_capi_ui_sticker_data_startup, ITs_capi_ui_sticker_data_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_create_destroy_p", ITc_capi_ui_sticker_data_sticker_consumer_create_destroy_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_all_p", ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_all_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_keyword_p", ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_keyword_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_group_p", ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_group_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_type_p", ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_type_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_all_p", ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_all_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_keyword_list_foreach_all_p", ITc_capi_ui_sticker_data_sticker_consumer_keyword_list_foreach_all_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_display_type_p", ITc_capi_ui_sticker_data_sticker_consumer_data_foreach_by_display_type_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_by_display_type_p", ITc_capi_ui_sticker_data_sticker_consumer_group_list_foreach_by_display_type_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_add_get_recent_data_p", ITc_capi_ui_sticker_data_sticker_consumer_add_get_recent_data_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_set_unset_event_cb_p", ITc_capi_ui_sticker_data_sticker_consumer_set_unset_event_cb_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_consumer_group_image_list_foreach_all_p", ITc_capi_ui_sticker_data_sticker_consumer_group_image_list_foreach_all_p, ITs_capi_ui_sticker_consumer_startup, ITs_capi_ui_sticker_consumer_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_create_destroy_p", ITc_capi_ui_sticker_data_sticker_provider_create_destroy_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_insert_data_p", ITc_capi_ui_sticker_data_sticker_provider_insert_data_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_insert_data_by_json_file_p", ITc_capi_ui_sticker_data_sticker_provider_insert_data_by_json_file_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_update_data_p", ITc_capi_ui_sticker_data_sticker_provider_update_data_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_delete_data_p", ITc_capi_ui_sticker_data_sticker_provider_delete_data_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_get_sticker_count_p", ITc_capi_ui_sticker_data_sticker_provider_get_sticker_count_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_data_foreach_all_p", ITc_capi_ui_sticker_data_sticker_provider_data_foreach_all_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_delete_data_by_uri_p", ITc_capi_ui_sticker_data_sticker_provider_delete_data_by_uri_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_data_get_handle_p", ITc_capi_ui_sticker_data_sticker_data_get_handle_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{"ITc_capi_ui_sticker_data_sticker_provider_set_group_image_p", ITc_capi_ui_sticker_data_sticker_provider_set_group_image_p, ITs_capi_ui_sticker_provider_startup, ITs_capi_ui_sticker_provider_cleanup},
{NULL, NULL}
};

#endif // __TCT_CAPI_UI_STICKER_NATIVE_H__
