//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_DATA-CONTROL-NATIVE_H__
#define __TCT_DATA-CONTROL-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_data_control_map_startup(void);
extern void utc_data_control_map_cleanup(void);
extern void utc_data_control_sql_startup(void);
extern void utc_data_control_sql_cleanup(void);
extern void utc_data_control_provider_startup(void);
extern void utc_data_control_provider_cleanup(void);
extern void utc_data_control_noti_startup(void);
extern void utc_data_control_noti_cleanup(void);
extern void utc_data_control_bulk_startup(void);
extern void utc_data_control_bulk_cleanup(void);

extern int utc_data_control_map_create_p(void);
extern int utc_data_control_map_create_n(void);
extern int utc_data_control_map_destroy_p(void);
extern int utc_data_control_map_destroy_n(void);
extern int utc_data_control_map_set_provider_id_p(void);
extern int utc_data_control_map_set_provider_id_n(void);
extern int utc_data_control_map_get_provider_id_p(void);
extern int utc_data_control_map_get_provider_id_n(void);
extern int utc_data_control_map_set_data_id_p(void);
extern int utc_data_control_map_set_data_id_n(void);
extern int utc_data_control_map_get_data_id_p(void);
extern int utc_data_control_map_get_data_id_n(void);
extern int utc_data_control_map_register_response_cb_p(void);
extern int utc_data_control_map_register_response_cb_n(void);
extern int utc_data_control_map_unregister_response_cb_p(void);
extern int utc_data_control_map_get_handle_id_p(void);
extern int utc_data_control_map_get_handle_id_n(void);
extern int utc_data_control_map_bind_response_cb_p1(void);
extern int utc_data_control_map_bind_response_cb_p2(void);
extern int utc_data_control_map_bind_response_cb_p3(void);
extern int utc_data_control_map_bind_response_cb_n(void);
extern int utc_data_control_map_unbind_response_cb_p(void);
extern int utc_data_control_map_unbind_response_cb_n(void);
extern int utc_data_control_map_add_p(void);
extern int utc_data_control_map_add_p1(void);
extern int utc_data_control_map_add_n1(void);
extern int utc_data_control_map_add_n2(void);
extern int utc_data_control_map_add_n3(void);
extern int utc_data_control_map_set_p01(void);
extern int utc_data_control_map_set_p02(void);
extern int utc_data_control_map_set_n1(void);
extern int utc_data_control_map_set_n2(void);
extern int utc_data_control_map_get_p(void);
extern int utc_data_control_map_get_n1(void);
extern int utc_data_control_map_get_n2(void);
extern int utc_data_control_map_get_with_page_p(void);
extern int utc_data_control_map_get_with_page_n1(void);
extern int utc_data_control_map_get_with_page_n2(void);
extern int utc_data_control_map_remove_p(void);
extern int utc_data_control_map_remove_n1(void);
extern int utc_data_control_map_remove_n2(void);
extern int utc_data_control_map_add_bulk_data_p(void);
extern int utc_data_control_map_add_bulk_data_n1(void);
extern int utc_data_control_map_add_bulk_data_n2(void);
extern int utc_data_control_map_register_add_bulk_data_response_cb_p(void);
extern int utc_data_control_map_register_add_bulk_data_response_cb_n(void);
extern int utc_data_control_map_unregister_add_bulk_data_response_cb_p(void);
extern int utc_data_control_map_unregister_add_bulk_data_response_cb_n(void);
extern int utc_data_control_map_bind_add_bulk_data_response_cb_p1(void);
extern int utc_data_control_map_bind_add_bulk_data_response_cb_p2(void);
extern int utc_data_control_map_bind_add_bulk_data_response_cb_p3(void);
extern int utc_data_control_map_bind_add_bulk_data_response_cb_n(void);
extern int utc_data_control_map_unbind_add_bulk_data_response_cb_p(void);
extern int utc_data_control_map_unbind_add_bulk_data_response_cb_n(void);
extern int utc_data_control_sql_create_p(void);
extern int utc_data_control_sql_create_n(void);
extern int utc_data_control_sql_destroy_p(void);
extern int utc_data_control_sql_destroy_n(void);
extern int utc_data_control_sql_set_provider_id_p(void);
extern int utc_data_control_sql_set_provider_id_n(void);
extern int utc_data_control_sql_get_provider_id_p(void);
extern int utc_data_control_sql_get_provider_id_n(void);
extern int utc_data_control_provider_match_provider_id_p(void);
extern int utc_data_control_provider_match_provider_id_n01(void);
extern int utc_data_control_provider_match_provider_id_n02(void);
extern int utc_data_control_sql_set_data_id_p(void);
extern int utc_data_control_sql_set_data_id_n(void);
extern int utc_data_control_provider_match_data_id_p(void);
extern int utc_data_control_provider_match_data_id_n01(void);
extern int utc_data_control_provider_match_data_id_n02(void);
extern int utc_data_control_sql_get_data_id_p(void);
extern int utc_data_control_sql_get_data_id_n(void);
extern int utc_data_control_sql_register_response_cb_p(void);
extern int utc_data_control_sql_register_response_cb_n(void);
extern int utc_data_control_sql_unregister_response_cb_p(void);
extern int utc_data_control_sql_get_handle_id_p(void);
extern int utc_data_control_sql_get_handle_id_n(void);
extern int utc_data_control_sql_bind_response_cb_p1(void);
extern int utc_data_control_sql_bind_response_cb_p2(void);
extern int utc_data_control_sql_bind_response_cb_p3(void);
extern int utc_data_control_sql_bind_response_cb_n(void);
extern int utc_data_control_sql_unbind_response_cb_p(void);
extern int utc_data_control_sql_unbind_response_cb_n(void);
extern int utc_data_control_sql_insert_p(void);
extern int utc_data_control_sql_insert_n1(void);
extern int utc_data_control_sql_insert_n2(void);
extern int utc_data_control_sql_update_p(void);
extern int utc_data_control_sql_update_n1(void);
extern int utc_data_control_sql_update_n2(void);
extern int utc_data_control_sql_select_p(void);
extern int utc_data_control_sql_select_n1(void);
extern int utc_data_control_sql_select_n2(void);
extern int utc_data_control_sql_select_with_page_p(void);
extern int utc_data_control_sql_select_with_page_p2(void);
extern int utc_data_control_sql_select_with_page_n1(void);
extern int utc_data_control_sql_select_with_page_n2(void);
extern int utc_data_control_sql_delete_p(void);
extern int utc_data_control_sql_delete_n1(void);
extern int utc_data_control_sql_delete_n2(void);
extern int utc_data_control_sql_get_blob_data_n(void);
extern int utc_data_control_sql_get_column_count_n(void);
extern int utc_data_control_sql_get_column_item_size_n(void);
extern int utc_data_control_sql_get_column_item_type_n(void);
extern int utc_data_control_sql_get_column_name_n(void);
extern int utc_data_control_sql_get_double_data_n(void);
extern int utc_data_control_sql_get_int_data_n(void);
extern int utc_data_control_sql_get_int64_data_n(void);
extern int utc_data_control_sql_get_text_data_n(void);
extern int utc_data_control_sql_step_first_n(void);
extern int utc_data_control_sql_step_last_n(void);
extern int utc_data_control_sql_step_next_n(void);
extern int utc_data_control_sql_step_previous_n(void);
extern int utc_data_control_sql_insert_bulk_data_p(void);
extern int utc_data_control_sql_insert_bulk_data_n1(void);
extern int utc_data_control_sql_insert_bulk_data_n2(void);
extern int utc_data_control_sql_register_insert_bulk_data_response_cb_p(void);
extern int utc_data_control_sql_register_insert_bulk_data_response_cb_n(void);
extern int utc_data_control_sql_unregister_insert_bulk_data_response_cb_p(void);
extern int utc_data_control_sql_unregister_insert_bulk_data_response_cb_n(void);
extern int utc_data_control_sql_bind_insert_bulk_data_response_cb_p1(void);
extern int utc_data_control_sql_bind_insert_bulk_data_response_cb_p2(void);
extern int utc_data_control_sql_bind_insert_bulk_data_response_cb_p3(void);
extern int utc_data_control_sql_bind_insert_bulk_data_response_cb_n(void);
extern int utc_data_control_sql_unbind_insert_bulk_data_response_cb_p(void);
extern int utc_data_control_sql_unbind_insert_bulk_data_response_cb_n(void);
extern int utc_data_control_provider_create_select_statement_n(void);
extern int utc_data_control_provider_create_insert_statement_n(void);
extern int utc_data_control_provider_create_delete_statement_n(void);
extern int utc_data_control_provider_create_update_statement_n(void);
extern int utc_data_control_provider_get_client_appid_n(void);
extern int utc_data_control_provider_send_delete_result_n(void);
extern int utc_data_control_provider_send_error_n(void);
extern int utc_data_control_provider_send_insert_result_n(void);
extern int utc_data_control_provider_send_map_get_value_result_n(void);
extern int utc_data_control_provider_send_map_result_n(void);
extern int utc_data_control_provider_send_select_result_n(void);
extern int utc_data_control_provider_send_update_result_n(void);
extern int utc_data_control_provider_sql_register_cb_p(void);
extern int utc_data_control_provider_sql_register_cb_n(void);
extern int utc_data_control_provider_sql_unregister_cb_p(void);
extern int utc_data_control_provider_map_register_cb_p(void);
extern int utc_data_control_provider_map_register_cb_n(void);
extern int utc_data_control_provider_map_unregister_cb_p(void);
extern int utc_data_control_provider_send_data_change_noti_p(void);
extern int utc_data_control_provider_send_data_change_noti_n01(void);
extern int utc_data_control_provider_send_data_change_noti_n02(void);
extern int utc_data_control_provider_add_data_change_consumer_filter_cb_p(void);
extern int utc_data_control_provider_add_data_change_consumer_filter_cb_n01(void);
extern int utc_data_control_provider_add_data_change_consumer_filter_cb_n02(void);
extern int utc_data_control_provider_remove_data_change_consumer_filter_cb_p(void);
extern int utc_data_control_provider_remove_data_change_consumer_filter_cb_n(void);
extern int utc_data_control_provider_foreach_data_change_consumer_p(void);
extern int utc_data_control_provider_foreach_data_change_consumer_n01(void);
extern int utc_data_control_provider_foreach_data_change_consumer_n02(void);
extern int utc_data_control_provider_send_bulk_insert_result_n01(void);
extern int utc_data_control_provider_send_map_bulk_add_result_n01(void);
extern int utc_data_control_provider_sql_register_insert_bulk_data_request_cb_p(void);
extern int utc_data_control_provider_sql_register_insert_bulk_data_request_cb_n01(void);
extern int utc_data_control_provider_sql_unregister_insert_bulk_data_request_cb_p(void);
extern int utc_data_control_provider_map_register_add_bulk_data_request_cb_p(void);
extern int utc_data_control_provider_map_register_add_bulk_data_request_cb_n01(void);
extern int utc_data_control_provider_map_unregister_add_bulk_data_request_cb_p(void);
extern int utc_data_control_add_data_change_cb_p(void);
extern int utc_data_control_add_data_change_cb_n01(void);
extern int utc_data_control_add_data_change_cb_n02(void);
extern int utc_data_control_add_data_change_cb_n03(void);
extern int utc_data_control_add_data_change_cb_n04(void);
extern int utc_data_control_remove_data_change_cb_p(void);
extern int utc_data_control_remove_data_change_cb_n01(void);
extern int utc_data_control_remove_data_change_cb_n02(void);
extern int utc_data_control_remove_data_change_cb_n03(void);
extern int utc_data_control_bulk_data_get_data_p(void);
extern int utc_data_control_bulk_data_get_data_n01(void);
extern int utc_data_control_bulk_data_get_data_n02(void);
extern int utc_data_control_bulk_data_get_count_p(void);
extern int utc_data_control_bulk_data_get_count_n01(void);
extern int utc_data_control_bulk_data_get_count_n02(void);
extern int utc_data_control_bulk_data_add_p(void);
extern int utc_data_control_bulk_data_add_n01(void);
extern int utc_data_control_bulk_data_create_p(void);
extern int utc_data_control_bulk_data_create_n(void);
extern int utc_data_control_bulk_data_destroy_p(void);
extern int utc_data_control_bulk_data_destroy_n(void);
extern int utc_data_control_bulk_result_data_get_result_data_p(void);
extern int utc_data_control_bulk_result_data_get_result_data_n01(void);
extern int utc_data_control_bulk_result_data_get_result_data_n02(void);
extern int utc_data_control_bulk_result_data_get_count_p(void);
extern int utc_data_control_bulk_result_data_get_count_n01(void);
extern int utc_data_control_bulk_result_data_get_count_n02(void);
extern int utc_data_control_bulk_result_data_add_p(void);
extern int utc_data_control_bulk_result_data_add_n01(void);
extern int utc_data_control_bulk_result_data_create_p(void);
extern int utc_data_control_bulk_result_data_create_n(void);
extern int utc_data_control_bulk_result_data_destroy_p(void);
extern int utc_data_control_bulk_result_data_destroy_n(void);

testcase tc_array[] = {
	{"utc_data_control_map_create_p",utc_data_control_map_create_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_create_n",utc_data_control_map_create_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_destroy_p",utc_data_control_map_destroy_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_destroy_n",utc_data_control_map_destroy_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_provider_id_p",utc_data_control_map_set_provider_id_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_provider_id_n",utc_data_control_map_set_provider_id_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_provider_id_p",utc_data_control_map_get_provider_id_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_provider_id_n",utc_data_control_map_get_provider_id_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_data_id_p",utc_data_control_map_set_data_id_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_data_id_n",utc_data_control_map_set_data_id_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_data_id_p",utc_data_control_map_get_data_id_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_data_id_n",utc_data_control_map_get_data_id_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_register_response_cb_p",utc_data_control_map_register_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_register_response_cb_n",utc_data_control_map_register_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unregister_response_cb_p",utc_data_control_map_unregister_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_handle_id_p",utc_data_control_map_get_handle_id_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_handle_id_n",utc_data_control_map_get_handle_id_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_response_cb_p1",utc_data_control_map_bind_response_cb_p1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_response_cb_p2",utc_data_control_map_bind_response_cb_p2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_response_cb_p3",utc_data_control_map_bind_response_cb_p3,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_response_cb_n",utc_data_control_map_bind_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unbind_response_cb_p",utc_data_control_map_unbind_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unbind_response_cb_n",utc_data_control_map_unbind_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_p",utc_data_control_map_add_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_p1",utc_data_control_map_add_p1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_n1",utc_data_control_map_add_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_n2",utc_data_control_map_add_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_n3",utc_data_control_map_add_n3,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_p01",utc_data_control_map_set_p01,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_p02",utc_data_control_map_set_p02,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_n1",utc_data_control_map_set_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_set_n2",utc_data_control_map_set_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_p",utc_data_control_map_get_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_n1",utc_data_control_map_get_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_n2",utc_data_control_map_get_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_with_page_p",utc_data_control_map_get_with_page_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_with_page_n1",utc_data_control_map_get_with_page_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_get_with_page_n2",utc_data_control_map_get_with_page_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_remove_p",utc_data_control_map_remove_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_remove_n1",utc_data_control_map_remove_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_remove_n2",utc_data_control_map_remove_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_bulk_data_p",utc_data_control_map_add_bulk_data_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_bulk_data_n1",utc_data_control_map_add_bulk_data_n1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_add_bulk_data_n2",utc_data_control_map_add_bulk_data_n2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_register_add_bulk_data_response_cb_p",utc_data_control_map_register_add_bulk_data_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_register_add_bulk_data_response_cb_n",utc_data_control_map_register_add_bulk_data_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unregister_add_bulk_data_response_cb_p",utc_data_control_map_unregister_add_bulk_data_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unregister_add_bulk_data_response_cb_n",utc_data_control_map_unregister_add_bulk_data_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_add_bulk_data_response_cb_p1",utc_data_control_map_bind_add_bulk_data_response_cb_p1,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_add_bulk_data_response_cb_p2",utc_data_control_map_bind_add_bulk_data_response_cb_p2,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_add_bulk_data_response_cb_p3",utc_data_control_map_bind_add_bulk_data_response_cb_p3,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_bind_add_bulk_data_response_cb_n",utc_data_control_map_bind_add_bulk_data_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unbind_add_bulk_data_response_cb_p",utc_data_control_map_unbind_add_bulk_data_response_cb_p,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_map_unbind_add_bulk_data_response_cb_n",utc_data_control_map_unbind_add_bulk_data_response_cb_n,utc_data_control_map_startup,utc_data_control_map_cleanup},
	{"utc_data_control_sql_create_p",utc_data_control_sql_create_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_create_n",utc_data_control_sql_create_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_destroy_p",utc_data_control_sql_destroy_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_destroy_n",utc_data_control_sql_destroy_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_set_provider_id_p",utc_data_control_sql_set_provider_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_set_provider_id_n",utc_data_control_sql_set_provider_id_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_provider_id_p",utc_data_control_sql_get_provider_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_provider_id_n",utc_data_control_sql_get_provider_id_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_provider_id_p",utc_data_control_provider_match_provider_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_provider_id_n01",utc_data_control_provider_match_provider_id_n01,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_provider_id_n02",utc_data_control_provider_match_provider_id_n02,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_set_data_id_p",utc_data_control_sql_set_data_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_set_data_id_n",utc_data_control_sql_set_data_id_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_data_id_p",utc_data_control_provider_match_data_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_data_id_n01",utc_data_control_provider_match_data_id_n01,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_match_data_id_n02",utc_data_control_provider_match_data_id_n02,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_data_id_p",utc_data_control_sql_get_data_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_data_id_n",utc_data_control_sql_get_data_id_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_register_response_cb_p",utc_data_control_sql_register_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_register_response_cb_n",utc_data_control_sql_register_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unregister_response_cb_p",utc_data_control_sql_unregister_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_handle_id_p",utc_data_control_sql_get_handle_id_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_handle_id_n",utc_data_control_sql_get_handle_id_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_response_cb_p1",utc_data_control_sql_bind_response_cb_p1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_response_cb_p2",utc_data_control_sql_bind_response_cb_p2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_response_cb_p3",utc_data_control_sql_bind_response_cb_p3,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_response_cb_n",utc_data_control_sql_bind_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unbind_response_cb_p",utc_data_control_sql_unbind_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unbind_response_cb_n",utc_data_control_sql_unbind_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_p",utc_data_control_sql_insert_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_n1",utc_data_control_sql_insert_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_n2",utc_data_control_sql_insert_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_update_p",utc_data_control_sql_update_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_update_n1",utc_data_control_sql_update_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_update_n2",utc_data_control_sql_update_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_p",utc_data_control_sql_select_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_n1",utc_data_control_sql_select_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_n2",utc_data_control_sql_select_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_with_page_p",utc_data_control_sql_select_with_page_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_with_page_p2",utc_data_control_sql_select_with_page_p2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_with_page_n1",utc_data_control_sql_select_with_page_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_select_with_page_n2",utc_data_control_sql_select_with_page_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_delete_p",utc_data_control_sql_delete_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_delete_n1",utc_data_control_sql_delete_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_delete_n2",utc_data_control_sql_delete_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_blob_data_n",utc_data_control_sql_get_blob_data_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_column_count_n",utc_data_control_sql_get_column_count_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_column_item_size_n",utc_data_control_sql_get_column_item_size_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_column_item_type_n",utc_data_control_sql_get_column_item_type_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_column_name_n",utc_data_control_sql_get_column_name_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_double_data_n",utc_data_control_sql_get_double_data_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_int_data_n",utc_data_control_sql_get_int_data_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_int64_data_n",utc_data_control_sql_get_int64_data_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_get_text_data_n",utc_data_control_sql_get_text_data_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_step_first_n",utc_data_control_sql_step_first_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_step_last_n",utc_data_control_sql_step_last_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_step_next_n",utc_data_control_sql_step_next_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_step_previous_n",utc_data_control_sql_step_previous_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_bulk_data_p",utc_data_control_sql_insert_bulk_data_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_bulk_data_n1",utc_data_control_sql_insert_bulk_data_n1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_insert_bulk_data_n2",utc_data_control_sql_insert_bulk_data_n2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_register_insert_bulk_data_response_cb_p",utc_data_control_sql_register_insert_bulk_data_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_register_insert_bulk_data_response_cb_n",utc_data_control_sql_register_insert_bulk_data_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unregister_insert_bulk_data_response_cb_p",utc_data_control_sql_unregister_insert_bulk_data_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unregister_insert_bulk_data_response_cb_n",utc_data_control_sql_unregister_insert_bulk_data_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_insert_bulk_data_response_cb_p1",utc_data_control_sql_bind_insert_bulk_data_response_cb_p1,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_insert_bulk_data_response_cb_p2",utc_data_control_sql_bind_insert_bulk_data_response_cb_p2,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_insert_bulk_data_response_cb_p3",utc_data_control_sql_bind_insert_bulk_data_response_cb_p3,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_bind_insert_bulk_data_response_cb_n",utc_data_control_sql_bind_insert_bulk_data_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unbind_insert_bulk_data_response_cb_p",utc_data_control_sql_unbind_insert_bulk_data_response_cb_p,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_sql_unbind_insert_bulk_data_response_cb_n",utc_data_control_sql_unbind_insert_bulk_data_response_cb_n,utc_data_control_sql_startup,utc_data_control_sql_cleanup},
	{"utc_data_control_provider_create_select_statement_n",utc_data_control_provider_create_select_statement_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_create_insert_statement_n",utc_data_control_provider_create_insert_statement_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_create_delete_statement_n",utc_data_control_provider_create_delete_statement_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_create_update_statement_n",utc_data_control_provider_create_update_statement_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_get_client_appid_n",utc_data_control_provider_get_client_appid_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_delete_result_n",utc_data_control_provider_send_delete_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_error_n",utc_data_control_provider_send_error_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_insert_result_n",utc_data_control_provider_send_insert_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_map_get_value_result_n",utc_data_control_provider_send_map_get_value_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_map_result_n",utc_data_control_provider_send_map_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_select_result_n",utc_data_control_provider_send_select_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_update_result_n",utc_data_control_provider_send_update_result_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_register_cb_p",utc_data_control_provider_sql_register_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_register_cb_n",utc_data_control_provider_sql_register_cb_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_unregister_cb_p",utc_data_control_provider_sql_unregister_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_register_cb_p",utc_data_control_provider_map_register_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_register_cb_n",utc_data_control_provider_map_register_cb_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_unregister_cb_p",utc_data_control_provider_map_unregister_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_data_change_noti_p",utc_data_control_provider_send_data_change_noti_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_data_change_noti_n01",utc_data_control_provider_send_data_change_noti_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_data_change_noti_n02",utc_data_control_provider_send_data_change_noti_n02,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_add_data_change_consumer_filter_cb_p",utc_data_control_provider_add_data_change_consumer_filter_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_add_data_change_consumer_filter_cb_n01",utc_data_control_provider_add_data_change_consumer_filter_cb_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_add_data_change_consumer_filter_cb_n02",utc_data_control_provider_add_data_change_consumer_filter_cb_n02,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_remove_data_change_consumer_filter_cb_p",utc_data_control_provider_remove_data_change_consumer_filter_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_remove_data_change_consumer_filter_cb_n",utc_data_control_provider_remove_data_change_consumer_filter_cb_n,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_foreach_data_change_consumer_p",utc_data_control_provider_foreach_data_change_consumer_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_foreach_data_change_consumer_n01",utc_data_control_provider_foreach_data_change_consumer_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_foreach_data_change_consumer_n02",utc_data_control_provider_foreach_data_change_consumer_n02,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_bulk_insert_result_n01",utc_data_control_provider_send_bulk_insert_result_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_send_map_bulk_add_result_n01",utc_data_control_provider_send_map_bulk_add_result_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_register_insert_bulk_data_request_cb_p",utc_data_control_provider_sql_register_insert_bulk_data_request_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_register_insert_bulk_data_request_cb_n01",utc_data_control_provider_sql_register_insert_bulk_data_request_cb_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_sql_unregister_insert_bulk_data_request_cb_p",utc_data_control_provider_sql_unregister_insert_bulk_data_request_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_register_add_bulk_data_request_cb_p",utc_data_control_provider_map_register_add_bulk_data_request_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_register_add_bulk_data_request_cb_n01",utc_data_control_provider_map_register_add_bulk_data_request_cb_n01,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_provider_map_unregister_add_bulk_data_request_cb_p",utc_data_control_provider_map_unregister_add_bulk_data_request_cb_p,utc_data_control_provider_startup,utc_data_control_provider_cleanup},
	{"utc_data_control_add_data_change_cb_p",utc_data_control_add_data_change_cb_p,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_add_data_change_cb_n01",utc_data_control_add_data_change_cb_n01,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_add_data_change_cb_n02",utc_data_control_add_data_change_cb_n02,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_add_data_change_cb_n03",utc_data_control_add_data_change_cb_n03,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_add_data_change_cb_n04",utc_data_control_add_data_change_cb_n04,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_remove_data_change_cb_p",utc_data_control_remove_data_change_cb_p,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_remove_data_change_cb_n01",utc_data_control_remove_data_change_cb_n01,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_remove_data_change_cb_n02",utc_data_control_remove_data_change_cb_n02,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_remove_data_change_cb_n03",utc_data_control_remove_data_change_cb_n03,utc_data_control_noti_startup,utc_data_control_noti_cleanup},
	{"utc_data_control_bulk_data_get_data_p",utc_data_control_bulk_data_get_data_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_get_data_n01",utc_data_control_bulk_data_get_data_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_get_data_n02",utc_data_control_bulk_data_get_data_n02,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_get_count_p",utc_data_control_bulk_data_get_count_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_get_count_n01",utc_data_control_bulk_data_get_count_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_get_count_n02",utc_data_control_bulk_data_get_count_n02,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_add_p",utc_data_control_bulk_data_add_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_add_n01",utc_data_control_bulk_data_add_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_create_p",utc_data_control_bulk_data_create_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_create_n",utc_data_control_bulk_data_create_n,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_destroy_p",utc_data_control_bulk_data_destroy_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_data_destroy_n",utc_data_control_bulk_data_destroy_n,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_result_data_p",utc_data_control_bulk_result_data_get_result_data_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_result_data_n01",utc_data_control_bulk_result_data_get_result_data_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_result_data_n02",utc_data_control_bulk_result_data_get_result_data_n02,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_count_p",utc_data_control_bulk_result_data_get_count_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_count_n01",utc_data_control_bulk_result_data_get_count_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_get_count_n02",utc_data_control_bulk_result_data_get_count_n02,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_add_p",utc_data_control_bulk_result_data_add_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_add_n01",utc_data_control_bulk_result_data_add_n01,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_create_p",utc_data_control_bulk_result_data_create_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_create_n",utc_data_control_bulk_result_data_create_n,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_destroy_p",utc_data_control_bulk_result_data_destroy_p,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{"utc_data_control_bulk_result_data_destroy_n",utc_data_control_bulk_result_data_destroy_n,utc_data_control_bulk_startup,utc_data_control_bulk_cleanup},
	{NULL, NULL}
};

#endif // __TCT_DATA-CONTROL-NATIVE_H__
