//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_SMARTCARD-NATIVE_H__
#define __TCT_SMARTCARD-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_smartcard_service_startup(void);
extern void utc_smartcard_service_cleanup(void);
extern void utc_smartcard_reader_startup(void);
extern void utc_smartcard_reader_cleanup(void);
extern void utc_smartcard_session_startup(void);
extern void utc_smartcard_session_cleanup(void);
extern void utc_smartcard_channel_startup(void);
extern void utc_smartcard_channel_cleanup(void);

extern int utc_smartcard_smartcard_initialize_p(void);
extern int utc_smartcard_smartcard_deinitialize_p(void);
extern int utc_smartcard_smartcard_deinitialize_n(void);
extern int utc_smartcard_smartcard_get_version_p(void);
extern int utc_smartcard_smartcard_get_version_n(void);
extern int utc_smartcard_smartcard_get_readers_p(void);
extern int utc_smartcard_smartcard_get_readers_n(void);
extern int utc_smartcard_smartcard_reader_get_name_p(void);
extern int utc_smartcard_smartcard_reader_get_name_n(void);
extern int utc_smartcard_smartcard_reader_is_secure_element_present_p(void);
extern int utc_smartcard_smartcard_reader_is_secure_element_present_n(void);
extern int utc_smartcard_smartcard_reader_open_session_p(void);
extern int utc_smartcard_smartcard_reader_open_session_n(void);
extern int utc_smartcard_smartcard_reader_close_sessions_p(void);
extern int utc_smartcard_smartcard_reader_close_sessions_n(void);
extern int utc_smartcard_smartcard_reader_set_event_cb_p(void);
extern int utc_smartcard_smartcard_reader_set_event_cb_n(void);
extern int utc_smartcard_smartcard_session_get_reader_p(void);
extern int utc_smartcard_smartcard_session_get_reader_n(void);
extern int utc_smartcard_smartcard_session_get_atr_p(void);
extern int utc_smartcard_smartcard_session_get_atr_n(void);
extern int utc_smartcard_smartcard_session_close_p(void);
extern int utc_smartcard_smartcard_session_close_n(void);
extern int utc_smartcard_smartcard_session_is_closed_p(void);
extern int utc_smartcard_smartcard_session_is_closed_n(void);
extern int utc_smartcard_smartcard_session_close_channels_p(void);
extern int utc_smartcard_smartcard_session_close_channels_n(void);
extern int utc_smartcard_smartcard_session_open_basic_channel_n(void);
extern int utc_smartcard_smartcard_session_open_logical_channel_n(void);
extern int utc_smartcard_smartcard_channel_close_n(void);
extern int utc_smartcard_smartcard_channel_is_basic_channel_n(void);
extern int utc_smartcard_smartcard_channel_is_closed_n(void);
extern int utc_smartcard_smartcard_channel_get_select_response_n(void);
extern int utc_smartcard_smartcard_channel_get_session_n(void);
extern int utc_smartcard_smartcard_channel_transmit_n(void);
extern int utc_smartcard_smartcard_channel_transmit_retrieve_response_n(void);
extern int utc_smartcard_smartcard_channel_select_next_n(void);

testcase tc_array[] = {
	{"utc_smartcard_smartcard_initialize_p",utc_smartcard_smartcard_initialize_p,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_deinitialize_p",utc_smartcard_smartcard_deinitialize_p,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_deinitialize_n",utc_smartcard_smartcard_deinitialize_n,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_get_version_p",utc_smartcard_smartcard_get_version_p,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_get_version_n",utc_smartcard_smartcard_get_version_n,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_get_readers_p",utc_smartcard_smartcard_get_readers_p,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_get_readers_n",utc_smartcard_smartcard_get_readers_n,utc_smartcard_service_startup,utc_smartcard_service_cleanup},
	{"utc_smartcard_smartcard_reader_get_name_p",utc_smartcard_smartcard_reader_get_name_p,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_get_name_n",utc_smartcard_smartcard_reader_get_name_n,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_is_secure_element_present_p",utc_smartcard_smartcard_reader_is_secure_element_present_p,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_is_secure_element_present_n",utc_smartcard_smartcard_reader_is_secure_element_present_n,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_open_session_p",utc_smartcard_smartcard_reader_open_session_p,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_open_session_n",utc_smartcard_smartcard_reader_open_session_n,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_close_sessions_p",utc_smartcard_smartcard_reader_close_sessions_p,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_close_sessions_n",utc_smartcard_smartcard_reader_close_sessions_n,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_set_event_cb_p",utc_smartcard_smartcard_reader_set_event_cb_p,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_reader_set_event_cb_n",utc_smartcard_smartcard_reader_set_event_cb_n,utc_smartcard_reader_startup,utc_smartcard_reader_cleanup},
	{"utc_smartcard_smartcard_session_get_reader_p",utc_smartcard_smartcard_session_get_reader_p,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_get_reader_n",utc_smartcard_smartcard_session_get_reader_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_get_atr_p",utc_smartcard_smartcard_session_get_atr_p,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_get_atr_n",utc_smartcard_smartcard_session_get_atr_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_close_p",utc_smartcard_smartcard_session_close_p,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_close_n",utc_smartcard_smartcard_session_close_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_is_closed_p",utc_smartcard_smartcard_session_is_closed_p,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_is_closed_n",utc_smartcard_smartcard_session_is_closed_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_close_channels_p",utc_smartcard_smartcard_session_close_channels_p,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_close_channels_n",utc_smartcard_smartcard_session_close_channels_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_open_basic_channel_n",utc_smartcard_smartcard_session_open_basic_channel_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_session_open_logical_channel_n",utc_smartcard_smartcard_session_open_logical_channel_n,utc_smartcard_session_startup,utc_smartcard_session_cleanup},
	{"utc_smartcard_smartcard_channel_close_n",utc_smartcard_smartcard_channel_close_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_is_basic_channel_n",utc_smartcard_smartcard_channel_is_basic_channel_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_is_closed_n",utc_smartcard_smartcard_channel_is_closed_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_get_select_response_n",utc_smartcard_smartcard_channel_get_select_response_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_get_session_n",utc_smartcard_smartcard_channel_get_session_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_transmit_n",utc_smartcard_smartcard_channel_transmit_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_transmit_retrieve_response_n",utc_smartcard_smartcard_channel_transmit_retrieve_response_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{"utc_smartcard_smartcard_channel_select_next_n",utc_smartcard_smartcard_channel_select_next_n,utc_smartcard_channel_startup,utc_smartcard_channel_cleanup},
	{NULL, NULL}
};

#endif // __TCT_SMARTCARD-NATIVE_H__
