//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WEBKIT2-NATIVE_H__
#define __TCT_WEBKIT2-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_webkit_efl_startup(void);
extern void ITs_webkit_efl_cleanup(void);
extern void ITs_webkit_efl_autofill_startup(void);
extern void ITs_webkit_efl_autofill_cleanup(void);
extern void ITs_webkit_efl_context_startup(void);
extern void ITs_webkit_efl_context_cleanup(void);
extern void ITs_webkit_efl_context_form_startup(void);
extern void ITs_webkit_efl_context_form_cleanup(void);
extern void ITs_webkit_efl_context_web_startup(void);
extern void ITs_webkit_efl_context_web_cleanup(void);
extern void ITs_webkit_efl_cookies_startup(void);
extern void ITs_webkit_efl_cookies_cleanup(void);
extern void ITs_webkit_efl_error_startup(void);
extern void ITs_webkit_efl_error_cleanup(void);
extern void ITs_webkit_efl_desicion_startup(void);
extern void ITs_webkit_efl_desicion_cleanup(void);
extern void ITs_webkit_efl_settings_startup(void);
extern void ITs_webkit_efl_settings_cleanup(void);
extern void ITs_webkit_efl_view_startup(void);
extern void ITs_webkit_efl_view_cleanup(void);
extern void ITc_ewk_intercept_request_startup(void);
extern void ITc_ewk_intercept_request_cleanup(void);
extern void ITs_webkit_view_add_incognito_mode_startup(void);
extern void ITs_webkit_view_add_incognito_mode_cleanup(void);
extern void ITs_webkit_ewk_view_original_url_startup(void);
extern void ITs_webkit_ewk_view_original_url_cleanup(void);

extern int ITc_webkit_efl_ewk_init_p(void);
extern int ITc_webkit_efl_ewk_shutdown_p(void);
extern int ITc_ewk_back_forward_list_current_item_get_p(void);
extern int ITc_ewk_back_forward_list_previous_item_get_p(void);
extern int ITc_ewk_back_forward_list_next_item_get_p(void);
extern int ITc_ewk_back_forward_list_count_p(void);
extern int ITc_ewk_back_forward_list_item_at_index_get_p(void);
extern int ITc_ewk_back_forward_list_n_back_items_copy_p(void);
extern int ITc_ewk_back_forward_list_n_forward_items_copy_p(void);
extern int ITc_ewk_back_forward_list_item_ref_p(void);
extern int ITc_ewk_back_forward_list_item_unref_p(void);
extern int ITc_ewk_back_forward_list_item_url_get_p(void);
extern int ITc_ewk_back_forward_list_item_original_url_get_p(void);
extern int ITc_ewk_back_forward_list_item_title_get_p(void);
extern int ITc_ewk_autofill_profile_data_set_get_p(void);
extern int ITc_ewk_autofill_profile_new_delete_p(void);
extern int ITc_ewk_autofill_profile_id_get_p(void);
extern int ITc_ewk_context_cache_model_set_p(void);
extern int ITc_ewk_context_cache_model_get_p(void);
extern int ITc_ewk_context_cookie_manager_get_p(void);
extern int ITc_ewk_context_resource_cache_clear_p(void);
extern int ITc_ewk_context_icon_database_icon_object_add_p(void);
extern int ITc_ewk_context_application_cache_delete_all_p(void);
extern int ITc_ewk_context_form_autofill_profile_add_remove_p(void);
extern int ITc_ewk_context_form_autofill_profile_get_all_p(void);
extern int ITc_ewk_context_form_autofill_profile_set_p(void);
extern int ITc_ewk_context_form_autofill_profile_get_p(void);
extern int ITc_ewk_context_form_candidate_data_delete_all_p(void);
extern int ITc_ewk_context_form_password_data_delete_all_p(void);
extern int ITc_ewk_context_web_indexed_database_delete_all_p(void);
extern int ITc_ewk_context_web_storage_delete_all_p(void);
extern int ITc_ewk_cookie_manager_accept_policy_set_p(void);
extern int ITc_ewk_cookie_manager_accept_policy_async_get_p(void);
extern int ITc_ewk_cookie_manager_cookies_clear_p(void);
extern int ITc_ewk_cookie_manager_file_scheme_cookies_allow_set_get_p(void);
extern int ITc_ewk_cookie_manager_persistent_storage_set_p(void);
extern int ITc_ewk_error_url_get_p(void);
extern int ITc_ewk_error_code_get_p(void);
extern int ITc_ewk_error_description_get_p(void);
extern int ITc_ewk_error_cancellation_get_p(void);
extern int ITc_ewk_policy_decision_cookie_get_p(void);
extern int ITc_ewk_policy_decision_url_get_p(void);
extern int ITc_ewk_policy_decision_scheme_get_p(void);
extern int ITc_ewk_policy_decision_host_get_p(void);
extern int ITc_ewk_policy_decision_http_method_get_p(void);
extern int ITc_ewk_policy_decision_use_p(void);
extern int ITc_ewk_policy_decision_ignore_p(void);
extern int ITc_ewk_policy_decision_type_get_p(void);
extern int ITc_ewk_policy_decision_navigation_type_get_p(void);
extern int ITc_ewk_policy_decision_response_mime_get_p(void);
extern int ITc_ewk_policy_decision_response_headers_get_p(void);
extern int ITc_ewk_policy_decision_response_status_code_get_p(void);
extern int ITc_ewk_settings_auto_fitting_set_p(void);
extern int ITc_ewk_settings_auto_fitting_get_p(void);
extern int ITc_ewk_settings_javascript_enabled_set_p(void);
extern int ITc_ewk_settings_javascript_enabled_get_p(void);
extern int ITc_ewk_settings_loads_images_automatically_set_p(void);
extern int ITc_ewk_settings_loads_images_automatically_get_p(void);
extern int ITc_ewk_settings_default_text_encoding_name_set_p(void);
extern int ITc_ewk_settings_default_text_encoding_name_get_p(void);
extern int ITc_ewk_settings_default_font_size_set_p(void);
extern int ITc_ewk_settings_default_font_size_get_p(void);
extern int ITc_ewk_settings_scripts_can_open_windows_set_p(void);
extern int ITc_ewk_settings_scripts_can_open_windows_get_p(void);
extern int ITc_ewk_settings_form_candidate_data_enabled_set_p(void);
extern int ITc_ewk_settings_form_profile_data_enabled_set_p(void);
extern int ITc_ewk_settings_autofill_password_form_enabled_set_p(void);
extern int ITc_ewk_view_add_p(void);
extern int ITc_ewk_view_context_get_p(void);
extern int ITc_ewk_view_url_get_p(void);
extern int ITc_ewk_view_url_set_p(void);
extern int ITc_ewk_view_reload_p(void);
extern int ITc_ewk_view_stop_p(void);
extern int ITc_ewk_view_settings_get_p(void);
extern int ITc_ewk_view_back_p(void);
extern int ITc_ewk_view_forward_p(void);
extern int ITc_ewk_view_back_possible_p(void);
extern int ITc_ewk_view_forward_possible_p(void);
extern int ITc_ewk_view_back_forward_list_clear_p(void);
extern int ITc_ewk_view_back_forward_list_get_p(void);
extern int ITc_ewk_view_title_get_p(void);
extern int ITc_ewk_view_load_progress_get_p(void);
extern int ITc_ewk_view_user_agent_set_p(void);
extern int ITc_ewk_view_user_agent_get_p(void);
extern int ITc_ewk_view_contents_size_get_p(void);
extern int ITc_ewk_view_script_execute_p(void);
extern int ITc_ewk_view_scale_set_p(void);
extern int ITc_ewk_view_scale_get_p(void);
extern int ITc_ewk_view_fullscreen_exit_p(void);
extern int ITc_ewk_view_suspend_p(void);
extern int ITc_ewk_view_resume_p(void);
extern int ITc_ewk_view_url_request_set_p(void);
extern int ITc_ewk_view_contents_set_p(void);
extern int ITc_ewk_view_scroll_by_p(void);
extern int ITc_ewk_view_scroll_pos_get_p(void);
extern int ITc_ewk_view_scroll_set_p(void);
extern int ITc_ewk_view_text_find_p(void);
extern int ITc_ewk_view_orientation_send_p(void);
extern int ITc_ewk_view_text_selection_clear_p(void);
extern int ITc_ewk_view_text_selection_text_get_p(void);
extern int ITc_ewk_view_visibility_set_p(void);
extern int ITc_ewk_view_html_string_load_p(void);
extern int ITc_ewk_view_evaluate_javascript_p(void);
extern int ITc_ewk_view_javascript_message_handler_add_p(void);
extern int ITc_ewk_context_intercept_request_callback_set_p(void);
extern int ITc_ewk_view_focus_set_get_p(void);
extern int ITc_ewk_intercept_request_http_method_get_p(void);
extern int ITc_ewk_intercept_request_header_get_p(void);
extern int ITc_ewk_intercept_request_ignore_p(void);
extern int ITc_ewk_intercept_request_url_get_p(void);
extern int ITc_ewk_intercept_request_response_body_set_p(void);
extern int ITc_ewk_intercept_request_response_header_add_p(void);
extern int ITc_ewk_intercept_request_response_header_map_add_p(void);
extern int ITc_ewk_intercept_request_response_set_p(void);
extern int ITc_ewk_intercept_request_response_status_set_p(void);
extern int ITc_ewk_intercept_request_response_write_chunk_p(void);
extern int ITc_webkit_ewk_view_add_in_incognito_mode_p(void);
extern int ITc_webkit_ewk_view_original_url_p(void);
extern int ITc_ewk_context_background_music_get_set_p(void);
extern int ITc_ewk_context_block_multimedia_on_call_get_set_p(void);
extern int ITc_ewk_context_rotation_lock_get_set_p(void);
extern int ITc_ewk_context_sound_overlap_get_set_p(void);


testcase tc_array[] = {
	{"ITc_webkit_efl_ewk_init_p",ITc_webkit_efl_ewk_init_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_webkit_efl_ewk_shutdown_p",ITc_webkit_efl_ewk_shutdown_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_current_item_get_p",ITc_ewk_back_forward_list_current_item_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_previous_item_get_p",ITc_ewk_back_forward_list_previous_item_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_next_item_get_p",ITc_ewk_back_forward_list_next_item_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_count_p",ITc_ewk_back_forward_list_count_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_at_index_get_p",ITc_ewk_back_forward_list_item_at_index_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_n_back_items_copy_p",ITc_ewk_back_forward_list_n_back_items_copy_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_n_forward_items_copy_p",ITc_ewk_back_forward_list_n_forward_items_copy_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_ref_p",ITc_ewk_back_forward_list_item_ref_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_unref_p",ITc_ewk_back_forward_list_item_unref_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_url_get_p",ITc_ewk_back_forward_list_item_url_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_original_url_get_p",ITc_ewk_back_forward_list_item_original_url_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_back_forward_list_item_title_get_p",ITc_ewk_back_forward_list_item_title_get_p,ITs_webkit_efl_startup,ITs_webkit_efl_cleanup},
	{"ITc_ewk_autofill_profile_data_set_get_p",ITc_ewk_autofill_profile_data_set_get_p,ITs_webkit_efl_autofill_startup,ITs_webkit_efl_autofill_cleanup},
	{"ITc_ewk_autofill_profile_new_delete_p",ITc_ewk_autofill_profile_new_delete_p,ITs_webkit_efl_autofill_startup,ITs_webkit_efl_autofill_cleanup},
	{"ITc_ewk_autofill_profile_id_get_p",ITc_ewk_autofill_profile_id_get_p,ITs_webkit_efl_autofill_startup,ITs_webkit_efl_autofill_cleanup},
	{"ITc_ewk_context_cache_model_set_p",ITc_ewk_context_cache_model_set_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_cache_model_get_p",ITc_ewk_context_cache_model_get_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_cookie_manager_get_p",ITc_ewk_context_cookie_manager_get_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_resource_cache_clear_p",ITc_ewk_context_resource_cache_clear_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_icon_database_icon_object_add_p",ITc_ewk_context_icon_database_icon_object_add_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_application_cache_delete_all_p",ITc_ewk_context_application_cache_delete_all_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_form_autofill_profile_add_remove_p",ITc_ewk_context_form_autofill_profile_add_remove_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_form_autofill_profile_get_all_p",ITc_ewk_context_form_autofill_profile_get_all_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_form_autofill_profile_set_p",ITc_ewk_context_form_autofill_profile_set_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_form_autofill_profile_get_p",ITc_ewk_context_form_autofill_profile_get_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_form_candidate_data_delete_all_p",ITc_ewk_context_form_candidate_data_delete_all_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_form_password_data_delete_all_p",ITc_ewk_context_form_password_data_delete_all_p,ITs_webkit_efl_context_form_startup,ITs_webkit_efl_context_form_cleanup},
	{"ITc_ewk_context_web_indexed_database_delete_all_p",ITc_ewk_context_web_indexed_database_delete_all_p,ITs_webkit_efl_context_web_startup,ITs_webkit_efl_context_web_cleanup},
	{"ITc_ewk_context_web_storage_delete_all_p",ITc_ewk_context_web_storage_delete_all_p,ITs_webkit_efl_context_web_startup,ITs_webkit_efl_context_web_cleanup},
	{"ITc_ewk_cookie_manager_accept_policy_set_p",ITc_ewk_cookie_manager_accept_policy_set_p,ITs_webkit_efl_cookies_startup,ITs_webkit_efl_cookies_cleanup},
	{"ITc_ewk_cookie_manager_accept_policy_async_get_p",ITc_ewk_cookie_manager_accept_policy_async_get_p,ITs_webkit_efl_cookies_startup,ITs_webkit_efl_cookies_cleanup},
	{"ITc_ewk_cookie_manager_cookies_clear_p",ITc_ewk_cookie_manager_cookies_clear_p,ITs_webkit_efl_cookies_startup,ITs_webkit_efl_cookies_cleanup},
	{"ITc_ewk_cookie_manager_file_scheme_cookies_allow_set_get_p",ITc_ewk_cookie_manager_file_scheme_cookies_allow_set_get_p,ITs_webkit_efl_cookies_startup,ITs_webkit_efl_cookies_cleanup},
	{"ITc_ewk_cookie_manager_persistent_storage_set_p",ITc_ewk_cookie_manager_persistent_storage_set_p,ITs_webkit_efl_cookies_startup,ITs_webkit_efl_cookies_cleanup},
	{"ITc_ewk_error_url_get_p",ITc_ewk_error_url_get_p,ITs_webkit_efl_error_startup,ITs_webkit_efl_error_cleanup},
	{"ITc_ewk_error_code_get_p",ITc_ewk_error_code_get_p,ITs_webkit_efl_error_startup,ITs_webkit_efl_error_cleanup},
	{"ITc_ewk_error_description_get_p",ITc_ewk_error_description_get_p,ITs_webkit_efl_error_startup,ITs_webkit_efl_error_cleanup},
	{"ITc_ewk_error_cancellation_get_p",ITc_ewk_error_cancellation_get_p,ITs_webkit_efl_error_startup,ITs_webkit_efl_error_cleanup},
	{"ITc_ewk_policy_decision_cookie_get_p",ITc_ewk_policy_decision_cookie_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_url_get_p",ITc_ewk_policy_decision_url_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_scheme_get_p",ITc_ewk_policy_decision_scheme_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_host_get_p",ITc_ewk_policy_decision_host_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_http_method_get_p",ITc_ewk_policy_decision_http_method_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_use_p",ITc_ewk_policy_decision_use_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_ignore_p",ITc_ewk_policy_decision_ignore_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_type_get_p",ITc_ewk_policy_decision_type_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_navigation_type_get_p",ITc_ewk_policy_decision_navigation_type_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_response_mime_get_p",ITc_ewk_policy_decision_response_mime_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_response_headers_get_p",ITc_ewk_policy_decision_response_headers_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_policy_decision_response_status_code_get_p",ITc_ewk_policy_decision_response_status_code_get_p,ITs_webkit_efl_desicion_startup,ITs_webkit_efl_desicion_cleanup},
	{"ITc_ewk_settings_auto_fitting_set_p",ITc_ewk_settings_auto_fitting_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_auto_fitting_get_p",ITc_ewk_settings_auto_fitting_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_javascript_enabled_set_p",ITc_ewk_settings_javascript_enabled_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_javascript_enabled_get_p",ITc_ewk_settings_javascript_enabled_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_loads_images_automatically_set_p",ITc_ewk_settings_loads_images_automatically_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_loads_images_automatically_get_p",ITc_ewk_settings_loads_images_automatically_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_default_text_encoding_name_set_p",ITc_ewk_settings_default_text_encoding_name_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_default_text_encoding_name_get_p",ITc_ewk_settings_default_text_encoding_name_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_default_font_size_set_p",ITc_ewk_settings_default_font_size_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_default_font_size_get_p",ITc_ewk_settings_default_font_size_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_scripts_can_open_windows_set_p",ITc_ewk_settings_scripts_can_open_windows_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_scripts_can_open_windows_get_p",ITc_ewk_settings_scripts_can_open_windows_get_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_form_candidate_data_enabled_set_p",ITc_ewk_settings_form_candidate_data_enabled_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_form_profile_data_enabled_set_p",ITc_ewk_settings_form_profile_data_enabled_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_settings_autofill_password_form_enabled_set_p",ITc_ewk_settings_autofill_password_form_enabled_set_p,ITs_webkit_efl_settings_startup,ITs_webkit_efl_settings_cleanup},
	{"ITc_ewk_view_add_p",ITc_ewk_view_add_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_context_get_p",ITc_ewk_view_context_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_url_get_p",ITc_ewk_view_url_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_url_set_p",ITc_ewk_view_url_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_reload_p",ITc_ewk_view_reload_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_stop_p",ITc_ewk_view_stop_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_settings_get_p",ITc_ewk_view_settings_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_back_p",ITc_ewk_view_back_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_forward_p",ITc_ewk_view_forward_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_back_possible_p",ITc_ewk_view_back_possible_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_forward_possible_p",ITc_ewk_view_forward_possible_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_back_forward_list_clear_p",ITc_ewk_view_back_forward_list_clear_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_back_forward_list_get_p",ITc_ewk_view_back_forward_list_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_title_get_p",ITc_ewk_view_title_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_load_progress_get_p",ITc_ewk_view_load_progress_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_user_agent_set_p",ITc_ewk_view_user_agent_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_user_agent_get_p",ITc_ewk_view_user_agent_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_contents_size_get_p",ITc_ewk_view_contents_size_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_script_execute_p",ITc_ewk_view_script_execute_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_scale_set_p",ITc_ewk_view_scale_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_scale_get_p",ITc_ewk_view_scale_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_fullscreen_exit_p",ITc_ewk_view_fullscreen_exit_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_suspend_p",ITc_ewk_view_suspend_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_resume_p",ITc_ewk_view_resume_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_url_request_set_p",ITc_ewk_view_url_request_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_contents_set_p",ITc_ewk_view_contents_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_scroll_by_p",ITc_ewk_view_scroll_by_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_scroll_pos_get_p",ITc_ewk_view_scroll_pos_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_scroll_set_p",ITc_ewk_view_scroll_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_text_find_p",ITc_ewk_view_text_find_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_orientation_send_p",ITc_ewk_view_orientation_send_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_text_selection_clear_p",ITc_ewk_view_text_selection_clear_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_text_selection_text_get_p",ITc_ewk_view_text_selection_text_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_visibility_set_p",ITc_ewk_view_visibility_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_html_string_load_p",ITc_ewk_view_html_string_load_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_evaluate_javascript_p",ITc_ewk_view_evaluate_javascript_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_javascript_message_handler_add_p",ITc_ewk_view_javascript_message_handler_add_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_context_intercept_request_callback_set_p",ITc_ewk_context_intercept_request_callback_set_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_view_focus_set_get_p",ITc_ewk_view_focus_set_get_p,ITs_webkit_efl_view_startup,ITs_webkit_efl_view_cleanup},
	{"ITc_ewk_intercept_request_http_method_get_p",ITc_ewk_intercept_request_http_method_get_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_header_get_p",ITc_ewk_intercept_request_header_get_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_ignore_p",ITc_ewk_intercept_request_ignore_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_url_get_p",ITc_ewk_intercept_request_url_get_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_body_set_p",ITc_ewk_intercept_request_response_body_set_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_header_add_p",ITc_ewk_intercept_request_response_header_add_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_header_map_add_p",ITc_ewk_intercept_request_response_header_map_add_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_set_p",ITc_ewk_intercept_request_response_set_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_status_set_p",ITc_ewk_intercept_request_response_status_set_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_ewk_intercept_request_response_write_chunk_p",ITc_ewk_intercept_request_response_write_chunk_p,ITc_ewk_intercept_request_startup,ITc_ewk_intercept_request_cleanup},
	{"ITc_webkit_ewk_view_add_in_incognito_mode_p",ITc_webkit_ewk_view_add_in_incognito_mode_p,ITs_webkit_view_add_incognito_mode_startup,ITs_webkit_view_add_incognito_mode_cleanup},
	{"ITc_webkit_ewk_view_original_url_p",ITc_webkit_ewk_view_original_url_p,ITs_webkit_ewk_view_original_url_startup,ITs_webkit_ewk_view_original_url_cleanup},
	{"ITc_ewk_context_background_music_get_set_p",ITc_ewk_context_background_music_get_set_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_block_multimedia_on_call_get_set_p",ITc_ewk_context_block_multimedia_on_call_get_set_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_rotation_lock_get_set_p",ITc_ewk_context_rotation_lock_get_set_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},
	{"ITc_ewk_context_sound_overlap_get_set_p",ITc_ewk_context_sound_overlap_get_set_p,ITs_webkit_efl_context_startup,ITs_webkit_efl_context_cleanup},

	{NULL, NULL}
};

#endif // __TCT_WEBKIT2-NATIVE_H__
