//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WIDGET_SERVICE-NATIVE_H__
#define __TCT_WIDGET_SERVICE-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_widget_service_startup(void);
extern void utc_widget_service_cleanup(void);

extern int utc_widget_service_get_size_n(void);
extern int utc_widget_service_get_size_type_n(void);
extern int utc_widget_service_get_need_of_mouse_event_n(void);
extern int utc_widget_service_get_need_of_touch_effect_n(void);
extern int utc_widget_service_get_need_of_frame_n(void);
extern int utc_widget_service_trigger_update_n(void);
extern int utc_widget_service_change_period_n(void);
extern int utc_widget_service_get_widget_list_n(void);
extern int utc_widget_service_get_main_app_id_n(void);
extern int utc_widget_service_get_widget_list_by_pkgid_n(void);
extern int utc_widget_service_get_widget_id_n(void);
extern int utc_widget_service_get_app_id_of_setup_app_n(void);
extern int utc_widget_service_get_package_id_n(void);
extern int utc_widget_service_get_name_n(void);
extern int utc_widget_service_get_preview_image_path_n(void);
extern int utc_widget_service_get_icon_n(void);
extern int utc_widget_service_get_nodisplay_n(void);
extern int utc_widget_service_get_supported_sizes_n(void);
extern int utc_widget_service_get_supported_size_types_n(void);
extern int utc_widget_service_get_widget_instance_list_n(void);
extern int utc_widget_service_set_lifecycle_event_cb_n(void);
extern int utc_widget_service_unset_lifecycle_event_cb_n(void);
extern int utc_widget_service_get_content_of_widget_instance_n(void);
extern int utc_widget_service_get_size_p(void);
extern int utc_widget_service_get_size_type_p(void);
extern int utc_widget_service_get_need_of_mouse_event_p(void);
extern int utc_widget_service_get_need_of_touch_effect_p(void);
extern int utc_widget_service_get_need_of_frame_p(void);
extern int utc_widget_service_get_widget_list_p(void);
extern int utc_widget_service_get_main_app_id_p(void);
extern int utc_widget_service_get_widget_list_by_pkgid_p(void);
extern int utc_widget_service_get_widget_id_p(void);
extern int utc_widget_service_get_app_id_of_setup_app_p(void);
extern int utc_widget_service_get_package_id_p(void);
extern int utc_widget_service_get_name_p(void);
extern int utc_widget_service_get_preview_image_path_p(void);
extern int utc_widget_service_get_icon_p(void);
extern int utc_widget_service_get_nodisplay_p(void);
extern int utc_widget_service_get_supported_sizes_p(void);
extern int utc_widget_service_get_supported_size_types_p(void);
extern int utc_widget_service_set_lifecycle_event_cb_p(void);
extern int utc_widget_service_unset_lifecycle_event_cb_p(void);
extern int utc_widget_service_set_disable_event_cb_p(void);
extern int utc_widget_service_set_disable_event_cb_n(void);
extern int utc_widget_service_unset_disable_event_cb_p(void);
extern int utc_widget_service_unset_disable_event_cb_n(void);
extern int utc_widget_service_get_widget_disabled_p(void);
extern int utc_widget_service_get_widget_disabled_n(void);
extern int utc_widget_service_set_widget_disabled_n(void);
extern int utc_widget_service_set_widget_disabled_n2(void);

testcase tc_array[] = {
	{"utc_widget_service_get_size_n",utc_widget_service_get_size_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_size_type_n",utc_widget_service_get_size_type_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_mouse_event_n",utc_widget_service_get_need_of_mouse_event_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_touch_effect_n",utc_widget_service_get_need_of_touch_effect_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_frame_n",utc_widget_service_get_need_of_frame_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_trigger_update_n",utc_widget_service_trigger_update_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_change_period_n",utc_widget_service_change_period_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_list_n",utc_widget_service_get_widget_list_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_main_app_id_n",utc_widget_service_get_main_app_id_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_list_by_pkgid_n",utc_widget_service_get_widget_list_by_pkgid_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_id_n",utc_widget_service_get_widget_id_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_app_id_of_setup_app_n",utc_widget_service_get_app_id_of_setup_app_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_package_id_n",utc_widget_service_get_package_id_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_name_n",utc_widget_service_get_name_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_preview_image_path_n",utc_widget_service_get_preview_image_path_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_icon_n",utc_widget_service_get_icon_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_nodisplay_n",utc_widget_service_get_nodisplay_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_supported_sizes_n",utc_widget_service_get_supported_sizes_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_supported_size_types_n",utc_widget_service_get_supported_size_types_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_instance_list_n",utc_widget_service_get_widget_instance_list_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_lifecycle_event_cb_n",utc_widget_service_set_lifecycle_event_cb_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_unset_lifecycle_event_cb_n",utc_widget_service_unset_lifecycle_event_cb_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_content_of_widget_instance_n",utc_widget_service_get_content_of_widget_instance_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_size_p",utc_widget_service_get_size_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_size_type_p",utc_widget_service_get_size_type_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_mouse_event_p",utc_widget_service_get_need_of_mouse_event_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_touch_effect_p",utc_widget_service_get_need_of_touch_effect_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_need_of_frame_p",utc_widget_service_get_need_of_frame_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_list_p",utc_widget_service_get_widget_list_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_main_app_id_p",utc_widget_service_get_main_app_id_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_list_by_pkgid_p",utc_widget_service_get_widget_list_by_pkgid_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_id_p",utc_widget_service_get_widget_id_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_app_id_of_setup_app_p",utc_widget_service_get_app_id_of_setup_app_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_package_id_p",utc_widget_service_get_package_id_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_name_p",utc_widget_service_get_name_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_preview_image_path_p",utc_widget_service_get_preview_image_path_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_icon_p",utc_widget_service_get_icon_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_nodisplay_p",utc_widget_service_get_nodisplay_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_supported_sizes_p",utc_widget_service_get_supported_sizes_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_supported_size_types_p",utc_widget_service_get_supported_size_types_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_lifecycle_event_cb_p",utc_widget_service_set_lifecycle_event_cb_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_unset_lifecycle_event_cb_p",utc_widget_service_unset_lifecycle_event_cb_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_disable_event_cb_p",utc_widget_service_set_disable_event_cb_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_disable_event_cb_n",utc_widget_service_set_disable_event_cb_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_unset_disable_event_cb_p",utc_widget_service_unset_disable_event_cb_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_unset_disable_event_cb_n",utc_widget_service_unset_disable_event_cb_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_disabled_p",utc_widget_service_get_widget_disabled_p,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_get_widget_disabled_n",utc_widget_service_get_widget_disabled_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_widget_disabled_n",utc_widget_service_set_widget_disabled_n,utc_widget_service_startup,utc_widget_service_cleanup},
	{"utc_widget_service_set_widget_disabled_n2",utc_widget_service_set_widget_disabled_n2,utc_widget_service_startup,utc_widget_service_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WIDGET_SERVICE-NATIVE_H__
