//
// Copyright (c) 2018 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WATCHFACE-COMPLICATION-NATIVE_H__
#define __TCT_WATCHFACE-COMPLICATION-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_watchface_complication_provider_startup(void);
extern void ITs_watchface_complication_provider_cleanup(void);
extern int ITc_watchface_complication_provider_timeinfo_create_destroy_p(void);
extern int ITc_watchface_complication_provider_data_set_timeinfo_p(void);
extern int ITc_watchface_complication_provider_timeinfo_set_timezone_p(void);
extern int ITc_watchface_complication_provider_timeinfo_set_timezone_id_p(void);
extern int ITc_watchface_complication_provider_timeinfo_set_timezone_country_p(void);
extern int ITc_watchface_complication_provider_timeinfo_set_timezone_city_p(void);
extern int ITc_watchface_complication_provider_add_remove_update_requested_cb_p(void);
extern int ITc_watchface_complication_provider_notify_update_p(void);
extern int ITc_watchface_complication_provider_setup_get_context_p(void);
extern int ITc_watchface_complication_provider_setup_reply_to_editor_p(void);
extern int ITc_watchface_complication_provider_setup_is_editing_p(void);
extern int ITc_watchface_complication_provider_data_set_short_text_p(void);
extern int ITc_watchface_complication_provider_data_set_long_text_p(void);
extern int ITc_watchface_complication_provider_data_set_title_p(void);
extern int ITc_watchface_complication_provider_data_set_image_path_p(void);
extern int ITc_watchface_complication_provider_data_set_ranged_value_p(void);
extern int ITc_watchface_complication_provider_data_set_icon_path_p(void);
extern int ITc_watchface_complication_provider_data_set_extra_data_p(void);
extern int ITc_watchface_complication_provider_event_get_type_p(void);
extern int ITc_watchface_complication_provider_event_get_provider_id_p(void);
extern int ITc_watchface_complication_provider_event_get_complication_type_p(void);
extern int ITc_watchface_complication_provider_event_get_context_p(void);
extern int ITc_watchface_complication_provider_data_set_screen_reader_text_p(void);
extern int ITc_watchface_complication_provider_data_is_valid_p(void);

extern void ITs_watchface_complication_startup(void);
extern void ITs_watchface_complication_cleanup(void);
extern int ITc_watchface_complication_data_get_timeinfo_p(void);
extern int ITc_watchface_complication_timeinfo_get_timezone_p(void);
extern int ITc_watchface_complication_timeinfo_get_timezone_id_p(void);
extern int ITc_watchface_complication_timeinfo_get_timezone_country_p(void);
extern int ITc_watchface_complication_timeinfo_get_timezone_city_p(void);
extern int ITc_watchface_complication_timeinfo_get_timestamp_p(void);
extern int ITc_watchface_complication_timeinfo_destroy_p(void);
extern int ITc_watchface_complication_get_current_provider_id_p(void);
extern int ITc_watchface_complication_get_current_type_p(void);
extern int ITc_watchface_complication_create_destroy_p(void);
extern int ITc_watchface_complication_data_get_type_p(void);
extern int ITc_watchface_complication_data_get_long_text_p(void);
extern int ITc_watchface_complication_data_get_short_text_p(void);
extern int ITc_watchface_complication_data_get_title_p(void);
extern int ITc_watchface_complication_data_get_image_path_p(void);
extern int ITc_watchface_complication_data_get_ranged_value_p(void);
extern int ITc_watchface_complication_data_get_icon_path_p(void);
extern int ITc_watchface_complication_data_get_extra_data_p(void);
extern int ITc_watchface_complication_allowed_list_create_destroy_p(void);
extern int ITc_watchface_complication_allowed_list_add_delete_p(void);
extern int ITc_watchface_complication_allowed_list_get_nth_p(void);
extern int ITc_watchface_complication_allowed_list_apply_clear_p(void);
extern int ITc_watchface_complication_add_update_remove_updated_cb_p(void);
extern int ITc_watchface_complication_data_get_screen_reader_text_p(void);
extern int ITc_watchface_complication_transfer_event_p(void);

extern void ITs_watchface_editable_startup(void);
extern void ITs_watchface_editable_cleanup(void);
extern int ITc_watchface_editable_candidates_list_create_add_destroy_p(void);
extern int ITc_watchface_editable_add_complication_p(void);
extern int ITc_watchface_editable_get_nth_data_p(void);
extern int ITc_watchface_editable_add_design_element_p(void);
extern int ITc_watchface_editable_request_edit_p(void);
extern int ITc_watchface_editable_add_remove_edit_ready_cb_p(void);
extern int ITc_watchface_editable_get_current_data_p(void);
extern int ITc_watchface_editable_get_current_data_idx_p(void);
extern int ITc_watchface_editable_get_editable_id_p(void);
extern int ITc_watchface_editable_load_current_data_p(void);
extern int ITc_watchface_editable_set_editable_name_p(void);
extern int ITc_watchface_editable_get_editable_name_p(void);
extern int ITc_watchface_editable_get_highlight_p(void);
extern int ITc_watchface_editable_set_get_geometry_p(void);
extern int ITc_watchface_editable_highlight_set_get_shape_type_p(void);
extern int ITc_watchface_editable_highlight_create_destroy_p(void);

testcase tc_array[] = {
	{"ITc_watchface_complication_provider_timeinfo_create_destroy_p", ITc_watchface_complication_provider_timeinfo_create_destroy_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_timeinfo_p", ITc_watchface_complication_provider_data_set_timeinfo_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_timeinfo_set_timezone_p", ITc_watchface_complication_provider_timeinfo_set_timezone_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_timeinfo_set_timezone_id_p", ITc_watchface_complication_provider_timeinfo_set_timezone_id_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_timeinfo_set_timezone_country_p", ITc_watchface_complication_provider_timeinfo_set_timezone_country_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_timeinfo_set_timezone_city_p", ITc_watchface_complication_provider_timeinfo_set_timezone_city_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_add_remove_update_requested_cb_p", ITc_watchface_complication_provider_add_remove_update_requested_cb_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_notify_update_p", ITc_watchface_complication_provider_notify_update_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_setup_reply_to_editor_p", ITc_watchface_complication_provider_setup_reply_to_editor_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_setup_is_editing_p", ITc_watchface_complication_provider_setup_is_editing_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_setup_get_context_p", ITc_watchface_complication_provider_setup_get_context_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_short_text_p", ITc_watchface_complication_provider_data_set_short_text_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_long_text_p", ITc_watchface_complication_provider_data_set_long_text_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_title_p", ITc_watchface_complication_provider_data_set_title_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_image_path_p", ITc_watchface_complication_provider_data_set_image_path_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_ranged_value_p", ITc_watchface_complication_provider_data_set_ranged_value_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_icon_path_p", ITc_watchface_complication_provider_data_set_icon_path_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_extra_data_p", ITc_watchface_complication_provider_data_set_extra_data_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_event_get_type_p", ITc_watchface_complication_provider_event_get_type_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_event_get_provider_id_p", ITc_watchface_complication_provider_event_get_provider_id_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_event_get_complication_type_p", ITc_watchface_complication_provider_event_get_complication_type_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_event_get_context_p", ITc_watchface_complication_provider_event_get_context_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_set_screen_reader_text_p", ITc_watchface_complication_provider_data_set_screen_reader_text_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_provider_data_is_valid_p", ITc_watchface_complication_provider_data_is_valid_p, ITs_watchface_complication_provider_startup, ITs_watchface_complication_provider_cleanup},
	{"ITc_watchface_complication_data_get_timeinfo_p", ITc_watchface_complication_data_get_timeinfo_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_get_timezone_p", ITc_watchface_complication_timeinfo_get_timezone_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_get_timezone_id_p", ITc_watchface_complication_timeinfo_get_timezone_id_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_get_timezone_country_p", ITc_watchface_complication_timeinfo_get_timezone_country_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_get_timezone_city_p", ITc_watchface_complication_timeinfo_get_timezone_city_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_get_timestamp_p", ITc_watchface_complication_timeinfo_get_timestamp_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_timeinfo_destroy_p", ITc_watchface_complication_timeinfo_destroy_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_get_current_provider_id_p", ITc_watchface_complication_get_current_provider_id_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_get_current_type_p", ITc_watchface_complication_get_current_type_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_create_destroy_p", ITc_watchface_complication_create_destroy_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_type_p", ITc_watchface_complication_data_get_type_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_long_text_p", ITc_watchface_complication_data_get_long_text_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_short_text_p", ITc_watchface_complication_data_get_short_text_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_image_path_p", ITc_watchface_complication_data_get_image_path_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_ranged_value_p", ITc_watchface_complication_data_get_ranged_value_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_icon_path_p", ITc_watchface_complication_data_get_icon_path_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_extra_data_p", ITc_watchface_complication_data_get_extra_data_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_allowed_list_create_destroy_p", ITc_watchface_complication_allowed_list_create_destroy_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_allowed_list_add_delete_p", ITc_watchface_complication_allowed_list_add_delete_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_allowed_list_get_nth_p", ITc_watchface_complication_allowed_list_get_nth_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_allowed_list_apply_clear_p", ITc_watchface_complication_allowed_list_apply_clear_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_title_p", ITc_watchface_complication_data_get_title_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_add_update_remove_updated_cb_p", ITc_watchface_complication_add_update_remove_updated_cb_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_data_get_screen_reader_text_p", ITc_watchface_complication_data_get_screen_reader_text_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_complication_transfer_event_p", ITc_watchface_complication_transfer_event_p, ITs_watchface_complication_startup, ITs_watchface_complication_cleanup},
	{"ITc_watchface_editable_candidates_list_create_add_destroy_p", ITc_watchface_editable_candidates_list_create_add_destroy_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_add_complication_p", ITc_watchface_editable_add_complication_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_nth_data_p", ITc_watchface_editable_get_nth_data_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_add_design_element_p", ITc_watchface_editable_add_design_element_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_request_edit_p", ITc_watchface_editable_request_edit_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_add_remove_edit_ready_cb_p", ITc_watchface_editable_add_remove_edit_ready_cb_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_current_data_p", ITc_watchface_editable_get_current_data_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_current_data_idx_p", ITc_watchface_editable_get_current_data_idx_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_editable_id_p", ITc_watchface_editable_get_editable_id_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_load_current_data_p", ITc_watchface_editable_load_current_data_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_set_editable_name_p", ITc_watchface_editable_set_editable_name_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_editable_name_p", ITc_watchface_editable_get_editable_name_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_get_highlight_p", ITc_watchface_editable_get_highlight_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_set_get_geometry_p", ITc_watchface_editable_set_get_geometry_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_highlight_set_get_shape_type_p", ITc_watchface_editable_highlight_set_get_shape_type_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{"ITc_watchface_editable_highlight_create_destroy_p", ITc_watchface_editable_highlight_create_destroy_p, ITs_watchface_editable_startup, ITs_watchface_editable_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WATCHFACE-COMPLICATION-NATIVE_H__
