//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_APP-MANAGER-NATIVE_H__
#define __TCT_APP-MANAGER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_app_manager_startup(void);
extern void utc_app_manager_cleanup(void);

extern int utc_app_manager_app_context_clone_p(void);
extern int utc_app_manager_app_context_clone_n(void);
extern int utc_app_manager_app_context_destroy_p(void);
extern int utc_app_manager_app_context_destroy_n(void);
extern int utc_app_manager_app_context_get_app_id_p(void);
extern int utc_app_manager_app_context_get_app_id_n(void);
extern int utc_app_manager_app_context_get_package_p(void);
extern int utc_app_manager_app_context_get_package_n(void);
extern int utc_app_manager_app_context_get_package_id_p(void);
extern int utc_app_manager_app_context_get_package_id_n1(void);
extern int utc_app_manager_app_context_get_package_id_n2(void);
extern int utc_app_manager_app_context_get_app_state_p(void);
extern int utc_app_manager_app_context_get_app_state_n(void);
extern int utc_app_manager_app_context_get_pid_p(void);
extern int utc_app_manager_app_context_get_pid_n(void);
extern int utc_app_manager_app_context_is_equal_p(void);
extern int utc_app_manager_app_context_is_equal_n(void);
extern int utc_app_manager_app_context_is_terminated_p(void);
extern int utc_app_manager_app_context_is_terminated_n(void);
extern int utc_app_manager_app_context_is_sub_app_p(void);
extern int utc_app_manager_app_context_is_sub_app_n(void);
extern int utc_app_manager_get_external_shared_data_path_p(void);
extern int utc_app_manager_get_external_shared_data_path_n1(void);
extern int utc_app_manager_get_external_shared_data_path_n2(void);
extern int utc_app_manager_get_external_shared_data_path_n3(void);
extern int utc_app_manager_get_shared_data_path_p(void);
extern int utc_app_manager_get_shared_data_path_n1(void);
extern int utc_app_manager_get_shared_data_path_n2(void);
extern int utc_app_manager_get_shared_data_path_n3(void);
extern int utc_app_manager_get_shared_data_path_n4(void);
extern int utc_app_manager_get_shared_resource_path_p(void);
extern int utc_app_manager_get_shared_resource_path_n1(void);
extern int utc_app_manager_get_shared_resource_path_n2(void);
extern int utc_app_manager_get_shared_resource_path_n3(void);
extern int utc_app_manager_get_shared_trusted_path_p1(void);
extern int utc_app_manager_get_shared_trusted_path_p2(void);
extern int utc_app_manager_get_shared_trusted_path_n1(void);
extern int utc_app_manager_get_shared_trusted_path_n2(void);
extern int utc_app_manager_get_shared_trusted_path_n3(void);
extern int utc_app_manager_get_shared_trusted_path_n4(void);
extern int utc_app_info_app_info_clone_p(void);
extern int utc_app_info_app_info_clone_n(void);
extern int utc_app_info_metadata_filter_add_p(void);
extern int utc_app_info_metadata_filter_add_n(void);
extern int utc_app_info_app_info_destroy_p(void);
extern int utc_app_info_app_info_destroy_n(void);
extern int utc_app_info_app_info_create_p(void);
extern int utc_app_info_app_info_create_n1(void);
extern int utc_app_info_app_info_create_n2(void);
extern int utc_app_info_get_app_id_p(void);
extern int utc_app_info_get_app_id_n(void);
extern int utc_app_info_get_icon_p(void);
extern int utc_app_info_get_icon_n(void);
extern int utc_app_info_get_label_p(void);
extern int utc_app_info_get_label_n(void);
extern int utc_app_info_get_package_p(void);
extern int utc_app_info_get_package_n(void);
extern int utc_app_info_get_type_p(void);
extern int utc_app_info_get_type_n(void);
extern int utc_app_info_get_app_component_type_p(void);
extern int utc_app_info_get_app_component_type_p1(void);
extern int utc_app_info_get_app_component_type_n(void);
extern int utc_app_info_foreach_metadata_p(void);
extern int utc_app_info_foreach_metadata_n(void);
extern int utc_app_info_foreach_res_control_p(void);
extern int utc_app_info_foreach_res_control_n(void);
extern int utc_app_info_is_nodisplay_p(void);
extern int utc_app_info_is_nodisplay_n(void);
extern int utc_app_info_is_equal_p(void);
extern int utc_app_info_is_equal_n(void);
extern int utc_app_info_is_enabled_p(void);
extern int utc_app_info_is_enabled_n(void);
extern int utc_app_info_filter_destroy_p1(void);
extern int utc_app_info_filter_destroy_p2(void);
extern int utc_app_info_filter_create_p1(void);
extern int utc_app_info_filter_create_p2(void);
extern int utc_app_info_filter_create_n(void);
extern int utc_app_info_filter_destroy_n(void);
extern int utc_app_info_filter_add_bool_p(void);
extern int utc_app_info_filter_add_bool_n1(void);
extern int utc_app_info_filter_add_bool_n2(void);
extern int utc_app_info_filter_add_bool_n3(void);
extern int utc_app_info_filter_add_string_p(void);
extern int utc_app_info_filter_add_string_n1(void);
extern int utc_app_info_filter_add_string_n2(void);
extern int utc_app_info_filter_add_string_n3(void);
extern int utc_app_info_filter_foreach_appinfo_p1(void);
extern int utc_app_info_filter_foreach_appinfo_p2(void);
extern int utc_app_info_filter_foreach_appinfo_n1(void);
extern int utc_app_info_filter_foreach_appinfo_n2(void);
extern int utc_app_info_metadata_filter_create_p1(void);
extern int utc_app_info_metadata_filter_create_p2(void);
extern int utc_app_info_metadata_filter_create_n(void);
extern int utc_app_info_metadata_filter_destroy_p1(void);
extern int utc_app_info_metadata_filter_destroy_p2(void);
extern int utc_app_info_metadata_filter_destroy_n(void);
extern int utc_app_info_metadata_filter_foreach_p1(void);
extern int utc_app_info_metadata_filter_foreach_p2(void);
extern int utc_app_info_metadata_filter_foreach_n1(void);
extern int utc_app_info_metadata_filter_foreach_n2(void);
extern int utc_app_manager_is_running_p(void);
extern int utc_app_manager_is_running_n1(void);
extern int utc_app_manager_is_running_n2(void);
extern int utc_app_manager_is_running_n3(void);
extern int utc_app_manager_foreach_app_context_p(void);
extern int utc_app_manager_foreach_app_context_n(void);
extern int utc_app_manager_foreach_running_app_context_p(void);
extern int utc_app_manager_foreach_running_app_context_n(void);
extern int utc_app_manager_foreach_app_info_p(void);
extern int utc_app_manager_foreach_app_info_n(void);
extern int utc_app_manager_get_app_id_n1(void);
extern int utc_app_manager_get_app_id_n2(void);
extern int utc_app_manager_get_app_id_p(void);
extern int utc_app_manager_resume_app_p(void);
extern int utc_app_manager_resume_app_n(void);
extern int utc_app_manager_get_app_context_p(void);
extern int utc_app_manager_get_app_context_n1(void);
extern int utc_app_manager_get_app_context_n2(void);
extern int utc_app_manager_get_app_context_n3(void);
extern int utc_app_manager_get_app_info_p(void);
extern int utc_app_manager_get_app_info_n1(void);
extern int utc_app_manager_get_app_info_n2(void);
extern int utc_app_manager_get_app_info_n3(void);
extern int utc_app_manager_request_terminate_bg_app_p(void);
extern int utc_app_manager_request_terminate_bg_app_n(void);
extern int utc_app_manager_set_app_context_event_cb_p1(void);
extern int utc_app_manager_set_app_context_event_cb_p2(void);
extern int utc_app_manager_set_app_context_event_cb_n(void);
extern int utc_app_manager_event_create_p(void);
extern int utc_app_manager_event_create_n(void);
extern int utc_app_manager_event_set_status_p(void);
extern int utc_app_manager_event_set_status_n(void);
extern int utc_app_manager_set_event_cb_p(void);
extern int utc_app_manager_set_event_cb_n(void);
extern int utc_app_manager_unset_event_cb_p(void);
extern int utc_app_manager_unset_event_cb_n(void);
extern int utc_app_manager_event_destroy_p(void);
extern int utc_app_manager_event_destroy_n(void);
extern int utc_app_info_filter_count_appinfo_p(void);
extern int utc_app_info_filter_count_appinfo_n(void);
extern int utc_app_info_get_exec_p(void);
extern int utc_app_info_get_exec_n(void);
extern int utc_app_info_get_localed_label_p(void);
extern int utc_app_info_get_localed_label_n(void);
extern int utc_app_info_is_onboot_p(void);
extern int utc_app_info_is_onboot_n(void);
extern int utc_app_info_is_preload_p(void);
extern int utc_app_info_is_preload_n(void);
extern int utc_app_info_is_support_ambient_p(void);
extern int utc_app_info_is_support_ambient_n(void);
extern int utc_app_multi_resolution_icon_test_p(void);
extern int utc_app_multi_resolution_icon_test_n(void);
extern int utc_app_manager_unset_app_context_event_cb_p(void);

testcase tc_array[] = {
	{"utc_app_manager_app_context_clone_p",utc_app_manager_app_context_clone_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_clone_n",utc_app_manager_app_context_clone_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_destroy_p",utc_app_manager_app_context_destroy_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_destroy_n",utc_app_manager_app_context_destroy_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_app_id_p",utc_app_manager_app_context_get_app_id_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_app_id_n",utc_app_manager_app_context_get_app_id_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_package_p",utc_app_manager_app_context_get_package_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_package_n",utc_app_manager_app_context_get_package_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_package_id_p",utc_app_manager_app_context_get_package_id_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_package_id_n1",utc_app_manager_app_context_get_package_id_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_package_id_n2",utc_app_manager_app_context_get_package_id_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_app_state_p",utc_app_manager_app_context_get_app_state_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_app_state_n",utc_app_manager_app_context_get_app_state_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_pid_p",utc_app_manager_app_context_get_pid_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_get_pid_n",utc_app_manager_app_context_get_pid_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_equal_p",utc_app_manager_app_context_is_equal_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_equal_n",utc_app_manager_app_context_is_equal_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_terminated_p",utc_app_manager_app_context_is_terminated_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_terminated_n",utc_app_manager_app_context_is_terminated_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_sub_app_p",utc_app_manager_app_context_is_sub_app_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_app_context_is_sub_app_n",utc_app_manager_app_context_is_sub_app_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_external_shared_data_path_p",utc_app_manager_get_external_shared_data_path_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_external_shared_data_path_n1",utc_app_manager_get_external_shared_data_path_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_external_shared_data_path_n2",utc_app_manager_get_external_shared_data_path_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_external_shared_data_path_n3",utc_app_manager_get_external_shared_data_path_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_data_path_p",utc_app_manager_get_shared_data_path_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_data_path_n1",utc_app_manager_get_shared_data_path_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_data_path_n2",utc_app_manager_get_shared_data_path_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_data_path_n3",utc_app_manager_get_shared_data_path_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_data_path_n4",utc_app_manager_get_shared_data_path_n4,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_resource_path_p",utc_app_manager_get_shared_resource_path_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_resource_path_n1",utc_app_manager_get_shared_resource_path_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_resource_path_n2",utc_app_manager_get_shared_resource_path_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_resource_path_n3",utc_app_manager_get_shared_resource_path_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_p1",utc_app_manager_get_shared_trusted_path_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_p2",utc_app_manager_get_shared_trusted_path_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_n1",utc_app_manager_get_shared_trusted_path_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_n2",utc_app_manager_get_shared_trusted_path_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_n3",utc_app_manager_get_shared_trusted_path_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_shared_trusted_path_n4",utc_app_manager_get_shared_trusted_path_n4,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_clone_p",utc_app_info_app_info_clone_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_clone_n",utc_app_info_app_info_clone_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_add_p",utc_app_info_metadata_filter_add_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_add_n",utc_app_info_metadata_filter_add_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_destroy_p",utc_app_info_app_info_destroy_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_destroy_n",utc_app_info_app_info_destroy_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_create_p",utc_app_info_app_info_create_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_create_n1",utc_app_info_app_info_create_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_app_info_create_n2",utc_app_info_app_info_create_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_app_id_p",utc_app_info_get_app_id_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_app_id_n",utc_app_info_get_app_id_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_icon_p",utc_app_info_get_icon_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_icon_n",utc_app_info_get_icon_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_label_p",utc_app_info_get_label_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_label_n",utc_app_info_get_label_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_package_p",utc_app_info_get_package_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_package_n",utc_app_info_get_package_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_type_p",utc_app_info_get_type_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_type_n",utc_app_info_get_type_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_app_component_type_p",utc_app_info_get_app_component_type_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_app_component_type_p1",utc_app_info_get_app_component_type_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_app_component_type_n",utc_app_info_get_app_component_type_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_foreach_metadata_p",utc_app_info_foreach_metadata_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_foreach_metadata_n",utc_app_info_foreach_metadata_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_foreach_res_control_p",utc_app_info_foreach_res_control_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_foreach_res_control_n",utc_app_info_foreach_res_control_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_nodisplay_p",utc_app_info_is_nodisplay_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_nodisplay_n",utc_app_info_is_nodisplay_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_equal_p",utc_app_info_is_equal_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_equal_n",utc_app_info_is_equal_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_enabled_p",utc_app_info_is_enabled_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_enabled_n",utc_app_info_is_enabled_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_destroy_p1",utc_app_info_filter_destroy_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_destroy_p2",utc_app_info_filter_destroy_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_create_p1",utc_app_info_filter_create_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_create_p2",utc_app_info_filter_create_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_create_n",utc_app_info_filter_create_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_destroy_n",utc_app_info_filter_destroy_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_bool_p",utc_app_info_filter_add_bool_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_bool_n1",utc_app_info_filter_add_bool_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_bool_n2",utc_app_info_filter_add_bool_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_bool_n3",utc_app_info_filter_add_bool_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_string_p",utc_app_info_filter_add_string_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_string_n1",utc_app_info_filter_add_string_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_string_n2",utc_app_info_filter_add_string_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_add_string_n3",utc_app_info_filter_add_string_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_foreach_appinfo_p1",utc_app_info_filter_foreach_appinfo_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_foreach_appinfo_p2",utc_app_info_filter_foreach_appinfo_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_foreach_appinfo_n1",utc_app_info_filter_foreach_appinfo_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_foreach_appinfo_n2",utc_app_info_filter_foreach_appinfo_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_create_p1",utc_app_info_metadata_filter_create_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_create_p2",utc_app_info_metadata_filter_create_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_create_n",utc_app_info_metadata_filter_create_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_destroy_p1",utc_app_info_metadata_filter_destroy_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_destroy_p2",utc_app_info_metadata_filter_destroy_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_destroy_n",utc_app_info_metadata_filter_destroy_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_foreach_p1",utc_app_info_metadata_filter_foreach_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_foreach_p2",utc_app_info_metadata_filter_foreach_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_foreach_n1",utc_app_info_metadata_filter_foreach_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_metadata_filter_foreach_n2",utc_app_info_metadata_filter_foreach_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_is_running_p",utc_app_manager_is_running_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_is_running_n1",utc_app_manager_is_running_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_is_running_n2",utc_app_manager_is_running_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_is_running_n3",utc_app_manager_is_running_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_app_context_p",utc_app_manager_foreach_app_context_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_app_context_n",utc_app_manager_foreach_app_context_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_running_app_context_p",utc_app_manager_foreach_running_app_context_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_running_app_context_n",utc_app_manager_foreach_running_app_context_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_app_info_p",utc_app_manager_foreach_app_info_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_foreach_app_info_n",utc_app_manager_foreach_app_info_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_id_n1",utc_app_manager_get_app_id_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_id_n2",utc_app_manager_get_app_id_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_id_p",utc_app_manager_get_app_id_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_resume_app_p",utc_app_manager_resume_app_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_resume_app_n",utc_app_manager_resume_app_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_context_p",utc_app_manager_get_app_context_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_context_n1",utc_app_manager_get_app_context_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_context_n2",utc_app_manager_get_app_context_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_context_n3",utc_app_manager_get_app_context_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_info_p",utc_app_manager_get_app_info_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_info_n1",utc_app_manager_get_app_info_n1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_info_n2",utc_app_manager_get_app_info_n2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_get_app_info_n3",utc_app_manager_get_app_info_n3,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_request_terminate_bg_app_p",utc_app_manager_request_terminate_bg_app_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_request_terminate_bg_app_n",utc_app_manager_request_terminate_bg_app_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_set_app_context_event_cb_p1",utc_app_manager_set_app_context_event_cb_p1,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_set_app_context_event_cb_p2",utc_app_manager_set_app_context_event_cb_p2,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_set_app_context_event_cb_n",utc_app_manager_set_app_context_event_cb_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_create_p",utc_app_manager_event_create_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_create_n",utc_app_manager_event_create_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_set_status_p",utc_app_manager_event_set_status_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_set_status_n",utc_app_manager_event_set_status_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_set_event_cb_p",utc_app_manager_set_event_cb_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_set_event_cb_n",utc_app_manager_set_event_cb_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_unset_event_cb_p",utc_app_manager_unset_event_cb_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_unset_event_cb_n",utc_app_manager_unset_event_cb_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_destroy_p",utc_app_manager_event_destroy_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_event_destroy_n",utc_app_manager_event_destroy_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_count_appinfo_p",utc_app_info_filter_count_appinfo_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_filter_count_appinfo_n",utc_app_info_filter_count_appinfo_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_exec_p",utc_app_info_get_exec_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_exec_n",utc_app_info_get_exec_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_localed_label_p",utc_app_info_get_localed_label_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_get_localed_label_n",utc_app_info_get_localed_label_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_onboot_p",utc_app_info_is_onboot_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_onboot_n",utc_app_info_is_onboot_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_preload_p",utc_app_info_is_preload_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_preload_n",utc_app_info_is_preload_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_support_ambient_p",utc_app_info_is_support_ambient_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_info_is_support_ambient_n",utc_app_info_is_support_ambient_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_multi_resolution_icon_test_p",utc_app_multi_resolution_icon_test_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_multi_resolution_icon_test_n",utc_app_multi_resolution_icon_test_n,utc_app_manager_startup,utc_app_manager_cleanup},
	{"utc_app_manager_unset_app_context_event_cb_p",utc_app_manager_unset_app_context_event_cb_p,utc_app_manager_startup,utc_app_manager_cleanup},
	{NULL, NULL}
};

#endif // __TCT_APP-MANAGER-NATIVE_H__
