//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_MEDIACODEC-NATIVE_H__
#define __TCT_MEDIACODEC-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_media_mediacodec_startup(void);
extern void utc_media_mediacodec_cleanup(void);

extern int _mediacodec_get_output(void);
extern int utc_mediacodec_create_p(void);
extern int utc_mediacodec_create_n(void);
extern int utc_mediacodec_destroy_p(void);
extern int utc_mediacodec_destroy_n(void);
extern int utc_media_mediacodec_set_codec_p(void);
extern int utc_media_mediacodec_set_codec_n(void);
extern int utc_media_mediacodec_set_venc_info_p(void);
extern int utc_media_mediacodec_set_venc_info_n(void);
extern int utc_media_mediacodec_set_vdec_info_p(void);
extern int utc_media_mediacodec_set_vdec_info_n(void);
extern int utc_media_mediacodec_set_aenc_info_p(void);
extern int utc_media_mediacodec_set_aenc_info_n(void);
extern int utc_media_mediacodec_set_adec_info_p(void);
extern int utc_media_mediacodec_set_adec_info_n(void);
extern int utc_media_mediacodec_prepare_p(void);
extern int utc_media_mediacodec_prepare_n(void);
extern int utc_media_mediacodec_unprepare_p(void);
extern int utc_media_mediacodec_unprepare_n(void);
extern int utc_media_mediacodec_process_input_p(void);
extern int utc_media_mediacodec_process_input_n(void);
extern int utc_media_mediacodec_get_output_p(void);
extern int utc_media_mediacodec_get_output_n(void);
extern int utc_media_mediacodec_flush_buffers_p(void);
extern int utc_media_mediacodec_flush_buffers_n(void);
extern int utc_mediacodec_set_input_buffer_used_cb_p(void);
extern int utc_mediacodec_set_input_buffer_used_cb_n(void);
extern int utc_mediacodec_unset_input_buffer_used_cb_p(void);
extern int utc_mediacodec_unset_input_buffer_used_cb_n(void);
extern int utc_mediacodec_set_output_buffer_available_cb_p(void);
extern int utc_mediacodec_set_output_buffer_available_cb_n(void);
extern int utc_mediacodec_unset_output_buffer_available_cb_p(void);
extern int utc_mediacodec_unset_output_buffer_available_cb_n(void);
extern int utc_mediacodec_set_error_cb_p(void);
extern int utc_mediacodec_set_error_cb_n(void);
extern int utc_mediacodec_unset_error_cb_p(void);
extern int utc_mediacodec_unset_error_cb_n(void);
extern int utc_mediacodec_set_eos_cb_p(void);
extern int utc_mediacodec_set_eos_cb_n(void);
extern int utc_mediacodec_unset_eos_cb_p(void);
extern int utc_mediacodec_unset_eos_cb_n(void);
extern int utc_mediacodec_foreach_supported_codec_p(void);
extern int utc_mediacodec_foreach_supported_codec_n(void);
extern int utc_mediacodec_get_supported_type_p(void);
extern int utc_mediacodec_get_supported_type_n(void);
extern int utc_mediacodec_set_buffer_status_cb_p(void);
extern int utc_mediacodec_set_buffer_status_cb_n(void);
extern int utc_mediacodec_unset_buffer_status_cb_p(void);
extern int utc_mediacodec_unset_buffer_status_cb_n(void);
extern int utc_mediacodec_get_packet_pool_p(void);
extern int utc_mediacodec_get_packet_pool_n(void);
extern int utc_mediacodec_configure_from_media_format_p(void);
extern int utc_mediacodec_configure_from_media_format_n(void);

testcase tc_array[] = {
	{"_mediacodec_get_output",_mediacodec_get_output,NULL,NULL},
	{"utc_mediacodec_create_p",utc_mediacodec_create_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_create_n",utc_mediacodec_create_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_destroy_p",utc_mediacodec_destroy_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_destroy_n",utc_mediacodec_destroy_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_codec_p",utc_media_mediacodec_set_codec_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_codec_n",utc_media_mediacodec_set_codec_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_venc_info_p",utc_media_mediacodec_set_venc_info_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_venc_info_n",utc_media_mediacodec_set_venc_info_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_vdec_info_p",utc_media_mediacodec_set_vdec_info_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_vdec_info_n",utc_media_mediacodec_set_vdec_info_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_aenc_info_p",utc_media_mediacodec_set_aenc_info_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_aenc_info_n",utc_media_mediacodec_set_aenc_info_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_adec_info_p",utc_media_mediacodec_set_adec_info_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_set_adec_info_n",utc_media_mediacodec_set_adec_info_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_prepare_p",utc_media_mediacodec_prepare_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_prepare_n",utc_media_mediacodec_prepare_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_unprepare_p",utc_media_mediacodec_unprepare_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_unprepare_n",utc_media_mediacodec_unprepare_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_process_input_p",utc_media_mediacodec_process_input_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_process_input_n",utc_media_mediacodec_process_input_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_get_output_p",utc_media_mediacodec_get_output_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_get_output_n",utc_media_mediacodec_get_output_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_flush_buffers_p",utc_media_mediacodec_flush_buffers_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_media_mediacodec_flush_buffers_n",utc_media_mediacodec_flush_buffers_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_input_buffer_used_cb_p",utc_mediacodec_set_input_buffer_used_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_input_buffer_used_cb_n",utc_mediacodec_set_input_buffer_used_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_input_buffer_used_cb_p",utc_mediacodec_unset_input_buffer_used_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_input_buffer_used_cb_n",utc_mediacodec_unset_input_buffer_used_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_output_buffer_available_cb_p",utc_mediacodec_set_output_buffer_available_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_output_buffer_available_cb_n",utc_mediacodec_set_output_buffer_available_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_output_buffer_available_cb_p",utc_mediacodec_unset_output_buffer_available_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_output_buffer_available_cb_n",utc_mediacodec_unset_output_buffer_available_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_error_cb_p",utc_mediacodec_set_error_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_error_cb_n",utc_mediacodec_set_error_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_error_cb_p",utc_mediacodec_unset_error_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_error_cb_n",utc_mediacodec_unset_error_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_eos_cb_p",utc_mediacodec_set_eos_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_eos_cb_n",utc_mediacodec_set_eos_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_eos_cb_p",utc_mediacodec_unset_eos_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_eos_cb_n",utc_mediacodec_unset_eos_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_foreach_supported_codec_p",utc_mediacodec_foreach_supported_codec_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_foreach_supported_codec_n",utc_mediacodec_foreach_supported_codec_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_get_supported_type_p",utc_mediacodec_get_supported_type_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_get_supported_type_n",utc_mediacodec_get_supported_type_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_buffer_status_cb_p",utc_mediacodec_set_buffer_status_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_set_buffer_status_cb_n",utc_mediacodec_set_buffer_status_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_buffer_status_cb_p",utc_mediacodec_unset_buffer_status_cb_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_unset_buffer_status_cb_n",utc_mediacodec_unset_buffer_status_cb_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_get_packet_pool_p",utc_mediacodec_get_packet_pool_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_get_packet_pool_n",utc_mediacodec_get_packet_pool_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_configure_from_media_format_p",utc_mediacodec_configure_from_media_format_p,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{"utc_mediacodec_configure_from_media_format_n",utc_mediacodec_configure_from_media_format_n,utc_media_mediacodec_startup,utc_media_mediacodec_cleanup},
	{NULL, NULL}
};

#endif // __TCT_MEDIACODEC-NATIVE_H__
