//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_URL-DOWNLOAD-NATIVE_H__
#define __TCT_URL-DOWNLOAD-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_download_add_http_header_field_startup(void);
extern void utc_download_add_http_header_field_cleanup(void);
extern void utc_download_create_startup(void);
extern void utc_download_destroy_startup(void);
extern void utc_download_destroy_cleanup(void);
extern void utc_download_get_auto_download_startup(void);
extern void utc_download_get_auto_download_cleanup(void);
extern void utc_download_get_auto_download_startup(void);
extern void utc_download_get_auto_download_cleanup(void);
extern void utc_download_get_content_name_startup(void);
extern void utc_download_get_content_name_cleanup(void);
extern void utc_download_get_content_size_startup(void);
extern void utc_download_get_content_size_cleanup(void);
extern void utc_download_get_destination_startup(void);
extern void utc_download_get_destination_cleanup(void);
extern void utc_download_get_downloaded_file_path_startup(void);
extern void utc_download_get_downloaded_file_path_cleanup(void);
extern void utc_download_get_error_startup(void);
extern void utc_download_get_error_cleanup(void);
extern void utc_download_get_etag_startup(void);
extern void utc_download_get_etag_cleanup(void);
extern void utc_download_get_file_name_startup(void);
extern void utc_download_get_file_name_cleanup(void);
extern void utc_download_get_http_header_field_startup(void);
extern void utc_download_get_http_header_field_cleanup(void);
extern void utc_download_get_http_header_field_list_startup(void);
extern void utc_download_get_http_header_field_list_cleanup(void);
extern void utc_download_get_http_status_startup(void);
extern void utc_download_get_http_status_cleanup(void);
extern void utc_download_get_mime_type_startup(void);
extern void utc_download_get_mime_type_cleanup(void);
extern void utc_download_get_network_type_startup(void);
extern void utc_download_get_network_type_cleanup(void);
extern void utc_download_get_notification_app_control_startup(void);
extern void utc_download_get_notification_app_control_cleanup(void);
extern void utc_download_get_notification_description_startup(void);
extern void utc_download_get_notification_description_cleanup(void);
extern void utc_download_get_notification_title_startup(void);
extern void utc_download_get_notification_title_cleanup(void);
extern void utc_download_get_notification_type_startup(void);
extern void utc_download_get_notification_type_cleanup(void);
extern void utc_download_get_state_startup(void);
extern void utc_download_get_state_cleanup(void);
extern void utc_download_get_temp_path_startup(void);
extern void utc_download_get_temp_path_cleanup(void);
extern void utc_download_get_url_startup(void);
extern void utc_download_get_url_cleanup(void);
extern void utc_download_set_notification_title_startup(void);
extern void utc_download_set_notification_title_cleanup(void);

extern void utc_download_set_network_type_startup(void);
extern void utc_download_set_network_type_cleanup(void);
extern void utc_download_set_notification_app_control_startup(void);
extern void utc_download_set_notification_app_control_cleanup(void);
extern void utc_download_set_notification_description_startup(void);
extern void utc_download_set_notification_description_cleanup(void);
extern void utc_download_set_notification_type_startup(void);
extern void utc_download_set_notification_type_cleanup(void);
extern void utc_download_set_progress_cb_startup(void);
extern void utc_download_set_progress_cb_cleanup(void);
extern void utc_download_set_state_changed_cb_startup(void);
extern void utc_download_set_state_changed_cb_cleanup(void);
extern void utc_download_set_url_startup(void);
extern void utc_download_set_url_cleanup(void);
extern void utc_download_unset_progress_cb_startup(void);
extern void utc_download_unset_progress_cb_cleanup(void);
extern void utc_url_download_unset_state_changed_cb_startup(void);
extern void utc_url_download_unset_state_changed_cb_cleanup(void);

extern void utc_download_pause_startup(void);
extern void utc_download_pause_cleanup(void);
extern void utc_download_cancel_startup(void);
extern void utc_download_cancel_cleanup(void);
extern void utc_download_remove_http_header_field_startup(void);
extern void utc_download_remove_http_header_field_cleanup(void);
extern void utc_download_set_auto_download_startup(void);
extern void utc_download_set_auto_download_cleanup(void);
extern void utc_download_set_destination_startup(void);
extern void utc_download_set_destination_cleanup(void);
extern void utc_download_set_file_name_startup(void);
extern void utc_download_set_file_name_cleanup(void);
extern void utc_download_set_temp_path_startup(void);
extern void utc_download_set_temp_path_cleanup(void);
extern void utc_download_start_startup(void);
extern void utc_download_start_cleanup(void);

extern int utc_download_add_http_header_field_p1(void);
extern int utc_download_add_http_header_field_n1(void);
extern int utc_download_add_http_header_field_n2(void);
extern int utc_download_add_http_header_field_n3(void);
extern int utc_download_create_p1(void);
extern int utc_download_create_n1(void);
extern int utc_download_destroy_p1(void);
extern int utc_download_destroy_n1(void);
extern int utc_download_get_auto_download_p1(void);
extern int utc_download_get_auto_download_n1(void);
extern int utc_download_get_auto_download_n2(void);
extern int utc_download_get_content_name_p1(void);
extern int utc_download_get_content_name_n1(void);
extern int utc_download_get_content_name_n2(void);
extern int utc_download_get_content_size_p1(void);
extern int utc_download_get_content_size_n1(void);
extern int utc_download_get_content_size_n2(void);
extern int utc_download_get_destination_p1(void);
extern int utc_download_get_destination_n1(void);
extern int utc_download_get_destination_n2(void);
extern int utc_download_get_downloaded_file_path_p1(void);
extern int utc_download_get_downloaded_file_path_n1(void);
extern int utc_download_get_downloaded_file_path_n2(void);
extern int utc_download_get_error_p1(void);
extern int utc_download_get_error_n1(void);
extern int utc_download_get_error_n2(void);
extern int utc_download_get_etag_p1(void);
extern int utc_download_get_etag_n1(void);
extern int utc_download_get_etag_n2(void);
extern int utc_download_get_file_name_p1(void);
extern int utc_download_get_file_name_n1(void);
extern int utc_download_get_file_name_n2(void);
extern int utc_download_get_http_header_field_p1(void);
extern int utc_download_get_http_header_field_n1(void);
extern int utc_download_get_http_header_field_n2(void);
extern int utc_download_get_http_header_field_n3(void);
extern int utc_download_get_http_header_field_list_p1(void);
extern int utc_download_get_http_header_field_list_n1(void);
extern int utc_download_get_http_header_field_list_n2(void);
extern int utc_download_get_http_header_field_list_n3(void);
extern int utc_download_get_http_status_p1(void);
extern int utc_download_get_http_status_n1(void);
extern int utc_download_get_http_status_n2(void);
extern int utc_download_get_mime_type_p1(void);
extern int utc_download_get_mime_type_n1(void);
extern int utc_download_get_mime_type_n2(void);
extern int utc_download_get_network_type_p1(void);
extern int utc_download_get_network_type_n1(void);
extern int utc_download_get_network_type_n2(void);
extern int utc_download_get_notification_app_control_p1(void);
extern int utc_download_get_notification_app_control_n1(void);
extern int utc_download_get_notification_app_control_n2(void);
extern int utc_download_get_notification_app_control_n3(void);
extern int utc_download_get_notification_description_p1(void);
extern int utc_download_get_notification_description_n1(void);
extern int utc_download_get_notification_description_n2(void);
extern int utc_download_get_notification_title_p1(void);
extern int utc_download_get_notification_title_n1(void);
extern int utc_download_get_notification_title_n2(void);
extern int utc_download_get_notification_type_p1(void);
extern int utc_download_get_notification_type_n1(void);
extern int utc_download_get_notification_type_n2(void);
extern int utc_download_get_state_p1(void);
extern int utc_download_get_state_n1(void);
extern int utc_download_get_state_n2(void);
extern int utc_download_get_temp_path_p1(void);
extern int utc_download_get_temp_path_n1(void);
extern int utc_download_get_temp_path_n2(void);
extern int utc_download_get_url_p1(void);
extern int utc_download_get_url_n1(void);
extern int utc_download_get_url_n2(void);
extern int utc_download_pause_p1(void);
extern int utc_download_pause_n1(void);
extern int utc_download_cancel_p1(void);
extern int utc_download_cancel_n1(void);
extern int utc_download_remove_http_header_field_p1(void);
extern int utc_download_remove_http_header_field_n1(void);
extern int utc_download_remove_http_header_field_n2(void);
extern int utc_download_remove_http_header_field_n3(void);
extern int utc_download_set_auto_download_p1(void);
extern int utc_download_set_auto_download_n1(void);
extern int utc_download_set_destination_p1(void);
extern int utc_download_set_destination_n1(void);
extern int utc_download_set_destination_n2(void);
extern int utc_download_set_file_name_p1(void);
extern int utc_download_set_file_name_n1(void);
extern int utc_download_set_file_name_n2(void);
extern int utc_download_set_network_type_p1(void);
extern int utc_download_set_network_type_n1(void);
extern int utc_download_set_network_type_n2(void);
extern int utc_download_set_notification_app_control_p1(void);
extern int utc_download_set_notification_app_control_n1(void);
extern int utc_download_set_notification_app_control_n2(void);
extern int utc_download_set_notification_app_control_n3(void);
extern int utc_download_set_notification_description_p1(void);
extern int utc_download_set_notification_description_n1(void);
extern int utc_download_set_notification_description_n2(void);
extern int utc_download_set_notification_description_n3(void);
extern int utc_download_set_notification_title_p1(void);
extern int utc_download_set_notification_title_n1(void);
extern int utc_download_set_notification_title_n2(void);
extern int utc_download_set_notification_title_n3(void);
extern int utc_download_set_notification_type_p1(void);
extern int utc_download_set_notification_type_n1(void);
extern int utc_download_set_notification_type_n2(void);
extern int utc_download_set_progress_cb_p1(void);
extern int utc_download_set_progress_cb_n1(void);
extern int utc_download_set_state_changed_cb_p1(void);
extern int utc_download_set_state_changed_cb_n1(void);
extern int utc_download_set_temp_file_path_p1(void);
extern int utc_download_set_temp_file_path_n1(void);
extern int utc_download_set_temp_file_path_n2(void);
extern int utc_download_set_url_p1(void);
extern int utc_download_set_url_n1(void);
extern int utc_download_set_url_n2(void);
extern int utc_download_start_p1(void);
extern int utc_download_start_n1(void);
extern int utc_download_unset_progress_cb_p1(void);
extern int utc_download_unset_progress_cb_n1(void);
extern int utc_url_download_unset_state_changed_cb_p1(void);
extern int utc_url_download_unset_state_changed_cb_n1(void);

testcase tc_array[] = {
	{"utc_download_add_http_header_field_p1",utc_download_add_http_header_field_p1,utc_download_add_http_header_field_startup,utc_download_add_http_header_field_cleanup},
	{"utc_download_add_http_header_field_n1",utc_download_add_http_header_field_n1,utc_download_add_http_header_field_startup,utc_download_add_http_header_field_cleanup},
	{"utc_download_add_http_header_field_n2",utc_download_add_http_header_field_n2,utc_download_add_http_header_field_startup,utc_download_add_http_header_field_cleanup},
	{"utc_download_add_http_header_field_n3",utc_download_add_http_header_field_n3,utc_download_add_http_header_field_startup,utc_download_add_http_header_field_cleanup},
	{"utc_download_create_p1",utc_download_create_p1,utc_download_create_startup,NULL},
	{"utc_download_create_n1",utc_download_create_n1,utc_download_create_startup,NULL},
	{"utc_download_destroy_p1",utc_download_destroy_p1,utc_download_destroy_startup,utc_download_destroy_cleanup},
	{"utc_download_destroy_n1",utc_download_destroy_n1,utc_download_destroy_startup,utc_download_destroy_cleanup},
	{"utc_download_get_auto_download_p1",utc_download_get_auto_download_p1,utc_download_get_auto_download_startup,utc_download_get_auto_download_cleanup},
	{"utc_download_get_auto_download_n1",utc_download_get_auto_download_n1,utc_download_get_auto_download_startup,utc_download_get_auto_download_cleanup},
	{"utc_download_get_auto_download_n2",utc_download_get_auto_download_n2,utc_download_get_auto_download_startup,utc_download_get_auto_download_cleanup},
	{"utc_download_get_content_name_p1",utc_download_get_content_name_p1,utc_download_get_content_name_startup,utc_download_get_content_name_cleanup},
	{"utc_download_get_content_name_n1",utc_download_get_content_name_n1,utc_download_get_content_name_startup,utc_download_get_content_name_cleanup},
	{"utc_download_get_content_name_n2",utc_download_get_content_name_n2,utc_download_get_content_name_startup,utc_download_get_content_name_cleanup},
	{"utc_download_get_content_size_p1",utc_download_get_content_size_p1,utc_download_get_content_size_startup,utc_download_get_content_size_cleanup},
	{"utc_download_get_content_size_n1",utc_download_get_content_size_n1,utc_download_get_content_size_startup,utc_download_get_content_size_cleanup},
	{"utc_download_get_content_size_n2",utc_download_get_content_size_n2,utc_download_get_content_size_startup,utc_download_get_content_size_cleanup},
	{"utc_download_get_destination_p1",utc_download_get_destination_p1,utc_download_get_destination_startup,utc_download_get_destination_cleanup},
	{"utc_download_get_destination_n1",utc_download_get_destination_n1,utc_download_get_destination_startup,utc_download_get_destination_cleanup},
	{"utc_download_get_destination_n2",utc_download_get_destination_n2,utc_download_get_destination_startup,utc_download_get_destination_cleanup},
	{"utc_download_get_downloaded_file_path_p1",utc_download_get_downloaded_file_path_p1,utc_download_get_downloaded_file_path_startup,utc_download_get_downloaded_file_path_cleanup},
	{"utc_download_get_downloaded_file_path_n1",utc_download_get_downloaded_file_path_n1,utc_download_get_downloaded_file_path_startup,utc_download_get_downloaded_file_path_cleanup},
	{"utc_download_get_downloaded_file_path_n2",utc_download_get_downloaded_file_path_n2,utc_download_get_downloaded_file_path_startup,utc_download_get_downloaded_file_path_cleanup},
	{"utc_download_get_error_p1",utc_download_get_error_p1,utc_download_get_error_startup,utc_download_get_error_cleanup},
	{"utc_download_get_error_n1",utc_download_get_error_n1,utc_download_get_error_startup,utc_download_get_error_cleanup},
	{"utc_download_get_error_n2",utc_download_get_error_n2,utc_download_get_error_startup,utc_download_get_error_cleanup},
	{"utc_download_get_etag_p1",utc_download_get_etag_p1,utc_download_get_etag_startup,utc_download_get_etag_cleanup},
	{"utc_download_get_etag_n1",utc_download_get_etag_n1,utc_download_get_etag_startup,utc_download_get_etag_cleanup},
	{"utc_download_get_etag_n2",utc_download_get_etag_n2,utc_download_get_etag_startup,utc_download_get_etag_cleanup},
	{"utc_download_get_file_name_p1",utc_download_get_file_name_p1,utc_download_get_file_name_startup,utc_download_get_file_name_cleanup},
	{"utc_download_get_file_name_n1",utc_download_get_file_name_n1,utc_download_get_file_name_startup,utc_download_get_file_name_cleanup},
	{"utc_download_get_file_name_n2",utc_download_get_file_name_n2,utc_download_get_file_name_startup,utc_download_get_file_name_cleanup},
	{"utc_download_get_http_header_field_p1",utc_download_get_http_header_field_p1,utc_download_get_http_header_field_startup,utc_download_get_http_header_field_cleanup},
	{"utc_download_get_http_header_field_n1",utc_download_get_http_header_field_n1,utc_download_get_http_header_field_startup,utc_download_get_http_header_field_cleanup},
	{"utc_download_get_http_header_field_n2",utc_download_get_http_header_field_n2,utc_download_get_http_header_field_startup,utc_download_get_http_header_field_cleanup},
	{"utc_download_get_http_header_field_n3",utc_download_get_http_header_field_n3,utc_download_get_http_header_field_startup,utc_download_get_http_header_field_cleanup},
	{"utc_download_get_http_header_field_list_p1",utc_download_get_http_header_field_list_p1,utc_download_get_http_header_field_list_startup,utc_download_get_http_header_field_list_cleanup},
	{"utc_download_get_http_header_field_list_n1",utc_download_get_http_header_field_list_n1,utc_download_get_http_header_field_list_startup,utc_download_get_http_header_field_list_cleanup},
	{"utc_download_get_http_header_field_list_n2",utc_download_get_http_header_field_list_n2,utc_download_get_http_header_field_list_startup,utc_download_get_http_header_field_list_cleanup},
	{"utc_download_get_http_header_field_list_n3",utc_download_get_http_header_field_list_n3,utc_download_get_http_header_field_list_startup,utc_download_get_http_header_field_list_cleanup},
	{"utc_download_get_http_status_p1",utc_download_get_http_status_p1,utc_download_get_http_status_startup,utc_download_get_http_status_cleanup},
	{"utc_download_get_http_status_n1",utc_download_get_http_status_n1,utc_download_get_http_status_startup,utc_download_get_http_status_cleanup},
	{"utc_download_get_http_status_n2",utc_download_get_http_status_n2,utc_download_get_http_status_startup,utc_download_get_http_status_cleanup},
	{"utc_download_get_mime_type_p1",utc_download_get_mime_type_p1,utc_download_get_mime_type_startup,utc_download_get_mime_type_cleanup},
	{"utc_download_get_mime_type_n1",utc_download_get_mime_type_n1,utc_download_get_mime_type_startup,utc_download_get_mime_type_cleanup},
	{"utc_download_get_mime_type_n2",utc_download_get_mime_type_n2,utc_download_get_mime_type_startup,utc_download_get_mime_type_cleanup},
	{"utc_download_get_network_type_p1",utc_download_get_network_type_p1,utc_download_get_network_type_startup,utc_download_get_network_type_cleanup},
	{"utc_download_get_network_type_n1",utc_download_get_network_type_n1,utc_download_get_network_type_startup,utc_download_get_network_type_cleanup},
	{"utc_download_get_network_type_n2",utc_download_get_network_type_n2,utc_download_get_network_type_startup,utc_download_get_network_type_cleanup},
	{"utc_download_get_notification_app_control_p1",utc_download_get_notification_app_control_p1,utc_download_get_notification_app_control_startup,utc_download_get_notification_app_control_cleanup},
	{"utc_download_get_notification_app_control_n1",utc_download_get_notification_app_control_n1,utc_download_get_notification_app_control_startup,utc_download_get_notification_app_control_cleanup},
	{"utc_download_get_notification_app_control_n2",utc_download_get_notification_app_control_n2,utc_download_get_notification_app_control_startup,utc_download_get_notification_app_control_cleanup},
	{"utc_download_get_notification_app_control_n3",utc_download_get_notification_app_control_n3,utc_download_get_notification_app_control_startup,utc_download_get_notification_app_control_cleanup},
	{"utc_download_get_notification_description_p1",utc_download_get_notification_description_p1,utc_download_get_notification_description_startup,utc_download_get_notification_description_cleanup},
	{"utc_download_get_notification_description_n1",utc_download_get_notification_description_n1,utc_download_get_notification_description_startup,utc_download_get_notification_description_cleanup},
	{"utc_download_get_notification_description_n2",utc_download_get_notification_description_n2,utc_download_get_notification_description_startup,utc_download_get_notification_description_cleanup},
	{"utc_download_get_notification_title_p1",utc_download_get_notification_title_p1,utc_download_get_notification_title_startup,utc_download_get_notification_title_cleanup},
	{"utc_download_get_notification_title_n1",utc_download_get_notification_title_n1,utc_download_get_notification_title_startup,utc_download_get_notification_title_cleanup},
	{"utc_download_get_notification_title_n2",utc_download_get_notification_title_n2,utc_download_get_notification_title_startup,utc_download_get_notification_title_cleanup},
	{"utc_download_get_notification_type_p1",utc_download_get_notification_type_p1,utc_download_get_notification_type_startup,utc_download_get_notification_type_cleanup},
	{"utc_download_get_notification_type_n1",utc_download_get_notification_type_n1,utc_download_get_notification_type_startup,utc_download_get_notification_type_cleanup},
	{"utc_download_get_notification_type_n2",utc_download_get_notification_type_n2,utc_download_get_notification_type_startup,utc_download_get_notification_type_cleanup},
	{"utc_download_get_state_p1",utc_download_get_state_p1,utc_download_get_state_startup,utc_download_get_state_cleanup},
	{"utc_download_get_state_n1",utc_download_get_state_n1,utc_download_get_state_startup,utc_download_get_state_cleanup},
	{"utc_download_get_state_n2",utc_download_get_state_n2,utc_download_get_state_startup,utc_download_get_state_cleanup},
	{"utc_download_get_temp_path_p1",utc_download_get_temp_path_p1,utc_download_get_temp_path_startup,utc_download_get_temp_path_cleanup},
	{"utc_download_get_temp_path_n1",utc_download_get_temp_path_n1,utc_download_get_temp_path_startup,utc_download_get_temp_path_cleanup},
	{"utc_download_get_temp_path_n2",utc_download_get_temp_path_n2,utc_download_get_temp_path_startup,utc_download_get_temp_path_cleanup},
	{"utc_download_get_url_p1",utc_download_get_url_p1,utc_download_get_url_startup,utc_download_get_url_cleanup},
	{"utc_download_get_url_n1",utc_download_get_url_n1,utc_download_get_url_startup,utc_download_get_url_cleanup},
	{"utc_download_get_url_n2",utc_download_get_url_n2,utc_download_get_url_startup,utc_download_get_url_cleanup},
	{"utc_download_pause_p1",utc_download_pause_p1,utc_download_pause_startup,utc_download_pause_cleanup},
	{"utc_download_pause_n1",utc_download_pause_n1,utc_download_pause_startup,utc_download_pause_cleanup},
	{"utc_download_cancel_p1",utc_download_cancel_p1,utc_download_cancel_startup,utc_download_cancel_cleanup},
	{"utc_download_cancel_n1",utc_download_cancel_n1,utc_download_cancel_startup,utc_download_cancel_cleanup},
	{"utc_download_remove_http_header_field_p1",utc_download_remove_http_header_field_p1,utc_download_remove_http_header_field_startup,utc_download_remove_http_header_field_cleanup},
	{"utc_download_remove_http_header_field_n1",utc_download_remove_http_header_field_n1,utc_download_remove_http_header_field_startup,utc_download_remove_http_header_field_cleanup},
	{"utc_download_remove_http_header_field_n2",utc_download_remove_http_header_field_n2,utc_download_remove_http_header_field_startup,utc_download_remove_http_header_field_cleanup},
	{"utc_download_remove_http_header_field_n3",utc_download_remove_http_header_field_n3,utc_download_remove_http_header_field_startup,utc_download_remove_http_header_field_cleanup},
	{"utc_download_set_auto_download_p1",utc_download_set_auto_download_p1,utc_download_set_auto_download_startup,utc_download_set_auto_download_cleanup},
	{"utc_download_set_auto_download_n1",utc_download_set_auto_download_n1,utc_download_set_auto_download_startup,utc_download_set_auto_download_cleanup},
	{"utc_download_set_destination_p1",utc_download_set_destination_p1,utc_download_set_destination_startup,utc_download_set_destination_cleanup},
	{"utc_download_set_destination_n1",utc_download_set_destination_n1,utc_download_set_destination_startup,utc_download_set_destination_cleanup},
	{"utc_download_set_destination_n2",utc_download_set_destination_n2,utc_download_set_destination_startup,utc_download_set_destination_cleanup},
	{"utc_download_set_file_name_p1",utc_download_set_file_name_p1,utc_download_set_file_name_startup,utc_download_set_file_name_cleanup},
	{"utc_download_set_file_name_n1",utc_download_set_file_name_n1,utc_download_set_file_name_startup,utc_download_set_file_name_cleanup},
	{"utc_download_set_file_name_n2",utc_download_set_file_name_n2,utc_download_set_file_name_startup,utc_download_set_file_name_cleanup},
	{"utc_download_set_network_type_p1",utc_download_set_network_type_p1,utc_download_set_network_type_startup,utc_download_set_network_type_cleanup},
	{"utc_download_set_network_type_n1",utc_download_set_network_type_n1,utc_download_set_network_type_startup,utc_download_set_network_type_cleanup},
	{"utc_download_set_network_type_n2",utc_download_set_network_type_n2,utc_download_set_network_type_startup,utc_download_set_network_type_cleanup},
	{"utc_download_set_notification_app_control_p1",utc_download_set_notification_app_control_p1,utc_download_set_notification_app_control_startup,utc_download_set_notification_app_control_cleanup},
	{"utc_download_set_notification_app_control_n1",utc_download_set_notification_app_control_n1,utc_download_set_notification_app_control_startup,utc_download_set_notification_app_control_cleanup},
	{"utc_download_set_notification_app_control_n2",utc_download_set_notification_app_control_n2,utc_download_set_notification_app_control_startup,utc_download_set_notification_app_control_cleanup},
	{"utc_download_set_notification_app_control_n3",utc_download_set_notification_app_control_n3,utc_download_set_notification_app_control_startup,utc_download_set_notification_app_control_cleanup},
	{"utc_download_set_notification_description_p1",utc_download_set_notification_description_p1,utc_download_set_notification_description_startup,utc_download_set_notification_description_cleanup},
	{"utc_download_set_notification_description_n1",utc_download_set_notification_description_n1,utc_download_set_notification_description_startup,utc_download_set_notification_description_cleanup},
	{"utc_download_set_notification_description_n2",utc_download_set_notification_description_n2,utc_download_set_notification_description_startup,utc_download_set_notification_description_cleanup},
	{"utc_download_set_notification_description_n3",utc_download_set_notification_description_n3,utc_download_set_notification_description_startup,utc_download_set_notification_description_cleanup},
	{"utc_download_set_notification_title_p1",utc_download_set_notification_title_p1,utc_download_set_notification_title_startup,utc_download_set_notification_title_cleanup},
	{"utc_download_set_notification_title_n1",utc_download_set_notification_title_n1,utc_download_set_notification_title_startup,utc_download_set_notification_title_cleanup},
	{"utc_download_set_notification_title_n2",utc_download_set_notification_title_n2,utc_download_set_notification_title_startup,utc_download_set_notification_title_cleanup},
	{"utc_download_set_notification_title_n3",utc_download_set_notification_title_n3,utc_download_set_notification_title_startup,utc_download_set_notification_title_cleanup},
	{"utc_download_set_notification_type_p1",utc_download_set_notification_type_p1,utc_download_set_notification_type_startup,utc_download_set_notification_type_cleanup},
	{"utc_download_set_notification_type_n1",utc_download_set_notification_type_n1,utc_download_set_notification_type_startup,utc_download_set_notification_type_cleanup},
	{"utc_download_set_notification_type_n2",utc_download_set_notification_type_n2,utc_download_set_notification_type_startup,utc_download_set_notification_type_cleanup},
	{"utc_download_set_progress_cb_p1",utc_download_set_progress_cb_p1,utc_download_set_progress_cb_startup,utc_download_set_progress_cb_cleanup},
	{"utc_download_set_progress_cb_n1",utc_download_set_progress_cb_n1,utc_download_set_progress_cb_startup,utc_download_set_progress_cb_cleanup},
	{"utc_download_set_state_changed_cb_p1",utc_download_set_state_changed_cb_p1,utc_download_set_state_changed_cb_startup,utc_download_set_state_changed_cb_cleanup},
	{"utc_download_set_state_changed_cb_n1",utc_download_set_state_changed_cb_n1,utc_download_set_state_changed_cb_startup,utc_download_set_state_changed_cb_cleanup},
	{"utc_download_set_temp_file_path_p1",utc_download_set_temp_file_path_p1,utc_download_set_temp_path_startup,utc_download_set_temp_path_cleanup},
	{"utc_download_set_temp_file_path_n1",utc_download_set_temp_file_path_n1,utc_download_set_temp_path_startup,utc_download_set_temp_path_cleanup},
	{"utc_download_set_temp_file_path_n2",utc_download_set_temp_file_path_n2,utc_download_set_temp_path_startup,utc_download_set_temp_path_cleanup},
	{"utc_download_set_url_p1",utc_download_set_url_p1,utc_download_set_url_startup,utc_download_set_url_cleanup},
	{"utc_download_set_url_n1",utc_download_set_url_n1,utc_download_set_url_startup,utc_download_set_url_cleanup},
	{"utc_download_set_url_n2",utc_download_set_url_n2,utc_download_set_url_startup,utc_download_set_url_cleanup},
	{"utc_download_start_p1",utc_download_start_p1,utc_download_start_startup,utc_download_start_cleanup},
	{"utc_download_start_n1",utc_download_start_n1,utc_download_start_startup,utc_download_start_cleanup},
	{"utc_download_unset_progress_cb_p1",utc_download_unset_progress_cb_p1,utc_download_unset_progress_cb_startup,utc_download_unset_progress_cb_cleanup},
	{"utc_download_unset_progress_cb_n1",utc_download_unset_progress_cb_n1,utc_download_unset_progress_cb_startup,utc_download_unset_progress_cb_cleanup},
	{"utc_url_download_unset_state_changed_cb_p1",utc_url_download_unset_state_changed_cb_p1,utc_url_download_unset_state_changed_cb_startup,utc_url_download_unset_state_changed_cb_cleanup},
	{"utc_url_download_unset_state_changed_cb_n1",utc_url_download_unset_state_changed_cb_n1,utc_url_download_unset_state_changed_cb_startup,utc_url_download_unset_state_changed_cb_cleanup},
	{NULL, NULL}
};

#endif // __TCT_URL-DOWNLOAD-NATIVE_H__
