#ifndef _UTC_DALI_PROPERTYCONDITION_COMMON_H_
#define _UTC_DALI_PROPERTYCONDITION_COMMON_H_

#include "dali-common.h"

using namespace Dali;

#define SUITE_NAME  "PROPERTY_CONDITION_UTC"
#define ARGUMENT_INDEX_ZERO  0
#define ARGUMENT_INDEX_ONE  1

#endif  //_UTC_DALI_PROPERTYNOTIFICATION_COMMON_H_
