//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WIFI_MANAGER_NATIVE_H__
#define __TCT_WIFI_MANAGER_NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_wifi_manager_startup(void);
extern void ITs_wifi_manager_cleanup(void);
extern void ITs_wifi_manager_ap_startup(void);
extern void ITs_wifi_manager_ap_cleanup(void);
extern void ITs_wifi_manager_config_startup(void);
extern void ITs_wifi_manager_config_cleanup(void);
extern void ITs_wifi_manager_tdls_startup(void);
extern void ITs_wifi_manager_tdls_cleanup(void);

extern int ITc_wifi_manager_get_connected_forget_refresh_ap_p(void);
extern int ITc_wifi_manager_connect_hidden_ap_p(void);
extern int ITc_wifi_manager_initialize_deinitialize_p(void);
extern int ITc_wifi_manager_connect_disconnect_p(void);
extern int ITc_wifi_manager_foreach_found_ap_p(void);
extern int ITc_wifi_manager_get_connection_state_p(void);
extern int ITc_wifi_manager_get_mac_address_p(void);
extern int ITc_wifi_manager_scan_specific_ap_p(void);
extern int ITc_wifi_manager_get_network_interface_name_p(void);
extern int ITc_wifi_manager_set_unset_device_state_changed_cb_p(void);
extern int ITc_wifi_manager_set_unset_connection_state_changed_cb_p(void);
extern int ITc_wifi_manager_set_unset_rssi_level_changed_cb_p(void);
extern int ITc_wifi_manager_is_5ghz_band_supported_p(void);
extern int ITc_wifi_manager_specific_scan_get_max_ssids_p(void);

extern int ITc_wifi_manager_scanned_callback_p(void);
extern int ITc_wifi_manager_ap_create_destroy_p(void);
extern int ITc_wifi_manager_ap_hidden_create_p(void);
extern int ITc_wifi_manager_ap_clone_p(void);
extern int ITc_wifi_manager_ap_get_essid_p(void);
extern int ITc_wifi_manager_ap_get_bssid_p(void);
extern int ITc_wifi_manager_ap_get_rssi_p(void);
extern int ITc_wifi_manager_ap_get_rssi_level_p(void);
extern int ITc_wifi_manager_ap_get_frequency_p(void);
extern int ITc_wifi_manager_ap_get_max_speed_p(void);
extern int ITc_wifi_manager_ap_is_favorite_p(void);
extern int ITc_wifi_manager_ap_is_passpoint_p(void);
extern int ITc_wifi_manager_ap_get_connection_state_p(void);
extern int ITc_wifi_manager_ap_get_ip_config_type_p(void);
extern int ITc_wifi_manager_ap_set_ip_config_type_p(void);
extern int ITc_wifi_manager_ap_set_get_ip_address_p(void);
extern int ITc_wifi_manager_ap_set_get_subnet_mask_p(void);
extern int ITc_wifi_manager_ap_set_get_gateway_address_p(void);
extern int ITc_wifi_manager_ap_set_get_proxy_address_p(void);
extern int ITc_wifi_manager_ap_set_get_proxy_type_p(void);
extern int ITc_wifi_manager_ap_set_get_dns_address_p(void);
extern int ITc_wifi_manager_ap_set_get_security_type_p(void);
extern int ITc_wifi_manager_ap_set_get_encryption_type_p(void);
extern int ITc_wifi_manager_ap_is_passphrase_required_p(void);
extern int ITc_wifi_manager_ap_set_passphrase_p(void);
extern int ITc_wifi_manager_ap_is_wps_supported_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_passphrase_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_ca_cert_file_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_client_cert_file_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_private_key_info_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_type_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_auth_type_p(void);
extern int ITc_wifi_manager_connect_by_wps_pbc_p(void);
extern int ITc_wifi_manager_connect_by_wps_pin_p(void);
extern int ITc_wifi_manager_update_ap_p(void);
extern int ITc_wifi_manager_config_create_destroy_p(void);
extern int ITc_wifi_manager_config_save_remove_p(void);
extern int ITc_wifi_manager_config_foreach_configuration_p(void);
extern int ITc_wifi_manager_config_clone_p(void);
extern int ITc_wifi_manager_config_get_name_p(void);
extern int ITc_wifi_manager_config_get_security_type_p(void);
extern int ITc_wifi_manager_config_set_get_proxy_address_p(void);
extern int ITc_wifi_manager_config_set_get_hidden_ap_property_p(void);
extern int ITc_wifi_manager_config_set_get_eap_anonymous_identity_p(void);
extern int ITc_wifi_manager_config_set_get_eap_ca_cert_file_p(void);
extern int ITc_wifi_manager_config_set_get_eap_client_cert_file_p(void);
extern int ITc_wifi_manager_config_set_get_eap_identity_p(void);
extern int ITc_wifi_manager_config_set_get_eap_type_p(void);
extern int ITc_wifi_manager_config_set_get_eap_auth_type_p(void);
extern int ITc_wifi_manager_config_set_get_eap_subject_match_p(void);
extern int ITc_wifi_manager_config_set_get_eap_private_key_info_p(void);
extern int ITc_wifi_manager_foreach_found_specific_ap_p(void);
extern int ITc_wifi_manager_activate_deactivate_p(void);
extern int ITc_wifi_manager_activate_with_wifi_picker_tested_p(void);
extern int ITc_wifi_manager_ap_set_get_prefix_length_p(void);
extern int ITc_wifi_manager_ap_set_get_dns_config_type_p(void);
extern int ITc_wifi_manager_ap_foreach_ipv6_address_p(void);
extern int ITc_wifi_manager_ap_get_raw_ssid_p(void);
extern int ITc_wifi_manager_get_scan_state_p(void);
extern int ITc_wifi_manager_set_unset_scan_state_changed_cb_p(void);
extern int ITc_wifi_manager_bssid_scan_p(void);
extern int ITc_wifi_manager_foreach_found_bssid_ap_p(void);
extern int ITc_wifi_manager_ap_get_dhcp_server_address_p(void);
extern int ITc_wifi_manager_ap_get_error_state_p(void);
extern int ITc_wifi_manager_ap_get_dhcp_lease_duration_p(void);
extern int ITc_wifi_manager_specific_ap_start_multi_scan_p(void);
extern int ITc_wifi_manager_specific_scan_set_freq_p(void);
extern int ITc_wifi_manager_specific_scan_set_ssid_p(void);
extern int ITc_wifi_manager_specific_scan_create_and_destroy_p(void);
extern int ITc_wifi_manager_ap_get_assoc_status_code_p(void);
extern int ITc_wifi_manager_set_ip_conflict_detect_enable_p(void);
extern int ITc_wifi_manager_ip_conflict_detect_is_enabled_p(void);
extern int ITc_wifi_manager_get_ip_conflict_state_p(void);
extern int ITc_wifi_manager_add_remove_vsie_p(void);
extern int ITc_wifi_manager_get_vsie_p(void);
extern int ITc_wifi_manager_ap_foreach_vsie_p(void);
extern int ITc_wifi_manager_config_set_get_ip_config_type_p(void);
extern int ITc_wifi_manager_config_set_get_ip_address_p(void);
extern int ITc_wifi_manager_config_set_get_subnet_mask_p(void);
extern int ITc_wifi_manager_config_set_get_prefix_length_p(void);
extern int ITc_wifi_manager_config_set_get_gateway_address_p(void);
extern int ITc_wifi_manager_config_set_get_dns_config_type_p(void);
extern int ITc_wifi_manager_config_set_get_dns_address_p(void);
extern int ITc_wifi_manager_ap_set_get_eap_anonymous_identity_p(void);
extern int ITc_wifi_manager_ap_is_hidden_p(void);

testcase tc_array[] = {
	{"ITc_wifi_manager_get_connected_forget_refresh_ap_p", ITc_wifi_manager_get_connected_forget_refresh_ap_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_connect_hidden_ap_p",ITc_wifi_manager_connect_hidden_ap_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_initialize_deinitialize_p", ITc_wifi_manager_initialize_deinitialize_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_connect_disconnect_p", ITc_wifi_manager_connect_disconnect_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_foreach_vsie_p", ITc_wifi_manager_ap_foreach_vsie_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_foreach_found_ap_p", ITc_wifi_manager_foreach_found_ap_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_get_connection_state_p", ITc_wifi_manager_get_connection_state_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_get_mac_address_p", ITc_wifi_manager_get_mac_address_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_scan_specific_ap_p", ITc_wifi_manager_scan_specific_ap_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_get_network_interface_name_p", ITc_wifi_manager_get_network_interface_name_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_set_unset_device_state_changed_cb_p", ITc_wifi_manager_set_unset_device_state_changed_cb_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_set_unset_connection_state_changed_cb_p", ITc_wifi_manager_set_unset_connection_state_changed_cb_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_set_unset_rssi_level_changed_cb_p", ITc_wifi_manager_set_unset_rssi_level_changed_cb_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_is_5ghz_band_supported_p", ITc_wifi_manager_is_5ghz_band_supported_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_specific_scan_get_max_ssids_p", ITc_wifi_manager_specific_scan_get_max_ssids_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_scanned_callback_p", ITc_wifi_manager_scanned_callback_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_add_remove_vsie_p", ITc_wifi_manager_add_remove_vsie_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_get_vsie_p", ITc_wifi_manager_get_vsie_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_ap_create_destroy_p", ITc_wifi_manager_ap_create_destroy_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_hidden_create_p", ITc_wifi_manager_ap_hidden_create_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_clone_p", ITc_wifi_manager_ap_clone_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_essid_p", ITc_wifi_manager_ap_get_essid_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_bssid_p", ITc_wifi_manager_ap_get_bssid_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_rssi_p", ITc_wifi_manager_ap_get_rssi_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_rssi_level_p", ITc_wifi_manager_ap_get_rssi_level_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_frequency_p", ITc_wifi_manager_ap_get_frequency_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_max_speed_p", ITc_wifi_manager_ap_get_max_speed_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_is_favorite_p", ITc_wifi_manager_ap_is_favorite_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_is_passpoint_p", ITc_wifi_manager_ap_is_passpoint_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_connection_state_p", ITc_wifi_manager_ap_get_connection_state_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_ip_config_type_p", ITc_wifi_manager_ap_get_ip_config_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_ip_config_type_p", ITc_wifi_manager_ap_set_ip_config_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_ip_address_p", ITc_wifi_manager_ap_set_get_ip_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_subnet_mask_p", ITc_wifi_manager_ap_set_get_subnet_mask_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_gateway_address_p", ITc_wifi_manager_ap_set_get_gateway_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_proxy_address_p", ITc_wifi_manager_ap_set_get_proxy_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_proxy_type_p", ITc_wifi_manager_ap_set_get_proxy_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_dns_address_p", ITc_wifi_manager_ap_set_get_dns_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_security_type_p", ITc_wifi_manager_ap_set_get_security_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_encryption_type_p", ITc_wifi_manager_ap_set_get_encryption_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_is_passphrase_required_p", ITc_wifi_manager_ap_is_passphrase_required_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_passphrase_p", ITc_wifi_manager_ap_set_passphrase_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_is_wps_supported_p", ITc_wifi_manager_ap_is_wps_supported_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_passphrase_p", ITc_wifi_manager_ap_set_get_eap_passphrase_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_ca_cert_file_p", ITc_wifi_manager_ap_set_get_eap_ca_cert_file_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_client_cert_file_p", ITc_wifi_manager_ap_set_get_eap_client_cert_file_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_private_key_info_p", ITc_wifi_manager_ap_set_get_eap_private_key_info_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_type_p", ITc_wifi_manager_ap_set_get_eap_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_auth_type_p", ITc_wifi_manager_ap_set_get_eap_auth_type_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_connect_by_wps_pbc_p", ITc_wifi_manager_connect_by_wps_pbc_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_connect_by_wps_pin_p", ITc_wifi_manager_connect_by_wps_pin_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_update_ap_p", ITc_wifi_manager_update_ap_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_config_create_destroy_p", ITc_wifi_manager_config_create_destroy_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_save_remove_p", ITc_wifi_manager_config_save_remove_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_foreach_configuration_p", ITc_wifi_manager_config_foreach_configuration_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_clone_p", ITc_wifi_manager_config_clone_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_get_name_p", ITc_wifi_manager_config_get_name_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_get_security_type_p", ITc_wifi_manager_config_get_security_type_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_proxy_address_p", ITc_wifi_manager_config_set_get_proxy_address_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_hidden_ap_property_p", ITc_wifi_manager_config_set_get_hidden_ap_property_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_anonymous_identity_p", ITc_wifi_manager_config_set_get_eap_anonymous_identity_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_ca_cert_file_p", ITc_wifi_manager_config_set_get_eap_ca_cert_file_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_client_cert_file_p", ITc_wifi_manager_config_set_get_eap_client_cert_file_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_identity_p", ITc_wifi_manager_config_set_get_eap_identity_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_auth_type_p", ITc_wifi_manager_config_set_get_eap_auth_type_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_type_p", ITc_wifi_manager_config_set_get_eap_type_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_subject_match_p", ITc_wifi_manager_config_set_get_eap_subject_match_p, ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_foreach_found_specific_ap_p", ITc_wifi_manager_foreach_found_specific_ap_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_ap_set_get_eap_anonymous_identity_p",ITc_wifi_manager_ap_set_get_eap_anonymous_identity_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
    	{"ITc_wifi_manager_activate_deactivate_p", ITc_wifi_manager_activate_deactivate_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_activate_with_wifi_picker_tested_p", ITc_wifi_manager_activate_with_wifi_picker_tested_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_ap_set_get_prefix_length_p", ITc_wifi_manager_ap_set_get_prefix_length_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_set_get_dns_config_type_p", ITc_wifi_manager_ap_set_get_dns_config_type_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_foreach_ipv6_address_p",ITc_wifi_manager_ap_foreach_ipv6_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_raw_ssid_p",ITc_wifi_manager_ap_get_raw_ssid_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_get_scan_state_p",ITc_wifi_manager_get_scan_state_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_set_unset_scan_state_changed_cb_p",ITc_wifi_manager_set_unset_scan_state_changed_cb_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_bssid_scan_p",ITc_wifi_manager_bssid_scan_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_foreach_found_bssid_ap_p",ITc_wifi_manager_foreach_found_bssid_ap_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_ap_get_dhcp_server_address_p",ITc_wifi_manager_ap_get_dhcp_server_address_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_error_state_p",ITc_wifi_manager_ap_get_error_state_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_dhcp_lease_duration_p", ITc_wifi_manager_ap_get_dhcp_lease_duration_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_specific_scan_create_and_destroy_p",ITc_wifi_manager_specific_scan_create_and_destroy_p, ITs_wifi_manager_startup, ITs_wifi_manager_cleanup},
	{"ITc_wifi_manager_specific_scan_set_ssid_p",ITc_wifi_manager_specific_scan_set_ssid_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_specific_scan_set_freq_p",ITc_wifi_manager_specific_scan_set_freq_p, ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_specific_ap_start_multi_scan_p", ITc_wifi_manager_specific_ap_start_multi_scan_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_ap_get_assoc_status_code_p", ITc_wifi_manager_ap_get_assoc_status_code_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_set_ip_conflict_detect_enable_p", ITc_wifi_manager_set_ip_conflict_detect_enable_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
        {"ITc_wifi_manager_ip_conflict_detect_is_enabled_p", ITc_wifi_manager_ip_conflict_detect_is_enabled_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
        {"ITc_wifi_manager_get_ip_conflict_state_p", ITc_wifi_manager_get_ip_conflict_state_p,ITs_wifi_manager_ap_startup, ITs_wifi_manager_ap_cleanup},
	{"ITc_wifi_manager_config_set_get_eap_private_key_info_p", ITc_wifi_manager_config_set_get_eap_private_key_info_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_ip_config_type_p",ITc_wifi_manager_config_set_get_ip_config_type_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_ip_address_p",ITc_wifi_manager_config_set_get_ip_address_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_subnet_mask_p",ITc_wifi_manager_config_set_get_subnet_mask_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_prefix_length_p",ITc_wifi_manager_config_set_get_prefix_length_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_gateway_address_p",ITc_wifi_manager_config_set_get_gateway_address_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_dns_config_type_p",ITc_wifi_manager_config_set_get_dns_config_type_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_config_set_get_dns_address_p",ITc_wifi_manager_config_set_get_dns_address_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{"ITc_wifi_manager_ap_is_hidden_p",ITc_wifi_manager_ap_is_hidden_p,ITs_wifi_manager_config_startup, ITs_wifi_manager_config_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WIFI_MANAGER_NATIVE_H__
