//
// Copyright (c) 2019 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_AUTOFILL-NATIVE_H__
#define __TCT_AUTOFILL-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_autofill_startup(void);
extern void ITs_autofill_cleanup(void);
extern void ITs_autofill_service_startup(void);
extern void ITs_autofill_service_cleanup(void);

extern int ITc_autofill_item_create_destroy_p(void);
extern int ITc_autofill_item_clone_p(void);
extern int ITc_autofill_item_set_get_autofill_hint_p(void);
extern int ITc_autofill_item_set_get_id_p(void);
extern int ITc_autofill_item_set_get_label_p(void);
extern int ITc_autofill_item_set_get_sensitive_data_p(void);
extern int ITc_autofill_item_set_get_value_p(void);
extern int ITc_autofill_auth_info_create_destroy_p(void);
extern int ITc_autofill_auth_info_set_get_app_id_p(void);
extern int ITc_autofill_auth_info_set_get_view_id_p(void);
extern int ITc_autofill_auth_info_set_get_autofill_data_present_p(void);
extern int ITc_autofill_auth_info_set_get_authentication_needed_p(void);
extern int ITc_autofill_auth_info_set_get_service_name_p(void);
extern int ITc_autofill_auth_info_set_get_service_message_p(void);
extern int ITc_autofill_auth_info_set_get_service_logo_image_path_p(void);
extern int ITc_autofill_view_info_create_destroy_p(void);
extern int ITc_autofill_view_info_set_get_app_id_p(void);
extern int ITc_autofill_view_info_set_get_view_id_p(void);
extern int ITc_autofill_view_info_add_item_p(void);
extern int ITc_autofill_view_info_foreach_item_p(void);
extern int ITc_autofill_save_view_info_create_destroy_p(void);
extern int ITc_autofill_save_view_info_set_get_app_id_p(void);
extern int ITc_autofill_save_view_info_set_get_view_id_p(void);
extern int ITc_autofill_save_view_info_add_item_p(void);
extern int ITc_autofill_save_view_info_foreach_item_p(void);
extern int ITc_autofill_fill_response_create_destroy_p(void);
extern int ITc_autofill_fill_response_set_get_app_id_p(void);
extern int ITc_autofill_fill_response_set_get_view_id_p(void);
extern int ITc_autofill_fill_response_add_group_p(void);
extern int ITc_autofill_fill_response_foreach_group_p(void);
extern int ITc_autofill_fill_response_get_group_count_p(void);
extern int ITc_autofill_fill_response_group_create_destroy_p(void);
extern int ITc_autofill_fill_response_group_clone_p(void);
extern int ITc_autofill_fill_response_group_add_item_p(void);
extern int ITc_autofill_fill_response_group_foreach_item_p(void);
extern int ITc_autofill_fill_response_item_create_destroy_p(void);
extern int ITc_autofill_fill_response_item_clone_p(void);
extern int ITc_autofill_fill_response_item_set_get_id_p(void);
extern int ITc_autofill_fill_response_item_set_get_value_p(void);
extern int ITc_autofill_fill_response_item_set_get_p(void);
extern int ITc_autofill_fill_response_item_set_get_presentation_text_p(void);
extern int ITc_autofill_save_item_create_destroy_p(void);
extern int ITc_autofill_save_item_clone_p(void);
extern int ITc_autofill_save_item_set_get_autofill_hint_p(void);
extern int ITc_autofill_save_item_set_get_id_p(void);
extern int ITc_autofill_save_item_set_get_label_p(void);
extern int ITc_autofill_save_item_set_get_sensitive_data_p(void);
extern int ITc_autofill_save_item_set_get_value_p(void);
extern int ITc_autofill_create_destroy_p(void);
extern int ITc_autofill_connect_p(void);
extern int ITc_autofill_auth_info_set_unset_received_cb_p(void);
extern int ITc_autofill_fill_request_p(void);
extern int ITc_autofill_fill_response_set_unset_received_cb_p(void);
extern int ITc_autofill_commit_p(void);
extern int ITc_autofill_service_initialize_deinitialize_p(void);
extern int ITc_autofill_service_set_unset_auth_info_requested_cb_p(void);
extern int ITc_autofill_service_set_unset_fill_requested_cb_p(void);
extern int ITc_autofill_service_set_unset_committed_cb_p(void);
extern int ITc_autofill_service_set_unset_terminate_received_cb_p(void);
extern int ITc_autofill_auth_info_request_p(void);
extern int ITc_autofill_error_info_create_destroy_p(void);
extern int ITc_autofill_error_info_set_get_app_id_p(void);
extern int ITc_autofill_error_info_set_get_error_code_p(void);
extern int ITc_autofill_error_info_set_unset_received_cb_p(void);
extern int ITc_autofill_save_view_info_set_get_view_title_p(void);
extern int ITc_autofill_fill_response_item_set_get_autofill_hint_p(void);
extern int ITc_autofill_view_info_cancel_fill_request_p(void);
extern int ITc_autofill_service_set_unset_cancel_fill_requested_cb_p(void);

testcase tc_array[] = {
	{"ITc_autofill_item_create_destroy_p",ITc_autofill_item_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_clone_p",ITc_autofill_item_clone_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_set_get_autofill_hint_p",ITc_autofill_item_set_get_autofill_hint_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_set_get_id_p",ITc_autofill_item_set_get_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_set_get_label_p",ITc_autofill_item_set_get_label_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_set_get_sensitive_data_p",ITc_autofill_item_set_get_sensitive_data_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_item_set_get_value_p",ITc_autofill_item_set_get_value_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_create_destroy_p",ITc_autofill_auth_info_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_app_id_p",ITc_autofill_auth_info_set_get_app_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_view_id_p",ITc_autofill_auth_info_set_get_view_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_autofill_data_present_p",ITc_autofill_auth_info_set_get_autofill_data_present_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_authentication_needed_p",ITc_autofill_auth_info_set_get_authentication_needed_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_service_name_p",ITc_autofill_auth_info_set_get_service_name_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_service_message_p",ITc_autofill_auth_info_set_get_service_message_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_get_service_logo_image_path_p", ITc_autofill_auth_info_set_get_service_logo_image_path_p, ITs_autofill_startup, ITs_autofill_cleanup},
	{"ITc_autofill_view_info_create_destroy_p",ITc_autofill_view_info_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_view_info_set_get_app_id_p",ITc_autofill_view_info_set_get_app_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_view_info_set_get_view_id_p",ITc_autofill_view_info_set_get_view_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_view_info_add_item_p", ITc_autofill_view_info_add_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_view_info_foreach_item_p", ITc_autofill_view_info_foreach_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_create_destroy_p", ITc_autofill_save_view_info_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_set_get_app_id_p", ITc_autofill_save_view_info_set_get_app_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_view_info_cancel_fill_request_p", ITc_autofill_view_info_cancel_fill_request_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_set_get_view_id_p", ITc_autofill_save_view_info_set_get_view_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_add_item_p", ITc_autofill_save_view_info_add_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_foreach_item_p", ITc_autofill_save_view_info_foreach_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_create_destroy_p", ITc_autofill_fill_response_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_set_get_app_id_p", ITc_autofill_fill_response_set_get_app_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_set_get_view_id_p", ITc_autofill_fill_response_set_get_view_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_add_group_p", ITc_autofill_fill_response_add_group_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_foreach_group_p", ITc_autofill_fill_response_foreach_group_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_get_group_count_p", ITc_autofill_fill_response_get_group_count_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_group_create_destroy_p", ITc_autofill_fill_response_group_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_group_clone_p", ITc_autofill_fill_response_group_clone_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_group_add_item_p", ITc_autofill_fill_response_group_add_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_group_foreach_item_p", ITc_autofill_fill_response_group_foreach_item_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_create_destroy_p", ITc_autofill_fill_response_item_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_clone_p", ITc_autofill_fill_response_item_clone_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_set_get_id_p", ITc_autofill_fill_response_item_set_get_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_set_get_value_p", ITc_autofill_fill_response_item_set_get_value_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_set_get_presentation_text_p", ITc_autofill_fill_response_item_set_get_presentation_text_p, ITs_autofill_startup, ITs_autofill_cleanup},
	{"ITc_autofill_save_item_create_destroy_p", ITc_autofill_save_item_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_clone_p", ITc_autofill_save_item_clone_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_set_get_autofill_hint_p", ITc_autofill_save_item_set_get_autofill_hint_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_set_get_id_p", ITc_autofill_save_item_set_get_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_set_get_label_p", ITc_autofill_save_item_set_get_label_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_set_get_sensitive_data_p", ITc_autofill_save_item_set_get_sensitive_data_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_item_set_get_value_p", ITc_autofill_save_item_set_get_value_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_create_destroy_p", ITc_autofill_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_connect_p", ITc_autofill_connect_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_auth_info_set_unset_received_cb_p", ITc_autofill_auth_info_set_unset_received_cb_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_request_p", ITc_autofill_fill_request_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_set_unset_received_cb_p", ITc_autofill_fill_response_set_unset_received_cb_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_commit_p", ITc_autofill_commit_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_service_initialize_deinitialize_p", ITc_autofill_service_initialize_deinitialize_p,ITs_autofill_service_startup,ITs_autofill_service_cleanup},
	{"ITc_autofill_service_set_unset_auth_info_requested_cb_p", ITc_autofill_service_set_unset_auth_info_requested_cb_p, ITs_autofill_service_startup, ITs_autofill_service_cleanup},
	{"ITc_autofill_service_set_unset_fill_requested_cb_p", ITc_autofill_service_set_unset_fill_requested_cb_p, ITs_autofill_service_startup, ITs_autofill_service_cleanup},
	{"ITc_autofill_service_set_unset_committed_cb_p", ITc_autofill_service_set_unset_committed_cb_p,ITs_autofill_service_startup,ITs_autofill_service_cleanup},
	{"ITc_autofill_service_set_unset_terminate_received_cb_p",  ITc_autofill_service_set_unset_terminate_received_cb_p, ITs_autofill_service_startup, ITs_autofill_service_cleanup},
	{"ITc_autofill_auth_info_request_p", ITc_autofill_auth_info_request_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_error_info_create_destroy_p", ITc_autofill_error_info_create_destroy_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_error_info_set_get_app_id_p", ITc_autofill_error_info_set_get_app_id_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_error_info_set_get_error_code_p", ITc_autofill_error_info_set_get_error_code_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_error_info_set_unset_received_cb_p", ITc_autofill_error_info_set_unset_received_cb_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_save_view_info_set_get_view_title_p", ITc_autofill_save_view_info_set_get_view_title_p,ITs_autofill_startup,ITs_autofill_cleanup},
	{"ITc_autofill_fill_response_item_set_get_autofill_hint_p", ITc_autofill_fill_response_item_set_get_autofill_hint_p, ITs_autofill_startup, ITs_autofill_cleanup},
	{"ITc_autofill_service_set_unset_cancel_fill_requested_cb_p",  ITc_autofill_service_set_unset_cancel_fill_requested_cb_p, ITs_autofill_service_startup, ITs_autofill_service_cleanup},
	{NULL, NULL}
};

#endif // __TCT_AUTOFILL-NATIVE_H__
