//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_PLAYER-NATIVE_H__
#define __TCT_PLAYER-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_media_player_display_startup(void);
extern void utc_media_player_display_cleanup(void);
extern int utc_media_player_get_video_size_p(void);
extern int utc_media_player_get_video_size_n(void);
extern int utc_media_player_set_display_p(void);
extern int utc_media_player_set_display_p2(void);
extern int utc_media_player_set_display_p3(void);
extern int utc_media_player_set_display_n(void);
extern int utc_media_player_set_display_n2(void);
extern int utc_media_player_capture_video_p(void);
extern int utc_media_player_capture_video_n(void);
extern int utc_media_player_capture_video_n2(void);
extern int utc_media_player_get_video_stream_info_p(void);
extern int utc_media_player_get_video_stream_info_n(void);
extern int utc_media_player_get_video_stream_info_n2(void);
extern int utc_media_player_set_audio_only_p(void);
extern int utc_media_player_set_audio_only_n(void);
extern int utc_media_player_is_audio_only_p(void);
extern int utc_media_player_is_audio_only_n(void);
extern int utc_media_player_360_is_content_spherical_p(void);
extern int utc_media_player_360_is_content_spherical_n(void);
extern int utc_media_player_360_set_get_enable_p(void);
extern int utc_media_player_360_is_enabled_n(void);
extern int utc_media_player_360_set_get_direction_of_view_p(void);
extern int utc_media_player_360_set_direction_of_view_n(void);
extern int utc_media_player_360_get_direction_of_view_n(void);
extern int utc_media_player_360_set_get_zoom_p(void);
extern int utc_media_player_360_set_zoom_n(void);
extern int utc_media_player_360_get_zoom_n(void);
extern int utc_media_player_360_set_get_field_of_view_p(void);
extern int utc_media_player_360_set_field_of_view_n(void);
extern int utc_media_player_360_get_field_of_view_n(void);
extern int utc_media_player_360_set_zoom_with_field_of_view_p(void);
extern int utc_media_player_360_set_zoom_with_field_of_view_n(void);
extern int utc_media_player_set_video_roi_area_p(void);
extern int utc_media_player_set_video_roi_area_n(void);
extern int utc_media_player_get_video_roi_area_p(void);
extern int utc_media_player_get_video_roi_area_n(void);
extern int utc_media_player_set_display_visible_p(void);
extern int utc_media_player_set_display_visible_n(void);
extern int utc_media_player_is_display_visible_p(void);
extern int utc_media_player_is_display_visible_n(void);
extern int utc_media_player_set_display_mode_p(void);
extern int utc_media_player_set_display_mode_n(void);
extern int utc_media_player_get_display_mode_p(void);
extern int utc_media_player_get_display_mode_n(void);
extern int utc_media_player_set_display_roi_area_p(void);
extern int utc_media_player_set_display_roi_area_n(void);
extern int utc_media_player_set_display_rotation_p(void);
extern int utc_media_player_set_display_rotation_n(void);
extern int utc_media_player_get_display_rotation_p(void);
extern int utc_media_player_get_display_rotation_n(void);
extern int utc_media_player_set_video_stream_changed_cb_p(void);
extern int utc_media_player_set_video_stream_changed_cb_n(void);
extern int utc_media_player_set_video_stream_changed_cb_n2(void);
extern int utc_media_player_unset_video_stream_changed_cb_p(void);
extern int utc_media_player_unset_video_stream_changed_cb_n(void);

testcase tc_array[] = {
	{"utc_media_player_get_video_size_p",utc_media_player_get_video_size_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_size_n",utc_media_player_get_video_size_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_p",utc_media_player_set_display_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_p2",utc_media_player_set_display_p2,utc_media_player_display_startup,utc_media_player_display_cleanup},
       {"utc_media_player_set_display_p3",utc_media_player_set_display_p3,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_n",utc_media_player_set_display_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_n2",utc_media_player_set_display_n2,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_capture_video_p",utc_media_player_capture_video_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_capture_video_n",utc_media_player_capture_video_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_capture_video_n2",utc_media_player_capture_video_n2,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_stream_info_p",utc_media_player_get_video_stream_info_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_stream_info_n",utc_media_player_get_video_stream_info_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_stream_info_n2",utc_media_player_get_video_stream_info_n2,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_audio_only_p",utc_media_player_set_audio_only_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_audio_only_n",utc_media_player_set_audio_only_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_is_audio_only_p",utc_media_player_is_audio_only_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_is_audio_only_n",utc_media_player_is_audio_only_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_is_content_spherical_p",utc_media_player_360_is_content_spherical_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_is_content_spherical_n",utc_media_player_360_is_content_spherical_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_get_enable_p",utc_media_player_360_set_get_enable_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_is_enabled_n",utc_media_player_360_is_enabled_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_get_direction_of_view_p",utc_media_player_360_set_get_direction_of_view_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_direction_of_view_n",utc_media_player_360_set_direction_of_view_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_get_direction_of_view_n",utc_media_player_360_get_direction_of_view_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_get_zoom_p",utc_media_player_360_set_get_zoom_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_zoom_n",utc_media_player_360_set_zoom_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_get_zoom_n",utc_media_player_360_get_zoom_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_get_field_of_view_p",utc_media_player_360_set_get_field_of_view_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_field_of_view_n",utc_media_player_360_set_field_of_view_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_get_field_of_view_n",utc_media_player_360_get_field_of_view_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_zoom_with_field_of_view_p",utc_media_player_360_set_zoom_with_field_of_view_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_360_set_zoom_with_field_of_view_n",utc_media_player_360_set_zoom_with_field_of_view_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_video_roi_area_p",utc_media_player_set_video_roi_area_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_video_roi_area_n",utc_media_player_set_video_roi_area_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_roi_area_p",utc_media_player_get_video_roi_area_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_video_roi_area_n",utc_media_player_get_video_roi_area_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_visible_p",utc_media_player_set_display_visible_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_visible_n",utc_media_player_set_display_visible_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_is_display_visible_p",utc_media_player_is_display_visible_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_is_display_visible_n",utc_media_player_is_display_visible_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_mode_p",utc_media_player_set_display_mode_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_mode_n",utc_media_player_set_display_mode_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_display_mode_p",utc_media_player_get_display_mode_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_display_mode_n",utc_media_player_get_display_mode_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_roi_area_p",utc_media_player_set_display_roi_area_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_roi_area_n",utc_media_player_set_display_roi_area_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_rotation_p",utc_media_player_set_display_rotation_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_display_rotation_n",utc_media_player_set_display_rotation_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_display_rotation_p",utc_media_player_get_display_rotation_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_get_display_rotation_n",utc_media_player_get_display_rotation_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_video_stream_changed_cb_p",utc_media_player_set_video_stream_changed_cb_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_video_stream_changed_cb_n",utc_media_player_set_video_stream_changed_cb_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_set_video_stream_changed_cb_n2",utc_media_player_set_video_stream_changed_cb_n2,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_unset_video_stream_changed_cb_p",utc_media_player_unset_video_stream_changed_cb_p,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{"utc_media_player_unset_video_stream_changed_cb_n",utc_media_player_unset_video_stream_changed_cb_n,utc_media_player_display_startup,utc_media_player_display_cleanup},
	{NULL, NULL}
};

#endif // __TCT_PLAYER-NATIVE_H__
