//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAMERA-NATIVE_H__
#define __TCT_CAMERA-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_camera_attribute_startup(void);
extern void ITs_camera_attribute_cleanup(void);
extern void ITs_camera_capability_startup(void);
extern void ITs_camera_capability_cleanup(void);
extern void ITs_camera_display_startup(void);
extern void ITs_camera_display_cleanup(void);
extern void ITs_camera_startup(void);
extern void ITs_camera_cleanup(void);

extern int ITc_camera_attr_set_get_preview_fps_p(void);
extern int ITc_camera_attr_set_get_image_quality_p(void);
extern int ITc_camera_attr_set_get_zoom_p(void);
extern int ITc_camera_attr_get_zoom_range_p(void);
extern int ITc_camera_attr_set_get_af_mode_p(void);
extern int ITc_camera_attr_set_clear_af_area_p(void);
extern int ITc_camera_attr_set_get_exposure_mode_p(void);
extern int ITc_camera_attr_set_get_exposure_p(void);
extern int ITc_camera_attr_get_exposure_range_p(void);
extern int ITc_camera_attr_set_get_flash_mode_p(void);
extern int ITc_camera_attr_set_get_iso_p(void);
extern int ITc_camera_attr_set_get_theater_mode_p(void);
extern int ITc_camera_attr_set_get_brightness_p(void);
extern int ITc_camera_attr_get_brightness_range_p(void);
extern int ITc_camera_attr_set_get_contrast_p(void);
extern int ITc_camera_attr_get_contrast_range_p(void);
extern int ITc_camera_attr_set_get_whitebalance_p(void);
extern int ITc_camera_attr_set_get_effect_p(void);
extern int ITc_camera_attr_set_get_scene_mode_p(void);
extern int ITc_camera_attr_enable_is_enabled_tag_p(void);
extern int ITc_camera_attr_set_get_tag_image_description_p(void);
extern int ITc_camera_attr_set_get_tag_orientation_p(void);
extern int ITc_camera_attr_set_get_tag_software_p(void);
extern int ITc_camera_attr_set_get_remove_geotag_p(void);
extern int ITc_camera_attr_get_lens_orientation_p(void);
extern int ITc_camera_attr_set_get_stream_rotation_p(void);
extern int ITc_camera_attr_set_get_stream_flip_p(void);
extern int ITc_camera_attr_set_get_hdr_mode_p(void);
extern int ITc_camera_attr_set_unset_hdr_capture_progress_cb_p(void);
extern int ITc_camera_attr_enable_is_enabled_antishake_p(void);
extern int ITc_camera_attr_enable_is_enabled_video_stabilization_p(void);
extern int ITc_camera_attr_enable_is_enabled_auto_contrast_p(void);
extern int ITc_camera_attr_disable_shutter_sound_p(void);
extern int ITc_camera_attr_set_get_encoded_preview_bitrate_p(void);
extern int ITc_camera_attr_set_get_encoded_preview_gop_interval_p(void);
extern int ITc_camera_attr_set_get_pan_p(void);
extern int ITc_camera_attr_get_pan_range_p(void);
extern int ITc_camera_attr_set_get_tilt_p(void);
extern int ITc_camera_attr_get_tilt_range_p(void);
extern int ITc_camera_attr_set_ptz_type_p(void);
extern int ITc_camera_attr_foreach_supported_ptz_type_p(void);
extern int ITc_camera_attr_set_get_display_roi_area_p(void);
extern int ITc_camera_attr_set_get_hue_p(void);
extern int ITc_camera_attr_get_hue_range_p(void);
extern int ITc_camera_is_supported_continuous_capture_p(void);
extern int ITc_camera_foreach_supported_preview_resolution_p(void);
extern int ITc_camera_foreach_supported_capture_resolution_p(void);
extern int ITc_camera_foreach_supported_capture_format_p(void);
extern int ITc_camera_foreach_supported_preview_format_p(void);
extern int ITc_camera_is_supported_face_detection_p(void);
extern int ITc_camera_is_supported_zero_shutter_lag_p(void);
extern int ITc_camera_get_device_count_p(void);
extern int ITc_camera_get_device_state_p(void);
extern int ITc_camera_add_remove_device_state_changed_cb_p(void);
extern int ITc_camera_is_supported_media_packet_preview_cb_p(void);
extern int ITc_camera_attr_foreach_supported_fps_p(void);
extern int ITc_camera_attr_foreach_supported_fps_by_resolution_p(void);
extern int ITc_camera_attr_foreach_supported_af_mode_p(void);
extern int ITc_camera_attr_foreach_supported_exposure_mode_p(void);
extern int ITc_camera_attr_foreach_supported_iso_p(void);
extern int ITc_camera_attr_foreach_supported_whitebalance_p(void);
extern int ITc_camera_attr_foreach_supported_effect_p(void);
extern int ITc_camera_attr_foreach_supported_scene_mode_p(void);
extern int ITc_camera_attr_foreach_supported_flash_mode_p(void);
extern int ITc_camera_attr_foreach_supported_stream_rotation_p(void);
extern int ITc_camera_attr_foreach_supported_stream_flip_p(void);
extern int ITc_camera_attr_is_supported_hdr_capture_p(void);
extern int ITc_camera_attr_is_supported_anti_shake_p(void);
extern int ITc_camera_attr_is_supported_video_stabilization_p(void);
extern int ITc_camera_attr_is_supported_auto_contrast_p(void);
extern int ITc_camera_set_get_display_rotation_p(void);
extern int ITc_camera_set_get_display_flip_p(void);
extern int ITc_camera_set_display_isvisible_display_p(void);
extern int ITc_camera_set_get_display_mode_p(void);
extern int ITc_camera_create_destroy_p(void);
extern int ITc_camera_start_stop_preview_set_unset_preview_cb_p(void);
extern int ITc_camera_start_capture_p(void);
extern int ITc_camera_start_stop_continuous_capture_p(void);
extern int ITc_camera_get_state_p(void);
extern int ITc_camera_start_cancel_focusing_p(void);
extern int ITc_camera_set_display_p(void);
extern int ITc_camera_set_get_preview_resolution_p(void);
extern int ITc_camera_get_recommended_preview_resolution_p(void);
extern int ITc_camera_set_get_capture_resolution_p(void);
extern int ITc_camera_attr_set_get_capture_format_p(void);
extern int ITc_camera_set_get_preview_format_p(void);
extern int ITc_camera_set_unset_media_packet_preview_cb_p(void);
extern int ITc_camera_set_unset_state_change_cb_p(void);
extern int ITc_camera_attr_set_unset_interrupted_cb_p(void);
extern int ITc_camera_set_unset_focus_changed_cb_p(void);
extern int ITc_camera_attr_set_unset_error_cb_p(void);
extern int ITc_camera_get_facing_direction_p(void);
extern int ITc_camera_get_flash_state_p(void);
extern int ITc_camera_change_device_p(void);

testcase tc_array[] = {
	{"ITc_camera_attr_set_get_preview_fps_p",ITc_camera_attr_set_get_preview_fps_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_image_quality_p",ITc_camera_attr_set_get_image_quality_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_zoom_p",ITc_camera_attr_set_get_zoom_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_zoom_range_p",ITc_camera_attr_get_zoom_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_af_mode_p",ITc_camera_attr_set_get_af_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_clear_af_area_p",ITc_camera_attr_set_clear_af_area_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_exposure_mode_p",ITc_camera_attr_set_get_exposure_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_exposure_p",ITc_camera_attr_set_get_exposure_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_exposure_range_p",ITc_camera_attr_get_exposure_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_flash_mode_p",ITc_camera_attr_set_get_flash_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_iso_p",ITc_camera_attr_set_get_iso_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_theater_mode_p",ITc_camera_attr_set_get_theater_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_brightness_p",ITc_camera_attr_set_get_brightness_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_brightness_range_p",ITc_camera_attr_get_brightness_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_contrast_p",ITc_camera_attr_set_get_contrast_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_contrast_range_p",ITc_camera_attr_get_contrast_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_whitebalance_p",ITc_camera_attr_set_get_whitebalance_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_effect_p",ITc_camera_attr_set_get_effect_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_scene_mode_p",ITc_camera_attr_set_get_scene_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_enable_is_enabled_tag_p",ITc_camera_attr_enable_is_enabled_tag_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_tag_image_description_p",ITc_camera_attr_set_get_tag_image_description_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_tag_orientation_p",ITc_camera_attr_set_get_tag_orientation_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_tag_software_p",ITc_camera_attr_set_get_tag_software_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_remove_geotag_p",ITc_camera_attr_set_get_remove_geotag_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_lens_orientation_p",ITc_camera_attr_get_lens_orientation_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_stream_rotation_p",ITc_camera_attr_set_get_stream_rotation_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_stream_flip_p",ITc_camera_attr_set_get_stream_flip_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_hdr_mode_p",ITc_camera_attr_set_get_hdr_mode_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_unset_hdr_capture_progress_cb_p",ITc_camera_attr_set_unset_hdr_capture_progress_cb_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_enable_is_enabled_antishake_p",ITc_camera_attr_enable_is_enabled_antishake_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_enable_is_enabled_video_stabilization_p",ITc_camera_attr_enable_is_enabled_video_stabilization_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_enable_is_enabled_auto_contrast_p",ITc_camera_attr_enable_is_enabled_auto_contrast_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_disable_shutter_sound_p",ITc_camera_attr_disable_shutter_sound_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_encoded_preview_bitrate_p",ITc_camera_attr_set_get_encoded_preview_bitrate_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_encoded_preview_gop_interval_p",ITc_camera_attr_set_get_encoded_preview_gop_interval_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_pan_p",ITc_camera_attr_set_get_pan_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_pan_range_p",ITc_camera_attr_get_pan_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_tilt_p",ITc_camera_attr_set_get_tilt_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_tilt_range_p",ITc_camera_attr_get_tilt_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_ptz_type_p",ITc_camera_attr_set_ptz_type_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_foreach_supported_ptz_type_p",ITc_camera_attr_foreach_supported_ptz_type_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_display_roi_area_p",ITc_camera_attr_set_get_display_roi_area_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_set_get_hue_p",ITc_camera_attr_set_get_hue_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_attr_get_hue_range_p",ITc_camera_attr_get_hue_range_p,ITs_camera_attribute_startup,ITs_camera_attribute_cleanup},
	{"ITc_camera_is_supported_continuous_capture_p",ITc_camera_is_supported_continuous_capture_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_foreach_supported_preview_resolution_p",ITc_camera_foreach_supported_preview_resolution_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_foreach_supported_capture_resolution_p",ITc_camera_foreach_supported_capture_resolution_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_foreach_supported_capture_format_p",ITc_camera_foreach_supported_capture_format_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_foreach_supported_preview_format_p",ITc_camera_foreach_supported_preview_format_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_is_supported_face_detection_p",ITc_camera_is_supported_face_detection_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_is_supported_zero_shutter_lag_p",ITc_camera_is_supported_zero_shutter_lag_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_get_device_count_p",ITc_camera_get_device_count_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_get_device_state_p",ITc_camera_get_device_state_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_add_remove_device_state_changed_cb_p",ITc_camera_add_remove_device_state_changed_cb_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_is_supported_media_packet_preview_cb_p",ITc_camera_is_supported_media_packet_preview_cb_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_fps_p",ITc_camera_attr_foreach_supported_fps_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_fps_by_resolution_p",ITc_camera_attr_foreach_supported_fps_by_resolution_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_af_mode_p",ITc_camera_attr_foreach_supported_af_mode_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_exposure_mode_p",ITc_camera_attr_foreach_supported_exposure_mode_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_iso_p",ITc_camera_attr_foreach_supported_iso_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_whitebalance_p",ITc_camera_attr_foreach_supported_whitebalance_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_effect_p",ITc_camera_attr_foreach_supported_effect_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_scene_mode_p",ITc_camera_attr_foreach_supported_scene_mode_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_flash_mode_p",ITc_camera_attr_foreach_supported_flash_mode_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_stream_rotation_p",ITc_camera_attr_foreach_supported_stream_rotation_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_foreach_supported_stream_flip_p",ITc_camera_attr_foreach_supported_stream_flip_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_is_supported_hdr_capture_p",ITc_camera_attr_is_supported_hdr_capture_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_is_supported_anti_shake_p",ITc_camera_attr_is_supported_anti_shake_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_is_supported_video_stabilization_p",ITc_camera_attr_is_supported_video_stabilization_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_attr_is_supported_auto_contrast_p",ITc_camera_attr_is_supported_auto_contrast_p,ITs_camera_capability_startup,ITs_camera_capability_cleanup},
	{"ITc_camera_set_get_display_rotation_p",ITc_camera_set_get_display_rotation_p,ITs_camera_display_startup,ITs_camera_display_cleanup},
	{"ITc_camera_set_get_display_flip_p",ITc_camera_set_get_display_flip_p,ITs_camera_display_startup,ITs_camera_display_cleanup},
	{"ITc_camera_set_display_isvisible_display_p",ITc_camera_set_display_isvisible_display_p,ITs_camera_display_startup,ITs_camera_display_cleanup},
	{"ITc_camera_set_get_display_mode_p",ITc_camera_set_get_display_mode_p,ITs_camera_display_startup,ITs_camera_display_cleanup},
	{"ITc_camera_create_destroy_p",ITc_camera_create_destroy_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_start_stop_preview_set_unset_preview_cb_p",ITc_camera_start_stop_preview_set_unset_preview_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_start_capture_p",ITc_camera_start_capture_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_start_stop_continuous_capture_p",ITc_camera_start_stop_continuous_capture_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_get_state_p",ITc_camera_get_state_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_start_cancel_focusing_p",ITc_camera_start_cancel_focusing_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_display_p",ITc_camera_set_display_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_get_preview_resolution_p",ITc_camera_set_get_preview_resolution_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_get_recommended_preview_resolution_p",ITc_camera_get_recommended_preview_resolution_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_get_capture_resolution_p",ITc_camera_set_get_capture_resolution_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_attr_set_get_capture_format_p",ITc_camera_attr_set_get_capture_format_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_get_preview_format_p",ITc_camera_set_get_preview_format_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_unset_media_packet_preview_cb_p",ITc_camera_set_unset_media_packet_preview_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_unset_state_change_cb_p",ITc_camera_set_unset_state_change_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_attr_set_unset_interrupted_cb_p",ITc_camera_attr_set_unset_interrupted_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_set_unset_focus_changed_cb_p",ITc_camera_set_unset_focus_changed_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_attr_set_unset_error_cb_p",ITc_camera_attr_set_unset_error_cb_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_get_facing_direction_p",ITc_camera_get_facing_direction_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_get_flash_state_p",ITc_camera_get_flash_state_p,ITs_camera_startup,ITs_camera_cleanup},
	{"ITc_camera_change_device_p",ITc_camera_change_device_p,ITs_camera_startup,ITs_camera_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CAMERA-NATIVE_H__
