//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CONTEXT-NATIVE_H__
#define __TCT_CONTEXT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_context_trigger_startup(void);
extern void utc_context_trigger_cleanup(void);
extern void utc_context_history_startup(void);
extern void utc_context_history_cleanup(void);

extern int utc_context_trigger_add_rule_p(void);
extern int utc_context_trigger_add_rule_n(void);
extern int utc_context_trigger_remove_rule_p(void);
extern int utc_context_trigger_remove_rule_n(void);
extern int utc_context_trigger_enable_rule_p(void);
extern int utc_context_trigger_enable_rule_n(void);
extern int utc_context_trigger_disable_rule_p(void);
extern int utc_context_trigger_disable_rule_n(void);
extern int utc_context_trigger_get_own_rule_ids_p(void);
extern int utc_context_trigger_get_own_rule_ids_n(void);
extern int utc_context_trigger_get_rule_by_id_p(void);
extern int utc_context_trigger_get_rule_by_id_n(void);
extern int utc_context_trigger_rule_create_p(void);
extern int utc_context_trigger_rule_create_n(void);
extern int utc_context_trigger_rule_destroy_p(void);
extern int utc_context_trigger_rule_destroy_n(void);
extern int utc_context_trigger_rule_add_entry_p(void);
extern int utc_context_trigger_rule_add_entry_n1(void);
extern int utc_context_trigger_rule_add_entry_n2(void);
extern int utc_context_trigger_rule_set_action_app_control_p(void);
extern int utc_context_trigger_rule_set_action_app_control_n(void);
extern int utc_context_trigger_rule_set_action_notification_p(void);
extern int utc_context_trigger_rule_set_action_notification_n(void);
extern int utc_context_trigger_rule_set_description_p(void);
extern int utc_context_trigger_rule_set_description_n(void);
extern int utc_context_trigger_rule_get_description_p(void);
extern int utc_context_trigger_rule_get_description_n(void);
extern int utc_context_trigger_rule_event_create_p(void);
extern int utc_context_trigger_rule_event_create_n(void);
extern int utc_context_trigger_rule_event_is_supported_p(void);
extern int utc_context_trigger_rule_event_is_supported_n(void);
extern int utc_context_trigger_rule_condition_create_p(void);
extern int utc_context_trigger_rule_condition_create_n(void);
extern int utc_context_trigger_rule_condition_is_supported_p(void);
extern int utc_context_trigger_rule_condition_is_supported_n(void);
extern int utc_context_trigger_rule_entry_destroy_p(void);
extern int utc_context_trigger_rule_entry_destroy_n(void);
extern int utc_context_trigger_rule_entry_add_key_p(void);
extern int utc_context_trigger_rule_entry_add_key_n(void);
extern int utc_context_trigger_rule_entry_add_comparison_int_p(void);
extern int utc_context_trigger_rule_entry_add_comparison_int_n(void);
extern int utc_context_trigger_rule_entry_add_comparison_string_p(void);
extern int utc_context_trigger_rule_entry_add_comparison_string_n(void);
extern int utc_context_trigger_rule_entry_add_comparison_p1(void);
extern int utc_context_trigger_rule_entry_add_comparison_p2(void);
extern int utc_context_trigger_rule_entry_add_comparison_n(void);
extern int utc_context_trigger_rule_entry_add_option_int_p(void);
extern int utc_context_trigger_rule_entry_add_option_int_n(void);
extern int utc_context_trigger_rule_entry_add_option_string_p(void);
extern int utc_context_trigger_rule_entry_add_option_string_n(void);
extern int utc_context_trigger_rule_entry_add_option_p1(void);
extern int utc_context_trigger_rule_entry_add_option_p2(void);
extern int utc_context_trigger_rule_entry_add_option_p3(void);
extern int utc_context_trigger_rule_entry_add_option_n(void);
extern int utc_context_trigger_custom_register_p(void);
extern int utc_context_trigger_custom_register_n(void);
extern int utc_context_trigger_custom_unregister_p(void);
extern int utc_context_trigger_custom_unregister_n(void);
extern int utc_context_trigger_custom_publish_p(void);
extern int utc_context_trigger_custom_publish_n(void);
extern int utc_context_trigger_rule_custom_event_create_p(void);
extern int utc_context_trigger_rule_custom_event_create_n(void);
extern int utc_context_trigger_rule_custom_condition_create_p(void);
extern int utc_context_trigger_rule_custom_condition_create_n(void);
extern int utc_context_history_create_p(void);
extern int utc_context_history_create_n(void);
extern int utc_context_history_destroy_p(void);
extern int utc_context_history_destroy_n(void);
extern int utc_context_history_filter_create_p(void);
extern int utc_context_history_filter_create_n(void);
extern int utc_context_history_filter_destroy_p(void);
extern int utc_context_history_filter_destroy_n(void);
extern int utc_context_history_filter_set_int_p(void);
extern int utc_context_history_filter_set_int_n(void);
extern int utc_context_history_filter_set_string_p(void);
extern int utc_context_history_filter_set_string_n(void);
extern int utc_context_history_is_supported_p(void);
extern int utc_context_history_is_supported_n(void);
extern int utc_context_history_get_list_p(void);
extern int utc_context_history_get_list_n(void);
extern int utc_context_history_list_get_count_p(void);
extern int utc_context_history_list_get_count_n(void);
extern int utc_context_history_list_get_current_p(void);
extern int utc_context_history_list_get_current_n(void);
extern int utc_context_history_list_move_first_p(void);
extern int utc_context_history_list_move_first_n(void);
extern int utc_context_history_list_move_next_p(void);
extern int utc_context_history_list_move_next_n(void);
extern int utc_context_history_list_destroy_p(void);
extern int utc_context_history_list_destroy_n(void);
extern int utc_context_history_record_get_int_p(void);
extern int utc_context_history_record_get_int_n(void);
extern int utc_context_history_record_get_string_p(void);
extern int utc_context_history_record_get_string_n(void);
extern int utc_context_history_record_get_double_p(void);
extern int utc_context_history_record_get_double_n(void);
extern int utc_context_history_record_destroy_p(void);
extern int utc_context_history_record_destroy_n(void);

testcase tc_array[] = {
	{"utc_context_trigger_add_rule_p",utc_context_trigger_add_rule_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_add_rule_n",utc_context_trigger_add_rule_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_remove_rule_p",utc_context_trigger_remove_rule_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_remove_rule_n",utc_context_trigger_remove_rule_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_enable_rule_p",utc_context_trigger_enable_rule_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_enable_rule_n",utc_context_trigger_enable_rule_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_disable_rule_p",utc_context_trigger_disable_rule_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_disable_rule_n",utc_context_trigger_disable_rule_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_get_own_rule_ids_p",utc_context_trigger_get_own_rule_ids_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_get_own_rule_ids_n",utc_context_trigger_get_own_rule_ids_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_get_rule_by_id_p",utc_context_trigger_get_rule_by_id_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_get_rule_by_id_n",utc_context_trigger_get_rule_by_id_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_create_p",utc_context_trigger_rule_create_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_create_n",utc_context_trigger_rule_create_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_destroy_p",utc_context_trigger_rule_destroy_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_destroy_n",utc_context_trigger_rule_destroy_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_add_entry_p",utc_context_trigger_rule_add_entry_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_add_entry_n1",utc_context_trigger_rule_add_entry_n1,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_add_entry_n2",utc_context_trigger_rule_add_entry_n2,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_action_app_control_p",utc_context_trigger_rule_set_action_app_control_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_action_app_control_n",utc_context_trigger_rule_set_action_app_control_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_action_notification_p",utc_context_trigger_rule_set_action_notification_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_action_notification_n",utc_context_trigger_rule_set_action_notification_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_description_p",utc_context_trigger_rule_set_description_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_set_description_n",utc_context_trigger_rule_set_description_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_get_description_p",utc_context_trigger_rule_get_description_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_get_description_n",utc_context_trigger_rule_get_description_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_event_create_p",utc_context_trigger_rule_event_create_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_event_create_n",utc_context_trigger_rule_event_create_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_event_is_supported_p",utc_context_trigger_rule_event_is_supported_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_event_is_supported_n",utc_context_trigger_rule_event_is_supported_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_condition_create_p",utc_context_trigger_rule_condition_create_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_condition_create_n",utc_context_trigger_rule_condition_create_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_condition_is_supported_p",utc_context_trigger_rule_condition_is_supported_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_condition_is_supported_n",utc_context_trigger_rule_condition_is_supported_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_destroy_p",utc_context_trigger_rule_entry_destroy_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_destroy_n",utc_context_trigger_rule_entry_destroy_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_key_p",utc_context_trigger_rule_entry_add_key_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_key_n",utc_context_trigger_rule_entry_add_key_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_int_p",utc_context_trigger_rule_entry_add_comparison_int_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_int_n",utc_context_trigger_rule_entry_add_comparison_int_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_string_p",utc_context_trigger_rule_entry_add_comparison_string_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_string_n",utc_context_trigger_rule_entry_add_comparison_string_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_p1",utc_context_trigger_rule_entry_add_comparison_p1,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_p2",utc_context_trigger_rule_entry_add_comparison_p2,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_comparison_n",utc_context_trigger_rule_entry_add_comparison_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_int_p",utc_context_trigger_rule_entry_add_option_int_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_int_n",utc_context_trigger_rule_entry_add_option_int_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_string_p",utc_context_trigger_rule_entry_add_option_string_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_string_n",utc_context_trigger_rule_entry_add_option_string_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_p1",utc_context_trigger_rule_entry_add_option_p1,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_p2",utc_context_trigger_rule_entry_add_option_p2,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_p3",utc_context_trigger_rule_entry_add_option_p3,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_entry_add_option_n",utc_context_trigger_rule_entry_add_option_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_register_p",utc_context_trigger_custom_register_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_register_n",utc_context_trigger_custom_register_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_unregister_p",utc_context_trigger_custom_unregister_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_unregister_n",utc_context_trigger_custom_unregister_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_publish_p",utc_context_trigger_custom_publish_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_custom_publish_n",utc_context_trigger_custom_publish_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_custom_event_create_p",utc_context_trigger_rule_custom_event_create_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_custom_event_create_n",utc_context_trigger_rule_custom_event_create_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_custom_condition_create_p",utc_context_trigger_rule_custom_condition_create_p,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_trigger_rule_custom_condition_create_n",utc_context_trigger_rule_custom_condition_create_n,utc_context_trigger_startup,utc_context_trigger_cleanup},
	{"utc_context_history_create_p",utc_context_history_create_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_create_n",utc_context_history_create_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_destroy_p",utc_context_history_destroy_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_destroy_n",utc_context_history_destroy_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_create_p",utc_context_history_filter_create_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_create_n",utc_context_history_filter_create_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_destroy_p",utc_context_history_filter_destroy_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_destroy_n",utc_context_history_filter_destroy_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_set_int_p",utc_context_history_filter_set_int_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_set_int_n",utc_context_history_filter_set_int_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_set_string_p",utc_context_history_filter_set_string_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_filter_set_string_n",utc_context_history_filter_set_string_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_is_supported_p",utc_context_history_is_supported_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_is_supported_n",utc_context_history_is_supported_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_get_list_p",utc_context_history_get_list_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_get_list_n",utc_context_history_get_list_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_get_count_p",utc_context_history_list_get_count_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_get_count_n",utc_context_history_list_get_count_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_get_current_p",utc_context_history_list_get_current_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_get_current_n",utc_context_history_list_get_current_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_move_first_p",utc_context_history_list_move_first_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_move_first_n",utc_context_history_list_move_first_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_move_next_p",utc_context_history_list_move_next_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_move_next_n",utc_context_history_list_move_next_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_destroy_p",utc_context_history_list_destroy_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_list_destroy_n",utc_context_history_list_destroy_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_int_p",utc_context_history_record_get_int_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_int_n",utc_context_history_record_get_int_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_string_p",utc_context_history_record_get_string_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_string_n",utc_context_history_record_get_string_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_double_p",utc_context_history_record_get_double_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_get_double_n",utc_context_history_record_get_double_n,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_destroy_p",utc_context_history_record_destroy_p,utc_context_history_startup,utc_context_history_cleanup},
	{"utc_context_history_record_destroy_n",utc_context_history_record_destroy_n,utc_context_history_startup,utc_context_history_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CONTEXT-NATIVE_H__
