//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_WIFI-DIRECT-NATIVE_H__
#define __TCT_WIFI-DIRECT-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_wifi_direct_connection_negative_startup(void);
extern void utc_wifi_direct_connection_negative_cleanup(void);
extern void utc_wifi_direct_connection_positive_startup(void);
extern void utc_wifi_direct_connection_positive_cleanup(void);
extern void utc_wifi_direct_device_negative_startup(void);
extern void utc_wifi_direct_device_negative_cleanup(void);
extern void utc_wifi_direct_device_positive_startup(void);
extern void utc_wifi_direct_device_positive_cleanup(void);
extern void utc_wifi_direct_discovery_negative_startup(void);
extern void utc_wifi_direct_discovery_negative_cleanup(void);
extern void utc_wifi_direct_discovery_positive_startup(void);
extern void utc_wifi_direct_discovery_positive_cleanup(void);
extern void utc_wifi_direct_group_negative_startup(void);
extern void utc_wifi_direct_group_negative_cleanup(void);
extern void utc_wifi_direct_group_positive_startup(void);
extern void utc_wifi_direct_group_positive_cleanup(void);
extern void utc_wifi_direct_registration_negative_startup(void);
extern void utc_wifi_direct_registration_negative_cleanup(void);
extern void utc_wifi_direct_registration_positive_startup(void);
extern void utc_wifi_direct_registration_positive_cleanup(void);
extern void utc_wifi_direct_service_negative_startup(void);
extern void utc_wifi_direct_service_negative_cleanup(void);
extern void utc_wifi_direct_service_positive_startup(void);
extern void utc_wifi_direct_service_positive_cleanup(void);

extern int utc_wifi_direct_connect_n(void);
extern int utc_wifi_direct_set_wps_pin_n(void);
extern int utc_wifi_direct_foreach_connected_peers_n(void);
extern int utc_wifi_direct_get_wps_pin_n(void);
extern int utc_wifi_direct_disconnect_all_n(void);
extern int utc_wifi_direct_disconnect_n(void);
extern int utc_wifi_direct_cancel_connection_n(void);
extern int utc_wifi_direct_activate_pushbutton_n(void);
extern int utc_wifi_direct_get_connecting_peer_info_n(void);
extern int utc_wifi_direct_connect_p(void);
extern int utc_wifi_direct_set_wps_pin_p(void);
extern int utc_wifi_direct_set_session_timer_n(void);
extern int utc_wifi_direct_get_session_timer_n(void);
extern int utc_wifi_direct_get_ssid_n(void);
extern int utc_wifi_direct_get_mac_address_n(void);
extern int utc_wifi_direct_get_state_n(void);
extern int utc_wifi_direct_activate_n(void);
extern int utc_wifi_direct_deactivate_n(void);
extern int utc_wifi_direct_get_device_name_n(void);
extern int utc_wifi_direct_get_primary_device_type_n(void);
extern int utc_wifi_direct_get_secondary_device_type_n(void);
extern int utc_wifi_direct_init_miracast_n(void);
extern int utc_wifi_direct_init_display_n(void);
extern int utc_wifi_direct_deinit_display_n(void);
extern int utc_wifi_direct_set_display_n(void);
extern int utc_wifi_direct_set_display_availability_n(void);
extern int utc_wifi_direct_get_display_n(void);
extern int utc_wifi_direct_get_display_availability_n(void);
extern int utc_wifi_direct_is_autoconnection_mode_n(void);
extern int utc_wifi_direct_set_autoconnection_mode_n(void);
extern int utc_wifi_direct_set_autoconnection_peer_n(void);
extern int utc_wifi_direct_set_device_name_n(void);
extern int utc_wifi_direct_foreach_supported_wps_types_n(void);
extern int utc_wifi_direct_get_supported_wps_mode_n(void);
extern int utc_wifi_direct_add_vsie_n(void);
extern int utc_wifi_direct_get_vsie_n(void);
extern int utc_wifi_direct_remove_vsie_n(void);
extern int utc_wifi_direct_set_wps_config_method_n(void);
extern int utc_wifi_direct_get_wps_config_method_n(void);
extern int utc_wifi_direct_set_session_timer_p(void);
extern int utc_wifi_direct_get_session_timer_p(void);
extern int utc_wifi_direct_activate_p(void);
extern int utc_wifi_direct_get_ssid_p(void);
extern int utc_wifi_direct_get_mac_address_p(void);
extern int utc_wifi_direct_get_state_p(void);
extern int utc_wifi_direct_deactivate_p(void);
extern int utc_wifi_direct_get_device_name_p(void);
extern int utc_wifi_direct_get_primary_device_type_p(void);
extern int utc_wifi_direct_get_secondary_device_type_p(void);
extern int utc_wifi_direct_init_miracast_p(void);
extern int utc_wifi_direct_init_display_p(void);
extern int utc_wifi_direct_deinit_display_p(void);
extern int utc_wifi_direct_set_display_p(void);
extern int utc_wifi_direct_set_display_availability_p(void);
extern int utc_wifi_direct_get_display_p(void);
extern int utc_wifi_direct_get_display_availability_p(void);
extern int utc_wifi_direct_is_autoconnection_mode_p(void);
extern int utc_wifi_direct_set_autoconnection_mode_p(void);
extern int utc_wifi_direct_set_autoconnection_peer_p(void);
extern int utc_wifi_direct_set_device_name_p(void);
extern int utc_wifi_direct_foreach_supported_wps_types_p(void);
extern int utc_wifi_direct_get_supported_wps_mode_p(void);
extern int utc_wifi_direct_add_vsie_p(void);
extern int utc_wifi_direct_get_vsie_p(void);
extern int utc_wifi_direct_remove_vsie_p(void);
extern int utc_wifi_direct_set_wps_config_method_p(void);
extern int utc_wifi_direct_get_wps_config_method_p(void);
extern int utc_wifi_direct_start_discovery_n(void);
extern int utc_wifi_direct_cancel_discovery_n(void);
extern int utc_wifi_direct_get_peer_info_n(void);
extern int utc_wifi_direct_foreach_discovered_peers_n(void);
extern int utc_wifi_direct_get_local_wps_type_n(void);
extern int utc_wifi_direct_set_req_wps_type_n(void);
extern int utc_wifi_direct_get_req_wps_type_n(void);
extern int utc_wifi_direct_is_discoverable_n(void);
extern int utc_wifi_direct_is_listening_only_n(void);
extern int utc_wifi_direct_start_discovery_specific_channel_n(void);
extern int utc_wifi_direct_start_discovery_specific_freq_n(void);
extern int utc_wifi_direct_get_peer_display_availability_n(void);
extern int utc_wifi_direct_get_peer_display_type_n(void);
extern int utc_wifi_direct_get_peer_display_hdcp_n(void);
extern int utc_wifi_direct_get_peer_display_port_n(void);
extern int utc_wifi_direct_get_peer_display_throughput_n(void);
extern int utc_wifi_direct_get_peer_rssi_n(void);
extern int utc_wifi_direct_get_peer_vsie_n_1(void);
extern int utc_wifi_direct_get_peer_vsie_n_2(void);
extern int utc_wifi_direct_start_discovery_p(void);
extern int utc_wifi_direct_cancel_discovery_p(void);
extern int utc_wifi_direct_foreach_discovered_peers_p(void);
extern int utc_wifi_direct_get_local_wps_type_p(void);
extern int utc_wifi_direct_set_req_wps_type_p(void);
extern int utc_wifi_direct_get_req_wps_type_p(void);
extern int utc_wifi_direct_is_discoverable_p(void);
extern int utc_wifi_direct_is_listening_only_p(void);
extern int utc_wifi_direct_start_discovery_specific_channel_p(void);
extern int utc_wifi_direct_start_discovery_specific_freq_p(void);
extern int utc_wifi_direct_set_auto_group_removal_n(void);
extern int utc_wifi_direct_create_group_n(void);
extern int utc_wifi_direct_create_group_with_ssid_n(void);
extern int utc_wifi_direct_destroy_group_n(void);
extern int utc_wifi_direct_is_group_owner_n(void);
extern int utc_wifi_direct_is_autonomous_group_n(void);
extern int utc_wifi_direct_get_group_owner_intent_n(void);
extern int utc_wifi_direct_set_group_owner_intent_n(void);
extern int utc_wifi_direct_set_go_intent_per_type_n(void);
extern int utc_wifi_direct_get_go_intent_per_type_n(void);
extern int utc_wifi_direct_get_max_clients_n(void);
extern int utc_wifi_direct_set_max_clients_n(void);
extern int utc_wifi_direct_set_passphrase_n(void);
extern int utc_wifi_direct_get_passphrase_n(void);
extern int utc_wifi_direct_set_persistent_group_enabled_n(void);
extern int utc_wifi_direct_foreach_persistent_groups_n(void);
extern int utc_wifi_direct_is_persistent_group_enabled_n(void);
extern int utc_wifi_direct_get_subnet_mask_n(void);
extern int utc_wifi_direct_get_operating_channel_n(void);
extern int utc_wifi_direct_get_ip_address_n(void);
extern int utc_wifi_direct_get_gateway_address_n(void);
extern int utc_wifi_direct_get_network_interface_name_n(void);
extern int utc_wifi_direct_remove_persistent_group_n(void);
extern int utc_wifi_direct_remove_persistent_device_n(void);
extern int utc_wifi_direct_remove_all_persistent_devices_n(void);
extern int utc_wifi_direct_set_auto_group_removal_p(void);
extern int utc_wifi_direct_create_group_p(void);
extern int utc_wifi_direct_create_group_with_ssid_p(void);
extern int utc_wifi_direct_destroy_group_p(void);
extern int utc_wifi_direct_is_group_owner_p(void);
extern int utc_wifi_direct_is_autonomous_group_p(void);
extern int utc_wifi_direct_get_group_owner_intent_p(void);
extern int utc_wifi_direct_set_group_owner_intent_p(void);
extern int utc_wifi_direct_set_go_intent_per_type_p(void);
extern int utc_wifi_direct_get_go_intent_per_type_p(void);
extern int utc_wifi_direct_get_max_clients_p(void);
extern int utc_wifi_direct_set_max_clients_p(void);
extern int utc_wifi_direct_set_passphrase_p(void);
extern int utc_wifi_direct_get_passphrase_p(void);
extern int utc_wifi_direct_set_persistent_group_enabled_p(void);
extern int utc_wifi_direct_foreach_persistent_groups_p(void);
extern int utc_wifi_direct_is_persistent_group_enabled_p(void);
extern int utc_wifi_direct_initialize_n(void);
extern int utc_wifi_direct_deinitialize_n(void);
extern int utc_wifi_direct_set_device_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_device_state_changed_cb_n(void);
extern int utc_wifi_direct_set_discovery_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_discovery_state_changed_cb_n(void);
extern int utc_wifi_direct_set_connection_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_connection_state_changed_cb_n(void);
extern int utc_wifi_direct_set_peer_info_connection_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_peer_info_connection_state_changed_cb_n(void);
extern int utc_wifi_direct_set_service_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_service_state_changed_cb_n(void);
extern int utc_wifi_direct_set_client_ip_address_assigned_cb_n(void);
extern int utc_wifi_direct_unset_client_ip_address_assigned_cb_n(void);
extern int utc_wifi_direct_set_peer_found_cb_n(void);
extern int utc_wifi_direct_unset_peer_found_cb_n(void);
extern int utc_wifi_direct_set_state_changed_cb_n(void);
extern int utc_wifi_direct_unset_state_changed_cb_n(void);
extern int utc_wifi_direct_initialize_p(void);
extern int utc_wifi_direct_set_device_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_device_state_changed_cb_p(void);
extern int utc_wifi_direct_set_discovery_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_discovery_state_changed_cb_p(void);
extern int utc_wifi_direct_set_connection_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_connection_state_changed_cb_p(void);
extern int utc_wifi_direct_set_peer_info_connection_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_peer_info_connection_state_changed_cb_p(void);
extern int utc_wifi_direct_deinitialize_p(void);
extern int utc_wifi_direct_set_service_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_service_state_changed_cb_p(void);
extern int utc_wifi_direct_set_client_ip_address_assigned_cb_p(void);
extern int utc_wifi_direct_unset_client_ip_address_assigned_cb_p(void);
extern int utc_wifi_direct_set_peer_found_cb_p(void);
extern int utc_wifi_direct_unset_peer_found_cb_p(void);
extern int utc_wifi_direct_set_state_changed_cb_p(void);
extern int utc_wifi_direct_unset_state_changed_cb_p(void);
extern int utc_wifi_direct_register_service_n(void);
extern int utc_wifi_direct_deregister_service_n(void);
extern int utc_wifi_direct_start_service_discovery_n(void);
extern int utc_wifi_direct_cancel_service_discovery_n(void);
extern int utc_wifi_direct_register_service_p(void);
extern int utc_wifi_direct_deregister_service_p(void);
extern int utc_wifi_direct_start_service_discovery_p(void);
extern int utc_wifi_direct_cancel_service_discovery_p(void);

testcase tc_array[] = {
	{"utc_wifi_direct_connect_n",utc_wifi_direct_connect_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_set_wps_pin_n",utc_wifi_direct_set_wps_pin_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_foreach_connected_peers_n",utc_wifi_direct_foreach_connected_peers_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_get_wps_pin_n",utc_wifi_direct_get_wps_pin_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_disconnect_all_n",utc_wifi_direct_disconnect_all_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_disconnect_n",utc_wifi_direct_disconnect_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_cancel_connection_n",utc_wifi_direct_cancel_connection_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_activate_pushbutton_n",utc_wifi_direct_activate_pushbutton_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_get_connecting_peer_info_n",utc_wifi_direct_get_connecting_peer_info_n,utc_wifi_direct_connection_negative_startup,utc_wifi_direct_connection_negative_cleanup},
	{"utc_wifi_direct_connect_p",utc_wifi_direct_connect_p,utc_wifi_direct_connection_positive_startup,utc_wifi_direct_connection_positive_cleanup},
	{"utc_wifi_direct_set_wps_pin_p",utc_wifi_direct_set_wps_pin_p,utc_wifi_direct_connection_positive_startup,utc_wifi_direct_connection_positive_cleanup},
	{"utc_wifi_direct_set_session_timer_n",utc_wifi_direct_set_session_timer_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_session_timer_n",utc_wifi_direct_get_session_timer_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_ssid_n",utc_wifi_direct_get_ssid_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_mac_address_n",utc_wifi_direct_get_mac_address_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_state_n",utc_wifi_direct_get_state_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_activate_n",utc_wifi_direct_activate_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_deactivate_n",utc_wifi_direct_deactivate_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_device_name_n",utc_wifi_direct_get_device_name_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_primary_device_type_n",utc_wifi_direct_get_primary_device_type_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_secondary_device_type_n",utc_wifi_direct_get_secondary_device_type_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_init_miracast_n",utc_wifi_direct_init_miracast_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_init_display_n",utc_wifi_direct_init_display_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_deinit_display_n",utc_wifi_direct_deinit_display_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_display_n",utc_wifi_direct_set_display_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_display_availability_n",utc_wifi_direct_set_display_availability_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_display_n",utc_wifi_direct_get_display_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_display_availability_n",utc_wifi_direct_get_display_availability_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_is_autoconnection_mode_n",utc_wifi_direct_is_autoconnection_mode_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_autoconnection_mode_n",utc_wifi_direct_set_autoconnection_mode_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_autoconnection_peer_n",utc_wifi_direct_set_autoconnection_peer_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_device_name_n",utc_wifi_direct_set_device_name_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_foreach_supported_wps_types_n",utc_wifi_direct_foreach_supported_wps_types_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_supported_wps_mode_n",utc_wifi_direct_get_supported_wps_mode_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_add_vsie_n",utc_wifi_direct_add_vsie_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_vsie_n",utc_wifi_direct_get_vsie_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_remove_vsie_n",utc_wifi_direct_remove_vsie_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_wps_config_method_n",utc_wifi_direct_set_wps_config_method_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_get_wps_config_method_n",utc_wifi_direct_get_wps_config_method_n,utc_wifi_direct_device_negative_startup,utc_wifi_direct_device_negative_cleanup},
	{"utc_wifi_direct_set_session_timer_p",utc_wifi_direct_set_session_timer_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_session_timer_p",utc_wifi_direct_get_session_timer_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_activate_p",utc_wifi_direct_activate_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_ssid_p",utc_wifi_direct_get_ssid_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_mac_address_p",utc_wifi_direct_get_mac_address_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_state_p",utc_wifi_direct_get_state_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_deactivate_p",utc_wifi_direct_deactivate_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_device_name_p",utc_wifi_direct_get_device_name_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_primary_device_type_p",utc_wifi_direct_get_primary_device_type_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_secondary_device_type_p",utc_wifi_direct_get_secondary_device_type_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_init_miracast_p",utc_wifi_direct_init_miracast_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_init_display_p",utc_wifi_direct_init_display_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_deinit_display_p",utc_wifi_direct_deinit_display_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_display_p",utc_wifi_direct_set_display_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_display_availability_p",utc_wifi_direct_set_display_availability_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_display_p",utc_wifi_direct_set_display_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_display_availability_p",utc_wifi_direct_set_display_availability_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_is_autoconnection_mode_p",utc_wifi_direct_is_autoconnection_mode_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_autoconnection_mode_p",utc_wifi_direct_set_autoconnection_mode_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_autoconnection_peer_p",utc_wifi_direct_set_autoconnection_peer_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_device_name_p",utc_wifi_direct_set_device_name_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_foreach_supported_wps_types_p",utc_wifi_direct_foreach_supported_wps_types_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_supported_wps_mode_p",utc_wifi_direct_get_supported_wps_mode_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_add_vsie_p",utc_wifi_direct_add_vsie_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_vsie_p",utc_wifi_direct_get_vsie_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_remove_vsie_p",utc_wifi_direct_remove_vsie_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_set_wps_config_method_p",utc_wifi_direct_set_wps_config_method_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_get_wps_config_method_p",utc_wifi_direct_get_wps_config_method_p,utc_wifi_direct_device_positive_startup,utc_wifi_direct_device_positive_cleanup},
	{"utc_wifi_direct_start_discovery_n",utc_wifi_direct_start_discovery_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_cancel_discovery_n",utc_wifi_direct_cancel_discovery_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_info_n",utc_wifi_direct_get_peer_info_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_foreach_discovered_peers_n",utc_wifi_direct_foreach_discovered_peers_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_local_wps_type_n",utc_wifi_direct_get_local_wps_type_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_set_req_wps_type_n",utc_wifi_direct_set_req_wps_type_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_req_wps_type_n",utc_wifi_direct_get_req_wps_type_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_is_discoverable_n",utc_wifi_direct_is_discoverable_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_is_listening_only_n",utc_wifi_direct_is_listening_only_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_start_discovery_specific_channel_n",utc_wifi_direct_start_discovery_specific_channel_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_start_discovery_specific_freq_n",utc_wifi_direct_start_discovery_specific_freq_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_display_availability_n",utc_wifi_direct_get_peer_display_availability_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_display_type_n",utc_wifi_direct_get_peer_display_type_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_display_hdcp_n",utc_wifi_direct_get_peer_display_hdcp_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_display_port_n",utc_wifi_direct_get_peer_display_port_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_display_throughput_n",utc_wifi_direct_get_peer_display_throughput_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_rssi_n",utc_wifi_direct_get_peer_rssi_n,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_vsie_n_1",utc_wifi_direct_get_peer_vsie_n_1,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_get_peer_vsie_n_2",utc_wifi_direct_get_peer_vsie_n_2,utc_wifi_direct_discovery_negative_startup,utc_wifi_direct_discovery_negative_cleanup},
	{"utc_wifi_direct_start_discovery_p",utc_wifi_direct_start_discovery_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_cancel_discovery_p",utc_wifi_direct_cancel_discovery_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_foreach_discovered_peers_p",utc_wifi_direct_foreach_discovered_peers_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_get_local_wps_type_p",utc_wifi_direct_get_local_wps_type_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_set_req_wps_type_p",utc_wifi_direct_set_req_wps_type_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_get_req_wps_type_p",utc_wifi_direct_get_req_wps_type_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_is_discoverable_p",utc_wifi_direct_is_discoverable_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_is_listening_only_p",utc_wifi_direct_is_listening_only_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_start_discovery_specific_channel_p",utc_wifi_direct_start_discovery_specific_channel_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_start_discovery_specific_freq_p",utc_wifi_direct_start_discovery_specific_freq_p,utc_wifi_direct_discovery_positive_startup,utc_wifi_direct_discovery_positive_cleanup},
	{"utc_wifi_direct_set_auto_group_removal_n",utc_wifi_direct_set_auto_group_removal_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_create_group_n",utc_wifi_direct_create_group_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_create_group_with_ssid_n",utc_wifi_direct_create_group_with_ssid_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_destroy_group_n",utc_wifi_direct_destroy_group_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_is_group_owner_n",utc_wifi_direct_is_group_owner_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_is_autonomous_group_n",utc_wifi_direct_is_autonomous_group_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_group_owner_intent_n",utc_wifi_direct_get_group_owner_intent_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_group_owner_intent_n",utc_wifi_direct_set_group_owner_intent_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_go_intent_per_type_n",utc_wifi_direct_set_go_intent_per_type_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_go_intent_per_type_n",utc_wifi_direct_get_go_intent_per_type_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_max_clients_n",utc_wifi_direct_get_max_clients_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_max_clients_n",utc_wifi_direct_set_max_clients_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_passphrase_n",utc_wifi_direct_set_passphrase_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_passphrase_n",utc_wifi_direct_get_passphrase_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_persistent_group_enabled_n",utc_wifi_direct_set_persistent_group_enabled_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_foreach_persistent_groups_n",utc_wifi_direct_foreach_persistent_groups_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_is_persistent_group_enabled_n",utc_wifi_direct_is_persistent_group_enabled_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_subnet_mask_n",utc_wifi_direct_get_subnet_mask_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_operating_channel_n",utc_wifi_direct_get_operating_channel_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_ip_address_n",utc_wifi_direct_get_ip_address_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_gateway_address_n",utc_wifi_direct_get_gateway_address_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_get_network_interface_name_n",utc_wifi_direct_get_network_interface_name_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_remove_persistent_group_n",utc_wifi_direct_remove_persistent_group_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_remove_persistent_device_n",utc_wifi_direct_remove_persistent_device_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_remove_all_persistent_devices_n",utc_wifi_direct_remove_all_persistent_devices_n,utc_wifi_direct_group_negative_startup,utc_wifi_direct_group_negative_cleanup},
	{"utc_wifi_direct_set_auto_group_removal_p",utc_wifi_direct_set_auto_group_removal_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_create_group_p",utc_wifi_direct_create_group_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_create_group_with_ssid_p",utc_wifi_direct_create_group_with_ssid_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_destroy_group_p",utc_wifi_direct_destroy_group_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_is_group_owner_p",utc_wifi_direct_is_group_owner_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_is_autonomous_group_p",utc_wifi_direct_is_autonomous_group_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_get_group_owner_intent_p",utc_wifi_direct_get_group_owner_intent_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_set_group_owner_intent_p",utc_wifi_direct_set_group_owner_intent_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_set_go_intent_per_type_p",utc_wifi_direct_set_go_intent_per_type_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_get_go_intent_per_type_p",utc_wifi_direct_get_go_intent_per_type_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_get_max_clients_p",utc_wifi_direct_get_max_clients_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_set_max_clients_p",utc_wifi_direct_set_max_clients_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_set_passphrase_p",utc_wifi_direct_set_passphrase_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_get_passphrase_p",utc_wifi_direct_get_passphrase_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_set_persistent_group_enabled_p",utc_wifi_direct_set_persistent_group_enabled_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_foreach_persistent_groups_p",utc_wifi_direct_foreach_persistent_groups_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_is_persistent_group_enabled_p",utc_wifi_direct_is_persistent_group_enabled_p,utc_wifi_direct_group_positive_startup,utc_wifi_direct_group_positive_cleanup},
	{"utc_wifi_direct_initialize_n",utc_wifi_direct_initialize_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_deinitialize_n",utc_wifi_direct_deinitialize_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_device_state_changed_cb_n",utc_wifi_direct_set_device_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_device_state_changed_cb_n",utc_wifi_direct_unset_device_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_discovery_state_changed_cb_n",utc_wifi_direct_set_discovery_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_discovery_state_changed_cb_n",utc_wifi_direct_unset_discovery_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_connection_state_changed_cb_n",utc_wifi_direct_set_connection_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_connection_state_changed_cb_n",utc_wifi_direct_unset_connection_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_peer_info_connection_state_changed_cb_n",utc_wifi_direct_set_peer_info_connection_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_peer_info_connection_state_changed_cb_n",utc_wifi_direct_unset_peer_info_connection_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_service_state_changed_cb_n",utc_wifi_direct_set_service_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_service_state_changed_cb_n",utc_wifi_direct_unset_service_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_client_ip_address_assigned_cb_n",utc_wifi_direct_set_client_ip_address_assigned_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_client_ip_address_assigned_cb_n",utc_wifi_direct_unset_client_ip_address_assigned_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_peer_found_cb_n",utc_wifi_direct_set_peer_found_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_peer_found_cb_n",utc_wifi_direct_unset_peer_found_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_set_state_changed_cb_n",utc_wifi_direct_set_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_unset_state_changed_cb_n",utc_wifi_direct_unset_state_changed_cb_n,utc_wifi_direct_registration_negative_startup,utc_wifi_direct_registration_negative_cleanup},
	{"utc_wifi_direct_initialize_p",utc_wifi_direct_initialize_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_device_state_changed_cb_p",utc_wifi_direct_set_device_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_device_state_changed_cb_p",utc_wifi_direct_unset_device_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_discovery_state_changed_cb_p",utc_wifi_direct_set_discovery_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_discovery_state_changed_cb_p",utc_wifi_direct_unset_discovery_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_connection_state_changed_cb_p",utc_wifi_direct_set_connection_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_connection_state_changed_cb_p",utc_wifi_direct_unset_connection_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_peer_info_connection_state_changed_cb_p",utc_wifi_direct_set_peer_info_connection_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_peer_info_connection_state_changed_cb_p",utc_wifi_direct_unset_peer_info_connection_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_deinitialize_p",utc_wifi_direct_deinitialize_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_service_state_changed_cb_p",utc_wifi_direct_set_service_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_service_state_changed_cb_p",utc_wifi_direct_unset_service_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_client_ip_address_assigned_cb_p",utc_wifi_direct_set_client_ip_address_assigned_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_client_ip_address_assigned_cb_p",utc_wifi_direct_unset_client_ip_address_assigned_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_peer_found_cb_p",utc_wifi_direct_set_peer_found_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_peer_found_cb_p",utc_wifi_direct_unset_peer_found_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_set_state_changed_cb_p",utc_wifi_direct_set_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_unset_state_changed_cb_p",utc_wifi_direct_unset_state_changed_cb_p,utc_wifi_direct_registration_positive_startup,utc_wifi_direct_registration_positive_cleanup},
	{"utc_wifi_direct_register_service_n",utc_wifi_direct_register_service_n,utc_wifi_direct_service_negative_startup,utc_wifi_direct_service_negative_cleanup},
	{"utc_wifi_direct_deregister_service_n",utc_wifi_direct_deregister_service_n,utc_wifi_direct_service_negative_startup,utc_wifi_direct_service_negative_cleanup},
	{"utc_wifi_direct_start_service_discovery_n",utc_wifi_direct_start_service_discovery_n,utc_wifi_direct_service_negative_startup,utc_wifi_direct_service_negative_cleanup},
	{"utc_wifi_direct_cancel_service_discovery_n",utc_wifi_direct_cancel_service_discovery_n,utc_wifi_direct_service_negative_startup,utc_wifi_direct_service_negative_cleanup},
	{"utc_wifi_direct_register_service_p",utc_wifi_direct_register_service_p,utc_wifi_direct_service_positive_startup,utc_wifi_direct_service_positive_cleanup},
	{"utc_wifi_direct_deregister_service_p",utc_wifi_direct_deregister_service_p,utc_wifi_direct_service_positive_startup,utc_wifi_direct_service_positive_cleanup},
	{"utc_wifi_direct_start_service_discovery_p",utc_wifi_direct_start_service_discovery_p,utc_wifi_direct_service_positive_startup,utc_wifi_direct_service_positive_cleanup},
	{"utc_wifi_direct_cancel_service_discovery_p",utc_wifi_direct_cancel_service_discovery_p,utc_wifi_direct_service_positive_startup,utc_wifi_direct_service_positive_cleanup},
	{NULL, NULL}
};

#endif // __TCT_WIFI-DIRECT-NATIVE_H__
