//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_CAPI-MAPS-SERVICE-NATIVE_H__
#define __TCT_CAPI-MAPS-SERVICE-NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void ITs_maps_service_startup(void);
extern void ITs_maps_service_cleanup(void);
extern void ITs_maps_service_address_startup(void);
extern void ITs_maps_service_address_cleanup(void);
extern void ITs_maps_service_area_startup(void);
extern void ITs_maps_service_area_cleanup(void);
extern void ITs_maps_service_coordinates_startup(void);
extern void ITs_maps_service_coordinates_cleanup(void);
extern void ITs_maps_service_item_place_filter_startup(void);
extern void ITs_maps_service_item_place_filter_cleanup(void);
extern void ITs_maps_service_item_preference_startup(void);
extern void ITs_maps_service_item_preference_cleanup(void);
extern void ITs_maps_place_category_startup(void);
extern void ITs_maps_place_category_cleanup(void);
extern void ITs_maps_view_object_startup(void);
extern void ITs_maps_view_object_cleanup(void);
extern void ITs_maps_view_startup(void);
extern void ITs_maps_view_cleanup(void);
extern void ITs_maps_place_startup(void);
extern void ITs_maps_place_cleanup(void);
extern void ITs_maps_place_contact_startup(void);
extern void ITs_maps_place_contact_cleanup(void);
extern void ITs_maps_place_image_linkobj_startup(void);
extern void ITs_maps_place_image_linkobj_cleanup(void);
extern void ITs_maps_place_review_startup(void);
extern void ITs_maps_place_review_cleanup(void);
extern void ITs_maps_route_startup(void);
extern void ITs_maps_route_cleanup(void);
extern void ITs_maps_route_maneuver_startup(void);
extern void ITs_maps_route_maneuver_cleanup(void);

extern int ITc_maps_service_create_destroy_p(void);
extern int ITc_maps_service_set_get_preference_p(void);
extern int ITc_maps_service_set_get_provider_key_p(void);
extern int ITc_maps_service_provider_is_service_data_supported_p(void);
extern int ITc_maps_service_foreach_provider_p(void);
extern int ITc_maps_service_geocode_p(void);
extern int ITc_maps_service_cancel_request_p(void);
extern int ITc_maps_service_geocode_by_structured_address_p(void);
extern int ITc_maps_service_geocode_inside_area_p(void);
extern int ITc_maps_service_reverse_geocode_p(void);
extern int ITc_maps_service_search_place_p(void);
extern int ITc_maps_service_search_place_by_address_p(void);
extern int ITc_maps_service_search_place_by_area_p(void);
extern int ITc_maps_service_search_route_p(void);
extern int ITc_maps_service_search_route_waypoints_p(void);
extern int ITc_maps_service_multi_reverse_geocode_p(void);
extern int ITc_maps_service_search_place_list_p(void);
extern int ITc_maps_service_get_place_details_p(void);
extern int ITc_maps_service_request_user_consent_p(void);
extern int ITc_maps_address_create_destroy_p(void);
extern int ITc_maps_address_clone_p(void);
extern int ITc_maps_address_set_get_building_number_p(void);
extern int ITc_maps_address_set_get_city_p(void);
extern int ITc_maps_address_set_get_country_p(void);
extern int ITc_maps_address_set_get_country_code_p(void);
extern int ITc_maps_address_set_get_county_p(void);
extern int ITc_maps_address_set_get_district_p(void);
extern int ITc_maps_address_set_get_freetext_p(void);
extern int ITc_maps_address_set_get_postal_code_p(void);
extern int ITc_maps_address_set_get_state_p(void);
extern int ITc_maps_address_set_get_street_p(void);
extern int ITc_maps_address_list_create_destroy_p(void);
extern int ITc_maps_address_list_append_remove_p(void);
extern int ITc_maps_address_list_get_length_p(void);
extern int ITc_maps_address_list_foreach_p(void);
extern int ITc_maps_area_create_destroy_rectangle_p(void);
extern int ITc_maps_area_create_destroy_circle_p(void);
extern int ITc_maps_area_clone_p(void);
extern int ITc_maps_coordinates_create_destroy_p(void);
extern int ITc_maps_coordinates_clone_p(void);
extern int ITc_maps_coordinates_set_get_latitude_p(void);
extern int ITc_maps_coordinates_set_get_longitude_p(void);
extern int ITc_maps_coordinates_set_get_latitude_longitude_p(void);
extern int ITc_maps_coordinates_list_create_destroy_p(void);
extern int ITc_maps_coordinates_list_append_remove_p(void);
extern int ITc_maps_coordinates_list_get_length_p(void);
extern int ITc_maps_coordinates_list_foreach_p(void);
extern int ITc_maps_place_filter_create_destroy_p(void);
extern int ITc_maps_place_filter_clone_destroy_p(void);
extern int ITc_maps_place_filter_set_get_p(void);
extern int ITc_maps_place_filter_set_get_keyword_p(void);
extern int ITc_maps_place_filter_set_get_place_name_p(void);
extern int ITc_maps_place_filter_foreach_property_p(void);
extern int ITc_maps_place_filter_set_get_category_p(void);
extern int ITc_maps_place_filter_set_get_place_address_p(void);
extern int ITc_maps_preference_create_destroy_p(void);
extern int ITc_maps_preference_clone_destroy_p(void);
extern int ITc_maps_preference_set_get_distance_unit_p(void);
extern int ITc_maps_preference_set_get_country_code_p(void);
extern int ITc_maps_preference_set_get_language_p(void);
extern int ITc_maps_preference_set_get_max_results_p(void);
extern int ITc_maps_preference_set_get_route_feature_p(void);
extern int ITc_maps_preference_set_get_route_feature_weight_p(void);
extern int ITc_maps_preference_set_get_route_optimization_p(void);
extern int ITc_maps_preference_set_get_route_transport_mode_p(void);
extern int ITc_maps_preference_set_get_property_p(void);
extern int ITc_maps_preference_foreach_property_p(void);
extern int ITc_maps_preference_set_get_route_alternatives_enabled_p(void);
extern int ITc_maps_place_category_create_destroy_p(void);
extern int ITc_maps_place_category_clone_p(void);
extern int ITc_maps_place_category_set_get_id_p(void);
extern int ITc_maps_place_category_set_get_name_p(void);
extern int ITc_maps_place_category_set_get_url_p(void);
extern int ITc_maps_view_object_create_marker_destroy_p(void);
extern int ITc_maps_view_object_create_polyline_p(void);
extern int ITc_maps_view_object_create_polygon_p(void);
extern int ITc_maps_view_object_get_type_p(void);
extern int ITc_maps_view_object_set_get_visible_p(void);
extern int ITc_maps_view_object_polyline_foreach_point_p(void);
extern int ITc_maps_view_object_polyline_set_polyline_p(void);
extern int ITc_maps_view_object_polyline_set_get_color_p(void);
extern int ITc_maps_view_object_polyline_set_get_width_p(void);
extern int ITc_maps_view_object_polygon_set_polygon_p(void);
extern int ITc_maps_view_object_polygon_foreach_point_p(void);
extern int ITc_maps_view_object_polygon_set_get_fill_color_p(void);
extern int ITc_maps_view_object_marker_set_get_coordinates_p(void);
extern int ITc_maps_view_object_marker_resize_p(void);
extern int ITc_maps_view_object_marker_set_get_image_file_p(void);
extern int ITc_maps_view_object_marker_get_size_p(void);
extern int ITc_maps_view_object_marker_get_type_p(void);
extern int ITc_maps_view_object_marker_set_get_z_order_p(void);
extern int ITc_maps_view_object_create_overlay_p(void);
extern int ITc_maps_view_object_overlay_get_object_p(void);
extern int ITc_maps_view_object_overlay_set_get_coordinates_p(void);
extern int ITc_maps_view_object_overlay_set_get_min_zoom_level_p(void);
extern int ITc_maps_view_object_overlay_set_get_max_zoom_level_p(void);
extern int ITc_maps_view_create_destroy_p(void);
extern int ITc_maps_view_set_get_center_p(void);
extern int ITc_maps_view_set_get_zoom_level_p(void);
extern int ITc_maps_view_set_get_min_zoom_level_p(void);
extern int ITc_maps_view_set_get_max_zoom_level_p(void);
extern int ITc_maps_view_set_get_orientation_p(void);
extern int ITc_maps_view_screen_to_geolocation_p(void);
extern int ITc_maps_view_geolocation_to_screen_p(void);
extern int ITc_maps_view_set_get_type_p(void);
extern int ITc_maps_view_set_get_buildings_enabled_p(void);
extern int ITc_maps_view_set_get_language_p(void);
extern int ITc_maps_view_set_get_scalebar_enabled_p(void);
extern int ITc_maps_view_set_get_traffic_enabled_p(void);
extern int ITc_maps_view_get_viewport_p(void);
extern int ITc_maps_view_set_get_screen_location_p(void);
extern int ITc_maps_view_set_get_visibility_p(void);
extern int ITc_maps_view_set_get_gesture_enabled_p(void);
extern int ITc_maps_view_add_remove_object_p(void);
extern int ITc_maps_view_remove_all_objects_p(void);
extern int ITc_maps_view_foreach_object_p(void);
extern int ITc_maps_view_move_p(void);
extern int ITc_maps_view_resize_p(void);
extern int ITc_maps_view_set_get_public_transit_enabled_p(void);
extern int ITc_maps_view_set_unset_event_cb_p(void);
extern int ITc_maps_place_get_distance_p(void);
extern int ITc_maps_place_get_id_p(void);
extern int ITc_maps_place_get_location_p(void);
extern int ITc_maps_place_get_name_p(void);
extern int ITc_maps_place_get_rating_p(void);
extern int ITc_maps_place_rating_clone_destroy_p(void);
extern int ITc_maps_place_rating_get_average_p(void);
extern int ITc_maps_place_rating_get_count_p(void);
extern int ITc_maps_place_get_address_p(void);
extern int ITc_maps_place_get_related_link_p(void);
extern int ITc_maps_place_clone_p(void);
extern int ITc_maps_place_foreach_category_p(void);
extern int ITc_maps_place_foreach_contact_p(void);
extern int ITc_maps_place_contact_clone_destroy_p(void);
extern int ITc_maps_place_contact_get_label_p(void);
extern int ITc_maps_place_contact_get_type_p(void);
extern int ITc_maps_place_contact_get_value_p(void);
extern int ITc_maps_place_foreach_image_p(void);
extern int ITc_maps_place_image_clone_destroy_p(void);
extern int ITc_maps_place_image_get_ids_p(void);
extern int ITc_maps_place_image_get_media_p(void);
extern int ITc_maps_place_image_get_url_p(void);
extern int ITc_maps_place_image_get_user_link_p(void);
extern int ITc_maps_place_link_object_clone_destroy_p(void);
extern int ITc_maps_place_link_object_get_id_p(void);
extern int ITc_maps_place_link_object_get_name_p(void);
extern int ITc_maps_place_foreach_review_p(void);
extern int ITc_maps_place_review_clone_destroy_p(void);
extern int ITc_maps_place_review_get_date_p(void);
extern int ITc_maps_place_review_get_description_p(void);
extern int ITc_maps_place_review_get_language_p(void);
extern int ITc_maps_place_review_get_media_p(void);
extern int ITc_maps_place_review_get_rating_p(void);
extern int ITc_maps_place_review_get_title_p(void);
extern int ITc_maps_place_review_get_user_link_p(void);
extern int ITc_maps_route_clone_p(void);
extern int ITc_maps_route_foreach_path_p(void);
extern int ITc_maps_route_get_bounding_box_p(void);
extern int ITc_maps_route_get_destination_p(void);
extern int ITc_maps_route_get_distance_unit_p(void);
extern int ITc_maps_route_get_origin_p(void);
extern int ITc_maps_route_get_total_distance_p(void);
extern int ITc_maps_route_get_total_duration_p(void);
extern int ITc_maps_route_get_transport_mode_p(void);
extern int ITc_maps_route_foreach_segment_p(void);
extern int ITc_maps_route_segment_clone_destroy_p(void);
extern int ITc_maps_route_segment_get_destination_p(void);
extern int ITc_maps_route_segment_get_distance_p(void);
extern int ITc_maps_route_segment_get_duration_p(void);
extern int ITc_maps_route_segment_get_origin_p(void);
extern int ITc_maps_route_segment_foreach_path_p(void);
extern int ITc_maps_route_segment_foreach_maneuver_p(void);
extern int ITc_maps_route_maneuver_clone_destroy_p(void);
extern int ITc_maps_route_maneuver_get_direction_id_p(void);
extern int ITc_maps_route_maneuver_get_distance_to_next_instruction_p(void);
extern int ITc_maps_route_maneuver_get_instruction_text_p(void);
extern int ITc_maps_route_maneuver_get_position_p(void);
extern int ITc_maps_route_maneuver_get_time_to_next_instruction_p(void);
extern int ITc_maps_route_maneuver_get_turn_type_p(void);

testcase tc_array[] = {
	{"ITc_maps_service_create_destroy_p",ITc_maps_service_create_destroy_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_set_get_preference_p",ITc_maps_service_set_get_preference_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_set_get_provider_key_p",ITc_maps_service_set_get_provider_key_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_provider_is_service_data_supported_p",ITc_maps_service_provider_is_service_data_supported_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_foreach_provider_p",ITc_maps_service_foreach_provider_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_geocode_p",ITc_maps_service_geocode_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_cancel_request_p",ITc_maps_service_cancel_request_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_geocode_by_structured_address_p",ITc_maps_service_geocode_by_structured_address_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_geocode_inside_area_p",ITc_maps_service_geocode_inside_area_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_reverse_geocode_p",ITc_maps_service_reverse_geocode_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_place_p",ITc_maps_service_search_place_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_place_by_address_p",ITc_maps_service_search_place_by_address_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_place_by_area_p",ITc_maps_service_search_place_by_area_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_route_p",ITc_maps_service_search_route_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_route_waypoints_p",ITc_maps_service_search_route_waypoints_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_multi_reverse_geocode_p",ITc_maps_service_multi_reverse_geocode_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_search_place_list_p",ITc_maps_service_search_place_list_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_get_place_details_p",ITc_maps_service_get_place_details_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_service_request_user_consent_p",ITc_maps_service_request_user_consent_p,ITs_maps_service_startup,ITs_maps_service_cleanup},
	{"ITc_maps_address_create_destroy_p",ITc_maps_address_create_destroy_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_clone_p",ITc_maps_address_clone_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_building_number_p",ITc_maps_address_set_get_building_number_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_city_p",ITc_maps_address_set_get_city_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_country_p",ITc_maps_address_set_get_country_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_country_code_p",ITc_maps_address_set_get_country_code_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_county_p",ITc_maps_address_set_get_county_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_district_p",ITc_maps_address_set_get_district_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_freetext_p",ITc_maps_address_set_get_freetext_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_postal_code_p",ITc_maps_address_set_get_postal_code_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_state_p",ITc_maps_address_set_get_state_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_set_get_street_p",ITc_maps_address_set_get_street_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_list_create_destroy_p",ITc_maps_address_list_create_destroy_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_list_append_remove_p",ITc_maps_address_list_append_remove_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_list_get_length_p",ITc_maps_address_list_get_length_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_address_list_foreach_p",ITc_maps_address_list_foreach_p,ITs_maps_service_address_startup,ITs_maps_service_address_cleanup},
	{"ITc_maps_area_create_destroy_rectangle_p",ITc_maps_area_create_destroy_rectangle_p,ITs_maps_service_area_startup,ITs_maps_service_area_cleanup},
	{"ITc_maps_area_create_destroy_circle_p",ITc_maps_area_create_destroy_circle_p,ITs_maps_service_area_startup,ITs_maps_service_area_cleanup},
	{"ITc_maps_area_clone_p",ITc_maps_area_clone_p,ITs_maps_service_area_startup,ITs_maps_service_area_cleanup},
	{"ITc_maps_coordinates_create_destroy_p",ITc_maps_coordinates_create_destroy_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_clone_p",ITc_maps_coordinates_clone_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_set_get_latitude_p",ITc_maps_coordinates_set_get_latitude_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_set_get_longitude_p",ITc_maps_coordinates_set_get_longitude_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_set_get_latitude_longitude_p",ITc_maps_coordinates_set_get_latitude_longitude_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_list_create_destroy_p",ITc_maps_coordinates_list_create_destroy_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_list_append_remove_p",ITc_maps_coordinates_list_append_remove_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_list_get_length_p",ITc_maps_coordinates_list_get_length_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_coordinates_list_foreach_p",ITc_maps_coordinates_list_foreach_p,ITs_maps_service_coordinates_startup,ITs_maps_service_coordinates_cleanup},
	{"ITc_maps_place_filter_create_destroy_p",ITc_maps_place_filter_create_destroy_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_clone_destroy_p",ITc_maps_place_filter_clone_destroy_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_set_get_p",ITc_maps_place_filter_set_get_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_set_get_keyword_p",ITc_maps_place_filter_set_get_keyword_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_set_get_place_name_p",ITc_maps_place_filter_set_get_place_name_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_foreach_property_p",ITc_maps_place_filter_foreach_property_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_set_get_category_p",ITc_maps_place_filter_set_get_category_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_place_filter_set_get_place_address_p",ITc_maps_place_filter_set_get_place_address_p,ITs_maps_service_item_place_filter_startup,ITs_maps_service_item_place_filter_cleanup},
	{"ITc_maps_preference_create_destroy_p",ITc_maps_preference_create_destroy_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_clone_destroy_p",ITc_maps_preference_clone_destroy_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_distance_unit_p",ITc_maps_preference_set_get_distance_unit_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_country_code_p",ITc_maps_preference_set_get_country_code_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_language_p",ITc_maps_preference_set_get_language_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_max_results_p",ITc_maps_preference_set_get_max_results_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_route_feature_p",ITc_maps_preference_set_get_route_feature_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_route_feature_weight_p",ITc_maps_preference_set_get_route_feature_weight_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_route_optimization_p",ITc_maps_preference_set_get_route_optimization_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_route_transport_mode_p",ITc_maps_preference_set_get_route_transport_mode_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_property_p",ITc_maps_preference_set_get_property_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_foreach_property_p",ITc_maps_preference_foreach_property_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_preference_set_get_route_alternatives_enabled_p",ITc_maps_preference_set_get_route_alternatives_enabled_p,ITs_maps_service_item_preference_startup,ITs_maps_service_item_preference_cleanup},
	{"ITc_maps_place_category_create_destroy_p",ITc_maps_place_category_create_destroy_p,ITs_maps_place_category_startup,ITs_maps_place_category_cleanup},
	{"ITc_maps_place_category_clone_p",ITc_maps_place_category_clone_p,ITs_maps_place_category_startup,ITs_maps_place_category_cleanup},
	{"ITc_maps_place_category_set_get_id_p",ITc_maps_place_category_set_get_id_p,ITs_maps_place_category_startup,ITs_maps_place_category_cleanup},
	{"ITc_maps_place_category_set_get_name_p",ITc_maps_place_category_set_get_name_p,ITs_maps_place_category_startup,ITs_maps_place_category_cleanup},
	{"ITc_maps_place_category_set_get_url_p",ITc_maps_place_category_set_get_url_p,ITs_maps_place_category_startup,ITs_maps_place_category_cleanup},
	{"ITc_maps_view_object_create_marker_destroy_p",ITc_maps_view_object_create_marker_destroy_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_create_polyline_p",ITc_maps_view_object_create_polyline_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_create_polygon_p",ITc_maps_view_object_create_polygon_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_get_type_p",ITc_maps_view_object_get_type_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_set_get_visible_p",ITc_maps_view_object_set_get_visible_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polyline_foreach_point_p",ITc_maps_view_object_polyline_foreach_point_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polyline_set_polyline_p",ITc_maps_view_object_polyline_set_polyline_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polyline_set_get_color_p",ITc_maps_view_object_polyline_set_get_color_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polyline_set_get_width_p",ITc_maps_view_object_polyline_set_get_width_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polygon_set_polygon_p",ITc_maps_view_object_polygon_set_polygon_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polygon_foreach_point_p",ITc_maps_view_object_polygon_foreach_point_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_polygon_set_get_fill_color_p",ITc_maps_view_object_polygon_set_get_fill_color_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_set_get_coordinates_p",ITc_maps_view_object_marker_set_get_coordinates_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_resize_p",ITc_maps_view_object_marker_resize_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_set_get_image_file_p",ITc_maps_view_object_marker_set_get_image_file_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_get_size_p",ITc_maps_view_object_marker_get_size_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_get_type_p",ITc_maps_view_object_marker_get_type_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_marker_set_get_z_order_p",ITc_maps_view_object_marker_set_get_z_order_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_create_overlay_p",ITc_maps_view_object_create_overlay_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_overlay_get_object_p",ITc_maps_view_object_overlay_get_object_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_overlay_set_get_coordinates_p",ITc_maps_view_object_overlay_set_get_coordinates_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_overlay_set_get_min_zoom_level_p",ITc_maps_view_object_overlay_set_get_min_zoom_level_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_object_overlay_set_get_max_zoom_level_p",ITc_maps_view_object_overlay_set_get_max_zoom_level_p,ITs_maps_view_object_startup,ITs_maps_view_object_cleanup},
	{"ITc_maps_view_create_destroy_p",ITc_maps_view_create_destroy_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_center_p",ITc_maps_view_set_get_center_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_zoom_level_p",ITc_maps_view_set_get_zoom_level_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_min_zoom_level_p",ITc_maps_view_set_get_min_zoom_level_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_max_zoom_level_p",ITc_maps_view_set_get_max_zoom_level_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_orientation_p",ITc_maps_view_set_get_orientation_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_screen_to_geolocation_p",ITc_maps_view_screen_to_geolocation_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_geolocation_to_screen_p",ITc_maps_view_geolocation_to_screen_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_type_p",ITc_maps_view_set_get_type_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_buildings_enabled_p",ITc_maps_view_set_get_buildings_enabled_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_language_p",ITc_maps_view_set_get_language_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_scalebar_enabled_p",ITc_maps_view_set_get_scalebar_enabled_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_traffic_enabled_p",ITc_maps_view_set_get_traffic_enabled_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_get_viewport_p",ITc_maps_view_get_viewport_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_screen_location_p",ITc_maps_view_set_get_screen_location_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_visibility_p",ITc_maps_view_set_get_visibility_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_gesture_enabled_p",ITc_maps_view_set_get_gesture_enabled_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_add_remove_object_p",ITc_maps_view_add_remove_object_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_remove_all_objects_p",ITc_maps_view_remove_all_objects_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_foreach_object_p",ITc_maps_view_foreach_object_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_move_p",ITc_maps_view_move_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_resize_p",ITc_maps_view_resize_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_get_public_transit_enabled_p",ITc_maps_view_set_get_public_transit_enabled_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_view_set_unset_event_cb_p",ITc_maps_view_set_unset_event_cb_p,ITs_maps_view_startup,ITs_maps_view_cleanup},
	{"ITc_maps_place_get_distance_p",ITc_maps_place_get_distance_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_id_p",ITc_maps_place_get_id_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_location_p",ITc_maps_place_get_location_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_name_p",ITc_maps_place_get_name_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_rating_p",ITc_maps_place_get_rating_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_rating_clone_destroy_p",ITc_maps_place_rating_clone_destroy_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_rating_get_average_p",ITc_maps_place_rating_get_average_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_rating_get_count_p",ITc_maps_place_rating_get_count_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_address_p",ITc_maps_place_get_address_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_get_related_link_p",ITc_maps_place_get_related_link_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_clone_p",ITc_maps_place_clone_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_foreach_category_p",ITc_maps_place_foreach_category_p,ITs_maps_place_startup,ITs_maps_place_cleanup},
	{"ITc_maps_place_foreach_contact_p",ITc_maps_place_foreach_contact_p,ITs_maps_place_contact_startup,ITs_maps_place_contact_cleanup},
	{"ITc_maps_place_contact_clone_destroy_p",ITc_maps_place_contact_clone_destroy_p,ITs_maps_place_contact_startup,ITs_maps_place_contact_cleanup},
	{"ITc_maps_place_contact_get_label_p",ITc_maps_place_contact_get_label_p,ITs_maps_place_contact_startup,ITs_maps_place_contact_cleanup},
	{"ITc_maps_place_contact_get_type_p",ITc_maps_place_contact_get_type_p,ITs_maps_place_contact_startup,ITs_maps_place_contact_cleanup},
	{"ITc_maps_place_contact_get_value_p",ITc_maps_place_contact_get_value_p,ITs_maps_place_contact_startup,ITs_maps_place_contact_cleanup},
	{"ITc_maps_place_foreach_image_p",ITc_maps_place_foreach_image_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_image_clone_destroy_p",ITc_maps_place_image_clone_destroy_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_image_get_ids_p",ITc_maps_place_image_get_ids_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_image_get_media_p",ITc_maps_place_image_get_media_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_image_get_url_p",ITc_maps_place_image_get_url_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_image_get_user_link_p",ITc_maps_place_image_get_user_link_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_link_object_clone_destroy_p",ITc_maps_place_link_object_clone_destroy_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_link_object_get_id_p",ITc_maps_place_link_object_get_id_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_link_object_get_name_p",ITc_maps_place_link_object_get_name_p,ITs_maps_place_image_linkobj_startup,ITs_maps_place_image_linkobj_cleanup},
	{"ITc_maps_place_foreach_review_p",ITc_maps_place_foreach_review_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_clone_destroy_p",ITc_maps_place_review_clone_destroy_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_date_p",ITc_maps_place_review_get_date_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_description_p",ITc_maps_place_review_get_description_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_language_p",ITc_maps_place_review_get_language_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_media_p",ITc_maps_place_review_get_media_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_rating_p",ITc_maps_place_review_get_rating_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_title_p",ITc_maps_place_review_get_title_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_place_review_get_user_link_p",ITc_maps_place_review_get_user_link_p,ITs_maps_place_review_startup,ITs_maps_place_review_cleanup},
	{"ITc_maps_route_clone_p",ITc_maps_route_clone_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_foreach_path_p",ITc_maps_route_foreach_path_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_bounding_box_p",ITc_maps_route_get_bounding_box_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_destination_p",ITc_maps_route_get_destination_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_distance_unit_p",ITc_maps_route_get_distance_unit_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_origin_p",ITc_maps_route_get_origin_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_total_distance_p",ITc_maps_route_get_total_distance_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_total_duration_p",ITc_maps_route_get_total_duration_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_get_transport_mode_p",ITc_maps_route_get_transport_mode_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_foreach_segment_p",ITc_maps_route_foreach_segment_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_clone_destroy_p",ITc_maps_route_segment_clone_destroy_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_get_destination_p",ITc_maps_route_segment_get_destination_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_get_distance_p",ITc_maps_route_segment_get_distance_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_get_duration_p",ITc_maps_route_segment_get_duration_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_get_origin_p",ITc_maps_route_segment_get_origin_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_foreach_path_p",ITc_maps_route_segment_foreach_path_p,ITs_maps_route_startup,ITs_maps_route_cleanup},
	{"ITc_maps_route_segment_foreach_maneuver_p",ITc_maps_route_segment_foreach_maneuver_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_clone_destroy_p",ITc_maps_route_maneuver_clone_destroy_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_direction_id_p",ITc_maps_route_maneuver_get_direction_id_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_distance_to_next_instruction_p",ITc_maps_route_maneuver_get_distance_to_next_instruction_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_instruction_text_p",ITc_maps_route_maneuver_get_instruction_text_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_position_p",ITc_maps_route_maneuver_get_position_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_time_to_next_instruction_p",ITc_maps_route_maneuver_get_time_to_next_instruction_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{"ITc_maps_route_maneuver_get_turn_type_p",ITc_maps_route_maneuver_get_turn_type_p,ITs_maps_route_maneuver_startup,ITs_maps_route_maneuver_cleanup},
	{NULL, NULL}
};

#endif // __TCT_CAPI-MAPS-SERVICE-NATIVE_H__
