//
// Copyright (c) 2014 Samsung Electronics Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef __TCT_SYSTEM_SETTINGS_NATIVE_H__
#define __TCT_SYSTEM_SETTINGS_NATIVE_H__

#include "testcase.h"
#include "tct_common.h"

extern void utc_system_settings_startup(void);
extern void utc_system_settings_cleanup(void);

extern int utc_system_settings_get_value_string_p1(void);
extern int utc_system_settings_get_value_string_p2(void);
extern int utc_system_settings_get_value_string_p3(void);
extern int utc_system_settings_get_value_string_p4(void);
extern int utc_system_settings_get_value_string_p5(void);
extern int utc_system_settings_get_value_string_p11(void);
extern int utc_system_settings_get_value_string_p7(void);
extern int utc_system_settings_get_value_string_p6(void);
extern int utc_system_settings_get_value_string_p10(void);
extern int utc_system_settings_get_value_string_p8(void);
extern int utc_system_settings_get_value_string_p9(void);
extern int utc_system_settings_get_value_string_n(void);
extern int utc_system_settings_get_value_bool_p1(void);
extern int utc_system_settings_get_value_bool_p2(void);
extern int utc_system_settings_get_value_bool_p3(void);
extern int utc_system_settings_get_value_bool_p4(void);
extern int utc_system_settings_get_value_bool_p5(void);
extern int utc_system_settings_get_value_bool_p6(void);
extern int utc_system_settings_get_value_bool_p7(void);
extern int utc_system_settings_get_value_bool_p8(void);
extern int utc_system_settings_get_value_bool_p9(void);
extern int utc_system_settings_get_value_bool_p10(void);
extern int utc_system_settings_get_value_bool_n(void);
extern int utc_system_settings_get_value_int_p1(void);
extern int utc_system_settings_get_value_int_p2(void);
extern int utc_system_settings_get_value_n(void);
extern int utc_system_settings_get_value_int_p3(void);
extern int utc_system_settings_get_value_bool_p11(void);
extern int utc_system_settings_get_value_bool_p12(void);
extern int utc_system_settings_get_value_bool_p13(void);
extern int utc_system_settings_get_value_bool_p14(void);
extern int utc_system_settings_get_value_bool_p15(void);
extern int utc_system_settings_get_value_bool_p16(void);
extern int utc_system_settings_get_value_bool_p17(void);
extern int utc_system_settings_get_value_bool_p18(void);
extern int utc_system_settings_set_changed_cb_p1(void);
extern int utc_system_settings_unset_changed_cb_p1(void);
extern int utc_system_settings_set_changed_cb_p2(void);
extern int utc_system_settings_unset_changed_cb_p2(void);
extern int utc_system_settings_set_changed_cb_p3(void);
extern int utc_system_settings_unset_changed_cb_p3(void);
extern int utc_system_settings_set_changed_cb_p4(void);
extern int utc_system_settings_LOCK_SCREEN_unset_changed_cb_p(void);
extern int utc_system_settings_set_changed_cb_p5(void);
extern int utc_system_settings_unset_changed_cb_p4(void);
extern int utc_system_settings_set_changed_cb_p6(void);
extern int utc_system_settings_unset_changed_cb_p5(void);
extern int utc_system_settings_set_changed_cb_p7(void);
extern int utc_system_settings_unset_changed_cb_p6(void);
extern int utc_system_settings_set_changed_cb_p8(void);
extern int utc_system_settings_unset_changed_cb_p7(void);
extern int utc_system_settings_set_changed_cb_p9(void);
extern int utc_system_settings_unset_changed_cb_p8(void);
extern int utc_system_settings_set_changed_cb_p10(void);
extern int utc_system_settings_unset_changed_cb_p9(void);
extern int utc_system_settings_set_changed_cb_p11(void);
extern int utc_system_settings_unset_changed_cb_p10(void);
extern int utc_system_settings_set_changed_cb_p12(void);
extern int utc_system_settings_unset_changed_cb_p11(void);
extern int utc_system_settings_set_changed_cb_p13(void);
extern int utc_system_settings_unset_changed_cb_p12(void);
extern int utc_system_settings_set_changed_cb_p14(void);
extern int utc_system_settings_unset_changed_cb_p13(void);
extern int utc_system_settings_set_changed_cb_p15(void);
extern int utc_system_settings_unset_changed_cb_p14(void);
extern int utc_system_settings_set_changed_cb_p16(void);
extern int utc_system_settings_unset_changed_cb_p15(void);
extern int utc_system_settings_set_changed_cb_p17(void);
extern int utc_system_settings_unset_changed_cb_p16(void);
extern int utc_system_settings_set_changed_cb_p18(void);
extern int utc_system_settings_unset_changed_cb_p17(void);
extern int utc_system_settings_set_changed_cb_p19(void);
extern int utc_system_settings_unset_changed_cb_p18(void);
extern int utc_system_settings_set_changed_cb_p20(void);
extern int utc_system_settings_unset_changed_cb_p19(void);
extern int utc_system_settings_set_changed_cb_p21(void);
extern int utc_system_settings_unset_changed_cb_p20(void);
extern int utc_system_settings_set_changed_cb_p22(void);
extern int utc_system_settings_unset_changed_cb_p21(void);
extern int utc_system_settings_set_changed_cb_p23(void);
extern int utc_system_settings_unset_changed_cb_p22(void);
extern int utc_system_settings_set_changed_cb_p24(void);
extern int utc_system_settings_unset_changed_cb_p23(void);
extern int utc_system_settings_set_changed_cb_p25(void);
extern int utc_system_settings_unset_changed_cb_p24(void);
extern int utc_system_settings_set_changed_cb_p27(void);
extern int utc_system_settings_unset_changed_cb_p26(void);
extern int utc_system_settings_set_changed_cb_p29(void);
extern int utc_system_settings_unset_changed_cb_p28(void);
extern int utc_system_settings_set_changed_cb_p31(void);
extern int utc_system_settings_unset_changed_cb_p30(void);
extern int utc_system_settings_set_changed_cb_p33(void);
extern int utc_system_settings_unset_changed_cb_p32(void);
extern int utc_system_settings_set_changed_cb_p35(void);
extern int utc_system_settings_unset_changed_cb_p34(void);
extern int utc_system_settings_set_changed_cb_p37(void);
extern int utc_system_settings_unset_changed_cb_p36(void);
extern int utc_system_settings_set_changed_cb_p39(void);
extern int utc_system_settings_unset_changed_cb_p38(void);
extern int utc_system_settings_set_changed_cb_p41(void);
extern int utc_system_settings_unset_changed_cb_p40(void);
extern int utc_system_settings_set_changed_cb_p43(void);
extern int utc_system_settings_unset_changed_cb_p42(void);
extern int utc_system_settings_set_changed_cb_p45(void);
extern int utc_system_settings_unset_changed_cb_p44(void);
extern int utc_system_settings_set_changed_cb_p47(void);
extern int utc_system_settings_unset_changed_cb_p46(void);
extern int utc_system_settings_add_remove_changed_cb_p1(void);

testcase tc_array[] = {
	{"utc_system_settings_get_value_string_p1",utc_system_settings_get_value_string_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p2",utc_system_settings_get_value_string_p2,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p3",utc_system_settings_get_value_string_p3,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p4",utc_system_settings_get_value_string_p4,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p5",utc_system_settings_get_value_string_p5,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p11",utc_system_settings_get_value_string_p11,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p7",utc_system_settings_get_value_string_p7,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p6",utc_system_settings_get_value_string_p6,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p10",utc_system_settings_get_value_string_p10,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p8",utc_system_settings_get_value_string_p8,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_p9",utc_system_settings_get_value_string_p9,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_string_n",utc_system_settings_get_value_string_n,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p1",utc_system_settings_get_value_bool_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p2",utc_system_settings_get_value_bool_p2,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p3",utc_system_settings_get_value_bool_p3,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p4",utc_system_settings_get_value_bool_p4,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p5",utc_system_settings_get_value_bool_p5,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p6",utc_system_settings_get_value_bool_p6,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p7",utc_system_settings_get_value_bool_p7,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p8",utc_system_settings_get_value_bool_p8,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p9",utc_system_settings_get_value_bool_p9,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p10",utc_system_settings_get_value_bool_p10,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_n",utc_system_settings_get_value_bool_n,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_int_p1",utc_system_settings_get_value_int_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_int_p2",utc_system_settings_get_value_int_p2,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_n",utc_system_settings_get_value_n,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_int_p3",utc_system_settings_get_value_int_p3,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p11",utc_system_settings_get_value_bool_p11,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p12",utc_system_settings_get_value_bool_p12,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p13",utc_system_settings_get_value_bool_p13,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p14",utc_system_settings_get_value_bool_p14,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p15",utc_system_settings_get_value_bool_p15,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p16",utc_system_settings_get_value_bool_p16,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p17",utc_system_settings_get_value_bool_p17,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_get_value_bool_p18",utc_system_settings_get_value_bool_p18,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p1",utc_system_settings_set_changed_cb_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p1",utc_system_settings_unset_changed_cb_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p2",utc_system_settings_set_changed_cb_p2,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p2",utc_system_settings_unset_changed_cb_p2,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p3",utc_system_settings_set_changed_cb_p3,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p3",utc_system_settings_unset_changed_cb_p3,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p4",utc_system_settings_set_changed_cb_p4,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_LOCK_SCREEN_unset_changed_cb_p",utc_system_settings_LOCK_SCREEN_unset_changed_cb_p,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p5",utc_system_settings_set_changed_cb_p5,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p4",utc_system_settings_unset_changed_cb_p4,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p6",utc_system_settings_set_changed_cb_p6,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p5",utc_system_settings_unset_changed_cb_p5,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p7",utc_system_settings_set_changed_cb_p7,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p6",utc_system_settings_unset_changed_cb_p6,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p8",utc_system_settings_set_changed_cb_p8,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p7",utc_system_settings_unset_changed_cb_p7,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p9",utc_system_settings_set_changed_cb_p9,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p8",utc_system_settings_unset_changed_cb_p8,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p10",utc_system_settings_set_changed_cb_p10,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p9",utc_system_settings_unset_changed_cb_p9,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p11",utc_system_settings_set_changed_cb_p11,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p10",utc_system_settings_unset_changed_cb_p10,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p12",utc_system_settings_set_changed_cb_p12,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p11",utc_system_settings_unset_changed_cb_p11,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p13",utc_system_settings_set_changed_cb_p13,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p12",utc_system_settings_unset_changed_cb_p12,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p14",utc_system_settings_set_changed_cb_p14,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p13",utc_system_settings_unset_changed_cb_p13,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p15",utc_system_settings_set_changed_cb_p15,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p14",utc_system_settings_unset_changed_cb_p14,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p16",utc_system_settings_set_changed_cb_p16,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p15",utc_system_settings_unset_changed_cb_p15,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p17",utc_system_settings_set_changed_cb_p17,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p16",utc_system_settings_unset_changed_cb_p16,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p18",utc_system_settings_set_changed_cb_p18,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p17",utc_system_settings_unset_changed_cb_p17,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p19",utc_system_settings_set_changed_cb_p19,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p18",utc_system_settings_unset_changed_cb_p18,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p20",utc_system_settings_set_changed_cb_p20,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p19",utc_system_settings_unset_changed_cb_p19,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p21",utc_system_settings_set_changed_cb_p21,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p20",utc_system_settings_unset_changed_cb_p20,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p22",utc_system_settings_set_changed_cb_p22,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p21",utc_system_settings_unset_changed_cb_p21,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p23",utc_system_settings_set_changed_cb_p23,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p22",utc_system_settings_unset_changed_cb_p22,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p24",utc_system_settings_set_changed_cb_p24,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p23",utc_system_settings_unset_changed_cb_p23,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p25",utc_system_settings_set_changed_cb_p25,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p24",utc_system_settings_unset_changed_cb_p24,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p27",utc_system_settings_set_changed_cb_p27,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p26",utc_system_settings_unset_changed_cb_p26,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p29",utc_system_settings_set_changed_cb_p29,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p28",utc_system_settings_unset_changed_cb_p28,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p31",utc_system_settings_set_changed_cb_p31,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p30",utc_system_settings_unset_changed_cb_p30,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p33",utc_system_settings_set_changed_cb_p33,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p32",utc_system_settings_unset_changed_cb_p32,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p35",utc_system_settings_set_changed_cb_p35,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p34",utc_system_settings_unset_changed_cb_p34,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p37",utc_system_settings_set_changed_cb_p37,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p36",utc_system_settings_unset_changed_cb_p36,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p39",utc_system_settings_set_changed_cb_p39,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p38",utc_system_settings_unset_changed_cb_p38,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p41",utc_system_settings_set_changed_cb_p41,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p40",utc_system_settings_unset_changed_cb_p40,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p43",utc_system_settings_set_changed_cb_p43,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p42",utc_system_settings_unset_changed_cb_p42,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p45",utc_system_settings_set_changed_cb_p45,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p44",utc_system_settings_unset_changed_cb_p44,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_set_changed_cb_p47",utc_system_settings_set_changed_cb_p47,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_unset_changed_cb_p46",utc_system_settings_unset_changed_cb_p46,utc_system_settings_startup,utc_system_settings_cleanup},
	{"utc_system_settings_add_remove_changed_cb_p1",utc_system_settings_add_remove_changed_cb_p1,utc_system_settings_startup,utc_system_settings_cleanup},
	{NULL, NULL}
};

#endif // __TCT_SYSTEM_SETTINGS_NATIVE_H__
